### ISSUE TITLE
add `plugin` and `module` entities to the alarm

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#10014]
##### Feature idea summary

[Chart definition](https://learn.netdata.cloud/docs/agent/collectors/plugins.d#the-output-of-the-plugin) has optional `plugin` and `module` fields. It would be nice to add these entities to alarms.

This will help with collectors migration. When we rewrite a collector we keep charts definitions the same, the only difference is `plugin` and `module` fields. 

My usecase is `warn` level alarms for deprecated collectors.

##### Expected behavior

- Alarm has `plugin` and `module`entities.
- `plugin` and `module` support simple patterns.

**Comment by thiagoftsm** [comment]
@ilyam8 when a chart is created the optional parameters are given to it, and the simplest road to attach an alarm based on `plugin` or `module` would be allowing the users to set these values using the alarm line [on](https://learn.netdata.cloud/docs/agent/health/reference#alarm-line-on). To do this we would need to change the next function 

https://github.com/netdata/netdata/blob/fa45006179f07ecd7f6dca6088d0336e4407c895/database/rrdcalc.c#L111

to also compare `module` and  `plugin` with the chart name, because direct comparison with `module` or `plugin` would not be desirable. This comparison will be done with `rc->rrdset->plugin_name`.

On the `health` side, we would need to parse the `on` line instead only duplicate it 

https://github.com/netdata/netdata/blob/fa45006179f07ecd7f6dca6088d0336e4407c895/health/health_config.c#L690

because `plugin` and `module` would also be optional here. 

Before to move forward with this, we need to define how `plugin` or `module` will be added here.

**Comment by ilyam8** [comment]
> plugin or module would be allowing the users to set these values using the alarm line on

I dont get why you suggest to use `on`. Imo it should work same as `families`.

**Comment by thiagoftsm** [comment]
> I dont get why you suggest to use `on`. Imo it should work same as `families`.

I had an initial concern to break backward compatibility if we were storing `RRDCALC` inside the database as we do with `RRDSET`and `RRDHOST`, but considering that we are not, we do not have any problems to bring this two new options.

**Comment by ilyam8** [comment]
@thiagoftsm i added to the OP `Expected behavior` - should support simple patterns (so we can set list of modules).
