### ISSUE TITLE
Graphical glitches

### ISSUE THREAD

**Issue by stemy2** [netdata/netdata#10113]
##### Bug report summary
Some indicators have an ugly graphical glitch.

##### OS / Environment

```
4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux
Yunohost based on Debian 10.6
```

##### Netdata version

 1.22.1 (latest version available on YNH)

![Screenshot_20201021_180354](https://user-images.githubusercontent.com/22192600/96747372-b87bdc00-13b7-11eb-944f-4060ee786cf8.png)

**Comment by thiagoftsm** [comment]
Hello @stemy2 ,

I am not sure what is  a `YNH`, but Netdata released the version 1.26 few days ago, and our official repositories are listed [here](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/packages). 

I never saw images like you are showing here, so it is possible that there was a problem with the packages that you are using.

Best regards!

**Comment by stemy2** [comment]
YNH = yunohost, an OS based on debian for selfhosting, it uses its own repository with specifically packaged apps.

**Comment by thiagoftsm** [comment]
> YNH = yunohost, an OS based on debian for selfhosting, it uses its own repository with specifically packaged apps.

Thank you to explain me.

I was reading the release notes of the version [1.22](https://github.com/netdata/netdata/releases/tag/v1.22.0), and I saw that this was the version we made the New cloud  available, since April we made a lot of improvements and it is possible that when the distribution updates their package, you will have better images.

Another possibility that you could test without to do any modification inside your configuration files, it is to install the [static binary](https://github.com/netdata/netdata/releases/download/v1.26.0/netdata-v1.26.0.gz.run) it will install Netdata  at `/opt/netdata` and I believe this is not the same directory used by the distribution. You could stop the distribution binary and give a try for the static to confirm that the problem is not present with it.

Best regards!

**Comment by jacekkolasa** [comment]
Hi @stemy2! Can you please go to https://london3.my-netdata.io/ on the same machine and check if it looks similar to your case?

**Comment by stemy2** [comment]
> Hi @stemy2! Can you please go to https://london3.my-netdata.io/ on the same machine and check if it looks similar to your case?

Yup, same problem.

**Comment by jacekkolasa** [comment]
thanks! This issue is very surprising, i haven't seen it yet and those charts are here for few years already. Can you share your browser and version nr?

Can you also check http://rendro.github.io/easy-pie-chart/ page and look if you see similar artefacts?

**Comment by stemy2** [comment]
Apparently, it happens only on firefox based browser. I tested with:
-Firefox 78.7.0
-Tor Browser 10.0.8
-Chromium 87.0.4280.141
-Konqueror 5.0.97

**Comment by BoBeR182** [comment]
I have the same issue on Firefox 86.0.1

**Comment by stemy2** [comment]
I found the origin of the problem.

I'm using an add-on to block canvas to resist to fingerprinting. If i unblock it, the artefacts are vanished.

**Comment by ilyam8** [comment]
@stemy2 nice you've found the problem. And thx for sharing the solution!

**Comment by mojo-it** [comment]
only and still happens in Firefox. Workaround: -> about:config -> look for "privacy.resistFingerprinting" -> set to "false" -> reload ND
