### ISSUE TITLE
Unable to install netdata on Raspbian 

### ISSUE THREAD

**Issue by dongvan9** [netdata/netdata#10131]
##### Question summary
Unable to install netdata on Raspbian

I want to install netdata and add my node to the cloud https://app.netdata.cloud/
Previously, I have installed it via the apt but it didn't work. I have remove the application, delete /etc/netdata and  give a try with the script and it was not working either.
Can you advise how to fix this? Thank you!

```
root@raspberrypi:~# bash <(curl -Ss https://my-netdata.io/kickstart.sh)
 --- Found existing install of Netdata under: / ---
 --- Existing install appears to be handled manually or through the system package manager. ---
 ABORTED  Existing installation detected which cannot be safely updated by this script, refusing to continue.
```

##### OS / Environment
`Linux raspberrypi 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux`

**Comment by stelfrag** [comment]
Related to #10128

**Comment by OdysLam** [comment]
Hey @dongvan9, 

Welcome to our community and we are super sorry for encountering this bug. We are working towards fixing this. 

Thank you for bearing with us 💪

**Comment by dongvan9** [comment]
Hey @OdysLam,

Thanks for the response. I have another Orange Pi 2+ and would love to have netdata installed but it doesn't work either. Should I raise a new topic or I can update it here as well?

**Comment by OdysLam** [comment]
It seems that there are a number of connected issues. Please bear with us as we try to pinpoint the origin @dongvan9 

In the meantime can you follow all the procedures that are required to remove a package in debian (e.g by following this [guide](https://linuxhint.com/uninstall-debian-packages/)).

**Comment by Ferroin** [comment]
Most likely, uninstalling did not properly remove things (or the package got reinstalled somehow). The way the check that is failing here works, it looks for a copy of the `netdata` binary in `$PATH` (you can manually do the same check using `command -v netdata`) to find existing installs, and if it finds one tries to figure out the type of install and decide what to do based on that. The particular message you are seeing indicates that it a copy of `netdata` in either `/bin` or `/usr/bin`, and from that could not figure out what type of install is present.

If you’re _absolutely_ certain that you do not have an existing installation of netdata, you can add `--allow-duplicate-install` to the installer command you are using and it will continue as if there was no existing install instead of stopping when it fails to detect the install type.

**Comment by OdysLam** [comment]
So is this expected behaviour @Ferroin ? What would be the best-case scenario in the above use-case and what happened here? 

I am trying to figure out how to log this feedback.

**Comment by Ferroin** [comment]
It’s expected if the previous install didn’t get correctly cleaned up. I’m not sure there is a best-case scenario for handling this, but we can’t reliably detect the difference between a working existing install handled through some install method we don’t support and a failed/incomplete uninstall, and we can’t safely install over top of an existing install.

**Comment by OdysLam** [comment]
@Ferroin Could we have a script that nukes the system for any mention of Netdata and uninstall it so we can start from square-1?

**Comment by Ferroin** [comment]
No, not really, as that just moves the location we would be dealing with the issues and risking breaking a user’s system.

The correct fix here is to get proper support in various distribution’s package managers so that users don’t _need_ to use our installer unless they want nightly versions, that way the default install approach that any sane sysadmin takes on a Linux system (namely, install it through the distro’s package manager) will just work.

**Comment by Ferroin** [comment]
IOW, we have an XY problem here, the real problem is that our support from distributions is crappy, so when users go to install there first they have issues and then go find our installer and then just run it without uninstalling any existing copy of Netdata (that’s the whole reason we do these checks in fact). This, in turn, is causing these problems. If we solve that primary problem (lack of good support from distros), this one will cease to be a major issue for us.

**Comment by dongvan9** [comment]
Hi guys,
Thanks for the update. I have found that netdata still resides at /usr/bin. After apt-get –purge & apt-get autoremove –purge, I am able to install the application with the script.
There were still some error message but netdata runs at the end. Should I pay attention to it?

```
[/tmp/netdata-kickstart-5fZ9bpFeTg/netdata-v1.26.0-64-gbf8e2e0a]# systemctl enable netdata
Synchronizing state of netdata.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable netdata
Failed to enable unit: Unit file /etc/systemd/system/netdata.service is masked.
 FAILED

 FAILED  Cannot install netdata init service.

 --- Restarting netdata instance ---

Stopping all netdata threads
[/tmp/netdata-kickstart-5fZ9bpFeTg/netdata-v1.26.0-64-gbf8e2e0a]# stop_all_netdata
 OK

Starting netdata using command 'systemctl start netdata'
[/tmp/netdata-kickstart-5fZ9bpFeTg/netdata-v1.26.0-64-gbf8e2e0a]# systemctl start netdata
Failed to start netdata.service: Unit netdata.service is masked.
 FAILED

Attempting another netdata start using command 'systemctl start netdata'
[/tmp/netdata-kickstart-5fZ9bpFeTg/netdata-v1.26.0-64-gbf8e2e0a]# systemctl start netdata
Failed to start netdata.service: Unit netdata.service is masked.
 FAILED

Netdata service still not started, attempting another forced restart by running '/usr/sbin/netdata '
[/tmp/netdata-kickstart-5fZ9bpFeTg/netdata-v1.26.0-64-gbf8e2e0a]# stop_all_netdata
 OK

[/tmp/netdata-kickstart-5fZ9bpFeTg/netdata-v1.26.0-64-gbf8e2e0a]# /usr/sbin/netdata
2020-10-27 02:26:15: netdata INFO  : MAIN : CONFIG: cannot load cloud config '/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults.
2020-10-27 02:26:15: netdata INFO  : MAIN : Found 0 legacy dbengines, setting multidb diskspace to 256MB
2020-10-27 02:26:15: netdata INFO  : MAIN : Created file '/var/lib/netdata/dbengine_multihost_size' to store the computed value
2020-10-27 02:26:15: netdata INFO  : MAIN : SIGNAL: Not enabling reaper
 OK

 OK  netdata started!
```

**Comment by Ferroin** [comment]
@dongvan9 Given the errors, you will probably not see Netdata start automatically on system boot. You can fix that by running `systemctl unmask netdata.service` as root. Other than that, everything should work fine.

**Comment by dongvan9** [comment]
Thank you, @Ferroin . With the command, it is working fine after reboot. The issue is resolved and I will close it.
Thanks for the support!

**Comment by Ferroin** [comment]
@OdysLam Quick rundown of the primary points that came up in discussion here as requested:

* We cannot safely install over top of an existing install that was not created by our installer, so our installer bails if it sees evidence of such an install.
* Incomplete uninstalls can sometimes leave behind such evidence, but we can’t really differentiate between that and an actual working install created by a source other than our installer.
* We keep trying to solve these issues by improving our installer, but we would be far better served by improving support from major Linux distributions because that will give better overall UX while still mostly solving these issues.
