### ISSUE TITLE
More generic overwiew in standard dashboard

### ISSUE THREAD

**Issue by KickerTom** [netdata/netdata#10177]
##### Feature idea summary
I am learning to customize the standard dashboard, it's amazing how flexible you made it, congratulations. There is only one thing missing (or that I haven't discovered yet :-) ), and that's a bit more flexible overview at the top of the page. I love how the standard dashboard puts important values in gauges at the top, but as far as I know, it is possible to add only values from the first section. Other sections can have their own overview, but they can't contribute to the top of the page.
So, my proposal is to add another section to dashboard_info.js (and it's customizations) describing global overview. There could be a _title_, some descriptive text (_info_), and _heads_ section as in context to describe charts to be rendered at the top of the page, before any previous section.
Or, there could be a new keyword in the context section, e.g. _globalheads_ for this purpose. Less generic, but probably easier to implement.
Or, there could be a notion of "virtual sections", which could be added anywhere and contain any chart. Even more generic than first proposal, but probably overkill and hard to implement. 

I am willing to try my luck implementing this (if need be, as I am far from being a js programmer :-) ), but I would like to discuss first, to know what are others thinking about this idea.

**Comment by jacekkolasa** [comment]
@KickerTom thanks for those ideas!
That feature would be good to have, but we need first to rethink current configuration process. Dashboard_info.js is for some users hard to use and there are problems with propagating custom configuration to Netdata Cloud (because it's javascript, it cannot be imported there due to XSS security reasons). Maybe we will need to transform it to DSL, or we will have a UI for the feature you described, so we could just "pin" charts to the top.

**Comment by manos-saratsis** [comment]
@KickerTom thx for the feedback. We shall offer more customization options in the future and we will track this with an internal ticket. Closing this.
