### ISSUE TITLE
Oracle monitoring reports wrong data

### ISSUE THREAD

**Issue by jurgenhaas** [netdata/netdata#10196]
##### Bug report summary

Started to configure Oracle monitoring today and got confused about the reported metrics, so I think this needs to be reported. When I use this SQL in my Oracle database

```
set colsep '|'
set echo off
set feedback off
set linesize 1000
set pagesize 0
set sqlprompt ''
set trimspool on
set headsep off

select nvl(b.tablespace_name,
nvl(a.tablespace_name,'UNKNOWN'))
tablespace_name,
kbytes_alloc kbytes,
kbytes_alloc-nvl(kbytes_free,0)
size_alloc_bytes,
round(((kbytes_alloc-nvl(kbytes_free,0))/ kbytes_alloc)*200) used_chart,
to_char(((kbytes_alloc-nvl(kbytes_free,0))/ kbytes_alloc)*100,
'999G999G999G999G999G999G990D00') ||'%' used,
data_files
from ( select sum(bytes)/1024/1024 Kbytes_free,
max(bytes)/1024/1024 largest,
tablespace_name
from  sys.dba_free_space
group by tablespace_name ) a,
( select sum(bytes)/1024/1024 Kbytes_alloc,
tablespace_name,
count(*) data_files
from sys.dba_data_files
group by tablespace_name ) b
where a.tablespace_name (+) = b.tablespace_name;
```

I get the sizes reported like this:

```
SYSTEM			      |       700|	  690.4375|	  197|				98.63%| 	1
SYSAUX			      |      1030|	   965.375|	  187|				93.73%| 	1
UNDOTBS1		      |      2420|	     30.25|	    3|				 1.25%| 	1
USERS			      |      57.5|	   53.8125|	  187|				93.59%| 	1
```

But the netdata plugin reports much lower values:

![Screenshot from 2020-11-04 14-28-51](https://user-images.githubusercontent.com/1475675/98117494-26410100-1eaa-11eb-8504-3f9fca592818.png)

No idea where the difference is coming from. Can you help me with this?

##### OS / Environment

Ubuntu 18.04 LTS

##### Netdata version

1.26.0 

##### Component Name

Oracle

**Comment by ilyam8** [comment]
Hi @jurgenhaas 

I see

- the query

https://github.com/netdata/netdata/blob/3f70299e3521ac4708bd6f47abbf46f70e8692e8/collectors/python.d.plugin/oracledb/oracledb.chart.py#L186-L195

- query result

https://github.com/netdata/netdata/blob/3f70299e3521ac4708bd6f47abbf46f70e8692e8/collectors/python.d.plugin/oracledb/oracledb.chart.py#L581-L584

https://github.com/netdata/netdata/blob/3f70299e3521ac4708bd6f47abbf46f70e8692e8/collectors/python.d.plugin/oracledb/oracledb.chart.py#L589

- Chart dimensions

https://github.com/netdata/netdata/blob/3f70299e3521ac4708bd6f47abbf46f70e8692e8/collectors/python.d.plugin/oracledb/oracledb.chart.py#L689-L713

units `KiB`, so we `/1024 * 1000`, `* 1000` is because we multiply return values by `1000` (they are floats, nd can't into floats)

https://github.com/netdata/netdata/blob/3f70299e3521ac4708bd6f47abbf46f70e8692e8/collectors/python.d.plugin/oracledb/oracledb.chart.py#L396-L398

---

Everything looks correct :thinking:

**Comment by ilyam8** [comment]
Try same query as we do, probably there is something wrong 🤷‍♂️

**Comment by jurgenhaas** [comment]
I think the difference is that you take `tablespace_size` as the MAX BYTES metric which return the maximum size that's allowed for the oracle database. That value is always the same, in my case it's `3.4360E+10` (around 3 GB) for an XE license.

But a database may not necessarily grow to that size, only if you have auto-allocate enabled, which is not always recommended.

Instead, in our query we used the allocated max size for each database to calculate the percentage of usage.

May I suggest that you add the allocated space as a new metric and then also provide a percentage metric against that allocated space?

**Comment by ilyam8** [comment]
@jurgenhaas are you willing to make a PR?

**Comment by jurgenhaas** [comment]
I'm not a Oracle expert but I'll give it a try.

**Comment by ilyam8** [comment]
Me neither. Since you have access to an oracle instance, it is easier for you to fix the issue and test it.

**Comment by jurgenhaas** [comment]
@ilyam8 here you go, https://github.com/netdata/netdata/pull/10197 is working on 6 instances in our environment and the added code is similar to the tablespace code which was there before.

**Comment by ilyam8** [comment]
@jurgenhaas great! so fast! 😲 👍
