### ISSUE TITLE
Mirrored_host orderer in dash.html and Display it outsite of lan!

### ISSUE THREAD

**Issue by duhzon** [netdata/netdata#10210]
Hello guys!
Im trying to use default netdata multi host dashboard to show metrics! i ran all way up streaming configuration and im getting charts from dash.html aswell but the chart order is random! 
for example: charts is display from left to right in order: myserver1,myserver4,myserver6,myserver13,myserver5,myserver7...
How do dash.get_ordered_hosts(); work? its orderer by ip? label? Let me say a little about my topology to make it clear, my servers are:
main server: myserver00 (ip 192.168.1.100).
myserver01 (ip 192.168.1.101). myserver02 (ip 192.168.1.102).....myserver13 (ip 192.168.1.113).
Funny thing is that on main netdatadashboard (localhost:19999) into left menu all node are ordered, i dont know why html script is not getting this! I suppose its getting from the "mirrored_hosts": parameter (wich i can see on http://192.168.1.100:19999/api/v1/info) cause the chart displayed
 on dash.html is the same in the same order of what is showed under mirrored_host.
Do you guys know how i change that order? So i can se my server 00,01,02,03,04,05 from left to right into dash.html?
Its all running good with my metrics just that detail is bothering me thus i have came up a noob question: i can  acess my main dashboard outside of lan local host with my real myser00 ip (like 123.34.234.54:19999) but i cant load 123.34.234.54:19999/dash.html even placing var dash = new Dash('http://123.34.234.54:19999'); into dash.html. I thought that var dash was a local network parameter once mirrored_hosts is but i gave it a try anyway, without sucess. So the remain quest is: its possible to exibe dash.html outsite of lan that way? or i will have to use things like exporter nginx collector?
Thanks in advice!

**Comment by ilyam8** [comment]
Hi @duhzon 👋 

@tnyeanderson if you have time please take a look.

**Comment by tnyeanderson** [comment]
Hi @duhzon !

By default, the hosts are ordered alphabetically by hostname.

If you click the settings gear in the bottom right of the `dash.html` page, you will get a graphical interface where you can reorder the hosts.

Alternatively, line 449 is where you could use a different sort method:

```
        get_enabled_hosts () {
            try {
                return JSON.parse(localStorage.getItem('netdata_ordered_hosts')).enabled
            } catch (e) {
                return this.netdata_info.mirrored_hosts.sort();    // Line 449
            }
        }
```

The last thing about getting it "outside of lan".... you have to make the netdata API accessible to the *client*, because all of this is run in JS in the browser. So if that's what you want to do, make sure your netdata api is exposed to wherever the client happens to be outside of the lan. You will also have to have proper hostname resolution not using an internal IP address.

Hope this helps :)

**Comment by duhzon** [comment]
Really thanks! I Will give a try on gear in Dash.html! About outside of lan acess its like a suspect but how do i expose my api to the client and make proper internal resolution without internal ip? Its in .conf files?  Another thing its possible to use some sort of dns to acess it? Like myserver.com ? I saw registrer and colector documentation in learn netdata but it was a little Blur to me ! Sorry for these noob question and thanks for support!

**Comment by duhzon** [comment]
Another thing i have some kind of report i was installing last year netdata by clone git metod and install.sh all was fine but my cluster got formated and i gave netdata by kickstart metod a try. The thing is that netdata was unnable to apply change on netdata/web/stream.conf so i moved the conf to etc/netdata along with netdata.conf and it worked, no stream.conf was created with kickstart installation method so i moved it from clone git ditectory and stream was able to comunication. It took me a little bit to figure it out but im expossing it because i dont know if it happenned only to me or its because of kickstart method once its was the first time that i used it!

**Comment by tnyeanderson** [comment]
For access from outside your lan, I'd recommend one of two options:

1. Best option - use  a VPN to get into your lan from anywhere, then make the requests as normal (internal IPs and all)
2. Less secure - Set up port forwarding on your router to the ip:port of your netdata server. If you don't have a static IP for your router, then you'll also need a ddns service. Keep in mind to ONLY use this over https, never http. In fact, better to use a reverse proxy like caddy/nginx for https, along with a registered domain name pointing to your DDNS service, then port forward some random high port on your router to caddy/nginx. I would also password protect this page in some way to avoid unwanted access.....

The only netdata configuration that matters here is the `bind to` directive in the `[web]` section of your `netdata.conf`... just make sure that the `dashboard` is accessible from your reverse proxy (it is by default, `*` means accessible from anywhere)

I'm glad you were able to recover your `stream.conf`, I'm not sure what happened there.

Since accessing from outside the LAN is more a networking issue than a netdata one, I don't want to keep this issue open for that. So I'll ask that you please close this issue once you've verified that you can reorder the hosts in `dash.html`. Thanks @duhzon and best of luck!

**Comment by duhzon** [comment]
> For access from outside your lan, I'd recommend one of two options:
> 
> 1. Best option - use  a VPN to get into your lan from anywhere, then make the requests as normal (internal IPs and all)
> 2. Less secure - Set up port forwarding on your router to the ip:port of your netdata server. If you don't have a static IP for your router, then you'll also need a ddns service. Keep in mind to ONLY use this over https, never http. In fact, better to use a reverse proxy like caddy/nginx for https, along with a registered domain name pointing to your DDNS service, then port forward some random high port on your router to caddy/nginx. I would also password protect this page in some way to avoid unwanted access.....
> 
> The only netdata configuration that matters here is the `bind to` directive in the `[web]` section of your `netdata.conf`... just make sure that the `dashboard` is accessible from your reverse proxy (it is by default, `*` means accessible from anywhere)
> 
> I'm glad you were able to recover your `stream.conf`, I'm not sure what happened there.
> 
> Since accessing from outside the LAN is more a networking issue than a netdata one, I don't want to keep this issue open for that. So I'll ask that you please close this issue once you've verified that you can reorder the hosts in `dash.html`. Thanks @duhzon and best of luck!

I see @tnyeanderson thanks for the advices! Not sure if i will work on it yet but i will keep that in mind! Im happy with what i achieved with netdata so far and I already got dash.html reorderer thanks to your tip. 
Cloosing the issue as you asked

**Comment by duhzon** [comment]
> For access from outside your lan, I'd recommend one of two options:
> 
> 1. Best option - use  a VPN to get into your lan from anywhere, then make the requests as normal (internal IPs and all)
> 2. Less secure - Set up port forwarding on your router to the ip:port of your netdata server. If you don't have a static IP for your router, then you'll also need a ddns service. Keep in mind to ONLY use this over https, never http. In fact, better to use a reverse proxy like caddy/nginx for https, along with a registered domain name pointing to your DDNS service, then port forward some random high port on your router to caddy/nginx. I would also password protect this page in some way to avoid unwanted access.....
> 
> The only netdata configuration that matters here is the `bind to` directive in the `[web]` section of your `netdata.conf`... just make sure that the `dashboard` is accessible from your reverse proxy (it is by default, `*` means accessible from anywhere)
> 
> I'm glad you were able to recover your `stream.conf`, I'm not sure what happened there.
> 
> Since accessing from outside the LAN is more a networking issue than a netdata one, I don't want to keep this issue open for that. So I'll ask that you please close this issue once you've verified that you can reorder the hosts in `dash.html`. Thanks @duhzon and best of luck!

I see @tnyeanderson thanks for the advices! Not sure if i will work on it yet but i will keep that in mind! Im happy with what i achieved with netdata so far and I already got dash.html reorderer thanks to your tip.
Cloosing the issue as you asked
