### ISSUE TITLE
netdata start crash randomly

### ISSUE THREAD

**Issue by hitmoon** [netdata/netdata#10229]
version: e3b04fb39a06991d9a2deed0488044dd7d340e3f

My use case:
Starting netdata with two other node streaming  to localhost node, netdata crash randomly.

Here is what a got from gdb bt:
![netdata-gdb-bt](https://user-images.githubusercontent.com/3981296/98797723-ed73cf80-2447-11eb-9fb5-3506dcc80094.png)

The stack trace shows that crash happend at: rrddim_set_by_pointer function called by global_statistics_charts at file daemon/global_statistics.c. So I suspect there is 
a race condition: multiple threads call global_statistics_charts, add when one thread is creating RRDSET, set rdset to some non-null value,  another thread check rdset and find is not null, then goes to else branch. But at this point, the former thread has not
finished to create RDDIM, which lead rd == NULL . Then second thread call rrddim_set_by_pointer and its second parameter rd WILL BE NULL!!  This line: now_realtime_timeval(&rd->last_collected_time); will trigger a SEGV , thus lead to a crash.

Has anybody seen this issue ?  Any ideas?

**Comment by mfundul** [comment]
This cannot be a race condition since there is always only one thread running `global_statistics_charts()`. Moreover, It looks quite impossible for `rrddim_add()` to return `NULL`.

The other possible explanation is memory corruption, which fits with the "crash randomly" behaviour. Can you give some more information about your set-up? E.g. can you share your `etc/netdata/netdata.conf` and `etc/netdata/stream.conf` files after removing any sensitive information?

Can you share your "var/log/netdata/error.log" file?

**Comment by hitmoon** [comment]
> This cannot be a race condition since there is always only one thread running `global_statistics_charts()`. Moreover, It looks quite impossible for `rrddim_add()` to return `NULL`.
> 
After a closer look, I think I know where the problem is. 
Thank you very much !
