### ISSUE TITLE
Collectors Deprecation Strategy

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#10248]
##### Feature idea summary

We have collectors written in:
 - `c`
 - `bash`
 - `python`
 - `nodejs`
 - `golang`

`c` is used mainly for internal collectors.

Collectors written in `bash`, `python`, `nodejs` and `golang` are external, all of them follow the same approach: a plugin + data collection modules.

It totally makes sense to choose one language for core external collectors. `golang` has been chosen: it is compiled, popular, rapidly developing, its standard library is amazing, relatively simple, proven to be effective in data collection where you need concurrency,  etc.

## Desired State

| lang         | plugin (orchestrator)   | core collectors   | usage                    | maintainers    |
| :----------: | :---------------------: | :---------------: | -------------------------| -------------- |
| `c`          | -                       |  yes              | core collectors.         | nd + community |
| `golang`     | yes                     |  yes              | core + custom collectors | nd + community |
| `bash`       | yes                     |  no               | custom collectors        | nd + community |
| `python`     | yes                     |  *no              | custom collectors        | nd + community |
| **`nodejs`   | yes                     |  no               | custom collectors        | community      |

Both `bash` and `python` are great for writing custom collectors and there is no doubt we need to keep and maintain appropriate plugins. But keeping in mind only custom collectors scope (no new features, keep them simple).

`*` If there is a `no-go` for writing a collector in `golang` (ex.: needs `cgo`) we write it in `python`.
`**` Being honest... I am not really sure we need `nodejs` plugin at all, on the other hand deleting it feels not right, so I think we need just make it explicit that we have, but don't maintain (sounds not good too, back to the idea of deleting it? 😄).

## Deprecation Strategy Proposal/Example

**We need a clear and explicit collectors deprecation policy**, following it allows us to have the migration process transparent and predictable for us and our users.

We have no strict release schedule, at the moment it depends on added new features (common release) or fixed critical bugs (bug fix release). 

We can't use time periods, but only the number of releases. Patch releases (bug fix releases) should be ignored.

[Usually, it is](https://github.com/netdata/netdata/releases) 1-2 months between releases.

I suggest 3 releases between deprecation announcements and deprecating ([re]moving) a collector.
So it is ~3-6 months for stable channel users and a little bit less for nightlies users.

Stable channel:
 1. Release `x.y.0`: announcements + deprecation warning alarm. [Time for migration to new collectors]
 2. Release `x.y+1.0`: keep deprecation warning alarm. [Time for migration to new collectors]
 3. Release `x.y+2.0`: keep deprecation warning alarm. [Time for migration to new collectors]
 4. Release `x.y+3.0`: remove deprecated collectors, remove alarms.

Nightlies  channel:
 1. Release `x.y-1.0@master`: deprecation warning alarm. [Time for migration to new collectors]
 2. Release `x.y.0@master`: keep deprecation warning alarm. [Time for migration to new collectors]
 3. Release `x.y+1.0@master`: keep deprecation warning alarm. [Time for migration to new collectors]
 4. Release `x.y+2.0@master`: remove deprecated collectors, remove alarms.

**For nightlies users a deprecation alarm/removing a collector event can happen at any moment during release**: migration work is not the highest priority but will be always going in the background, we will try to migrate as much as possible, but the exact number is hard to predict, so it is better to announce after the work, not before/according to our plans.

##### Expected behavior

Have collectors deprecation policy and follow it.

**Comment by OdysLam** [comment]
Coming back to this, having spent a lot of time thinking about collectors in regards to how we should handle the collectors, here are a couple of ideas. 

My main goal is to increase the consistency of the collectors that we have by lowering the surface that we have to develop and maintain so that we can focus on and QA a number of production-grade collectors.

- Python: Used to create PoC and custom collectors. We don't maintain them, but we will help you in finding problems and contributing fixes. Everything is "as-is" and we take no responsibility if something doesn't work out as it should. It's our lab, so it's not very hard as a contributor to get your collector accepted.
. - Golang: Production grade, we maintain them, we do QA and we support them. Whatever you find there is of the same quality and coverage. It will not break unexpectedly. We make sure to update the collectors if the underlying services change (e.g API update). We have a very high standard of user contribution here and it's unlikely to see, as every new contribution increases the surface that we need to maintain. 
- Node: Remove and move to the community repo. Legacy stuff that you can use as is but we neither develop nor support it. We actively advise against using it. SNMP collector is an edge case as it's relatively famous.
- Shell: Same as Python
- StatsD: Same as Python

Finally, I think that if we upgraded the Prometheus collector to have the same functionality as the StatsD it would greatly increase coverage, as **any** user could submit a new configuration, creating in effect a new collector. Again we would have high standards for what we accept, but the development velocity will be considerably higher. So instead of starting to work on new collectors, I would argue to start working on this general collector (in essence build on top of what we have)

**Comment by Ferroin** [comment]
I second the suggestion about leveraging the prometheus collector to improve coverage quickly, The caveat is that we should not let this preclude a proper implementation in golang (which will almost always be more efficient than looping through a Prometheus exporter).

I’d also add that as of right now, some of the Python stuff is a first-class citizen, and will likely remain as such for the foreseeable future.

And, on a side note, we really need to just create an issue for the conversion of the SNMP collector. I don’t know how practical golang would be for that, but SNMP is seriously important in terms of coverage as well (we just don’t treat it as such right now) given that it enables monitoring of a huge selection of network appliances (and, in theory, even some basic stuff on remote systems without needing any special platform-specific handling).

**Comment by ilyam8** [comment]
In my opinion, deprecated (python, bash) collectors should be removed from the netdata repo and moved to the community repo. We don't want to install something by default if that provides no value, we don't maintain it and **take no responsibility if something doesn't work as it should**. Should be deliberate action from a user to use them.

@OdysLam why do you think we need to keep them? I think it makes things complex and confusing.

**Comment by OdysLam** [comment]
@ilyam8

I agree with the removal. It might take an extra step to install them, but it will greatly increase the credibility of the agent by setting expectations and having fewer things to break out of the box.

I think credibility is a crucial aspect, given the industry that we are in, so the value we get by limiting the things that break (by having less surface to QA) is more than the value that some people get by having them installed by default. 

Finally, of course we should create some tooling to make the installation easier, ideally without having to mess with git. (e.g run a script via a button on the dashboard). This way, we keep the awesome UX + philosophy.
