### ISSUE TITLE
mdstat_mismatch_cnt - should not be default alert

### ISSUE THREAD

**Issue by Slind14** [netdata/netdata#10247]
The mdstat_mismatch_cnt is automatically configured as an alert. Unfortunately, this triggers on pretty much every system with fast/heavy writes, and according to https://serverfault.com/a/885574 , this is harmless.

Even when resyncing a raid, the miss-match is back within just a few minutes to hours when there is a lot of fast writes going on.

I would like to suggest removing this from the default alerts, since on any server that has some write throughput this value will always be there and all the nodes will show up as "critical" in netdata.

**Comment by ilyam8** [comment]
Hi @Slind14 

From that discussion:

> However, there is a much more concernig and dangerous mismatch_cnt cause: an hardware issue (ie: faulty power supply delivering inconsistent power and/or a misbehaving disk DRAM chip) can alter in-flight data, leading to many inconsistencies between the two disks

So there are cases where we don't want to miss `mismatch_cnt` event.

Current alarm:

https://github.com/netdata/netdata/blob/8c57672cbfbc9c243381e2dff1b9055c7f332079/health/health.d/mdstat.conf#L20-L27

Perhaps we need to change its severity level to `warn` and tune the condition ( `> 0` => `> someNumber`). What do you think?

**Comment by Slind14** [comment]
I see. If there is no better metric for that, would `warn` at `> 1024` or similar be a good solution?

Unfortunately, I don't have any experience with this metric. We are seeing it at up to 32k without any harmful cause from what I can tell.

80% is =< 1024

**Comment by ilyam8** [comment]
Yes, `crit` => `warn`, 0 => 1024 looks good to me. And i think we can add [`delay: up`](https://learn.netdata.cloud/docs/agent/health/reference#alarm-line-delay) parameter.

**Comment by ilyam8** [comment]
I am not quite sure, but it looks that we need to inform a user if `mismatch_cnt`:
 - is relatively big.
 - does not decrease within some time period.

_relatively big_ and _ome time period_ are 🤷‍♂️ for me, we could choose something and tune it later if there are any issues.


For instance:

```
 template: mdstat_mismatch_cnt 
       on: md.mismatch_cnt 
    units: unsynchronized blocks 
     calc: $count 
    every: 10s 
     crit: $this > 1024 
    delay: up 10m
     info: Mismatch count! 
       to: sysadmin 
```

I have nothing to suggest any better. @Ferroin any ideas?

**Comment by Slind14** [comment]
If it is possible to trigger the alert if it doesn't decrease over time then a higher initial value would be great. Maybe 10 times of that.

**Comment by mailinglists35** [comment]
mdadm used to warn users about mismatch count, however since 2010 (version [3.1.1-0.gcd9a8b5.3](https://raid.wiki.kernel.org/images-raid/2/28/Mdadm.spec.txt)) this is silenced for raid 1 and 10 in their `/usr/sbin/raid-check` cron script

I am also getting false alerts. Greatest number so far since < 2 days of running netdata on this oracle db is [ $this = 3840 ]
I have swap on top of lvm, on the raid1 md (swap>lvm>md). It doesn't seem to be used, though... but I see use of memory mapped files that Neil Brown mentioned in a Debian bug [comment](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=405919#41):
> This can conceivably happen with out swap being part of the picture,
> if memory mapped files are used.  However in this case it is less
> likely to remain out-of-sync and dirty file data will be written out
> soon, where as there is no guarantee that dirty anonymous pages will
> be written to swap in any particular hurry, or at any particular
> location.
> 

Another false alert that I get is on an array where one device has been tuned with `--write-behind` option. On that array sometimes the mismatch count can legit go as high as 205312 and goes away when I issue a check to sync_action file, however it quickly re-grows from 0 to three digit number during normal use after the check or repair action finishes

**Comment by ilyam8** [comment]
So we don't need to report `mismatch_count` if [`check`/`repair`/`resync`](https://github.com/tinganho/linux-kernel/blob/f1349b033d5faee3682eea244a7cb4dbbb7982d0/Documentation/md.txt#L457-L472) is performing?

Those actions supposed to find some `mismatch_count`, but they fix them at the same time.

---

> can legit go as high as 205312 and goes away when I issue a check to sync_action file

Why do you think it is false positive in this case?

**Comment by mailinglists35** [comment]
Those were just my observations in arrays I manage:
- the one with oracle memory mapped files and swap on lvm on md raid1
- the one with a raid1 array made from: 1 lvm thin volume on ssd, 1 zfs zvol on hdd. The hdd one is setup with `--write-mostly` and `--write-behind`. There is a windows vm running on top of it and I *always* see the mismatch count non-zero. I have this setup in two places and they both have the mismatch non-zero (for the second place where I've never looked at, the count is 4519936 right now for an uptime of 130 days, despite the disks being ok)
what's odd it resets to zero at the beginning of a repair then increases during repair (ran this on the first win vm):
````
root@md:~# echo repair > /sys/block/md127/md/sync_action
root@md:~# while true; do grep . /sys/block/md127/md/mismatch_cnt; sleep 5; done
0
896
4736
6656
7168
7296
8832
9984
12160
13568
13952
13952
14976
16128
17920
18432
19072
19072
````
and remains there at 19072 when repair finishes or resets to zero then increases again to three digit value

- md guys themselves recommended disabling checks of mismatch_cnt for raid1 and 10 due to too many false positives. From https://access.redhat.com/solutions/22203: 

"Details from the patch in BZ 566828

Due to the fact that raid1 writes in the kernel are unbuffered, a raid1 array can have non-0 mismatch counts even when the array is healthy. These non-0 counts will only exist in transient data areas where they don't pose a problem. However, since we can't tell the difference between a non-0 count that is just in transient data or a non-0 count that signifies a real problem, simply don't check the mismatch_cnt on raid1 leaving the raid1 device in the check list and performing the check, we still catch and correct any bad sectors there might be in the device."

**Comment by ilyam8** [comment]
Filtering based on the array type makes sense.

We could add the array type (level) to the family (subsection on the dashboard)

Changes on the dashboard

```YAML
mdstat:
  - md1
  - md2
  - md3
```

=>

```YAML
mdstat:
  - md1 (raid1)
  - md2 (raid5)
  - md3 (raid10)
```

So we can use [alarm-line-families](https://learn.netdata.cloud/docs/agent/health/reference#alarm-line-families) for filtering.

```yaml
 template: mdstat_mismatch_cnt
       on: md.mismatch_cnt
    class: System
component: RAID
     type: Errors
 families: !*(raid1) !*(raid10) *
    units: unsynchronized blocks
     calc: $count
    every: 60s
     warn: $this > 1024
    delay: up 30m
     info: number of unsynchronized blocks for the $family array
       to: sysadmin
```

Does it sound good? cc @vlvkobal

**Comment by Slind14** [comment]
Thank you for digging into this. Now I see why we keep having this all the time.

**Comment by mailinglists35** [comment]
> `families: !*(raid1) !*(raid10) *`
> `warn: $this > 1024`

if you exclude the likely false positives raid1 and raid10, then instead shouldn't the warn threshold value be much lower, as it could potentially indicate a real issue to catch earlier? so maybe warn first on a much lower value, then escalate to critical?

**Comment by ilyam8** [comment]
Yes @mailinglists35, you are right, my point was we can use `families` to filter out raid1 and raid10

**Comment by ilyam8** [comment]
> if you exclude the likely false positives raid1 and raid10, then instead shouldn't the warn threshold value be much lower, as it could potentially indicate a real issue to catch earlier? so maybe warn first on a much lower value, then escalate to critical?

Let's discuss the thresholds. I am not sure about adding `critical`, but lowering the value sounds ok. What is your suggestion?

**Comment by mailinglists35** [comment]
Neil Brown said in the debian bug tracker: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=405919#41

> For RAID5, unexpected mismatches would be a problem, yes.

This is further largely detailed in the md(4) manual page:
> 
>        A  count of mismatches is recorded in the sysfs file md/mismatch_cnt.  This is set to zero when a scrub starts and is incremented whenever a
>        sector is found that is a mismatch.  md normally works in units much larger than a single sector and when it finds a mismatch, it  does  not
>        determine  exactly  how many actual sectors were affected but simply adds the number of sectors in the IO unit that was used.  So a value of
>        128 could simply mean that a single 64KB check found an error (128 x 512bytes = 64KB).
> 
>        If an array is created by mdadm with --assume-clean then a subsequent check could be expected to find some mismatches.
> 
**On a truly clean RAID5 or RAID6 array, any mismatches should indicate a hardware problem at some level - software issues should never  cause**
>        such a mismatch.
> 
>        However  on RAID1 and RAID10 it is possible for software issues to cause a mismatch to be reported.  This does not necessarily mean that the
>        data on the array is corrupted.  It could simply be that the system does not care what is stored on that part of the array -  it  is  unused
>        space.
> 
>        The most likely cause for an unexpected mismatch on RAID1 or RAID10 occurs if a swap partition or swap file is stored on the array.
> 
>        When the swap subsystem wants to write a page of memory out, it flags the page as 'clean' in the memory manager and requests the swap device
>        to write it out.  It is quite possible that the memory will be changed while the write-out is happening.  In that case the 'clean' flag will
>        be  found  to  be  clear when the write completes and so the swap subsystem will simply forget that the swapout had been attempted, and will
>        possibly choose a different page to write out.
> 
>        If the swap device was on RAID1 (or RAID10), then the data is sent from memory to a device twice (or more depending on the number of devices
>        in  the array).  Thus it is possible that the memory gets changed between the times it is sent, so different data can be written to the dif‐
>        ferent devices in the array.  This will be detected by check as a mismatch.  However it does not reflect any corruption as the  block  where
>        this mismatch occurs is being treated by the swap system as being empty, and the data will never be read from that block.
> 
>        It is conceivable for a similar situation to occur on non-swap files, though it is less likely.
> 
>        Thus the mismatch_cnt value can not be interpreted very reliably on RAID1 or RAID10, especially when the device is used for swap.

so in my understanding, raid1 and raid10 should be ignored while raid5 and raid5 should warn on non-zero, then emit new warnings for each increase

**Comment by mailinglists35** [comment]
md also supports level 4 (striped array with parity device) but there is no clarification in the docs what mismatch_cnt would mean for it; perhaps should be treated the same way as raid5/6? a corner case anyway
