### ISSUE TITLE
cgroups collection gaps in dynamic environments

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#10285]
##### Bug report summary
When cgroups get dynamically updated (e.g. our k8s infra), the cgroup collector is blocked and we lose data.

##### OS / Environment
Netdata production k8s infra

##### Netdata version
Latest

##### Component Name
cgroups

##### Steps To Reproduce
trigger running of cgroup-name.sh (new cgroup detected) in an infra with many containers 

##### Expected behavior
The bash scripts should be executed in parallel and not block data collection. This means that the cgroups collector should be multi-threaded.

**Comment by cakrit** [comment]
cc @mfundul who helped with the triage

**Comment by ilyam8** [comment]
`cgroup-name.sh` is indeed a problem and very slow/cpu expensive.

We added 2nd http call to get `cluster_id` in [Kubernetes labels PR](https://github.com/netdata/netdata/pull/10107)

i did some optimizations:
 - `/api/v1/pods` call: reduce number of returned data by [adding `fieldSelector` query parameters](https://github.com/netdata/netdata/pull/10107/commits/024d1538a9b7ab97ccf37d151e5cbe6f808192b9), so now it returns list of pods for the node netdata is running.
 - `api/v1/namespaces/kube-system`: it doesn't change, so i decided [to cache the response](https://github.com/netdata/netdata/pull/10107/commits/abf4e8af2c6d659ecacb9e83f1a556db6dd34fe8), so it is only one http call (`curl`) then we read from a file.

We could try to cache `/api/v1/pods` too and do a http call (`curl`) only if a cgroup is not in there. So `cgroup-name.sh` would be reading from a file, this would reduce number of http calls on start significantly. I am not sure this helps, but could try.

**That workaround is not good**, but we should have no problems with caching data since we do name resolution only on container creation.

Ideally we need some cgroup name resolution service or something 🤔

**Comment by ilyam8** [comment]
`cgroups` collector checks for new cgroups every 10 by default.
If there is any it calls `cgroup-name.sh` script _NumberOfNewCgroups_ times.

I didnt check other sources, but for k8s we need only one HTTP call, so it would be much better to pass a list of ids and get a list of names.

Just thinking out loud here 🤔

**Comment by ilyam8** [comment]
Fixed in #10399
