### ISSUE TITLE
Unable to locate package libjson-c-dev liblz4-dev libuv1-dev

### ISSUE THREAD

**Issue by neobiz** [netdata/netdata#10411]
#### Summary
Hello,

I'm trying to install Netdata on Debian (7.11  Wheezy) after "apt update & apt upgrade" I'am using this command :

bash <(curl -Ss https://my-netdata.io/kickstart.sh) --stable-channel --disable-telemetry

Unfurtunately I have the error message : 

E: Unable to locate package libjson-c-dev
E: Unable to locate package liblz4-dev
E: Unable to locate package libuv1-dev

I have also try " --libs-are-really-here" but the result is the same. "apt install libjson-c-dev" return "Unable to locate package libjson-c-dev".
Is someone has an idea to resolve this issue ?

Regards,

**Comment by Ferroin** [comment]
We no longer support local builds via our kickstart installeron Debian 7.x due to it not providing packages we need for the install (specifically a new enough version of `libuv`).

There are two options to get Netdata working there:

* If you have a 64-bit x86 system, you can use our static installer as outlined [here in our documentation](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart-64).
* Otherwise, you will need to build a local copy of a new enough version of libuv (I believe we just need 1. or newer, but I’m not certain) and then manually install Netdata as outlined [here in our documentation](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/manual).

**Comment by stelfrag** [comment]
Closing as the suggestion of using the static installer (if on 64-bit x86) system would solve the problem
