### ISSUE TITLE
[Bug]: Source RPM's Are Not Deployed

### ISSUE THREAD

**Issue by westphaldp** [netdata/netdata#10481]
Source RPM's are not being deployed to packagecloud.

It appears that the Travis pipeline intends to deploy the source RPM's, but I can't find any in the EL 7 SRPMS repository.

https://travis-ci.com/github/netdata/netdata/jobs/462417405#L7318

**Comment by OdysLam** [comment]
Thanks for reporting this @westphaldp, pinging @Ferroin who is leading our packaging efforts.

**Comment by Ferroin** [comment]
This is something we’d like to do long term, but it’s very low priority right now, especially since we’re in the middle of reworking how we handle building and publishing packages.

**Comment by westphaldp** [comment]
That is great to hear. Can you point me at a branch or elaborate on the plan?

**Comment by Ferroin** [comment]
The current WIP code for the packaging rework can be seen in #9964. The current plan once that is working correctly and merged is to work on getting packages building for ARM systems as well as the x86 builds we’re already doing (this _should_ be relatively quick and easy), and source packages (both DEBSRC and SRPM) are likely to be the next thing after ARM support to be worked on for our packaging.

**Comment by cakrit** [comment]
Packaging has been completely revamped, closing.

**Comment by Ferroin** [comment]
Reopening this as it’s not actually done and we are planning on doing it, the timeline has just slipped horribly because native package improvements have largely been low priority in favor of fixing other install/update related issues, and this one slipped through the cracks for a number of reasons other reasons as well.

I intend to get this properly planned out by the middle of next month, and hope to actually have it done by the end of Q3 2022.

**Comment by Ferroin** [comment]
Further update: This is currently stalled pending completion of the migration of our package repositories from Package Cloud to self-hosted infrastructure.

It’s still on the TODO list though, it just has no clear ETA at the moment.

**Comment by ilyam8** [comment]
@Ferroin hey, is it still pending?
