### ISSUE TITLE
Docker docs should have prominent link to installation or be updated

### ISSUE THREAD

**Issue by TeNNoX** [netdata/netdata#10500]
The run documentation on the [docker hub](https://hub.docker.com/r/netdata/netdata) is outdated and needs an update - or a prominent link to the [installation docs page](https://learn.netdata.cloud/docs/agent/packaging/docker#create-a-new-netdata-agent-container).

I encountered this when I restarted the container - loosing dashboards and cloud connection. #5516

**Comment by Ferroin** [comment]
I think the link to our Docker documentation page is probably the best option here. We can’t automate updates to the README on Docker Hub due to limitations in Docker Hub’s APIs (they do not support using a PAT (the only method supported for API access when using 2FA on an account) to make the required API calls to update the description), so it’s not realistically feasible for us to keep this up to date otherwise.

@joelhans Your thoughts on this would be appreciated.

**Comment by cakrit** [comment]
I updated the documentation with a link to [the docker installation page](https://learn.netdata.cloud/docs/agent/packaging/docker)

**Comment by cakrit** [comment]
Thanks @TeNNoX !
