### ISSUE TITLE
localhost:19999 Ip address access

### ISSUE THREAD

**Issue by PeterKW** [netdata/netdata#10591]
I have managed to get Netdata logs up on localhost:19999 which is fine but I would like now to be able to access the logs on another device.

I have another package running on the same Manjaro device which is available at a different port e.g. 000.000.0.000:1111
How do I get (or make) the correct port number or expose the port locally so that I can access Netdata logs on a different device in the same network?

Hopefully what I'm trying to do makes sense

**Comment by MrZammler** [comment]
Hi Peter!

I'm assuming you want to access the Netdata dashboard from another machine on the same network, right? If you know the IP of the machine (Manjaro) that the Netdata binary is running, then you can try to access it from another machine, just by using the IP:19999

This should work, since typically machines on the same network don't use firewalls, etc.

You can find the IP of your machine by using the `ip a` command in Manjaro.

If that doesn't work, perhaps in netdata.conf (/etc/netdata/netdata.conf) the web server is bound to just localhost (127.0.0.1). If so, try with setting `# bind to = *` in the `[web]` section of the file.

You could also take a look at the documentation on the subject (https://learn.netdata.cloud/docs/agent/web/server). Let us know if it's ok!

**Comment by PeterKW** [comment]
Thank you very much for your help. Got that working now
