### ISSUE TITLE
Nvidia smi circullar plots doesn't work properly

### ISSUE THREAD

**Issue by jendrusk** [netdata/netdata#10768]
Numbers are fine but I'm getting for example fully plotted circle for fan speed of 58%
![obraz](https://user-images.githubusercontent.com/9802737/111185917-c9212e80-85b2-11eb-8e9a-8e2382843fc5.png)

**Comment by ilyam8** [comment]
Hi @jendrusk 

You are right! Since it is percentage, we can set maximum adding

```java
+ ' data-easypiechart-max-value="100"'
```

to the

https://github.com/netdata/netdata/blob/6c5bb166ca16dad2f6f51e55a3a0c9965de15d04/web/gui/dashboard_info.js#L3738-L3754

Can you test it? (don't forget to `Empty cache and hard reload` the page)

**Comment by ilyam8** [comment]
>  for example fully plotted circle for fan speed of 58%

Unfortunately, we can fix it only for percentages plots (we know the maximum). Circle is the current value relative to the maximum for the period. And the period is whatever you chose using the time picker (default is the last 5 minutes).

**Comment by jendrusk** [comment]
Another plot is for used memory... maybe you can get maximum for it... I understand that this could be a problem for other ones :)

**Comment by ilyam8** [comment]
I wish we could _fix_ all of them, but that is how those gauges work

>  Circle is the current value relative to the maximum for the period. And the period is whatever you chose using the time picker (default is the last 5 minutes).

And there is no other options (like just a value), it is either `easypiechart` or `gauge`.

<img width="373" alt="Screenshot 2021-03-15 at 22 07 29" src="https://user-images.githubusercontent.com/22274335/111207592-df42e500-85da-11eb-8cff-c28d013b55fb.png">

So we can only do https://github.com/netdata/netdata/issues/10768#issuecomment-799590794

I can not test is myself, since i [don't use nvidia drivers](https://forum.manjaro.org/t/dropping-all-legacy-and-older-nvidia-drivers/36338) (nvidia-smi doesn't work).

**Comment by jendrusk** [comment]
Ok, so  how can I help you to test this? 
This is my netdata - http://xploria.io:20000/

**Comment by jendrusk** [comment]
Thanks Ilya :)

**Comment by ilyam8** [comment]
You are welcome 😄
