### ISSUE TITLE
Install script fails to install required packages

### ISSUE THREAD

**Issue by iTzEthqnHD** [netdata/netdata#10783]
Hi, 

I am having an issue where it is failing to install libssl-dev and don't know exactly what is causing it. Can any of you shed light on this?

[Screenshot](https://prnt.sc/10ng8d5)

**Comment by iTzEthqnHD** [comment]
Does anyone know how to fix this?

**Comment by Ferroin** [comment]
Apologies for the slow response.

Can you please share the output of `uname -a; grep -Hv "^#" /etc/*release` on the system you are seeing this issue?

**Comment by iTzEthqnHD** [comment]
![image](https://user-images.githubusercontent.com/36141762/111823807-c4fb5680-88bb-11eb-99e2-a5d572be2fe0.png)

**Comment by iTzEthqnHD** [comment]
Any update? 

To recreate it, all I did was use this script: https://github.com/vilhelmprytz/pterodactyl-installer and installed the panel.

**Comment by Ferroin** [comment]
Based on looking further at https://github.com/vilhelmprytz/pterodactyl-installer further, it appears that what is going on here is that that is installing an additional repository on the system in question to be able to use a newer version of OpenSSL than Ubuntu 18.04 provides by default, but the repository in question does not provide the required packages to be able to build against that version of OpenSSL.

As a result, the Netdata installer is unable to install a version of OpenSSL it can actually build against.

There’s unfortunately not really anything we can do about this on our end. You _might_ be able to get things working together if you tried on Ubuntu 20.04 instead of 18.04 (20.04 ships with a much newer version of OpenSSL than 18.04, so the Pterodactyl installer may not need to lean on the third-party repo there). Your best option though, if you’re on a 64-bit x86 system, is probably going to be using our [static installer](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart-64), which does not depend on the state of the rest of the system at all.

**Comment by iTzEthqnHD** [comment]
I tried the static installer again today and only a few things fail. I try claiming a node and says netdata-claim.sh: command not found

These are the only things that failed: [](https://i.ethqn.co/KKuZnq.png)

**Comment by Ferroin** [comment]
Those failures are expected (we try to add the user Netdata runs as to a bunch of well known group IDs on install to help make sure as much as possible works out of the box, and those failures are just cases of such groups that you don’t have on the system in question).

As far as the claiming script, if you’re using the static installer either add `/opt/netdata/bin` to your `$PATH`, or instead invoke the claiming script as `/opt/netdata/bin/netdata-claim.sh`.
