### ISSUE TITLE
Add kernel clock sync status and time offset in between local system and reference clock metrics

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#10889]
##### Feature idea summary

It is important to have system clock synchronized to a reliable server. 

We can gather this data using [adjtimex](https://man7.org/linux/man-pages/man2/adjtimex.2.html) system call (linux only).

It returns a lot of metrics. I am not a specialist, but several of them looks worth to collect. Likely there is more, but i am not sure atm 🤷‍♂️ 

Related article: http://www.ntp.org/ntpfaq/NTP-s-algo-kernel.htm

I think we need:
 - clock sync status (is system clock synchronized to a reliable server or not)
 - time offset in between local system and reference clock (if synced)

`node_exporter` has [timex collector](https://github.com/prometheus/node_exporter/blob/master/collector/timex.go), it does exactly it: executes `adjtimex` system call.

##### Expected behavior

Netdata collects kernel clock sync status and time offset in between local system and reference clock.

**Comment by Ferroin** [comment]
Pretty much everything there should be exposed if possible. The only ones that are irrelevant as metrics are the `modes`, `constant` and `time` members (and `constant` _may_ be useful in som rare cases when debugging krnel-level timing issues, but that’s not super likely). We can _probably_ ignore `tai` as well (essentially, this is the timezone offset).

Among the others:

* `offset`, `freq`, `precision`, and `tick`: Are important as measures of relative accuracy and precision of the system clock.
* `maxerror`, `esterror`, and `tolerance`: Are stability metrics (lower values mean a more stable clock).
* All of the PPS related stuff is actually really important for determining clock accuracy on systems that use PPS (pulse-per-second) hardware for timing. Among other things, most stratum 1 NTP servers use such hardware (usually using GPS, a radio timesignal broadcast, or an atomic clock), because it’s really the only way to properly stabilize the local clock on a computer.

**Comment by ilyam8** [comment]
@Ferroin that is a very valuable input, thanks! We plan to dig a bit into this topic and add additional metrics when we have better understanding of them.
