### ISSUE TITLE
[Bug]: Readable output from  the kickstarter script

### ISSUE THREAD

**Issue by vincentkersten** [netdata/netdata#10881]
##### Bug report summary

Hi NETDATA, awesome work you are doing, I really enjoy the project!

Today I was installing (reinstalling) the netdata and it caught my eye that the display colors of the kickstarter - netdata-install script could use some trimming (or at least on my machine )  looks like this: 

<img width="919" alt="Screen Shot 2021-03-30 at 09 19 52" src="https://user-images.githubusercontent.com/5429401/112950756-e8839400-913a-11eb-9546-ffbd0189e163.png">

Highliting the output gives me some useful info I cannot see otherwise:

<img width="1011" alt="Screen Shot 2021-03-30 at 09 35 13" src="https://user-images.githubusercontent.com/5429401/112951186-6182eb80-913b-11eb-8dc8-63eb687166c1.png">

##### OS / Environment
Linux / Debian 10

##### Netdata version
Version: netdata v1.29.3-215-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-lws=externaldeps/libwebsockets' 'CFLAGS=-O2' 'LDFLAGS='
Features:
    dbengine:                YES
    Native HTTPS:            YES
    Netdata Cloud:           YES 
    Cloud Implementation:    Legacy
    TLS Host Verification:   YES
Libraries:
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
##### Installation method
kickstarter script
##### Component Name
kickstarter build phase

##### Steps To Reproduce

Start the kickstarter.sh ; slap on some sunglasses; highlight text to get important info. 

##### Expected behavior

Readable build output.

**Comment by Ferroin** [comment]
Hmm, looks like we’re not setting the background color for our colored output.

**Comment by Ferroin** [comment]
@netdata/product How do we want to handle this?

While a default white text on a bright green background is unusual, our honestly excessive use of colors is a bit distracting and may lead to readability issues for some users for other reasons.

Given this, we have three options as I see things (no pun intended):

1. Quit messing around with colors at all, and just use bold text to draw attention where we actually need to do so. This would trivially solve the readability issues brought about by colors, but would probably need a pass over how we actually handle logging things to the console to preserve some aspects of readability (though that may be a good thing, we have absrudly noisy console output).
2. Only use colors for the OK/FAILED/ABORTED tags and actual error messages, and do so in a way that works regardless of the color palette on the user’s terminal.
3. Force a specific background color for any colored text we want to output (probably black).

I’m personally in favor of the second option because it would make our output look a lot cleaner, still lets us draw attention where we need to, looks nicer than either 1 or 3, and requires relatively little effort to implement.

**Comment by thanos-karachalios** [comment]
I agree here with @Ferroin on point 2. Let's follow some basic rules with what exist in other terminals/IDEs. I don't think of this context as one for netdata branding etc.

**Comment by vincentkersten** [comment]
Just my input: I think I favor option 1, it keeps it easy (maintainable) , readable, and works 'everywhere'.

**Comment by manos-saratsis** [comment]
@Ferroin I am in favor of the second option but more improvements will be required on the output such as:
- Show final status at the end & instructions how to proceed
- Copy all errors/warnings at the end
- Introduce -debug param which will have the same long output we currently have. If the param is not there show only final status ("Installation completed successfully") and errors/warnings

I suggest we sync

**Comment by Ferroin** [comment]
@vincentkersten In theory, if we implement option 2, we will probably end up doing so in a way that functionally falls back to behaving like option 1 if we aren’t on a color terminal.

@manos-saratsis Agreed, we should sync up on this. Feel free to send an invite for a meeting. I personally think we should probably have some of the UX guys involved in the discussion as well as they may be able to provide a more user oriented perspective than either of us would have.

**Comment by Ferroin** [comment]
@netdata/agent-sre If someone wants to pick this up, currently desired behavior for the resolution of this is:

- Only message tags (`OK`/`FAILED`/`ABORTED`) should use colors, they should set a background color, and they should use bold text.
- Clean fallback behavior should be provided if possible for the case of terminals which do not support colors or bold text.

**Comment by Dim-P** [comment]
Dropping this one to low priority and adding label for first time contributors, as I think it can be handled without necessarily too much knowledge about how everything else works.

**Comment by ilyam8** [comment]
I think this issue has been fixed, at least I can't reproduce it.
