### ISSUE TITLE
Use release branch(es) instead of releasing Netdata from the master branch

### ISSUE THREAD

**Issue by vlvkobal** [netdata/netdata#11039]
Our existing practice of releasing Netdata from the master branch has a couple of drawbacks:
- We have long periods of time when we can't merge new code until we think the release is stable. The idea of using the `development` branch doesn't actually work.
- A lot of irrelevant code is merged to bugfix releases, which makes them less stable than they should be.

**Comment by Ferroin** [comment]
The SRE team has had support for this as a long-term goal for quite some time.

As things stand right now, the primary blocker is that our curent release CI does not support running on anything but the master branch. Our current plans to migrate off of Travis CI to GitHub Actions for the entirety of the release process include plans to fix that limitation.

I need to get around to just creating an Epic for the migration itself so that I can properly list it as a blocker for this.

**Comment by Ferroin** [comment]
Correction, we have an epic for this, it’s just not in the agent repo...

Guess I have a bunch of issues to move.

**Comment by Ferroin** [comment]
This is now implemented for patch releases, which is sufficient to fix the two issues outlined in the original post.
