### ISSUE TITLE
Ubuntu 20.04 installation fails

### ISSUE THREAD

**Issue by binaryfire** [netdata/netdata#11093]
Hi guys,

I'm trying to automate the installation of Netdata on Ubuntu 20.04. However the script is failing because of unmet package dependencies (see output below). Any ideas on how I could solve or work around this?

Thanks!

```
Reading package lists...
apt-get -yq install autoconf autoconf-archive autogen automake cmake gcc libelf-dev libjson-c-dev libjudy-dev liblz4-dev libmnl-dev libssl-dev libtool libuv1-dev make pkg-config uuid-dev zlib1g-dev 
Reading package lists...
Building dependency tree...
Reading state information...

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.

The following information may help to resolve the situation:
The following packages have unmet dependencies:
 libtool : Depends: libc6-dev but it is not going to be installed or
                    libc-dev
 uuid-dev : Depends: libc6-dev but it is not going to be installed or
                     libc-dev
 zlib1g-dev : Depends: libc6-dev but it is not going to be installed or
                       libc-dev
E: Unable to correct problems, you have held broken packages.

We are very sorry!
Installation of required packages failed.
What to do now:
  1. Make sure your system is updated.
     Most of the times, updating your system will resolve the issue.
  2. If the error message is about a specific package, try removing
     that package from the command and run it again.
     Depending on the broken package, you may be able to continue.
  3. Let us know. We may be able to help.
     Open a github issue with the above log, at:
           https://github.com/netdata/netdata/issues

 FAILED  
 WARNING  It failed to install all the required packages, but installation might still be possible. 
 ABORTED  Stopping due to non-interactive mode. Fix the issue or retry installation in an interactive mode. 
Failed: NonZeroResultCode: Remote command failed with exit status 1
```

**Comment by binaryfire** [comment]
Also, when I try and install libc6-dev manually I get the following error:

```
The following packages have unmet dependencies:
 libc6-dev : Depends: libc6 (= 2.31-0ubuntu9.2) but 2.31-0ubuntu9.3 is to be installed
E: Unable to correct problems, you have held broken packages
```

**Comment by Ferroin** [comment]
Testing in a clean Ubuntu 20.04 docker container doesn’t demonstrate any of these issues. It’s likely a problem with the repositories you have configured on the systems where you are seeing these issues.

Can you please share the output of `find /etc/apt/sources.list* -type f -iname "*.list" -exec grep -viE '(^#|^$)' {} \;`? This will list all the enabled repositories on the system (because unfortunately APT doesn’t have a command to do that itself...).

**Comment by binaryfire** [comment]
Hey @Ferroin, thanks for the info. I've tried with another cloud provider's Ubuntu 20.04 image and can confirm it works. So it may be an issue specific to Hetner's image. I'll experiment a bit more and let you know.

**Comment by Ferroin** [comment]
Indeed, that would not surprise me. A lot of cloud providers add custom repositories to their Linux images to either force them to go through the provider’s local mirrors of the normal repos (and thus cut down on external bandwidth usage, which is usually a good thing for both the provider and the customer) or add some custom guest-side software for things like monitoring and backups. As a result, it’s not unusual for something that works on one provider’s image to not work on another provider’s image.

**Comment by binaryfire** [comment]
@Ferroin Is there any reason why compiled versions aren't provided for each new release? For key archs like amd-64 etc.

I'm coming from Node Exporter / Prometheus. Going from single prebuilt go binaries to having to build from source on every node the agent is installed on feels like a big step backwards :)

It would also solve most of these kind of issues.

**Comment by Ferroin** [comment]
Prometheus and Node Exporter are both written in Go, which inherently compiles to a single statically linked binary that only cares about what the kernel and CPU architecture are. This makes it trivial for them to provide prebuilt binaries for most platforms (in theory every platform that Go actually supports, though I don0t think they build for some of the more exotic ones).

Netdata, on the other hand, is written predominantly in C, which is much more complicated to provide such builds for. We do, however, currently provide a static build for 64 bit x86 systems running Linux (and have plans to expand this to also have ones for 32 and 64 bit ARM and possibly other platforms), as well as official binary packages for a variety of Linux distributions (though those are also currently only for 64 bit x86 systems with plans to add ARM packages as well). See https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart-64 or https://learn.netdata.cloud/docs/agent/packaging/installer/methods/packages for info on installing using those instead of the kickstart script.

Long-term, we have plans to overhaul how our kickstart install script works so that it will preferentially use binary packages or static builds when available, and only fall back to building locally if neither is an option for a given system.

**Comment by ilyam8** [comment]
Closing this issue since it's been resolved by using another cloud provider's Ubuntu 20.04 image.
