### ISSUE TITLE
Reorganize submenu related to block device

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#11097]
Right now Netdata has different menus bring information about hard disks on our dashboard and this information is spread around our menu.

![Screenshot_20210505_175833](https://user-images.githubusercontent.com/49162938/117190344-d4345600-adce-11eb-9131-6c4fcd47731f.png)

We are given suggestion to reorganize our menu and put this information near each other to simplify the user visualization. We also give the suggestion instead to have only one `Disks` submenu, we will rename it for `Block devices` and split it in two new menus. Our new organization will be:

-  Block devices: Inside this submenu only hard disks will be displayed ( `sda`, `sda1` ). Do we need to separate the partitions from the other devices?
- Mount points: Inside this submenu we will move all mount points that are now inside `Disks` for it.
- MD stat: Information about raid devices
- Filesystems: Information for all file systems, inside it we will have `btrfs`(already merged) and the new charts that we will bring with eBPF (`ext4`, `xfs`, `nfs`)

We will also move nearest the network submenu the information for `NFS server` and `NFS client`, the idea is to move below the current `Network Interface`

**Comment by Ferroin** [comment]
I’m strongly of the opinion that this is a case where we would benefit from having more than just a two-level hierarchy for the side menu. Essentially, I’d love to see things structured so that partitions are clearly grouped under the associated device (and this gets more important for some cases, NVMe devices have another layer between the raw device and the partitions (namespaces) that we would want to group by as well).

As far as sorting, I’d actually put MD statistics before mount points, and we probably want to group the hardware RAID adapter collectors near the disk submenu as well.

**Comment by thiagoftsm** [comment]
@Ferroin this is our main goal, but right now we as a quick win are moving these families nearest each other.

**Comment by thiagoftsm** [comment]
After to have a talking with @jacekkolasa we observed that we will also need to change React dashboard to bring everything necessary to fix this issue. To avoid postpone what is possible to bring right now, I will split this issue in small issues.

**Comment by Conna576** [comment]
Im so lost with all this, i do feel there is only harm with my phone so I should just throe away

**Comment by ilyam8** [comment]
@thiagoftsm I suggest doing the following:
 - find all related to disk/filesystem collectors
 - propose a hierarchy for them
 - do the changes (separate issues, PRs) following the hierarhy

Otherwise, it is hard to understand/review PRs like https://github.com/netdata/netdata/pull/11119

In addition, it will help us from changing priority again in again (e.g.: move Mdstat under Disks, then decided to put Mountpoints under Disks => change Mdstat priority).

**Comment by thiagoftsm** [comment]
Considering the suggestion received [here](https://github.com/netdata/netdata/pull/11119#discussion_r634099873) we will need to rename the Menu for `mdstat`.
