### ISSUE TITLE
kernel crash when set "ebpf load mode = return" in /usr/lib/netdata/conf.d/ebpf.d/network.conf

### ISSUE THREAD

**Issue by wangpei-nice** [netdata/netdata#11136]
##### Bug report summary
kernel crash when set "ebpf load mode = return" in /usr/lib/netdata/conf.d/ebpf.d/network.conf

Here is the serial port log.
[minicom-log.txt](https://github.com/netdata/netdata/files/6463743/minicom-log.txt)

##### OS / Environment

OS: Debian 10
Kernel: 4.19
Arch: X86

##### Netdata version

Netdata Version: 1.30.1

##### Installation method

curl -s https://packagecloud.io/install/repositories/netdata/netdata/script.deb.sh | sudo bash

##### Component Name

ebpf.plugin

##### Steps To Reproduce

1. Install netdata(1.30.1)
2. Modify the /etc/netdata/netdata.conf to enable the ebpf.plugin     ---> add  "[plugins]  ebpf = yes"
3. Modify the /usr/lib/netdata/conf.d/ebpf.d.conf   ---> network connections = yes
4. Modify the /usr/lib/netdata/conf.d/ebpf.d/network.conf    --->  ebpf load mode = return
5. run "systemctl restart netdata.service", then kernel crash

##### Expected behavior

The netdata.service works well, kernel would not crash.

**Comment by thiagoftsm** [comment]
Hello @wangpei-nice ,

I could recreate the problem, probably it is happening on Debian the same thing that happens on Ubuntu. The Ubuntu does not use the official Linux kernel and the patches applied created some problems, I will do a deeper investigation on this tomorrow. Please, can you confirm you are running the kernel `4.19.171-2`?

Best regards!

**Comment by wangpei-nice** [comment]
> Hello @wangpei-nice ,
> 
> I could recreate the problem, probably it is happening on Debian the same thing that happens on Ubuntu. The Ubuntu does not use the official Linux kernel and the patches applied created some problems, I will do a deeper investigation on this tomorrow. Please, can you confirm you are running the kernel `4.19.171-2`?
> 
> Best regards!

Hey @thiagoftsm , here is the result of 'uname -a'.
**Linux debian 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux**
Best Regards.

**Comment by thiagoftsm** [comment]
> **Linux debian 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux**
> 
Thank you very much!

**Comment by thiagoftsm** [comment]
@wangpei-nice the PR #11152 will fix the problem, I am already more than one hour running on Debian 10.9 kernel `4.19.171-2` without any crash, previously Netdata was crashing when the plugin started.

Have a nice week!

**Comment by wangpei-nice** [comment]
> @wangpei-nice the PR #11152 will fix the problem, I am already more than one hour running on Debian 10.9 kernel `4.19.171-2` without any crash, previously Netdata was crashing when the plugin started.
> 
> Have a nice week!

@thiagoftsm Thank you very much! Have a nice week, too!

**Comment by wangpei-nice** [comment]
Hi @thiagoftsm,

Could you elaborate on how you debug this bug? I want to learn it.

**Comment by thiagoftsm** [comment]
Hello @wangpei-nice ,

Sorry for the long time to answer you, but I was very busy these last days.
To debug everything related to eBPF, I generally use `bpftool` that is part of Linux kernel, you can find it inside `tools/bpf/bpftool`, in normal situation distributions have conditions to install it easily, but I use Slackware, so I compile from scratch. Considering that you wanna learn, I will give you the "hardest" road, because I do not think packages will help you to go so deep.

Now we have another situation that we need to deal when we are working with Linux kernels, they are not constant on time, so it will be necessary to test in different distributions, because the eBPF loader is always improving, considering this I always test on long term support kernels that have libbpf support, right now they are `4.14.x`, `4.19.x`, `5.4.x`, `5.10.x` .There are situations that  I test on other kernels too, but these are obligatory. For you see the changes in possible functions, I suggest you to take a look at elixir.bootlin.com/.

There are situations where I need to recompile the eBPF program on the distribution to detect the problem that happens, for this I clone our [kernel-collector repo](https://github.com/netdata/kernel-collector) on that distribution and I do changes inside the eBPF program, after this I compile and I move the program for `/usr/libexec/netdata/plugins.d/ebpf.d` overwritten the default installed. When netdata starts, we can take a look inside the `error.log` to discover possible problems.  The default installation will hide some information for you, so to debug and develop Netdata I suggest to compile Netdata with the following flags:

```
CFLAGS="-O1 -ggdb -Wall -Wextra -fsanitize=address -static-libasan -fno-omit-frame-pointer -Wformat-signedness -fstack-protector-all -DNETDATA_INTERNAL_CHECKS=1 -D_FORTIFY_SOURCE=2 -DNETDATA_VERIFY_LOCKS=1"
```

the ebpf.plugin has some messages inside it that helps me to debug, but I always add some aditional messages while I am developing.

This is a brief introduction about how I develop our eBPF programs, in normal situation I am testing in different kernels and I am always with elixir open to be sure I did not miss nothing between kernel versions.

The steps to bring a new eBPF program is a little bit more complicated, because I need to make PRs at `kernel-collector repo` and  `here`, but to use the `kernel-collector` repo is very useful, because our eBPF programs are  compiled inside docker images using 7 different kernels, but to test on all kernels I cited, I use Virtual Machines and my laptop.

Any doubt, please, let me know.

Best regards!

**Comment by wangpei-nice** [comment]
@thiagoftsm  It's very kind of you, thank you very much for your detailed explanation.
