### ISSUE TITLE
Netdata kickstart script no Cannot open file /etc/netdata/apps_groups.conf (doesn't exist)

### ISSUE THREAD

**Issue by zilexa** [netdata/netdata#11151]
##### Bug report summary

My boot log says: 
```
mei 16 21:15:41 Obelix ebpf.plugin[3283]: PROCFILE: Cannot open file '/etc/netdata/apps_groups.conf'

```

When I check `/etc/netdata`, there is no file `apps_groups.conf`. 
Netdata works, but I only use it to monitor a few things and I am no Netdata expert, maybe some graphs are missing. 

##### OS / Environment
```
Linux Obelix 5.11.0-17-generic #18-Ubuntu SMP Thu May 6 20:10:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=21.04
/etc/lsb-release:DISTRIB_CODENAME=hirsute
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 21.04"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="21.04 (Hirsute Hippo)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 21.04"
/etc/os-release:VERSION_ID="21.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=hirsute
/etc/os-release:UBUNTU_CODENAME=hirsute
```

##### Netdata version
I am suprised to see the kickstart script installed a nightly version, not the latest stable!
```
Version: netdata v1.30.1-150-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-lws=externaldeps/libwebsockets' 'CFLAGS=-O2' 'LDFLAGS='
Features:
    dbengine:                YES
    Native HTTPS:            YES
    Netdata Cloud:           YES 
    Cloud Implementation:    Legacy
    TLS Host Verification:   YES
Libraries:
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

##### Installation method
Kickstart script

##### Steps To Reproduce

1. Clean install of Ubuntu Budgie 21.04 on Intel Core i3, 9100 on Intel C246 chipset motherboard (Fujitsu).
2. bash <(curl -Ss https://my-netdata.io/kickstart.sh).
3. reboot.

##### Expected behavior
1. No errors. 
2. No nightly version.

**Comment by Ferroin** [comment]
The logged message isn’t an error, it’s just supposed to be informative to indicate that a user-provided config file was not found. Stuff like this can safely be ignored in the logs unless it’s for something you were explicitly trying to configure. There has been some discussion in the past about changing how this gets reported, but it’s never really gotten to the point of any conclusive plan.

As far as pulling in the nightly version by default, I would love to change this (as would a number of other people here at Netdata), but it’s a mandate from the higher ups that we should ship the nightly version by default. In general it’s actually usually pretty stable (more than enough to be useful for homelab, staging, and testing setups), though I would not generally recommend it for production usage. You can specifically ask for the stable version by passing `--stable-channel` to the installer (note that if you want to change to a stable release, you’ll need to also add `--reinstall` to tell it to do an actual reinstall instead of trying to update the existing install). In case you had not noticed, the default also includes enabling automatic updates (scheduled to run daily using either cron or a systemd timer unit, depending on what’s available on your system), you can opt out of those on install by adding `--no-updates` (I also would love to change this, but again it’s a mandate from above).

---

On an unrelated note, I love your choice of hostname.

**Comment by ilyam8** [comment]
Thanks for the detailed explanation @Ferroin

**Comment by zilexa** [comment]
Ok that makes a lot of sense... but!

Why is this shown as an actual red error in the journal on Ubuntu 21.04? I would expect it to have prio 4 (yellow) or just be normal white: 

![2021-05-17 11_43_58-Obelix — Mozilla Firefox](https://user-images.githubusercontent.com/3430004/118468741-5d1f8b80-b705-11eb-9725-c657cc681bca.png)

**Comment by ilyam8** [comment]
You are right @zilexa, it is not an error. I would say `info` level message. @thiagoftsm @vlvkobal please check

**Comment by thiagoftsm** [comment]
> You are right @zilexa, it is not an error. I would say `info` level message. @thiagoftsm @vlvkobal please check

For `ebpf.pluigin` error we are using the same code from `apps.pugin`, and we are giving information as an error, because Linux returns an error when it is not possible to open a file, I do not have objection to write this as an `info`.

**Comment by Ferroin** [comment]
I’d actually argue that if it’s a case of not being able to open the file because it doesn’t exist (that is, we get `-ENOENT` back from the `open()` call), we shouldn’t even log it for user configuration files. It’s an expected situation that there is no user configuration if they are just going with the default configuration. At minimum, I’d argue it’s a debug message, not info.

Now, that said, if it’s a case of no permissions, or some other similar error message, then _that_ should probably stay as an error, because it’s very much unexpected and likely at odds with what the user wants to do.

**Comment by ilyam8** [comment]
It depends on a file - if that is something optional, like `/etc/netdata/apps_groups.conf`, it is definitely not an error and not even a warning. You know that it is ok to not have that file 😄 

The question is - why do we have that logline in the journald logs and not in the `error.log`?

**Comment by thiagoftsm** [comment]
> It depends on a file - if that is something optional, like `/etc/netdata/apps_groups.conf`, it is definitely not an error and not even a warning (assuming _doesn't exist_ error). You know that it is ok to not have that file smile
> 
> The question is - why do we have that logline in the journald logs and not in the `error.log`?

Thank you @Ferroin and @ilyam8 , I will take a look at all C collectors and bring a PR converting the error for message.

**Comment by ilyam8** [comment]
@thiagoftsm that is the sample output from `journalctl -u netdata`

```cmd
апр 06 11:33:09 pc systemd[1]: Started Real time performance monitoring.
апр 06 11:33:09 pc netdata[12577]: SIGNAL: Not enabling reaper
апр 06 11:33:09 pc netdata[12577]: 2021-04-06 11:33:09: netdata INFO  : MAIN : SIGNAL: Not enabling reaper
апр 06 11:33:10 pc ebpf.plugin[12703]: Does not have a configuration file inside `/opt/netdata/etc/netdata/ebpf.conf. It will try to load stoc>
апр 06 11:33:10 pc ebpf.plugin[12703]: Name resolution is disabled, collector will not parser "hostnames" list.
апр 06 11:33:10 pc ebpf.plugin[12703]: The network value of CIDR 127.0.0.1/8 was updated for 127.0.0.0 .
апр 06 11:33:10 pc ebpf.plugin[12703]: PROCFILE: Cannot open file '/opt/netdata/etc/netdata/apps_groups.conf'
апр 06 11:33:10 pc ebpf.plugin[12703]: Cannot read process groups configuration file '/opt/netdata/etc/netdata/apps_groups.conf'. Will try '/o>
апр 06 11:33:40 pc systemd[1]: Stopping Real time performance monitoring...
апр 06 11:33:43 pc systemd[1]: netdata.service: Succeeded.
```

Why is ebpf in there?

**Comment by thiagoftsm** [comment]
> Why is ebpf in there?

Because we call `error`, I will either remove the `error` call or to use `info`.

**Comment by ilyam8** [comment]
The problem is it seems like our logging is not initialized at the moment or something like that, as you may notice there are few messages: reaper + ebpf. Nothing more.

The severity level is not relevant. Will discuss it.

**Comment by nodiscc** [comment]
Hi, I think this issue should not have been closed: `apps.plugin: PROCFILE: Cannot open file '/opt/netdata/etc/netdata/apps_groups.conf'` is still logged as an error.

![image](https://user-images.githubusercontent.com/3950390/227542958-00265393-202f-4231-adb1-e00bcb939b4e.png)

A fix was provided (https://github.com/netdata/netdata/pull/12385) for a similar problem with `ebpf.plugin`, but the problem is still present for `apps.plugin`. Should I open a new issue or should this one be reopened?

Netdata 1.38.1

**Comment by timdonovanuk** [comment]
Yep still an error. Don't log as error if it's not an error.
