### ISSUE TITLE
Netdata News & Features

### ISSUE THREAD

**Issue by stdedos** [netdata/netdata#11271]
The "News & Features" button sounds awfully like a "phone home" feature.
I have been explicitly trying to go away from "phone home" features, and that's on my list too.

Isn't there a way to have my installation just load stuff from itself, not communicating anywhere (except for downloading the deb packages I am)?

**Comment by OdysLam** [comment]
Hey @stdedos,

Although I understand where you coming from, in an attempt to ease your reservations, let me give you some more information.

The particular feature directly sources content from a [prismic](https://prismic.io/ and has nothing to do with analytics. 

The Netdata Agent has a single point for all analytics, and that's the `anonymous-analytics` script. If you have added the appropriate flag to disable analytics, then we are gathering no information about your agent whatsoever.

The only thing that I *think* we do gather, is that the agent is alive and/or the dashboard was accessed. This is important for us to keep track, as it's the ultimate KPI for our work. We need to know that we are delivering the features that our users want and have the feedback loop as small as possible. 

Again, the last point is just a "number". More detailed analytics (e.g OS version, enabled features, etc.) are gathered using the analytics script and can be disabled, as I noted. Please note that these analytics are **vital** for us, since it informs every single decision that we take, from what content we need to produce to what features makes sense to ship next.

Since GitHub is used for bug tracking, I will close this issue. Let's continue the discussion in our [community forums](https://community.netdata.cloud) or in our [Discord](https://discord.gg/mPZ6WZKKG2)!
