### ISSUE TITLE
get EBPF_VERSION dynamically

### ISSUE THREAD

**Issue by wangpei-nice** [netdata/netdata#11365]
##### Bug report summary

Hi netdata maintainers.
A few days ago,  netdata/packaging/ebpf_version was still v0.7.4,  I compiled netdata by running ./netdata-installer.sh. The following error occurred when I started ebpf.plugin.
![image](https://user-images.githubusercontent.com/81410079/126955430-43faa252-1380-40f2-95d3-9a81553b80fe.png)
I downloaded https://github.com/netdata/kernel-collector/releases/download/v0.7.4/netdata-kernel-collector-glibc-v0.7.4.tar.xz and there were no bpf programs about version5.4.
![image](https://user-images.githubusercontent.com/81410079/126957288-cc641e20-22fb-47e2-b34a-a0a79c0082b9.png)
Although kernel-collector v0.7.5 had fixed this, I found that netdata/packaing/ebpf_version was not updated in time until 2 days later. I have a idea to get EBPF_VERSION dynamically.

##### OS / Environment

debian 10.6

##### Netdata version

1.31.0
##### Installation method
./netdata-installer.sh

##### Component Name
area/packaging

**Comment by ilyam8** [comment]
@thiagoftsm please, take a look

**Comment by thiagoftsm** [comment]
Hello @wangpei-nice ,

We already detected this problem days ago, and we made this [PR](https://github.com/netdata/kernel-collector/pull/243/files) on `kernel-collector` repo and this [PR](https://github.com/netdata/netdata/pull/11348) here at `netdata/netdata`. The latest `nightly` already have the fix for the version `0.7.5`, but `0.7.4` had the bug.

Thanks to report!

Best regards,

Thiago
