### ISSUE TITLE
eBPF.plugin server crash on intensive cpu/ram/disk use

### ISSUE THREAD

**Issue by void4** [netdata/netdata#11380]
##### Bug report summary

My website received a lot of traffic yesterday which led to a high CPU, RAM and disk use.

This seems to have caused the netdata ebpf.plugin to crash and took down the server. /var/crash log:

https://gist.github.com/void4/8503282d6bfcff02b5b3f9ed9b4f4fce

![image](https://user-images.githubusercontent.com/11392207/127432782-c7acd45a-4fec-47bb-952b-bdd317405958.png)

![image](https://user-images.githubusercontent.com/11392207/127432802-66e5dd33-61fd-40b0-9fa8-9905452b74d0.png)

##### OS / Environment
```
Linux D82F885 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.2 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.2 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal

```

##### Netdata version
```
Version: netdata v1.31.0-142-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-lws' 'CFLAGS=-O2' 'LDFLAGS='
Features:
    dbengine:                YES
    Native HTTPS:            YES
    Netdata Cloud:           YES 
    ACLK Next Generation:    NO
    ACLK Legacy:             YES
    TLS Host Verification:   YES
Libraries:
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

##### Installation method

I used the one line bash script to install netdata.

##### Component Name

epf.plugin

##### Steps To Reproduce

unknown

##### Expected behavior

Do not let netdata crash the server. I had to restart it using my hosting providers interface.

**Comment by thiagoftsm** [comment]
This looks like something direct linked with Ubuntu :thinking: I will test here to confirm, but this would not be the first time that this happened, thank you to report.

**Comment by a-schaefers** [comment]
@thiagoftsm Why does it look like something directly linked with Ubuntu?

**Comment by a-schaefers** [comment]
@void4  How do we know that netdata crashed your server, and not that your server ran out of resources and netdata just crashed along with your server?

**Comment by void4** [comment]
> @void4 How do we know that netdata crashed your server, and not that your server ran out of resources and netdata just crashed along with your server?

I only know that this crash log preceded my server being down, I don't know more.

**Comment by thiagoftsm** [comment]
> @thiagoftsm Why does it look like something directly linked with Ubuntu?

Firstly sorry for the delay to answer.

Let me explain the motive I suspected that this could be a problem with Ubuntu kernel, but of course I do not discard this was a RAM problem as you described. Right now Ubuntu 18.04 running kernel `4.18` is the unique kernel that we are rejecting to run eBPF.plugin, because according some users report the server was crashing, but considering that eBPF runs inside a "Virtual Machine" this should not happen. Ubuntu has a special kernel, they modify the kernels from https://kernel.org applying patches, so Ubuntu is not running the same kernel that we have when we do download and compile from scratch. I ran the eBPF.plugin on a Slackware Current running kernel 5.4.x, but it did not crash and everything was normal.

How are we trying to fix this? Netdata is using an old version of libbpf, but I already have PRs ready to update our repository, I am only expecting the PR https://github.com/netdata/netdata/pull/11401 to receive another review, after this I will merge it and finally I will update the libbpf.

@void4 for while I suggest you change the file [ebpf_kernel_reject_list.txt](https://raw.githubusercontent.com/netdata/netdata/master/collectors/ebpf.plugin/ebpf.d/ebpf_kernel_reject_list.txt) that is installed in `/etc/netdata/ebpf.d/` and add your kernel there. When we update the libbpf, I will close this issue, and after this you can remove your kernel from the file.

Best regards!

**Comment by void4** [comment]
Thank you! So far the issue has not occured again.

**Comment by thiagoftsm** [comment]
Hello @void4 I am closing this issue, but if somehow the problem happens again, be free to reopen it.
