### ISSUE TITLE
mysql go plugin - wrong Buffer Pool Operations chart label

### ISSUE THREAD

**Issue by ekexcello** [netdata/netdata#11485]
##### Bug report summary

go.d plugin, mysql module has incorrect chart labeling, namely, chart displaying `mysql_local_go.innodb_buffer_pool_read_ahead (operations/s)` is labeled:

```
InnoDB Buffer Pool Bytes (mysql_local_go.innodb_buffer_pool_read_ahead)
```
should be `InnoDB Buffer Pool Operations (mysql_local_go.innodb_buffer_pool_read_ahead)` instead.

##### OS / Environment

Linux 5.10.61-gentoo x86_64 AMD

##### Netdata version

netdata v1.31.0

##### Installation method

gentoo package

##### Component Name

go.d.plugin

**Comment by ilyam8** [comment]
Hey, @ekexcello. That is an issue, indeed.

Actually, [it is `pages`](https://dev.mysql.com/doc/refman/8.0/en/server-status-variables.html#statvar_Innodb_buffer_pool_read_ahead)

> The number of pages read into the InnoDB buffer pool by the read-ahead background thread.

> page
A unit representing how much data InnoDB transfers at any one time between disk (the data files) and memory (the buffer pool). A page can contain one or more rows, depending on how much data is in each row.

**Comment by ilyam8** [comment]
Ok, I think that is "operations/s" because we have [Innodb_buffer_pool_read_ahead_rnd](https://dev.mysql.com/doc/refman/8.0/en/server-status-variables.html#statvar_Innodb_buffer_pool_read_ahead_rnd) in the same chart, which is

> The number of “random” read-aheads initiated by InnoDB.
> read-ahead
A type of I/O request that prefetches a group of pages (an entire extent) into the buffer pool asynchronously

`Innodb_buffer_pool_read_ahead` and `Innodb_buffer_pool_read_ahead_evicted` are in pages and `Innodb_buffer_pool_read_ahead_rnd` in (read-ahead) operations.
