### ISSUE TITLE
Race between short-lived processes & procfs parsing

### ISSUE THREAD

**Issue by UmanShahzad** [netdata/netdata#11512]
In https://github.com/netdata/netdata/pull/11470 we discovered an interesting scenario:

- The eBPF OOM kill chart logic uses process data that is parsed by the eBPF `process` thread, which uses a lot of similar logic to `apps.plugin` for parsing the proc filesystem.
- When testing, we created processes that would get OOM killed extremely fast, before the `process` thread could parse their entries from `procfs`.
- Because of this, the OOM kill thread was left with PIDs whose target name could not be determined, thus both effectively leaking entries and not showing the OOM kill data correctly.

Our solution so far has been to just dump the "missed" PIDs into the `"other"` dimension. But since this issue is actually more generic, it would be nice to hear what other people think about this.

This issue would appear anytime we have a PID through some means and need more data for it, but procfs parsing has not yet occurred, and the process behind it dies, but we still want to show the data.

**Comment by UmanShahzad** [comment]
Would be nice to get some feedback @ilyam8 @thiagoftsm @stelfrag @underhood @vlvkobal & others.

**Comment by underhood** [comment]
I am not sure what can be done here other than tracking the process creation through eBPF directly instead of `procfs` (and if it is feasible/not extremely dificult to get all necessary info that way)?

**Comment by UmanShahzad** [comment]
It may not be possible to get that data through eBPF because, as we discovered, structure fields are randomized in the kernel for some structures as a security feature, and the process structure is one of them.

**Comment by ilyam8** [comment]
I see 3 options:
 1. don't account for short-lived processes
 2. account using "other" dimension
 3. account using "short-lived" dimension

I think we are in agreement that "don't account" is not the way, so it is either 2 or 3.

I tend to prefer 3 over 2 for the following reasons:
 - "other" means all processes that don't fall into apps groups.
 - adding "short-lived" in there => we extend the meaning to "all processes that don't fall into apps groups and all short-lived processes".
 - having a special dimension for short-lived could be nice and more _descriptive_.

**Comment by UmanShahzad** [comment]
cc @netdata/agent

**Comment by thiagoftsm** [comment]
@UmanShahzad I remember that we discussed this when we were integrating `apps.plugin` and `ebpf.plugin`. To keep compatibility between both process, our initial choice was to use the `/proc` to show the same information for charts made by both plugins.

The other approach that we can bring, and I am already doing this to integrate `cgroup.plugins` and `ebpf.plugins` will be to create a shared memory between `eBPF.plugin` and `apps.plugin`. `eBPF.plugin will be responsible to get the data and make the process list. The unique thing we need to have in mind, it is the fact that whether it is not possible to run `eBPF.plugin`, because the kernel is very old, we need to run `apps.plugin` independent of this.

Finally I agree  with @ilyam8's suggestions.

**Comment by UmanShahzad** [comment]
Alright, I think we are in consensus that "short-lived" is a new dimension we should introduce and set to for such scenarios. I'll leave this issue open and make a PR to try to introduce writing this dimension for `apps.plugin` & ebpf's version of that code.

**Comment by stelfrag** [comment]
> This issue has been inactive for 30 days. It will be closed in one week, unless it is updated.

keep active
