### ISSUE TITLE
Multi-host cookie set by PostHog

### ISSUE THREAD

**Issue by socialityCoop** [netdata/netdata#11602]
##### Bug report summary

From time to time, when I visit Netdata interface a cookie is set by PostHog. This cookie is not a host-only cookie, but a multi-host one starting with a dot, see screenshot:
![Screenshot_20210927_141218](https://user-images.githubusercontent.com/34302244/135502778-a754dc44-7fce-458d-8b8c-e2401e15aa67.png)
After that, if I visit a CSRF-aware web app (namely, ISPConfig), that has the same main domain but different subdomain, access to the app is denied and a security event is logged there (SQL injection).

##### OS / Environment

Several VMs with versions of Debian (9,10,11) and with ISPConfig. I haven't figured out if a specific box is causing this, but I doubt.
The Netdata panels are served through an Nginx reverse proxy that deals with SSL too, as per your official instructions.

##### Netdata version

```
Version: netdata v1.31.0-329-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-lws' '--with-bundled-protobuf' 'CFLAGS=-O2' 'LDFLAGS='
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                YES
    TLS Host Verification:      YES
Libraries:
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```
##### Installation method

kickstart.sh, not much of modifications.

##### Steps To Reproduce

This is not always reproducible, I guess it depends on whether it is time for PostHog to set its cookie.
1. Visit Netdata panel.
2. Watch for a cookie by PostHog with a domain that starts with a dot.

##### Expected behavior

(I think) the cookie should be created for the specific (sub)domain that Netdata panel is on, and without any leading dot.

**Comment by andrewm4894** [comment]
Thanks @socialityCoop - PostHog is our open source (self hosted) product analytics and telemetry we have moved to recently so that we could get off Google Analytics and GTM.

I will follow up internally and with the PostHog folks and update back here when i have more info.

Thanks for letting us know.

**Comment by farconada** [comment]
same problem here
I'm got blocked by the internal WAF cause of this

**Comment by cpipilas** [comment]
@andrewm4894 any updates on this?

**Comment by andrewm4894** [comment]
@cpipilas i pinged you on this internal slack with the PH guys: https://netdata-cloud.slack.com/archives/C01F31E9PRD/p1633080866040200

I think we should ping them again maybe.

**Comment by socialityCoop** [comment]
I found a workaround that is ok for us, that is to add `--disable-telemetry --disable-cloud` on executing kickstart.sh.
We don't use cloud, for our scopes this excellent documentation by Netdata is ok:
https://learn.netdata.cloud/docs/agent/running-behind-nginx
I don't know which of the two parameters actually eliminates the cookie problem, I'll try to update the thread on this.

**Comment by andrewm4894** [comment]
Thanks @socialityCoop i think we will still defo follow up with the folks from PostHog just to be sure. 

I wonder if maybe related to these too: 

- https://github.com/PostHog/posthog-js/issues/251
- https://github.com/PostHog/posthog-js/issues/168

I guess the reason for this default maybe it mentioned here:

https://posthog.com/docs/integrate/client/js#website-vs-app

![image](https://user-images.githubusercontent.com/2178292/176882570-96be5647-2461-49e5-a82a-570055b2f966.png)

Which actually is similar to our set up of:

- https://www.netdata.cloud/
- https://community.netdata.cloud/
- https://learn.netdata.cloud/
- https://app.netdata.cloud/

Being able to tell when app users are on learn and maybe need help with the docs or can see some clear areas or patterns is really really useful for us. 

I think in your case when just using the local agent dashboard then yes it for sure maybe does not make sense for that cookie to be multi host. So i wonder if there is a way for us to have the PH cookie on the agent dashboard to be single host since realistically i can't see much use or need for why it would be. 

Agent dashboard telemetry we try to anonymize and have it as minimal as much as possible (while still being some) so i think would be a good addition to try see if we can make the cookie stricter on agent dashboard.

**Comment by socialityCoop** [comment]
Latest stable kickstart installations do not have the issue. If anyone has more info, please add.
