### ISSUE TITLE
[Bug]: Uninstaller script does not remove netdata-updater

### ISSUE THREAD

**Issue by cdzombak** [netdata/netdata#11911]
##### Bug report summary

I recently uninstalled netdata from several (~6) servers. I then noticed that the following artifacts had not been removed:

- `/netdata-updater`
- `/etc/cron.daily/netdata-updater`

##### OS / Environment

Multiple, including Raspberry Pi OS Bullseye, Raspberry Pi OS Stretch, Ubuntu Bionic, Ubuntu Xenial.

```
Linux <HOSTNAME> 4.15.0-159-generic #167-Ubuntu SMP Tue Sep 21 08:55:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.6 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.6 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

##### Netdata version

Unfortunately, as Netdata has been uninstalled, I cannot determine what version it was. I believe it was generally 1.31.0 or 1.32.0.

##### Installation method

Basic `kickstart.sh` install script.

##### Component Name

Uninstaller script installed at `/usr/libexec/netdata/netdata-uninstaller.sh`.

##### Steps To Reproduce

1. Uninstall Netdata 
2. Observe `/netdata-updater` and `/etc/cron.daily/netdata-updater` are still present on the machine.

##### Expected behavior

`/netdata-updater` and `/etc/cron.daily/netdata-updater` are removed during uninstallation.

**Comment by MrZammler** [comment]
Hi @cdzombak ! Thank you for reporting this, we will check and try to reproduce.

**Comment by georgiats** [comment]
Hi @cdzombak,
Thank you for submitting this bug here. At the moment @MrZammler is looking into it.

I understand from your [blog post](https://www.dzombak.com/blog/2021/12/Reconsidering-Netdata.html) that the reason you are trying to uninstall Netdata is to re-install it from the PackageCloud repository. 
I’m amazed you did all this work to troubleshoot. Your articulate insights and very thorough feedback are more than valuable for us. 

We are currently preparing the delivery of a new kickstart script that will restructure and improve the entire build process and its resource utilization. If you are interested, we can notify you directly as soon as this is launched, so that you can try it out in your Pis. 

In the meantime, we’d also love to initiate a conversation based on your post, so that we can better utilize your feedback to improve Netdata. Please let me know if you are open to communicating through email or our Discord server [here](https://discord.gg/kUk3nCmbtx) and let’s catch up.

**Comment by cdzombak** [comment]
> In the meantime, we’d also love to initiate a conversation based on your post, so that we can better utilize your feedback to improve Netdata. Please let me know if you are open to communicating through email or our Discord server here and let’s catch up.

I'd be happy to chat via email; you can contact me at chris@dzombak.com. Thanks!

**Comment by ilyam8** [comment]
I believe this has been fixed.
