### ISSUE TITLE
[Bug]: Netdata installer fails on Synology DSM 7 due to missing os-release file

### ISSUE THREAD

**Issue by timrettop** [netdata/netdata#12068]
### Bug description

The netdata installer script and several github references indicate netdata can be installed in Synology natively using a static build described here: 
https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart#static-builds

Details on specific tweaks to complete the install are documented here: 
https://learn.netdata.cloud/docs/agent/packaging/installer/methods/synology

However following the first guide to attempt a static-only installation fails with the following output. 
```
tim@DS1621plus:~$ sh kickstart.sh --static-only

 ABORTED  Cannot find an os-release file ...

Password:
```

It seems that the installer is not reaching the point of attempting the static install because it cannot find an os-release file in /etc or in /usr/lib and is aborting. 

I was able to work around this by creating a dummy file, I used the following: 
```
$ cat /etc/os-release
NAME="Synology"
VERSION="DSM 7"
ID=synology
ID_LIKE=synology
VERSION_ID="7.0"
```

As I'm completing this bug report I'm seeing a reference to a kickstart-static64.sh script, which I wasn't aware of, maybe this is the recommended method of install, however I don't see any references to that script in the docs. 

### Expected behavior

The installer would proceed to attempt a static-only installation as described in the Synology netdata docs, or the docs would indicate to use a different script. 

### Steps to reproduce

1.
2.
3.
...

### Installation method

kickstart.sh

### System info

```shell
tim@DS1621plus:~$ uname -a; grep -HvE "^#|URL" /etc/*release
Linux DS1621plus 4.4.180+ #42218 SMP Mon Oct 18 19:15:51 CST 2021 x86_64 GNU/Linux synology_v1000_1621+
/etc/os-release:NAME="Synology"
/etc/os-release:VERSION="DSM 7"
/etc/os-release:ID=synology
/etc/os-release:ID_LIKE=synology
/etc/os-release:VERSION_ID="7.0"
```

### Netdata build info

```shell
$ /opt/netdata/bin/srv/netdata -W buildinfo
Version: netdata v1.33.0-9-g162f2b62b
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--without-bundled-protobuf' '--with-bundled-libJudy' 'CFLAGS=-static -O3 -I/openssl-static/include' 'LDFLAGS=-static -L/openssl-static/lib' 'PKG_CONFIG_PATH=/openssl-static/lib/pkgconfig'
Install type: kickstart-static
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

**Comment by abl** [comment]
Just tried to set this up on DSM 6.2.1 and had the same issue and same resolution.

**Comment by ilyam8** [comment]
I see that having either `/etc/os-release` or `/usr/lib/os-release` on Linux is hard requirement in our installer script:

https://github.com/netdata/netdata/blob/4d9ccc1b3d87086ed4fead4eac9531a8d2dea35f/packaging/installer/kickstart.sh#L391-L403

A quick search on google: Synology DSM has not that file, there is `/etc/VERSION` but it is different, ex.:

```cmd
bash-4.3# cat /etc/VERSION
majorversion="6"
minorversion="2"
productversion="6.2.1"
buildphase="GM"
buildnumber="23824"
smallfixnumber="4"
packing="iSCSI"
packing_id="1"
builddate="2018/12/25"
buildtime="16:58:15"
```

**Comment by ilyam8** [comment]
@timrettop @abl halp! 

Since you guys have installed Netdata using our one-line install script - is [Install Netdata on Synology](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/synology) valid? Did you have to do 1-4 steps from the [Run as netdata user](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/synology#run-as-netdata-user) section? That guide is (kind of) maintained by Netdata's community and is likely out-of-date. Was thinking it is a good chance to update it.

**Comment by abl** [comment]
The documented approach is probably good, but I did something slightly different - I created the netdata user/group first. Due to how Synology handles users, you can't remove a user from the "Users" group in the UI, and it's always the default group...so I had to go edit `/etc/passwd` and `/etc/group` to fix that. Since the default group is "Users", not netdata, I also had to:

```
sudo find /opt/netdata -group users -exec chgrp netdata {} \;
```

to clean things up. The config file suggested that files would be written as `netdata:users` so I edited the group owner.

I haven't yet sorted out the best way to do startup - DSM 6.2.1 doesn't have an `rc.local` - I was going to take a look at Tailscale and SynoCommunity to see how they do it for packaged services.

**Comment by abl** [comment]
oh, and the install script will have issues because it tries to `sudo sh` a few things - I'm not sure whether those scripts are necessary, when I saw the failures I CTRL+C'd out and edited sudoers so it'd work.

**Comment by Ferroin** [comment]
> I see that having either `/etc/os-release` or `/usr/lib/os-release` on Linux is hard requirement in our installer script:
> 
> ttps://github.com/netdata/netdata/blob/4d9ccc1b3d87086ed4fead4eac9531a8d2dea35f/packaging/installer/kickstart.sh#L391-L403

This was not actually intentional, and is a bug in and of itself. Intended behavior here is to just skip trying native packages if we can’t determine the distro we’re running on, but obviously that’s not the current behavior.

I’ll try to get a PR up to fix this today, though it may be Monday before I get to it (I’m unusually busy today for a Friday).

---

> The documented approach is probably good, but I did something slightly different - I created the netdata user/group first. Due to how Synology handles users, you can't remove a user from the "Users" group in the UI, and it's always the default group...so I had to go edit `/etc/passwd` and `/etc/group` to fix that. Since the default group is "Users", not netdata, I also had to:
> 
> ```
> sudo find /opt/netdata -group users -exec chgrp netdata {} \;
> ```
> 
> to clean things up. The config file suggested that files would be written as `netdata:users` so I edited the group owner.

This one is unfortunately on DSM, we do explicitly ask for the creation of a system user when creating the `netdata` user, which _should_ bypass such hard-coded behavior on any sanely designed system.

> I haven't yet sorted out the best way to do startup - DSM 6.2.1 doesn't have an `rc.local` - I was going to take a look at Tailscale and SynoCommunity to see how they do it for packaged services.

Synology apparently uses Upstart, which I do not think we actually provide a service definition for (because in general, essentially nobody uses Upstart anymore, they’ve all moved to systemd because it is generally better).

Possibly see https://gist.github.com/SanCoder-Q/f3755435e6e8bd46ba95bf0ec54ae1a4 for suggestions on how to handle this generically.

> oh, and the install script will have issues because it tries to sudo sh a few things - I'm not sure whether those scripts are necessary, when I saw the failures I CTRL+C'd out and edited sudoers so it'd work.

It’s not well documented, but the _current_ one-line install command can be modified like this:

```
wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sudo sh /tmp/netdata-kickstart.sh
```

To just run the whole script as root instead of prompting for root privileges when it needs them. We don’t really recommend doing this (potentially building software as root is never a good idea), but it may avoid any issues with the script itself invoking `sudo`.

Alternatively, if there is some better command on DSM for privilege escalation, you can set `ROOTCMD` to that command (including any required options) before running the installer and it will use that instead of `sudo`.
