### ISSUE TITLE
[Bug]: render exproting progress  on admin page but exporting action does not works at all 

### ISSUE THREAD

**Issue by icoco** [netdata/netdata#12115]
### Bug description

 I try to exporting data to influxdb, I follow the guide 'https://learn.netdata.cloud/guides/step-by-step/step-09#tweak-the-database-engines-settings'

but after struggle with many way, I think that seem is no way to do. 

I also confuse with the page render feature on admin page, although the export configuration is wrong and  influxdb not  running at all, but the exporting feature on admin page (localhost:19999) still rendering, it looks  streaming success but it does not indeed 

not sure why does this, why not show a error message that give useful tips ? 

another question, how to exporting data to influxdb, where can find the solution ? any helps is much appreciated . 

### Expected behavior

should exporting(store) data in influxdata but it does not 

### Steps to reproduce

1. enable exporting and config the export target 
2.
3.
...

### Installation method

docker

### System info

```shell
Linux
```

### Netdata build info

```shell
latest
```

**Comment by ilyam8** [comment]
Hi, @icoco. 

> but the exporting feature on admin page (localhost:19999) still rendering

Can you post a screenshot?

**Comment by vlvkobal** [comment]
> I try to exporting data to influxdb, I follow the guide '[learn.netdata.cloud/guides/step-by-step/step-09#tweak-the-database-engines-settings](https://learn.netdata.cloud/guides/step-by-step/step-09#tweak-the-database-engines-settings)'

How can this guide help you with exporting to InfluxDB? It's about the [database engine](https://learn.netdata.cloud/docs/agent/database/engine), not about the [exporting engine](https://learn.netdata.cloud/docs/agent/exporting). As you can see in the [supported databases](https://learn.netdata.cloud/docs/export/external-databases#supported-databases) list, you can use either the [Graphite](https://learn.netdata.cloud/docs/agent/exporting/graphite) or the [Prometheus remote write](https://learn.netdata.cloud/docs/agent/exporting/prometheus/remote_write) exporting connector to send metrics to InfluxDB.

**Comment by ilyam8** [comment]
Closing due to no response and the high possibility that @icoco mistook guides.

@icoco the one you need (as @vlvkobal correctly mentioned) is [Export metrics to external time-series databases](https://learn.netdata.cloud/docs/export/external-databases#supported-databases).

You can use one of the following connectors when exporting to InfluxDB:
 - [Graphite](https://learn.netdata.cloud/docs/agent/exporting/graphite)
 - [Prometheus remote write](https://learn.netdata.cloud/docs/agent/exporting/prometheus/remote_write)

If you still experiencing the problem, provide more info:
 - error message you get
 - InfluxDB version
 - exporting configuration

---

>  but the exporting feature on admin page (localhost:19999) still rendering

That sounds like you click on the "Export a Netdata snapshot" or "Print the dashboard" button.
