### ISSUE TITLE
[Bug]: Offline-Installation no longer possible with new installer, missing --local-files option

### ISSUE THREAD

**Issue by psuter80** [netdata/netdata#12111]
### Bug description

according to the documentation at https://learn.netdata.cloud/docs/agent/packaging/installer/methods/offline there should be a `--local-files` option to allow the installation of netdata on air-gapped or offline systems but it seems this option was lost with the introduction of the new installer. 

the message from the current installer when running the kickstart.sh command shown in the documentation is: 
`WARNING  Passing unrecognized option '--local-files' to installer script. If this is intended, please add it to $NETDATA_INSTALLER_OPTIONS instead.`

### Expected behavior

Please re-implement this option to allow offilne installation or update the documentation with the necessary steps to get netplan to install on an offline system. 

### Steps to reproduce

1. try to follow instructions at https://learn.netdata.cloud/docs/agent/packaging/installer/methods/offline

### Installation method

kickstart.sh

### System info

```shell
any linux system
```

### Netdata build info

```shell
anything from #11764 or newer
```

**Comment by psuter80** [comment]
a workaround or maybe better method for offline installations seems to be to use a pre-packaged run file available from the releases download section on github. This option should be mentioned in the offline installation documentation as it seems to be a good solution to install a stable release on a system where we can't track daily updates.

**Comment by Ferroin** [comment]
Indeed, the documentation for the offline install functionality needs updated and unfortunately somehow got missed with the release of the new kickstart script.

There are plans to implement offline install support in the new script, but they have so far been lower priority than the bugs that have been found in the script since it was released, but those have largely been taken care of at this point, so I (or someone else on the agent SRE team) should be picking this up in the near future. The plans currently are to do this completely from scratch in a way that should be much easier to work with (including being able to use the script to prepare all the files needed for an install).

**Comment by Ferroin** [comment]
https://github.com/netdata/netdata/pull/12809 will re-add basic support for offline installation of static builds, albeit with a completely new mechanism for handling all of this that should make things _much_ easier to work with.

For native packages, we have no plans to implement special handling, though our packages _should_ work fine with normal tooling for that type of thing (such as `apt-offline` on Debian/Ubuntu).

For local builds, there are currently no plans to work on adding support for offline installs, as the required changes would be complex and very invasive, and the decision from the engineering and product teams is that it’s not currently worth the required effort (however, if we _do_ implement support for this, it should work just like the above-mentioned support for static builds).

Given all of this, I’m going to update the above-mentioned PR so that it is listed as fixing this issue.
