### ISSUE TITLE
Measure performance impact of ML on the agent

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata#12173]
#### Summary

- It is crucial to measure the performance impact of ML (anomaly detection) on the agent.
- This ticket is to perform these measurements and share the resulting numbers 
- Performance impact includes CPU & Memory (but also other system resources which may be impacted)

- The test should compare the same system with ML vs without ML
- The test should operate using the current default ML configuration parameters

**Comment by cpipilas** [comment]
I think it's also related with https://github.com/netdata/product/issues/2719

**Comment by shyamvalsan** [comment]
Snapshots from @erdem2000 testing so far

https://drive.google.com/drive/folders/1NsjPDun_Yexjr1UlN2NhYgoYpEDtbwXe

Visually there's not a lot of difference here, currently exploring if there's a more concrete way of measuring the difference.

**Comment by andrewm4894** [comment]
@k-manolis hey im wondering if we would be able to use the terraform and ansible work you have been doing to create and configure the various vm's and configs we would need to do this in a fully automated and repeatable way. 

idea would be to create the following nodes, all claimed into a new space in staging:

- `ml-stress-enabled`: a `n2-standard-2` instance using ubuntu with ml enabled and default params.
- `ml-stress-disabled`: a `n2-standard-2` instance using ubuntu with ml disabled.
- `ml-stress-parent`: a `n2-standard-8` instance using ubunutu with ml enabled for all children streaming to it.
- `ml-stress-child[1-10]`: 10 `n2-standard-2` instances using ubunutu with ml disabled and streaming to `ml-stress-parent`.

Once they are all up and running we can then measure the impact using netdata cloud itself to do the comparisons.

Then we will be able to build on and extend this code to automatically do similar or related experiments in the future.

**Comment by shyamvalsan** [comment]
cc: @ktsaou

**Comment by andrewm4894** [comment]
FYI These nodes all live in here: https://staging.netdata.cloud/spaces/mlstress/rooms/general/overview#_f=

For example, you can indeed see the different cpu usage profile on the parent (orange) that is running ml on itself and its 10 children. 

![image](https://user-images.githubusercontent.com/2178292/157867475-7ebaa5f8-4f94-4813-993e-b9dc9ee48e3e.png)


@k-manolis can you invite @ ktsaou too if have not already?

**Comment by andrewm4894** [comment]
also big shout out to @k-manolis for automating all this via terraform and ansible! this will be very very useful to enable us to quickly iterate on stress testing and experimental set ups like this in a repeatable and consistent way. 

and the whole set up is something we'd love to wrap up into a public repo and some tutorials or blog posts or webinars to help users who would like to automate thier own infra and config management via terraform and ansible.

**Comment by ktsaou** [comment]
Guys, what we are saying is that the orange spikes on the chart posted above, come from ML training?

If yes, we have to make the work spread over time. There should be no spikes at all.

So, after each metric training, to calculate the sleep time to start the next one, we have to take into account the remaining time and the number of metrics remaining to be trained. So, depending on how fast it is, it should sleep a different amount of time to complete the job on time.

What do you think?

**Comment by vkalintiris** [comment]
> What do you think?

That was the initial implementation. The reason we changed this is because training of all dimensions would take at least `[ml] TrainEvery = xxx` seconds. FWIW, I believe that the previous implementation was the better approach.

**Comment by shyamvalsan** [comment]
@andrewm4894 @ktsaou I think spreading out the training is the right thing to do - even if it means that training *all* dimensions would take at least `TrainEvery` seconds (which is 1 hour by default). Once the system is up and running shouldn't the effect of taking a little longer to train all dimensions be near negligible. 

Do you disagree? What am I missing here?

**Comment by andrewm4894** [comment]
howdy - i have a feeling this might be running from a previous branch that did not have the latest 'spread the cost' optimizations from @vkalintiris 

https://github.com/netdata/analytics-bi/blob/master/ansible/ansible-netdata-branch-role/defaults/main.yml#L1

@k-manolis would we be able to update it all to use netdata nightly by default everywhere? 

(i have a feeling i originally asked you to use that branch so that we could test the highlight ordering on staging - but all PR's been merged now so would be cleanest i think to try set all defaults to use netdata nightly).

**Comment by vkalintiris** [comment]
> howdy - i have a feeling this might be running from a previous branch that did not have the latest 'spread the cost' optimizations from @vkalintiris

This is indeed an out-of-date branch but it does include the scheduling changes we are discussing in this thread.

**Comment by andrewm4894** [comment]
> This is indeed an out-of-date branch but it does include the scheduling changes we are discussing in this thread.

I wonder then if could be a sign that the scheduling changes might not be behaving as expected on the parent for some reason. I'll work with @k-manolis to make sure its all defaulting to nightly and default config params to begin with and once we sure on that we can dig into this if those spikes stay so pronounced.

**Comment by andrewm4894** [comment]
actually i was wrong - above is all using nighties on master. 

@vkalintiris if i look at my own latest devml node i see this profile:

![image](https://user-images.githubusercontent.com/2178292/158185697-30e75c43-6aee-4da1-8144-4c95830694c3.png)

So i think it is being spread out better than before but just gets exaggerated on a parent node where you have 10 of them on same schedule.

As another example here are my 5 devml nodes over last 6 hours, where you can see the "bumps". The peak of the bumps are still pretty small but i wonder if there is more tweaks we can do here perhaps. 
 
![image](https://user-images.githubusercontent.com/2178292/158186891-d0f7b9b7-ad3c-435e-ac81-edd532d46961.png)

@vkalintiris I'm unsure where this leaves us. Are you able to see similar behaviour on some of your own nodes?

**Comment by vkalintiris** [comment]
> @vkalintiris I'm unsure where this leaves us. Are you able to see similar behaviour on some of your own nodes?

Yes, that's the _expected_ behavior. The current scheduling policy is to start training a dimension as soon as it becomes available for training.

The older scheduling policy (it was removed several months ago), was to spread out the training of each dimension over the duration specified by the `TrainEvery` option.

We switched from the older scheduling policy to the new one, because it would finish training the "entire" node in a shorter amount of time.

However, if the bumps we are seeing are not desirable, we'll have to revert back to the old scheduling policy.

**Comment by ktsaou** [comment]
@vkalintiris could you please explain how ML works in the agent?

From the code I see the following (correct me if my conclusions are wrong):

I see there is a Training and a Detection thread per host (per child and parent).
https://github.com/netdata/netdata/blob/69ea17d6ec534e1ed796a92fd042bd76a3ca9215/ml/Host.cc#L500-L503

Question 1: Why you need a detection thread? Just to fill the detection chart?
Question 2: I think the detection thread is not properly aligned in time. It may lose a second every some hours. You sleep for 1 second on every iteration, without taking into account the time it needs to execute the loop. Especially on weak devices this will leak noticeable time. There are C functions to get a properly aligned heartbeat in netdata. But I don't know if you need them here.

Training works like this:
https://github.com/netdata/netdata/blob/69ea17d6ec534e1ed796a92fd042bd76a3ca9215/ml/Host.cc#L360-L379

1. You calculate a slot of time to train a dimension, based on `[ml].train every * [global].update_every / (dimensions + 1)`
2. You start training a dimension
3. If it finishes before the allocated slot of time expires, you sleep for the remaining time

This should give you a uniform distribution. The fact that it does not bothers me though. Is the merged code to master the one that produced the charts above? On my RPIs I don't have these spikes.

**Comment by vkalintiris** [comment]
> Question 1: Why you need a detection thread? Just to fill the detection chart?

The detection thread detects anomaly events (and saves them when to the DB when they occur), calculates anomaly rates, and computes a number of stats to present in charts.

> Question 2: I think the detection thread is not properly aligned in time. It may lose a second every some hours. You sleep for 1 second on every iteration, without taking into account the time it needs to execute the loop. Especially on weak devices this will leak noticeable time. There are C functions to get a properly aligned heartbeat in netdata. But I don't know if you need them here.

You're right. This effectively matters only for the data that we feed into the charts, not the anomaly events and the anomaly rates. The charts was the last functionality that I added hence the lack of proper per second alignment. I'll post a small PR to fix it.

> ...
> This should give you a uniform distribution. The fact that it does not bothers me though. 

Correct, but the "uniform" distribution is located near the beginning of each training iteration.

Let's assume that each host has X dimensions and training one dimension takes 1% of CPU time. `-` denotes 1 second where we didn't have to train any dimension, and `^` a 1 second period where we trained 1 dimension.

For 1 host, we'll get a peak CPU usage of 1%:

```
Host 1: --------^^^^--------^^^^--------^^^^--------^^^^
================================================================
% CPU : --------1111--------1111--------1111--------1111
```

For 4 hosts, we'll get something like this:

```
Host 1: --------^^^^--------^^^^--------^^^^--------^^^^--------
Host 2: ---------^^^^--------^^^^--------^^^^--------^^^^-------
Host 3: ------^^^^--------^^^^--------^^^^--------^^^^--------^^
Host 4: -------^^^^--------^^^^--------^^^^--------^^^^--------^
================================================================
% CPU : ------1234321-----1234321-----1234321-----1234321-----12
```

ie. CPU spikes.

If we were to spread out training over the entire `TrainEvery` duration, we'd effectively "spread" out the CPU spikes in the remaining `-` seconds. Some seconds would still have the same maximum/peak CPU usage because every host might happen to be training a dimension at the same second. However, I believe this would be much less pronounced than what we get from the current scheduling approach.

> Is the merged code to master the one that produced the charts above?

No. However, the code responsible for these spikes was merged in the branch that Andrew tested.

> On my RPIs I don't have these spikes.

Can you claim the node and share a link? Otherwise, you could copy/paste a 3h screenshot of `apps.cpu.netdata` and `anomaly_detection.training_stats_<machine-guid>` (Anomaly advisor -> training stats on the RHS menu).

**Comment by ktsaou** [comment]
> The detection thread detects anomaly events (and saves them when to the DB when they occur), calculates anomaly rates, and computes a number of stats to present in charts.

When you say "anomaly events" you mean "node level anomalies" or "per metric data collection outliers" (the ones that are stored in the database for every point) ?

Since all these are separate threads, we should be able to measure their resource utilization and have a dedicated chart for the CPU resources consumed from ML threads. So, it shouldn't be statistical. We can be very accurate about this.

> If we were to spread out training over the entire `TrainEvery` duration, we'd effectively "spread" out the CPU spikes in the remaining `-` seconds. Some seconds would still have the same maximum/peak CPU usage because every host might happen to be training a dimension at the same second. However, I believe this would be much less pronounced than what we get from the current scheduling approach.

To tell you the truth, I don't really get this. All `^` should be spread in `TrainEvery`. They shouldn't be together. Like this:

```
Host 1: ^---^---^---^----^---^---^---^----^---^---^---^----^---^---^---^----
        | TRAINEVERY     | TRAINEVERY     | TRAINEVERY     | TRAINEVERY     |
```

And I understand that multiple hosts will train together, like this:

```
Host 1: ^---^---^---^----^---^---^---^----^---^---^---^----^---^---^---^----
Host 2: ^---^---^---^----^---^---^---^----^---^---^---^----^---^---^---^----
        | TRAINEVERY     | TRAINEVERY     | TRAINEVERY     | TRAINEVERY     |
```

So, we may have to add an initial randomness of a few ms per host, to make it like this:

```
Host 1: ^---^---^---^----^---^---^---^----^---^---^---^----^---^---^---^----
Host 2: -^---^---^---^----^---^---^---^----^---^---^---^----^---^---^---^----
        | TRAINEVERY     | TRAINEVERY     | TRAINEVERY     | TRAINEVERY     |
```

> > Is the merged code to master the one that produced the charts above?
> 
> No. However, the code responsible for these spikes was merged in the branch that Andrew tested.

Please try to avoid this. We should all be testing the same thing. Now, my experience is completely different from Andy's.

> Can you claim the node and share a link? Otherwise, you could copy/paste a 3h screenshot of `apps.cpu.netdata` and `anomaly_detection.training_stats_<machine-guid>` (Anomaly advisor -> training stats on the RHS menu).

All the nodes here:

https://app.netdata.cloud/spaces/netdata-people/rooms/netdataatplaka/overview

![image](https://user-images.githubusercontent.com/2662304/158362503-8732a7f8-7ed7-482e-860e-e7c1fa43d4ff.png)

Please try to measure the resource usage for the ML threads. It is not scientific to measure the performance like this. Really a lot are happening at the agent and we can't really tell. Especially when you view the dashboard of an agent, data queries significantly influence the overall usage.

**Comment by ktsaou** [comment]
Also, I see you have structured the anomaly charts like this:

```json
                "anomaly_detection.training_stats_d5874cc6-1afb-11e6-859b-b827ebd15026":                {
                        "id": "anomaly_detection.training_stats_d5874cc6-1afb-11e6-859b-b827ebd15026",
                        "name": "anomaly_detection.training_stats_d5874cc6_1afb_11e6_859b_b827ebd15026",
                        "type": "anomaly_detection",
                        "family": "training_stats",
                        "context": "anomaly_detection.training_stats",
                        "title": "Training step statistics for host pi2 (anomaly_detection.training_stats_d5874cc6_1afb_11e6_859b_b827ebd15026)",
                        "priority": 39188,
                        "plugin": "netdata",
                        "module": "ml",
                        "enabled": true,
                        "units": "milliseconds",
                        "data_url": "/api/v1/data?chart=anomaly_detection.training_stats_d5874cc6_1afb_11e6_859b_b827ebd15026",
                        "chart_type": "line",
                        "duration": 46084,
                        "first_entry": 1647296098,
                        "last_entry": 1647342180,
                        "update_every": 2,
                        "dimensions": {
                                "total_training_duration": { "name": "total_training_duration" },
                                "max_training_duration": { "name": "max_training_duration" }
                        },
                        "chart_variables": {
                        },
                        "green": null,
                        "red": null,
                        "alarms": {

                        },
                        "chart_labels": {

                        }

                },
```

You have set the `title` to human readable and both `id` and `name` with GUIDs.
I suggest you also set the `name` to be human readable too, like this:

```json
                "anomaly_detection.training_stats_d5874cc6-1afb-11e6-859b-b827ebd15026":                {
                        "id": "anomaly_detection.training_stats_d5874cc6-1afb-11e6-859b-b827ebd15026",
                        "name": "anomaly_detection.training_stats_pi2",
                        "title": "Training step statistics (anomaly_detection.training_stats_pi2)",
```

Please note that the chart `name` is added to the `title` during json generation. It is not there really (don't add it in the code). Titles should never include instance information because this information is misleading in composite charts at the overview dashboard. So, the title of all charts of the same `context` should be exactly the same. Use `name` to provide human readable instance information.

**Comment by vkalintiris** [comment]
@ktsaou Good points, I'll address some of them in the following day(s) because I was busy with https://github.com/netdata/netdata/issues/12316 last week.

@andrewm4894 I built an agent that randomly samples the extracted features, ie. we perform feature extraction of the 4-hour window and randomly select:

1. 2000 features,
2. MaxTrainingSamples / LagN -> 4 * 3600 / 5 = 2880 features, and
3. 3600 features.

Let it run for ~10 hours:

```
Dimensions:
        2650
Seconds:
        38575
Anomaly bits:
        102223750
Differing anomaly bits:
        2880 samples: 21589 (MaxTrainingSamples / LagN)
        2000 samples: 39902
        3600 samples: 20301
AB %-error:
        2880 samples: 0.021% (MaxTrainingSamples / LagN)
        2000 samples: 0.039%
        3600 samples: 0.02%
```

![ml-perf](https://user-images.githubusercontent.com/25480816/159238679-38c83c70-2b2e-4222-9485-234ed5b88bc7.png)

Doing some back-of-the-envelop calculations, I believe this will reduce **peak** CPU-usage by ~60%.

**Comment by andrewm4894** [comment]
@vkalintiris i love this and it is exactly what i would have expected in terms of the ML - most of the feature vectors in any training window are fairly redundant and likely not actually all that important of contributing to the model fit. As long as we manage to see enough of the [high leverage points](https://en.wikipedia.org/wiki/Leverage_(statistics)) (in terms of representing the different normal patterns on the node) that's the main thing and we are safe to assume they are fairly randomly spread out in the training window.

Ultimately i think making this a param like `train data sample percent = 0.2` that the user can play with will be another very useful lever to make available to the end user. But for now i think the formula of `MaxTrainingSamples / LagN` is a reasonable constant if that makes implementation easier to begin with. 

Just mentioning to return to later - another way to get the ability to have users pick and choose essentially the performance profile they are comfortable with would be another param like `retrain models sample percent = 0.5` which would mean that during every (re)training window you actually don't bother retraining all the models you just randomly retrain some random 50%. Eventually then over time all models will get trained but this just becomes another performance lever users could play with. 

So for example if a user was to set `train data sample percent = 1.0` and `retrain models sample percent = 1.0` then they would be getting the original implementation of using all the data and continually retraining all the models. Whereas something like `train data sample percent = 0.2` and `retrain models sample percent = 0.5` would give much better overhead performance characteristics and resulting models that are probably not all that different in the longer run sense of average performance and "quality" of the ML.

**Comment by andrewm4894** [comment]
cross linking this discussion since this is essentially a version of what @vkalintiris has done above.

https://github.com/netdata/netdata/discussions/12350

**Comment by shyamvalsan** [comment]
@ktsaou @andrewm4894 @vkalintiris 

Considering the further performance gain from @vkalintiris [latest changes](https://github.com/netdata/netdata/pull/12494) and the testing and dogfooding done so far, are there any pending actions on this ticket?

**Comment by vkalintiris** [comment]
> Considering the further performance gain from @vkalintiris https://github.com/netdata/netdata/pull/12494 and the testing and dogfooding done so far, are there any pending actions on this ticket?

Nothing else I can think of from my side. The chart title/id/context changes mentioned by @ktsaou will be updated in a separate PR.
