### ISSUE TITLE
Exclude constant dimensions from ML training

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata#12180]
#### Summary

- Currently, the anomaly detection K means algorithm is trained for all metrics that are not excluded via the config option (charts to skip from training)

- This includes metrics that remain at the same value (zero for example) all the time, or nearly all the time.

- The objective of this ticket is to exclude from training constant metrics which never change in value

**Comment by ktsaou** [comment]
@vkalintiris I saw you kept the 1st training. Why? What do we gain by having the first training done on every metric?

**Comment by vkalintiris** [comment]
> @vkalintiris I saw you kept the 1st training. Why?

If we skip training entirely, we won't have a trained model in order to compute the anomaly score if/when the dimension's value change at some point in the future.

I mulled over the idea of generating one on the spot, ie. as soon as we find that a dimension is no longer constant, but training is a time consuming operation and we can't block the thread that calls `rrdset_done` that long.

> What do we gain by having the first training done on every metric?

100% correct anomaly bits/rates/events.

For example, suppose that some user out there has a custom collector that creates many dimensions that remain constant all the time, except if some rare event happens. If our implementation is not accurate, then we might not be able to identify anomaly events with the correct anomaly bits/rates.

**Comment by ktsaou** [comment]
> For example, suppose that some user out there has a custom collector that creates many dimensions that remain constant all the time, except if some rare event happens. If our implementation is not accurate, then we might not be able to identify anomaly events with the correct anomaly bits/rates.

So, let me understand.

1. We have a dimension that is always constant. Let's say 100.
2. We train a model for it.
3. The dimension now starts having variable values. 102, 120, 200, 90, etc.
4. Are they going to be outliers all of them until the next training?

If they are going to be outliers all of them, then just mark them as such.
If they are not going to be outliers, then don't mark them as such.

How the training will help? Is it possible that the training will detect some values as outliers and some as not outliers?

**Comment by vkalintiris** [comment]
> > For example, suppose that some user out there has a custom collector that creates many dimensions that remain constant all the time, except if some rare event happens. If our implementation is not accurate, then we might not be able to identify anomaly events with the correct anomaly bits/rates.
> 
> So, let me understand.
> 
> 1. We have a dimension that is always constant. Let's say 100.
> 2. We train a model for it.
> 3. The dimension now starts having variable values. 102, 120, 200, 90, etc.
> 4. Are they going to be outliers all of them until the next training?
> 
> If they are going to be outliers all of them, then just mark them as such. If they are not going to be outliers, then don't mark them as such.
> 
> How the training will help? Is it possible that the training will detect some values as outliers and some as not outliers?

@andrewm4894 is Costa's suggestion sound from an ML perspective?

**Comment by shyamvalsan** [comment]
I don't think it makes sense to train a K means clustering model for a constant dimension. Our default is K=2, but our inputs are all going to be the same resulting in a single centroid equal to the input dimension. 

In the case above, the model would only become useful when it has started seeing the non-constant dimensions (102,120,200,90 etc) so shouldn't we just wait for the flag to flip before training?

**Comment by shyamvalsan** [comment]
In any case we should check what happens in dlib where we configure K=2 but the input for training is all constant dimensions, one of the centroids will be the input dimension, but what about the other? Will it be 0, initialized to some random number? Does dlib default to K=1? 

I ran a quick test in Python using the Kmeans implementation in Sklearn and for the above example, it actually put 102, 120 etc into the same cluster - so no anomaly was detected. But this may vary by implementation.

**Comment by ktsaou** [comment]
Let's make the example a little better:

1. We have a dimension that is always constant. Let's say 100.
2. We train a model for it.
3. The dimension now starts having variable values. 102, 102, 102, 102, 120, 120, 120, 120, 105, 105, 105, 105, etc.
4. Are they going to be outliers all of them until the next training?

If they are going to be outliers all of them, then just mark them as such.
If they are not going to be outliers, then don't mark them as such.

How the training will help? Is it possible that the training will detect some values as outliers and some as not outliers?

In this example, the value changes and remains constant for some time. Then changes again and remains constant for some more time, etc.

**Comment by ktsaou** [comment]
> The trade off is that if 2 or 200 faults occur, the anomaly bit will in both cases just jump to 1. The ML has no understanding of the difference between 2 or 200 (for now).

@andrewm4894 so what about this process:

1. If a metric is constant, we don't train a model
2. If the metric changes value, we mark it anomalous (hard-coded) to the end of the training window
3. During the next training window, the metric is no longer constant, so we train a model
4. For the next hour we predict based on the training
5. If the metric becomes constant again, we just to point 1

This will avoid the first training and actually any metric can turn constant and not-constant during runtime. Every hour we will re-evaluate which metrics are constant (considered anomalous if they change value), or variable (train a model).

**Comment by andrewm4894** [comment]
Dlib author says constant metrics would just have the 2 cluster centers be identical, which is perfect for this edge case for us. https://github.com/davisking/dlib/issues/2525

**Comment by andrewm4894** [comment]
> 
> @andrewm4894 so what about this process:
> 
> 1. If a metric is constant, we don't train a model, and we flag it as `ML_CONSTANT` and remember the constant value (e.g. 100)
> 2. If the metric changes value (<>100), we mark that collection anomalous (hard-coded)
> 3. At the time we need to re-train, if a metric previously marked as `ML_CONSTANT` was found at least once anomalous, we train a model for it and we clear the `ML_CONSTANT` flag.
> 4. For the next hour we predict based on the training
> 5. If the metric becomes constant again, we jump to point 1
> 
> This will avoid the first training and actually any metric can turn constant and not-constant during runtime. Every hour we will re-evaluate which metrics are constant (considered anomalous if they change value), or variable (train a model).

I read this as mainly an optimization to avoid the initial training on the constant values, correct?

The ml already sort of does this, parts 1 and 2. Fitting the model on constant values the first time will converge very fast anyway and so it's probably not really 'costing' that much in terms of CPU to just leave the ml alone to fit the cluster on the constant data. 

I'm just not sure custom logic like this gives enough of a benefit (I have a high threshold for the justification for any custom logic like this, the main point of the ML is to, generally, not have to worry about stuff like this, of course will be exceptions). 

It's also kind of an antipattern in terms of ML the more custom business logic (which is unavoidable, will always be some) we add, the more complex and hard to maintain it all will be longer term.

Longer term some notion or measure of 'model quality' might be another useful Lego block such that we can the weight or route model inferences in some way according to model quality score.

Also all this just refers to constant values but there are probably just as many if not more "near constant" charts that have like a handful of numbers (e.g ram usage tends to be one like this). These are just as "bad" to fit a cluster with k=2 on. So unless we are tackling the general problem of what to do then I'd be inclined to leave it alone for now. @vkalintiris optimization of not bothering to retrain when it makes no sense is enough for me for now as it's nice and simple and obvious and easy to reason about.

Will think more and I'll start making a list/epic of the next set of issues to tackle under the hood on the ml side that I think we will get more benefit from rather than trying to optimize too much just yet until we have the base ml stuff all a bit more fully built out. 

Mainly this is around how we extend the model to 24 hours or more in some way. Part of the solution here might also impact training and retraining schedules and approaches so anything we are suggesting here could complicate that too so would rather tackle that more important ml issue first and then once we happy with that we start looking at pre training optimizations and also post training optimizations around model quality etc and start building in some intelligence about the quality of the models fit for each dimension.

**Comment by ktsaou** [comment]
Well, the problem is like this:

1. A user installs netdata
2. After an hour, training starts
3. The user is monitoring CPU consumption to understand how efficient this is
4. The user sees twice the CPU utilization netdata will normally need, just because we train also constant metrics
5. The user makes the wrong conclusion: netdata ML needs double the CPU resources

What can you tell to this user? "hey, wait another hour, it will settle to half of that!"

We are risking a bad reputation if we initially use double the resources.

I understand the background, but I believe this heuristic is very important for the reputation of our ML...

**Comment by shyamvalsan** [comment]
Agree with @andrewm4894 that we should minimize custom logic in our ML solutions as far as possible - otherwise we it will get difficult to debug, maintain and update. 

But @ktsaou brings up an important problem - of initial extra load on CPU and how it will be perceived by the user. 

Does training models for all dimensions together at one-shot really make sense? Should we stagger this out to distribute the performance hit? I think we should have this conversation with actual numbers.

**Comment by andrewm4894** [comment]
> Should we stagger this out to distribute the performance hit?

We do this already. Thats what the small little bumps below are (i am retraining every 900 seconds on this example): 

![image](https://user-images.githubusercontent.com/2178292/156177098-7743a5a3-ac3c-4c57-a94a-6fadf099d4e2.png)

**Comment by shyamvalsan** [comment]
Staggering within the training cycle (default 1 hour) reduces the really high peaks but the overall spike still exists and will "jump out" to the user. 

For example, the constant dimensions, if we do require trained models for them why not wait one or more training cycles before training those dimensions for the first time? Won't that reduce the CPU spikes and we won't lose much in the bargain.
