### ISSUE TITLE
Explore the update functionality across different netdata versions

### ISSUE THREAD

**Issue by cpipilas** [netdata/netdata#12274]
### Problem

Updating Netdata to the latest version should work smoothly for the majority of use cases. They have been reports that this is not true under certain circumstances. This may result to numerous problems including cloud connectivity issues. 

### Description

We need to explore and validate that we can properly update netdata to the latest version. A number of previous netdata versions can be used as a starting point, the list of these versions will be added later to this issue. 

Considerations:
- Need to check that we can properly update netdata from version vX.Y.Z to the latest version, according to the documentation.
- Both stable and nightly release channels should be validated.
- All installation methods should be considered (native binaries, static builds, build from source).
- Installation transitions should be explored as well.
- Any corner cases where the update is not straight-forward should be clearly documented.

### Importance

blocker

### Value proposition

1. It will enable Netdata to identify any corner cases that updating to the latest version is challenging
2. Will re-assure that users with issues in updating Netdata will continue using Netdata Cloud without any problems.

**Comment by cpipilas** [comment]
cc @Ferroin @iigorkarpov @maneamarius @stelfrag @ktsaou @cakrit @amalkov

**Comment by Ferroin** [comment]
The following cases have been identified as specific problems here:

1. RPM packages for CentOS 7 had not been handling protobuf properly.
2. Older installs that predate the introduction of the `.install-type` file which have not had the updater run on the since that file was introduced are not currently recognized correctly by the kickstart script.
3. Older installs that predate the introduction of the `.install-type` file which were updated prior to #11199 being merged are currently incorrectly categorized as `custom` installs.
4. Installs from before 2021-08-16 that are building locally _and_ did not already have a C++ compiler can’t bundle protobuf unless the user has installed a C++ compiler.
5. Native packages currently do not include auto-updates.
6. Installs with a custom install prefix (including macOS and FreeBSD) currently are not detected correctly by the kickstart script, meaning it cannot be used to run updates.

As far as resolving these:

* Case 1 was fixed by https://github.com/netdata/netdata/pull/12167. Current nightly builds include the fix, and the next release will also include it.
* https://github.com/netdata/netdata/pull/12273 Will fix handling of the case 2 above, as well as fixing detection of the installation type on installs that fall under case 3 when using the kickstart script.
* https://github.com/netdata/netdata/pull/12282 Will fix (most) installs that fit case 3 above when they run the updater script.
* https://github.com/netdata/netdata/pull/12199 Will fix case 6 above.
* https://github.com/netdata/netdata/pull/12202 Is the first part of fixing case 5 above. The second part will be a separate PR that is expected to take roughly a week of work total, including testing.
* Case 4 above does not currently have an associated PR to fix it. The fix we decided on was to just download and run the dependency handling script in the updater before trying to update. The PR required for this is expected to take a total of about a week of work including testing.

**Comment by Ferroin** [comment]
OK, we’ve got approvals on (most) of the above open PRs.

I’m going to do a staged series of merges so that we can more easily identify the point of failure in the event that something goes horribly wrong.

First phase will be merging https://github.com/netdata/netdata/pull/12199 (because it’s the oldest PR and has been an issue for the longest) and https://github.com/netdata/netdata/pull/12202 (because it’s an enabler for further work on this).

In the very likely case that nothing breaks from either of those, I will plan to merge https://github.com/netdata/netdata/pull/12282 and https://github.com/netdata/netdata/pull/12273 tomorrow.

**Comment by Ferroin** [comment]
Also, draft PR is up for the C++ compiler issue: https://github.com/netdata/netdata/pull/12294

It still needs testing, but _should_ work without issue in a majority of cases.

**Comment by Ferroin** [comment]
Initial draft PR is also up for finishing he changes required to allow auto-updates for native packages: https://github.com/netdata/netdata/pull/12296

It also still needs testing, which will have to wait until tomorrow (because it requires the changes from https://github.com/netdata/netdata/pull/12202 to be in the nightlies).

**Comment by Ferroin** [comment]
Further update, https://github.com/netdata/netdata/pull/12282 and https://github.com/netdata/netdata/pull/12273 are now merged as well.

This just leaves #12294 and #12296, which I expect to merge some time next week.

**Comment by Ferroin** [comment]
Updates on this:

* Number of installs reporting as custom since the merge of #12282 has started to go down (albeit slowly).
* #12294 has been merged now, so we should start to see the number of nodes without protobuf support at all going down starting tomorrow.
* I’m holding off on merging #12296 until a bit later this week once we see that everything else is working.

**Comment by ktsaou** [comment]
@cpipilas I would like an update on the current figures of the cloud connected nodes.
