### ISSUE TITLE
[Bug]: eBPF explicitly disabled

### ISSUE THREAD

**Issue by Nirjonadda** [netdata/netdata#12478]
### Bug description

 --- eBPF Kernel Collector ---
 FAILED  eBPF explicitly disabled.

![ScreenShot00482](https://user-images.githubusercontent.com/6899856/159279440-2ca969f5-f743-4305-ba90-f57d29746026.png)

### Expected behavior

 --- eBPF Kernel Collector ---
 FAILED  eBPF explicitly disabled.

### Steps to reproduce

wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh

### Installation method

kickstart.sh

### System info

```shell
AlmaLinux 8
```

### Netdata build info

```shell
wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh
```

**Comment by thiagoftsm** [comment]
Hello @Nirjonadda ,

Thank you for your report, as soon this [PR](https://github.com/netdata/netdata/pull/12471) is merged, I will work on this issue.

Best regards!

**Comment by thiagoftsm** [comment]
@Nirjonadda ,

I ran two tests using `Vagrant Alma Linux` image:

- The first I cloned netdata repo, and after this I ran `dnf --enablerepo=powertools install autoconf-archive autogen libuv-devel`, `./packaging/installer/install-required-packages.sh --dont-wait` and finally I ran `./netdata-installer.sh --install /opt`.
     - I had to use `dnf`, because the `install-required-packages.sh`  is missing something for `Alma`
- For the second test, I ran the same commands than you `wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh`

I ran both tests on an Intel processor. This means that at least on this scenario, eBPF is running fine. I will do some questions for you, because we need more information to replicate and fix the problems:

- Do you install direct on hardware? Or were you using a container?
- Did you recompile the kernel to disable some eBPF features?
- Was your first installation on this host? Or did you have a previous `netdata` version?
- Did you also observed the message `WARNING  Could not install native binary packages, falling back to alternative installation method`?

Best regards,

Thiago

**Comment by Ferroin** [comment]
We appear to not correctly recognize Almalinux as an RHEL/CentOS clone in our installer, and this may be affecting things here. See https://github.com/netdata/netdata/pull/12487 for a fix for that.

**Comment by Quazz** [comment]
This still happens, but perhaps not for the reason you think.

>cat: packaging/ebpf-co-re.version: No such file or directory

This also occurs for libbpf (though not as disastrously) 

It's the real culprit, imo. This then creates an invalid downloadlink and eBPF cannot be properly installed and is thus disabled. 

For some reason the "working directory" remains the directory you called the script from and not the netdata installer folder

adding cd "${INSTALLER_DIR}" before calling each of the bundle function seems to resolve this.

**Comment by thiagoftsm** [comment]
Hello @Quazz ,

It looks like that your Alma did not get all necessary files to compile from this repo. The fix made by @Ferroin was tested with success on this environment:

```sh
[fractal@malta2183 ~]$ cat /etc/os-release 
NAME="AlmaLinux"
VERSION="8.5 (Arctic Sphynx)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.5 (Arctic Sphynx)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.5"
```

, please, can you give us your `/etc/os-release`?

Best regards!

**Comment by Quazz** [comment]
@thiagoftsm 

Basically identical

`
[root@localhost ~]# cat /etc/os-release
NAME="AlmaLinux"
VERSION="8.5 (Arctic Sphynx)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.5 (Arctic Sphynx)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.5"
`

**Comment by thiagoftsm** [comment]
Thank you @Quazz !

You're right when you say that this should not be related to Alma, because the file is used with all Linux distributions. I only cited Alma, because we identified the problem on it.

@Quazz when you were installing your netdata, did you have any message like these:

- Failed to get CO-RE. You will not be able to use eBPF plugin
- Unable to fetch sources for eBPF CO-RE. You will not be able to use eBPF plugin.
- Unable to fetch sources for libbpf.
- Unable to fetch sources for libbpf. You may not be able to use eBPF plugin.

Another doubt, can you try to run the following commands on your Alma?

```sh
$ git clone https://github.com/netdata/netdata.git
# cd  netdata
# ./netdata-installer.sh
```

If it is possible, do you still have problems to install using these command lines?

Best regards!

**Comment by thiagoftsm** [comment]
Thank you for your help @Quazz, now it is clear what is happening.

About the error you reported, it is possible that some 'submodules` were  not initialized, and if you run the following command:

```sh
$ git submodule update --init --recursive
```

@Ferroin it looks like we are missing `submodule` initialization when we use `netdata-installer.sh`, and we are still having a problem with `kickstart.sh`, because sometimes it is not able to get the files properly.
