### ISSUE TITLE
[Feat]: nightlies should be built with debug symbols enabled

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#12505]
### Problem

Today, when netdata crashes we don't have any visibility on why that happened.
We need to be in position to get stack traces back, that will help us identify the problem.

### Description

Under systemd, the default handling of core dumps is this:

```sh
# sysctl -a | grep pattern
kernel.core_pattern = |/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h
```

Systemd-coredump manual is here: https://www.freedesktop.org/software/systemd/man/systemd-coredump.html

It says:

> By default, systemd-coredump will log the core dump to the journal, including a backtrace if possible, and store the core dump (an image of the memory contents of the process) itself in an external file in /var/lib/systemd/coredump. These core dumps are deleted after a few days by default

We need these stack traces and it they should be there by default.

### Importance

must have

### Value proposition

1. Allow users to report stack traces of netdata agent crashes

### Proposed implementation

All nightlies should be compiled with:

```sh
CFLAGS="-O1 -ggdb"
```

All stable releases should be compiled with (like it is now):

```sh
CFLAGS="-O2"
```

**Comment by ktsaou** [comment]
@stelfrag @ilyam8

**Comment by Ferroin** [comment]
@ktsaou Can you provide some info about what _exact_ install methods you are not able to get symbolic backtraces out of?

There’s a _very_ big difference between the results of adding `-ggdb` to the compiler flags and what is required to get symbolic backtraces (potentially hundreds of MB of difference in binary size and significantly longer compile times to start with), and as far as I know, we are not doing anything that would prevent symbolic backtraces from working when building any of our pre-built packages or when building locally.

**Comment by Ferroin** [comment]
@ktsaou You did not answer my actual question. I’m not asking about debugging symbols, I’m asking about proper backtraces, and which install method you used that you then saw a crash and were not able to get a symbolic backtrace.

Loading a locally built copy of Netdata into GDB, built using our current default CFLAGS (so with `-O2` but without `-ggdb`), I can produce entirely correct symbolic backtraces without issue. The backtrace has nothing to do with any `-g` options at all, it’s produced simply by unwinding the stack and resolving the return addresses to symbols. The only situation where this breaks is when you have no symbols in the binary because you’ve stripped it.

The only issue I see at the moment with getting backtraces in our production builds is for our static builds, which for some reason we strip.

**Comment by stelfrag** [comment]
can we revisit this?. The idea being if a user uses a nightly build and reports a crash, we request the core dump and we see exactly the source code line it failed.

**Comment by Ferroin** [comment]
Do we have any indication of whether `-Og` is actually needed here? It almost certainly reduces both performance _and_ memory efficiency, and if we just need line number resolution it’s almost certainly overkill.

**Comment by ilyam8** [comment]
I think this has been addressed by Sentry.
