### ISSUE TITLE
[Feat]: Enable testing for Linux/Arm64 platform in CI

### ISSUE THREAD

**Issue by odidev** [netdata/netdata#12895]
### Problem

_legacy & cmocka_ tests are running through GitHub Actions for Linux/AMD64 via [tests.yml](https://github.com/netdata/netdata/blob/master/.github/workflows/tests.yml). It would be great if these tests were also available for Linux/ARM64 via GitHub Actions CI.

### Description

As we know Netdata now has support for aarch64 platform as well, and binary is getting released for aarch64 platform as well. However, there are _legacy & cmocka_ tests are running through GitHub Actions for Linux/AMD64 via [tests.yml](https://github.com/netdata/netdata/blob/master/.github/workflows/tests.yml). It would be really helpful if we can add these tests for Linux/ARM64 platform as well. may i know if you are planning to add these tests for arm64 platform as well.

### Importance

nice to have

### Value proposition

1. would help in testing basic features for multiple platforms

**Comment by Ferroin** [comment]
This is theoretically doable, but not easy. GHA only provides 64-bit x86 environments. Unless that changes (not likely IMO, for multiple reasons), we have only two options for this type of thing:

- Set up a self-hosted GHA runner with the correct CPU architecture. This is not realistically happening unless GH makes significant changes to how their runners work, because right now using a self-hosted runner on a public repo has some seriously nasty security implications.
- Set up QEMU userspace emulation like we’re already doing for our package builds. This would work, but would be painfully slow (effective performance is less than 20% of native performance), and would probably be a bit tricky to set up in the first place.

**Comment by odidev** [comment]
@Ferroin, "[Works on Arm](https://github.com/WorksOnArm)" is an initiative that provides free access to Arm based clusters (on Equinix). This is for the purpose of giving open source projects access to Arm HW to support build-test loops. If Interested we can ask for access of the same.

**Comment by odidev** [comment]
Gentle Reminder...
Please let us know your opinion on above suggestion.
