### ISSUE TITLE
Use Websockets or SSE instead of polling

### ISSUE THREAD

**Issue by pjlegato** [netdata/netdata#130]
Performance would be better, and there would be less impact on the server from monitoring itself, if the data were transmitted to the web client via websockets or SSE rather than by polling the server once a second.

**Comment by ktsaou** [comment]
You are right!

However, even with websockets, the main chart library used ([dygraphs.com](http://dygraphs.com)) is not capable of just shifting the raster and adding a single point. The only chart libraries I know that are capable of doing this are:

- [flotcharts](http://www.flotcharts.org/), and
- [cubism.js](https://square.github.io/cubism/).

However, I find them a lot less flexible compared to dygraphs.
This means the charts on the browser would have to be re-drawn.
So, no performance benefit for the browser.

Then, let's consider the communication between client and server: A new protocol (over websockets) would have to be created to handle the different states of the charts:

- appending points in auto-refresh
- zooming in/out
- panning
- window resizing (which might change the data aggregation at the server so a full refresh might be triggered)
- scrolling the page (i.e. switching charts - again full refresh might be needed)
- data transformation at browser javascript to build the dataset at the proper structure required for each chart library (now this is done in C and it is simple because there is just one case: send all the visible data to the browser).

This is a huge project by itself !

So, yes I agree. The way it is now it is not optimal.
Can we do it the optimal way? Of course!
Does it have any value to do it? I am not sure.
Let's see why:

If we do it, we will gain some CPU cycles at the netdata server and some bandwidth.
When are we going to benefit from them?
Just for the moments we let the charts auto-refresh, without scrolling the page and without panning or zooming the charts.

Time yourself. How much time do you spend in that condition? I timed me and found that I don't spend that much time just sitting in front of screen watching it without interacting with the charts.

Of course, such a solution would be perfect for a TV dashboard.

**Comment by pjlegato** [comment]
All excellent points. It does seem like a fairly large amount of work for what would be a relatively small gain in the most common cases.

**Comment by pjlegato** [comment]
D3.js or one of its derivatives would be ideal, but would require substantial reworking.

**Comment by ibnesayeed** [comment]
> However, even with websockets, the main chart library used ([dygraphs.com](http://dygraphs.com/)) is not capable of just shifting the raster and adding a single point. The only chart libraries I know that are capable of doing this are:

@ktsaou, I was wandering if you considered [vis.js](http://visjs.org/) and does it support shifting and painting the raster incrementally? I find this library quite feature rich.

**Comment by ktsaou** [comment]
> I was wandering if you considered vis.js and does it support shifting and painting the raster incrementally? I find this library quite feature rich.

No I haven't. I can give it a try and integrate it (all integrated so far: http://netdata.firehol.org/dashboard.html).

**Comment by 0xpr03** [comment]
> I timed me and found that I don't spend that much time just sitting in front of the screen watching it without interacting with the charts.

I've to disagree, I'm just letting it run through to see changes when I'm doing some on the system, creating 40 MB logfiles from nginx, especially when I'm observing an DDOS and how the system reacts.

**Comment by ktsaou** [comment]
Of course, that is a proper use of netdata.
Regarding the logs, I can add a configuration option to netdata to just log a line per connection (not every request), logging also the X-Forwarded-For set by nginx for this connection. This way you could disable the nginx log entirely. If you want it, open a github issue for it.

**Comment by 0xpr03** [comment]
@ktsaou My use case for the logs is to catch failed logins.

**Comment by ibnesayeed** [comment]
> No I haven't. I can give it a try and integrate it (all integrated so far: http://netdata.firehol.org/dashboard.html).

@ktsaou Interesting page. If I may ask, is there a way to know if they are painting the changes incrementally or overwriting the whole canvas on each change, without looking into their code to find out the rendering logic?

**Comment by ktsaou** [comment]
ok. You have password protection on nginx.
Your problem can also be solved when we add password protection on netdata, #120

**Comment by ktsaou** [comment]
> If I may ask, is there a way to know if they are painting the changes incrementally or overwriting the whole canvas on each change, without looking into their code to find out the rendering logic

which one?

**Comment by ibnesayeed** [comment]
> which one?

[vis.js](http://visjs.org/)

**Comment by ktsaou** [comment]
> vis.js

In a few demos, I think they are scrolling the canvas. However, netdata requirements are tough. The charting library has to be really fast. If they manipulate data in javascript, they are not going to be fast. I saw a demo on vis.js with 50000 points. It took a few seconds on my PC. If that was processing time, it will not do for netdata. If it was downloading time, it might be ok. I don't know.

Then, there are issues with synchronizing mouse selection on multiple charts, legends, zooming, panning, etc. If you check the details on the dashboard I sent you, you will see that netdata calculates the time in ms each chart takes to be refreshed. Even in dygraphs, I had to disable almost all animations and effects it supports to make it usable. With 2-3 charts on a page it was playing nice. With 10 it was unusable. So, I disabled everything and I re-wrote the legend entirely, etc to speed it up!

**Comment by ibnesayeed** [comment]
> If they manipulate data in javascript, they are not going to be fast. I saw a demo on vis.js with 50000 points. It took a few seconds on my PC. If that was processing time, it will not do for netdata. If it was downloading time, it might be ok. I don't know.

I tried to profile their [50,000 example](http://visjs.org/examples/graph2d/08_performance.html) and it lookes like they are generating some dummy data using their `generateData` function and then calling `loadDataIntoVis` function at once with all that dataset. In my profiling it took 953.7ms for `loadDataIntoVis` (which internally called their `DataSet.add` method) to execute, load data, and render it. This is the measurement on rendering 50,000 data points at once. However, I did not measure what's the performance of the incremental changes. I can perhaps write a small function and run in the developer console to append a bunch of additional dataset one point at a time and collect the stats.

**Comment by myroslav** [comment]
Server Sent Events are usable, when netdata are displaying live data, i.e. right side of graphs is "now()" and zoom is 1:1 (when each and every datapoint is to be sent to web client).

Javascript code would need to collect set of graphs to be displayed/updated from the moment on (i.e. after page scroll), and request some "feed" endpoint with set of datasets to fetch and its superset to stream. Each of the sets would go into separate SSE **event** and **data** would provide missing data sequence.

After providing all of the data for all of the graphs into single HTTP response, that response would stay open and after a second when new set of data for all graphs to be "streamed" would be collected, these data would be set into series of **events**, one event per graph. Network-wise, the that http chunk would probably be gzipped into single TCP packet, meaning minimal overhead on TCP/HTTP-request processing. Additionally each such "burst" of data can have an **id** that would be used on connection loss, thus SSE reconnection would be quite efficient (where netdata API server would provide only missing datapoints).

All in all SSE appear as the proper solution nework-wise. However graph repaint/update issue is not quite understood by me, and most probably is valid.

**Comment by ktsaou** [comment]
I switched this to `enhancement`, to have a look at it at some point...

**Comment by ZetaHunter** [comment]
I would also like to add comment on the issue of using web-sockets in combination with services like CloudFlare that simply don't allow web-sockets, thus would require some form of fallback.

**Comment by ktsaou** [comment]
I think the first step is to allow incremental updates of the data of the charts. This will save a lot of bandwidth in cases the dashboard is left to autorefresh the charts.

Once we have this, web sockets could also be implemented.

**Comment by pjlegato** [comment]
@ZetaHunter Oddly enough, CloudFlare just launched WebSockets for all users today: https://blog.cloudflare.com/everybody-gets-websockets/

**Comment by ZetaHunter** [comment]
You ought to be kidding, well, thanks for letting me know. :+1:

**Comment by ktsaou** [comment]
This is on our roadmap, but no high priority.

Web sockets could help us lower the traffic required between netdata and the web server and it may allow the web dashboard to render only part of the chart on each update. Though, complexity will increase dramatically.

So it is an optimization. Not a feature.

**Comment by cakrit** [comment]
Keeping the "feature request" label even though it's optimization, to prevent the bot from marking it as stale again.

**Comment by Daniel15** [comment]
Server-Sent Events would likely be easier to implement than WebSockets, as it's still using HTTP rather than a separate protocol. SSE is only unidirectional though (from server to client) and you'd still need to use regular HTTP requests to send data from the client to the server. WebSockets would be good if you need bidirectional messaging.

**Comment by cakrit** [comment]
The main question is what would give us the best chance of avoiding issues with firewalls and proxies. I haven't done much research on the subject and would appreciate any info you can provide on the matter.

**Comment by 0xpr03** [comment]
I think long polling is fine if you wan to avoid company firewalls. Many websocket implementations are defaulting to that if it doesn't work.
Websocket itself will pose another thread and be a problem for firewalls as you allow the server to start communication by himself.

**Comment by Daniel15** [comment]
@cakrit Server Sent Events is more likely than WebSockets to work with proxies/firewalls since it's just plain HTTP, whereas WebSockets are a totally separate protocol (RFC6455). However, if the connection is encrypted, WebSockets should also get through most firewalls, since the firewall can't tell it's a different protocol unless it MitM's the connection. 

@0xpr03 Long polling is good for cases where you have occasional messages from server to client (eg. chat clients, notifications on sites like Facebook, etc), but it doesn't work well if you have a continuous stream of data. Long polling also has quite a few issues (eg. https://blog.baasil.io/why-you-shouldnt-use-long-polling-fallbacks-for-websockets-c1fff32a064a) although in some cases it's a decent fallback option if all else fails. For netdata, I'd suggest just falling back to its regular polling mechanism (what it's doing today) if WebSockets and server sent events are both unavailable.

**Comment by thiagoftsm** [comment]
Thank you all by the explanation and source of information, right now we are working in the PR relative to SSL and your requests are already in my task list to bring to Netdata.

**Comment by peterwillcn** [comment]
The construction of the simple quick websocket https://github.com/Azolo/websockex

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
