### ISSUE TITLE
[Bug]: CPU Frequency

### ISSUE THREAD

**Issue by SteveBox0** [netdata/netdata#13116]
### Bug description

The CPU Frequency does not report the current clock rate or effective clock rate. This means it display the base frequency that does not change for AMD CPUs. Ideally we should be graphing effective clock rate like HWinfo on Windows, as this is the most useful metric for displaying the real CPU Frequency.

### Expected behavior

CPU Frequency should not always stay at the same value. 

### Steps to reproduce

1. Install latest netdata on Ubuntu 22.04 with AMD 5000 series CPU
2. Run Stress Test
3. look at net data CPU Frequency graph for any changes.
...

### Installation method

kickstart.sh

### System info

```shell
:~# uname -a; grep -HvE "^#|URL" /etc/*release
Linux ubuntu 5.18.3-xanmod1-x64v2 #0~git20220609.f2e6e36 SMP Thu Jun 9 21:37:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=22.04
/etc/lsb-release:DISTRIB_CODENAME=jammy
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
/etc/os-release:PRETTY_NAME="Ubuntu 22.04 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="22.04"
/etc/os-release:VERSION="22.04 LTS (Jammy Jellyfish)"
/etc/os-release:VERSION_CODENAME=jammy
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=jammy
```

### Netdata build info

```shell
:~# netdata -W buildinfo
Version: netdata v1.35.0-8-nightly
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-option-checking' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--disable-dependency-tracking' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

**Comment by SteveBox0** [comment]
Workaround with https://github.com/netdata/netdata/pull/2714 and turbostat from Linux Kernel 5.19.

**Comment by vlvkobal** [comment]
At the moment we read `scaling_cur_freq` which is the current frequency of the CPU as seen by the kernel. The is also `cpuinfo_cur_freq` that provides CPU frequency obtained from the hardware. More information can be found in the [kernel documentation](https://www.kernel.org/doc/html/latest/admin-guide/pm/cpufreq.html#policy-interface-in-sysfs).

I think we should add a separate chart for the value, obtained from the hardware, but it should be disabled by default because it can affect performance (usually, CPU performance scaling drivers read MSR registers to get the information). There is a good [discussion](https://github.com/prometheus/procfs/issues/122) on the matter.

**Comment by vlvkobal** [comment]
I'm closing this because Netdata needs root permissions to read `cpuinfo_cur_freq` so the chart has very limited application. @SteveBox0 You can use `scaling_cur_freq filename to monitor = /sys/devices/system/cpu/%s/cpufreq/cpuinfo_cur_freq` to monitor the frequency reported by the hardware if you are ok with granting Netdata root permissions.

**Comment by ilyam8** [comment]
> for me the scaling_cur_freq files are world readable

@thulle hey. @vlvkobal said the `cpuinfo_cur_freq` file is not world readable.

[I see that Netdata prefers](https://github.com/netdata/netdata/blob/a749ab00a63b229d99f6bc82a965206e5481db3e/collectors/proc.plugin/proc_stat.c#L664-L680) `cpufreq/stats/time_in_state` over `cpufreq/scaling_cur_freq` if the latter is available


You can change it (in a hacky way) by uncommenting and changing `time_in_state filename to monitor` to a file that doesn't exists (e.g. `/sys/devices/system/cpu/%s/cpufreq/stats/time_in_state1`) in `netdata.conf`.

---

On my server (2 CPUs, 112 cores) reading `scaling_cur_freq` is slow

```cmd
$ time cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq > /dev/null

real	0m2.460s
user	0m0.014s
sys	0m0.001s
```

**Comment by thulle** [comment]
@ilyam8 but cpuinfo_cur_freq doesn't contain the wanted data anyway? Kernel docs says:

        In the majority of cases, this is the frequency of the last P-state
        requested by the scaling driver from the hardware using the scaling
        interface provided by it, which may or may not reflect the frequency
        the CPU is actually running at

checking time_in_state it becomes clear why it doesn't work, it also just reflects the, in my case, 3 P-states:

$ cat time_in_state 
3400000 2102121
2800000 2297051
2200000 25151149

On my 16 core 32 thread AMD 5950X I can read scaling_cur_freq pretty quickly:
$ time cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq > /dev/null 

real	0m0,002s
user	0m0,000s
sys	0m0,002s

Reading /proc/cpuinfo gives the same times as above, and also the data matches scaling_cur_freq as shown in the earlier post.

On a 2 cpu 16 core Xeon 2690 it's way slower:

$ time cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq > /dev/null 

real	0m0,333s
user	0m0,005s
sys	0m0,002s

But reading cpuinfo is still pretty fast:

$ time cat /proc/cpuinfo > /dev/null 

real	0m0,020s
user	0m0,003s
sys	0m0,000s

But I'm slightly unsure about the returned data:

$ paste <(grep MHz /proc/cpuinfo) <(cat /sys/devices/system/cpu/cpu{0..16}/cpufreq/scaling_cur_freq 2>/dev/null)|head -n 3
cpu MHz		: 1537.149	1537149
cpu MHz		: 1600.000	1832861
cpu MHz		: 1400.000	1635521


Since the first one is actually spot on I suspect the frequencies are just changing while the separate scaling_cur_freq are slowly read.

Same story on a 2 cpu 12 core Xeon X5650, but it's not the first cpu that's spot on in frequency between the files:

$ time cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq > /dev/null

real	0m0,261s
user	0m0,003s
sys	0m0,001s

$ time cat /proc/cpuinfo > /dev/null 

real	0m0,021s
user	0m0,002s
sys	0m0,001s

$ paste <(grep MHz /proc/cpuinfo) <(cat /sys/devices/system/cpu/cpu{0..16}/cpufreq/scaling_cur_freq 2>/dev/null)|head -n 5
cpu MHz		: 1867.000	1631992
cpu MHz		: 1685.401	1685401
cpu MHz		: 1600.000	1612337
cpu MHz		: 1867.000	1653753
cpu MHz		: 1867.000	1607709


So at least on recent AMD consumer CPUs it seems like we should just read scaling_cur_freq and avoid ugly hacks? 
And in the other cases it might be faster to parse cpuinfo?

**Comment by ilyam8** [comment]
> And in the other cases it might be faster to parse cpuinfo?

Interesting idea. It is pretty fast, indeed

```cmd
$ time cat /proc/cpuinfo | grep "cpu MHz" > /dev/null

real	0m0.021s
user	0m0.005s
sys	0m0.001s
```

**Comment by nethershaw** [comment]
> You can change it (in a hacky way) by uncommenting and changing `time_in_state filename to monitor` to a file that doesn't exists (e.g. `/sys/devices/system/cpu/%s/cpufreq/stats/time_in_state1`) in `netdata.conf`.

Still what I have to do in 2024 to correctly read the boost frequencies from an AMD Ryzen 7 2700X Eight-Core Processor. A bit silly because the turbostat plugin is still in someone else's tree.
