### ISSUE TITLE
[Feat]: Add ability to mark node as ephemeral, propagate that flag trough streaming (to parents)

### ISSUE THREAD

**Issue by underhood** [netdata/netdata#13160]
### Description

- Add ability to mark node as ephemeral
- propagate that flag trough streaming (to parents)
- send that info to cloud as part of NodeInfo message

### Importance

really want

### Value proposition

1.
2.
3.
...

**Comment by ralphm** [comment]
What about the following?

- Introduce a configuration option `ephemeral` in the `global` section.
  - It will have values `yes` and `no` (default).
  - Users will immediately have the ability to mark nodes ephemeral, according to their definition of ephemeral.
  - Possibly we can have `auto` in the future, and make that the default. It could look at things like the node belonging to a managed k8s service (Google GKE, AWS EKS, Azure AKS).
- The ultimate (static or calculated in case of `auto`) value `yes` or `no` will be exposed through an automated host label `_is_emphemeral`, which then gets propagated along with the other host labels.

**Comment by andrewm4894** [comment]
would using a host label be too weak a signal? e.g a special host label like `netdata_node_type = ephemeral` and then Netdata can take action accordingly based on the value of `netdata_node_type` host label. 

just wondering if we can use host labels since they might be easier then to build FE features off and maybe more easily extendable etc.

perhaps default value would be that all hosts have a label of `netdata_node_type = autodetect` or something like you say.

**Comment by ralphm** [comment]
Host labels with an underscore are reserved, so we can use them ourselves, and it is already _special_. The others are user-defined and we shouldn't mix them.

**Comment by ralphm** [comment]
By the way, by doing it this way, you can also use ephemerality in alerts, exports, etc.

**Comment by ktsaou** [comment]
I think ephemerality is related to host health management. So, probably it should be like (in `netdata.conf`):

```
[health]
   node type = ephemeral | permanent
```

With `permanent` being the default.

This could also set the host label `_node_type` which will be propagated to parent nodes.

I prefer `_node_type` over `_is_ephemeral` mainly because this will allow us to have more types in the future, like:

* permanent (pet)
* ephemeral (instant resource)
* unreliable (unreliable connectivity from IoT or other remote agents, over GPRS or whatever non-reliable network)
* roaming (permanent, but roaming node with long duration between connections - like laptops)

The idea is that an admin could eventually set different policies to control how the cloud should handle different node types.

**Comment by Ferroin** [comment]
I concur with @ktsaou here, both on the point of this being part of the health management info, and on needing it to be more than simply a boolean flag, though am not completely sold on the user-defined node types.

At minimum, I see a need for three types here:

- `permanent`, which has all the current ‘standard’ behaviors and should be the default barring special cases.
- `intermittent`, which works like permanent, but defaults to not firing unreachability notifications unless a (ideally user configurable) threshold for time out of contact is met. Intended for laptops, IoT sensor nodes, and similar things that are expected to only connect intermittently. We can and probably should set this by default for nodes that are identified as having a battery as part of their power supply.
- `ephemeral`, which does not fire unreachability alerts at all and gets garbage collected when offline much more quickly than the other types. We can and probably should set this by default for instances managed as part of a k8s deployment.

**Comment by ralphm** [comment]
Thinking about this a bit more, I'm not convinced on having a single configuration for a node type, as it only indirectly conveys information on how such nodes should be handled:

- Whether a node is expected to be continuously connected (a machine in a datacenter) or not (a laptop, a fixed machine with unreliable connectivity like a submarine, or even a machine that is expected to be turned off regularly).
- Whether an offline node is off interest in listings by default.
- Whether a node that has been offline for while should be cleaned up.

So maybe we need to make that a bit more explicit, so that the interpretation of those properties can be more easily be processed, without having to synchronize the semantics of each node type between Agents (including older versions) and Cloud.

Additionally, there maybe other things influencing what happens. E.g. if a node is on a metered connection, it may want to configured to not stream to a parent.

I like the idea about doing things automatically (e.g. by looking at batteries, but please exclude peripherals that have batteries), but I didn't want to this to explode into a big project. Instead I was looking for the very narrow scope of being able to hide an offline node by default in lists of nodes in Cloud.

**Comment by underhood** [comment]
Well we could add 2 config values:
1. node is permanent/ephemeral (expected to never reconnect and thus cloud can remove it auto-magically)
2. node connection is expected to be intermittent or not (e.g. laptops, in which case we could silence online/offline alarms etc.)

As for allowing any value for those config values as Costa suggested... I am not sure about that. We should allow user defined labels for that anyway as a generic thing. Those values we are introducing now are supposed to have special meaning for cloud.

**Comment by Ferroin** [comment]
@ralphm Indeed, that’s almost certainly a better approach in terms of scalability. I still think any configuration overrides should probably be in the health section on the client side (or possibly a new section just for this?) however.

I would also argue that marking a node as ephemeral should probably shorten the max age before it gets cleaned up automatically in addition to hiding it if offline. My reasoning on this is more a matter of us keeping our own infrastructure tidy than one of some direct user benefit (ephemeral nodes that are sticking around in the Cloud potentially skew our metrics, as well as impacting our resource usage requirements).

As far as other flags, three to implement in the future come to mind:

- One to mark a node as being expected to only be online sometimes. Intended for laptops, roaming IoT devices, etc. Can probably be enabled by default if we see that the system is designed to run on battery power. This should set a longer timeout that the node must be offline before we warn about it being unreachable (thinking to have this initially default to 24h, but it should probably be configurable per room eventually).
- One to mark a node as having an unstable connection (lots of dropouts/latency/packet loss). We can mark this automatically on the Cloud side itself. Ideally should make the Cloud a bit more tolerant of connection latency for that node, but warn the user about the reliability issues (we might even consider adding something equivalent to the unreachability notifications for this).
- One to mark a node as being on a metered connection. We can at least partially auto-detect this. I’m envisioning this one translating to less aggressive keepalive behavior for the ACLK connection, and possibly more aggressive compression on the link.

**Comment by ralphm** [comment]
@underhood agreed. I originally suggested having this as a boolean to limit the possible options, with an additional value `auto` to explicitly let Netdata figure it out. When such heuristics are indeed implemented, that would be the default. Otherwise I'd take the defaults for ephemerality and expected connectedness to reflect always on.

@Ferroin sure we could clean up nodes known to be ephemeral earlier, but it also depends on what the topology looks like. I.e. if there's a parent node with long retention, you'd still want to be able to get to those metrics.

**Comment by Ferroin** [comment]
> sure we could clean up nodes known to be ephemeral earlier, but it also depends on what the topology looks like. I.e. if there's a parent node with long retention, you'd still want to be able to get to those metrics.

I would argue that in that case, we should automatically clamp the lifetime of the node on the Cloud side to the lifetime of the last metrics collected from it that the Cloud can still access. We can in theory infer that from the streaming topology and the parent configs, and once you can't get metrics for the node there’s not really much point in the Cloud continuing to remember that it existed at some point.

That said, that type of handling is definitely out of scope for the basic requirements for this ticket.

**Comment by ralphm** [comment]
Indeed, I would like to keep this simple and first just have a way to mark nodes as being ephemeral, as suggested in https://github.com/netdata/netdata/issues/13160#issuecomment-1237952768. Then we can work separately on other _markings_, as well as define how we'd handle ephemeral nodes on Cloud.

**Comment by underhood** [comment]
As I was thinking about this now. Should this be .dotfile (like in case of .do_not_track) so that it could easily be set by installer/claim script etc.?

**Comment by Ferroin** [comment]
> As I was thinking about this now. Should this be .dotfile (like in case of .do_not_track) so that it could easily be set by installer/claim script etc.?

Probably as a way to set the default value, though we almost certainly should have a ‘regular’ config option for it as well.
