### ISSUE TITLE
[Bug]: Kickstart Script cannot be downloaded from an IPv4 only network

### ISSUE THREAD

**Issue by StiviiK** [netdata/netdata#13204]
### Bug description

The `kickstart.sh` script can only be fetched via an IPv6 connection. If you are trying to fetch the script from an IPv4 only network the connection times out.

### Expected behavior

I want to be able to download the script via both ip stacks.

### Steps to reproduce

```
> curl -v --ipv4 https://my-netdata.io/kickstart.sh
*   Trying 188.114.97.3:443...
* connect to 188.114.97.3 port 443 failed: Operation timed out
*   Trying 188.114.96.3:443...
* connect to 188.114.96.3 port 443 failed: Operation timed out
* Failed to connect to my-netdata.io port 443 after 150320 ms: Operation timed out
* Closing connection 0
curl: (28) Failed to connect to my-netdata.io port 443 after 150320 ms: Operation timed out
```

### Installation method

other

### System info

```shell
Does not apply.
```

### Netdata build info

```shell
Does not apply.
```

**Comment by Ferroin** [comment]
The site in question is proxied through CloudFlare, which had major issues at around the time this issue was opened. Given this, together with the fact that I cannot reporduce it (checking from a dozen different networks worldwide), I’m going to assume that this was a result of the aforementioned issues with CloudFlare and close this.

If you are still seeing this issue, please comment here and we can reopen it and investigate further.

**Comment by StiviiK** [comment]
Unfortunately I am still unable to open an IPv4 connection to that server. Other Websites proxied through Cloudflare seem to be working fine for me. 
But also I unterstand you can't really help me there, as it is a problem of my Provider or Cloudflare itself.
