### ISSUE TITLE
[Bug]: go.d.plugin/mysql collects MyISAM stats, despite the engine being disabled

### ISSUE THREAD

**Issue by snwflake** [netdata/netdata#13518]
### Bug description

The external `go.d.plugin` `mysql` collects and displays chart information for the `MyISAM` storage engine, despite being disabled via conf:
```ini
[mysqld]
disabled_storage_engines = "MyISAM,FEDERATED"
[...]
```

### Expected behavior

The plugin should not collect and display metrics for storage engines that are disabled.

### Steps to reproduce

1. add agent to a db node, running mysql ^8.*
2. disable `MyISAM` storage engine
3. configure `go.d/mysql.conf`
4. enable `mysql` in `go.d.conf`
5. restart the agent

### Installation method

kickstart-static64.sh

### System info

```shell
Linux proxmox.r2.test.netdata 3.10.0-1160.62.1.el7.x86_64 #1 SMP Tue Apr 5 16:57:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 7.9.2009 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.9.2009 (Core)
/etc/system-release:CentOS Linux release 7.9.2009 (Core)
```

### Netdata build info

```shell
Version: netdata v1.36.0
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--without-bundled-protobuf' '--disable-dependency-tracking' 'CFLAGS=-static -O2 -I/openssl-static/include -pipe' 'LDFLAGS=-static -L/openssl-static/lib' 'PKG_CONFIG_PATH=/openssl-static/lib/pkgconfig'
Install type: kickstart-static
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

### Additional info

/

**Comment by snwflake** [comment]
Addendum:
The same behavior exists for the `binlog`. On my testing node, the binlog is deliberately disabled, but netdata charts it anyway.

**Comment by ilyam8** [comment]
Hi, @snwflake.

> MyISAM stats

I see there are 3 charts:

- [**MyISAM Key Cache Blocks**](https://github.com/netdata/go.d.plugin/blob/0287d62a6777146a55c90d08b52a04a003d1547a/modules/mysql/charts.go#L374)
- [**MyISAM Key Cache Requests**](https://github.com/netdata/go.d.plugin/blob/0287d62a6777146a55c90d08b52a04a003d1547a/modules/mysql/charts.go#L386)
- [**MyISAM Key Cache Disk Operations**](https://github.com/netdata/go.d.plugin/blob/0287d62a6777146a55c90d08b52a04a003d1547a/modules/mysql/charts.go#L398)

Those charts metrics come from ["SHOW GLOBAL STATUS;"](https://mariadb.com/kb/en/server-status-variables) query.

Relevant collected status variables:

- **MyISAM Key Cache Blocks**
  -  [**Key_blocks_unused**](https://mariadb.com/kb/en/server-status-variables/#key_blocks_unused): number of unused key cache blocks.
  - [**Key_blocks_used**](https://mariadb.com/kb/en/server-status-variables/#key_blocks_used): max number of key cache blocks which have been used simultaneously.
  - [**Key_blocks_not_flushed**](https://mariadb.com/kb/en/server-status-variables/#key_blocks_not_flushed): number of key cache blocks which have been modified but not flushed to disk.
- **MyISAM Key Cache Requests**
  - [**Key_read_requests**](https://mariadb.com/kb/en/server-status-variables/#key_read_requests): number of key cache block read requests.
  - [**Key_write_requests**](https://mariadb.com/kb/en/server-status-variables/#key_write_requests): number of requests to write a block to the key cache.
- **MyISAM Key Cache Disk Operations**
  - [**Key_reads**](https://mariadb.com/kb/en/server-status-variables/#key_reads): number of physical index block reads.
  - [**Key_writes**](https://mariadb.com/kb/en/server-status-variables/#key_writes): number of key cache block write requests.



1. Not a specialist, I am not 100% sure those metrics always refer to MyISAM. Need to check.
2. Netdata collects them because MySQL exposes them ("SHOW GLOBAL STATUS" response contains the metrics).

**The 2nd point needs clarification**:

- If MySQL returns the metrics - it is not a bug.
- if MySQL doesn't return the metrics, but Netdata creates charts - it is a bug.

Can you verify that @snwflake? The same question about `binlog` metrics.

**Comment by snwflake** [comment]
Hi @ilyam8,

`SHOW GLOBAL STATUS;` does indeed expose them, despite being disabled. So this should be treated as a feature request from now on.

I don't think it makes much sense to bloat the charts with useless metrics.
According to mysql docs, the aforementioned `key_*` metrics are restricted to MyISAM:

- MyISAM Cache Key Blocks
  - [Key_blocks_unused](https://dev.mysql.com/doc/refman/8.0/en/server-status-variables.html#statvar_Key_blocks_unused)
  - [Key_blocks_used](https://dev.mysql.com/doc/refman/8.0/en/server-status-variables.html#statvar_Key_blocks_used)
  - [Key_blocks_not_flushed](https://dev.mysql.com/doc/refman/8.0/en/server-status-variables.html#statvar_Key_blocks_not_flushed)
- MyISAM Key Cache Requests
  - [Key_read_requests](https://dev.mysql.com/doc/refman/8.0/en/server-status-variables.html#statvar_Key_read_requests)
  - [Key_write_requests](https://dev.mysql.com/doc/refman/8.0/en/server-status-variables.html#statvar_Key_write_requests)
- MyISAM Key Cache Disk Operations
  - [Key_reads](https://dev.mysql.com/doc/refman/8.0/en/server-status-variables.html#statvar_Key_reads)
  - [Key_writes](https://dev.mysql.com/doc/refman/8.0/en/server-status-variables.html#statvar_Key_writes)

Would it be feasible to extend the [global_vars collector](https://github.com/netdata/go.d.plugin/blob/master/modules/mysql/collect_global_vars.go) in a way to account for `disabled_storage_engines` and `log_bin` and only add charts if they're present in a similar fashion to the way it does for ie. `innodb_deadlocks`?

**Comment by snwflake** [comment]
I drafted the rough idea, my knowledge of golang is rudimentary at best, so it's probably not optimal.
