### ISSUE TITLE
[Bug]: Critical alert mysql_galera_cluster_status

### ISSUE THREAD

**Issue by ced1check** [netdata/netdata#13549]
### Bug description

Since upgrade 1.36, I receive a critical alert incorrectly on mysql_galera_cluster_status.

galera node cluster component status (-1: unknown, 0: primary/quorum present, 1: non-primary/quorum lost, 2: disconnected). Any other value than primary indicates that the node is part of a nonoperational component.

All nodes are actually connected and in Primary status:

wsrep_cluster_status    Primary

Is there a way to fix that without waiting for next update?

### Expected behavior

No alert should be raised.

### Steps to reproduce

1. Run a galera cluster with all nodes in Primary state
2. Upgrade netdata agent to 1.36

### Screenshots

![critical_alert](https://user-images.githubusercontent.com/104206200/184088490-46791168-2eac-4a46-9c70-0563ceb9e479.png)

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
@MrZammler is this an issue on our stock alert configs?

**Comment by ced1check** [comment]
Yes, that alert is one of those default/stock alerts as I've not added any so far.

**Comment by MrZammler** [comment]
Not sure why this poped up in 1.36. The alert itself hasn't been changed for a while.

I'm not sure then if something changed in the collector to trigger this. @ced1check mind if you open a PR for the fix in `mysql.conf` so other team members can have a look as well please ?

**Comment by ced1check** [comment]
Created the PR: https://github.com/netdata/netdata/pull/13550

**Comment by ilyam8** [comment]
@ced1check can you show the chart? @MrZammler what does `0-` (the value, what is that `-`?) mean?

**Comment by ced1check** [comment]
Chart is a flat and constant 0.
Values are defined like this in alert definition:
-1: unknown, 0: primary/quorum present, 1: non-primary/quorum lost, 2: disconnected

The values I've seen so far are 'Primary' or 'Disconnected'.

From documentation:

Possible values are PRIMARY (primary group configuration, quorum present), NON_PRIMARY (non-primary group configuration, quorum lost) or DISCONNECTED (not connected to group, retrying).

**Comment by ilyam8** [comment]
There are [3 possible values](https://github.com/codership/wsrep-API/blob/eab2d5d5a31672c0b7d116ef1629ff18392fd7d0/wsrep_api.h#L278-L281):
 - primary
 - non-primary
 - disconnected

**Comment by ced1check** [comment]
Whatever the values when it's set to 'Primary' I kept receiving a critical alert as shown in screenshot, until I made the change explained in first comment.

**Comment by ilyam8** [comment]
I have already [explained](https://github.com/netdata/netdata/pull/13550#discussion_r951353408) that the change is not correct (e.g. removing the alarm will also _solve_ the problem, but is not the correct way too).

> Chart is a flat and constant 0.

Then the `$this != 0` condition shouldn't trigger the alarm. 

Can you send me a [snapshot](https://learn.netdata.cloud/docs/dashboard/import-export-print-snapshot#export-a-snapshot) from any of your servers with MySQL Galera to `ilya@netdata.cloud`?

**Comment by ced1check** [comment]
I can't find any export button in the graphs, but here is a screenshot showing 0 for the past 2 days:
![image](https://user-images.githubusercontent.com/104206200/185925750-0e472ce6-4966-4594-8364-7c16cd4ffcdc.png)

And if I revert the configuration change, the critical alert is back.

**Comment by ilyam8** [comment]
Ok, I will set up a Galera cluster and see if I had the same problem.

**Comment by ilyam8** [comment]
We found the problem:

[galera_cluster_status](https://github.com/netdata/go.d.plugin/blob/faa01a27a40818eeef5b849ae599353ab000dc48/modules/mysql/charts.go#L751-L759) dimension is `cluster`. So this line
https://github.com/netdata/netdata/blob/c414aca77ab8f83fba9f8b22fa2c6448b5a5a5e4/health/health.d/mysql.conf#L161

should be changed to `calc: $status`, but it doesn't really a fix because `$status` is a [reserved variable](https://learn.netdata.cloud/docs/agent/health/reference#variables)

> $status, which is resolved to the current status of the alarm

There is no way to fix the alarm by changing the alarm config, it should be disabled e.g. by adding the `plugin: !*` line.

```
 template: mysql_galera_cluster_status
       on: mysql.galera_cluster_status
    class: Errors
     type: Database
component: MySQL
   plugin: !*
       ...
```

What I am going to do:
 - Change both `galera_cluster_status` and `galera_cluster_state` charts => from encoding a state with an integer (0: primary, 1: non-primary, 2: disconnected) to a dimension per state,(primary: 0 or 1, non-primary: 0 or 1, disconnected: 0 or 1).
 - Update mysql healtm templates.

---

On a side note, from our docs

> All calculations (i.e. addition, multiplication, etc) with a nan result in a nan.

Should all logicap operations result in False with nan? Because currently they don't:

https://github.com/netdata/netdata/blob/c414aca77ab8f83fba9f8b22fa2c6448b5a5a5e4/health/health.d/mysql.conf#L161-L163

the `crit` expressions results in True when `$calc` is nan. cc @MrZammler @stelfrag
