### ISSUE TITLE
[Feat]: Support unmounted THIN LVMs

### ISSUE THREAD

**Issue by fliespl** [netdata/netdata#13588]
### Problem

Currently if not mounted, they won't be shown in dashboard.

### Description

It's possible to collect those metrics using:

```
root@pve:/tmp# pvesm status
Name             Type     Status           Total            Used       Available        %
local             dir     active        98497780         5321000        88127232    5.40%
local-lvm     lvmthin     active       833396736         8834005       824562730    1.06%
```

Df showing that local-lvm is not mounted and hence not available as metric.
```
Filesystem           1K-blocks    Used Available Use% Mounted on
udev                  16212704       0  16212704   0% /dev
tmpfs                  3249412    1396   3248016   1% /run
/dev/mapper/pve-root  98497780 5321040  88127192   6% /
tmpfs                 16247052   44188  16202864   1% /dev/shm
tmpfs                     5120       0      5120   0% /run/lock
/dev/nvme0n1p2          523248     328    522920   1% /boot/efi
tmpfs                  3249408       0   3249408   0% /run/user/0
/dev/fuse               131072      32    131040   1% /etc/pve
```

### Importance

nice to have

### Value proposition

Not possible to monitor thin lvm partitions.

**Comment by mailinglists35** [comment]
this should be retitled without proxmox specifically because all modern linux distros ship `dm_thin_pool` kernel module out of the box

this weekend my thinpool overflowed and netdata didn't even get a whiff of it.

it's just a matter of parsing `/usr/sbin/lvm lvs` output `Data%` and `Meta%` columns. it works for unmounted volumes as well, however not for deactivated ones. it would also be nice to emit trend alerts like for regular free space ("it will be full in N hours if filled at current data rate")

````
$ sudo /usr/sbin/lvm lvs --select 'lv_attr=~^t.*'
  LV       VG     Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  thinpool hddvg  twi-aotz-- 450.00g             78.89  19.25
  thinpool os_hdd twi-aotz-- 100.00g             22.12  13.12
  thinpool ssdvg  twi-aotz-- 206.00g             0.01   1.65
````

this way all distros can be monitored, using standard lvm commands, and not just proxmox with their particular tools.

**Comment by kylernocturnalnerd** [comment]
Wanted to mention this as well. It's not really a proxmox thing.
I did notice this on my proxmox. Being able to see unmounted LVs is essential in enterprise environments. I'm surprised this isn't a higher priority.

**Comment by mailinglists35** [comment]
hi @ilyam8 , any chance at making this work?

**Comment by ilyam8** [comment]
I see that `lvm` requires root privileges

```bash
$ /usr/sbin/lvm lvs
  WARNING: Running as a non-root user. Functionality may be unavailable.
  /run/lock/lvm/P_global:aux: open failed: Permission denied
$ sudo /usr/sbin/lvm lvs
  LV   VG    Attr       LSize    Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  root cm-vg -wi-ao---- <199.52g
```

**Comment by ilyam8** [comment]
We discussed adding a helper executable with the setuid bit set that will be used by data collection plugins to execute commands that require elevated privileges.

- This helper will have a hard-coded list of commands+parameters so that only known and safe commands can be executed.
- It will be used/command will be added to it only if adding [capabilites](https://man7.org/linux/man-pages/man7/capabilities.7.html) to the plugin won't do.

It will help with `lvm lvs`.

**Comment by ilyam8** [comment]
The helper executable added in #16614

**Comment by ilyam8** [comment]
I added a simple collector that collects thin pools data/metadata % in #17394. I plan to improve, but I need to read some docs/articles about LVM - not a specialist. Also, suggestions are welcome.

**Comment by mailinglists35** [comment]
> I added a simple collector that collects thin pools data/metadata % in #17394. I plan to improve it, but I need to read some docs/articles about LVM first - not a specialist. Also, suggestions are welcome.

I think for my use case I would be happy to receive alerts about Data% and Meta% trends (filling up fast, close to 100%). See my comment https://github.com/netdata/netdata/issues/13588#issuecomment-1607195542
Do you already added to monitor these two values?

**Comment by ilyam8** [comment]
@mailinglists35 added % alerts in #17807
