### ISSUE TITLE
SNMP v3 not supported

### ISSUE THREAD

**Issue by Stonemage** [netdata/netdata#1363]
Was playing with netdata for the first time yesterday - love it and want to start installation across our network...

But it does not seem to work with SNMPv3!

Is this in a feature tracker or something? It's a total showstopper for us, with hundreds of devices already configured and using v3.

**Comment by ktsaou** [comment]
Well, to support SNMP v3 we need a library that supports it. The current implementation is based on `node.js`, so an SNMP v3 library for `node.js` would be the fastest way to support it in netdata.
Though, searching for it, does not reveal much...

Another way, is to re-write the SNMP plugin in python using `pySNMP` that seems to support SNMP v3, but I not that good in python...

**Comment by ktsaou** [comment]
I see that the `net-snmp` node.js library we use, has SNMPv3 in its roadmap: https://github.com/stephenwvickers/node-net-snmp#roadmap

**Comment by l2isbad** [comment]
Hundreds of devices with current netdata snmp implementation (which is very basic)? Are you sure @Stonemage ? It will result in 'administrative nightmare'

**Comment by Stonemage** [comment]
We have hundreds of devices that currently report via SNMPv3, through a number of different alerting, monitoring and trapping destinations.

We're evaluating netdata, but without SNMPv3 support we cannot give it a test within our current setup.

**Comment by markabrahams** [comment]
Hi team - FYI - I've just added SNMPv3 support to net-snmp, and it's available for use now at:
https://github.com/markabrahams/node-net-snmp

There's a PR open for this at nospaceships/net-snmp to merge into the main net-snmp repo, but it hasn't been merged as of yet - although it has been tested reasonably well.

To use pre-merge, just add this to package.json:
"net-snmp": "https://github.com/markabrahams/node-net-snmp.git"

and "npm install"

There's only one new public API call added to the net-snmp library:
snmp.createV3Session(target, user, [options])

which you would call for v3 instead of snmp.createSession(target, [community], [options]) for v1 or v2c.

Documentation for the new call is also at the above Github link.

Cheers, Mark.

**Comment by markabrahams** [comment]
FYI - SNMPv3 support has been merged and published in the net-snmp NPM, and so is available for use now.

**Comment by ilyam8** [comment]
@markabrahams thx you 👍
