### ISSUE TITLE
[Feat]: Re-organize Redis metrics

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata#13688]
### Description

Here's the proposed organization for Redis metrics - this is pretty close to what exists now, the extra ask is to add a new **Performance** section and to move some metrics to other sections. For example Evicted keys/second is related to maxmemory limit being hit and should be in memory section. 

- Connections
  - Accepted, rejected connections 
  - Clients (blocked, connected, in_timeout_table, tracking) 
- Performance
  - Latency (avg time for redis server to respond to a request)
  - Processed commands per second
  - Lookup hitrate
- Memory
  - Usage (dataset, lua, max, peak, rss, scripts, used)
  - Memory fragmentation (ratio between memory rss and used memory) 
  - Evicted keys/second (due to maxmemory limit) 
- Network
  - received/sent
- Replication
  - Connected replicas 
  - Time since last interaction (Time in seconds since last interaction between replica and primary)
  - Time since link down (Time in seconds since link between replica and primary went down) 
- Persistence 
  - Changes (ops that produced changes since the last save or bgsave)
  - Current bgsave time (duration of the ongoing rdb save if any)
  - Status of last rdb bg save 
  - Rdb last save time
- Commands
  - Commands by type 
  - Total CPU time consumed by commands (usec)
  - Avg CPU consumed per command execution
- Keyspace
  - Expired keys
  - Keys per database
  - Keys with expiration per database
- Uptime

### Importance

really want

### Value proposition

1. A more usable metric organization

**Comment by ilyam8** [comment]
Summing up all the changes:

 - Processed commands: commands => performance.
 - Keys lookup hit rate: keyspace => performance.
 - Evicted keys due to maxmemory limit: keyspace => memory.
 - merge "persistence rdb" and "persistence aof" into "persistence" (not sure tho, I guess you missed the "AOF file size" chart). Am I correct about this one?

@shyamvalsan, hey 🙋 Please add the changes list next time, it took me some time to figure out the diff despite very few changes (and because there is a missing metric (or metrics, I am not sure) and [new metrics](https://github.com/netdata/netdata/issues/13687)).

**Comment by ilyam8** [comment]
@shyamvalsan if you don't mind I am going to close this ticket by merging netdata/go.d.plugin#848. Some metrics (requested in #13687) are missing, but I think one issue is enough, we don't need both.
