### ISSUE TITLE
[Feat]: Add a default windows_export job in wmi.conf, for WSL

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#13716]
### Problem

It's easy to auto-detect a default installation of windows_exporter (and any other prometheus endpoints, actually), when running netdata on WSL. But we're not doing it.

### Description

WSL has this very nice feature, that the windows host it's running on can be accessed via the hostname `$(hostname).local`
e.g.
```
root@DESKTOP-C7OKV71:/etc/netdata# echo $(hostname).local
DESKTOP-C7OKV71.local
```
So this actually works:
```
wget -O sample http://$(hostname).local:9182/metrics
```

We should add some way to do this as a default job in our default wmi.conf (I expect it doesn't dereference shell variables, but I don't know)

### Importance

really want

### Value proposition

zero config for the wmi and probably all prometheus collectors on WSL, to monitor the host we're installed on.

**Comment by Ferroin** [comment]
I would say we can probably go a step beyond this, and add jobs for _any_ collectors that would be expected to work against a Windows system using this mechanism (in particular, _most_ of the network services we have collectors for do support running on Windows).

On a side note, this actually happens to work on any Linux system with a properly configured mDNS stack as well, so we ideally should have this be a ‘fallback’ job for any collectors expected to work on both Linux and Windows in case trying to connect to `localhost` fails for some reason other than authentication issues.

**Comment by cakrit** [comment]
This is a brilliant idea. Indeed, everything we do an HTTP request against  will work (including all Prometheus collectors), database access, pretty much every single job that has a localhost should also be running against `$(localhost).local`.

**Comment by ilyam8** [comment]
> pretty much **every single job** that has a localhost should also be running against $(localhost).local

Why? Isn't this needed only for one collector (wmi)?

**Comment by ilyam8** [comment]
Also, the case is pretty much you testing Netdata on WSL. I doubt somebody will install Netdata on a win machine to monitor it (because it is not possible), I assume the default use case is installing Netdata on a Linux server and collect windows metrics from it (one server collects metrics from N wmi_exporters).

**Comment by ilyam8** [comment]
> as well so that it just works under WSL for stuff running on the Windows side.

What stuff? Can you be more specific? I don't remember any requests (issues), so I have nothing in mind.

---

Regarding the 2nd topic - it is like installing Netdata in a Docker container and calling it macOS support. I don't understand the point.

What I am saying is:
 - you need `$(hostname).local` only for wmi_exporter (assuming the thing is installed!).
 - you need `$(hostname).local` only when Netdata is installed under WSL. And my assumption is that this case is not common, because there is no benefit in this setup (only curiosity I guess). This makes the `$(hostname).local` thing pointless.

**Comment by cakrit** [comment]
Getting `wmi_exporter` to work with this default job is the minimum. 
I said "stuff" thinking along the lines of @Ferroin 's brilliant idea that anything at all running on that windows host that is accessible via tcp is also accessible to our collectors. So the idea is to ensure that in every place where we have a job configured for `localhost` (e.g. mysql), we also add a job for `$(hostname).local` (however that will be specified on the config. it could for example be called "wsl-windows-localhost" or something like that, but if `$` doesn't do something special in the config, we might as well use that).

**Comment by cakrit** [comment]
@ilyam8 see if it's possible to get this done next week, if not this one.

**Comment by ilyam8** [comment]
@cakrit will check today, downloading windows11...

**Comment by ilyam8** [comment]
@cakrit I went with just replacing `hostname` in the URL host.

```yaml
jobs:
  - name: local
    url: http://hostname.local:9182/metrics
```

**Comment by cakrit** [comment]
I really think that it will be confusing in the overview screen, if we leave the job name like this. We can't group by URL. 
Can you make the name hostname as well and put the result of the command there too?

**Comment by cakrit** [comment]
BTW I haven't yet tested it, will do so tomorrow.
