### ISSUE TITLE
[Feat]: Add Functions capability

### ISSUE THREAD

**Issue by amalkov** [netdata/netdata#13950]
### Problem
After introducing the Functions feature we need to know that the Agent support this or not

### Description

Epic: https://github.com/netdata/netdata-cloud/issues/602
Initial implementation (BE): https://github.com/netdata/cloud-backend/issues/380

### Importance
really want

### Value proposition
We would be able to know upfront do we need to make a call to get a list of all available Functions from the Agent or not.

### Proposed implementation
Add Functions capability to the list of capabilities supported by the Agent
In case Functions are disabled via configuration options, we should not add "functions" to the list of supported capabilities

FYI: @ktsaou @underhood @papazach

**Comment by papazach** [comment]
From cloud-be side, after agreeing on the actual capability name - mentioning this since I know that @underhood is a fan of small capability names [maybe `funcs` ?] - we should not have a lot to actually do given that the mechanism is already in place.

So those new capabilities should be present in the `api/v2/spaces/{spaceID}/rooms/{roomID}/nodes` response and the front-end could use them to filter the applicable nodes accordingly.

**Comment by ktsaou** [comment]
@underhood this would be nice to have before the release. Is it something simple for you to do today?
