### ISSUE TITLE
[Feat]: Don't update latest on Docker Hub everytime something is pushed to master

### ISSUE THREAD

**Issue by MrAlucardDante** [netdata/netdata#14022]
### Problem

On Docker Hub, there is currently no difference between the edge and the latest tags.

Everytime there is a commit pushed to the master branch, both tags are updated.

### Description

The latest tag should point to the latest official release, and the edge tag should point to the master.

Some might even say that everytime something is pushed to master, there should be a new official release and the edge tag should point to a develop branch, but that's not the point of this issue.

When we use something like watchtower or diun, we got notifications multiples times a week (or even a day) that a new version is available, even though it is not the case.

### Importance

really want

### Value proposition

1. Update you CI pipeline so the latest tag on the Docker Hub points to the latest available version and not your master branch
2. Alternative: Update your gitflow

### Proposed implementation

The latest tag should point to the latest official release, and the edge tag should point to the master.

**Comment by Ferroin** [comment]
Strictly speaking, `edge` is tracking our nightly builds, not ‘every commit to master’. This is an intentional choice because building our Docker images is not computationally cheap (a full build takes about 90 minutes right now), so it’s impractical for us to build on every single commit (and it also means that we have Docker images that track our nightly builds).

As far as tracking the latest release, we provide a `stable` tag for people who wish to do that, but in all practicality, nobody should be using that in production because you have no way to guarantee that things will not randomly break because of an upgrade. Actual production usage should be using our semver tags (for example, `netdata/netdata@v1`) to ensure compatibility.

As far as `latest`, that’s tracking the most recently pushed images, irrespective of what other tags are on the images. The _only_ reason we provide this tag at all is so that `docker pull netdata/netdata` without an explicit tag works, and the only reason we care about that is because people who are testing images by hand tend to not think to specify an exact tag. Nobody should be using this in production for reasons that have exactly nothing to do with how we happen to provide the tag (most notably the exact same compatibility issue mentioned above regarding the `stable` tag).

**Comment by MrAlucardDante** [comment]
Thank you for the clarification.

I wasn't aware of the existence of the stable tag, it's buried down the list on the docker hub page. I will update my compose so it watch stable instead of the latest.

I am closing this issue

**Comment by Ferroin** [comment]
> I wasn't aware of the existence of the stable tag, it's buried down the list on the docker hub page.

Indeed, I’ve updated the Overview tab on DockerHub for the netdata/netdata image to more clearly describe these tags so that they’re a bit more visible, with the hope that there’s a bit less confusion about them going forwards.
