### ISSUE TITLE
[Feat]: Virtual Hosts support

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#14127]
### Problem

It is not possible to present as a Netdata host:
- a Windows host (an instance running [windows_exporter](https://github.com/prometheus-community/windows_exporter#windows_exporter)).
- a group of processes running on a remote host that does not have Netdata installed.

### Description

It would be very nice to be able to create a virtual (Netdata) host with a dedicated set of data collectors. Collectors are limited to those that collect metrics from remote instances.

For instance:

 - Windows instances.
 - A group of remote Postgres servers.

The virtual host will have its own dashboard and will be accessible via `IP:PORT/host/HOSTNAME`. The same as replicated nodes.

### Importance

must have

### Value proposition

1. Windows hosts are presented as hosts, not as a section on the dashboard.
2. Clearer separation in the cloud of processes that do not actually belong to the Netdata host performing the data collection.

### Proposed implementation

- Every virtual host has its configuration under `/etc/netdata/hosts/<NAME>/`.
- The host metadata can (perhaps part of it - must) be set manually in (for instance) `host.yaml`.
- The host GUID should be generated by a user and be a separate file under the virtual host directory.

Those are general points and are provided just to show the idea.

```cmd
# tree /opt/netdata/etc/netdata/hosts/
/opt/netdata/etc/netdata/hosts/
├── my-windows-1
│   ├── go.d
│   │   └── wmi.conf
│   ├── host.yaml
│   └── netdata.public.unique.id
└── my-windows-2
    ├── go.d
    │   └── wmi.conf
    ├── host.yaml
    └── netdata.public.unique.id
```

**Comment by cakrit** [comment]
To add a couple of points:
- For Windows hosts we can generate some of the optional metadata, with info from the windows_exporter
- Initially, every directory under hosts will result in a separate go.d.plugin process, spawned by netdata, each with its own pipe to Netdata. In the long run we'd like to replace these with a single process that opens multiple TCP sockets to the deamon.
- When we build this we'll also stop nesting the windows_exporter metric categories (e.g. IIS) under a section for each job. They will be promoted to the root level, same as with linux host metric categories per collector

**Comment by Ferroin** [comment]
> * Initially, every directory under hosts will result in a separate go.d.plugin process, spawned by netdata, each with its own pipe to Netdata. In the long run we'd like to replace these with a single process that opens multiple TCP sockets to the deamon.

I would argue that it’s actually beneficial to have separate processes. Then a user somehow compromising the plugin for one virtual host does not potentially get things like credentials for other virtual hosts.

That said, this should probably be a configuration option, as whether or not the security implications matter is dependent on what the user is doing.

Also, I would argue that we should be looking at UNIX sockets instead of TCP sockets here unless we think it’s a good idea to support running the plugin on a remote host directly (and hey, that may actually be a good idea for Windows monitoring), and seriously consider just updating the plugin protocol to support multiplexing the data for separate virtual hosts over one connection.
