### ISSUE TITLE
Add support to monitor interrupts through /sys/kernel/irq

### ISSUE THREAD

**Issue by infectormp** [netdata/netdata#1416]
In kernel 4.9 was added ability expose interrupt information through sysfs 

https://lkml.org/lkml/2016/9/14/431
> Information about interrupts is exposed via /proc/interrupts, but the
> format of that file has changed over kernel versions and differs across
> architectures. It also has varying column numbers depending on hardware.
> 
> That all makes it hard for tools to parse.
> 
> To solve this, expose the information through sysfs so each irq attribute
> is in a separate file in a consistent, machine parsable way.

**Comment by ktsaou** [comment]
thanks! I didn't know that!

It seems however that they have chosen to create a directory for each interrupt, with the information spread over several files for each interrupt. This will slow down netdata, as it will have to read way too many files on systems with many cores.

Check for example this little system: #1323

**Comment by yetanothernerdk** [comment]
Hi @ktsaou I would love to contribute on this feature. For this feature I'll need to read `/sys/kernel/irq/*/*` to read how many interrupts are being used by kernel and more detailed information can be read for each of them by reading files such as `actions, chip_name, hwirq, name, per_cpu_count, type`, etc. These are files present in each interrupt directory. Please correct me if my understanding is wrong.

For this development I'm using Ubuntu 16.04 on virtual box. I have already compiled Linux Kernel 4.9.0 for the same.

I need some help on understanding the source code. For this feature I'll create file under directory `src`
e.g. file name can be `sys_irq.c` and I'll write my code in it. Am'I understanding this right?

**Comment by yetanothernerdk** [comment]
Thanks for the reply @ktsaou 
We already have interrupt interface from `/proc/interrupts`.
Are we going to keep this interface parallel with `/sys/kernel/irq/`?
Please bear with me if I'm asking too many questions, This is my first time to contribute to an project. 

The chart idea for the new `/sys/kernel/irq/` interface will be same as `/proc/interrupts` 
A chart that will show number of interrupts per sec 
Source for this chart will be `/sys/kernel/irq/*/per_cpu_count`
We'll need to read `per_cpu_count` for each of the IRQ number 
The file `per_cpu_count` has number of times the interrupt has fired since boot.  It contains a comma-separated list of counter, one per CPU in CPU id order. We need to add this count for each of the IRQ to get interrupt per second count.
Need thoughts on this chart.

**Comment by ktsaou** [comment]
Well, the challenge with this implementation will be its performance.

Check this:

```
cat /proc/interrupts 
           CPU0       CPU1       CPU2       CPU3       CPU4       CPU5       CPU6       CPU7       
  0:      24980      68619      24777      34647       1087      25379       3694      21103   IO-APIC-edge      timer
  1:          1          1          1          2          1          1          1          0   IO-APIC-edge      i8042
  8:          0          0          0          0          0          0          0          1   IO-APIC-edge      rtc0
  9:          0          0          0          0          0          0          0          0   IO-APIC-fasteoi   acpi
 12:         17         21         15         13          6         22         18         12   IO-APIC-edge      i8042
 14:         12          6         13         11         15         12         13          8   IO-APIC-edge      ata_piix
 15:          0          0          0          0          0          0          0          0   IO-APIC-edge      ata_piix
 16:          2          4          3          1          0          3          0          1   IO-APIC-fasteoi   ehci_hcd:usb1, uhci_hcd:usb2
 17:          7          6          5          7          0          6          0          2   IO-APIC-fasteoi   uhci_hcd:usb3
 18:          0          0          0          0          0          0          0          0   IO-APIC-fasteoi   uhci_hcd:usb4
 19:          0          0          0          0          0          0          0          0   IO-APIC-fasteoi   uhci_hcd:usb5
 22:         12         14         12         12         11          9         10         14   IO-APIC-fasteoi   uhci_hcd:usb6, hpilo
 24:   13313507     893457   21843308     994023 2354801727 4038548165  162282882 1617888612   IO-APIC-fasteoi   eth2, eth0
 25:   90307738     951638   83677526     710790  251693243 1884258504 2990061485 2809700051   IO-APIC-fasteoi   eth1, eth3
 59:  116626972   60142233  135588950  146089492   22159321   13011094   21687982   37837939   PCI-MSI-edge      cciss0
 61:    2491907        884    4855049        797    3112771       8192    3627235 1397656988   PCI-MSI-edge      eth4
 62:   42058225    7366339   93073189    7364096 3801023607   94802476  158637753    7170666   PCI-MSI-edge      eth5
NMI:          0          0          0          0          0          0          0          0   Non-maskable interrupts
LOC: 1552695591  841160370 1732845096 2445598025  888657821 1708815569 4211773352  532439222   Local timer interrupts
SPU:          0          0          0          0          0          0          0          0   Spurious interrupts
PMI:          0          0          0          0          0          0          0          0   Performance monitoring interrupts
PND:          0          0          0          0          0          0          0          0   Performance pending work
RES:  386313398  403332682  373386415  316364545  304864138  413893576  294950934  342496442   Rescheduling interrupts
CAL:   93749672  125795724   96412154  113465425      47845      46232      47786      47304   Function call interrupts
TLB:  972592326  985788758  871693924  878426772 1912084958 2088802789 1923986192 1967037478   TLB shootdowns
TRM:          0          0          0          0          0          0          0          0   Thermal event interrupts
THR:          0          0          0          0          0          0          0          0   Threshold APIC interrupts
MCE:          0          0          0          0          0          0          0          0   Machine check exceptions
MCP:     204242     204242     204242     204242     204242     204242     204242     204242   Machine check polls
ERR:          0
MIS:          0
```

The above produce 1 chart for the system and 1 chart for each CPU core.

It is 35 lines, times 8 cores = 280 metrics. Are you going to read all these from 280 files + the files needed to read labels, etc?

It will be challenging to do it efficiently. You can use `procfile` (already in netdata), but to avoid opening and closing the files every second, you are going to need an internal structure to keep track of everything.

**Comment by yetanothernerdk** [comment]
> Are you going to read all these from 280 files + the files needed to read labels, etc?

For the chart which I'm suggesting, there is no need to read 280 files, We only need to read `/sys/kernel/irq/*/per_cpu_count` file for each IRQ. i.e. in your example I'll need to read 35 files and not 280 files. Because `per_cpu_count` file will have comma separated list of number of times the interrupt is served.

Consider following:

```
cat /sys/kernel/irq/21/per_cpu_count
12414,1112
```


In this example I'm reading `per_cpu_count` for IRQ number 21.
The IRQ 21 interrupt is served by CPU0 for 21414 times and it is served by CPU1 for 1112 times.

Clearly if we read interrupts from `/proc/interrupts`, then we have only 1 file to read.
But we need to do processing on output of that file.
And if we want to read interrupts from `/sys/kernel/irq`, then we need to read multiple files.

Same way, To read labels we again need to read a file per interrupt i.e. 35 files in your example.

Obviously reading from `/sys/kernel/irq' will have overhead than reading from '/proc/interrupts'.
But the [thread](https://lkml.org/lkml/2016/9/14/431) says

> Information about interrupts is exposed via /proc/interrupts, but the
format of that file has changed over kernel versions and differs across
architectures. It also has varying column numbers depending on hardware.

So if someone using netdata for IoT devices which has different architectures, then reading from the `/sys/kernel/irq` will be very helpful.

What do you say?

**Comment by ktsaou** [comment]
nice! ok, let's do it...

**Comment by yetanothernerdk** [comment]
### Great.
I need some more help. How to make a testing setup for the project?
As you suggested in [comment](https://github.com/firehol/netdata/issues/1416#issuecomment-272520299) I have added new file and exposed the new function.
After added changes I'm building and installing project using `./netdata-install.sh`. Is it right?
I'm not great into `HTML/CSS` part, How will I be able to show raw data read from `/sys/kernel/irq*` into HTML page?

**Comment by yetanothernerdk** [comment]
OK. I'm enabling debug logs so that, it'll help me with testing.

 I'm adding following debug print in my do_proc_sys_kernel_irq function

`debug(D_CONFIG, "Hello debugging Its %s", "netdata");`

Also I'm enabling the debug log by setting the debug flag to 0xffffff in `\etc\netdata\netdata.conf` file as stated [here](https://github.com/firehol/netdata/wiki/Tracing-Options).
Then doing `killall netdata` to stop netdata and `sudo netdata` to start netdata with new configuration.
But I'm not getting any debug logs in `/var/log/netdata/debug.log`
What am I missing here?

**Comment by yetanothernerdk** [comment]
Hi @ktsaou 
I have created basic [algorithm](https://docs.google.com/document/d/1MuvM9nX6z293TxWcZLz09QG2ptNME_3rjSLeV8-MfkE/edit) for this. You can have look at it and give comment. Also I have started coding. 
Please review code [here](https://github.com/yetanothernerdk/netdata) and provide some comments or suggest changes if needed. The code is work in progress. 

Thank You.

**Comment by ktsaou** [comment]
@yetanothernerdk I read the code here: https://github.com/yetanothernerdk/netdata/blob/master/src/sys_kernel_irq.c

There are several problems about this. The key problem is that you execute shell commands from a `C` program. You cannot do this.

I suggest to review the way `proc_interrupts.c` works and try to come with code to do something similar.

**Comment by yetanothernerdk** [comment]
Hi @ktsaou 
Thanks for your time on this.
I have changed implementation to use `opendir`, `readdir` and `closedir` calls, compliant to `POSIX.1-2001`
Please look at the new implementation [here](https://github.com/yetanothernerdk/netdata/commit/256188c9ac94df32a644da4b71c904493cbdfc25)
Can I use these (`opendir`, `readdir `and `closedir`) calls?
Is there any specific reason why we don't want to execute shell command from `C` program?

**Comment by yetanothernerdk** [comment]
I'm getting "Error 405: Cannot download chart index from server: http://localhost:19999/api/v1/charts"
More [details](https://github.com/yetanothernerdk/netdata/commit/8006d3014b003ec3e1158b70e990fbacfb6ffe4a#commitcomment-20535725)

**Comment by ktsaou** [comment]
> I'm getting "Error 405: Cannot download chart index from server

Check the permissions of the web directory and netdata error.log

> Is there any specific reason why we don't want to execute shell command from C program?

`popen()` is the worst command ever, in terms of performance. It `forks()` netdata, loads the shell interpreter, which then forks again to execute the command you are interested, then the output of this command is send to netdata via a pipe, so both the called program and netdata use slow file I/O to communicate. Your code called several `popen()` per iteration. This is: several per second. Run your code and then examine the relative charts in netdata. Check the system.processes chart, the memory page faults charts, the system.load chart, etc. You cannot use `popen()` in netdata except when it is absolutely necessary.

> Can I use these (opendir, readdir and closedir) calls?

The whole idea with netdata is performance. We cannot merge code that is not excellent in terms of performance. And we constantly improving it.

Questions like this can be answered by you. You don't need my help: Do you really have to use these calls **every single second data are collected?** Why? Do the interrupts of the machine change every single second? If they don't, you should not call them all the time. You can call them once and then collect only values. If something can change over time, but not every second, then you could refresh it every 10 or 100 iterations.

As I said, please review the way netdata works. If you want your code to be merged, it has to be done the "netdata way". For example, we don't write parsers for proc and sys files. There is `procfile` for that. We don't call `malloc()` or `calloc()`, but we allocate memory with the `z` set of functions, etc.

First understand how it works, then write code to make it better.

**Comment by yetanothernerdk** [comment]
> netdata error.log

Helped. Thanks for that.

> You cannot use `popen()` in netdata except when it is absolutely necessary.

Totally got it.

> opendir, readdir and closedir

I'm sure that there is no alternate to this calls. If we want to read interrupt data from `/sys/kerel/irq`.
Because this directory is going to have multiple directories associated with each interrupt. And number of sub-directories under this directory does not match with number of interrupts in `/proc/interrupts`
Following is the directory structure:
```
$ tree /sys/kernel/irq/
/sys/kernel/irq/
├── 0
│   ├── actions
│   ├── chip_name
│   ├── hwirq
│   ├── name
│   ├── per_cpu_count
│   └── type
├── 1
│   ├── actions
│   ├── chip_name
│   ├── hwirq
│   ├── name
│   ├── per_cpu_count
│   └── type
├── 10
│   ├── actions
│   ├── chip_name
│   ├── hwirq
│   ├── name
│   ├── per_cpu_count
│   └── type
...
```
The number of directories in `/sys/kernel/irq` will change if someone removed/inserted a kernel module associated with a IRQ. So I'll need to read number of directories present in `/sys/kernel/irq` each second.
Based on this value if number of directories are increased/decreased then I'll change my static structure holding all interrupt data, and read all data again. And in practical there will be very less probability of this.

With some new clarity I have updated the [algorithm](https://docs.google.com/document/d/1MuvM9nX6z293TxWcZLz09QG2ptNME_3rjSLeV8-MfkE).

One more concern here is using procfile_open:
As the number of directories in `/sys/kernel/irq` (number of interrupts present in system) are dynamic, and hence number of files I'll need to read. From previous code I see that I'll need to create static procfile handle for each file I need to open.
e.g. Say I need to read `/sys/kernel/irq/*/per_cpu_count'. And I have 20 interrupts in my system.
Then I'll need  to open 20 procfile handles. If I create dynamic number of procfile handler, then I need to do dynamic memory allocation for them. But as you see [here](https://github.com/yetanothernerdk/netdata/blob/master/src/procfile.h#L61)
```
typedef struct {
    ...
    char separators[256];
    char data[];        // allocated buffer to keep file contents
} procfile;
```
The last element in procfile struct is already dynamic, and I can't guess the size of data from `/sys/kernel/irq/*/per_cpu_count` file, it will be very dynamic.
I'm trying to find solution to this problem and help is always welcome.

**Comment by yetanothernerdk** [comment]
Ok. I have code working now to read `hwirq `number and `chip_name` for each interrupt.
You can review it [here](https://github.com/yetanothernerdk/netdata/blob/master/src/sys_kernel_irq.c)

**Comment by ktsaou** [comment]
nice. Seems a lot better. I'll review it in detail in the weekend. Thanks!

**Comment by yetanothernerdk** [comment]
@ktsaou Did you got time to go through code? Any comments?

**Comment by ktsaou** [comment]
yes, I saw it. It is really a lot better.

You are returning in a few places, inside `opendir()` without calling `closedir()`. This is a memory leak.

Since `do_proc_sys_kernel_irq()` will be called once per second, I suggest to do this:

1. Create a function called `reload_interrupts()` to create/update a global array of `struct interrupt *interrupts_root` . This function should be called once every minute.

   This will be tricky, since interrupts may have added or removed. Probably it is better to turn it to a linked list so that you can add/remove interrupts on demand.

   To call this function once every minute, you could add `dt` on every iteration, until the sum reaches `60 * USEC_PER_SEC` (60 seconds). Then you should call `reload_interrupts()` again and  zero the sum.

   The values collected are per CPU, so each such structure will need an array of `collected_number values[processors + 1]`. `processors` is a global variable of netdata and resolves to the number of CPUs the machine has. You need `+1` because you are going to need also the total (for a chart that shows the total interrupts of the system).

   You are going to need an array of `RRDDIM dimensions[processors + 1]`, since your are going to produce a chart for each CPU, so you will need a pointer to the dimension of this interrupt for each chart.

   In this function you should read everything about the interrupt, except the values.

2. On each iteration, walk through the interrupts array or linked list and read/parse the file `per_cpu_count`. 

   You should keep the filename to read and a `procfile *ff` pointer inside `struct interrupt`, to avoid opening and closing the file all the time.

   Keep in mind that file has the comma as separator. You can give a string with separators to `procfile_open()`, so the number will be splitted already.

3. Then, loop through all available processors, generating/updating the charts.

4. Then, generate/update the chart for the total interrupts of the system.

**Comment by yetanothernerdk** [comment]
Hi @ktsaou I have implemented link list. You can review base code [here](https://github.com/yetanothernerdk/netdata/blob/linkedlist_implimentation/src/sys_kernel_irq.c)
(Still need to implement reading of files).
If a interrupt got removed from system, then I'm removing it from link list. I hope this is fine. Or we should keep it for reference.
Also I'm having difficulties in understanding how the charts and `RRDDIM dimensions` integrates.

**Comment by cakrit** [comment]
@yetanothernerdk the links to the code you were working on are no longer valid. Do you have it somewhere? Will you be able to continue on this?

**Comment by ilyam8** [comment]
Closing this issue due to the low interest in this feature.

If there is anybody who is interested in having this implemented please visit our Community Forums and create a new topic in the [Netdata Agent Feature Requests](https://community.netdata.cloud/c/feature-requests/agent-fr/21) category.
