### ISSUE TITLE
[Feat]: Being able to monitor updates of the installed packages on the server

### ISSUE THREAD

**Issue by SofianeHamlaoui** [netdata/netdata#14259]
### Problem

Keeping track and having information about all kind and every important package ( software ) updates.

### Description

So, Netdata is about monitoring ! 

So the idea is about being able to watch and be informed about any kind of new updates of the installed packages on the server.

Let's say : I have **python**, **php** and **nodejs** installed on my server.

I want to be able to get notifications ( of any kind ) as soon as there is an update for Python, PHP or NodeJS. 

For the moment the solution I'm using is a small script that does it ( kind of ) automatically with each package update, the previous version and the new update version.

It'll be perfect to have that on Netdata directly.

### Importance

must have

### Value proposition

1. More Monitoring
2. Getting notifications about packages updates which means having updates packages on your server ( more security ) 
3. Being informed of critical updates that needs and has to be done 
4. more help for SysAdmins
...

**Comment by ilyam8** [comment]
Hi, @SofianeHamlaoui. Thanks for the request. But it looks like out of scope for Netdata.

**Comment by SofianeHamlaoui** [comment]
> Hi, @SofianeHamlaoui. Thanks for the request. But it looks like out of scope for Netdata.

Do you have or can propose any alternative for that ?

**Comment by ilyam8** [comment]
No, I have nothing to propose.

**Comment by andrewm4894** [comment]
@SofianeHamlaoui you could maybe build a custom collector to check the versions like you say and then sort of map that to a status of 0=no updates available and 1=updates are available. 

This would be sort of like what we do for the [alarms collector](https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/alarms/alarms.chart.py) but you would just need some sort of function to do the status check and define what the current status is. 

So it's not quite a fit for netdata core since it's not really time series based metrics or monitoring but that's not to say it cant be done. If you wanted to have a go at a custom python collector and contribute it to [netdata/community](https://github.com/netdata/community/tree/main/collectors) where other users can then independently install and use it if they wanted (without it being included in the netdata agent itself and not supported by netdata) i'd be happy to help.

**Comment by nodiscc** [comment]
I wrote a collector a while ago that will raise an alarm when package updates are available: https://gitlab.com/nodiscc/netdata-apt. It only supports the `apt` package managed (Debian-based distributions, only tested on Debian).

I have been using it for about 1 year and it's proven very useful.
