### ISSUE TITLE
[Feat]: Allow users to configure Netdata to call local kubelet server for metrics to avoid overtaxing the kube api servers

### ISSUE THREAD

**Issue by data-dude** [netdata/netdata#14843]
### Problem

In large clusters Netdata agents can cause serious stress to the kubernets api server.  If you try starting all the agents at once they all hit the k8s api server and can actually cause it a denial of service incident.  

### Description

Allow users to set Use_Kubelet configuration, just like Fluentbit, that instructs  Netdata agents to call the local kublet server api instead of the kubernetes api server.

### Importance

really want

### Value proposition

1.
2.
3.
...

### Proposed implementation

One solution is to configure Netdata to query metrics from the local Kubelet, instead of hitting the kube api servers.

**Comment by ilyam8** [comment]
Hi, @data-dude. I believe Kubelet doesn't provide the needed information. We query the K8s API server to map the container id to K8s Pod/container and its metadata ([namespace, pod_name, pod_uid, controller_name, etc.](https://github.com/netdata/netdata/blob/ec5c038f2ca3f665490887f6c690445e93c27a33/collectors/cgroups.plugin/cgroup-name.sh#L334-L347)).

> can actually cause it a denial of service incident

Why do you think so?

Netdata:

 - queries only the list of pods running on the same host [using fieldSelector](https://github.com/netdata/netdata/blob/ec5c038f2ca3f665490887f6c690445e93c27a33/collectors/cgroups.plugin/cgroup-name.sh#L306-L307).
 -  caches (stores on the host filesystem) /api/v1/pods response and check it before querying K8s API (only for containers). This makes it much less likely to make requests to the K8s API.

**Comment by data-dude** [comment]
I have a 100+ cluster and each server may have 100+ pods.  If I were to deploy netdata agent to all pods the kubernetes api will stop serving.  It'll be so overloaded with requests that it suffers a denial of service.   I have to deploy 10 at a time to avoid this.

This site describes the kubelet api
https://www.deepnetwork.com/blog/2020/01/13/kubelet-api.html

I don't know if it has everything you need but it has quite a bit.

**Comment by data-dude** [comment]
What I observe is if I were to deploy 100+ netdata agents to servers which have 100+ pods running on them the K8s API server becomes unresponsive to the whole cluster.   I have a graph that shows k8s api calls and it goes down to almost 0.    There's also a metric called apiserver_current_inflight_requests and it rockets up.   K8s api server can't handle the amount of queries hitting it.  Fluent-bit is aware of this problem and so they made it configurable so that agents could call the local kubelet instead.

**Comment by ilyam8** [comment]
Yes, I missed that Kubelet has `/pods` endpoint that returns the runnings pods metadata. I will check it.

**Comment by ilyam8** [comment]
Hey, @data-dude. I added an option to use Kubelet for pods metadata, but it may not fix the problem, because:

 - Netdata does [2 requests to the K8s API on startup to get its own Pod labels](https://github.com/netdata/netdata/blob/1c46b32bbebd12e18cc4b9dc416d2336368c025c/daemon/get-kubernetes-labels.sh.in#L21-L31).
 - [k8sState instance](https://github.com/netdata/helmchart/blob/dd2f6dc62dd608d3002dd3606839342110f001f2/charts/netdata/values.yaml#L376-L377) subscribes to the K8s API and receives a lot of metrics. Not sure if this can be a problem, but you can try disabling it if switching to Kubelet for Pods meta is not enough.

---

I build a docker image with #14891 changes - `ilyam8/netdata-test-for-github`. Can you test it? You need to:

- use the `ilyam8/netdata-test-for-github` image.
- set the `USE_KUBELET_FOR_PODS_METADATA` env var for `child`.
- (optionally) disable k8sState.

This is override:

```yaml
image:
  repository: ilyam8/netdata-test-for-github
  tag: latest

child:
  env:
    USE_KUBELET_FOR_PODS_METADATA: "1"

k8sState:
  enabled: false
```

**Comment by data-dude** [comment]
Ok I'll test it out

**Comment by ilyam8** [comment]
```
git clone --recursive https://github.com/ilyam8/netdata nd_ilyam8
cd nd_ilyam8
git checkout cgroups_k8s_use_kubelet_for_pods_metadata
docker build -t USERNAME/REPONAME .
```

**Comment by ilyam8** [comment]
@data-dude forgot to add, you need to update netdata helmchart.

**Comment by data-dude** [comment]
@ilyam8 An issue people run into is that localhost doesn't work for some clusters.  If you look at the fluent-bit solution they allow the user to configure the kubelet_host.  For some clusters localhost works, but for some of my other clusters i need to set the node name for it to work.

e.g.
```
- env:
  - name: NETDATA_HOST
    valueFrom:
       fieldRef:  
         fieldPath: spec.nodeName
 
```
When I ran your change I saw this in my logs:

error on curl 'https://localhost:10250/pods' the request url returned 403

I ran into this same problem with fluent-bit but was able to get around it by setting the environment variable and then using that in my configuration.

**Comment by ilyam8** [comment]
Hey, @data-dude. Just pushed a [commit](https://github.com/netdata/netdata/pull/14891/commits/a838bc1f332ca1ba3c8c49eda65851944021b1f7) to use [MY_NODE_NAME](https://github.com/netdata/helmchart/blob/dd2f6dc62dd608d3002dd3606839342110f001f2/charts/netdata/templates/daemonset.yaml#L102-L105) as host.

You need to `git pull` my branch and rebuild the image.

**Comment by ilyam8** [comment]
@data-dude 

- [X] our latest helmchart [contains all required groups](https://github.com/netdata/helmchart/blob/dd2f6dc62dd608d3002dd3606839342110f001f2/charts/netdata/templates/clusterrole.yaml#L11-L29).
- [ ] PR in netdata/netdata (#14891).
- [ ] PR in netdata/helmchart (netdata/helmchart#349).

> Also my deployment already has an env var names MY_NODE_NAME.

I changed the logic a bit. To change the Kubelet address you need to use `KUBELET_URL` endpoint. The default is `https://localhost:10250`.


After netdata/helmchart#349 is merged there will be no need to set env vars because I added new values. To enable querying Kubelet and use the URL that works in your case, you need the following:

```yaml
child:
  podsMetadata:
    useKubelet: "1"
    kubelerURL: "https://$(MY_NODE_NAME):10250"
```
