### ISSUE TITLE
[Bug]: Netdata nightly behind stable

### ISSUE THREAD

**Issue by etec-masterofsynapse** [netdata/netdata#14851]
### Bug description

In your docs (https://learn.netdata.cloud/docs/getting-started/install-netdata#:~:text=By%20default%2C%20Netdata%27s%20installation%20scripts%20will%20give%20you%20automatic%2C%20nightly%20updates%2C%20as%20that%20is%20our%20recommended%20configuration.), you write that the nightly channel will give us automatic nightly updates.
But currently, the newest stable is v1.38.1 and the latest nightly is v1.38.0-333-nightly, so a minor version behind stable.

How can that be when you are publishing daily nightly builds and the latest stable is from Feb 13, over 6 weeks ago?

### Expected behavior

Newer nightly version than stable.

### Steps to reproduce

Not relevant to issue.

### Installation method

kickstart.sh

### System info

```shell
Not relevant to issue.
```

### Netdata build info

```shell
Not relevant to issue.
```

**Comment by MrZammler** [comment]
Hi @etec-masterofsynapse 

Indeed, there can be some confusion there. However, v1.38.0-333-nightly is in fact newer than the v1.38.1 stable version (and of course contains what v1.38.1 does).

**Comment by etec-masterofsynapse** [comment]
Hi @MrZammler ,
then why does the nightly, which is newer than 1.38.1, still have 1.38.0?
Shouldn't it be v1.38.1-XXX-nightly?

**Comment by Ferroin** [comment]
> Hi @MrZammler , then why does the nightly, which is newer than 1.38.1, still have 1.38.0? Shouldn't it be v1.38.1-XXX-nightly?

Because we use release branches for handling of patch releases. There is no `v1.38.1` tag on the master branch, and nightlies are always built from the master branch, so they never see patch number bumps.

**Comment by etec-masterofsynapse** [comment]
> > Hi @MrZammler , then why does the nightly, which is newer than 1.38.1, still have 1.38.0? Shouldn't it be v1.38.1-XXX-nightly?
> 
> Because we use release branches for handling of patch releases. There is no `v1.38.1` tag on the master branch, and nightlies are always built from the master branch, so they never see patch number bumps.

I see. Does your SCM / CICD have the capability of building a stable / nightly branch tree so we could see on a website which commit level each branch is currently at?

**Comment by Ferroin** [comment]
> > > Hi @MrZammler , then why does the nightly, which is newer than 1.38.1, still have 1.38.0? Shouldn't it be v1.38.1-XXX-nightly?
> > 
> > 
> > Because we use release branches for handling of patch releases. There is no `v1.38.1` tag on the master branch, and nightlies are always built from the master branch, so they never see patch number bumps.
> 
> I see. Does your SCM / CICD have the capability of building a stable / nightly branch tree so we could see on a website which commit level each branch is currently at?

Not exactly at the moment, and it doesn’t even make sense in many cases to consider it this way. Patch releases (intentionally) do not contain all the commits from the master branch, only those that are deemed to be significant enough to qualify (as a general rule, this means fixes for security problems, regulatory compliance, crashes, data corruption, or serious usability issues). However, part of how we prepare commits for a patch release includes preserving the commit messages whenever possible, so if you’re looking to see whether a patch release includes a specific fix, you can almost always compare commit messages (for example, using `git log --oneline` in a local copy of the git repo).

That said, if all you care about is what stable patch release a given nightly is ‘equivalent’ to, the release date is a reasonably reliable indicator. In almost all cases, a given nightly build will include all the fixes present in any patch releases that occurred prior to that nightly build being released. There are only two exceptions to this that our release policy allows for, either fixes for things that do not affect the master branch (for example, if one of the fixes introduces a bug in the patch release because of someone making a mistake when backporting it), or fixes that have to be reverted in the master branch after they were already included in a patch release (which should in theory never happen, but if it does we’ll almost certainly have a new patch release out within 72 hours including the same revert).

**Comment by Ferroin** [comment]
> My idea about having the branch tree was more a quick thought to have the visibility to actually check that the nightly contains a specific fix, if I wouldn't trust the relationship between release date and commit date.

Excellent point. Unfortunately I don’t think there’s any easy way for us to implement this on our end though.
 
> That being said, is this information you just gave me readily available in the docs and I missed it? In my opinion it would be good to be able to look this up since others could be thrown off also by the nightly numbering scheme.

It’s not currently in our documentation anywhere, but yes, we do need to document it properly.

> Also, would it make sense to change the nightly numbering scheme? Instead of including the .0 in v1.38.0, just use v1.38-XXX-nightly and for stable, stay with the major.minor.patch numbering.

Nice idea, that actually should go a long ways towards mitigating this confusion. Any chance you could open a feature request with that suggestion?

**Comment by etec-masterofsynapse** [comment]
> > Also, would it make sense to change the nightly numbering scheme? Instead of including the .0 in v1.38.0, just use v1.38-XXX-nightly and for stable, stay with the major.minor.patch numbering.
> 
> Nice idea, that actually should go a long ways towards mitigating this confusion. Any chance you could open a feature request with that suggestion?

Of course, here you go: #14855
