### ISSUE TITLE
 vnodes.conf is getting overwritten

### ISSUE THREAD

**Issue by opalomogt** [netdata/netdata#14983]
### Bug description

After adding windows hosts in  /usr/lib/netdata/conf.d/vnodes/vnodes.conf  and creating the corresponding configuration in /etc/netdata/go.d/windows.conf  I am able to see the windows machines as nodes in Netdata Cloud.

But every single day, the /usr/lib/netdata/conf.d/vnodes/vnodes.conf gets overwritten to the original (empty) configuration.

I am guessing it could be a problem with the daily cron running "/etc/cron.daily/netdata-updater"

I am using the Nightly version because the stable one does not have the vnodes option.

### Expected behavior

vnode configuration should not be overwritten

### Steps to reproduce

1. Modify file "/etc/cron.daily/netdata-updater"
2. Wait 24 hours
3. Check the file again
...

### Installation method

kickstart.sh

### System info

```shell
/etc/centos-release:Rocky Linux release 8.7 (Green Obsidian)
/etc/os-release:NAME="Rocky Linux"
/etc/os-release:VERSION="8.7 (Green Obsidian)"
/etc/os-release:ID="rocky"
/etc/os-release:ID_LIKE="rhel centos fedora"
/etc/os-release:VERSION_ID="8.7"
/etc/os-release:PLATFORM_ID="platform:el8"
/etc/os-release:PRETTY_NAME="Rocky Linux 8.7 (Green Obsidian)"
/etc/os-release:ANSI_COLOR="0;32"
/etc/os-release:LOGO="fedora-logo-icon"
/etc/os-release:CPE_NAME="cpe:/o:rocky:rocky:8:GA"
/etc/os-release:ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
/etc/os-release:ROCKY_SUPPORT_PRODUCT_VERSION="8.7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="Rocky Linux"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="8.7"
/etc/redhat-release:Rocky Linux release 8.7 (Green Obsidian)
/etc/rocky-release:Rocky Linux release 8.7 (Green Obsidian)
/etc/system-release:Rocky Linux release 8.7 (Green Obsidian)
```

### Netdata build info

```shell
Configure options:  '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--datadir=/usr/share' '--includedir=/usr/include' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--disable-dependency-tracking' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' 'LDFLAGS=-Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld' 'CXXFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' 'PKG_CONFIG_PATH=:/usr/lib/pkgconfig:/usr/share/pkgconfig'
Install type: binpkg-rpm
    Binary architecture: x86_64
    Packaging distro:  
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         NO
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

**Comment by thiagoftsm** [comment]
I updated labels and title of this issue, because you were describing an expected behavior.

**Comment by gdoermann** [comment]
[[Bug]: After updating netdata, prometheus mysql_exporter metrics not collected](https://github.com/netdata/netdata/issues/15207) is a duplicate of this issue.  This is really a bug. 

@thiagoftsm how is overwriting the vnodes.conf file expected behavior? Every night when I get an update all my vnodes go stale.  This is a bug and should be fixed.  I agree with some of the other threads that the vnodes.conf file should be moved into the standard config directory.  We should have the stock config and an overridden config. This is causing grief for many people and I've had to come up with workarounds (scripts on a cron) to put the vhosts.conf back in place ever day and restart if it gets reset.

**Comment by thiagoftsm** [comment]
Hello @gdoermann ,

It is not a bug we rewrite examples inside `/usr/lib/netdata/conf.d/vnodes/vnodes.conf`, we would have a bug whether we rewrite the file inside `/etc/netdata/vnodes/vnodes.conf`. Everything  inside can be `/usr/lib/netdata/conf.d/` rewritten for different reasons like:

- Plugin update
- Module moved from one plugin to another
- Plugin is obsolete.

This is the motive I recommended you to use `edit-config`, because we do not expect to rewrite nothing inside `/etc/netdata`.

Any doubt, please, let us know!
