### ISSUE TITLE
[Feat]: Reduce eBPF deliverable

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#15016]
### Problem

Right now `netdata` is delivering around 30Mb of data in binary format for `ebpf.plugin`, we need to reduce this.

### Description

 We selected the option to deliver all eBPF programs, because this simplified transition between kernel versions, but now that we have different eBPF programs and some of them are compiled for specific distributions, it makes sense we deliver software according kernel running. 

On the other hand, we should not remove completely the option of transition between kernels, so we will deliver an option for users (reviewers) to install everything and test behaviors across different kernel versions.

### Importance

nice to have

### Value proposition

1. Save disk space
2. Reduce RPM and DEB packages.

### Proposed implementation

We will have the following steps:

1. We need to start working on https://github.com/netdata/kernel-collector `repo` splitting binaries instead to delivery one unique `tar.gz`. We can also continue delivering only one, but we have to modify our installation script to discard some binaries (ping @netdata/agent-sre ) (https://github.com/netdata/kernel-collector/pull/332)
2. Add `CO-RE` codes for remaining threads.
3. We have to modify `netdata/netdata` according road we selected. 

It is not necessary to modify eBPF CO-RE repo.

**Comment by ilyam8** [comment]
@thiagoftsm do we still need this issue?

**Comment by thiagoftsm** [comment]
@Ferroin ,

The majority of the distributions are using eBPF CO-RE already. This issue has more relationship with distributions that are still running kernels older than `5.8` that we are supporting. Do you think it's worth investing time into addressing this?

Best regards!

**Comment by Ferroin** [comment]
The only platforms we currently support that run older kernels are:

- RHEL 7/CentOS 7 (end of life at the end of June).
- Debian 10 (also end of life at the end of June).
- Ubuntu 20.04 (end of life at the star of April of next year).
- Amazon Linux 2 (end of life at the end of June of next year).

I think having an option in the build and installer to disable installing the legacy programs would be a good idea, but I would also suggest that:

1. We should consider ending development of new features for the legacy code. This is the bigger advantage I personally see to deprecating this stuff, because it means you will have more time to focus on making the forward-portable CO-RE based stuff better.
2. We should also seriously consider just dropping all support for this long-term. We probably need to keep it in the static builds for a while at least, but in 3-4 years it will likely make little to no sense to still be shipping this stuff anywhere, let alone supporting it.

**Comment by thiagoftsm** [comment]
@Ferroin, I don't have any objections to your suggestions.

As soon as I finish the 'WOLFSSL' tasks, I'll work on closing this issue

**Comment by thiagoftsm** [comment]
The first PR (https://github.com/netdata/kernel-collector/pull/383) to close this issue was merged.

**Comment by ilyam8** [comment]
@thiagoftsm that PR was merged 4 months ago, is there anything pending regarding this issue?

**Comment by thiagoftsm** [comment]
I am closing this, thank you to remember!
