### ISSUE TITLE
[Bug]: Temperature charts don't plot max temp achieved per time unit

### ISSUE THREAD

**Issue by NiGhTTraX** [netdata/netdata#15264]
### Bug description

The temperature sensor charts seem to "hide" spikes, requiring me to zoom in to find them. Because of this it's easy to miss periods where the CPU thermally throttled. See the reproduction video for more details.

### Expected behavior

I would expect the temperature charts to plot the MAXIMUM value achieved during the aggregated time unit.

### Steps to reproduce

https://github.com/netdata/netdata/assets/485061/a883aac8-3d56-4232-b6d5-c57293c45b3b

### Installation method

docker

### System info

```shell
Linux 5.15.0-75-generic #82-Ubuntu SMP Tue Jun 6 23:10:23 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=22.04
/etc/lsb-release:DISTRIB_CODENAME=jammy
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
/etc/os-release:PRETTY_NAME="Ubuntu 22.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="22.04"
/etc/os-release:VERSION="22.04.1 LTS (Jammy Jellyfish)"
/etc/os-release:VERSION_CODENAME=jammy
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=jammy
```

### Netdata build info

```shell
Version: netdata v1.40.0-38-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--without-bundled-protobuf' '--disable-dependency-tracking' '--disable-ebpf' 'CFLAGS=-O2 -pipe' 'LDFLAGS='
Install type: oci
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
    HTTPD (h2o):                YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    debugfs:                 YES
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

### Additional info

I am running netdata in Docker without Netdata Cloud and without any config changes e.g. custom dashboards.

I filed this as a bug report, and not a feature request, because I think the current behavior for the temperature charts is misleading.

**Comment by andrewm4894** [comment]
Thanks for the issue. 

I think this is expected behaviour even though i agree it's a bit subjective. If different charts started doing different aggregations out of the box it would get confusing overall. And while one person might want max by default for temperature others might really really not want that so I think it's more about doing the least unexpected thing in some sense.

Would be nice I think if there was some config option here so that we could have the best of both worlds maybe such that you could just change your own default as easy as possible.

There is the option to use different aggregations on the fly via the Netdata Cloud UI and that should be coming very soon to the agent dashboard.

So then I think ability to maybe save or configure your own default aggregations per chart could actually be a nice feature request.

@sashwathn do you know if users might easily be able to configure their own custom aggregations per chart in the new context.js or would that need to be something new we'd need to build on top in some way.

**Comment by ilyam8** [comment]
> There is the option to use different aggregations on the fly via the Netdata Cloud UI and that should be coming very soon to the agent dashboard.

@andrewm4894 is correct. The current agent dashboard does not support grouping options other than "average". This dashboard won't get any updated and will be deprecated soon.

> I would expect the temperature charts to plot the MAXIMUM value achieved during the aggregated time unit.

Max is the default for temperature charts on Cloud UI (which will replace the agent dashboard soon).

**Comment by NiGhTTraX** [comment]
> Max is the default for temperature charts on Cloud UI (which will replace the agent dashboard soon).

Will we still have the option of running everything locally without connecting to Netdata Cloud?

**Comment by ilyam8** [comment]
Yes
