### ISSUE TITLE
[Feat]: Packages compilation settings

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#15338]
### Problem

1. We want netdata to be the fastest possible for production use
2. We want netdata to have the smallest footprint as possible for production use

### Description

Smallest size:

```
LDFLAGS="-Wl,--gc-sections"
CFLAGS="-ffunction-sections -fdata-sections"
```

Based on our tests, netdata itself can benefit a 10-20% reduction of stripped binary size. But the biggest benefit is on smaller binaries, which can become several times smaller compared to the default options.

Best Performance:

```
CFLAGS="-O2 -funroll-loops" kickstart.sh --enable-lto
```

Based on our tests, the above can have a 2x performance boost to the rate they can ingest metrics, on busy parents.

### Importance

nice to have

### Value proposition

1. Smallest binary sizes
2. Fastest performance

### Proposed implementation

As above.

**Comment by ktsaou** [comment]
> However, the fact that we see any significant size reduction from these options indicates that we have a nontrivial amount of dead-code, and we ideally need to follow up on this by finding and getting rid of that dead code as much as possible.

Your conclusion is not accurate. We do not have any dead code in our code base. The reduction in size arises from how the compiled code is organized into sections. In the default settings, if a function from a section is required, the entire section is included in the final binary. The settings I've proposed allow the compiler to create a separate section for each function. This way, the linker can selectively include only those functions that are actually used by each binary.

The impact is relatively minor for the Netdata agent, since the "dead code" primarily consists of functions from static libraries we link against, such as protobuf, dblib, etc. However, the impact is significantly larger for our smaller binaries, as the "dead code" includes substantial portions of libnetdata that these smaller binaries do not use.

## About LTO

Inlining functions is generally critical for code optimization. We already manually inline functions within each C source file. But when it comes to different files, we have two options:

Define the functions in .h files as static inline. This approach leads to the function being included in every .o file it's used in, which significantly increases compilation time as it's compiled repeatedly for each .c file.
Utilize LTO to allow the compiler to figure it out without having to alter the code as in the first option.
Overall, I believe enabling LTO is beneficial.

## About -funroll-loops

@vkalintiris is currently running tests and, according to his preliminary observations, enabling this option can potentially double the speed of busy parents.

I acknowledge the complexity associated with varying architectures. Please coordinate with him to address this issue.

**Comment by vkalintiris** [comment]
> Does it still provide a performance benefit for normal usage outside of that use case?

Yes.

>  Have we tested it in isolation from LTO (IOW, if a user disables LTO, will using this option still provide a significant performance benefit?)?

Yes and no. We need both LTO + loop unrolling, otherwise the loop unrolling optimization alone provides only a small speedup.

> There are, IMO, too many loose ends here to say we should enable it globally.

Considering the measurements I got, I think enabling it globally is the way to go. Unless, anyone is able to provide any counter-examples. 

> especially right before a release, even aside from the CPU µarch aspect.

At the very least, we should have these opts enabled on nightlies for a couple days. The only risk I see is the possibility that these optimizations might exploit any unintended undefined behaviour we might have in our codebase. Having said that, this would be a bug that we already have in _our codebase_ (and should fix either way), and not an issue with the optimizations themselves.

**Comment by Ferroin** [comment]
> > Does it still provide a performance benefit for normal usage outside of that use case?
> 
> Yes.
> 
> > Have we tested it in isolation from LTO (IOW, if a user disables LTO, will using this option still provide a significant performance benefit?)?
> 
> Yes and no. We need both LTO + loop unrolling, otherwise the loop unrolling optimization alone provides only a small speedup.

And that then begs the question: Does the combination produce a significantly higher performance benefit than just using LTO does?

> > There are, IMO, too many loose ends here to say we should enable it globally.
> 
> Considering the measurements I got, I think enabling it globally is the way to go. Unless, anyone is able to provide any counter-examples.

OK, a bit of perspective here: I’ve actually experimented with this flag quite a bit, not with Netdata specifically, but with a _lot_ of other software, because it’s one of the few truly safe optimizations that isn’t part of `-O2` or `-O3`. I’ve seen far too many cases of applications built with `-funroll-loops` showing _significant_ differences in performance  across different systems that did not exist without the option to blindly trust that the limited amount of testing I’ve actually heard of us doing indicates that it won’t make things any worse than they are now for at least some percentage of users.

> > especially right before a release, even aside from the CPU µarch aspect.
> 
> At the very least, we should have these opts enabled on nightlies for a couple days. The only risk I see is the possibility that these optimizations might exploit any unintended undefined behaviour we might have in our codebase. Having said that, this would be a bug that we already have in _our codebase_ (and should fix either way), and not an issue with the optimizations themselves.
> 
> Edit: LTO + other kind of optimizations are things that we should investigate more closely in the future (eg. PGO + BOLT). Netdata's the kind of program that's very amenable to these kind of optimizations and they can potentially give us quick, easy (and significant) wins.

Agreed on PGO and BOLT, but for those to be workable we need to be building _natively_ for non-x86 platforms, which is currently not practical.

Other possibilities that come to mind include using OpenMP in some places, and possibly leveraging Graphite (the GCC thing, not the text-layout library).

At some point I would also like to do a performance comparison between GCC+LTO, Clang+LTO, and Clang+ThinLTO. I strongly suspect (based on prior experience elsewhere) that Clang with ThinLTO will build almost as fast as our current non-LTO builds but still get us a vast majority of the performance benefits of using LTO with GCC, which would be a significant benefit for us since a lot of our release process is _heavily_ constrained by compile times.

**Comment by Ferroin** [comment]
> > And that then begs the question: Does the combination produce a significantly higher performance benefit than just using LTO does?
> 
>     * -O2 -> 4.2M points/sec.
> 
>     * -funroll-loops -> 5.5M points/sec.
> 
>     * -funroll-loops + LTO -> 8.6M points/sec.

I get that the specific test cases being used showed a significant improvement when using it _with_ `-funroll-loops` (at least, on that speciific system), my question was about whether we have data for LTO _without_ `-funroll-loops`. I suspect that LTO accounts for a far larger percentage of the benefits of the combined case than `-funroll-loops` does.

And, for that matter, have we tried with `-O3` at all? If we’re seeing this much improvement from `-funroll-loops` and `-flto`, then I would also expect `-O3` to show a nontrivial performance improvement as well.

**Comment by zamazan4ik** [comment]
@Ferroin @vkalintiris Do we need to create a dedicated issue regarding PGO and BOLT? I understand that right now seems like that issue will not be resolved (due to some limitations on non-x86-64 platforms). At least we can try to provide PGOed versions for x86 and non-PGO for others. Also, if proper build options will be available in the build scripts, for the maintainers and users will be easier to recompile Netdata with their own profiles.

If you agree to create an issue for that (just to track) - I can do it.

Maybe you will be interested in my results regarding PGO for other applications - they are available [here](https://github.com/zamazan4ik/awesome-pgo).
