### ISSUE TITLE
[Bug]: 401 when behind a proxy with basic HTTP auth and signed-in

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#15789]
### Bug description

[Reported on Reddit](https://www.reddit.com/r/linux/comments/15n7nbr/comment/jvlck0u/?utm_source=reddit&utm_medium=web2x&context=3).

Get 401 with valid user/pass when Netdata:

- behind a proxy with basic HTTP and
- connected to Cloud

### Expected behavior

No 401

### Steps to reproduce

1. Netdata behind a proxy with basic HTTP auth.
2. Go to IP:19999, enter user/pass.
3. Sign in and connect to Netdata.

### Installation method

kickstart.sh

### System info

```shell
n/a
```

### Netdata build info

```shell
netdata v1.42.0-8-g060dfc80e
```

**Comment by andyundso** [comment]
We are having the same issue, but our nodes are not connected to the cloud. We also disabled the cloud integration using the respective parameter in `/var/lib/netdata/cloud.d/cloud.conf`.

**Comment by andyundso** [comment]
I'm wondering if I'm doing something wrong.

In `/var/lib/netdata/cloud.d/cloud.conf`, I have the following:

```
[global]
    enabled = no
```

I also updated my nodes from v1.41.0 to v1.42.0, still the same issue as described on the Reddit post.

> Chrome pops up the basic authentication prompt dozens of times

The old dashboard at `/v1` works fine, it's just an issue with the new version at `/v2`.

We run a Caddy reverse proxy instead of Nginx. Happy to provide more details, for example an `access.log`.

**Comment by ilyam8** [comment]
I use NGINX as a proxy. A detailed step-by-step guide on how to make the same setup to reproduce the problem would be helpful. I have no experience with caddy.

**Comment by ilyam8** [comment]
>  Is it possible that our nodes are marked as "cloud enabled" because it was not deactivated on the initial setup?

Yes, it is enabled if not explicitly disabled/compiled w/o Cloud support.
