### ISSUE TITLE
[Feat]: Monitoring and alerting on disk drive helium levels

### ISSUE THREAD

**Issue by Hr46ph** [netdata/netdata#15904]
### Description

On helium filled disk drives I believe it is crucial to monitor helium level as the likelihood a drive will fail increases as helium levels drop.

```
 22 Helium_Level            0x0023   100   100   025    Pre-fail  Always       -       100
```
I initially asked if this was possible to create alerts on Discord:
https://discord.com/channels/847502280503590932/1145446874858401953

### Importance

really want

### Value proposition

1. Risk of disk failure increases with low helium levels (I think below 20% is considered critical).
2. Opportunity to preemptively replace a disk when alerted in time

**Comment by ilyam8** [comment]
[go.d/smartctl](https://learn.netdata.cloud/docs/collecting-metrics/hardware-devices-and-sensors/s.m.a.r.t.) allows for monitoring of helium levels on compatible drives (it collects all smart attributes unlike (deprecated) python.d/smartd_log that had hardcoded list of attributes). However, due to the lack of test environments with drives containing this metric, I'm hesitant to implement an alert for it at this time. @Hr46ph if you want to do it yourself - feel free top open a pull request.
