### ISSUE TITLE
[Bug]: netdata package has unmet dependencies

### ISSUE THREAD

**Issue by btravouillon** [netdata/netdata#16003]
### Bug description

Trying to install a previous release of Netdata on Debian fails with:
```
$ sudo apt-get install netdata=1.42.3
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 netdata : Depends: netdata-plugin-ebpf (= 1.42.3) but it is not going to be installed
           Depends: netdata-plugin-apps (= 1.42.3) but it is not going to be installed
           Depends: netdata-plugin-pythond (= 1.42.3) but it is not going to be installed
           Depends: netdata-plugin-go (= 1.42.3) but it is not going to be installed
           Depends: netdata-plugin-debugfs (= 1.42.3) but it is not going to be installed
           Depends: netdata-plugin-nfacct (= 1.42.3) but it is not going to be installed
           Depends: netdata-plugin-chartsd (= 1.42.3) but it is not going to be installed
           Depends: netdata-plugin-slabinfo (= 1.42.3) but it is not going to be installed
           Depends: netdata-plugin-perf (= 1.42.3) but it is not going to be installed
           Recommends: netdata-plugin-systemd-journal (= 1.42.3) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

### Expected behavior

The system should be able to install netdata 1.42.3 and the compatible plugins.

### Steps to reproduce

1. Add netdata repos
2. `apt-get install netdata=1.42.3`

### Installation method

manual setup of official DEB/RPM packages

### System info

```shell
Linux paperoni 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=debian
```

### Netdata build info

```shell
$ netdata -W buildinfo
-bash: netdata: command not found
```

### Additional info

Trying to install netdata 1.42.3 which should include the fix for #15843.

**Comment by Ferroin** [comment]
We have strict versioning requirements for our plugin packages, they have to exactly match the core Netdata version to ensure that nothing breaks because of some internal API change. This means that installing an old version of Netdata must also pull in old versions of the plugins.

However, APT tends to not be happy with installing versions of packages that do not appear to be the latest unless you explicitly tell it to do so for every individual package you want installed. As far as I can tell, there is no way to work around this just using APT short of manually listing all of the problematic dependencies for the install.

That said, Aptitude (not installed by default on Debian, but easily installable with `apt install aptitude`) _does_ have decent support for this, it will interactively prompt you with ‘solutions’ to make things work (usually in ascending order based on total number of changes, so the first solution it proposes will not be what you want in this case), and does allow this type of install.

**Comment by ilyam8** [comment]
Closing because there are no plans to "fix" this issue, and using `aptitude` solves the problem.

**Comment by loood** [comment]
> One solution is to configure apt pinning for netdata :
> 
> ```
> # File /etc/apt/preferences.d/netdata
> Package: netdata*
> Pin: version 1.42.3
> Pin-Priority: 1000
> ```

Ran into this issue today with 1.44.1 being released. Updated my puppet code to pin the version for all the netdata packages. Thanks!!
