### ISSUE TITLE
CMake: Remaining issues

### ISSUE THREAD

**Issue by vkalintiris** [netdata/netdata#16573]
Remaining issues of the [CMake PR](https://github.com/netdata/netdata/pull/15996).

- [x] (@vkalintiris) v1 vs v2 default dashboard.
- [x] (@vkalintiris) Wrong home dir of netdata user:
    `/opt/netdata` vs `/opt/netdata/var/lib/netdata`)
- [x] (@vkalintiris) Missing swagger files and ilove.html
- [x] [WONTFIX, optional and not used by v2] (@vkalintiris) ~~Distributing dashboard's `version.txt`~~
- [x] (@Ferroin) `netdata-installer.sh` tries to lookup files from source dir instead of build dir:
    ```
    ( --- Installing (but not enabling) the netdata updater tool ---
    cat: /home/ilyam/src/nd_vkalintiris/system/systemd/netdata-updater.service: No such file or 
    directory
    ```
- [x] the [else branch of install_netdata_service()](https://github.com/netdata/netdata/blob/c558c157076dda91fc87dcf96ead1320b3eb5a67/packaging/installer/functions.sh#L567) is broken because there we expect to find files in `system\...`. I am not sure that is not dead code. Does install-service.sh always exist? @netdata/agent-sre

**Comment by vkalintiris** [comment]
@Ferroin @ilyam8 I'll be tracking remaining issues of the CMake PR here. If you think something is missing from the list let me know. Once the tasks of the list are done, I'll check with you to get a final confirmation and we will merge the PR.

**Comment by vkalintiris** [comment]
> Wrong home dir of netdata user:
> /opt/netdata vs /opt/netdata/var/lib/netdata)

@ilyam How can I check this? Is this about the information printed from `-W buildinfo` under `Default Directories -> Home`, or is it something else?

**Comment by ilyam8** [comment]
I think the [else branch of install_netdata_service()](https://github.com/netdata/netdata/blob/c558c157076dda91fc87dcf96ead1320b3eb5a67/packaging/installer/functions.sh#L567) is broken because there we expect to find files in `system\...`. I am not sure that is not dead code. Does install-service.sh always exist? @netdata/agent-sre

**Comment by ilyam8** [comment]
@Ferroin the issue is this line

https://github.com/netdata/netdata/blob/c558c157076dda91fc87dcf96ead1320b3eb5a67/packaging/installer/functions.sh#L1066

I believe at this point we have `netdata-updater.service` in two places:

- `${NETDATA_BUILD_DIR}/system/systemd/netdata-updater.service`
- `${NETDATA_PREFIX}/usr/lib/netdata/system/systemd/netdata-updater.service`

Which file is better to use?
