### ISSUE TITLE
[Feat]: Build and install go.d.plugin as part of the normal build process

### ISSUE THREAD

**Issue by svenstaro** [netdata/netdata#16729]
### Problem

I'm the maintainer of netdata in Arch Linux. I received a [request for shipping go.d.plugin](https://gitlab.archlinux.org/archlinux/packaging/packages/netdata/-/issues/1). However, there exist no docs on how to build it and how to ship it and for some reason the official build system doesn't handle it either. The go.d.plugin doesn't even exist in the official release sources as far as I can see.

### Description

I'd like for the official build system to take care of installing the go plugin. I'd also like for the go plugin to be contained in the release sources. It currently appears to be in a [separate repo](https://github.com/netdata/go.d.plugin) that I need to get the sources from separately but this isn't documented nor is this clear. I can only infer that.

### Importance

nice to have

### Value proposition

People on Arch Linux get the go.d.plugin.

**Comment by ilyam8** [comment]
@svenstaro hey. go.d.plugin will remain in the separate repo.

**Comment by svenstaro** [comment]
Ok but still I think my request is reasonable. I don't want the repos to be merged, I want the source releases to be complete and for the build system to take care of installing everything.

**Comment by ilyam8** [comment]
> received a request 

Just noticed who is the requester, hey @k0ste 👋

**Comment by k0ste** [comment]
> > received a request
> 
> Just noticed who is the requester, hey @k0ste 👋

I made MR for Archlinux [!1](https://gitlab.archlinux.org/archlinux/packaging/packages/netdata/-/merge_requests/1) as @svenstaro requested

**Comment by hexchain** [comment]
Hi @svenstaro, thanks for maintaining netdata for Arch!

> I want the source releases to be complete and for the build system to take care of installing everything.

Is it really a good idea to bundle them together, though? I'm under the impression that the `go.d.plugin` is more or less a separate project, with different release cycles, and isn't strictly tied to netdata. Maybe you could just absorb `aur/netdata-go-plugins` into `[extra]` and make it an optional dependency? Of course, the package name could be better, e.g. `netdata-go.d.plugin` to better match the upstream project.

**Comment by svenstaro** [comment]
Depends on how upstream wants this to be packaged. It is my understanding that the official rpm packages have go.d.plugin in the same package.

**Comment by ilyam8** [comment]
All external plugins are separate packages (both rpm and dev).

**Comment by k0ste** [comment]
> All external plugins are separate packages (both rpm and deb).

This just a way for a packaging. Arch does not pack `{devel,debuginfo,plugin}` into a separate packages. Only way for this is a `-libs` package or a `-gui` (when cli and gui may be used separately)

And in fact, when we do the installation of the main package (`dnf install netdata`), the plugins are installed as a dependency automatically

To be clear - `netdata` currently can't even make a `icmp` ping without a `go.d.plugin`. Simply put, it makes no sense to keep `netdata` in an Arch upstream package in this form (without a `go.d.plugin`), it’s easier to give it to a user repository, where users themselves can determine how to maintain the package - this is usually solved with the help of democracy and investment of time

But it seems that the topic of this problem was about the delivery of the source code, and not how to do the packaging 🤔

**Comment by hexchain** [comment]
Arch does not split packages most of the time. In this case, it's not about splitting, it's about combining two different upstream projects into one package, and is IMHO questionable (and also should be discussed in the Arch issue tracker). As I've said, it is probably preferable to package the Go plugins separately and make that an optional dependency.

**Comment by k0ste** [comment]
> Arch does not split packages most of the time. In this case, it's not about splitting, it's about combining two different upstream projects into one package, and is IMHO questionable (and also should be discussed in the Arch issue tracker). As I've said, it is probably preferable to package the Go plugins separately and make that an optional dependency.

For me, this is a substitution of concepts. This is one project, not two, just the development of which is carried out in different repositories. This is the same if Gitlab packs PostgresSQL support in different optional packages, although the project is impossible to real work without a database

Can you use the go.d.plugin separately from netdata? No
Can you use netdata (the core) without any plugin, but most likely you won’t, because the tool does not solve the problem for which it was created - monitoring the system and everything possible, with minimal configuration

Also, netdata does not declare anywhere that the go.d.plugin version can be changed relative to the netdata version. Obviously this is only possible to a limited extent for minor versions. But there is no backward compatibility provided because this is one project

**Comment by Ferroin** [comment]
As a bit of background, the reason we have separate DEB/RPM packages for each external plugin (that is, those which run as a separate process from the main Netdata daemon) is that there are legitimate use cases that do not require specific plugins, and we have had users complain in the past about our dependency tree being too big (and most of the ‘big’ dependencies were either optional things, or stuff pulled in by external plugins). However, we don’t actually use the Go plugin version for the package version, we use the associated Netdata version, largely because that makes dependency handling _much_ simpler (instead of needing to compute the dependencies on the fly every release, this lets them just be a static constraint that the versions match), and we don’t really officially support using anything but the associated version of the Go plugin with any given Netdata release (effectively, we only support use of the version listed in `packaging/go.d.version` in the release tarball). And, on top of that, all the plugins have a hard dependency on the core agent (so you can’t install the Go plugin without the core agent unless you jump through flaming hoops to get the package manager to ignore dependencies).

I agree that it’s relatively unlikely that any given user will want to run without the Go plugin, but such use cases do exist (think small embedded systems that just need stuff covered by the main daemon, or which only want a handful of custom plugins), and it’s easier on our end from a policy perspective to not treat the Go plugin specially compared to the others.

As far as packaging on Arch, I think this comes down to what the Arch maintainers want to support though. If they don’t care about those admittedly atypical use cases, then having a single package is perfectly fine and should actually provide a better user experience. If they do, then it should indeed be a separate package, but I would argue for using the main Netdata agent version for the package itself and having a hard dependency on the main Netdata package, just like we do with our split Go plugin DEB/RPM package, for the same reasons that we do things that way.

**Comment by k0ste** [comment]
`go.d.plugin` Arch support merged in [1.44.1-3](https://gitlab.archlinux.org/archlinux/packaging/packages/netdata/-/commit/7cc6ef1b8d0eb0ddd378286885e49487a547917d)
