### ISSUE TITLE
[Feat]: go.d elasticsearch exclude node ID from metric export

### ISSUE THREAD

**Issue by nikobearrr** [netdata/netdata#16832]
### Problem

I used netdata v1.40.1 and after upgrading to 1.42.3 my metrics have changed.
They used to be named `elasticsearch_<jobname>.xxx` and now they are named `elasticsearch_<jobname>.node_YYYYYYYYY_cluster_ZZZZ_xxx`. My metrics do not match and I cannot keep the historical (exported to graphite). Also, I am not interest in the node ID itself.

### Description

I need an option to remove the `node_YYYYYYYYY_` from the metrics/series as well as `cluster_ZZZZ`

### Importance

really want

### Value proposition

1. People having metrics will manage to retain them without creating new metrics

### Proposed implementation

have an extra option in the job config:
1. `include_node_id_in_series: yes/no`
2. `include_cluster_name_in_series: yes/no`

**Comment by ilyam8** [comment]
@nikobearrr, we added [support for cluster mode](https://github.com/netdata/netdata/issues/15263) - I didn't know that nodes stats API can return multiple nodes. It was fixed in netdata/go.d.plugin#1227. Charts id must be globally unique, that is why `node_YYYYYYYYY_cluster_ZZZZ` is a part of id now. You are right, that the change means new charts => no history, but there is no way back. Thanks for your request, but I don't plan to add that option.
