### ISSUE TITLE
Tag nightlies

### ISSUE THREAD

**Issue by vkalintiris** [netdata/netdata#16884]
#### Summary

Add git tags for nightly releases.

**Comment by ilyam8** [comment]
@Ferroin has this been fixed/implemented? If not, do we still need it?

**Comment by Ferroin** [comment]
It’s been discussed multiple times before and has repeatedly been decided to _not_ do it because it interferes with version generation, adds a lot of extra data to the repository, and objectively has little to no benefit to users since we don’t want them installing by hand anyway.

Given that repeated discussion, I’m going to just close this as not planned.
