### ISSUE TITLE
[Bug]: Postgres metrics stopped working in latest update

### ISSUE THREAD

**Issue by cacraig** [netdata/netdata#17302]
### Bug description

Postgres metrics stopped working in latest update. 

### Expected behavior

It should work.

### Steps to reproduce

1.

### Screenshots

When postgres does appear as an option - there are no metrics.
<img width="1297" alt="Screenshot 2024-03-27 at 3 25 40 PM" src="https://github.com/netdata/netdata-cloud/assets/3621157/bb7fa46d-c465-4e8e-94f0-6526551e5f8f">

Postgres also disappeared as a chart option on some of our servers with postgres running.
<img width="267" alt="Screenshot 2024-03-27 at 3 30 09 PM" src="https://github.com/netdata/netdata-cloud/assets/3621157/634802cc-a1ad-4f06-be23-28f552a2b1bf">

### Desktop

OS: Ubuntu 22.04

**Comment by hugovalente-pm** [comment]
@cacraig moving this to `netdata/netdata` repo since this seems an Agent issue and asking some further details to help the team troubleshoot this:
* Installation method
   ![image](https://github.com/netdata/netdata/assets/82235632/1f9ff0f3-72c3-4fa1-9b9a-3bd2390fe427)
* System info _Provide information about your system. To get this information, execute one of the following commands based on your OS:_
```
# Linux
uname -a; grep -HvE "^#|URL" /etc/*release
# BSD
uname -a; uname -K
# macOS
uname -a; sw_vers
```
* Netdata build info _Provide Netdata Agent version and build info. To get this information, execute: _
```
netdata -W buildinfo
# If get "netdata: command not found", try (required running Netdata)
$(ps aux | grep -m1 -E -o "[a-zA-Z/]+netdata ") -W buildinfo
```

@ilyam8 in the meantime, is there something useful from the debug output that could hepl start the investigation?

**Comment by ilyam8** [comment]
> ERR postgres/postgres.go:127 error on pinging the Postgres database [postgresql://netdata@127.0.0.1:5432/postgres]: failed to connect to `host=127.0.0.1 user=netdata database=postgres`: failed SASL auth (FATAL: password authentication failed for user "netdata" (SQLSTATE 28P01)) collector=postgres job=local

@cacraig how did you configure auth? Did you use passwordless unix connection? Do you have

```
local   all             postgres                                trust
```

in `pg_hba.conf`?
