### ISSUE TITLE
[Bug]: Installation failed on OpenBSD 7.5 (arm64)

### ISSUE THREAD

**Issue by iredmail** [netdata/netdata#18614]
### Bug description

Failed to install on OpenBSD 7.5, arm64.
OpenBSD is a VMware Fusion guest on MacBook Pro with M3 Pro chip.

### Expected behavior

Expect installation succeeded without error.

### Steps to reproduce

- Download latest `netdata-aarch64-v1.47.2.gz.run`.
- Install it:

```
ob75# ./netdata-aarch64-v1.47.2.gz.run --accept

  ^
  |.-.   .-.   .-.   .-.   .  netdata
  |   '-'   '-'   '-'   '-'   real-time performance monitoring, done right!
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->

  (C) Copyright 2017-2023, Costa Tsaousis
  All rights reserved
  Released under GPL v3+

  You are about to install netdata to this system.
  netdata will be installed at:

                    /opt/netdata

  The following changes will be made to your system:

  # USERS / GROUPS
  User 'netdata' and group 'netdata' will be added, if not present.

  # LOGROTATE
  This file will be installed if logrotate is present.

   - /etc/logrotate.d/netdata

  # SYSTEM INIT
  If a supported init system is detected, appropriate configuration will be
  installed to allow Netdata to run as a system service. We currently support
  systemd, OpenRC, LSB init scripts, and traditional init.d setups, as well as
  having experimental support for runit.


  This package can also update a netdata installation that has been
  created with another version of it.

  Your netdata configuration will be retained.
  After installation, netdata will be (re-)started.

  netdata re-distributes a lot of open source software components.
  Check its full license at:
  https://github.com/netdata/netdata/blob/master/LICENSE
Creating directory /opt/netdata
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing netdata, the real-time performance and health monitoring system  100%  
./bin/bash[2]: syntax error: `)' unexpected
```

### Installation method

other

### System info

```shell
# uname -a
OpenBSD ob75.x.io 7.5 GENERIC#131 arm64
```

### Netdata build info

```shell
Installation failed, so no `netdata` command yet.
```

**Comment by Ferroin** [comment]
Our static install images are only built for Linux systems (this is very explicitly mentioned at the top of the static install documentation), and are only officially supported on actual Linux systems. They will _probably_ work in most simulated Linux environments (for example, running under the Linux compatibility layers provided by FreeBSD, VMWare’s ESXi, or VxWorks), but this is not guaranteed and and such installs are not officially supported (though depending on what issues are seen, we _may_ still fix issues found running in such a setup).

It’s a near certainty that we will never build static install images for any platform other than Linux, as the only reason we even provide them for Linux is because it trivializes support for exotic, or more commonly horribly outdated, Linux distributions that we don’t provide native packages for.

It’s unlikely we will ever officially support running on a non-Linux platform that provides Linux compatibility either (our official stance will always be that you should be running either natively or in a VM or container), though if we get sufficient demand from paying users we may start supporting such setups to a limited degree (and even then probably only with paid support).

---

Irrespective of any of that, Netdata does not support running on OpenBSD. We currently only support Linux, FreeBSD, and macOS (though our macOS support is severely lacking at the moment), and in the near future Windows.

Back in 2018-2019 there was an attempt by a community member (https://github.com/netdata/netdata/pull/4192) to port Netdata to run on OpenBSD, but that ultimately went unfinished and is horribly out of date at this point.

If a paying business/enterprise customer asks for it we will probably end up supporting OpenBSD, but as of right now there are currently no plans for such support.
