### ISSUE TITLE
Stacking of values in memory view

### ISSUE THREAD

**Issue by candlerb** [netdata/netdata#1982]
This is a very minor suggestion!

I note that in the memory view, the results are currently stacked as:

* free (top)
* used
* cached
* buffers (bottom)

![image](https://cloud.githubusercontent.com/assets/44789/24106332/739876bc-0d7f-11e7-9e5e-72ba6a2c6c7e.png)

However, "cached" can be considered another kind of "free", since non-dirty cached pages can be dropped as soon as more RAM is required, and dirty cached pages will be flushed to disk.

This means that the width of the 'buffers' stripe plus the width of the 'used' stripe is what's really of interest.

So I would like to propose swapping "used" and "cached", so it looks like this:

* free (top)
* cached
* used
* buffers (bottom)

Then visually it's very clear how much memory is really in use: just follow the top of the 'used' stripe.

**Comment by ktsaou** [comment]
Thanks!

I have a minor issue with this. netdata charts are automated. We don't configure each and every of them. There is a standard logic that applies to all.

This logic currently says that colors are in pairs: positive, negative, positive, negative, etc. Positive can be anything (green, blue, bright yellow, etc), but negative have more red in them (red, brown, dark purple, etc).
(yes, I know the white theme has blue as the first positive colorm instead of green - I checked green too, but I decided I prefer more blue in white background - btw, google charts prefer blue too).

So, if we move `cache` to the second position, it will become red, which is not good.

There are a few requests to allow sorting the legend ( like #1566 ) and I would like to have an alternative with the legend below the chart, like this:

![image](https://cloud.githubusercontent.com/assets/2662304/24109258/c307c860-0d98-11e7-91f1-aa9aceba0974.png)

So, I will leave this as an enhancement, to see what we can do when time comes to improve the legend.

**Comment by candlerb** [comment]
OK, thank you. I'll leave it to you to decide the best generic way to approach this.

> This logic currently says that colors are in pairs: positive, negative, positive, negative, etc

It occured to me that perhaps the data could be recorded as

~~~
[free, None, cached, None, None, used, None, buffers]
~~~

... but that would require some legends to be suppressed.

**Comment by ktsaou** [comment]
@gmosx 	check this.
The chart I posted above has different legend (below the chart).
This is also very important for a mobile view (not much width on the screen).

Other than that, this issue can be closed.
