### ISSUE TITLE
alarms to monitor the number of processes in a system

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#2239]
A quite common case is for a cron job to keep forking processes endlessly that do not end in time, so the number of processes grows forever.

It would be very nice to have an alarm for this case.

**Comment by ktsaou** [comment]
There is already a chart with this info:

![image](https://user-images.githubusercontent.com/2662304/48943562-4761ee80-ef2c-11e8-85ce-50abf996d0b7.png)


So, it is just a matter of defining a new alarm in netdata.

**Comment by Ferroin** [comment]
The problem is figuring out what to set the trigger point at.  Any arbitrary absolute value is likely to not work for everybody, and end up either annoying the crap out of people, or just never fire.  We really need to base this on the maximum number of processes that the system can have active.  On Linux, we can query `/proc/sys/kernel/pid_max` to get that value, but I'm not sure what's needed on other platforms.  Setting the thresholds at 80% and 95% for warning and critical respectively seems reasonable.   We might also consider something similar to the disk alarms, and have one that extrapolates when the process table will be full and sends an alarm at some threshold of time for that.

**Comment by Ferroin** [comment]
Relevant to #4313

**Comment by ktsaou** [comment]
@Ferroin 	this is nice!

Regarding the threshold, we can also compare the max number for the timeframe -10min to -60min with the average number of the timeframe 0 to -10min. If the later is +X% we can trigger the alarm. This should detect sudden changes in the number of processes.

**Comment by Ferroin** [comment]
I like that idea too,  though I can think of at least a couple of cases where it might produce false positives unless we put a lower bound on the number of new processes created.

**Comment by apardyl** [comment]
+1 for the feature, really useful for apps, that can spawn workers infinitely on error (e.g. Zulip chat).

Using an absolute value might not be that bad - both macosx and freebsd have hardcoded limit of `99999` (according to https://www.freebsd.org/cgi/man.cgi?query=intro&apropos=0&sektion=2&manpath=FreeBSD+12.0-RELEASE&arch=default&format=html and https://apple.stackexchange.com/questions/51119/whats-the-maximum-pid-for-mac-os-x) and both 64 and 32 bit Linux defaults to `32768` unless manually changed. Otherwise on Linux we would have to monitor both `/proc/sys/kernel/pid_max` and `/proc/sys/kernel/threads-max`, because with high `pid_max` the kernel might run out of thread structures before it reaches max pid number.

I am afraid that the approach based on comparing the average number of processes in different time frames can be false-positive prone in containerized environments, where the number of active processes can quickly jump from several dozen to several hundred or thousand on container start. It will also not detect slowly rising process number, e.g. some scheduled tasks not finishing and piling up.

One more thing to consider is how often the alarm should be updated so the notification is delivered *before* the process limit is reached so the alarm-notify script can be executed. Every two or five second seem reasonable unless someone launches a fork-bomb.

I can write a PR for this unless someone is working on it.

**Comment by ilyam8** [comment]
> I can write a PR for this unless someone is working on it.

please do!
