### ISSUE TITLE
bond master/slave interfaces not handled properly, triggering packet dropping errors

### ISSUE THREAD

**Issue by gdevenyi** [netdata/netdata#2285]
Details here:
https://bugs.launchpad.net/ubuntu/+source/bridge-utils/+bug/1041070

Netdata doesn't know the above, so it reports lots of packet loss.

**Comment by ktsaou** [comment]
hm... interesting... what netdata can do then? I think our only option is to disable this alarm....

**Comment by Ferroin** [comment]
In theory, there should be some way to check the interface type and whether or not the settings for it are configured in such a way that this would be an issue, although doing that may require root access (or CAP_NET_ADMIN), or at least talking to something like NetworkManager.

**Comment by Ferroin** [comment]
If the interface is a bonding interface, then the directory /sys/class/net/<ifname>/bonding/ will exist, and that should be visible to any user unless the system is using SELinux (or another MAC LSM) or GRSecurity.  Similarly, if an interfaces is a slave for a bonding interface, the directory will instead be /sys/class/net/<ifname>/bonding_slave/.

Unfortunately, beyond that, there's not much that can be verified because for any of the bonding modes, misconfigured networking hardware on the remote end will cause this, although mode 1 (active backup) requires some pretty bad misconfiguration or poor design to cause this, and mode 3 (802.3ad) should be safe since it won't work at all unless the remote end is configured properly.  I would think that netdata can assume if one of those modes is set or if /sys/class/net/<ifname>/bonding/all_slaves_active is 1, then it's safe to enable the alarm, otherwise it's not (that is, for bonding interfaces, this should be safe for non-bonded ones regardless).

**Comment by ktsaou** [comment]
ok nice.
Could you please give me a full example of files I should look for? Let's say `eth0` is a bonded interface, what should I expect to find under `/sys/class/net//bonding/` ?

**Comment by Ferroin** [comment]
The three that should matter for this are:
* `/sys/class/net/<ifname>/bonding/slaves`:  This contains a space separated list of the slave interfaces linked to this bonding interface.  This may be useful for checking where the errors are coming from.
* `/sys/class/net/<ifname>/bonding/mode`: This contains a single line consisting for the bonding mode name and the bonding mode number separated by a space.  As I mentioned above, for modes 1 and 3, you can probably safely enable the alert, and it _might_ be safe for mode 0 (I'm pretty sure the round-robin operation in mode 0 implies that all slaves are active).
* `/sys/class/net/<ifname>/bonding/all_slaves_active`:  Will contain either 0 or 1, showing whether or not all the bonding slaves are active (that is, whether or not duplicates coming in mon multiple slaves will be treated as errors).  If this is 1, you can almost certainly enable the alert, since it then shouldn't trigger unless you get actual errors.

If you want some more in-depth info, there's pretty good documentation of all the configuration parameters (which map directly to the sysfs files) in `Documentation/networking/bonding.txt` in the Linux source tree.

**Comment by fagg** [comment]
Also seeing this issue. Just to add to this, I have a slightly different setup.

My bond is an LACP trunk connected to a managed switch. For some insane reason, my managed switch likes to send broadcast packets to each of the bonded NICs individually, which results in them getting deduplicated and subsequently dropped. As such I end up with a ton of these alarms - it's  in alarm state 24/7 and I've had to silence the notifications for my sanity. 

The clue is that across each of my NIC slaves (4 of them in my case), you end up seeing the exact same number of dropped RX packets (the sum of the dropped packets on all NIC slaves == number of dropped RX packets on the bond interface).

Please let me know if I can be of assistance with any more info you might need.

**Comment by vlvkobal** [comment]
I had a discussion with @ilyam8 and @mfundul about this issue and we came to a conclusion, that we can't safely disable the alarm even for an inactive bonded interface, not to mention other possible configurations. For example, if we automatically disable the alarm for an inactive bonded interface, a user can miss the moment number of drops has raised on this interface.

The alarm is a tricky one and there can be a lot of false positives. But I think, the right way is to leave the alarm as it is and add some information about it in the `proc.plugin` documentation. A netdata user should be aware of possible issues with a network interface and tune or disable the alarm manually if he is sure it is incorrect in his case.

@cakrit what do you think?

**Comment by ilyam8** [comment]
The link from OP is from 2012. And its status is `Invalid`, becuase it is not a bug (see last comment).

**Comment by cakrit** [comment]
We should start with the instructions as a temporary workaround, for sure. The related .conf files will need a long comment that talks about how users can detect the interfaces that are expected to show drops and how to modify the alarm configuration to exclude only those interfaces, using the `family` option. 

However, we need to think about what intelligence we can add here. One of the key tenets of netdata is zero configuration. Since we are able to detect bonded interfaces, we should do something smart about them and I'm not necessarily talking only about the alarms. Perhaps our charts also need something additional or different. We'll need to think about it a bit more. The [last comment  on that thread](https://bugs.launchpad.net/ubuntu/+source/bridge-utils/+bug/1041070/comments/14) and @ferroin 's info here give us a good starting point for an algorithm that we can suggest to the users for the workaround and use for our longer term solution.

It's a very difficult problem though I am a bit concerned by @fagg 's comment https://github.com/netdata/netdata/issues/2285#issuecomment-462300780. This case seems to be very different than the expected behavior of inactive slaves dropping duplicate packets when `all_slaves_active` is 0. @fagg, are all your slaves active? Perhaps it's not about duplication at all but about invalid broadcast packets that would be dropped regardless of whether the interface was bonded or not? For a really great solution, we would need to distinguish between the packets that were dropped due to the deduplication expected in a bonding interface and drops for other reasons. Is that even possible without a `tcpdump` that we definitely can't add to netdata?

**Comment by ilyam8** [comment]
@fagg case sounds like a bug in his switch os

> For some insane reason, my managed switch likes to send broadcast packets to each of the bonded NICs individually

It should send broadcast only to the master lacp port. Nothing we can do there.

**Comment by vlvkobal** [comment]
> We should start with the instructions as a temporary workaround

It will be a permanent solution. I can't imagine any sane and safe logic we could apply to the alarm. We can't predict mistakes in designing or configuring a network the interface is the part of. We can only guess what might be a little bit more appropriate solution in the majority of the possible cases with quite a low level of certainty. It doesn't matter how smart we will be in prediction it will still be a vague prediction. We might improve some things, but we will make other things worse at the same time.

However, if any networking expert provides us with a proved, precise, and sane algorithm for a particular network interface configuration, we can implement it.

Another way is to change a strict policy of the alarm to a loose one. But if we want to warn users in ambiguous situations, we shouldn't change it.

> This case seems to be very different than the expected behaviour of inactive slaves dropping duplicate packets

I mentioned inactive slaves only as the simplest example. It can't be applied to all of the possible cases.

As for the @fagg comment, the algorithm proposed there will not work correctly in a ton of other cases. So, @ilyam8 is right: nothing we can do there.

**Comment by fagg** [comment]
I have been led to believe that my particular issue is related to my HP
switch, yes. This seems to be a known issue with some of them (1810G in my
case), and I'm not sure there's much to do about it on any level. My
probing around seems to validate the theory that it's getting duplicate
broadcast packets.

My post was merely trying to point out that there's issues beyond what was
originally discussed here (I found this thread in the hope there was a
workaround for my issue). As suboptimal as it is to have to silence the
alarm constantly (or turn it off completely), you guys can't be expected to
work around this sort of buggy nonsense. The solution in my case is
probably "get a different switch".

**Comment by ilyam8** [comment]
> My probing around seems to validate the theory that it's getting duplicate broadcast packets.

since you have the linux host it easy to investigate it using `tcpdump`

**Comment by ilyam8** [comment]
> The solution in my case is probably "get a different switch".

@cakrit as you see the alarm is extremly useful :smile:
