### ISSUE TITLE
on frontend, if JavaScript is disabled, there's no graceful degradation

### ISSUE THREAD

**Issue by magicgoose** [netdata/netdata#2422]
if JavaScript is disabled, there's no graceful degradation, everything breaks down beyond recognition.

Tested on `http://london.my-netdata.io/default.html`

This is how it looks like:
![screen shot 2017-07-06 at 07 27 17-fullpage](https://user-images.githubusercontent.com/1442206/27895655-d6a44dca-621c-11e7-8a27-61debb030f8a.png)

**Comment by ktsaou** [comment]
You are right. I'll try to fix that.

**Comment by gmosx** [comment]
But what would be a 'graceful degradation' ? And why would someone want to use Netdata GUI without JavaScript enabled?

**Comment by Ferroin** [comment]
> But what would be a 'graceful degradation' ?

Displaying a message that you need JavaScript enabled to view this site, just like used to be the standard for sites that required it.  Bonus points if it's done in a way that works correctly with stuff that blocks script execution without disabling JavaScript, because browser extensions that do that are starting to become popular in the tech-savvy community.

> And why would someone want to use Netdata GUI without JavaScript enabled?

They probably wouldn't, and I'm not sure we should support it.

**Comment by gmosx** [comment]
OK, I guess displaying a message is reasonable. Regarding proper handling of the script blockers, I will do some research.

**Comment by Ferroin** [comment]
@gmosx I can't say I've done any research, but the few pages I've seen that do handle them correctly have the message in the actual HTML outside of the usual `<noscript>` tags so that it gets rendered, and then delete that first-thing in their scripts.
