### ISSUE TITLE
FQDN in alert sending

### ISSUE THREAD

**Issue by m-emelchenkov** [netdata/netdata#2477]
Hi!

it's nice to have FQDN (hostname -f) in alerts (which delivered via alarm-notify.sh script), because now I get, for example: "www needs attention - ram in use". So I do not know what "www" means because it is only just a part of a full domain name which is a hostname for the server.

**Comment by ktsaou** [comment]
Hi,

the hostname used in alerts is the one defined in `netdata.conf` at `[global].hostname` (so that slave hosts will give the right hostname). It defaults to whatever `gethostname()` returns.

But you are right. We should probably use also `getdomainname()` and append the two to fix the real full hostname.

We could also use `hostname -f` at the little comment at the end of emails to uniquely identify the host sending the alarm:


![image](https://user-images.githubusercontent.com/2662304/28332351-2d6a708c-6bfd-11e7-9dfc-10960a3357fb.png)

**Comment by ktsaou** [comment]
To implement the first (add domain name), we probably need to fix #2335 first.

**Comment by m-emelchenkov** [comment]
I use Telegram bot as an alarm delivery method. Thanks for reply and for info about [global].hostname—yes, I already know this option, and I use it to name some servers more human-readable, just want to have FQDN as a default for those servers which hostname.domainname is already have good meaning so do not configure it manually. I agree, UI should be fixed in first place.

**Comment by ktsaou** [comment]
@Ferroin 	we could modify `alarm-notify.sh` to send the FQDN of the host sending the alarm. It could be an option actually.

**Comment by cakrit** [comment]
I think that we shouldn't replace the existing functionality of the host that is configured in netdata.conf, just add a line with the FQDN and the IP on each alarm, regardless of how netdata calls alarm-notify.sh. It's a very easy addition. Agreed?

**Comment by Ferroin** [comment]
FQDN should be easy, though I agree that it should be optional, especially since figuring out that there isn't one can take a long time on a system that doesn't have one.

IP is trickier, because it's not unusual for systems to have 2 or more IP's.

**Comment by Ferroin** [comment]
Alternatively, why not just make it so the user can choose to either display the short hostname (like we currently do) or the FQDN?  That would amount to at most 4-5 lines of changes in `alarm-notify.sh`.

**Comment by cakrit** [comment]
Fine. Let's say this then:
- Default is exactly as is. 
- We add an option to health_alarm_notify.conf to use FQDN instead.
- Ensure though that url_host is created from the FQDN, because the goto_url shouldn't be affected by this parameter. It should always have the name that the registry will recognize, which is the one the daemon sends to alarm-notify.sh

**Comment by Ferroin** [comment]
@cakrit Agreed.  I'll try and have a working PR later today for this.

**Comment by Ferroin** [comment]
@ktsaou Do you happen to know if there are any circumstances where Netdata will invoke `alarm-notify.sh` _without_ specifying a hostname?  If there aren't any, that would make the code for this change significantly simpler.

**Comment by ktsaou** [comment]
> Do you happen to know if there are any circumstances where Netdata will invoke `alarm-notify.sh` _without_ specifying a hostname

All invocations of `alarm-notify.sh` are exactly the same. There is only one point that invokes it: https://github.com/netdata/netdata/blob/68f71547d237ec4509d88d6e9a064b8aac6f1a48/health/health.c#L103-L200

**Comment by cakrit** [comment]
We have the case of calling `alarm-notify.sh` in test mode, it's the only one where we don't explicitly pass the host configured in `netdata.conf`. In this case, in L57 alarm-notify.sh calls itself again by passing the FQDN (i.e. ignores the setting in netdata.conf).
