### ISSUE TITLE
SNMP Plugin (Multiple Devices)

### ISSUE THREAD

**Issue by hmmxp** [netdata/netdata#2496]
Dear All,

Are there any better way to add multiple devices and monitoring them via SNMP plugin?

Current my understanding is add each device, OID and related based on each device which i find time consuming.

Thank You

**Comment by ktsaou** [comment]
You are right.
But there is no other way currently.

I understand that we could have a script walk through an SNMP device to automatically detect the charts it could add, but I am not sure I know how to map all these OIDs yet.

If you can help in this area it would be great!

**Comment by frizop** [comment]
Isn't that what MIB's are for? Mapping OIDs to the info collected?

**Comment by hmmxp** [comment]
Dear All,

1. What language should this be coded? My current background is system administration but learning back how to code, so coding at the moment very basic. 

But i can give ideas on how to make it work

1. The script is able to define multiple module (Example: 1 module for cisco switch, 1 module for APC UPS etc.)

2. Under each module it allows users to define the SNMP target, SNMP Authentication, SNMP OID and The Required Metrics Based on SNMP OID.

Example (Based On Prometheus SNMP_Exporter)

apcups:
  version: 2
  auth:
    community: SomeCommunityString
  walk:
  - 1.3.6.1.2.1.1.3
  - 1.3.6.1.2.1.2
  - 1.3.6.1.4.1.318.1.1.1.12
  - 1.3.6.1.4.1.318.1.1.1.2
  - 1.3.6.1.4.1.318.1.1.1.3
  - 1.3.6.1.4.1.318.1.1.1.4
  - 1.3.6.1.4.1.318.1.1.1.7.2
  - 1.3.6.1.4.1.318.1.1.1.8.1
  - 1.3.6.1.4.1.318.1.1.10.2.3.2
  metrics:
  - name: sysUpTime
    oid: 1.3.6.1.2.1.1.3
    type: gauge
    help: The time (in hundredths of a second) since the network management portion
      of the system was last re-initialized. - 1.3.6.1.2.1.1.3

**Comment by hmmxp** [comment]
Ready to help in anyway be it coding or give ideas, let's do this.

It will be beneficial for everyone

**Comment by ktsaou** [comment]
ok.

I understand that SNMP is based on templates. For example all switches use the same OIDs to describe the the ports. In order to provide charts for all ports, we should first get the number of ports supported by the switch (i.e. auto-detection) and based on this information configure the SNMP collector to query the switch for all ports and generate charts.

So, I would split it in 3 parts:

1. **Configuration**: read users configuration about each SNMP device. Something like the IP address of the switch, SNMP connection settings, etc.

2. **Auto-detection**: connect to the SNMP device and attempt to detect, based on the OIDs we find, the SNMP metrics we can collect. This should template based. So, if you find OID X and Y, we can enable template T1 with options O1 and O2. Example, if we detect that the SNMP device reports ethernet ports, we should enable a template that creates a chart for each port - and since the switch has 24 ports, we need to have 24 such charts under the same name.

3. **Data Collection**: collect and visualize metrics.

So the plugin should be enhanced like this:

### configuration

The snmp configuration should like this:

```json
{
    "enable_autodetect": false,
    "update_every": 5,
    "max_request_size": 100,
    "servers": [
        {
            "hostname": "10.11.12.8",
            "name": "switch1",
            "community": "public",
            "update_every": 10,
            "max_request_size": 50,
            "options": { "timeout": 10000 },
        },
        {
            "hostname": "10.11.12.9",
            "name": "switch2",
            "community": "public",
            "update_every": 10,
            "max_request_size": 50,
            "options": { "timeout": 10000 },
        },
        {
            "hostname": "10.11.12.10",
            "name": "switch3",
            "community": "public",
            "update_every": 10,
            "max_request_size": 50,
            "options": { "timeout": 10000 },
        }
    ]
}
```

### auto-detection

We should snmpwalk all servers and based on the OIDs we find we should enhance the above configuration.

So, if we connect to `switch1` and we find that it has ethernet ports, we should enhance the configuration like this:

```json
{
    "enable_autodetect": false,
    "update_every": 5,
    "max_request_size": 100,
    "servers": [
        {
            "hostname": "10.11.12.8",
            "name": "switch1",
            "community": "public",
            "update_every": 10,
            "max_request_size": 50,
            "options": { "timeout": 10000 },
            "charts": {
                "snmp_switch1.bandwidth_port": {
                    "title": "Switch Bandwidth for port ",
                    "units": "kilobits/s",
                    "type": "area",
                    "priority": 1,
                    "family": "ports",
                    "multiply_range": [ 1, 24 ],
                    "dimensions": {
                        "in": {
                            "oid": "1.3.6.1.2.1.2.2.1.10.",
                            "algorithm": "incremental",
                            "multiplier": 8,
                            "divisor": 1024,
                            "offset": 0
                        },
                        "out": {
                            "oid": "1.3.6.1.2.1.2.2.1.16.",
                            "algorithm": "incremental",
                            "multiplier": -8,
                            "divisor": 1024,
                            "offset": 0
                        }
                    }
                }
            }
        },
        {
            "hostname": "10.11.12.9",
            "name": "switch2",
            "community": "public",
            "update_every": 10,
            "max_request_size": 50,
            "options": { "timeout": 10000 },
        },
        {
            "hostname": "10.11.12.10",
            "name": "switch3",
            "community": "public",
            "update_every": 10,
            "max_request_size": 50,
            "options": { "timeout": 10000 },
        }
    ]
}
```

We can do the above on disk (externally to the plugin), but we can also embed the auto-detection method to the plugin code and do it in memory.

### data collection

If we have the above done, the existing data collector will just do it.

---

How does that sound?

**Comment by ktsaou** [comment]
Keep in mind all node.js implementations for SNMP do not support SNMP v3.

If we do this work, it might be preferable to swtich to python and use a SNMP library that can support SNMP v3 (like this: http://pysnmp.sourceforge.net/).

pySNMP says it is pure python, which means we can also distribute it with netdata.

cc: @l2isbad

**Comment by l2isbad** [comment]
To be honest i don't think snmp is what netdata should focus on. It's too complicated and not worth the effort (since there is a lot of great open source projects for monitoring network devices).  Even current netdata's dashboard is not suitable for monitoring many devices.

I think basic snmp implementation is ok. I use it to chart some core stats (uplink, number of subscribers, radius pps, dns response time) of our network (20k+ network devices (ISP)).

**Comment by hmmxp** [comment]
I understand SNMP is complicated and i know there are other great open source project, what i am trying here to have a good snmp plugin or dedicated that people can use as replacement and consolidate all monitoring to a single platform as much as possible.

That was my thought

**Comment by vbonline** [comment]
Collecting interface statistics via SNMPv3 for 200+ interfaces at work needs 45 sec. per switch(!). 
I can't see how this would fit in with netadas default interval of 1 sec.
Configure a backend for netdata to have historical data (influxdb/Grafana in my case) and send SNMP data directly into the backend (where it belongs IMHO).

**Comment by ktsaou** [comment]
> Collecting interface statistics via SNMPv3 for 200+ interfaces at work needs 45 sec. per switch(!).

this must be a collector's fault. On my tests enterprise grade devices as very fast and can easily serve metrics per second.

SOHO grade devices are slower but I have never seen any needing more than 10 seconds.

A few devices are losing responses when multiple collectors are querying them at the same time. This leads to retries which may increase collection time significantly.

Even if a switch is slow, netdata core and the snmp collector can have a different data collection frequency per device (actually per chart).

**Comment by l2isbad** [comment]
Actually it can be 4k+ interfaces per switch (D-Link DES-3028 with `vlan_trunk` function). 

> can easily serve metrics per second

Very depends.

cisco 7606 (sup 720).

![screenshot_20170724_024738](https://user-images.githubusercontent.com/22274335/28501616-abd9aa2a-701a-11e7-998d-55b07afbe8b8.png)

**Comment by ktsaou** [comment]
hm... this is huge time. Are you sure this is not poller's fault? If you just send one `snmpget` to such a switch, does it need that much time to respond?

My enterprise grade cisco switches at work (sorry I don't recall their model), do per second data collection with netdata for 48 ports each. My linksys SRW2024P switch at home, needs 7-8 seconds to respond (24 ports).

SNMP is supposed to be very simple for the devices. They just have a few counters which they update all the time and they just need to lookup the values and respond to SNMP requests. 45 seconds for this operation means that probably the SNMP processor in the device runs at 1Mhz or even lower... :-)

Except if I am missing something... (I admit I am not an SNMP expert)

**Comment by runeka** [comment]
Observium polls the entire Switch MIB for statistics on details like DDM and NTP. If all you need is port bits it is faster.

**Comment by cakrit** [comment]
This issue may be a bit old and I see few differing opinions on how much netdata should be focused on SNMP, but there are good points in here, which shouldn't be ignored. I'm keeping it on our backlog.

**Comment by Duffyx** [comment]
I think SNMP auto discovery is the only feature missing in netdata that I'm missing today :-). This would be a really great addition and maybe even taken for granted sometimes when you compare alternative monitoring software.

**Comment by ilyam8** [comment]
SNMP autodiscovery is very difficult and it is a big project itself.

See

> https://www.observium.org/

> https://www.librenms.org/
