### ISSUE TITLE
overlapping alarm templates with different settings each

### ISSUE THREAD

**Issue by haasn** [netdata/netdata#2579]
This is 1. redundant with the RAM used metrics, and 2. generates a lot of false positives (at least on my end): because of tmpfs' usually small size meaning that unpacking an archive to /tmp can cause trigger the “out of disk space time” warning frequently.

**Comment by haasn** [comment]
This configuration solves my issue, but I argue that it should be default behavior:

```conf
[plugin:proc:diskspace]
        exclude space metrics on filesystems = tmpfs
```

**Comment by Ferroin** [comment]
I'm somewhat ambivalent about whether or not this is the default (I've already got special settings in that value because I've got a somewhat complicated storage stack), but I would like to point out one of the primary counter-arguments:
* A lot of software breaks if `/tmp` runs out of space.  Technically, stuff shouldn't break if `/tmp` is full, but in practice many things do.  The same goes for `/run`, which is usually on tmpfs these days, and `/dev` which is a special type of tmpfs on most systems (and udev will often break if it's full).
* Differentiating what is using RAM is often important (tmpfs is counted under both cache and possible swap (it will use swap if memory pressure is high), but it's not conventional cache or swap usage either).

Overall though, I do think the handling could be improved in other ways though, with two things coming to mind:
1. The alert about a disk being full in less than 48 hours can probably be disabled for certain locations (`/tmp`, `/var/tmp`, `/run`, and most other widely used tmpfs mounts, with the possible inclusion of `/dev` and `/dev/shm`) because the typical write patterns are a few bytes here and there once at startup, and occasional spikes during normal usage, which in turn means that it's very likely to trigger false positives.\  This is especially important for cases like `/run`, which is usually small enough that writing a single file a few kB in size can trigger the alert.
2. The thresholds for disk fill on tmpfs filesystems should probably be much higher (I'd say 90 or 95 for warning, and 95 or 97.5 for critical).  Unlike most other filesystems, tmpfs can be resized on-the-fly with a single command and no need to mess with the block stack, so it's less critical that it be dealt with early, and tmpfs instances are often sized to whatever task they're going to be used for, so short of something going completely bonkers, they can be expected to be closer to full most of the time.

**Comment by ktsaou** [comment]
I like the idea of having different thresholds for certain mount points.
I think this can be done by filtering on `families: *`. Let me check it.

**Comment by Ferroin** [comment]
Just looking at what's tracked on my systems, I think netdata is already excluding tracking of most of the filesystem types that we should exclude from those checks (devpts for example) other than tmpfs.

**Comment by ktsaou** [comment]
I think this is already implemented.
So I believe that the same alarm can be defined, matching different families each, and the first matching will be used for each disk.

So, I am closing this. But if you need help configuring it, just post.
