### ISSUE TITLE
squid with https

### ISSUE THREAD

**Issue by wikiwang1991** [netdata/netdata#2612]
For some reason my squid only accepts https connections.
There is --https option in squidclient, would you please add this to configuration?
Thanks.

**Comment by ktsaou** [comment]
Hi,

netdata does not use `squidclient`. It connects directly to the squid port and attempt to fetch [one these URLs](https://github.com/firehol/netdata/blob/918919e46c4e76aad12e9f1495d81719ea8bf343/conf.d/python.d/squid.conf#L87-L161).

I am not sure how we can do this in the python plugin. @l2isbad any ideas?

**Comment by Ferroin** [comment]
Are you using Python's internal `http.client` module, or are you rolling your own?  In the first case, it shouldn't be too hard to add (in fact, it should just amount to changing `http.client.HTTPConnection()` to `http.client.HTTPSConnection()`, since the default auto-generated SSL context should be sufficient), the second might be trickier, but still not too hard if you just use the `ssl` module.

**Comment by ktsaou** [comment]
I think it cannot use `http.client` since these URLs are not HTTP friendly. They are a squid extension.
So, probably an extension to `SocketService` is needed to support SSL.

Unfortunately I am not that good in python. If you can help please do so.

**Comment by l2isbad** [comment]
@Ferroin can you help on this?

**Comment by ilyam8** [comment]
Current module connects to tcp socket to get data, there is an option to get same data from http endpoint

> https://wiki.squid-cache.org/Features/CacheManager

If i understand it right it works since v3.2+

<details>
<summary>curl http://127.0.0.1:3128/squid-internal-mgr/info</summary>

Squid Object Cache: Version 3.4.8
Build Info:  linux
Start Time:	Mon, 26 Nov 2018 12:02:57 GMT
Current Time:	Tue, 10 Dec 2019 07:58:12 GMT
Connection information for squid:
Number of clients accessing cache:	1
Number of HTTP requests received:	34184188
Number of ICP messages received:	0
Number of ICP messages sent:	0
Number of queued ICP replies:	0
Number of HTCP messages received:	0
Number of HTCP messages sent:	0
Request failure ratio:	 0.00
Average HTTP requests per minute since start:	62.7
Average ICP messages per minute since start:	0.0
Select loop called: 350993690 times, 93.252 ms avg
Cache information for squid:
Hits as % of all requests:	5min: 0.0%, 60min: 0.0%
Hits as % of bytes sent:	5min: 100.0%, 60min: 100.0%
Memory hits as % of hit requests:	5min: 0.0%, 60min: 0.0%
Disk hits as % of hit requests:	5min: 0.0%, 60min: 0.0%
Storage Swap size:	0 KB
Storage Swap capacity:	 0.0% used,  0.0% free
Storage Mem size:	260608 KB
Storage Mem capacity:	99.4% used,  0.6% free
Mean Object Size:	0.00 KB
Requests given to unlinkd:	0
Median Service Times (seconds)  5 min    60 min:
HTTP Requests (All):   0.00000  0.00000
Cache Misses:          0.00000  0.00000
Cache Hits:            0.00000  0.00000
Near Hits:             0.00000  0.00000
Not-Modified Replies:  0.00000  0.00000
DNS Lookups:           0.00000  0.00000
ICP Queries:           0.00000  0.00000
Resource usage for squid:
UP Time:	32730915.055 seconds
CPU Time:	23769.736 seconds
CPU Usage:	0.07%
CPU Usage, 5 minute avg:	0.07%
CPU Usage, 60 minute avg:	0.07%
Maximum Resident Size: 1499792 KB
Page faults with physical i/o: 0
Memory usage for squid via mallinfo():
Total space in arena:  360776 KB
Ordinary blocks:       358531 KB  77967 blks
Small blocks:               0 KB      0 blks
Holding blocks:         27540 KB      8 blks
Free Small blocks:          0 KB
Free Ordinary blocks:    2245 KB
Total in use:            2245 KB 1%
Total free:              2245 KB 1%
Total size:            388316 KB
Memory accounted for:
Total accounted:       332983 KB  86%
memPool accounted:     332983 KB  86%
memPool unaccounted:    55333 KB  14%
memPoolAlloc calls:        40
memPoolFree calls:  3491383255
File descriptor usage for squid:
Maximum number of file descriptors:   65535
Largest file desc currently in use:     25
Number of file desc currently in use:   16
Files queued for open:                   0
Available number of file descriptors: 65519
Reserved number of file descriptors:   100
Store Disk files open:                   0
Internal Data Structures:
 65150 StoreEntries
 65150 StoreEntries with MemObjects
 65149 Hot Object Cache Items
     0 on-disk objects

</details>

**Comment by ilyam8** [comment]
We have

```yaml
  host     : '127.0.0.1'
  port     : 8080
```

I think it would be better to have one param with scheme, address and port

**Comment by ilyam8** [comment]
This feature will be added to the go version of the squid collector when we will work on it, no need to keep this issue open.
