### ISSUE TITLE
notifications with smstools (direct connection to mobile phone)

### ISSUE THREAD

**Issue by LeeNX** [netdata/netdata#2720]
Looking at implementing local SMS for alerts, mostly for critical. I found smstools3, which Ubuntu has a package for and seem pretty easy to do a bash script send messages.  
  
Any reason anybody else can think of not to use smstools3 or a better local SMS gateway?  
  
Worth making documentation and possibly a PR for the script?

**Comment by Ferroin** [comment]
I think most of the reason this hasn't been done is that having a local SMS gateway or a GSM modem is a pretty unusual case for typical netdata installations, and most people have smartphones so the other notification services provide non-SMS methods of getting notifications on their phone, especially if they have email configured on their phone.

Whether or not it's worth doing is a separate discussion, but I'm probably not the best person to discuss that with since I don't maintain the code myself and I wouldn't likely ever use it (aside from not having access to an SMS gateway or GSM modem I can use for this, I just route everything through email and use GMail labels to sort and control what shows up on my phone).

**Comment by LeeNX** [comment]
Thanks @Ferroin.  
  
My use case is to monitor a remote site with a less than reliable internet connection. No good if the internet goes down and can't get alerts. I agree and understand the very limit use case, but I am sure they are other people that might find this useful.  
  
My questions was more about if other might have found better tool other than smstools3 - smstools3.kekekasvi.com  
  
I already have my basic PoC up and running and already thinking about extending the gateway functionality, but as a Lazy Admin, that will only happen if there is a real need.

**Comment by Ferroin** [comment]
I'm pretty certain that smstools is the only option available unless you feel like trying to talk to the GSM modem or SMS gateway directly yourself.

If you've already got working code though, I'd say that there's no reason not to submit a PR, assuming you've got it documented.  Keep in mind however that you'll likely be the person who gets asked to help if users have trouble with it.

**Comment by sarlalian** [comment]
smstools is generally the best option, most others are either commercial or poorly supported.

**Comment by LeeNX** [comment]
Thanks ... Just to be fair, I did take a quick look at gsm-utils, kannel, (w|g)ammu and gnokii  
  
smstools seemed:  
 *  to have more recent development and a package in Ubuntu for R-Pi
 * was easy to get up and running
 * small requirements - (no DB)  
  
Will post back shortly, once alerts are working in netdata via smstools.

**Comment by Ferroin** [comment]
Based on some quick investigation, smstools is pretty widely supported, but not universally.

Of the distro's I can easily check, it's available on:
* Debian
* Ubuntu
* openSUSE
* Arch via AUR (and possibly Manjaro as a result)
* FreeBSD
* NetBSD

And is absent in standard repositories for:
* Fedora (and by extension, probably CentOS and RHEL)
* Alpine

Gnokii appears to be more widely available, but other than that, I entirely agree with your assessment that smstools is a better option because it's simpler to use and doesn't have stupid dependencies on a full-fledged RDBMS.

**Comment by ktsaou** [comment]
> Worth making documentation and possibly a PR for the script?

yes, of course! I would love to have this functionality in netdata.

**Comment by LeeNX** [comment]
Still going to work on this, just waiting for a SIM package for cheaper SMS. Please don't close. ;-)

**Comment by Ferroin** [comment]
@LeeNX Do you still have interest in this?  If so, I'd like to try and coordinate so we can build on what code you already had.

**Comment by LeeNX** [comment]
@Ferroin - I had hope to deploy alerts for our office systems, but this never happen ... But I have setup at home some notifications and hoping to put together some info, but does not use smstools3.  
  
Also with the new addition to our family, I currently have very limited time to play with these awesome tools, so please don't wait on me ... At least for the time been.

**Comment by ilyam8** [comment]
> Also with the new addition to our family

@LeeNX gratz!

**Comment by binaryplease** [comment]
I'm still intereseted in this and will be trying it out soon. (When the GSM stick arrives). Did you make any progress on it? What would be the best place to start?

**Comment by cakrit** [comment]
@Ferroin will you be able to work on this?

**Comment by Ferroin** [comment]
@cakrit As of right now, probably not in the immediate future.  I've gotten far more involved than I intended to be on a private development project, and as such don't have anywhere near as much time as I did when I had initially expressed interest in helping with it.

**Comment by cakrit** [comment]
That's fine mate, you know we love you no matter what! :)
Gents, I don't have a problem giving it a shot. Can someone provide the command that needs to be executed to send the SMS? Of course we want to limit the text to fit in a single SMS, correct?

**Comment by Ferroin** [comment]
The relevant command (if you're planning on using smstools) is `smssend <phone-number> "<message>"`.  However, you need to have a running (and correctly configured) instance of `smsd` on the system for that to work.  Info on getting that set up can be found [at the smstools website](http://smstools3.kekekasvi.com/index.php?p=).

**Comment by cakrit** [comment]
I've worked with SMS gateways in the past and I know better than to try and set it up :)
I'll just write the code and let @binaryplease or @LeeNX test it before we merge it.

**Comment by cakrit** [comment]
Tentatively planned it for this sprint, though I do have a lot of other things committed. This one should be really easy though...

**Comment by cakrit** [comment]
It's ready, someone please test #5662 in a working system, so we can merge.

**Comment by cakrit** [comment]
On more call for testers. I'll probably merge it on Monday if no one can help, as it doesn't break anything else.
