### ISSUE TITLE
[RFE] send notifications repeatedly until the alert is resolved

### ISSUE THREAD

**Issue by pschiffe** [netdata/netdata#2956]
Hello,

nagios has this feature, that if there is an alert, notification email is send repeatedly every hour or so (configurable) until the alert is resolved. I would like to see this feature in netdata as well, as sometimes long lasting alerts can be lost during short lasting alerts (if there are occasional spikes e.g. during backups or so). I know that I can probably super-tinker with alerts to configure them in a way that I receive the notifications only when really necessary, but I believe that this new feature would be useful as well. I'm thinking about global configuration (on/off, how often) and per alert as well.

I've checked the documentation, but didn't find anything related. Please let me know if the feature already exists.

Thanks.

**Comment by Ferroin** [comment]
I don't know of such a feature in netdata, but I agree that it would be a good thing to have, especially if there's per-alarm configuration.  Netdata is in fact the only monitoring software I know of that doesn't seem to have this feature.

**Comment by ktsaou** [comment]
Yeap, this is needed.

**Comment by pschiffe** [comment]
bump to increase priority. with more alerts this is getting more and more important. I'm not able to create a PR, but I can help to test, or provide any information necessary.

**Comment by Ferroin** [comment]
I believe Grafana does support recurring notifications, but I don't know how easy it is to set up notifications in Grafana (I looked into Grafana bit some time ago when I was using collectd instead of netdata, but never got very deep because at the time it was more effort than it was worth for my use case).

**Comment by ktsaou** [comment]
How this should work?

Just adding a `repeat: DURATION` would suffice?

**Comment by Ferroin** [comment]
I like the idea of having just a simple `repeat` key, with two caveats:

* It would be _really_ nice to have some global config for this that can be overridden by individual alarms so that people only have to change things in one place if they just want this globally.
* It would also be kind of nice to be able to specify a different frequency for `CRITICAL` alarms, as those are usually more urgent and it therefore makes sense to have them pester people more.  Having this part default to just matching the interval for `WARNING` messages makes sense though.

**Comment by ktsaou** [comment]
ok, I started coding this.

I added `repeat: [DEFAULT_VALUE] [warning VALUE] [critical VALUE]`, where value is a duration (i.e. `1m`, `10s`, `1d`, etc so it is quite flexible - it also support fractionals).

I also added 2 netdata.conf options under `[health]` for providing default repeat rates for all alarms.

The only thing missing is to repeatedly send the notifications. I have the following question:

netdata has an alarm transaction log. This is the alarm log visualized on the dashboard too and it is currently one-on-one with the notifications.

It works like this:

1. Every time an alarm changes state, an entry is added in the alarm log. This is done for all alarms, before sending any notifications. if it important to do it like that, so that all alarms will have accurate timings.

2. Once all alarms have been checked for state changes, netdata traverses all NEW alarm log entries, and executes the programs to dispatch notifications.

3. alarm log entries are also linked together, when they refer to the same alarm. So, a new alarm log entry invalidates (obsoletes) the previous log entry for the same alarm.

So it is 2 phases: a) check the alarms and b) dispatch notifications - and the log is kind of live. netdata uses this to understand what it has to do with the notifications.

The question is this: each repeated notification should add a new alarm log entry? or not?

### case 1: new alarm log entry is added for repeated notifications

This is the easier to implement. But it will flood the log. The log will actually become sort of a notifications log.

### case 2: the existing alarm log entries are used for repeated notifications

This is probably the preferred, but I don't like the idea of keeping a history of all the repeated notifications (netdata keeps with each alarm log entry the program run, its exit status, the time it was run, etc).

If we use the existing alarm log entry, netdata will only keep metadata for the last execution of the notification. All previous executions will only be available in `/var/log/netdata/error.log` and the notifications themselves.

This has a few tricky parts, since I don't want netdata to loop through the entire log every time. The way it is now, it loops through the NEW log entries only. Since we will use the existing log entries for the repeats, I will have to find a way to avoid looping over thousands of log entries every time. But I'll manage this...

What do you think?
Case 2?

**Comment by ktsaou** [comment]
> If we use the existing alarm log entry, netdata will only keep metadata for the last execution of the notification. All previous executions will only be available in /var/log/netdata/error.log and the notifications themselves.

hm... probably the **first successful notification** is more appropriate. The important information to know is when you where first notified, not the last.

I could probably also keep a counter (how many successful notifications it dispatched).

**Comment by pschiffe** [comment]
@ktsaou this is awesome! thanks. I basically agree with you on the case 2, as the alert state itself is more important than whether the notification was sent, or how many, and the alarm log is valuable even without any notification info.

**Comment by cakrit** [comment]
We were unable to proceed with this issue as planned, we discussed with a contributors about picking it up shortly.

**Comment by kamcpp** [comment]
Hi guys. I've started to work on this issue, but I got some questions. Before asking them, I explain what I'm going to do first.

I'm going for the Case 2 in @ktsaou's above comment. I'm keeping a list of repeating alarm entries in the host object. The alarm entries now have two extra fields to keep the warning and critical repetition durations, and they have a few other not-persisted states. Now, my questions:

1. Currently, we are using a fixed-length policy for cleaning up the hosts' alarm_log. What about the alarm entires which are in the repeating list? The first obvious approach is to remove them from the alarm_log but don't delete them right away. But I think we need further cleanups regarding alarm entries once they are not needed anymore.

2. The current policy is clear about the non-repeating alarm entries. But regarding the repeating alarm entires, when should we remove them from the host's repeating list? This question is valid for both Case 1 and Case 2 solutions. As I read in the initial description, we have a condition **until done**. What does it mean exactly in terms of implementation?

I have prepared an initial code about the above changes, but I cannot move further because of the above questions.

**Comment by cakrit** [comment]
IMHO it's overkill to keep these alarms in place. The default limit for alarm log entries in memory is 1000, which means that I will have received at least another 999 more notifications from other sources in the meantime. Furthermore, I'm not quite sure, but I think that Netdata would treat that old, removed, repeated alarm as a new one, starting the repeated notifications all over again. Can you verify it?

I think that what you mean by 'until done' is 'until the alarm is CLEARED'. That's a very specific point in time, marked by its own entry in the alarm_log. Active alarms are the ones that are not yet cleared and we already show a list of those, so it's not so difficult to know which ones are not 'done', i.e. 'cleared'.

**Comment by kamcpp** [comment]
> IMHO it's overkill to keep these alarms in place. The default limit for alarm log entries in memory is 1000, which means that I will have received at least another 999 more notifications from other sources in the meantime. Furthermore, I'm not quite sure, but I think that Netdata would treat that old, removed, repeated alarm as a new one, starting the repeated notifications all over again. Can you verify it?
I think that your statement about 'old, removed, repeated alarm as new one' refers to the Costa's case 1. Since I'm going to implement case 2, I have to maintain the same alarm entry for future repetitions. If you think the first approach (adding new log entries for future repetitions) is better, I can think about it. The previous PR was implementing the first approach. It was inserting new log entries for repeating notifications. I found Costa's comments valid on his proposed approach by flooding the alarm log by notifications.

> I think that what you mean by 'until done' is 'until the alarm is CLEARED'. That's a very specific point in time, marked by its own entry in the alarm_log. Active alarms are the ones that are not yet cleared and we already show a list of those, so it's not so difficult to know which ones are not 'done', i.e. 'cleared'.
This is great. Thanks. I was exactly looking for the definition of 'done' or 'cleared'.

I got two further questions.

- Is it possible to silent a repeating notification? I guess yes like others.
- And for my general knowledge, how an alarm is cleared? Is it based on the definition of the alarm and the collected values?

**Comment by cakrit** [comment]
> Is it possible to silent a repeating notification? I guess yes like others.

Yes, it's all described [here](https://docs.netdata.cloud/web/api/health/#health-management-api).

> how an alarm is cleared? Is it based on the definition of the alarm and the collected values?

Yes. Specifically, it's based on the limits set in `warn` and `crit`.

E.g. for this... 
```
     warn: $this > (($status >= $WARNING)  ? (80) : (85))
```

 - No alarm -> warning, when I go from 84 to 86
 - Warning or critical -> Clear, on my way down, when I go from 81 to 79

**Comment by kamcpp** [comment]
OK, perfect. Thanks. And may I ask you side? Case 1 (inserting new alarm entries for repetition) or Case 2 (using the same alarm entry for repetition)?

**Comment by cakrit** [comment]
Case 2 - Same alarm, multiple notifications that I can see via the API (we'll show them on the UI too, a bit later).

**Comment by kamcpp** [comment]
> Yes, it's all described [here](https://docs.netdata.cloud/web/api/health/#health-management-api).

Thanks for this. Now, I have a better understanding about health API and its various functionalities.

**Comment by paulkatsoulakis** [comment]
> * Is it possible to silent a repeating notification? I guess yes like others
+1 on the need to have a suppression mechanism for the alarms. When you have an alarm defined is very handy to have a button "Suspend Alarming" with a duration and a reason for the suspension. That way you can stop notifying people when for example a maintenance activity is taking place and you know some alarms will fire but you don't have to notify everybody.  IMHO this should be part of a completely separate implementation though, not within the scope of this work

**Comment by cakrit** [comment]
> > * Is it possible to silent a repeating notification? I guess yes like others
> 
> +1 on the need to have a suppression mechanism for the alarms. When you have an alarm defined is very handy to have a button "Suspend Alarming" with a duration and a reason for the suspension. That way you can stop notifying people when for example a maintenance activity is taking place and you know some alarms will fire but you don't have to notify everybody. IMHO this should be part of a completely separate implementation though, not within the scope of this work

That's implemented already, we just need #3414 now.

**Comment by paulkatsoulakis** [comment]
> > > * Is it possible to silent a repeating notification? I guess yes like others
> > 
> > 
> > +1 on the need to have a suppression mechanism for the alarms. When you have an alarm defined is very handy to have a button "Suspend Alarming" with a duration and a reason for the suspension. That way you can stop notifying people when for example a maintenance activity is taking place and you know some alarms will fire but you don't have to notify everybody. IMHO this should be part of a completely separate implementation though, not within the scope of this work
> 
> That's implemented already, we just need #3414 now.

That is great! I didn't see it checked on the parent issue and i assumed is not done yet

**Comment by pschiffe** [comment]
The PR for this feature has been merged! https://github.com/netdata/netdata/pull/6309

**Comment by thiagoftsm** [comment]
As @pschiffe already said, I am closing this issue, because the solution was already merged. Thanks to everybody that helped us to develop this new feature for Netdata!
