### ISSUE TITLE
Feature Request: Native queueing for alerts.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#2984]
Partially inspired by the comment about rethinking alarm-notify.sh in #2976.

The general idea is pretty simple.  As of right now, if multiple notification channels are configured, and at least one of them succeeds, but the others fail, the notification will never get sent via the channels that failed.

Some of the programs used by alarm-notify.sh to send notifications actually handle this to at least a limited degree (`pd-send` for PagerDuty notifications does so for example), but most of them don't handle it beyond retrying immediately once or twice.

Given this, I think it makes sense to implement some kind of queueing mechanism either in alarm-notify.sh, or at some layer above that, that will track what channels have succeeded in sending the message, and which ones haven't, and retry on the ones that haven't up to some user configurable number of times (possibly including infinitely for those people who use a particular channel as a status log) at regular intervals.

The event queue system in Monit might be worth looking at for inspiration.  They only have one notification mechanism (e-mail), so it's simpler than what netdata would need, but the general design is still a reasonable starting point.

**Comment by ktsaou** [comment]
nice!

If you check `alarm-notify.sh`, it has become a mechanism that implements these:

1. configures `channels` (i.e. notification methods)
2. expands `roles` to `channel recipients`
3. It executes `curl` or `sendmail` to dispatch the notifications

Since we ended up running either `curl` or `sendmail`, I think we can move the code **inside the netdata daemon**.

So:

1. netdata will provide a new config file `notifications.conf` that will control channels configuration and recipients.
2. netdata will implement a simple queue in memory. Instead of running `alarm-notify.sh`, it will expand the list of recipients and add to the queue one notification for each recipient.
3. a new thread will now attempt to execute all the notifications in the queue, applying some retry policy.
4. if an alarm is cancelled, netdata will cancel any pending notifications in the queue for this alarm.
5. `alarm-notify.sh` could still be run, but we will remove from it all the notification channels we move inside netdata.

This will have the following benefits:

1. netdata will not depend on disk I/O for sending alarm notifications
2. netdata will retry notifications for all recipients on all channels
3. the same thread could push data to the central health service we want to build

But there will one drawback:

1. we will have to link netdata with `libcurl`.

**Comment by Ferroin** [comment]
I like the proposed implementation, but would suggest three slight differences:

1. Make the dependency on libcurl optional.  It's more efficient that calling out to the `curl` command directly, but some people may not want that.   Ideally, use `libcurl` if it's there, and if not fall back to just calling `curl` directly.  A build-time option to control usage would be an option too, but would be more likely to break existing installations when the upgrade gets pushed out.

2. Regarding the queueing, having the ability to set some upper limit on the number of alerts to be queued would be nice.  Even better would be tracking that based on the actual number of alerts, not the number of items in the queue (so, each alert gets counted once, no matter how many channels it goes out over), or possibly just providing separate queues for each channel and capping those.  While many users will want all alerts sent over all channels, it's not all that unusual to push all alerts over one channel, and specific subsets additionally over other channels (For example, I have all alerts sent via e-mail,  but I don't check e-mail much when I'm not at work, so I have really important stuff sent over pushbullet as well so that I actually notice it), and in such a setup it becomes hard to determine how many alerts will get queued before stuff starts getting dropped.

3. While I can understand not wanting to hit the disk most of the time, it would be nice to have some way to persist the queue across netdata restarts, and ideally have the option to not lose the queue if netdata crashes for some reason (not that I think it will, but it's always good to be prepared, especially if you're a prime OOM killer target).  For most users, defaulting to the queue being in-memory, and then saving to disk on shutdown (like netdata already does for the charts) should work for pretty much everyone, and then having an option equivalent to the `map` mode for the charts would cover the people who need to be certain alerts don't get lost.

**Comment by ktsaou** [comment]
nice!

1. we could supply an environment variable to `alarm-notify.sh` to disable all alarms that have been handled by netdata.

2. alarm floods are a problem. But I don't think an upper limit will solve the issue. We may miss important alarms. Another solution would be multi-alarm notifications (so 1 notification, many alarms), but this will make automation impossible. This is something we need to think a bit more.

3. alarms are already persistent in netdata (they are saved to disk as they happen). However, when netdata restarts, it will trigger the alarms again and send notifications.

**Comment by Ferroin** [comment]
1. Perhaps have it list which alarm mechanisms to disable instead of just hard coding them?  That way people could potentially migrate over to the new system slowly, and you could easily test specific alarm channels.

2. It really depends on how the queue is handled and what your intent is.  In my case, I'd rather have a limited queue size to avoid giving DoS attacks yet another means of resource exhaustion on my systems, but in most cases I'll still set the size to well over a thousand messages (given typical error rates I see when having problems, that's at least a week's worth of alerts).  Some people may be really focused on having all the alerts delivered regardless, other like me may not care about what happened a day or more ago.  Even for people who want to see all alerts, it's still useful to have something to prevent alerts from soaking up otherwise usable memory and potentially making a bad situation worse (and also possibly getting stuck in a loop if you've got an alert configured on memory usage).

3. Huh, I actually didn't know this.  I assume it's dependent on having the database saved to disk?

**Comment by ktsaou** [comment]
> I assume it's dependent on having the database saved to disk?

No, different things. There is a machine readable text file log for all alarms at `/var/lib/netdata/health/health-log.db`. A line is appended every time an alarm changes state. The file is rotated by netdata and is controlled by netdata.conf:

[health]
	in memory max health log entries = 1000
	rotate log every lines = 2000

So, netdata has a size limit for both memory and disk.

btw, the registry works the same way (machine readable text files, a little bit more complicated since it has a log and a db - the log is written in real-time, the db is a dump of the database that happens every a given number of log entries).

**Comment by Ferroin** [comment]
Carrying that over directly would completely take care of the reasons I had suggested limiting the queue size.

The only issue I can think of  other than the first item I listed is that `in memory health log entries` might get a bit complicated without tracking things independently for each channel (because you may end up with more alarms going to one channel than the others based on how you have things limited on each), though I don't think that splitting that config item to one-per channel would provide any practical benefit.

**Comment by ktsaou** [comment]
keep in mind that due to hysteresis (`delay` line) alarms are self-cancelling. So, if an alarm is raised and then cleared, unsent notifications will be cancelled. This already works. So, the alarm queue cannot become infinitely long. It will have at most one item per alarm per recipient, which for most cases it could grow to up to a few hundreds.

**Comment by Ferroin** [comment]
This is likely to need a significant redesign of `alarm-notify.sh`, so unless someone else wants this with high priority (or someone submits a PR that does it), I'm inclined to say it should wait for the hub.

**Comment by ktsaou** [comment]
> I'm inclined to say it should wait for the hub.

I agree...

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
