### ISSUE TITLE
No /etc/netdata

### ISSUE THREAD

**Issue by MuffinMedic** [netdata/netdata#3063]
I installed netdata using the kickstart script for the pre-compiled binary on Debian 9. Netdata is running OK, but I do not have a config file (or anything) in `/etc/netdata`. I am able to view the config file OK from the web (http:/.../netdata.conf), but cannot find the config on disk.

Adding it manually to /etc/netdata and restarting the service does not seem to fix the issue and the config remains unchanged when viewed from the web.

Thanks!

**Comment by dgadelha** [comment]
It's at `/opt/netdata/etc`.

**Comment by MuffinMedic** [comment]
@dgadelha Thank you. I forgot to mention earlier - I checked both `/opt/netdata/etc/netdata/netdata.conf` and `/opt/netdata/netdata-configs/netdata.conf`. Both files exist but do not contain the config - they say `# Get config from http://127.0.0.1:19999/netdata.conf`

**Comment by dgadelha** [comment]
When I installed a static build and didn't see stuff on /etc/netdata too, I uninstalled it then installed the normal kickstart. The problem was that also my config was empty. I had to copy the config from another server I had installed netdata and it worked without any problem.

**Comment by ktsaou** [comment]
> Both files exist but do not contain the config - they say # Get config from http://127.0.0.1:19999/netdata.conf

You are right, it is not downloaded by default.
You can get it from within the server with this:

```sh
/opt/netdata/bin/curl 'http://127.0.0.1:19999/netdata.conf' >/opt/netdata/etc/netdata/netdata.conf.new && cp /opt/netdata/etc/netdata/netdata.conf.new /opt/netdata/etc/netdata/netdata.conf
```

So, the netdata server generates this file. You can use `curl` to download it.

**Comment by tisc0** [comment]
Hi,
I found it pretty annoing actually, since doing the installation "manually" bring zeverything at the right place (/etc/netdata for example).
We started to install a bunch a servers like this, and I need to keep it standardized to write the documentation for colleagues.

Also, I just noticed the ./netdata-installer.sh is not working anymore with the --dont-wait ?! I might open a specific issue for this.

Thanks anyway for the projetct, it's fabulous.

**Comment by MuffinMedic** [comment]
Seconded what @tisc0 said.

I think it would be great if all install methods used the same configuration in `/etc/netdata` without needing to download it from the web.

**Comment by ktsaou** [comment]
ok, here it is #3136 
now both installers download the default config from netdata, and both generate the same default when they can't (i.e. instructed not to start netdata).

**Comment by paulfantom** [comment]
Closing as this should be fixed now. Please reopen if this is still valid.

**Comment by makutamatey** [comment]
please where can i locate the log files when the home is **/opt/netdata/etc**  instead of /etc/netdata? Thank you

**Comment by ilyam8** [comment]
@makutamatey  `/opt/netdata/var/log/netdata/`

**Comment by thiagoftsm** [comment]
Hello @jult ,

Netdata installs on different environments (Linux, BSD, Mac) and of course for Linux distributions we are installing on different flavors.

To simplify users life we modified our `kickstart-script.sh` recently to detect and install using `apt`, `yum`, `pacman` when it detects the environment. 

About `apt-get`, until I remember we have our repo and `Debian` also has their package for Netdata (@Ferroin and @ilyam8 , please, correct me if I am wrong). 

I hope I could clarify what is happening.

Best regards!

**Comment by jult** [comment]
I have been trying to get a bunch of nodes connected to a netdata cloud, using the install string the cloud instance provides, but none seem to work. It's honestly surprisingly messy to even get one node working. They all find an existing install, which frankly I can't (there's no /etc/netdata on them..), or they claim they can't claim a token that's already claimed. Either way, it puts me off using netdata yet one more time. Uninstalling it, using the advice giving here: https://learn.netdata.cloud/docs/agent/packaging/installer/uninstall does not solve the issues either. As I've seen quite a lot in distributed packages, it's like they're not actually being tested anymore, because all its users seem to use docker or other containers, or ready made VMs or such.. A bare metal server install is a pain now. Sorry, I think I've concluded netdata is not for me.
