### ISSUE TITLE
maintenance time and silence time

### ISSUE THREAD

**Issue by andreioss** [netdata/netdata#3187]
Hello!
It would be great to have such options for every separate alert.
So how I see such features:
we have some time intervals, when I need to not raise specific alerts on a host, maybe it's planned backup job that utilize disk every night, or another job because of which alert is raising.
So I want in these specific time periods specified alarms do not check and therefore - do not fire and notification.
In my opinion - it could be one more option to health configuration, with time range (for example):
silence_time: every day 03.00 - 07.00
silence_time: every Tuesday 12.00 - 14.00
and so on.
What do you think about it?
Is it possible to implement this?

**Comment by ktsaou** [comment]
Yes, this is needed. It comes up quite frequently.

**Comment by Saruspete** [comment]
Would need it too !

Is there a linked RFE or someone having already pushed / planned to push a PR for this ? Or a list of issues for this ? 
For the configuration part, a few questions : 
  * Is it possible to repeat a key multiple times (silence_time in the example published by @andreioss )
  * If not, what's the usual separator, a comma ? 
  * or should we make it as an expression, parsable by eval.c::eval_variable ?

Thanks,

**Comment by ktsaou** [comment]
@cakrit 	this is on our roadmap.

**Comment by cakrit** [comment]
My proposal is to do this in two steps:
Step 1 - No health checks at all during the specified period.
Step 2 - Support silencing of specific alarms.

For both use cases, I propose to build a mechanism that supports the iCalendar format. The basic idea is the following:
- I use any scheduling tool I like, to create a calendar for my maintenance times. There I can specify events any way I like (recurring or not, with exceptions for particular days etc). 
- I export the calendar in the iCal format and import it to Netdata (quickest way would be to manually put the file somewhere, it should be relatively easy to give an import button for it as well).
- Netdata uses libical to parse the file and determine if an event has started. It checks its duration and stops checking until the event ends.

Possible addition:
- Look for affected hosts (e.g. IPs) in the description field of the event, so that I can have a single calendar for all my hosts, with different maintenance times for each host.
- Look for alarm selectors (TBD what they will be) in the description field and only stop health checks for the alarms matching these selectors (to support Step 2).

We will also need to explicitly show in the alarm log that health checks are stopping for X minutes when the event starts and that health check has resumed after the event ends.

**Comment by cakrit** [comment]
One more thing. The iCal format enables us to quickly add a widget to display the maintenance times on the UI as well. We have countless options to do that.

**Comment by Ferroin** [comment]
Agreed on the iCal support.  Two thoughts for features that would be nice to additionally have:

* Support for fetching calendars from a given URL, with an option to refresh it on a regular basis.  This gives us easy integration with existing infrastructure (CalDAV uses iCal, and lots of companies use CalDAV), and allows for the reasonably common case of maintenance being scheduled ahead of time but not on a recurring schedule without requiring the user to update each Netdata instance when a new maintenance period gets scheduled.
* Support for somehow tagging events for a particular Netdata instance.  IOW, letting a user use one calendar that has different schedules for different nodes.

**Comment by cakrit** [comment]
> Support for fetching calendars from a given URL, with an option to refresh it on a regular basis.

I like this idea very much. We could actually leave the synch completely out of netdata and instruct people to use [vdirsyncer](https://github.com/pimutils/vdirsyncer). Then all netdata needs is the path/filename where it would look for the calendar.

> Support for somehow tagging events for a particular Netdata instance. IOW, letting a user use one calendar that has different schedules for different nodes.

This is actually what I meant with the "Look for affected hosts" part.
