### ISSUE TITLE
Alarm badge link escaping for disk paths in default dashboard

### ISSUE THREAD

**Issue by Dennis4b** [netdata/netdata#3253]
(On FreeBSD, but doesn't matter I think).

The alarm badges in the default dashboard for disks are rendered with the following code:
`var badge_url = NETDATA.alarms.server + '/api/v1/badge.svg?chart=' + alarm.chart + '&alarm=' + alarm.name + '&refresh=auto';`

yielding for example the following URL for the disk space of a root partition:
`/app/api/v1/badge.svg?chart=disk_space./&alarm=disk_fill_rate&refresh=auto`

The problem is the `/` (forward slash) in the path, causing the badge to not work.

The actual metric, which is used in charts, is named `disk_space._` (i.e. path separators are replaced with underscores), so I assume there is an escaping step missing somewhere, but I'm not familiar enough with the code to speculate what the correct place to fix this is.

Note also that the "jump to chart" link with action `scrollToChartAfterHidingModal` does work because the chart_id is flattened with `NETDATA.name2id` so the jump goes to the `div` with `id ` `chart_disk_space__` either way.

**Comment by ktsaou** [comment]
Hi,

you are right. this is a bug.

however the bug is that the HTTP request parser should not consider that `/` as a path. It should have stopped parsing `/` as path at the `?`.

**Comment by Charanjet** [comment]
Can anyone please help me to create new alarms and new charts i m looking for a complete guidance.

**Comment by ktsaou** [comment]
traced it to find the issue.

The bug is at the internal web server of netdata. It parses the URLs like this:

1. a request comes

2. it checks it received the whole of it (it searches for `\r\n\r\n` - i.e. an empty line as defined in the spec)

3. BUG 1: it decodes the whole URL. This is a bug since any `/` or `?` URL encoded will be decoded before actually parsing the URL. To work properly it should decode the URL part by part (i.e. first split it in its parts and then decode each part of it). **The way it is now, URL encoding cannot be used to encode characters that are URL control characters (`/`, `?`, `&`, `%`).** Even when URL encoded, these character will still play an important role in URL parsing (although they are escaped).

4. BUG 2: it does not separate URL `path` from URL `query string`. It treats the whole URL as a continuous string, separated by `/?&`, which of course leads to bugs like the one we face here.

So, the right flow should be like this:

1. receive the request

2. make sure it received the whole of it

3. split the path from the query string

4. URL decode the path to find the API command or the filename to be served

5. split the query string in its parts (separated with `&`)

6. for each part of the query string, split it at the `=` sign to find the `name` and `value` and decode both of them.

I think the whole HTTP parser needs to be rewritten.

In the mean time I'll attempt to make a patch to properly use separators depending on the position of the parsing.
