### ISSUE TITLE
Add prometheus format for alerts

### ISSUE THREAD

**Issue by Kami-no** [netdata/netdata#3272]
It would be nice to monitor alarms state through prometheus =)

**Comment by ktsaou** [comment]
hm... interesting.
Does prometheus has a special format for it, or they are just metrics like all the rest?

**Comment by n0guest** [comment]
> Does prometheus has a special format for it, or they are just metrics like all the rest?

As i remember Prometheus by himself doesn't do anything except sending alerts to AlertManager (+periodic repeats, see https://github.com/grafana/grafana/issues/7481). Looks like it's just a webhook (w/json payload) plus "retries" while alert is still active (e.g. loop in thread).

So, this issue isn't about sending alerts to Prometheus, it's about sending alerts to AlertManager from Prometheus project:

- https://prometheus.io/docs/alerting/alertmanager/
- https://github.com/prometheus/alertmanager

But it would be great to have such feature in Netdata.

**Comment by Kami-no** [comment]
The question is to make netdata not only export raw metrics but also its internal alerts status =)
For example list of all alerts and their status (firing or not).

**Comment by n0guest** [comment]
> The question is to make netdata not only export raw metrics but also its internal alerts status =)

And this can be done only via integration with AlertManager (as I described before).

**Comment by Kami-no** [comment]
Your idea is to send alerts through AlertManager but mine is to get from netdata alerts and their status as metrics with Prometheus.

**Comment by andreioss** [comment]
> Your idea is to send alerts through AlertManager but mine is to get from netdata alerts and their status > as metrics with Prometheus.

By the way, I think both of these ideas are great!

**Comment by n0guest** [comment]
> Your idea is to send alerts through AlertManager but mine is to get from netdata alerts and their status as metrics with Prometheus.

So, you just want to monitor "current alerts" on your Netdata nodes? o_0
Could you, please, describe your "usage case"? Just interesting, because i'm not fully understand how it could be usefull (may be your explanation would show it). Do you want to add Prometheus rules for those metrics and send alerts based on them?

Thanks.

**Comment by Kami-no** [comment]
netdata might be deployed as is (it has nice basic preset alerts and all alert are monitored locally). You just need to add a centralized control panel and alerting solution. It might be light separate installation of Prometheus.

But to monitor a whole cluster there might be one more installation that will gather all metrics and process them the way you like with more resources.

**Comment by paulfantom** [comment]
Just for clarification. Prometheus is in fact **creating** alerts and sends them to alertmanager which **routes** alerts. So adding an option to netdata to send alerts to alertmanager would mean that alertmanager could take care of things like:
- alert resending
- routing alerts to different groups on various conditions
- actual alert sending
- silencing alerts
- deduplicating alerts

Basically if there was an option to send alerts to alertmanager this would mean that alertmanger would **be** the control plane for alerts. @Kami-no you don't need prometheus to scrape some new metric just to create rule on this and send alert to alertmanager.

**Comment by ktsaou** [comment]
Seems pretty simple: https://prometheus.io/docs/alerting/clients/

Can you make a PR? It should be pretty simple to modify alarm-notify.sh

**Comment by paulfantom** [comment]
I can try, after I get what is going on in this huge shell script :smile:

One more thing, alertmanager can take care of sending alerts to other communication mediums (slack, hipchat, mail, etc.) but clients are expected to resend alerts every 30s to 3min. And since netdata cannot resend alerts now (#2956) I wonder what will happen if this condition won't be met. @mxinden could you help?

**Comment by mxinden** [comment]
As [mentioned above](https://prometheus.io/docs/alerting/clients/) as long as an alert is active it needs to be periodically send to Alertmanager.

The interval can be configured via the Alertmanager [`resolve_timeout`](https://prometheus.io/docs/alerting/configuration/):

``` yaml
  # ResolveTimeout is the time after which an alert is declared resolved
  # if it has not been updated.
  [ resolve_timeout: <duration> | default = 5m ]
```

More theoretically Alertmanager is a system translating level-triggered events to edge-triggered events. You can find more on this [here](http://gengnosis.blogspot.com/2007/01/level-triggered-and-edge-triggered.html?m=1).

Fixing this in a hacky manner by making `resolve_timeout` very high would only work if netdata sends resolved notifications to Alertmanager. Otherwise Alertmanager would alert indefinitely.

If netdata can resend notifications periodically Alertmanager seems to be a great fit.

**Comment by paulfantom** [comment]
It looks that we first need #2956 before doing this.

**Comment by Kami-no** [comment]
I just want a dashboard in grafana with all alerts from all installations of netdata. To collect status of alerts I would like to use prometheus as lists of metrics with status 0 for "ok" and 1 for "triggered".

Also than you can anyway create rules for alertmanager based on "triggered" status.

**Comment by paulfantom** [comment]
@Kami-no that's what [Prometheus AlertManager datasource](https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource) is for.
No need to create some artificial metric which shouldn't even be a metric in the first place.

**Comment by Kami-no** [comment]
It's just point of view: collect raw data or processed. State 

You can scrape alerts from netdata as metrics and then send them to alertmanager or send alerts from netdata directly to alertmeneger and scrape them to prometheus as metrics.

**Comment by Kami-no** [comment]
Ok, np.

**Comment by petarkozic** [comment]
And on the end, can we use alertmanager with netdata. I'm using prometheus for scrape and prometheus storage for storing metrics from netdata, what is perfect.
I know that netdata have own alerting system.
Can we than send alert from netdata to alertmanager as on alerta ? If not yet can we expect something... ?
Thanks.

**Comment by petarkozic** [comment]
I know that I can to create rule feom prometheus, but I don't understand
well. Can you write me here one example rule from netdata how to need to
look in prometheus. I ask that because I thi k netdata have some own
variable. Maybe I mistake, but please send me one example.
Thank you !

**Comment by paulfantom** [comment]
@petarkozic I don't think this is a thread for this kind of support.

Nonetheless, here is an example alert definition:
```yaml
alert: ExampleNetdataAlert
expr: netdata_cpu_cpu_percentage_average > 90
labels:
  severity: warning
annotations:
  description: '{{ $labels.instance }} needs attention due to this example alert'
```
All netdata metrics are prefixed with `netdata_` in prometheus. You can see them by writing `netdata` in [prometheus graph console](http://demo.cloudalchemy.org:9090/graph) and waiting a second for autocompletion to kick in.

**Comment by petarkozic** [comment]
Hi @paulfantom Thank you on your answer. You don't understand me. I know how to write rules for prometheus. But I don't know how to use exactly netdata alarm into prometheus alert rules.

On example how need to look this netdata . alarms in prometheus:

<img width="897" alt="screen shot 2018-07-09 at 10 50 31 am" src="https://user-images.githubusercontent.com/17702869/42440452-176d27d0-8366-11e8-880d-3adb4a46183f.png">

**Comment by paulfantom** [comment]
This is still not a thread for that.

You want to take netdata alert rules and implement them in prometheus? If yes, then I cannot help you, since I don't know how to do this.

As for attached netdata alert example, `$this` would probably refer to `netdata_system_softnet_stat_events_persec_average` in prometheus.

**Comment by petarkozic** [comment]
Ok, thank you in anyway @paulfantom

**Comment by wales** [comment]
Hey, now that #2956  has been implemented is this now able to go ahead?

**Comment by cakrit** [comment]
Yep, looks like you're right, we can indeed progress on a PR for a new alarm notification mechanism. It's just that in the documentation of the notifications for alertmanager we should mention that repeating alarms need to be enabled. Is anyone from the community willing to pick this up? It should be fairly straightforward now.

**Comment by ilyam8** [comment]
> The question is to make netdata not only export raw metrics but also its internal alerts status =)
For example list of all alerts and their status (firing or not).

There is [python alarms collector](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/alarms#alarms---graphing-netdata-alarm-states-over-time), so we can export netdata alarms statuses as metrics.

**Comment by intelfx** [comment]
Why was this closed?

**Comment by ilyam8** [comment]
Hi @intelfx 

The request is

> It would be nice to monitor alarms state through prometheus
> I just want a dashboard in grafana with all native alerts from all installations of netdata. I would like to use prometheus to collect status of alerts as a lists of metrics with status 0 for "ok" and 1 for "triggered".

As I mentioned in https://github.com/netdata/netdata/issues/3272#issuecomment-768966604 it is already possible, because we added alarms status collector.

I read the discussion and it was sidetracked to:
 - Can we than send alert from netdata to alertmanager as on alerta ?
 - How to use exactly netdata alarm into prometheus alert rules.

**Comment by intelfx** [comment]
Ah, I see. I (mis-)understood the original feature request similar to the second commenter here (https://github.com/netdata/netdata/issues/3272#issuecomment-357691575), but apparently this is not what the OP wanted.

By the way, what about the _alertmanager_ format for Netdata alerts?
