### ISSUE TITLE
Collect data without installing Netdata.

### ISSUE THREAD

**Issue by Knittens** [netdata/netdata#3313]
Hey,
I've been wondering, is it possible to collecting Data from for example Server 2 without installing netdata on it? We dont want to install it on every single machine, but I would like to know if I could just collect the metrics from a server and show it in a custom Dashboard which is running on Server 1 and has netdata installed on it.

**Comment by Ferroin** [comment]
Not with Netdata.  In theory you might be able to handle this by setting up SNMP on all the other servers and configuring netdata to query that, but that will greatly limit what data you can collect and will probably require you to install software on every system anyway (very few Linux distributions ship SNMP support as part of their base install).

If you absolutely have to avoid installing it on every system (which shouldn't be much of an issue if you're managing things centrally with something like Ansible or Puppet), then you should probably look into a centralized network monitoring framework like Nagios (but even then you do have to do some work on each system so that Nagios can collect the data).

**Comment by ktsaou** [comment]
Hi,

As @Ferroin states there is no agentless monitoring in Linux. In all cases an agent is required.

There are a few solutions that call "agentless monitoring", their ability to ssh to the server and collect metrics. This, of course, has many more issues.

Other solutions call "agentless monitoring", their ability to execute code via cron jobs. So instead of running an agent, programs get spawned from cron every minute or so, to collect the metrics. These are a lot less efficient and usually not very detailed.

Then there are solutions, including netdata, that can collect remote **application** metrics, for example by connecting to a remote database server, a remote web server, etc to fetch the metrics the application provides. netdata can do this.

In general though, installing netdata on all hosts is the only solution that will provide the maximum of insights at a good resolution. This is the preferred method.

If you work on the cloud, this is mandatory.

Cloud VMs have all sorts of issues and relying on anything else than the host itself for collecting the metrics, is a bad idea.

Cloud VMs may loose their disks, their network interfaces, even one or more of their CPU cores. Running netdata inside the VM, is the only solution that could provide insights during that time.

**Comment by paulfantom** [comment]
By design netdata should be installed at all monitored hosts.
