### ISSUE TITLE
Security concerns when running downloaded shell scripts

### ISSUE THREAD

**Issue by ScaredyCat** [netdata/netdata#3551]
Please stop encouraging people to download and execute scripts directly, it's a horrific idea. 

> bash <(curl -Ss https://my-netdata.io/kickstart.sh)

**Comment by ktsaou** [comment]
Well, you are right, but I cannot do this, for the following reasons:

1. ideally installation should be taken care by the distros. However, the main distros fail to keep up to speed. It has been 2 years since the first release of netdata and still they haven't included it (there are exceptions, like arch linux and gentoo that added netdata almost in no time).

2. Before this one-liner, most tickets in this repo were about installation issues. This required a tremendous amount of work, helping users get through the installation procedure.

3. Such one-liners are extremely common - most commercial monitoring solutions provide similar instructions.

4. There are alternative ways of installing netdata - you are not forced to use this.

So, you are right, such one-lines are bad practice. But, we have to use them, mainly due to the amount of support required without them.

Keep in mind that I am seeking for help to setup PPAs or whatever else needed for installing binary packages on major distros #2728

**Comment by FedericoCeratto** [comment]
@ktsaou running an installer script is not wrong per se. The problem is encouraging users to run a file that can change at any time with no warning and/or cannot easily verified. 
See for example https://www.idontplaydarts.com/2016/04/detecting-curl-pipe-bash-server-side/

You can deliver a file from a dedicated branch or repo on GitHub where people can easily check its history. The URL can point to a specific tag or commitish.

**Comment by ktsaou** [comment]
So, you say we should just change the URL to point to github?

**Comment by FedericoCeratto** [comment]
Users already have to trust GitHub security when pulling the sources and getting install instructions from the wiki.
At least, using:
```
curl -sS https://raw.githubusercontent.com/firehol/netdata/e8915e26537615282003d6baf094d59712c9b4f1/kickstart.sh -o kickstart.sh
```
...they are a "known" file from a known location.

GPG-signing tarballs and the kickstart script would be another improvement.

**Comment by paulfantom** [comment]
So instead 
```sh
bash <(curl -Ss my-netdata.io/kickstart.sh)
```
use
```sh
curl -sS https://raw.githubusercontent.com/firehol/netdata/master/kickstart.sh | bash
```
?

As for GPG signing tarball, I don't think I know any project which does that. SHA checksum is common but GPG - not so much.

**Comment by ktsaou** [comment]
> curl -sS https://raw.githubusercontent.com/firehol/netdata/master/kickstart.sh | bash

This removes stdin from bash, so the script cannot have user input.

> As for GPG signing tarball, I don't think I know any project which does that. SHA checksum is common but GPG - not so much

So, how this will work? The script will check itself with a signature it downloads from the server?
I don't see any value to it.

The only possible solution would be to instruct the users the check the signature of the script before running it, but this would require to save the script and the signature and check the downloaded files with an extra command you will run.

**Comment by paulfantom** [comment]
I wasn't clear enough. I know about GPG checking of packages from repositories (apt, yum, and almost every package manager does it), problem is that we are not releasing package to the repository. We are releasing tarballs. And I meant projects which do the same, when saying that "I don't think I know any project which does that".

Sorry for not being clear on that.

**Comment by nodiscc** [comment]
This is what I use instead of relying on the insecure `bash <(curl...` recommendation:

```
$ wget https://github.com/netdata/netdata/releases/download/${netdata_version}/netdata-${netdata_version}.gz.run
$ ./netdata-${netdata_version}.gz.run --check
$ ./netdata-${netdata_version}.gz.run --accept -- --dont-start-it --disable-telemetry

**Comment by paulfantom** [comment]
@nodiscc what you are doing is not that much different from `bash <(curl...` as you solely rely on binary downloaded from the internet to do everything. In the process, you described there is no external validation of binary authenticity (via GPG) or at least of its coherency (via checksum). Essentially you are adding yourself more work without getting any benefits from it.

**Comment by prologic** [comment]
Thank you reporting. We believe at this time the best possible way for users to instal the NetData Agent that have security concerns with running the one-lineer lsited on the website is to use our [Native Packages](https://packagecloud.io/netdata/netdata) built and hsoted by [PackageCloud](https://packagecloud.io).
