### ISSUE TITLE
Option to hide detailed description of charts

### ISSUE THREAD

**Issue by ko-zu** [netdata/netdata#3564]
It can be nice to have an option to hide descriptive information sitting over every charts.

For example, CPU chart has
> Total CPU utilization (all cores). 100% here means there is no CPU idle time at all. You can get per core usage at the CPUs section and per application usage at the Applications Monitoring section.
Keep an eye on iowait
(11.6%). If it is constantly high, your disks are a bottleneck and they slow your system down.
An important metric worth monitoring, is softirq
(0.00%). A constantly high percentage of softirq may indicate network driver issues.

I am sure It can be helpful for one's very first visit. However, it is consuming too much space that could be left for other useful and dynamically updated information.

I am now hiding some div elements by classes on my userstyle. Unfortunately some of descriptions cannot be removed by css as they are bare text nodes that are not wrapped by selectable elements.

Thanks for consideration.

**Comment by Ferroin** [comment]
Probably of interest to people discussing #3536.

I'd also like for this to be an option, preferably something that could be quickly toggled but still persists across visits from the same browser.

**Comment by ktsaou** [comment]
ok, I can do this...

**Comment by TDGalea** [comment]
Since there still seems to be no global option for this, here's the way I did it:
Open the configuration file (/opt/netdata/etc/netdata/netdata.conf) (download the default if necessary).
Replace all commented out lines such as these:
`# context = cpu.cpu`
with
`context = no`

Assuming nano, you can instantly do this to all lines by using the Replace search (CTRL + \) under the following criteria:
Replace:
`# context = `
with
`context = no # `

That way, the line will have the "context = no" part active, while the original remains on that line, but commented out.

**Comment by ilyam8** [comment]
Context is used by alarms pretty often

**Comment by TDGalea** [comment]
Then there really needs to be a global option to disable descriptions.
I don't see myself using alarms at any point so if I have broken their functionality, that won't bother me personally.

**Comment by markwone** [comment]
that   a good idea ! look forward to

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
