### ISSUE TITLE
golang orchestrator

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#3589]
@ktsaou 
`python.d.plugin` heavily use threading which [sucks](https://archive.org/details/pyvideo_588___mindblowing-python-gil).
**Workaround**: use another language. 

I looked at the ~~rust~~ `golang` (noob friendly, sexy, built-in concurrency) and found it **awesome** :smiley: 
I love it and i want to practice in it.

So... I'm working on `netdata-go.plugin` (current name, can be changed)
In my tests it consumes much less memory then `python.d.plugin` (better faster stronger in all ways).

What it does?
Well, it does the same as `python.d.plugin` -  It supervisor other modules.

Current status: **all** `python.d.plugin` functionality (except some framework services) implemented. I have to test it hard and add some comments/descriptions. And 1 module 100% ready - `portcheck`.

Since it's mimics `python.d.plugin` it's modules looks as python ones :smile: 

![screenshot_20180330_172644](https://user-images.githubusercontent.com/22274335/38130861-9603cc6e-343f-11e8-9596-b9678ceabc75.png)

**Main question**:  What should I do with the configuration files?

The plugin consists of plugin itself + modules (no conf files)
![screenshot_20180330_173302](https://user-images.githubusercontent.com/22274335/38131049-6ccaadda-3440-11e8-982e-ececa7e82b33.png)

Since it's **netdata**-go plugin it expects to find conf files in same directories as  `python.d.plugin` (`NETDATA_CONFIG_DIR` for itself and `NETDATA_CONFIG_DIR` + `go.d ` (?) for modules)

How should i name it?

My plan is to rewrite some modules (first candidates are `portcheck` (done), `httpcheck`, `web_log`).

What do you think?

**Comment by ktsaou** [comment]
Wow! This is really nice.

I think it should be named `go.d.plugin` and its configs should go at `${NETDATA_CONF_DIR}/go.d/`.

Since a lot of modules may exist under different plugin supervisors, I think we need to find a way to prioritize them a bit. Example, use go, if it does not exist use python, if it does not exist use bash. I guess we could implement some kind of election at `/var/cache/netdata/plugins.d` and allow admins to influence this election. Ideas are welcome.

I am not familiar with `go`. Does it compile? Can we distribute binary versions or the target system needs go installed?

**Comment by l2isbad** [comment]
> Does it compile? Can we distribute binary versions or the target system needs go installed?

Yes, it compiles. We can distribute binary versions.

**Comment by ktsaou** [comment]
And will it be one binary with all modules in it or multiple binaries?

**Comment by ktsaou** [comment]
What about shared libraries or third party go libraries?

**Comment by l2isbad** [comment]
> And will it be one binary with all modules in it or multiple binaries?

One with all modules, libraries **and** third party go libraries.

The only third-party library it uses atm is https://github.com/l2isbad/toml (modified version of https://github.com/naoina/toml).

**Comment by Wing924** [comment]
Go is very good for such tasks. You can even write all plugins with go and make a single binary. :)

**Comment by l2isbad** [comment]
@Wing924 that is the plan.

Ok, i added colorized output in `debug` mode.
After that, I wanted to use it somewhere else...

@ktsaou 
I added `info` command line flag. It prints brief info about the whole plugin (list of available modules, etc.) or more detailed info about a specific module.

Each module must implement `Description() string` and `SampleConfig() string` methods. 

![screenshot_20180401_170654](https://user-images.githubusercontent.com/22274335/38171182-1f55907a-35cf-11e8-9482-cb797abe54b7.png)

So we can build a module info. Result:

![screenshot_20180401_165339](https://user-images.githubusercontent.com/22274335/38171106-ac454c70-35cd-11e8-9951-74386a846717.png)

What do you think?

**Comment by ktsaou** [comment]
nice!

It would be nice if you could read the config and re-generate it. Like netdata.conf. So you could use the netdata way of getting the latest config file, while all current config options are into it.

**Comment by Wing924** [comment]
@l2isbad 
I don't understand the Description() string and SampleConfig() string.
Python plugins have the same string?

If you just mean yaml config files, I think you can use YAML in Go.
https://github.com/go-yaml/yaml

Don't afraid to add 3rd-party libraries.
Go use `dep` command to manage dependence and download the source code to `./vendor` directory.

**Comment by l2isbad** [comment]
> Python plugins have the same string?

no

> If you just mean yaml config file

I don't get why you are talking about `yaml`. Plugin uses [toml](https://github.com/l2isbad/toml).

> I don't understand the Description() string and SampleConfig() string.

The idea is to provide all needed for specific module info via cmd line.
 I **don't** like current python.d plugins configuration files format. Conf files are bloated. Every file has tons of duplicate info (**which nobody reads**).

I believe conf files should consist of... conf directives only. Details wiki/cmd line.

**Comment by l2isbad** [comment]
Actually i saw `Description SampleConfig` thing in [telegraf](https://github.com/influxdata/telegraf) and i like it :smile:

**Comment by Ferroin** [comment]
So, three specific comments on this:

1. Please make sure there's some way to set an arbitrary number for `GOMAXPROC`., since Go doesn't always reliably detect if it's been restricted to a subset of the system's CPU cores  Something in `netdata.conf` probably makes the most sense here.
2. There should ideally be support for running third-party Go plugins.  We kind of already can do this with the regular plugins directory if they use the native API, but it would be nice to specify secondary plugin binaries that use the same API that `go.d` plugins do.
3. Python's threading limitations could also be worked around by just adapting to use the `multiprocessing` library.  Assuming you use a pre-forked `multiprocessing.pool.Pool`, you can easily eliminate most of the costs of using processes instead of threads.  Note that I'm not saying adding Go support is a bad idea, just that alternatives should probably be explored, especially given that Go isn't quite as portable as C and Python.

**Comment by ktsaou** [comment]
> I believe conf files should consist of... conf directives only. Details - wiki/cmd line.

@l2isbad I believe you should re-think this. The main problem with documentation is that people have to search for it. And even once found, there may be discrepancies due to versioning.

Providing all the information right in the place it should be used is ideal. Minimal documentation elsewhere, all the information you need in the config file you need to edit.

Heavily commented conf files may be annoying for power users that know what to do, but it is the best way I can think for new or casual users.

**Comment by Ferroin** [comment]
Adding further to the discussion of config files:  It's trivial to strip comments from a config file if you want to. (It takes maybe a dozen lines of Python code, or two commands in `vi`).  It's not trivial  to add documentation in comments by hand.

**Comment by l2isbad** [comment]
Work was postponed because I decided to read some books/go documentation.
btw all go books are kind of sucks (authors are great programmers etc, but books are not great imo).

**Comment by Wing924** [comment]
@l2isbad @ktsaou I can help you about the go plugin.

**Comment by Wing924** [comment]
@ktsaou @l2isbad Shall I take over this work?

**Comment by l2isbad** [comment]
i want to finish the [go101](https://go101.org/article/101.html) book before i continue

**Comment by paulfantom** [comment]
@l2isbad do you still want to use toml for config? This way whole project ends up using many configuration languages as it already uses INI, YAML, json, and a custom config for BASH modules. Adding one more is a tragedy from UX point of view. I think the trend should be in the other direction, trying to settle for less config languages and not adding another one.

**Comment by l2isbad** [comment]
sounds reasonable :smiley_cat:

**Comment by l2isbad** [comment]
https://github.com/netdata/go.d.plugin

**Comment by ilyam8** [comment]
The issue resolved. We have [go.d.plugin](https://github.com/netdata/go.d.plugin). It's stable and works well according tests.

Our next steps:
 * add it to netdata (i wil open a new issue) (high priority)
 * add new and shiny `web_log` with high load support to `go.d` :+1:  (high priority)
 * start process of moving python modules to golang
 * add new modules!

**Comment by gmosx** [comment]
Great job ilya ;-)
