### ISSUE TITLE
fping plugin on FreeBSD

### ISSUE THREAD

**Issue by Zolotkey** [netdata/netdata#3595]
Hello,

I have netdata v1.9 installed via ports on my FreeBSD 11.1 host and I couldn't get fping to work at first. I was able to finally get some time to debug the issue. The plugin is backing out of the directory structure one too many times so it fails to find the config file. It seems to be this commit( #2337) that killed it.

I had to remove a set of "../" so it looks like this below to work on my FreeBSD machine.

/usr/local/libexec/netdata/plugins.d/fping.plugin
line 132
```[ -z "${NETDATA_CONFIG_DIR}" ] && NETDATA_CONFIG_DIR="$(dirname "${0}")/../../../etc/netdata"```

with 4 ../, it goes to /usr.

**Comment by ktsaou** [comment]
Yes, this happens when you run the plugin by hand and you have installed netdata without using the `--install` option of the supplied `netdata-installer.sh`.

When it is run by netdata, the variable `NETDATA_CONFIG_DIR` is properly set, so it works when run under netdata.

I guess the solution would build these files with the make system, so they will have the right paths hardcoded into them...

**Comment by cosmix** [comment]
@zolotkey if this still an issue please open a new one.
