### ISSUE TITLE
Persistent colors for dimensions (especially apps).

### ISSUE THREAD

**Issue by Elrique64** [netdata/netdata#367]
I'm wondering if it's possible to set specific colors for each of the monitored apps I have set up for NetData to track.  Knowing that a given "color" means XYZ app could make it easier to monitor the app's usage.

Every time I refresh the page, the apps I want to monitor change colors, so it makes it hard sometime to see what a specific app is using for resources.

This would be a "nice to have" so if you have the time to set it up, that would be great.

**Comment by ktsaou** [comment]
hm... selecting a color for a specific dimension using the default dashboard is tough.

Currently the dashboard makes the most to keep the dimension colors fixed across chart refreshes. As you may have noticed, the apps charts appear to have a variable number of dimensions. This happens because of the setting "Which dimensions to show? = Non Zero" (at the settings menu of the dashboard).

Internally there is a fixed set of dimensions controlled by `/etc/netdata/apps_groups.conf`. But many of them are just zero, so because of the "Non Zero" setting they are not transferred to your browser. Your browser has a fixed list of colors and starts giving colors to dimensions in the sequence it sees them. So while you don't refresh the dashboard, the colors are fixed. But if you refresh it then yes, their colors are remapped.

One quick fix is to set "Which dimensions to show? = All". Under this setting, the dimensions will (mostly) have fixed colors. There is only one reason for them to change: you start a new application that was never running before and you refresh the dashboard.

Hm... I'll mark this a "bug". I'll think of a way to fix the colors somehow...

**Comment by ktsaou** [comment]
I tried to replicate this with the latest version of netdata, but I couldn't.

I see in the code that I had already fixed it: https://github.com/firehol/netdata/blob/84d43b8679c21370ef65ee897ebb3170f07f8e77/web/dashboard.js#L2136-L2142

Could you please update your netdata and check if is works for you now?

**Comment by ktsaou** [comment]
Once you update it, please press Control-F5 to refresh the dashboard, to force the browser fetch the latest files.

**Comment by tx7** [comment]
Can we have an option to change the chart & gauge color from the web GUI instead go to the .conf to change it?

Thanks.

**Comment by ktsaou** [comment]
I a changing this to a feature request.
netdata already gives the same color to the same dimension across multiple charts, but it the html interface does not allow setting specific colors to dimensions (it is more like auto-assignment, that can be influenced, but cannot be overwritten for a specific dimension).

**Comment by nodiscc** [comment]
I have a custom netdata plugin [[1](https://gitlab.com/nodiscc/netdata-logcount)] reporting the number of info/warning/error messages in logs over the last 5 minutes. In my case, automatically applied chart colors are counter-intuitive (warnings in red, errors in green), I wish there was a way to hardcode chart colors in the plugin itself.

![COLOR](https://user-images.githubusercontent.com/3950390/78457383-418c2980-7699-11ea-8d0f-b9b830dac3b6.PNG)

**Comment by ilyam8** [comment]
From what i know it is only possible in custom dashboard.

On the main dashboard colors are like: good, bad, good, bad ... (green, red, blue, orange, ...).

Make it one chart:
- info
- error
- warning

**Comment by ilyam8** [comment]
But yes, we need to fix it somehow.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
