### ISSUE TITLE
Plugin for DRBD 

### ISSUE THREAD

**Issue by jyotirbhandari** [netdata/netdata#3689]
I have been using netdata for most of my things, but I would like to have metrics for DRBD. Currently either I have to use script or some other tool such as node exporter for DRBD.

**Comment by ktsaou** [comment]
Hi,

drbd stats are found in a proc file: https://docs.linbit.com/doc/users-guide-83/ch-admin/#s-proc-drbd

The page explains in detail what each metric means.

This is the prometheus plugin in go: https://github.com/prometheus/node_exporter/blob/master/collector/drbd_linux.go

This is relatively easy, even in C (inside netdata daemon).
If anyone is willing to take over it please do. I'll help...

**Comment by giang-nghg** [comment]
@ktsaou Hi I would like to take this issue. Is the general idea is to write a plugin (similar to Prometheus' DRDB one) that collect the stats from the DRDB proc file?

**Comment by ktsaou** [comment]
Which language would you like to use?

If you know C, it should be pretty simple to do. I'll help.

If you know python, I think @l2isbad can give a few directions.

If you want to work with go, you have 2 options: a) write a standalone plugin for it or b) cooperate with @l2isbad to be integrated in the first set of plugins he writes in go.

**Comment by giang-nghg** [comment]
@ktsaou I'd like to use C, please. Thanks.

**Comment by ktsaou** [comment]
ok nice.

Then, you will create 1 new file `src/proc_drbd.c`. Add it to src/Makefile.am at the place all other `proc_*.c` files are.

Your file needs to expose only one 1 function: `do_proc_drbd()`. You have to add this function in `src/plugin_proc.h` (there are many other similar functions there) and also add it to `src/plugin_proc.c` (also many others are already there).

With the above you added a hook in the `proc` plugin to run your function every second, much like all the other proc modules. You can monitor the performance of your code at the netdata proc module (at the end of the dashboard).

Then study a bit the other `proc_*.c` files to see how they work. You will most probably copy one that seems similar to what you need to do and adapt it.

These are key info you need to know:

1. `procfile` is a system that automatically parses and tokenises proc files. It is smart enough to keep the file open, seek to it to let the kernel know we need to re-read the whole of it, it reads the file with one read operation (it adapts its buffers through iterations to avoid memory allocations) and it tokenises the whole of it in one go. You should use this (all other modules do).

2. `arl` is an adaptive resortable list. Its purpose is minimize searches. So when you have list of name-value pairs, arl learns the order they appear in the file, so that each iteration will do the absolute minimum to parse it. Of course it can adapt to changes too (ie if the kernel decides to add or remove an element, it will find out and adapt).

Since the file is like this:

```
cat /proc/drbd
version: 8.3.0 (api:88/proto:86-89)
GIT-hash: 9ba8b93e24d842f0dd3fb1f9b90e8348ddb95829 build by buildsystem@linbit, 2008-12-18 16:02:26
 0: cs:Connected ro:Secondary/Secondary ds:UpToDate/UpToDate C r---
    ns:0 nr:8 dw:8 dr:0 al:0 bm:2 lo:0 pe:0 ua:0 ap:0 ep:1 wo:b oos:0
 1: cs:Connected ro:Secondary/Secondary ds:UpToDate/UpToDate C r---
    ns:0 nr:12 dw:12 dr:0 al:0 bm:1 lo:0 pe:0 ua:0 ap:0 ep:1 wo:b oos:0
 2: cs:Connected ro:Secondary/Secondary ds:UpToDate/UpToDate C r---
    ns:0 nr:0 dw:0 dr:0 al:0 bm:0 lo:0 pe:0 ua:0 ap:0 ep:1 wo:b oos:0
```

I think you will need:

1. a structure to keep each record. The above file has 3 records. They can be kept in a linked list or an array. Your call.

2. Your will need 2 ARLs: 1) for the first line of each record, 2) for the second line of each record. The ARL will ensure that if a past or future kernel decides to re-arrange the fields, your code will work and will be optimal.

This file uses `:` as separator, so make sure you add this to procfile separators parameters.

My suggestion is to adapt `proc_net_snmp.c`, since this a somewhat similar format (the name-value pairs are horizontal in the file, not vertical).

**Comment by giang-nghg** [comment]
@jyotirbhandari: Hi. I was wondering, do you have a relatively non-trivial DRBD setup (VM or Docker) that I can use as a test environment? Thanks a lot!

**Comment by jyotirbhandari** [comment]
@giang-nghg: Hi, I am using the complete setup in prod, and its difficult for me to replicate it somewhere else as of now (VM or Docker).

You can refer to the mentioned link for quick setup of DRBD -- http://www.learnitguide.net/2016/07/how-to-install-and-configure-drbd-on-linux.html

I would also recommend you to use DRBD version 8.4 as documented in the link rather the latest version 9.x

**Comment by giang-nghg** [comment]
Hi @ktsaou It's been a while. I'm still working on this issue (I was busy since May but I got time to do it now). There's a couple of questions I'd like to ask:
I was able to hook my `do_proc_drbd` (copied from `do_proc_snmp`), but I couldn't find any snmp- or drbd-specific metrics in the netdata browser window. How do I know that my code really work and not silently failed?
You said `You can monitor the performance of your code at the netdata proc module`, so this is the metric of all proc_* modules? I haven't quite understood this one.
Thank you very much.

**Comment by ktsaou** [comment]
All the `proc` modules defined here https://github.com/firehol/netdata/blob/84fbcbad4482f67db31c9dd8bb8c8a36ea3afc62/src/plugin_proc.c#L16-L66

are being tracked for their latency. Their latency is visualized in this chart:

![image](https://user-images.githubusercontent.com/2662304/45450040-9515db80-b6df-11e8-82a8-761a2a49a0ac.png)

So, if you successfully hooked your code to the `proc` plugin, there should be an entry in this chart with the name of your module.

**Comment by cakrit** [comment]
This seems fixed. Please reopen if there are any issues.

**Comment by ktsaou** [comment]
@cakrit 	how is it fixed?

**Comment by giang-nghg** [comment]
@cakrit Sorry, I am still working on it, but not actively. I'm fine with someone else taking over.
If I can complete it before it's fixed, I will make a PR.

**Comment by cakrit** [comment]
Let's pick this one up, there seems to be enough information to move with it.

**Comment by ilyam8** [comment]
It seems data should be collected from `/proc/drbd`, should be an internal plugin

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
