### ISSUE TITLE
dashboard configuration option to always show zero on the charts

### ISSUE THREAD

**Issue by shssoichiro** [netdata/netdata#3735]
I apologize if this is a duplicate, I searched for existing issues and did not find any that matched this request.

There are several charts within netdata which should have the minimum for the y-axis set to 0, but do not. For example, the available memory graph on my dashboard currently ranges from 2.87646 to 2.87988 GB. The effect of this is that the graphs become misleading. What appears as a huge fluctuation in memory usage on the graph is actually just a couple of MB. This is applicable to several graphs, including load, swap, interrupts, entropy, cpufreq, used sockets, and others.

**Comment by ktsaou** [comment]
Hi, this is by design. To make this decision I evaluated the following:

1. If zero is always included, many fluctuations will go unnoticed. For example, if you have an 4TB disk, a change in allocation of 10GB will not be visible at all.

2. If the charts focus their scale on the visible delta, fluctuations are magnified. When trying to solve a performance issue, this is a very important feature. You can clearly see that at the point of interest, an application allocated memory, wrote data on disk, etc.

So, I chose to help us troubleshoot, instead of providing a helicopter view.

Now that I think of it, we could add a dashboard option, so that you can have it the way you like it.
I am marking this as enhancement.

**Comment by cakrit** [comment]
Can we discuss this a bit more? Netdata is all about providing the info users need. If autoscaling is a bit too aggressive for some charts, then isn't it better to identify those and configure it appropriately so it provides meaningful presentation OOB?

**Comment by elgeorge2k** [comment]
I would also like this, sometimes you're not looking at the changes but rather the overall, like for example, u can notice a false large spike in cpu utilization and get alarmed, but its not really like that cuz it just went from 30 to 40%, just that it had been steady until now. And this with every graph. Maybe a option we can click to switch some graphs would do.

**Comment by mallman** [comment]
I would also like to see this capability. I think this can be especially useful where we're tracking a capacity. Personally, I'm less interested in seeing the lower bound of memory or disk usage than I am to see how close they are to zero.

I believe this is a valid issue. How do we reopen it?

**Comment by andrewm4894** [comment]
@mallman yep I would like to be able to have some way to have dynamic y-axis, fixed one (current), and more flexible options like you mention like 0 bound (or some better name). 

@netdata/product what's best way to track this?

A fresh feature request?

**Comment by cakrit** [comment]
Feature requests for cloud can still  be opened [in the community forum](https://community.netdata.cloud/c/feature-requests/7)

**Comment by andrewm4894** [comment]
this came up again and i have opened this feature request for it: https://github.com/netdata/netdata-cloud/issues/845

**Comment by RaidOneIsTaken** [comment]
Signed up to +1 this.
