### ISSUE TITLE
netdata in CNCF

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#3800]
Hi all,

I requested netdata to be accepted in CNCF.

Check it here: https://github.com/cncf/toc/issues/123

(vote for it too - I don't know if it will help, but anyway it is good to have a few votes there)

**Comment by paulfantom** [comment]
I am already spreading the word :smile:

**Comment by paulfantom** [comment]
I'm just reading [graduation criteria](https://www.cncf.io/projects/graduation-criteria/) for projects which want to be included in CNCF and I think there will be some legal problems regarding netdata. CNCF strongly recommends using [Apache License for all projects](https://www.cncf.io/blog/2017/02/01/cncf-recommends-aslv2/) and they want to include commercial ecosystems, so I don't think they will accept any project under GPL license.
I also wonder what is their take on redistributing code under different licenses.

**Comment by ktsaou** [comment]
> I'm just reading graduation criteria for projects which want to be included in CNCF and I think there will be some legal problems regarding netdata. CNCF strongly recommends using Apache License for all projects and they want to include commercial ecosystems, so I don't think they will accept any project under GPL license.

Well, this is why I requested to have a copyright transfer, as we discussed in #3695. Personally, I don't really care if it is GPL, Apache or MIT, as long as it is open-source (itself and all derivative works) and helps netdata grow.

When I chose GPL, my only criteria was to use the industry standard license for open-source software.

> I also wonder what is their take on redistributing code under different licenses.

I think all the other projects they have already use various tools and libraries with varying licenses. I don't think this will be a problem.

**Comment by Ferroin** [comment]
@ktsaou There are a handful of differences between GPL and Apache that may be significant here, and you may lose a percentage of users over the lack of GPL licensing (people get picky about the weirdest things). Assuming it's acceptable for CNCF, I'd actually suggest making it dual-licensed GPL and Apache (although unusual, this is possible).

**Comment by ktsaou** [comment]
Yes, I know. Dual licensing may work. We will have to discuss this with CNCF though...

**Comment by ntlug** [comment]
Having been in the software industry a very long time, if you want something to "last", use GPL.  Otherwise, you will be on the slow (or possibly fast) train to losing it all.  Just saying.

**Comment by dankohn** [comment]
CNCF's view on why you should use the Apache license: https://www.cncf.io/blog/2017/02/01/cncf-recommends-aslv2/

**Comment by ntlug** [comment]
If they truly wanted broadest adoption, make in public domain.  No. There's a shroud of (anti FOSS) evil there.  Looking forward to the proprietary commercial products :-)  I mean, it "sounds good".... and maybe they are running for elected positions.... who knows?

Just tired of all the IP/technology loss due to "good sounding" things.

**Comment by dankohn** [comment]
Public domain software can still have patent encumbrances.

**Comment by Ferroin** [comment]
Your assumption that not being GPL means no growth is demonstrably wrong though.  Just because something isn't GPL doesn't mean it won't grow.  OpenStack and the various Apache projects are living proof that things under the Apache license grow just fine.   If you go beyond just looking at things Apache licensed, you can find even more perfectly good examples (nginx, BIND, and quite a few other widely used network services are not GPL licensed for example).

**Comment by ntlug** [comment]
I didn't say that of course.  I was actually trying to say that commercial exploiters of free software as well as free software advocates want to see stuff grow, just that one allows things to grow in ways invisible so as to block usage as deemed necessary.

**Comment by paulfantom** [comment]
CNCF is adopting OpenMetrics format as a standard for gathering metrics. More info: https://www.cncf.io/blog/2018/08/10/cncf-to-host-openmetrics-in-the-sandbox/. This format isn't opinionated on gathering model (push vs pull).

Guys at OpenMetrics are also working on creating IETF RFC for this standard. Work on this is done independently by Prometheus core developers, Google, and Uber with contributions by quite a lot of other companies.

Also prometheus just got promoted in CNCF to "graduated project" (highest) stage.

I wonder how netdata will fit in this.

And since it is good to know what is happening in other monitoring projects, here is a portion of news from PromCon2018 (posting here since there is no other comm channel):
- guys at grafana are working on "mixins" which are basically sets of prometheus alerts, scrape rules, and grafana dashboards in form of jsonnet code. This is aimed to be provided by developers of particular software, example for etcd is [here](https://github.com/coreos/etcd/tree/master/Documentation/etcd-mixin).
- grafana is also working on bringing metrics descriptions from exporters (`# HELP ....` comments) directly into grafana dashboards.
- prometheus doesn't use OpenMetrics... yet
- guys at InfluxData are decoupling their database engine from storage and creating `flux` parser. They want to provide support for interchanging data via [apache arrow](https://arrow.apache.org) format. It seems that they are relying more on supporting prometheus as metrics acquisition system and focusing on long-term storage with multi-tenancy.
- prometheus is working on transport security and authentication (not a basic auth one)
- there is no consensus about long-term storage solution for prometheus
- fastly is moving their monitoring infra from ganglia+Icinga2 and DataDog to prometheus and they are doing it very quickly

**Comment by ktsaou** [comment]
All these are very nice improvements. Standardizing metrics format and having alternatives is always good.

> I wonder how netdata will fit in this.

Most of the existing solutions, including prometheus, grafana, etc. are generic tools to build your monitoring solution. The outcome of these solutions is not "real-time performance monitoring". It is more like "statistics about performance".

In the contrary, netdata is a real-time performance monitoring solution out of the box. Think a bit of it. To recreate a netdata dashboard using any of the other tools, you need several months of work and quite an expertise, to understand the metrics, categorize them, setup alarms on them, etc. I am sure, other solutions will eventually come with some kind of templates that can be used as-is, but still the work that will be needed to set everything up will be significantly more compared to installing netdata and most probably they will not be so rich, or so detailed.

Also, netdata is a distributed solution. We have to work a bit to improve various aspects of it (like the data retention period, the multi-server dashboards, etc), but still netdata's metrics resolution and count cannot be matched by any other solution. netdata will always be a lot cheaper to run and will provide a lot more insights.

Of course, netdata can be integrated in the modern ecosystem:

- netdata is the best metrics collector out there. It can be used just to collect metrics and push them to prometheus. We will support OpenMetrics too.

- netdata visualizer is a lot faster and more interactive compared to anything else. We need to work a bit on it to ease the creation of custom dashboards, multi-server dashboards, aggregated charts, etc, and due to the nature of netdata, we can do this a lot easier for end-users, compared to any other solution. Most applications will benefit by passing their metrics through netdata and then store them to a time-series db. This means netdata may also get an OpenMetrics collector.

- netdata is ideal for IoT. Of course we need to improve streaming a bit and provide some kind of central health monitoring, but the fact that netdata is actually a strong watchdog (alarms) installed on all systems makes it pretty unique for IoT. 

If netdata evolves as it should, prometheus+grafana will be only useful for long-term archiving of metrics.
I strongly believe that charts / dashboard integration into wikis and project documentation will be a key factor for selecting the visualizer of the metrics. netdata is already doing this and yes, we can also make it a lot easier.

Logs aggregation is also something netdata should eventually do, in a distributed way too.

**Comment by ktsaou** [comment]
@gmosx 	we need the new netdata logo in SVG format, to replace the one we have in CNCF: https://landscape.cncf.io/grouping=no&selected=netdata&sort=stars

**Comment by gmosx** [comment]
@taniaab , has access to all the logos. But here it is anyway.


[netdata-logo-horizontal.svg.zip](https://github.com/netdata/netdata/files/2643008/netdata-logo-horizontal.svg.zip)

**Comment by ktsaou** [comment]
Made PR https://github.com/cncf/landscape/pull/1024 at CNCF landscape.

**Comment by gmosx** [comment]
@ktsaou OK, I think we can close this issue, right?
