### ISSUE TITLE
Stair step graphs possible?

### ISSUE THREAD

**Issue by ntlug** [netdata/netdata#3816]
I'd like to be able graph immediate gauge information especially for small values.  Examples could be logins, but in my case it a rollingcountsuccess (etc.) value from Springboot metrics.  Right now with netdata, you go from zero to value via an angled line, and I just want to see it go vertically straight up.

Maybe I need to use a different chart type? (recommendation?)

Consider the following Grafana graph:
![raw-sync-service-stair-step](https://user-images.githubusercontent.com/337494/41307517-09a4b3ac-6e3f-11e8-9cdc-b97990186ec7.png)

versus what we get in netdata:
![raw-sync-service-netdata](https://user-images.githubusercontent.com/337494/41307541-193ed0cc-6e3f-11e8-8794-a8cbba92d453.png)

**Comment by ktsaou** [comment]
See the same timeframe on both charts:

![image](https://user-images.githubusercontent.com/2662304/41308311-3966bf32-6e84-11e8-8c5e-69d4879d06bc.png)

![image](https://user-images.githubusercontent.com/2662304/41308351-4ee49a00-6e84-11e8-99e3-ea34451856f8.png)

I think the difference you get is because of 3 factors:

1. netdata dashboards have the option (`on` by default) to use berzier lines, not just straight lines, to connect the points. This setting is under `Visual` in the settings tab. If you have a custom dashboard, there is a variable you can set to control this effect.

   ![image](https://user-images.githubusercontent.com/2662304/41308809-a088628c-6e85-11e8-8e05-359d367a709e.png)

2. netdata interpolates the values to find the expected value at second-boundaries, using microsecond calculations. So, `1` at 00:00:00.000 and `10` at 00.00.01.200, gives (about) `[1, 8]`, not `[1, 10]`. 

   This may be the issue only if your grafana chart has a non-netdata source, or if the backend configuration at netdata.conf is set to `as-collected` (so only if the collected values are not interpolated). However judging from the heights of the values, I think the 2 charts have the same source.

**Comment by ktsaou** [comment]
hm... I just read the legend: this smoothing is not applied on area and stacked charts. So, I guess it is just the chart library.

Another way would be to lower the number of pixels per point. netdata uses 3, so every second takes 3 pixels. If you lower this, you can get steeper lines.

There is a setting for this too, but not on the default dashboards: after loading `dashboard.js`, set:

```js
NETDATA.chartLibraries.dygraph.pixels_per_point = function(x) { return 1; };
```

**Comment by ntlug** [comment]
The use the same ultimate "root" source, but very indirect, that is, not the same direct source.  The grafana graph is coming from an InfluxDB populated by hystrix.stream (data twice a second).  Where the netdata is coming from the springboot /metrics polled at whatever interval is used by netdata.

Just saw you additional update... I'll start playing with some stuff.

**Comment by ktsaou** [comment]
hm... if the grafana source has twice the resolution, the diff in steepness is explained. dygraphs (the netdata chart library) is not given the horizontal points between 2 vertical points.

**Comment by ntlug** [comment]
While true, grafana also has a stair step option (for this sort of case).

**Comment by ktsaou** [comment]
Maybe: do you have point on netdata at the marked area?

![image](https://user-images.githubusercontent.com/2662304/41309748-42e2e17c-6e88-11e8-9b84-7910c657aba2.png)

**Comment by ktsaou** [comment]
hm... I just saw dygraphs also have this option http://dygraphs.com/options.html#stepPlot

**Comment by ktsaou** [comment]
And it is `false` in netdata: https://github.com/firehol/netdata/blob/f70a47874235e996961b9f0beac8cd6fed48309f/web/dashboard.js#L6391

On custom dashboards you can set it with:

```html
<div ... data-dygraph-stepplot="true" ... ></div>
```

**Comment by ntlug** [comment]
In picture form.... (without doing a query)...

![grafana-zoomed](https://user-images.githubusercontent.com/337494/41310215-893baf42-6e46-11e8-93d0-6c4afb9dd6cd.png)

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
