### ISSUE TITLE
If trailing slash is not included dashboard.js fails to load for slave dashboard for master

### ISSUE THREAD

**Issue by eliezerlp** [netdata/netdata#3820]
When trying to access a replicated slave DB on a netdata master using the `http://master.ip:19999/host/slave.hostname/` URL if the trailing slash is left off the dashboard fails to load giving a 404 error for `http://master.ip:19999/host/dashboard.js?xxxxx`. If the trailing slash in included netdata looks for it (with success) in `http://master.ip:19999/host/salve.hostname/dashboard.js?xxxxx`.

This was mentioned by @LucaDev in https://github.com/firehol/netdata/issues/817#issuecomment-241397371.

**Comment by ktsaou** [comment]
seems like a bug.

**Comment by lumbric** [comment]
The problem mentioned in [#817 (comment)](https://github.com/netdata/netdata/issues/817#issuecomment-241397371) is actually that `https://myserver.com/netdata` gives a 404 because of missing trailing `/`.
This issue is actually already tackled by the [nginx config sample](https://docs.netdata.cloud/docs/running-behind-nginx/#as-a-subfolder-to-an-existing-virtual-host), because it includes this redirect:

```
   location = /netdata {
        return 301 /netdata/;
   }
```

(I have no master/slave setup to test the case mentioned in this ticket.)

**Comment by cakrit** [comment]
You're correct @lumbric. We just never investigated more deeply. It does indeed have to do with the nginx configuration. Thanks for this!
