### ISSUE TITLE
"Access to file is not permitted" error after package update

### ISSUE THREAD

**Issue by jonathannz** [netdata/netdata#3896]
Using apt-get on Ubuntu 18.04, I updated Netdata from a previous version to `1.9.0`. 
During the update I opted for all conf files to remain as they were.

After the update, I get the following error when trying to access Netdata:

`Access to file is not permitted: /usr/share/netdata/web//index.html`

As you can see, there is a double forward slash in the folder location. I am not sure if that's the issue, or if it is an actual permissions error.

Please advise.

**Comment by tomwassenberg** [comment]
I also ran into this after uninstalling a netdata instance that was installed using `netdata-installer.sh`, and replacing it by the apt package (on Ubuntu 18.04).

Looks like this is a permission issue because the `/usr/share/netdata` wasn't (completely) deleted during the uninstall.

Removing that directory manually and re-installing the apt package fixed it.

**Comment by cakrit** [comment]
This will be resolved with our own packaging, which will be the way we will be distributing netdata in the future. Thank you for the report.
