### ISSUE TITLE
Reduce number of assets in github release

### ISSUE THREAD

**Issue by paulfantom** [netdata/netdata#3913]
@ktsaou I have couple of questions regarding releases

1. Why there is no prebuild release binary in release assets
2. Why there is no many snapshot archives in various formats? Is source code automatically attached by github in `tar.gz` and `zip` formats not enough?
3. How does `netdata-latest.gz.run` differ from for example `netdata-v1.10.0-x86_64-20180327-195445.gz.run` ?

**Comment by ktsaou** [comment]
> Why there is no prebuild release binary in release assets

We have to make travis do it. Can you try it?

> Why there is no many snapshot archives in various formats? Is source code automatically attached by github in tar.gz and zip formats not enough?

"various formats"? Where?

> How does netdata-latest.gz.run differ from for example netdata-v1.10.0-x86_64-20180327-195445.gz.run

`netdata-latest.gz.run` is always the latest one. The other is maintained in case someone wants to try an older version.

**Comment by paulfantom** [comment]
> "various formats"? Where?

preferably in https://packagecloud.io/ or in github assets

> The other is maintained in case someone wants to try an older version.

Full link to download `netdata-v1.10.0-x86_64-20180327-195445.gz.run` is already versioned as it is located under https://github.com/firehol/netdata/releases/download/v1.10.0/netdata-v1.10.0-x86_64-20180327-195445.gz.run making it redundant with `netdata-latest.gz.run`. And also making `netdata-latest.gz.run` name not true in earlier releases, like in 1.9.0: https://github.com/firehol/netdata/releases/download/v1.9.0/netdata-latest.gz.run

**Comment by paulfantom** [comment]
Basically I don't see any benefit of duplicating packages and thus introducing chaos. We could probably not loose any major functionality by releasing less assets. Like changing this:
![screenshot_20180907_131235](https://user-images.githubusercontent.com/3531758/45216273-4829a380-b2a0-11e8-81a7-bfb9dfb7477e.png)
into:
![screenshot_20180907_131235-mod](https://user-images.githubusercontent.com/3531758/45216295-5bd50a00-b2a0-11e8-9d3b-a6db2f710aad.png)

I would understand so many assets if we were publishing packages for various CPU architectures, but we are not.

**Comment by Ferroin** [comment]
Agreed on the different compression formats.  Pick one and stick with it.  I'd personally suggest BZip2 over GZip, as it's nearly as ubiquitous, and a few hundred kB _can_ make a difference for some people (not everyone in the world has amazing high-speed internet).  If Netdata ever gets native Windows support, we'll need to provide a ZIP archive (or better yet an MSI file) for it too, but that's an issue for the future.

Also agreed on reducing the variety of checksums.  `sha1sum` is present on a vast majority of Linux systems, and no sane person is using MD5 for verifying files (it protects against data corruption, but not malicious replacement).  If it weren't for the fact that it's not anywhere near as universally available, I'd actually suggest SHA-256 instead of either MD5 or SHA-1, as SHA-1 is known insecure too (though it's nowhere near as bad as MD5).

I also see no point in having the `latest` tagged self-extracting archives, or for that matter tagging them with exact build info, in with the release assets  Having them in the `firehol/binary-packages` repository makes sense, because the repo gets updated regularly with new builds.  For the release assets on GitHub though, there is never any update to them except for a new release superseding the old one, so the tags just make the filenames longer, and the `latest` one is a simple duplicate with a different name.

**Comment by paulfantom** [comment]
> I'd personally suggest BZip2 over GZip,

gzip is arguably more widely adopted by minimal distros so we can provide better user experience. Difference between gz and bz2 in our case is ~300kB and when system doesn't have bzip installed then someone will need to spend bandwidth on downloading it so it evens out.

> I'd actually suggest SHA-256 instead of either MD5 or SHA-1

Couldn't agree more :+1:

**Comment by ktsaou** [comment]
@paulfantom are your travis changes include these?
If not, do it.

**Comment by paulfantom** [comment]
No they do not, I didn't want to create one giant PR with everything.

**Comment by ktsaou** [comment]
ok, your call...

**Comment by paulfantom** [comment]
I didn't realize one thing. All those `*.tar.gz`, `*.tar.bz2` and `*.tar.xz` are nothing else than `Source code (*)` after running 3 commands (`autoreconf -ivf && ./configure --enable-maintainer-mode && make dist`). I don't see any benefit of having those archives.

**Comment by paulfantom** [comment]
Code tarball is always attached to GitHub release, it is called "Source code".

**Comment by Ferroin** [comment]
Ah, OK, I misunderstood what you meant, sorry.
