### ISSUE TITLE
mdstat RAID0 support

### ISSUE THREAD

**Issue by weidercs** [netdata/netdata#4010]
Not sure if it has to do with my first array being md1 as opposed to md0 but here's the debug output:

```
netdata@media1:/etc/netdata/python.d$ /usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace mdstat
2018-07-25 21:57:37: python.d INFO: plugin: main: Using python 2
2018-07-25 21:57:37: python.d DEBUG: plugin: main: module load source: 'mdstat' => [OK]
2018-07-25 21:57:37: python.d DEBUG: plugin: main: module load config: 'mdstat' => [OK]
2018-07-25 21:57:37: python.d DEBUG: plugin: main: job initialization: 'mdstat mdstat' => ['OK']
2018-07-25 21:57:37: python.d DEBUG: plugin: main: module status: 'mdstat' => [OK] (jobs: 1)
2018-07-25 21:57:37: python.d ERROR: mdstat: mdstat: Failed to read data from /proc/mdstat or there is no active arrays
2018-07-25 21:57:37: python.d INFO: mdstat: mdstat: check() => [FAILED]
2018-07-25 21:57:37: python.d INFO: plugin: main: FINISHED
```
```
netdata@media1:/etc/netdata/python.d$ cat /proc/mdstat
Personalities : [raid0] [linear] [multipath] [raid1] [raid6] [raid5] [raid4] [raid10] 
md1 : active raid0 sdd[1] sdb[0]
      15627790336 blocks super 1.2 512k chunks
      
unused devices: <none>
```

**Comment by l2isbad** [comment]
Hi @weidercs 

```
Personalities : [raid1] [raid6] [raid5] [raid4]
md_d0 : active raid5 sde1[0] sdf1[4] sdb1[5] sdd1[2] sdc1[1]
      1250241792 blocks super 1.2 level 5, 64k chunk, algorithm 2 [5/5] [UUUUU]
      bitmap: 0/10 pages [0KB], 16384KB chunk

unused devices: <none>
```

I see no `[5/5]` part in your output

> [n/m] means that ideally the array would have n devices however, currently, m devices are in use. Obviously when m >= n then things are good.

**Comment by weidercs** [comment]
Looks like Raid-0 doesn't print that information, is it necessary for netdata?

> Depending on what type of array is defined, slightly different information is available through /proc/mdstat.

```
md1 : active raid0 sdc1[1] sdb1[0]
      35840768 blocks 64k chunks
```

> This example describes a RAID-0 at /dev/md1. The first line provides the same information that the RAID-1 example provides, but the second line omits information about the status of member disks and instead includes information about the chunk-size. Since RAID-0 does not support redundancy, there's no need to provide information about how many member disks are online versus how many have failed. The failure of a single disk in a RAID-0 means that the entire array is failed. chunk-size, which isn't a factor when working with RAID-1, is a requirement for RAID-0. So chunk-size information, instead of failure information, is provided for RAID-0 arrays.

**Comment by l2isbad** [comment]
Yes, we have to add support for RAID-0 arrays.

**Comment by l2isbad** [comment]
@weidercs 
What should we chart for RAID0? `active/inactive` ?

**Comment by l2isbad** [comment]
Ok, i did some quick test in the vm.
According `mdadm --detail /dev/md`:

- raid 4 with 6 disks: degraded after 1 fails, failed after 2nd
- raid 5 with 6 disks: degraded after 1 fails, failed after 2nd
- raid 6 with 6 disks: degraded after 2 fails, failed after 3rd

I suggest:
1. Move `Faulty Devices In MD` from the `heath` section to the `md`(each md has it's own md section in the dashboard)
2. Add to `health` section 2 new charts: `Arrays in Failed State`, `Arrays in Degraded State` (units - boolean).

Since RAID0 can only be `active/inactive` (am i right?) we only need to add it to the `Arrays in Failed State` chart.

Or this doesn't make any sense because all uses 0,1,10 only these days. ?

@Ferroin 
@weidercs

**Comment by l2isbad** [comment]
And about `RAID0`, not sure i know how (correctly) to simulate a failure event.

What i did:
1.  create an array level 0
2.  remove one disk from the vm (virtualbox)

After that array completely disappeared from the `proc/mdstat`

```
test@debian:~$ cat /proc/mdstat 
Personalities : [raid1] [linear] [multipath] [raid0] [raid6] [raid5] [raid4] [raid10] 
unused devices: <none>

test@debian:~$ sudo mdadm --detail /dev/md0
/dev/md0:
        Version : 
     Raid Level : raid0
  Total Devices : 0

          State : inactive

    Number   Major   Minor   RaidDevice

```

**Comment by Ferroin** [comment]
What you did is indeed correctly simulating a failure event.

There is no 'degraded' state for RAID0, because the striping means that a single device loss results in 1/N blocks (where N is the total number of devices in the array) being completely gone (as opposed to the erasure coding provided by RAID4/5/6 which lets you recompute the block, or the mirroring provided by RAID1/10 where you just look at one of the other copies).  In this case, it's considered better to just make the whole array inaccessible, because you can't write to it, and you aren't guaranteed to be able to read from it.  Put a bit differently, if you suddenly had every Nth block (for a small single or double digit N) go bad on your hard drive, the disk would be useless, and a RAID0 array is no different in this respect.

I'd also expect similar behavior for a RAID10 array losing two devices.  In fact, because of how RAID10 is implemented in MD and DM on Linux, the numbers are identical (you still lose 1/N blocks, where N is the total number of devices).

Note that this is different from LVM, which will behave exactly like MD, except that the volume will still be visible in the tools and you can clearly see that it's missing devices.

It's also different from BTRFS. Files there are still readable in a  broken striped array provided that they're smaller than the stripe size and weren't stored on the failed device, and you can still write to the array (it will produce stripes over however many devices remain in the array.

**Comment by l2isbad** [comment]
> After that array completely disappeared from the proc/mdstat
> What you did is indeed correctly simulating a failure event.

So how to monitor it? Does it always disappear from `/proc/mdstat` losing one disk? @weidercs 

> I'd also expect similar behavior for a RAID10 array losing two devices.

I did some tests with RAID10 too (6 disks). Internally mdadm created RAID0 using 3 RAID1. So RAID10 is OK until underlying RAID's1 are OK (can survive maximum 3 disks failures in my case).

**Comment by Ferroin** [comment]
> So how to monitor it? Does it always disappear from /proc/mdstat losing one disk? @weidercs (you have to had some experience as a RAID0 user)

I have no idea on this one.

>I did some tests with RAID10 too (6 disks). Internally mdadm created RAID0 using 3 RAID1 (mdadm --create /dev/md0 --level=10 --raid-devices=6 /dev/sd[b-g] or smth). So RAID10 is OK until underlying RAID's1 are OK (can survive maximum 3 disks failures in my case).

That's odd.  Last I knew, tha'ts not how RAID10 worked in MD.  From what I understood, you defined a number of copies, and could lose one less disk than the number of copies before it was unrecoverable.  Without specifying a number of copies, you get two, and can thus lose exactly one disk before you have issues.  The striping (again, as far as I understand it) works by rotating what devices the copies of a block get put on (so, if you have two copies and three devices A, B, and C, your first block has copies on A and B, your second has copies on C and A, and your third has copies on B and C).

**Comment by weidercs** [comment]
@l2isbad yes, when the disk goes bad, it just disappears from /proc/mdstat.  That would make it difficult for the monitoring status to be meaningful (did the drive go bad or was it simply removed on purpose).

All that being said, the only value I see in supporting Raid0 would be alerting if there's a state change from 'active' to 'no raid detected' (since there's no meaningful status provided if the array has a problem).

**Comment by l2isbad** [comment]
@weidercs will be added in `C` version

**Comment by vlvkobal** [comment]
Done in #4923
