### ISSUE TITLE
Support for FastCGI in phpfpm.chart.py

### ISSUE THREAD

**Issue by n0guest** [netdata/netdata#4034]
Hello, All.

I want to add support for FastCGI in PHP-FPM module (now it supports only HTTP/HTTPS requests via urllib3?). The reason is simple - there is no much sense in keeping Nginx or any other software as a middleware between Netdata and PHP-FPM.

Based on the discussion in #4027, I guess, it can be done as in HAProxy module. I.e. inherit from UrlSocket and SocketService plus add logic, which will handle both modes (via HTTP and via FastCGI protocols). So, mainly my questions are addressed to @l2isbad and @Ferroin as participants of the initial discussion. Are there any guidelines or suggestions before it all begins? Or maybe it's totally wrong direction and it should be made in some other way?

Thank you.

PS: BTW, any other comments are welcomed.

**Comment by Ferroin** [comment]
So, as mentioned in the discussion between @l2isbad and me in the aforementioned issue, I'd _really_ like to avoid more stuff like the `HAProxy` module.

Potential alternatives that have come to mind include:

1. Open coding what is actually required from both the `SocketService` and `UUrlService` modules.  This is really error prone though, and likely to make things potentially very confusing.
2. True dynamic class behavior by using `__new__` (`__new__` gets passed the class to instantiate (unlike `__init__`, which gets passed an instance to initialize), so you can do interesting things like sub-classing that and instantiating the result) to override all the class methods appropriately at runtime.  I'm not 100% sure this will even work, and if it does it's still going to be rather non-obvious _how_ it works.  This would have a rather decisive benefit though that it could let the module completely avoid having to import urllib3.
3. Proper encapsulation.  In short, make the `Service` class a wrapper which just instantiates the appropriate service type and indirects all it's calls to that.  This is probably the cleanest, but will most likely have poor performance.
4. Write up a framework service that actually implements option 2 or 3, so that `Service` classes can just inherit from that instead.  THis gives the simplest API, but has all the same practical limitations of options 2 or 3.

I can try and help with any of these (both converting the HAProxy module to use them, and helping adapt other modules to use them), but I'm hesitant to start on any of them without some input from @l2isbad and probably also @paulfantom.

**Comment by l2isbad** [comment]
There is no clean way to do it. 

warkaround example

<details><summary>click</summary>
<p>

```python
# -*- coding: utf-8 -*-
# Description: example netdata python.d module
# Author: Pawel Krupa (paulfantom)
# SPDX-License-Identifier: GPL-3.0+

from random import SystemRandom

from bases.FrameworkServices.SimpleService import SimpleService
from bases.FrameworkServices.UrlService import UrlService

# default module values
# update_every = 4
priority = 90000
retries = 60

ORDER = ['random']
CHARTS = {
    'random': {
        'options': [None, 'A random number', 'random number', 'random', 'random', 'line'],
        'lines': [
            ['random1']
        ]
    }
}


def Service(**kwargs):
    if kwargs['configuration'].get("something"):
        return init(SimpleService)(**kwargs)
    else:
        return init(UrlService)(**kwargs)


def init(cls):
    class Example(cls):
        def __init__(self, configuration=None, name=None):
            super(self.__class__, self).__init__(configuration=configuration, name=name)
            self.order = ORDER
            self.definitions = CHARTS
            self.random = SystemRandom()

        @staticmethod
        def check():
            return True

        def get_data(self):
            data = dict()

            for i in range(1, 4):
                dimension_id = ''.join(['random', str(i)])

                if dimension_id not in self.charts['random']:
                    self.charts['random'].add_dimension([dimension_id])

                data[dimension_id] = self.random.randint(0, 100)

            return data
    return Example
```

</p>
</details>

**Comment by Ferroin** [comment]
Actually, assuming that your example works, I think that's somewhat cleaner than any of the options I had been thinking of (it's definitely cleaner than the second option I listed, which is doing essentially the same thing, just in a slightly more convoluted way).  Having a taken another look at things, I think that this approach _should_ work too (at least, in Python 3, there may be something I'm missing WRT Python 2 that would cause it to not work), as we don't appear to be doing anything that depends on the exact class that a given service is outside of the service itself, and we pretty obviously aren't depending `Service` being a class.

**Comment by l2isbad** [comment]
> assuming that your example works

It works, i checked. You can rewrite `haproxy` with this hack, it's super easy (add `option` dict in `def Service`)

**Comment by n0guest** [comment]
Hi, guys.

Is there any development on this matter? I mean looks like you've been discussing some major changes. And I guess I should wait with adding support of FastCGI until discussed changes will be implemented? Or I misunderstood the discussion above?

**Comment by ktsaou** [comment]
Past contributors of phpfpm in netdata that may be able to help: @safeie @clinta @leolovenet @schrenkb1
Guys you may find this interesting. If you can help, please do.
Thanks!

**Comment by tomascharvat** [comment]
There is binary cgi-fcgi, that is part of libfcgi0ldbl on Debian or dev-libs/fcgi on Gentoo.
It can be called from the /bin/bash by:
`#!/bin/bash
# Requirements: cgi-fcgi
RESULT=$(SCRIPT_NAME=/status \
SCRIPT_FILENAME='/status' \
QUERY_STRING=full \
REQUEST_METHOD=GET \
/usr/bin/cgi-fcgi -bind -connect 127.0.0.1:9000)

if [ -n "$1" ]; then
echo -e "$RESULT" | grep -A12 "$1"
else
echo -e "$RESULT"
fi
`
you will get 
`Expires: Thu, 01 Jan 1970 00:00:00 GMT
Cache-Control: no-cache, no-store, must-revalidate, max-age=0
Content-type: text/plain;charset=UTF-8

pool:                 www
process manager:      dynamic
start time:           06/Sep/2019:18:41:31 +0200
start since:          58942
accepted conn:        22
listen queue:         0
max listen queue:     0
listen queue len:     32768
idle processes:       1
active processes:     1
total processes:      2
max active processes: 1
max children reached: 0
slow requests:        0

************************
pid:                  24941
state:                Idle
start time:           06/Sep/2019:18:41:31 +0200
start since:          58942
requests:             11
request duration:     319
request method:       GET
request URI:          /status?full
content length:       0
user:                 -
script:               -
last request cpu:     0.00
last request memory:  262144

************************
pid:                  24942
state:                Running
start time:           06/Sep/2019:18:41:31 +0200
start since:          58942
requests:             11
request duration:     266
request method:       GET
request URI:          /status?full
content length:       0
user:                 -
script:               -
last request cpu:     0.00
last request memory:  0
`

So if Netdata call cfg-fcgi, it can get php-fpm status directly from socket and it dont need nginx, apache or alike service.

**Comment by ilyam8** [comment]
I think this was implemented in the go version of phpfpm module https://github.com/netdata/go.d.plugin/pull/402
