### ISSUE TITLE
RFC: Remove node and bash plugins

### ISSUE THREAD

**Issue by paulfantom** [netdata/netdata#4036]
@ktsaou @Ferroin @l2isbad 

We already have thin resources and low bus factor, let's deprecate plugins which are written in bash and those written in node.js. This way we can focus on python and maybe on go-lang in the near future.

This issue is a result of discussion from #4025

**Comment by Ferroin** [comment]
Agreed.

Assuming @ktsaou has no issue with it, I'll prep a PR to remove the currently deprecated charts.d plugins from the tree and look at getting the ones which have no python.d equivalent converted to Python (unless @l2isbad want's to convert them directly to Go, which is fine by me too, I just will not likely be much help with that as I have essentially zero experience with Go (though learning it is on my to-do list)).

I can probably help with the node.d plugins too, but I'm not quite as confident that I can do that without some extra assistance.

**Comment by l2isbad** [comment]
@Ferroin 
Are you sure all systems has `python`?

**Comment by l2isbad** [comment]
Sad that netdata has no anonymous statistics about modules usage :disappointed:

**Comment by Ferroin** [comment]
Oh, I know there are systems without Python out there.  I deal with them on an almost daily basis.  They also generally don't have a sanely working version of bash either (they either use a stripped down `/bin/sh` implementation from busybox, an actually POSIX compliant bourne shell, or a really ancient version of bash that's functionally useless for any modern scripts), so a vast majority are not likely to be able to run any of these plugins anyway.

At minimum though, we _should_ get rid of the ones which are provided by the netdata core or compiled code.  I was planning on submitting that as a separate PR from the ones that are served by Python plugins instead, as it should be relatively uncontroversial.

**Comment by Ferroin** [comment]
There's also the special case of the sensors plugin, which has slightly more functionality in the charts.d version than the python.d version.

**Comment by l2isbad** [comment]
In general seem a good direction. Lets wait @ktsaou :smile:

**Comment by paulfantom** [comment]
Let's maybe start with node.js. At least this isn't installed by default almost anywhere.

**Comment by Ferroin** [comment]
Depending on the particulars, it _might_ be easier to go straight to Go from the Node.js plugins.  I'm not quite sure though.

From a quick look at the charts.d plugins we still 'need', I see two big things that you can do there easily that you can't with python.d plugins:

* Privilege escalation.  I've got a (apparently) working patch for `ExecutableService` to add proper support for this, but I don't have anything that uses it yet, and I'm hesitant to try and adapt the `samba` plugin to use it because I can't test it (well, I kind of can, but it would be a serious pain in the arse to do so because I don't use SMB all that much).
* Combining output from multiple command invocations into a single list of items to parse.  The LibreSwan charts.d plugin does this, and it looks like a handful of others do to.  I'm working on a patch to support this, but it's not quite working yet.

If I can get those taken care of, I can write up python.d plugins for pretty much all of the remaining charts.d plugins to Python without much effort.

That would just leave the case of the sensor plugin.  I know what needs done there (essentially, reimplement a good portion of lm_sensors in pure python), it's just going to be long and somewhat involved to actually do it.

**Comment by paulfantom** [comment]
> Privilege escalation

Where and why this is needed?

> That would just leave the case of the sensor plugin. I know what needs done there (essentially, reimplement a good portion of lm_sensors in pure python)

That's why I wanted to take out node.js first. [lm_sensors in go-lang](https://github.com/ssimunic/gosensors/blob/master/sensors.go) will be much better than in python.

**Comment by l2isbad** [comment]
Guys, lets wait @ktsaou . Do not hurry to implement pls. You are acting like he is agreed, which is not true.

> That would just leave the case of the sensor plugin

I see python has sensors module and `lm_sensors.py` in `third_party` dir.

**Comment by l2isbad** [comment]
> Combining output from multiple command invocations into a single list of items to parse.

Sounds heavy, maybe some thing should stay in bash. Not an expert tho

**Comment by paulfantom** [comment]
> Do not hurry to implement pls.

Agreed. But we can talk and that's what I am doing :smile:


As for python and lm_sensors - it sucks. It sucked 2 years ago and it still sucks. Also it would be good to have this module on platform without python, so go-lang is a good candidate.

**Comment by paulfantom** [comment]
Also, title is **RFC** - Request For Comments, not for implementation :smile:

**Comment by paulfantom** [comment]
> maybe some things should stay in bash

I don't agree. If you still want to provide go-lang plugin implementation then we need to get rid of something. Bash is the least efficient from all and everything from node.js can be easily converted to python/go (as a bonus some sysadmin will be very happy to get rid of node.js from their servers). That's why those two are perfect candidates to let go. And reducing number of languages has obvious benefits.

Some time ago I heard a saying that "if you need arrays in BASH, then you chose a wrong language". At that time I thought it was stupid, but now I stand by it. BASH is great for simple, one-time jobs (like installation). But not when files reach hundreds or thousands lines of code. At that point it is inefficient and hard to maintain.

**Comment by Ferroin** [comment]
@paulfantom For privilege escalation, both the `samba` and `megacli` plugins need it currently.  `samba` is reading profiling data using `smbstatus` (which is ironically one of the only truly sensitive bits of information that that command exposes that you can't get reasonably easily by other non-root means).  `megacli` is calling a command that interacts directly with hardware via ioctls, and functionally _should_ have a requirement that it be run as root.  In theory, that one could be covered with a udev rule (probably, I'm not sure if the command itself does an EUID=0 check on startup or not), but that adds more work for users.

Among the charts.d plugins, libreswan requires it because it's interacting with the kernel's IPSEC stack.  This could theoretically be handled with capabilities, but using actual privilege escalation is far simpler for users exponentially safer (because it doesn't require giving the `netdata` user full access to a large amount of networking functionality).

As far as the sensors plugin, keeping the lm_sensors dependency is part of the issue actually.  There are some platforms that can't properly expose sensors under the hwmon interface (which lm_sensors requires), and therefore can't be directly handled with the current python.d sensors module.  I have no objection to this being implemented in Go, but keep in mind that it should ideally be possible to support the Linux thermal subsystem, and ideally also enumerate data without having to touch libsensors.

@l2isbad The case of needing multiple commands to be run and the output parsed together is likely specific to the libreswan plugin, I haven't looked in-depth at any of the other plugins yet though.  I can rewrite things to not have to deal with that, but we would lose autodetection of newly added tunnels.

As far as bash in general, I would tend to agree with @paulfantom here.  Bash is great for quick one-off stuff where performance doesn't matter or you just want the CLI equivalent of a macro, but that's about it.

**Comment by paulfantom** [comment]
> This could theoretically be handled with capabilities, but using actual privilege escalation is far simpler for users exponentially safer (because it doesn't require giving the netdata user full access to a large amount of networking functionality).

How?


> There are some platforms that can't properly expose sensors under the hwmon interface (which lm_sensors requires)

Which ones? Just don't say "raspberry pi" since if that is the case, then maybe this device should get its own module? From what I see libsensors is a hard requirement, we even link to its documentation: https://github.com/firehol/netdata/blob/6832ce444d2637173a6bac436805ca9e55b84fc1/charts.d/sensors.chart.sh#L10

**Comment by Ferroin** [comment]
> How?

If you use capabilities, then, depending on how picky you want to be, either the netdata user can run any of the ipsec commands, or _any_ user can.  With `sudo` (and I think `doas` as well), you can get down to the point of allowing only specific command-line arguments, which means it's possible to restrict the netdata user to only call exactly those commands that are needed for data collection and nothing more (well, theoretically nothing more).  It's also non-trivial even for experienced sysadmins to get configurations with capabilities correct, but it's really easy to get it right with `sudo` or `doas` configuration.

>Which ones? Just don't say "raspberry pi" since if that is the case, then maybe this device should get its own module?

The Pi is not unusual in that it doesn't have the required config options set in the default kernel.  There are quite a few tight-embedded systems out there that only use the thermal subsystem and don't have the appropriate kernel config options set to get the thermal sensors exposed as hwmon class devices.  If we _really_ want to work for IoT usage, we kind of need to support pathologically stupid configurations like that.

The Pi is different from those in that it is not too difficult to get it working properly if you have some background with building your own kernels.  Most platforms that have this issue are somewhat difficult to reflash with user provided kernels that handle this correctly

> From what I see libsensors is a hard requirement, we even link to its documentation:

Nope, you can easily parse all the stuff in `/sys/class/hwmon` (and `/sys/class/thermal`, as is required on the aforementioned problematic systems) by hand or with some reasonably simple code in almost any language you care to name (pulling readings for every temperature sensor on the system out of `/sys/class/hwmon` in Python 3 amounts to about 20 LoC for example, with similar lengths for other sensor types).  All that libsensors is 'required' for is giving out nice names for each of the sensors, but that generally only works out of the box on x86 systems that use older sensor chips (IT87 derived stuff for example) in the de-facto standard way.  Beyond that, if you want nice sensor names, you have to configure them by hand yourself.  The Python module uses libsensors to avoid having to do the parsing itself, which admittedly does make the implementation much cleaner.

**Comment by paulfantom** [comment]
On capabilities and sudo topic.

From security point of view best approach is to separate troublesome binary from the main component and grant it proper capabilities and permissions. Sudo uses much broader scope and grants all permissions to a user running that program, which is easy but very suspicious to end users. It is also VERY insecure.

Also `sudo`/`doas` aren't on every platform, but capabilites are embeded in linux kernel.

>  depending on how picky you want to be

I am very picky when it comes to security :smile:

When it comes to libreswan, why not ask guys from libreswan on what they recommend in aspect of monitoring their application?

---
On sensors topic:

For me it really seems like a good idea to split this into two modules. One handling lm-sensors and another one handling non-usual configuration.

> If we really want to work for IoT usage

We do. I also have contact with prometheus guys and sorry to say this, but they are having much better model for large-scale server deployments. But IoT, small-scale, and small-team environemnts is where netdata shines.

---
OT: I agree with @l2isbad. It is a shame that we don't have data on modules usage. We probably need this telemetry data to be able to estimate if puting workhours into maintaining one module is even worth it. Maybe it could be implemented in discovery stage and advertised as anonymous opt-in feature?

**Comment by Ferroin** [comment]
> From security point of view best approach is to separate troublesome binary from the main component and grant it proper capabilities and permissions. Sudo uses much broader scope and grants all permissions to a user running that program, which is easy but very suspicious to end users. It is also VERY insecure.

Permissions are fragile, insanely so in fact, and so are capabilities.  The moment you run an upgrade with any reasonably sane package manager, all of that disappears.  Note that I'm not saying there are not practical cases where capabilities make sense for this, just that you can't expect every user to use them, because using them is hard, and not very well supported by most distributions.

Also, CAP_NET_AMDIN is almost certainly the required capability for this, and _everything_ else this binary does requires that too, so it's not really providing any better security in this case.

> When it comes to libreswan, why not ask guys from libreswan on what they recommend in aspect of monitoring their application?

Perhaps because no matter what their answer is, it's not going to work for everyone.

There's numerous ways this can be handled:

1. Run netdata as root.  This is not an option for most sane people, and avoiding this is why issues like #3749 exist.
2. Mark the ipsec binary SUID root and set up ACL's/permissions so that only root and netdata can run it.  This is fragile (it will get overwritten by the package manager) and not particularly secure.  It's also a big red flag for any seasoned sysadmin.
3. Use capabilities, and set up ACL's/permissions so that only root and netdata can run it.  This is more secure than 1 or 2 (but not the most secure option), but has the same issues with being fragile that 2 has, and additionally is significantly more complicated to set up correctly (getting the capability set correct is not something most people can do without a significant amount of trial and error).
4. Use SELinux or some other LSM to enforce MAC permissions on objects, and set up the permissions so that netdata can call the ipsec binary appropriately.  This is extremely invasive, rather fragile in it's own way, non-trivial to set up (it makes capabilities look trivial by comparison), and on top of all of that results in a system that's not particularly easy to use.
5. Use `sudo` or `doas`.  This is not quite as secure as option 4, and may or may not be as secure as option 3 (depends on what capabilities are involved and what other things the binary in question can do), but it's trivial for end users to set up properly, doesn't randomly break when you run updates, and is still far better than options 1 or 2.

---

For the sensors stuff, I can look at writing something up for that, but would like to hear from @ktsaou which approach would be preferred.

**Comment by paulfantom** [comment]
> The moment you run an upgrade with any reasonably sane package manager, all of that disappears.

I don't understand this. We ship netdata, we take care of binaries. I wasn't talking anywhere about third-party binaries.

> just that you can't expect every user to use them, because using them is hard, and not very well supported by most distributions.

Not true, just assign them in systemd service file and they couldn't be simpler. Also capabilities are in mainline kernel since version 2.2 and aren't dependant on distro, so unless kernel is manually compiled (gentoo welcome) without them, they work on all distros.

> Also, CAP_NET_AMDIN is almost certainly the required capability for this, and everything else this binary does requires that too, so it's not really providing any better security in this case.

CAP_NET_ADMIN != CAP_SYS_ADMIN or sudo (basically CAP_SYS_ADMIN). So it does provide better security. Also capabilities can work in pair with ACL.

> Run netdata as root.

Never an option.

Options 2 & 3 & 4 -> Contact libreswan team since none of them are acceptable. Maybe same information can be acuired in different way.

Option 5 -> won't pass any security audit.

**Comment by Ferroin** [comment]
> I don't understand this. We ship netdata, we take care of binaries. I wasn't talking anywhere about third-party binaries.

Then I misunderstood what you were talking about.  To me, it sounded like you were saying we should be requiring permissions and capabilities on the `ipsec` binary (which is a third-party binary that we absolutely should not be bundling with Netdata) such that the netdata user can run it.

The only other interpretation I can come up with is that you want trivial wrappers to handle this with, but I'm not too keen on that either, as such an approach is rather fragile in it's own way.

> Not true, just assign them in systemd service file and they couldn't be simpler. Also capabilities are in mainline kernel since version 2.2 and aren't dependant on distro, so unless kernel is manually compiled (gentoo welcome) without them, they work on all distros.

So, this may come as a shock to you, but **_NOT EVERYONE USES OR EVEN WANTS TO USE SYSTEMD_.**.  Any argument that requires it is invalid, period, end of story (FWIW, I feel the same way about people making arguments that require upstart, or sysv-init, or pretty much any other init system, you just hear those far less often these days).

My argument here about support of by distributions is related to capabilities as used through PAM and the filesystem.  PAM management of capabilities is actually reasonably well supported, but that means the whole user session is running with them, which is _really_ dangerous (to quote your own comment below, that won't pass a security audit).  That leaves filesystem capabilities, which are not well supported by distributions, and are in general extremely fragile.

> CAP_NET_ADMIN != CAP_SYS_ADMIN or sudo (basically CAP_SYS_ADMIN). So it does provide better security. Also capabilities can work in pair with ACL.

CAP_NET_ADMIN plus access to the IPSec stack means you can reconfigure any of the system's IPSec tunnels however the hell you want, meaning at minimum you can rather easily DoS anything that depends on those tunnels.  It's actually worse than CAP_SYS_ADMIN here, because CAP_SYS_ADMIN won't let you reconfigure the networking stack in arbitrary ways and taking advantage of CAP_SYS_ADMIN would require you to make use of an ACE exploit in the IPSec stack.

Also, I think you're misunderstanding what exactly CAP_SYS_ADMIN is.  It's not the same thing as having root access (in fact, it's not even close, there's a _lot_ of stuff you can't do with CAP_SYS_ADMIN that root can), and it's absolutely not the same thing as having all the capabilities (which is mostly equivalent to having root access, but not technically the same thing).

> Options 2 & 3 & 4 -> Contact libreswan team since none of them are acceptable. Maybe same information can be acquired in different way.

Netlink probably, but that likely requires the same credentials that just calling through the ipsec binary does, and it means that you're dependent on Linux.

> Option 5 -> won't pass any security audit.

FIPS or equivalent maybe.  Not everyone wants or needs security at that level though.  Yes, we should try to be secure, but at the point at which we're doing so at the expense of usability, it's an issue.  The use of `sudo` for stuff like this is a de-facto standard.  Yes, it's not perfectly secure, but it's good enough for most regular users, and there's absolutely no reason that those who need better security can't just avoid using it The way I was integrating support does allow the user to explicitly disable it provided the module handles things sanely).

**Comment by ktsaou** [comment]
> Sad that netdata has no anonymous statistics about modules usage

This is a feature that **MUST** be added with netdata hub and must be by default enabled. It is really unbelievable that we don't have any visibility on module usage. We don't even know which modules are actually useless, so we spend time maintaining code that is not used at all.

1. I agree to remove all obsolete modules from the repo.
2. I don't agree to remove charts.d.plugin - this is the easiest for any admin to collect a couple of metrics. Actually, I would attempt to improve it a bit to make it easier for people to write quick-and-dirty data collection modules.
3. I agree to remove node.d.plugin - but we have to migrate `named` and `SNMP`. I think the other ones (`sma_webbox`, `fronius` and `stiebeltron`) could be split to a different repo and remain there forever for anyone willing to use them.

**Comment by paulfantom** [comment]
> but we have to migrate named and SNMP

We have a `go.d.plugin` in the making, maybe those modules should have a priority to be implemented in go?

**Comment by ilyam8** [comment]
Priority for `SNMP`? Please no :pray:

**Comment by paulfantom** [comment]
We need to do something with this, we currently have node.d plugin just because of those two modules. So it is either reimplementing it in python, in C or in go. I don't have any strong opinions about in which one of those it should be implemented I just know it cannot stay in javascript.

**Comment by ilyam8** [comment]
About the `SNMP`. I think it should stay as simple as possible. Otherwise we need a special guy only for that plugin.

**Comment by paulfantom** [comment]
I agree with that.

**Comment by ktsaou** [comment]
SNMP has quite a few issues outstanding (like support for the latest protocol, modular configuration, auto-detection of the SNMP collected metrics, etc).
It is not priority though. It would be nice if this handled by a contributor.

**Comment by ktsaou** [comment]
But, we can't remove the existing one, until then...

**Comment by Ferroin** [comment]
I _might_ be able to put together something in Python to handle SNMP support, but it would end up changing what we depend on for SNMP support (my preferred SNMP tool has an option for dumping most or all of the data from the remote system in an easily machine parseable format, but it depends on all the relevant MIB's being installed locally).

**Comment by cakrit** [comment]
I have left the SNMP issues as "help wanted" under https://github.com/netdata/netdata/projects/25

We should probably just go with something like https://github.com/prometheus/snmp_exporter, as soon as the openmetrics collector is ready.

**Comment by Ferroin** [comment]
> We should probably just go with something like https://github.com/prometheus/snmp_exporter, as soon as the openmetrics collector is ready.

Sounds good to me.
