### ISSUE TITLE
FreeBSD: (apps.cpu) not show a specific program

### ISSUE THREAD

**Issue by chalfling** [netdata/netdata#4037]
Hello!

I have a application running with 12 child threads that is a Software Router(SUM 13 Threads in one process). When traffic is very low(about 50Mb/s), I can see apps.cpu chart with my swrouter(lower than 100% of cpu time), but when I have a higher traffic(about 2Gb/s) that chart line is missing and cpu time is about 300%(seeing this in "top" command line).

My netdata is running at FreeBSD 11.2 with 8-cores CPU, so my application can reach almost 800% of cpu time.

Can you tell if netdata drop application above 100% or drop by timeout?

Thank you!

**Comment by ktsaou** [comment]
Hi,

Could you please post the cpu chart or provide a snapshot?

netdata generally does not drop applications based on their usage. If there are gaps though, netdata may not get from the system enough resources to process them, so you may need decrease the niceness of netdata.

**Comment by chalfling** [comment]
Hello!

What do you need? /var/cache/netdata/apps.cpu folder? Or /var/cache/netdata/apps.cpu/myapplication.db ?

How do I decrease the niceness of netdata?

Thank you!

**Comment by ktsaou** [comment]
To export a snapshot press this button on the dashboard: 
![image](https://user-images.githubusercontent.com/2662304/45602803-1eeddd80-ba2d-11e8-83c8-c42134e9cfe9.png)

It will save a file on your disk. Make a zip with it, then drag and drop this zip to a comments box here.

To change the priority of netdata check this: https://github.com/firehol/netdata/issues/4087#issuecomment-419280976

Keep in mind we did a few changes to make this easier. So, if you have the latest netdata, delete `/etc/systemd/system/netdata.service` and then update your netdata. After that, you can control everything with `netdata.service`.

**Comment by chalfling** [comment]
> To export a snapshot press this button on the dashboard:
> ![image](https://user-images.githubusercontent.com/2662304/45602803-1eeddd80-ba2d-11e8-83c8-c42134e9cfe9.png)
> 
> It will save a file on your disk. Make a zip with it, then drag and drop this zip to a comments box here.

Can I send you privately? The snapshot has data from my clients.

> To change the priority of netdata check this: [#4087 (comment)](https://github.com/netdata/netdata/issues/4087#issuecomment-419280976)
> 
> Keep in mind we did a few changes to make this easier. So, if you have the latest netdata, delete `/etc/systemd/system/netdata.service` and then update your netdata. After that, you can control everything with `netdata.service`.

I don't have netdata.service, I'm on a FreeBSD 11.2


I have two snapshot from two servers:
1. My application started about 7 hours ago and it's showing in charts. (showing 350% of CPU use)
2. My application started about 2 weeks ago and it's not showing in charts.(top shows 260% of CPU use)

**Comment by ktsaou** [comment]
Send it to costa@tsaousis.gr

**Comment by chalfling** [comment]
> Send it to [costa@tsaousis.gr](mailto:costa@tsaousis.gr)

Send it from charles@freebsdbrasil.com.br

Thank you!

**Comment by ktsaou** [comment]
Thanks. I received it.

You have 2 snapshots in it:

1. with netmap
2. without netmap

I think that in both versions, apps.plugin is missing something:

- In the version with netmap, the total system CPU utilization is constantly at 67%, but the apps.cpu chart is constantly at 300% (300 shown * 100 / 800 capacity = 37.5% of the total). So it misses about 30%.

- in the version without netmap, the total system CPU utilization is constantly at 35-40%, but the apps.cpu chart is constantly below 10% (it has some spikes that follow the spikes of the system total). Which means it also misses about 30%.

So, I think both chart miss the same thing. This has nothing to do with network or disk traffic. Something else is happening, and it is a bug.

The fact that I don't see this behavior under Linux, it makes me think this is related to the FreeBSD port of netdata. Somehow, apps.plugin does not get the full list of the processes running. @vlvkobal I need your help on this. Could you please verify apps.plugin is receiving from FreeBSD all the processes running on the system?

---

On your snapshots I also see gaps in all the charts. It is important that it happens on all of the them. netdata is multi-threaded. If the gaps were appearing on a few of the charts, then a thread could be locked for some reason. But the fact that they appear on all charts, means the whole process with all its thread were locked.

When these gaps happen, I see that your disks and ZFS is under pressure (they spike, then a gap, then the spikes fade out).

![image](https://user-images.githubusercontent.com/2662304/45977502-853cb680-c052-11e8-8ce8-3672c60d85f3.png)


It is also interesting that immediately before and after the gap, apps.plugin records that netdata and python.d.plugin have disk reads:

![image](https://user-images.githubusercontent.com/2662304/45977392-1eb79880-c052-11e8-9359-2a7fe3ca5dd1.png)

So I think your kernel is under pressure and probably swaps out (before the gap) and later swaps in (after the gap) netdata. But I am not a FreeBSD guy. I think this is true because of this chart:

![image](https://user-images.githubusercontent.com/2662304/45977432-427ade80-c052-11e8-82bc-d9a7ee95f67e.png)

Major page faults and memory accesses that triggered disk I/O.  It is also shown on this chart:

![image](https://user-images.githubusercontent.com/2662304/45977858-6a1e7680-c053-11e8-846f-dca1cd605cdd.png)

So, for the gaps, you system is under memory pressure and swaps. This blocks netdata, which results in gaps at the charts.

**Comment by chalfling** [comment]
> Thanks. I received it.
> 
> You have 2 snapshots in it:
> 
> 1. with netmap
> 2. without netmap

Both snapshots my application is running the word "with and without" is related to showing or not showing in charts.

In the machine not showing netmap's chart my application is running about 2 weeks, when I started the application netdata was showing it's chart, but about 1 or 2 days after, netmap's chart was missing. Can this be related to "TIME" on CPU use? Because in "top" command I have "TIME" and "WCPU" and the difference of both process is "TIME" column, where the older process have the word: i.e: "110.9H" on the other hand the newer process is like: "356:12"

> 
> I think that in both versions, apps.plugin is missing something:
> 
> * In the version with netmap, the total system CPU utilization is constantly at 67%, but the apps.cpu chart is constantly at 300% (300 shown * 100 / 800 capacity = 37.5% of the total). So it misses about 30%.
> * in the version without netmap, the total system CPU utilization is constantly at 35-40%, but the apps.cpu chart is constantly below 10% (it has some spikes that follow the spikes of the system total). Which means it also misses about 30%.
> 

Both machines have different scenarios (one with a 10Gb NIC with 2-ports and another with a 10Gb NIC with 4-ports) then my application use more threads to run. So we have one with 35-40% and another with 67% of CPU use

> So, I think both chart miss the same thing. This has nothing to do with network or disk traffic. Something else is happening, and it is a bug.
> 
> The fact that I don't see this behavior under Linux, it makes me think this is related to the FreeBSD port of netdata. Somehow, apps.plugin does not get the full list of the processes running. @vlvkobal I need your help on this. Could you please verify apps.plugin is receiving from FreeBSD all the processes running on the system?
> 
> On your snapshots I also see gaps in all the charts. It is important that it happens on all of the them. netdata is multi-threaded. If the gaps were appearing on a few of the charts, then a thread could be locked for some reason. But the fact that they appear on all charts, means the whole process with all its thread were locked.
> 
> When these gaps happen, I see that your disks and ZFS is under pressure (they spike, then a gap, then the spikes fade out).
> 
> ![image](https://user-images.githubusercontent.com/2662304/45977502-853cb680-c052-11e8-8ce8-3672c60d85f3.png)
> 
> It is also interesting that immediately before and after the gap, apps.plugin records that netdata and python.d.plugin have disk reads:
> 
> ![image](https://user-images.githubusercontent.com/2662304/45977392-1eb79880-c052-11e8-9359-2a7fe3ca5dd1.png)
> 
> So I think your kernel is under pressure and probably swaps out (before the gap) and later swaps in (after the gap) netdata. But I am not a FreeBSD guy. I think this is true because of this chart:
> 
> ![image](https://user-images.githubusercontent.com/2662304/45977432-427ade80-c052-11e8-82bc-d9a7ee95f67e.png)
> 
> Major page faults and memory accesses that triggered disk I/O. It is also shown on this chart:
> 
> ![image](https://user-images.githubusercontent.com/2662304/45977858-6a1e7680-c053-11e8-846f-dca1cd605cdd.png)
> 
> So, for the gaps, you system is under memory pressure and swaps. This blocks netdata, which results in gaps at the charts.

Both machines have 8Gb of RAM. One using about 6Gb and another using about 5Gb.

**Comment by vlvkobal** [comment]
A there any errors in netdata log files connected to the missing process?

**Comment by chalfling** [comment]
> Are there any errors in netdata log files connected to the missing process?

I had removed all logs then restart netdata, so I'm running: 
# cat /var/log/netdata/*.log | grep netmap
Exit 1

**Comment by vlvkobal** [comment]
I think it's better to track pid rather than name.

**Comment by chalfling** [comment]
> I think it's better to track pid rather than name.

`:# ps ax | grep netmap`
`98602  4- I    50636:36.98 /usr/local/libexec/netmap`
`98604  4- I        0:00.00 logger -t netmap -p local3.info`

`:# cat /var/log/netdata/*.log | grep 98602`
`Exit 1`

`:# cat /var/log/netdata/*.log | grep 98604`
`Exit 1`

**Comment by chalfling** [comment]
@vlvkobal 
Is there any other test I can do?

Thanks!

**Comment by vlvkobal** [comment]
@chalfling The issue was fixed in #5038. Please update your netdata and test if it works for you.
