### ISSUE TITLE
Netdata release

### ISSUE THREAD

**Issue by gamefundas** [netdata/netdata#4081]
Its been a while since Netdata 1.10. Any new releases being planned out?
Also curious to know what is coming up.

**Comment by Ferroin** [comment]
For reference, last release was on 2018-03-27.

The commit that marked that release was c92349444f88427d8ddef2fb1ac6c4932cf6c8bb, so everything since that will be included.  This currently constitutes a total of 148 merged pull requests, including the following major additions (in roughly chronological order):

* Notification delivery to syslog. #3599
* A plugin for monitoring SpigotMC Minecraft servers (tracking current users and server latency). #3664 
* SSL/TLS support in the SocketService python.d plugin framework (which means that a number of plugins now have native SSL/TLS support). Part of #3670 
* A plugin for monitoring the Unbound recursive caching DNS server.  #3670 #3787
* A startup script for MacOS. #3694 
* Support for user-defined date formatting for Netdata alert (so you can now use ISO 8601 timestamps or whatever else you want).  #3702 #3724
* Tracking of SCTP and UDPLite metrics on Linux. #3705
* Improvements to the bcache monitoring.  #3762 #3765 #3766 
* Removal of the old obsolete web interface (saves a small amount of space and reduces the potential attack surface).  #3767 
* Added support for threading of email notifications (will be disabled by default in release 1.10, but will become the new default in release 1.11). #3768 
* Improvements to time synchronization for python plugins. #3776 
* Support for notifications to rocket.chat. #3777 
* A plugin for monitoring the Litespeed web server. #3782 
* A plugin for monitoring BOINC distributed computing clients. #3786
* Support for notifications to fleep.io. #3794 
* Changes to the BTRFS monitoring charts to make things a bit more clear. #3887 
* A plugin for monitoring active users and sessions tracked by logind. #3815 
* A plugin for monitoring 1-Wire sensor devices. #3822 
* Refactoring and performance improvements for the redis, mdstat, and hddtemp plugins. #3832 #3839 #3841 
* Support for email sender names with spaces in them. #3864 
* Support for notifications to Microsoft Teams. #3903 
* A plugin for monitoring MegaRAID HBA's. #3930 
* Rate-limiting of streaming requests (improves performance and reduces load on the master node). #3938 
* Support for delivering notifications to Amazon Simple Notification Service. #3962 
* Some of the networking related alarms that have high false positive rates have been relaxed a bit. #3976 
* Support for the PowerDNS recursor module in the PowerDNS plugin. #4001 
* A plugin for monitoring Monit instances. #4027 
* Fixes to the parsing logic for `/proc/softirqs` and `/proc/interrupts` to properly handle very large numbers of total interrupts. #4055

**Comment by Ferroin** [comment]
Also, forgot to mention, #3583 will be updated when 1.10 is released with a list of all the changes.

**Comment by gamefundas** [comment]
Thanks for sharing the feature list. Any tentative release date?

**Comment by paulfantom** [comment]
* new docker images based only on alpine

**Comment by ktsaou** [comment]
- support of veritas logic groups naming of disks

I have to go through the whole changelog to start building a release...

**Comment by Ferroin** [comment]
@ktsaou Don't know if it helps, but I built the above list by manually going through the list of PR's that matched the search query `is:pr is:closed merged:>2017-03-27`, which should be everything that got merged since the last release (largely because we don't ever commit directly to the repository).

**Comment by paulfantom** [comment]
And that's why we should have automatic changelog generation based on github labels.

**Comment by Ferroin** [comment]
Oops, meant `is:pr is:closed merged:>2018-03-27`.  That first one goes a year beyond what is needed.

**Comment by ktsaou** [comment]
> And that's why we should have automatic changelog generation based on github labels.

I love you! To prepare a release I need at least 2 days...

**Comment by paulfantom** [comment]
I need ~5 minutes. But I just hit GitHub API rate limiter due to some other thing, so I need to wait for an hour...

I am using it in @cloudalchemy, so it can look like [here](https://github.com/cloudalchemy/ansible-prometheus/blob/master/CHANGELOG.md). That repo has frequent releases so there is not much under "release", but it is a good example.

**Comment by paulfantom** [comment]
It is a matter of running sth like from tld:
```bash
docker run -it --rm \
           -v "$(pwd)":/usr/local/src/your-app \
           ferrarimarco/github-changelog-generator:1.14.3 \
               -u firehol \
               -p netdata \
               --token "${GH_TOKEN}" \
               --release-url https://github.com/firehol/netdata/releases \
               --unreleased-label "**Next release**" \
               --no-compare-link \
               --since-tag 1.10 \
               -o AUTO_CHANGELOG.md
```

And pushing AUTO_CHANGELOG to master with `[ci skip]` in commit msg, so it won't retrigger travis.

**Comment by paulfantom** [comment]
You can even synchronize this changelog with github release by running this after AUTO_CHANGELOG.md is pushed to github:
```bash
docker run -e CHANDLER_GITHUB_API_TOKEN="${GH_TOKEN}" -v "$(pwd)":/chandler -ti whizark/chandler push "${GIT_TAG}"
```

**Comment by paulfantom** [comment]
Created changelog: https://markdownshare.com/view/21a86fe5-21e2-45f6-9c96-6c2ac16b0325

**Comment by ktsaou** [comment]
hm... nice... though not human readable enough.
You say that with tagging we can manage this to be better?

**Comment by paulfantom** [comment]
It is human readable, it is just a lot of content due to very long release cycles. I can also make it show only things merged without adding closed issues.

**Comment by paulfantom** [comment]
I also believe that making 2 reviews mandatory we will have less PRs as they should have more quality content.

**Comment by paulfantom** [comment]
Also this application is very customizable, so I can exclude issues/PR with some label or only include some labels, etc.

It is easier if you just run:
```sh
docker run -it --rm ferrarimarco/github-changelog-generator:1.14.3 -h
```
and see yourself, command will print very meaningful help page.

**Comment by paulfantom** [comment]
It also seems that changlog I posted is invalid.

**Comment by paulfantom** [comment]
@ktsaou This is a correct changelog for the whole project since beginning: https://markdownshare.com/view/56d8a1ef-4a2d-46b6-b068-e2aac3e85822

**Comment by ktsaou** [comment]
This is the human readable form of v1.11.0:

---

> **IMPORTANT**
> This release of netdata fixes known vulnerabilities.
> **All users are advised to update to this version.**

## At a glance

#### Moved to `netdata/netdata`
Netdata now has its **own organization on GitHub**. All references to `firehol/netdata` should be changed to `netdata/netdata`.

#### Modularized and re-structured source code
We have significantly restructured the source tree of netdata. Now everything is modular, and even the hierarchies of modules is now visible in the repo directory structure. We hope the new hierarchy will make it a lot easier for contributors to participate.

#### Moved (most of the) wiki into the repo
We have moved most of the documentation, from the wiki into the repo. This is quite unique. Netdata is one of the first projects that organizes code and docs under the same hierarchy. Browse the repo; **you will be surprised!** Examples: [data collection plugins](https://github.com/netdata/netdata/tree/master/collectors#data-collection-plugins), [database](https://github.com/netdata/netdata/tree/master/database), [backends](https://github.com/netdata/netdata/tree/master/backends), [web server](https://github.com/netdata/netdata/tree/master/web/server), [ARL, including benchmarks](https://github.com/netdata/netdata/tree/master/libnetdata/adaptive_resortable_list), etc.

#### New query engine
The [query engine of netdata](https://github.com/netdata/netdata/tree/master/web/api/queries) has been re-written to support query plugins. We have already added the following algorithms that are available for alarm, charts and badges:

- [`stddev`](https://github.com/netdata/netdata/tree/master/web/api/queries/stddev), for calculating the **standard deviation** on any time-frame.
- [`ses` or `ema` or `ewma`](https://github.com/netdata/netdata/tree/master/web/api/queries/ses), for calculating the **exponential weighted moving average**, or **single/simple exponential smoothing** on any time-frame.
- [`des`](https://github.com/netdata/netdata/tree/master/web/api/queries/des), for calculating the **double exponential smoothing** on any time-frame.
- [`cv` or `rsd`](https://github.com/netdata/netdata/tree/master/web/api/queries/stddev#coefficient-of-variation-cv), for calculating the **coefficient of variation** for any time-frame.

#### Stock config files are now in `/usr/lib/netdata`
We prepare netdata for binary packages. This required stock config files to be overwritten unconditionally when new netdata binary packages are installed. So, all config files we ship with netdata are now installed under `/usr/lib/netdata/conf.d`.

To edit config files, we have supplied the script `/etc/netdata/edit-config` that automatically moves the config file you need to edit to `/etc/netdata` and opens an editor for you.


## Fixed Security Issues

#### Identified by Red4Sec.com
- `CVE-2018-18836` Fixed JSON Header Injection (an attacker could send `\n` encoded in the request to inject a JSON fragment into the response).
- `CVE-2018-18837` Fixed HTTP Header Injection (an attacker could send `\n` encoded  in the request to inject an HTTP header into the response).
- `CVE-2018-18838` Fixed LOG Injection (an attacker could send `\n` encoded in the request to inject a log line at `access.log`).
- `CVE-2018-18839` **Not fixed** Full Path Disclosure, since these are **intended** (netdata reports the absolute filename of web files, alarm config files and alarm handlers).

#### Identified by Synacktiv
- Fixed Privilege Escalation by manipulating `apps.plugin` or `cgroup-network` error handling.
- Fixed LOG injection (by sending URLs with `\n` in them).

## Packaging
- Our **official docker hub images** are now at [`netdata/netdata`](https://hub.docker.com/r/netdata/netdata/). These images are based on **Alpine Linux** for optimal footprint. We provide images for `i386`, `amd64`, `aarch64` and `armhf`.
- the supplied `netdata.service` now allows configuring process scheduling priorities exclusively on `netdata.service` (no need to change `netdata.conf` too).
- the supplied `netdata.service` is now installed in `/usr/lib/systemd/system`.
- Stock netdata configurations are now installed in `/usr/lib/netdata/conf.d` and a new script has been added to allow easily copying and editing config files: `/etc/netdata/edit-config`.

## New Data Collection Modules
- `rethinkdbs` for monitoring RethinkDB performance
- `proxysql` for monitoring ProxySQL performance
- `litespeed` for monitoring LiteSpeed web server performance.
- `uwsgi` for monitoring uWSGI performance
- `unbound` for monitoring the performance of Unbound DNS servers.
- `powerdns` for monitoring the performance of PowerDNS servers.
- `bind_rndc` for monitoring bind name servers, using `rndc`.
- `dockerd` for monitoring the health of dockerd
- `pupper` for monitoring Puppet Server and Puppet DB.
- `logind` for monitoring the number of active users.
- `adaptec_raid` and `megacli` for monitoring the relevant raid controller
- `spigotmc` for monitoring minecraft server statistics
- `boinc` for monitoring Berkeley Open Infrastructure Network Computing clients.
- `w1sensor` for monitoring multiple 1-Wire temperature sensors.
- `monit` for collecting process, host, filesystem, etc checks from monit.
- `linux_power_supplies` for monitoring Linux Power Supplies attributes

## Data Collection Orchestrators Changes
- `node.d.plugin` does not use the `js` command any more.
- `python.d.plugin` now uses `monotonic` clocks. There was a discrepancy in clocks used in netdata that resulted in a shift in time of python module after some time (it was missing 1 sec per day).
- added `MySQLService` for quickly adding plugins using mysql queries.
- `URLService` now supports self-signed certificates and supports custom client certificates.
- all `python.d.plugin` modules that require `sudo` to collect metrics, are now disabled by default, to avoid security alarms on installations that do not need them.

## Improved Data Collection Modules
- `apps.plugin` now detects changes in process file descriptors, also fixed a couple of memory leaks. Its default configuration has been enriched significantly, especially for IoT.
- `freeipmi.plugin` now supports option `ignore-status` to ignore the status reported by given sensors.

#### `statsd.plugin` (for collecting custom APM metrics)
- The charting thread has been optimized for lowering its CPU consumption when several millions of metrics are collected.
- `sets` now report zeros instead of gaps when no data are collected
- `histograms` and `timers` have been optimized for lowering their CPU consumption to support several thousands of such metrics are collected.
- `histograms` had wrong sampling rate calculations.
- `gauges` now ignore sampling rate when no sign is included in the value.
- the minimum sampling rate supported is now 0.001.
- netdata statsd is now drop-in replacement for datadog statsd (although statsd tags are currently ignored by netdata).

#### `proc.plugin` (Linux, system monitoring)
- Unused interrupts and softirqs are not used in charts (this saves quite some processing power and memory on systems with dozens of CPU cores).
- fixed `/proc/net/snmp` parsing of `IcmpMsg` lines that failed on a few systems.
- Veritas Volume Manager disks are now recognized and named accordingly.
- Now netdata collects `TcpExtTCPReqQFullDrop` and re-organizes metrics in charts to properly monitor the TCP SYN queue and the TCP Accept queue of the kernel.
- Many charts that were previously reported as IPv4, where actually reflecting metrics for both IPv4 and IPv6. They have been renamed to `ip.*`.
- netdata now monitors `SCTP`.
- Fixed BTRFS over BCACHE sector size detection.
- BCACHE data collection is now faster.
- `/proc/interrupts` and `/proc/softirqs` parsing fixes.

#### `diskspace.plugin` (Linux, disk space usage monitoring)
- It does not `stat()` excluded mount points any more (it was interfering with kerberos authenticated mount points).
- several filesystems are now by default excluded from disk-space monitoring, to avoid breaking suspend on workstations.

#### `freebsd.plugin` (FreeBSD, PFSense, system monitoring)
- `loundry` memory is now monitored.
- `system.net` and `system.packets` charts added that report the total bandwidth and packets of all physical network interfaces combined.

#### `python.d.plugin` PYTHON modules (applications monitoring)
- `web_log` module now supports virtual hosts, reports http/https metrics, support `squid` logs
- `nginx_plus` module now handles non-continuous peer IDs (bug fix)
- `ipfs` module is optimized, the use of its Pin API is now disabled by default and can enabled with a netdata module option (using the IPFS Pin API increases the load on the IPFS server).
- `fail2ban` module now supports IPv6 too.
- `ceph` module now checks permissions and properly reports issues
- `elasticsearch` module got better error handling
- `nginx_plus` module now uses upstream `ip:port` instead of transient id to identify dimensions.
- `redis`, now it supports Pika, collects evited keys, fixes authentication issues reported and improves exception handling.
- `beanstalk`, bug fix for yaml config loading.
- `mysql`, the % of active connections is now monitored, query types are also charted.
- `varnish`, now it supports versions above 5.0.0
- `couchdb`
- `phpfpm`, now supports IPv6 too.
- `apache`, now supports IPv6 too.
- `icecast`
- `mongodb`, added support for connect URIs
- `postgress`
- `elasticsearch`, now it supports versions above 6.3.0, fixed JSON parse errors
- `mdstat` , now collects `mismatch_cnt`
- `openvpn_log`

#### `node.d.plugin` NODE.JS modules
- `snmp` was incorrectly parsing a new OID names as float. Fixed it.

#### `charts.d.plugin` BASH modules
- `nut` now supports naming UPSes.

## Health Monitoring
- Added variable `$system.cpu.processors`.
- Added alarms for detecting abnormally high load average.
- `TCP` `SYN` and `TCP` accept queue alarms, replacing the old softnet dropped alarm that was too generic and reported many false positives.
- system alarms are now enabled on FreeBSD.
- netdata now reads NIC speed and sets alarms on each interface to detect congestion.
- Network alarms are now relaxed to avoid false positives.
- New `bcache` alarms.
- New `mdstat` alarms.
- New `apcupsd` alarms.
- New `mysql` alarms.
- New notification methods:
	- **rocket.chat**
	- **Microsoft Teams**
	- **syslog**
	- **fleep.io** 
	- **Amazon SNS**

## Backends
- Host tags are now sent to Graphite
- Host variables are now sent to Prometheus

## Streaming
- Each netdata slave and proxy and now filter the charts that are streamed. This allows exposing netdata masters to third parties by limiting the number of charts available at the master.
- Fixed a bug in streaming slaves that randomly prevented them to resume streaming after network errors.
- Fixed a bug that on slaves that sent duplicated chart names under certain conditions.
- Fixed a bug that caused slaves to consume 100% CPU (due to a misplaced lock) when multiple threads were adding dimensions on the same chart.
- The receiving nodes of streaming (netdata masters and proxies) can now rate-limit the rate of inbound streaming requests received.
- Re-worked time synchronization between netdata slaves and masters.

## API
- Badges that report time, now show `undefined` instead of `never`.

## Dashboard
- Added `UTC` timezone to the list of available time-zones.
- The dashboard was sending some non-HTTP compliant characters at the URLs that made netdata dashboards break when used under certain proxies. Fixed.
