### ISSUE TITLE
Archive metrics to mongoDB

### ISSUE THREAD

**Issue by vrst37** [netdata/netdata#4096]
How to get mongoDB backend for netdata?

I tried with the following setup and was unable to see any data stream/tables etc into mongoDB

```
[backend]
        enabled = yes
        type = json
        destination = localhost:27017
        data source = average
        prefix = netdata
        update every = 10
        buffer on failures = 10
        timeout ms = 20000
        send charts matching = *
        send names instead of ids = yes
```

**Comment by ktsaou** [comment]
Hi,

I am not sure it will work like that. Netdata does not know how to send data to mongodb. The json backend just connects to a socket and pushes json data. I think mongodb needs some special communication.

So this is a request for new backend.

**Comment by rirze** [comment]
Are there any further thoughts on this? This would be a great feature to have and would prevent me from scraping the metrics with a custom script.

**Comment by ilyam8** [comment]
@rirze 	is mongodbdb ok for such tasks? i thought it is not based choice

https://www.influxdata.com/blog/influxdb-is-27x-faster-vs-mongodb-for-time-series-workloads/

**Comment by rirze** [comment]
I wouldn't mind using InfluxDB but all of our DB infrastructure is in MongoDB. I would imagine there being a lot of inertia for switching to InfluxDB specifically for this task. If there is any way mongodb could be supported as a backend for netdata, that would be greatly appreciated. Thanks!

**Comment by hazcod** [comment]
Since influxdb isn't offered as a hosted solution on the major cloud providerrs, is mongodb our only option here?

**Comment by cakrit** [comment]
The Prometheus remote write API we introduced in v1.15.0 gives you many additional options. 
See https://prometheus.io/docs/operating/integrations/#remote-endpoints-and-storage
and https://docs.netdata.cloud/backends/prometheus/remote_write/

We also support AWS Kinesis backends: https://docs.netdata.cloud/backends/aws_kinesis/

We need an update on the main README, because we're not clear on what's supported.

**Comment by cakrit** [comment]
@vlvkobal we need updates to https://github.com/netdata/netdata#integrations and the main Wiki page that has the same content.
In addition, https://github.com/netdata/netdata/tree/master/backends#features should list at least the most popular providers that we can stream to, using the prometheus write API. The link to the prometheus page needs to remain of course, because more could be added at any time.

**Comment by rirze** [comment]
That definitely looks like an impressive list of backends. However, I don't think mongodb is supported. At the very least, it would suffice to have the 'json db export' option in netdata support authentication (eg. username, password). That way I can have it point to a rEST endpoint that inserts into the mongodb database.

**Comment by cakrit** [comment]
But the JSON export is something you poll for today. We need a new backend, as the OP states. @vlvkobal put this on your roadmap, as there's sufficient interest in it.

**Comment by vlvkobal** [comment]
@rirze Could you test #6524?

**Comment by ilyam8** [comment]
@vrst37 ^^

**Comment by hazcod** [comment]
Does this also mean we can use the netdata dashboard to view archived metrics?
Or is this sending only?

**Comment by vlvkobal** [comment]
This is sending only.
