### ISSUE TITLE
java charts on wiki ref to 404

### ISSUE THREAD

**Issue by benwh4** [netdata/netdata#4100]
Hello 
I wonder if it was migrated.

The conf of java charts link to 404 web pages : 

  - https://github.com/firehol/netdata/blob/master/conf.d/java.d/jmx.conf
  - https://github.com/firehol/netdata/blob/master/conf.d/python.d/stringboot.conf

Does anyone have another link to configure charts for java application ?

**Comment by simonnagl** [comment]
These links are dead because the MR introducing these links is still open(https://github.com/firehol/netdata/pull/2663). Sorry for that! If you want java charts you currently have two options.
1. Using the MR
2. Using https://github.com/simonnagl/netdata-plugin-java-daemon

Both is generally the same. I started implementing the project in the repository and then moved development into the MR. Currently I have no time / not enough motivation to continue the development. If you want to contribute please do so. I sure will find some time to review your code. Also, if you have further questions on how to configure the plugin be free to ask. Sorry again for the freeze in further development.

**Comment by ktsaou** [comment]
I think we can close this.
if the problem remains, please post here.
