### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by paulfantom** [netdata/netdata#4146]
As we have some requirements before merging PR it would be good to create CONTRIBUTING.md doc with everything outlined.

Good template for such file is in https://github.com/nayafia/contributing-template

**Comment by ktsaou** [comment]
Yes, this would be nice!
We also have a checklist when new plugins are added.

**Comment by paulfantom** [comment]
I don't know what is the acceptance procedure, so I cannot write this doc. Who wants to do that?

**Comment by Ferroin** [comment]
I can cover the new-plugin checklist part, assuming that everyone is OK with what we already have [on the wiki](https://github.com/firehol/netdata/wiki/New-Module-PR-Checklist).

**Comment by ktsaou** [comment]
Yes, though it needs a little bit more info (charts.d is missing, several sections are python.d only, etc).

It does not request updating this page: https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata

It is also missing the infographic update.

**Comment by paulfantom** [comment]
> It is also missing the infographic update.

No infographics in CONTRIBUTING.md please.

**Comment by ktsaou** [comment]
It should be updated somehow. If we don't add it there, we will have to do it...
The infographic is a file in the repo.

**Comment by Ferroin** [comment]
> Yes, though it needs a little bit more info (charts.d is missing, several sections are python.d only, etc).

> It does not request updating this page: https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata

Yeah, it could stand to be updated somewhat.

> It should be updated somehow. If we don't add it there, we will have to do it...
The infographic is a file in the repo.

Are we sure we want random people updating the infographic though?  I mean, that's one of the primary marketing tools, so it would be _really_ good to have a smaller group of people doing it as appropriate.  Also, given the highly condensed format being used, it's not exactly something that's _easy_ for people to update.

**Comment by paulfantom** [comment]
CONTRIBUTING.md should be a simple text-only file. Not a book with pictures.

**Comment by paulfantom** [comment]
Sorry, I misunderstood you.

**Comment by ktsaou** [comment]
> Are we sure we want random people updating the infographic though? I mean, that's one of the primary marketing tools, so it would be really good to have a smaller group of people doing it as appropriate. Also, given the highly condensed format being used, it's not exactly something that's easy for people to update.

You are probably right. This requires searching for a proper logo, adding it to a github issue to get a permanent high-speed URL, pasting it properly in draw.io to link the github URL - not the image itself, re-arranging a lot of other logos to make room, adding the new logo and linking it to the wiki page, saving the new infographic in png, adding it to a github issue to get another URL, editing README.md and the wiki home to replace the existing infographic image.

So, yes, this is subject to a lot of errors...

**Comment by cakrit** [comment]
Blocked By: #4394

**Comment by cakrit** [comment]
Taking from #4391:

> Almost no one reads READMEs which are far down in directory layout. This should be in documentation.

Documentation will collect individual READMEs automatically and organize them appropriately. 

> CONTRIBUTING.md should exist as one simple file as the intention of that file is to engage new contributors into taking action and contributing to project by following simple guidelines. This cannot be some distributed multi-page document.

I will try to make it a single document and see what we end up with. If it can remain simple, we will keep it as one. Do note that when I try to work on a specific item, I need the documentation for that specific item handy. 

Merged the following sources...
Writing-Plugins
New-Module-PR-Checklist
How-to-write-new-module
to create https://github.com/cakrit/netdata-doc/blob/master/source/md/CONTRIBUTING.md
It currently refers only to the README template at 
https://github.com/cakrit/netdata-doc/blob/master/source/md/README-Template.md

The README template is very tightly linked to this, so let's close #4394 first. You'll notice that in the instructions I removed lines instructing people to put their documentation in various other files and instruct them to create a single README.md will all the info there, in the same directory as their code.

It's already pretty big and missing content on adding internal plugins and third party plugins (though if I understand correctly, those are just a special case of external plugins.

Question: Do we keep the following two as separate files? I think we should
CONTRIBUTORS.md
CODE_OF_CONDUCT.md

**Comment by ktsaou** [comment]
I am ok with that.
I would add a list of maintainers for each plugin.

**Comment by cakrit** [comment]
Contributing tells people what they need to do. Documentation is one of the things they need to do, it was already required in the PR guidelines. Each module needs a readme

**Comment by cakrit** [comment]
> I propose do do this in a file header. This way it will be easier to find a maintainer when a PR touching such file is created.

Can you provide an example for a specific plugin? What would that header file look like?

**Comment by paulfantom** [comment]
CONTRIBUTING.md should contain a short guide on **how** people can help, not what they **need to do**.

**Comment by paulfantom** [comment]
As for header, simple:
```bash
# Maintainers: @paulfantom 
```

will be enough. It is similar to current "Author" section ex. https://github.com/netdata/netdata/blob/1ad4f1bcfc691120102b57dbd426de0870abd76f/python.d/beanstalk.chart.py#L3

**Comment by paulfantom** [comment]
Good example of contributing.md file: https://github.com/atom/atom/blob/master/CONTRIBUTING.md

More on the subject: https://mozillascience.github.io/working-open-workshop/contributing/

**Comment by cakrit** [comment]
> Good example of contributing.md file: 
The example is 80% what they need to do (styleguides etc.). The content in the draft I sent is almost everything we have written right now (though I'm sure there are some scattered sentences in other wiki pages as well) . Good point that it needs to start with a list of things we'd like people to do, but we still need to tell them how they need to do it, as your example does

**Comment by cakrit** [comment]
The second link is really good too. I will use the two examples to improve it. Instructions  definitely belong there too. I really like the suggestion to tell them how to test it. Is there anything we can tell them to do other than try it on their browser with a local installation?

**Comment by cakrit** [comment]
- I pulled out all the details on the plugins except for the PR checklists which need to remain there. I moved those details to "External Plugins"
- Added link to "External Plugins", which is similar to atom's "Contributing to atom packages". 
- Moved to contributing a section from the netdata home page that says what we want people to do. Removed the documentation part though, too many things moving to ask people to contribute right now. 

There's a lot more to do, but it's a start.

**Comment by cakrit** [comment]
Accidentally deleted this from here instead of from #4196
Adding the latest comments from there as well. 

Almost no one reads READMEs which are far down in directory layout. This should be in documentation.

Documentation will collect individual READMEs automatically and organize them appropriately.

CONTRIBUTING.md should exist as one simple file as the intention of that file is to engage new contributors into taking action and contributing to project by following simple guidelines. This cannot be some distributed multi-page document.

I will try to make it a single document and see what we end up with. If it can remain simple, we will keep it as one. Do note that when I try to work on a specific item, I need the documentation for that specific item handy.

These are the sources we have right now, which I will put together in one big CONTRIBUTING.md:

https://netdata-doc.readthedocs.io/en/latest/Writing-Plugins/
https://netdata-doc.readthedocs.io/en/latest/New-Module-PR-Checklist/
https://netdata-doc.readthedocs.io/en/latest/How-to-write-new-module/

Question: Do we keep the following two as separate files? I think we should
CONTRIBUTORS.md
CODE_OF_CONDUCT.md

ktsaou commented 20 hours ago
CONTRIBUTORS.md

This is the Contributors License Agreement

CODE_OF_CONDUCT.md

This is how we behave and the behavior we accept. This should be a bit more broad (not only about contributors).

**Comment by ktsaou** [comment]
A first version of it (first 2 section by me, the others are template):
I'll finish the first 2 sections. Who can contribute to the next ones?

---


# Introduction

Thank you for considering contributing to Netdata.

We love to receive contributions. Maintaining a platform for monitoring everything imaginable, requires a broad understanding of a plethora of technologies, systems and applications. We rely on community contributions and user feedback to continue providing the best monitoring solution out there.

There are many ways to contribute, with varying requirements of skills:

#### Give Netdata a GitHub star

This is the minimum open-source users should contribute back to the projects they use. Github stars help the project gain visibility, stand out. So, if you use Netdata, consider pressing that button. **It really matters**.

#### Spread the word

Community growth allows the project to attract new talent willing to contribute. This talent is then developing new features and improves the project. These new features and improvements attract more users and so on. It is a loop. So, post about netdata, present it to local meetups you attend, let your online social network or twitter, facebook, reddit, etc. know you are using it. **The more people involved, the faster the project evolves**.

#### Give feedback

Is there anything that bothers you about netdata? Did you experience an issue while installing it or using it? Would you like to see it evolve to you need? Let us know. Open a github issue to discuss it. Feedback is very important for open-source projects. We can't commit we will do everything, but your feedback influences our road-map significantly. **We rely on your feedback to make Netdata better**.

#### Help other users

As the project grows, an increasing share of our time is spent on supporting this community of users in terms of answering questions, of helping users understand how netdata works and find their way with it. Helping other users is crucial. It allows the developers and maintainers of the project to focus on improving it.

#### Improve documentation

#### Help the developers understand what they have to do

#### Develop new data collection plugins

#### Help us package Netdata

# Ground Rules

#### Performance and efficiency

Everything on Netdata is about efficiency. We need netdata to always be the most lightweight monitoring solution available. We will reject to merge PRs that are not optimal in resource utilization and efficiency.

Of course there are cases that such technical excellence is either not reasonable or not feasible. In these cases, we may require the feature or code submitted to be by disabled by default.

#### Meaningful metrics

Unlike other monitoring solutions, Netdata requires all metrics collected to have some structure attached to them. So, Netdata metrics have a name, units, belong to a chart that has a title, a family, a context, belong to an application, etc.

This structure is what makes netdata different. Most other monitoring solution collect bulk metrics in terms of name-value pairs and then expect their users to give meaning to these metrics during visualization. This does not work. It is neither practical nor reasonable to give to someone 2000 metrics and let him/her visualize them in a meaningful way.

So, netdata requires all metrics to have a meaning at the time they are collected.  We will reject to merge PRs that loosely collect just a "bunch of metrics", but we are very keen to help you fix this.

#### Automated Testing

Netdata is a very large application to have automated testing end-to-end. But automated testing is required for crucial functions of it.

Generally, all pull requests should be coupled with automated testing scenarios. However since we do not currently have a framework in place for testing everything little bit of it, we currently require automated tests for parts of Netdata that seem too risky to be changed without automated testing.

Of course, manual testing is always required.

#### Netdata is a distributed application

Netdata is a distributed monitoring application. A few basic features can become quite complicated for such applications. We may reject features that alter or influence the nature of netdata, though we usually discuss the requirements with contributors and help them adapt their code to be better suited for Netdata.

#### Operating systems supported

Netdata should be running everywhere, on every production system out there.

Although we focus on **supported operating systems**, we still want Netdata to run even on non-supported systems. This, of course, may require some more manual work from the users (to prepare their environment, or enable certain flags, etc).

If your contributions limit the number of operating systems supported we will request from you to improve it.

#### Documentation

Your contributions should be bundled with related documentation to help users understand how to use the features you introduce.

#### Maintenance

When you contribute code to Netdata, you are automatically accepting that you will be responsible for maintaining that code in the future. So, if users need help, or report bugs, we will invite you to the related github issues to help them or fix the issues or bugs of your contributions.

---

INSTRUCTIONS BELLOW THIS POINT

---

# Your First Contribution
Help people who are new to your project understand where they can be most helpful. This is also a good time to let people know if you follow a label convention for flagging beginner issues.

> Unsure where to begin contributing to Atom? You can start by looking through these beginner and help-wanted issues:
> Beginner issues - issues which should only require a few lines of code, and a test or two.
> Help wanted issues - issues which should be a bit more involved than beginner issues.
> Both issue lists are sorted by total number of comments. While not perfect, number of comments is a reasonable proxy for impact a given change will have.

[source: [Atom](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#your-first-code-contribution)] **Need more inspiration?** [1] [Read the Docs](http://docs.readthedocs.org/en/latest/contribute.html#contributing-to-development) [2] [Django](https://docs.djangoproject.com/en/dev/internals/contributing/new-contributors/#first-steps) (scroll down to "Guidelines" as well)

### Bonus points: Add a link to a resource for people who have never contributed to open source before.
Here are a couple of friendly tutorials you can include: http://makeapullrequest.com/ and http://www.firsttimersonly.com/

> Working on your first Pull Request? You can learn how from this *free* series, [How to Contribute to an Open Source Project on GitHub](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github).

[source: [React](https://github.com/facebook/react/blob/master/CONTRIBUTING.md#pull-requests)]  

As a side note, it helps to use newcomer-friendly language throughout the rest of your document. Here are a couple of examples from [Active Admin](https://github.com/activeadmin/activeadmin/blob/master/CONTRIBUTING.md):

>At this point, you're ready to make your changes! Feel free to ask for help; everyone is a beginner at first :smile_cat:
>
>If a maintainer asks you to "rebase" your PR, they're saying that a lot of code has changed, and that you need to update your branch so it's easier to merge.

# Getting started
### Give them a quick walkthrough of how to submit a contribution.
How you write this is up to you, but some things you may want to include:

* Let them know if they need to sign a CLA, agree to a DCO, or get any other legal stuff out of the way
* If tests are required for contributions, let them know, and explain how to run the tests
* If you use anything other than GitHub to manage issues (ex. JIRA or Trac), let them know which tools they’ll need to contribute

>For something that is bigger than a one or two line fix:

>1. Create your own fork of the code
>2. Do the changes in your fork
>3. If you like the change and think the project could use it:
    * Be sure you have followed the code style for the project.
    * Sign the Contributor License Agreement, CLA, with the jQuery Foundation.
    * Note the jQuery Foundation Code of Conduct.
    * Send a pull request indicating that you have a CLA on file.

[source: [Requirejs](http://requirejs.org/docs/contributing.html)] **Need more inspiration?** [1] [Active Admin](https://github.com/activeadmin/activeadmin/blob/master/CONTRIBUTING.md#1-where-do-i-go-from-here) [2] [Node.js](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#code-contributions) [3] [Ember.js](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#pull-requests)

### If you have a different process for small or "obvious" fixes, let them know.

> Small contributions such as fixing spelling errors, where the content is small enough to not be considered intellectual property, can be submitted by a contributor as a patch, without a CLA.
>
>As a rule of thumb, changes are obvious fixes if they do not introduce any new functionality or creative thinking. As long as the change does not affect functionality, some likely examples include the following:
>* Spelling / grammar fixes
>* Typo correction, white space and formatting changes
>* Comment clean up
>* Bug fixes that change default return values or error codes stored in constants
>* Adding logging messages or debugging output
>* Changes to ‘metadata’ files like Gemfile, .gitignore, build scripts, etc.
>* Moving source files from one directory or package to another

[source: [Chef](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-obvious-fix-policy)] **Need more inspiration?** [1] [Puppet](https://github.com/puppetlabs/puppet/blob/master/CONTRIBUTING.md#making-trivial-changes)

# How to report a bug
### Explain security disclosures first!
At bare minimum, include this sentence:
> If you find a security vulnerability, do NOT open an issue. Email XXXX instead.

If you don’t want to use your personal contact information, set up a “security@” email address. Larger projects might have more formal processes for disclosing security, including encrypted communication. (Disclosure: I am not a security expert.)

> Any security issues should be submitted directly to security@travis-ci.org
> In order to determine whether you are dealing with a security issue, ask yourself these two questions:
> * Can I access something that's not mine, or something I shouldn't have access to?
> * Can I disable something for other people?
>
> If the answer to either of those two questions are "yes", then you're probably dealing with a security issue. Note that even if you answer "no" to both questions, you may still be dealing with a security issue, so if you're unsure, just email us at security@travis-ci.org.

[source: [Travis CI](https://github.com/travis-ci/travis-ci/blob/master/CONTRIBUTING.md)] **Need more inspiration?** [1] [Celery](https://github.com/celery/celery/blob/master/CONTRIBUTING.rst#security) [2] [Express.js](https://github.com/expressjs/express/blob/master/Security.md)

### Tell your contributors how to file a bug report.
You can even include a template so people can just copy-paste (again, less work for you).

> When filing an issue, make sure to answer these five questions:
>
> 1. What version of Go are you using (go version)?
> 2. What operating system and processor architecture are you using?
> 3. What did you do?
> 4. What did you expect to see?
> 5. What did you see instead?
> General questions should go to the golang-nuts mailing list instead of the issue tracker. The gophers there will answer or ask you to file an issue if you've tripped over a bug.

[source: [Go](https://github.com/golang/go/blob/master/CONTRIBUTING.md#filing-issues)] **Need more inspiration?** [1] [Celery](https://github.com/celery/celery/blob/master/CONTRIBUTING.rst#other-bugs ) [2] [Atom](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#reporting-bugs) (includes template)

# How to suggest a feature or enhancement
### If you have a particular roadmap, goals, or philosophy for development, share it here.
This information will give contributors context before they make suggestions that may not align with the project’s needs.

> The Express philosophy is to provide small, robust tooling for HTTP servers, making it a great solution for single page applications, web sites, hybrids, or public HTTP APIs.
>
> Express does not force you to use any specific ORM or template engine. With support for over 14 template engines via Consolidate.js, you can quickly craft your perfect framework.

[source: [Express](https://github.com/expressjs/express#philosophy)] **Need more inspiration?** [Active Admin](https://github.com/activeadmin/activeadmin#goals)

### Explain your desired process for suggesting a feature.
If there is back-and-forth or signoff required, say so. Ask them to scope the feature, thinking through why it’s needed and how it might work.

> If you find yourself wishing for a feature that doesn't exist in Elasticsearch, you are probably not alone. There are bound to be others out there with similar needs. Many of the features that Elasticsearch has today have been added because our users saw the need. Open an issue on our issues list on GitHub which describes the feature you would like to see, why you need it, and how it should work.

[source: [Elasticsearch](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#feature-requests)] **Need more inspiration?** [1] [Hoodie](https://github.com/hoodiehq/hoodie/blob/master/CONTRIBUTING.md#feature-requests) [2] [Ember.js](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#requesting-a-feature)

# Code review process
### Explain how a contribution gets accepted after it’s been submitted.
Who reviews it? Who needs to sign off before it’s accepted? When should a contributor expect to hear from you? How can contributors get commit access, if at all?

> The core team looks at Pull Requests on a regular basis in a weekly triage meeting that we hold in a public Google Hangout. The hangout is announced in the weekly status updates that are sent to the puppet-dev list. Notes are posted to the Puppet Community community-triage repo and include a link to a YouTube recording of the hangout.
> After feedback has been given we expect responses within two weeks. After two weeks we may close the pull request if it isn't showing any activity.

[source: [Puppet](https://github.com/puppetlabs/puppet/blob/master/CONTRIBUTING.md#submitting-changes)] **Need more inspiration?** [1] [Meteor](https://meteor.hackpad.com/Responding-to-GitHub-Issues-SKE2u3tkSiH ) [2] [Express.js](https://github.com/expressjs/express/blob/master/Contributing.md#becoming-a-committer)

# Community
If there are other channels you use besides GitHub to discuss contributions, mention them here. You can also list the author, maintainers, and/or contributors here, or set expectations for response time.

> You can chat with the core team on https://gitter.im/cucumber/cucumber. We try to have office hours on Fridays.

[source: [cucumber-ruby](https://github.com/cucumber/cucumber-ruby/blob/master/CONTRIBUTING.md#talking-with-other-devs)] **Need more inspiration?**
 [1] [Chef](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#-developer-office-hours) [2] [Cookiecutter](https://github.com/audreyr/cookiecutter#community)

# BONUS: Code, commit message and labeling conventions
These sections are not necessary, but can help streamline the contributions you receive.

### Explain your preferred style for code, if you have any.

**Need inspiration?** [1] [Requirejs](http://requirejs.org/docs/contributing.html#codestyle) [2] [Elasticsearch](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-to-the-elasticsearch-codebase)

### Explain if you use any commit message conventions.

**Need inspiration?** [1] [Angular](https://github.com/angular/material/blob/master/.github/CONTRIBUTING.md#submit) [2] [Node.js](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#step-3-commit)

### Explain if you use any labeling conventions for issues.

**Need inspiration?** [1] [StandardIssueLabels](https://github.com/wagenet/StandardIssueLabels#standardissuelabels) [2] [Atom](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#issue-and-pull-request-labels)

**Comment by Ferroin** [comment]
Just thought of this, but it seems to me that a number of the sections could easily have links to appropriate GitHub documentation to provide supplemental information.  For example, the code review section could have a link to the [GitHub page about required reviews for pull requests](https://help.github.com/articles/about-required-reviews-for-pull-requests/).

Also, we are enforcing a particular coding style on new contributions, so we should document it here.  Ideally, we should have a section for each language in use, since the conventions we are using are largely language specific.

Not 100% sure, but it might be worth doing special documents for contributions to particular sections (eg, a special one for contributing to the python.d plugin, a separate one for contributions to the web interface, etc). Without that, this is likely to get _very_ long if we want to do a checklist that people need to verify against before making a PR, because there will be many conditional sections to it.

**Comment by ktsaou** [comment]
> Not 100% sure, but it might be worth doing special documents for contributions to particular sections (eg, a special one for contributing to the python.d plugin, a separate one for contributions to the web interface, etc). Without that, this is likely to get _very_ long if we want to do a checklist that people need to verify against before making a PR, because there will be many conditional sections to it.

I like that. A `CONTRIBUTING.md` at https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin

**Comment by Ferroin** [comment]
In that, case, a decent percentage of the stuff for submitting PR's can probably just be links pointing at individual documents.  I can look at writing up the basis of one for the Python plugin.  Do we possibly want to document the basic API in these too?

**Comment by Ferroin** [comment]
I don't know of any that embed it as separate files, but I do know quite a few that do it as inline documentation in the code itself.  See for example the various Python-based modules in Ansible, they all have a docstring for the module itself that contains all the actual documentation for the module.  I'm actually kind of against that approach personally though, because it will produce a number of files that are more documentation than code, and it can lead to unnecessary memory overhead for Python modules (the whole docstring for the module stays in memory for the whole time the module is loaded, which would translate to a roughly 300k+ increase in runtime memory overhead for the python.d plugin with everything enabled).

**Comment by Ferroin** [comment]
Also, When I finally get some time to work on it, I'll look at getting the python.d API documented in-tree.

**Comment by paulfantom** [comment]
We can write `TBD` in sections which are incomplete and finish them later.

**Comment by ktsaou** [comment]
A `REFERENCE.md` could be used in many places. This should document all the options available or APIs available, etc. So, developers could know that at least `REFERENCE.md` needs updating when things are added, removed or are changed.

So:

- `README.md` = end user description of what this is it and how it works
- `REFERENCE.md` = each and every option available for this
- `CONTRIBUTING.md` = documentation, how-tos, walk-throughs for contributing to this.

Also, to avoid deduplication we should somehow modularized common things. For example, the way `simple patterns` work is documented many times. But we have this: https://github.com/netdata/netdata/tree/master/libnetdata/simple_pattern - so every reference to "simple pattern" could be just a link.

The happens for sockets binding `bind to` settings in netdata. We could document them here https://github.com/netdata/netdata/tree/master/libnetdata/socket
