### ISSUE TITLE
Alarms should check the state of other alarms

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#4154]
As mentioned in https://github.com/firehol/netdata/issues/1076#issuecomment-407023368, the `system.softnet_stat` alarms are largely only useful for indicating causes of high packet drop rates, but have an insanely high false positive rate because most systems regularly display the conditions that trigger them even though they are having no networking issues whatsoever.

Ideally, there would be some logic in the alarm handling stuff that correlates spikes in packet drops and spikes in the metrics being tracked by these alarms, and only triggers the alarms if there is a correspondingly high rate of packet drops.

Relevant to #1076, and probably some others too.

**Comment by ktsaou** [comment]
@cakrit 	this is very important. Without this feature combined alarms cannot be easily created.

**Comment by cakrit** [comment]
Assigning to myself for triage.

**Comment by thiagoftsm** [comment]
Hi everyone,

After to finish the PR #6560 I could understand better the way the Netdata database works and my suggestion for we do this issue is to bring for Netdata something analogous the "WHERE" and/or "JOIN" used in the SQL statements, in resume we will let two or more alarms run and get their final result, after this we combine the results checking case they are true so we send the alarm for the user. I think the better keyword to use in the alarms for this case will be the "JOIN" and its arguments can be one of the following cases:

- the name of other alarm : When we have this so every time that both alarms are raised we send a message
- the name of other alarm plus a condition: For this case the other alarm must raise and reach a specific level.

@Ferroin , do you believe with these changes we can reach what you imagined?

Best Regards.!

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
