### ISSUE TITLE
web files should be owned by root:netdata, with permission 0644

### ISSUE THREAD

**Issue by jorti** [netdata/netdata#4173]
I'm having trouble accessing the web server which is running by the user netdata and the files in /usr/share/netdata are owned by root.

```
File '/usr/share/netdata/web//index.html' is owned by user 0 (expected user 411). Access Denied.
```
I see at this [comment](https://github.com/firehol/netdata/issues/52#issuecomment-177582297) that this is a "security rule". How can it be more secure that the webserver owns and can modify its own files? I classify this more like a security hole, because any bug in the webserver software allow a remote user to modify the files to whatever purpose.

**Comment by ktsaou** [comment]
How did you install netdata? Did an installer left it like that?

The permissions expected by netdata are defined in `netdata.conf`:

```
[web]
	web files owner = netdata
	web files group = netdata
```

netdata does not allow any other files to be served.

A few users prefer to have the web files owned by `root` so that the web server will not be able to write there (there is no code in netdata that writes web files, but these people assume that somehow netdata got hijacked).

The default permissions shipped by us, prefer these files to be owned by `netdata:netdata`.

**Comment by jorti** [comment]
The installation is a bit special, it is the package distributed by OpenWrt and modified by me.

Thanks for pointing out the configurations options, that'll be enough for me.

Anyway, consider your policy of owning the web files, I think it's a potential security hole, much better to be owned by root, so the webserver can only access in read-only mode to them.

Thank you.

**Comment by ktsaou** [comment]
The only reason I don't like files to be owned by `root`, is that really a lot of files are owned by `root` in a system. This means that netdata can potentially send them over the wire. There is code that prevents `..` in URLs, so netdata will reject such requests, but still there is code that sends files, which could potentially be manipulated to bypass that `..` check (I don't have any proof it can be manipulated - this is a speculation).

So, I strongly suggest that the best permissions are "root:netdata" with 0644.

The only reason I haven't changed this already, is that netdata can be installed as a normal user. No need for root. This means the installer has to apply different permissions depending on who installs it.

I guess it is it time to be done though... So, let me fix this now...

**Comment by ktsaou** [comment]
It is a chicken-egg problem:

The netdata binary has to be compiled with a default with the web files owner. The fact that compilation runs as a user, should not affect the default. The same is true for the user starting up netdata. For example, systemd starts netdata as user `netdata`, not `root`.

The installer, that knows how it installs netdata, should not change the web files to `root:user` when running as a normal user. If it does, it will not be able to update them later.

So, I think the only solution is:

1. when the **installer runs as a normal user**
2. alter `netdata.conf`, and set `netdata web user = user`, replacing `netdata web user = root`.

@paulfantom @Ferroin what do you think?

**Comment by paulfantom** [comment]
From security point of view self-updating code is not great and also applying `root:user` file permissions is recommended. This goes especially for web applications. However RHEL STIG says only that file permissions shouldn't be greater than default ones applied by vendor (https://www.stigviewer.com/stig/red_hat_enterprise_linux_7/2017-12-14/finding/V-71849), so it could mean that we are ok with 

We could probably look how software like nextcloud do it.


> The only reason I don't like files to be owned by root, is that really a lot of files are owned by root in a system. 

And that is a good thing. Files owned by root are a security feature since, if used correctly, they cannot be changed by anyone apart from root. CoreOS Container Linux extended this concept to a degree where even root cannot modify most of the files.

> The installer, that knows how it installs netdata, should not change the web files to root:user when running as a normal user. If it does, it will not be able to update them later.

If installer do any kind of privilege escalation then files should have `root:user` permissions. If it doesn't then there is no need to change permissions.

**Comment by alokraj68** [comment]
This issue is killing one of my servers, everyday its filling all the space in server
