### ISSUE TITLE
stock config files should be in `/usr/lib/netdata/`

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#4182]
Today netdata installs the default config files in `/etc/netdata`. 

This has the problem that the default ones supplied by us and the user edited ones are merged, in one directory structure.

To solve this problem during updates, the netdata installer maintains an MD5 hash of all versions of all config files ever supplied by us, and compares all files in `/etc/netdata` with these hashes to check if any file has been modified.

A better solution would be to install all default config files in `/usr/lib/netdata`. The installer will overwrite them, without checking anything. Any user willing to change a default file, should copy it under `/etc/netdata` and edit it.

The full list of actions is at #4283

**Comment by paulfantom** [comment]
This should be high priority as it will be also needed for packaging netdata.

**Comment by ktsaou** [comment]
ok, we need @l2isbad for this.
And it would require quite some testing. It touches almost every component of netdata.

**Comment by Ferroin** [comment]
I'm all for not having to deal with manually merging config updates in `/etc`.

That said, for the modules that don't need _any_ configuration by default (for example, the various Python modules), do we really _need_ to install the config in `/usr/lib`, instead of say, dropping a template in `/usr/share` where a lot of other packages put things?  Alternatively, perhaps we could have the config files in `/usr/lib` anyway, but have them actually contain the default configuration for the modules instead of being functionally empty files?

**Comment by paulfantom** [comment]
I agree with @Ferroin, when we ship config files which are only comments, then those should be put in `/usr/share`. 

There is a convention of putting configs which are needed to start program in `/usr/lib` and those which are not needed (due to program having embedded default values) in `/usr/share`.

**Comment by Ferroin** [comment]
A couple of other points I just thought of:

* The README files from the plugin directories should be in `/usr/share` too, not in `/usr/libexec`.  Not sure if it makes sense to handle these as part of the same movement of config files or not.
* It probably makes sense to have a dedicated `config` subdirectory in both `/usr/lib/netdata` and `/usr/share/netdata` to actually store the configs.  That way, when we inevitably need to put other stuff in either location, we don't have to worry about people confusing it and the configuration.

**Comment by ktsaou** [comment]
## Discussion

I would to discuss a bit how this will work.

### health.d

> Today netdata reads all config files matching `/etc/netdata/health.d/*.conf`. We will provide stock health configs in `/usr/lib/netdata/conf.d/health.d/*.conf`. How this should now work?

A solution could be to load:

1. All files matching `/etc/netdata/health.d/*.conf`
2. All files matching `*.conf` in `/usr/lib/netdata/conf.d/health.d/` which are not present (same sub-directory and filename) in `/etc/netdata/health.d/`.

The above means the directory `/etc/netdata/health.d` has precedence over `/usr/lib/netdata/conf.d/health.d`, even for alarms of the same name that are defined in different directories.

---

### statsd.d synthetic charts

We don't ship any by default. Should we support loading statsd synthetic charts from `/usr/lib/netdata/health.d/statsd.d` ?

---

### stream.conf

The default `stream.conf` is a placeholder. It does not define anything.

Should we support loading stream configuration from `/usr/lib/netdata/conf.d/stream.conf` ?

**Comment by paulfantom** [comment]
> The above means the directory /etc/netdata/health.d has precedence over /usr/lib/netdata/conf.d/health.d, even for alarms of the same name that are defined in different directories.

Yes, that's exectly how it should work. It should have the same behavior as with every module config otherwise it will just create confusion.

> We don't ship any by default. Should we support loading statsd synthetic charts from /usr/lib/netdata/health.d/statsd.d

We should, configuration loading mechanism should be the same for everything. We might ship without files in this directory but mechanism should be preserved.

> Should we support loading stream configuration from /usr/lib/netdata/conf.d/stream.conf

Yes, for the same reasons as above.

**Comment by Ferroin** [comment]
I would also suggest having things that are largely just placeholders (that is, configs that get parsed as being empty by default) like the default `stream.conf` in `/usr/share/netdata`.  Netdata shouldn't parse anything from there, but we should keep the placeholder configs around _somewhere_ as they provide easy documentation of the file formats, and most people are likely to look in `/usr/share/netdata` for them if they're not in `/etc`.

**Comment by ktsaou** [comment]
`/usr/lib/netdata/conf.d` mimics systemd.

ok, univrersal solution for all config files, first in `/etc/netdata`, then in `/usr/lib/netdata/conf.d`.

**Comment by paulfantom** [comment]
Probably there will be a request to add an option to allow splitting config files and allow merging files from `/usr/lib/netdata/conf.d` with files from `/etc/netdata`. We can solve this also the same way systemd does it.
Example for config file `conf.d/apache.conf` (look closely to dirs):
1. Look if `/etc/netdata/python.d/apache.conf` exists, use it as a base if it exists
2. If not, use `/usr/lib/netdata/conf.d/python.d/apache.conf`
3. Merge config files from `/etc/netdata/python.d/apache.conf.d/*.conf` with config taken from previous points.

This way we can provide default config files, allow to completely replace them with custom ones and allow to change only parts of configs.

However this can be added later and probably should have another issue.

**Comment by ktsaou** [comment]
@paulfantom this is a nice idea we can apply on all configs.

**Comment by ktsaou** [comment]
merged it!

**Comment by sonicaj** [comment]
Hello @ktsaou. Please have a look at this - https://www.freebsd.org/cgi/man.cgi?query=hier&sektion=7&manpath=freebsd-release-ports. We can perhaps settle on having config files under /usr/local/lib making updates simpler but editing files there and reading from there wouldn't be ideal - I'm referencing stream.conf file. From my understanding of this issue, right now we have decided on doing this which seems very wrong. Please have a look and let me know if I missed something. Many thanks !
Plus maybe I don't think we make them readonly, the files under /usr/local/lib, should we perhaps consider that as well ? Because users would be too lazy to copy them and edit them under /etc ? I don't think we do this in freebsd port at least

**Comment by cakrit** [comment]
We will have an internal design discussion on #4731 next week, referencing that issue so we can take into consideration @sonicaj 's feedback as well.

**Comment by sykp241095** [comment]
Issue:
netdata FATAL : MAIN :Cannot cd to directory '/usr/lib64/netdata/conf.d' # : No such file or directory

Solution:
stock config directory = /etc/netdata/conf.d
