### ISSUE TITLE
[Request] Better update-function

### ISSUE THREAD

**Issue by Jonn3y** [netdata/netdata#419]
Heyho,

I like netdata, but not the way to update it. Would be better to click onto "update" and it makes everything automatically. 
The update-funtion from PlexPy is a good example for! https://github.com/drzoidberg33/plexpy

Best Wishes: Jonas

**Comment by ktsaou** [comment]
Hi Jonas, so you want netdata to self-update itself? i.e. to click update and have it download the latest version and re-install itself?

**Comment by Jonn3y** [comment]
Yes :) exactly

**Comment by Jonn3y** [comment]
How it looks like:
Update-Notification:
<img width="257" alt="bildschirmfoto 2016-05-21 um 11 01 57" src="https://cloud.githubusercontent.com/assets/11927089/15447467/932ebe12-1f43-11e6-8aba-32eeab5fc1c4.png">

Updateprocess (Onclick: Update):
<img width="603" alt="bildschirmfoto 2016-05-21 um 11 02 08" src="https://cloud.githubusercontent.com/assets/11927089/15447466/932e0b20-1f43-11e6-8851-14d4c9410596.png">

Verison-Comparing (Onclick: newer Version):
Link to github: Example: https://github.com/drzoidberg33/plexpy/compare/a726154b1d2231fdc59d2ffb2d567e2008e68348...c3378e165339a218bf98d0742d2ecfd0485a519a

**Comment by paulfantom** [comment]
@Jonn3y  Wow! Do I understand you clearly? You want to update software on your PC by clicking on `update` in a web browser? Correct me if I am wrong but I think that this can lead to a major security problem.

**Comment by Jonn3y** [comment]
Sure, why not. I don't know much about programming and security but I don't understand why it shouldn't be a major security problem. Tools like Plex, CMS and a lot of other programms have a feature like that.

?!

**Comment by ktsaou** [comment]
I have been trying to understand what monitoring companies do. I created free accounts to many of them. Most, require from you install an agent on your systems and then they are able to push changes to your systems via their central web site!

From a security standpoint this is even worst: their users have transferred to them the right to execute arbitrary commands as `root` on all systems monitored.

I have marked this as an enhancement because I think we can find a way to do this somewhat more safely:

1. command to update and all related functions will require authentication on the dashboard - and probably a configuration option to enable this capability for one or more authenticated users.

2. netdata runs as user netdata, so all updates will be done as this user. We will have an issue setting capabilities for `apps.plugin` though, since this requires running `setcap` as root.

3. we would need to have a web log of some kind so that the admin will be able to check for errors (i.e. plugins that are failing to collect values)

A binary release could be useful for this though, #87, #444, #439, etc.

This is not high on priorities though (check: #436 )

**Comment by paulfantom** [comment]
As of binary releases maybe we could use something like [Open Build Service](http://openbuildservice.org)? This way we could provide users a way to include our own repository for many different distros. Just like [ownCloud](https://download.owncloud.org/download/repositories/stable/owncloud/) does it.
@ktsaou what do you think about it?

**Comment by ktsaou** [comment]
I don't any experience with such a service. I welcome of course any work towards this.

**Comment by tx7** [comment]
Regarding security, I lock my netdata's site with a password, so nobody can enter without a password.

**Comment by paulfantom** [comment]
There is no plan on implementing updating netdata from netdata itself. This will be also in direct opposition to binary packaging.
