### ISSUE TITLE
[project management] Move wiki to `docs` repo

### ISSUE THREAD

**Issue by paulfantom** [netdata/netdata#4196]
Blocked by https://github.com/firehol/netdata/issues/4190

Since wiki is nothing else than a git repo (https://github.com/firehol/netdata.wiki.git), then I propose to treat it as such. Move it to separate repo like `docs` or `wiki`, enable pull requests, setup automatic synchronization (travis) and disable write access via web interface.

**Comment by ktsaou** [comment]
Like this one I guess: https://www.netlifycms.org/docs/add-to-your-site/

**Comment by ktsaou** [comment]
One of the key issues I have with github wiki, is that we can't embed live netdata charts on it!
It would be perfect to have live charts in documentation.

The funny thing, is that we could create page for (eg) "Monitoring MySQL", and in that page, we could add a drop down button with your servers (from the registry), to render in the page YOUR MYSQL SERVER !!!

**Comment by paulfantom** [comment]
No idea. Also why do we need CMS to edit some markdown files, is github UI editor not enough?

This PR is more about controlling and reviewing new additions to wiki than ease of use.

**Comment by ktsaou** [comment]
Check netlify. It does exactly that.

**Comment by paulfantom** [comment]
netlify is a site builder (I use it), do we need to build a site for docs?

**Comment by paulfantom** [comment]
I want to show markdown docs, not manage full site. It would be probably better to go with readthedocs.io.

**Comment by paulfantom** [comment]
> The funny thing, is that we could create page for (eg) "Monitoring MySQL", and in that page, we could add a drop down button with your servers (from the registry), to render in the page YOUR MYSQL SERVER !!!

That is mixing docs and marketing.

**Comment by ktsaou** [comment]
> That is mixing docs and marketing.

that is the idea, yes.

**Comment by ktsaou** [comment]
Documentation can be a tool. Not just docs.

**Comment by paulfantom** [comment]
> > That is mixing docs and marketing.
>
> that is the idea, yes.

Yeah, I don't like projects which does that. Especially when I need to find some info, but instead I spend time on going through all the marketing crap. I can understand landing page with marketing stuff, but not docs.

**Comment by paulfantom** [comment]
It is the same with CHANGELOGs, they are intended to quickly find what has changed not for marketing.

**Comment by Ferroin** [comment]
I would tend to agree with @paulfantom on this one.  That said, things aren't _too_ bad on the wiki beyond the main page right now.

**Comment by paulfantom** [comment]
> things aren't too bad on the wiki

They are not, but it is better to control what is going into official docs. That's why I didn't intend to change **how we present** wiki, only how we allow on changing it.

I can even create a [CI pipeline with grammar checks](https://pawel.krupa.net.pl/2018/07/automate-your-grammar-checks/) for this :stuck_out_tongue:

**Comment by ktsaou** [comment]
ok, let me explain:

When I say that documentation is a marketing tool, I mean that documentation gives value to a project. Its clarity, its ease of use, its unified language and concrete structure, its effectiveness in helping people go through the problem they have, etc.

We all know that marketing is extrapolating things a bit. Of course documentation should not do that.

But being able to adapt documentation to your use case (as I suggested above) is a great tool. People would use this as a learning tool and I find it magical.

At the same time, I strongly believe documentation should be minimal. People do not read. People search and expect to find answers in a bunch of lines. Or even better, the answer should be embedded in the place it is needed in the first place (like the config files, the alarm notifications, the dashboard), so that people will have the answer in front of them.

So, professional documentation is a unique marketing tool, to help the project grow.
Our documentation is not good at all. I have written much of it, but still I don't like it...

**Comment by ktsaou** [comment]
ok, I agree!

**Comment by elfgoh** [comment]
> At the same time, I strongly believe documentation should be minimal. People do not read. People search and expect to find answers in a bunch of lines. Or even better, the answer should be embedded in the place it is needed in the first place (like the config files, the alarm notifications, the dashboard), so that people will have the answer in front of them.

This is so true. Thanks for crystallising this thought for me @ktsaou! And one of the reasons I love netdata!

**Comment by cakrit** [comment]
Test documentation project is at https://github.com/cakrit/netdata-doc
It gets automatically published to https://cocky-fermi-65a7ac.netlify.com/
Source files are under sources/netdata.wiki (will rename) and structure in sources/toc
"make html" converts the markdown files to restructuredtext and runs Sphinx to generate the site

Please provide feedback here so we can move with the next steps.

**Comment by ktsaou** [comment]
@cakrit we need this structure:

- Welcome Guide
- Installation Guide
- Getting Started With Netdata
- Configuration Guide
- Tuning Guide
- Systems Monitoring Reference
- Applications Monitoring Reference (could be a automatically generated, interactive)
- APM (statsd)
- Metrics Streaming & Replication
- Metrics Archiving (backends)
- Health Monitoring & Notifications
- Alarms Reference (could be automatically generated, interactive)
- Netdata Registry
- APIs Reference (data collection, web API, etc)
- Custom Dashboards & Badges (including reference for each chart library we use)
- Development Guide (write plugins, protocols used, APIs, etc)

Then we need a set of "How Tos", like:

- Monitoring web servers
- Netdata with Prometheus
- Monitoring Ephemeral Nodes
- Monitoring Kubernetes
- Monitoring Containers and Virtual Machines
- Monitoring an IoT cloud
- Monitoring the process tree with netdata
- Visual Anomaly Detection with netdata

I think we should start section by section, reusing parts of the existing docs when possible.
But each section should be discussed a bit to understand what we need to do.

Can we start with "Installation Guide" ?
I understand it needs the following sections:

## Installation Guide

Owner: @paulfantom 

- **Binary packages per distribution**
  Use the native package manager of the system to install netdata
  Supported distributions: debian / ubuntu, red hat / fedora / centos, arch / manjaro, gentoo

- **Static packages**
  Install a statically built netdata package, on any `X86_64` Linux box, running kernel 2.4 or later

- **Install with docker**
  Install netdata with docker on `x86` 32 and 64bit, `armv7l`

- **Install with CI**
  Integrate netdata to your CI

    - Ansible
    - Puppet
    - Chef

- **Install from source**
  Install the latest unreleased version of netdata, directly from source

    - Linux
    - FreeBSD and pfsense
    - MacOS

- **Verify netdata installation**
  Checklist to verify netdata is installed properly, that has the right permissions to monitor everything, the required third party packages are installed, etc.

**Comment by paulfantom** [comment]
> Install with CI
> Integrate netdata to your CI

Not `CI`, those are `IaC` :smile:
CI == Continuous Integration
IaC == Infrastructure as Code

**Comment by cakrit** [comment]
Right now I can restructure, clean, de-duplicate, correct syntax/grammar errors etc. 
I can't add new content. I restructured the first two sections and removed duplicate info. Check it out and tell me if that's what you're looking for.

I need confirmation that you're ok with the netdata-doc project structure and build process, because we'll be wasting time if we are to change these later. Want me to document how it works first?

**Comment by paulfantom** [comment]
I want to know if that is the **look** we are aiming for? Will this theme be consistent with a future blog and current my-netdata site? Is it "theamable"? Or maybe we don't want that consistency?

**Comment by cakrit** [comment]
I have no views on the theme, we can change it any time. A list of available themes can be found at https://github.com/yoloseem/awesome-sphinxdoc

**Comment by cakrit** [comment]
This process with pandoc and sphinx has *serious* issues with links inside tables. Just look at the table at https://cocky-fermi-65a7ac.netlify.com/rst/add-more-charts-to-netdata?highlight=add%20more%20charts and you'll understand. The syntax is correct, but I guess the table completely messes up the sphinx parser. I will give up on sphinx, I'll find some other static site generator.

**Comment by cakrit** [comment]
1. Documentation generation with Sphinx

https://docs.readthedocs.io/en/latest/intro/getting-started-with-sphinx.html#

Option 1.1:
- Use pandocs to convert markdown to restructuredText and have sphinx read restructuredText to generate html

Cons:
- Links inside tables not processed properly
- Internal linking (from one doc to another) requires a lot of manual work, pandocs doesn't generate the required anchors
- Intermediate, generated restructuredText files are pretty much useless to us, as we'll only be working with markdown. 

Pros:
- Pandocs is much more mature and powerful than other converters 
- Sphinx is powerful and supports documentation versioning OOTB

Option 1.2:
- Have Sphinx use markdown documents directly, via the recommonmark addon

Cons:
- Hard, cryptic error while processing just the 5th mardkown file. No explanation of offending syntax. Luckily found an already open issue, explaining that links in bold are not supported.
- Tables not supported.  Tried suggestions from https://github.com/rtfd/recommonmark/issues/3, neither worked OOTB, gave up.
- Sphinx is powerful and supports documentation versioning OOTB

Pros:
- No intermediate restructuredText files

Option 2. MkDocs

Cons: 
- Doesn't natively support versioning : https://github.com/mkdocs/mkdocs/issues/193
- Less powerful than Sphinx, readthedocs suggests Sphinx. 

Pros:
- Simpler than using Sphinx.
- Seems to be more modern, better supported (haven't verified).

SUMMARY: 
- Current best option is 1.2, with the caveat that tables are not supported. (we need to put them in custom html pages or restructure them into lists).
- I will start working with MkDocs to see if option 2 is better, despite the customization needed for versioning.

**Comment by paulfantom** [comment]
"Con" from MkDocs is fulfilled with git, as we intend to use git for version control of docs repository.
And as far as I know Sphinx is really good for projects where documentation lives in docstrings in the code (not netdata). Mkdocs is easier to write from scratch, style, and deploy (exactly our case).

**Comment by cakrit** [comment]
The question is how easy it will be to have published versions of the documentation frozen and aligned with versions of netdata itself. Starting on it now, will let you know how it goes.

**Comment by cakrit** [comment]
I like mkdocs. It's MUCH simpler to use and I don't see any strange things happening this far. The bad thing is that I'm having to redo the TOC (nav) from scratch, but I should have that done tomorrow. The long structure Costas described doesn't work very well with the standard templates, but it's rather minor. It also looks like we could easily have a yml file for each "frozen version", sending the builds to different output directories (i.e. sub-sites). I don't see a reason to go back to Sphinx now.

**Comment by paulfantom** [comment]
@ktsaou Can we make this TOC structure more nested? I fear that with very flat structure we will end up with 100s of top level links.

**Comment by cakrit** [comment]
Check out a rough draft at https://netdata-doc.readthedocs.io/en/latest/
I will do some more restructuring and clean ups tomorrow and then work on a template README.md for plugins that will be parsed automatically. We had a long chat with Costa about how it should work, so that a big part of the docs can be generated from READMEs inside the netdata project itself.

**Comment by ktsaou** [comment]
> @ktsaou Can we make this TOC structure more nested? I fear that with very flat structure we will end up with 100s of top level links.

of course we can.

> Check out a rough draft at https://netdata-doc.readthedocs.io/en/latest/

This is a great progress. However we are still far from an acceptable result. @cakrit I don't know if restructuring the existing content will work. Probably we need more and somewhat different content...

I am also trying to find out how a lot of details can be documented in the repo. PR #4391 is such an attempt. For example, check how the [plugins](https://github.com/ktsaou/netdata/tree/plugins3/src/plugins) section and the [external plugins](https://github.com/ktsaou/netdata/tree/plugins3/src/plugins/plugins.d.plugin) section.

**Comment by ktsaou** [comment]
Join also the discussion at #4391 . @paulfantom is right that moving everything under `src/` will be wrong from a usability perspective. So, I think of removing `src/` completely. Let me know what you think,

**Comment by cakrit** [comment]
Taking from #4391:

> Almost no one reads READMEs which are far down in directory layout. This should be in documentation.

Documentation will collect individual READMEs automatically and organize them appropriately. 

> CONTRIBUTING.md should exist as one simple file as the intention of that file is to engage new contributors into taking action and contributing to project by following simple guidelines. This cannot be some distributed multi-page document.

I will try to make it a single document and see what we end up with. If it can remain simple, we will keep it as one. Do note that when I try to work on a specific item, I need the documentation for that specific item handy. 

These are the sources we have right now, which I will put together in one big CONTRIBUTORS.md:

https://netdata-doc.readthedocs.io/en/latest/Writing-Plugins/
https://netdata-doc.readthedocs.io/en/latest/New-Module-PR-Checklist/
https://netdata-doc.readthedocs.io/en/latest/How-to-write-new-module/
CONTRIBUTORS.md

**Comment by ktsaou** [comment]
> CONTRIBUTORS.md

This is the Contributors License Agreement

> CODE_OF_CONDUCT.md

This is how we behave and the behavior we accept. This should be a bit more broad (not only about contributors).

**Comment by paulfantom** [comment]
@cakrit Please either move this discussion to https://github.com/netdata/netdata/issues/4146#issuecomment-429643204, close one of those issues or respond accordingly. Same response in two issues are a bit confusing.

**Comment by cakrit** [comment]
Moved discussion on CONTRIBUTING to #4146

**Comment by cakrit** [comment]
Updated vision:
@ktsaou prefers most of the documentation to be inside the netdata project. It's the reason so many README files have already been added, many of them already taken directly from the wiki.

This means that the separate netdata-doc repository will be used only for the transition to the end state. The end state will be the following:
- The netdata project contains all source files, static content, doc configs and required scripts to build its static html documentation. 
 - Source files are markdown documents throughout the netdata directory structure
 - Static content is images, html fragments, javascripts etc. that reside in a separate directory structure under netdata (e.g. docs)
 - Doc configs are files like requirements.txt, mkdocs.yml and any mapping files that are needed to generate the static site
 - Required scripts are the code that will be used to validate the consistency of the documentation and to build the site. 
- Netlify is used to generate and publish the site. The main advantage of Netlify over mkdocs is that we are able to specify a custom build command, whereas mkdocs forces us to use either mkdocs or sphinx. We need the custom build command, as the generated files will not be tracked in git. 
- Every commit, regardless of whether it is related to code or documentation will trigger the documentation to be built before. We will have a way to see older versions of the documentation.  

High level list of things that need to happen:
1. Eliminate the wiki pages ASAP. We already have a problem with content duplicated between the wiki and the various README files.
 1.1 Remove wiki pages that have already been moved under netdata. In the wiki sidebar, reference their github location. 
 1.2 Move remaining wiki pages to netdata/docs and update the wiki sidebar.

This action alone will be sufficient to close this issue, as every change to the markdown files will require a PR in netdata. Any new wiki entries will be vetted, added to the netdata project and the sidebar will be updated to point to the committed netdata markdown file.

2. Incrementally prepare the static site builder, in netdata-doc. As mentioned before, this project is temporary. When the generated site is good enough to go public, we will add all required artifacts to netdata itself. From that point onwards, the entire wiki will be replaced with a single link to the published html documentation.

There are a lot of steps to this and I will go into them into much greater detail in a different issue (epic). 
Indicatively:
- Diff migration of wiki updates to new documentation #4320. This one will be modified now that our source is netdata instead of netdata-doc.
- Create new site build script, that takes all markdown files from netdata
- Documentation links sanity checker #4416
- Generate Collectors.md #4415 
 - Requires move all plugin/module README files to the templates in #4394  
- Finalize structure.
- Create new content to match the new structure.

We need to arrange an all-hands call to align on this direction, so that we don't have any more changes to the vision.

**Comment by ktsaou** [comment]
> 1. Eliminate the wiki pages ASAP. We already have a problem with content duplicated between the wiki and the various README files.

done, although I believe a may have missed a couple.

> 1. 1.1 Remove wiki pages that have already been moved under netdata. In the wiki sidebar, reference their github location.

done, but not "removed". They are now say "Moved to URL".
We should not remove them. Google search will break.

The inforgraphic is still pending. I'll fix it.

> 1. 1.2 Move remaining wiki pages to netdata/docs and update the wiki sidebar.

I will do another pass and move as many as I can inside the repo.
The ones I will leave behind will not "fit" into the current repo structure. We will need a new structure for them.

I need 1-2 days to complete this task (it was tremendous already).

**Comment by ktsaou** [comment]
I have a question:

In a few cases, a single `README.md` will not suffice. What should be done in these cases? Add another `TITLE.md` to the repo at the path it should be?

Example is `streaming/`. Most probably I'll need:

1. `README.md` to describe how it works
2. `EPHEMERAL.md` to describe how to setup ephemeral nodes monitoring
3. `PROXIES.md` to describe how to setup the various kinds of netdata proxies

Another example is `health/`:

1. `README.md` to describe how it works
2. `REFERENCE.md` to document every single option available
3. `EXAMPLES.md` to give a few configuration examples

I also think we need `health/notificiations/` to describe `alarm-notify.sh` and a plugin directory for each notification method supported.

So the question is:

Is non `README.md` files accepted? Currently everything is in `README.md`. Should I added docs in other files?

**Comment by cakrit** [comment]
It's impossible to have just a single readme everywhere. Additional .mds are certainly needed. Anything that doesn't fit the directory structure can be added to /doc/md

**Comment by cakrit** [comment]
By the way, you don't need to do everything yourself! I was looking for acknowledgement/alignment :)

**Comment by ktsaou** [comment]
Finished in PR #4428.
I have the wiki ready to be pushed, but I need to first merge #4428 so that I'll also make a search for broken links.

**Comment by ktsaou** [comment]
Done. All the wiki pages that belong to the repo have been moved.
I have not deleted files from the wiki. Instead all pages now point to their location.

I also walked through the entire thing (well most of it), and updated the documentation to be current.
