### ISSUE TITLE
Request: Use the /config folder in docker

### ISSUE THREAD

**Issue by mattgphoto** [netdata/netdata#4219]
Hello all, I had a request as I'm using netdata in docker, and I can make config changes to say, do notifications to webhooks, but if the container restarts or upgrades, then the config is wiped and I have to re-do the config. After creating a /config directory, it appears that the /config directory doesn't have any files in it. Is there a way to make the config permanent in docker? This is also mentioned in this discussion: https://github.com/firehol/netdata/issues/4125#issuecomment-422157585

**Comment by paulfantom** [comment]
We are already having a directory for configuration files, it is called `/etc/netdata`. There is no need for another dir. All files in container should be ephemeral and if you want them to last longer, then attach a volume.

**Comment by mattgphoto** [comment]
So then if I want to keep configurations permanent, do I put/copy a health_alarm_notify.conf file into a /config folder that's mounted? Because the health_alarm_notify.conf file is what needs to be edited...

**Comment by paulfantom** [comment]
Yes, you put a file in a volume with all config files, so you can edit them later. After that you run netdata container with this config.

Please read those for more information how to manage persistent data in docker:
- https://docs.docker.com/storage/volumes/
- https://docs.docker.com/storage/

**Comment by nemchik** [comment]
I think the concern with the blank volume when mounting `/etc/netdata` is that the netdata image populates this folder with `.conf` files if there is no volume and those files might be nice to have automatically created at the location of the volume if they are not present.

**Comment by paulfantom** [comment]
I disagree. Configuration files shouldn't be touched by application they are configuring and recreation is exactly that. Apart from that, when using docker you should almost always mount configuration as read-only.

What is a proper solution is to have either:
- default values embedded in application and be able to read partial config (current netdata way)
- have config files in `/lib` and allow app to overwrite those files when file with same name is detected in `/etc` (planned netdata way)

**Comment by paulfantom** [comment]
I still don't understand what is the problem here. Netdata can run without anything in `/etc/netdata` (@ktsaou correct me if I am wrong) so you can mount empty volume and create your own files there.

**Comment by paulfantom** [comment]
And if you want to have **all** config files, why not run:
```
mkdir config
docker run -d --name netdata_tmp firehol/netdata
docker cp netdata_tmp:/etc/netdata config/
docker rm -f netdata
docker run -v $(pwd)/config:/etc/netdata:ro <other_options> firehol/netdata
```
?

**Comment by nemchik** [comment]
Sorry, I'm not trying to be difficult or anything. Many other docker containers I use will have their config files stored in a volume, but if those files don't exist then they are created when the container runs. Also many of the apps will make changes to the config files based on elements in the UI such as a Settings menu. A very good example of this is Plex, or a torrent client. The config should be persistent, but may be editable from within the web interface of the app itself.

In this case, with netdata, i think the only reason having a blank volume is a negative is that the files that would normally be found at `/etc/netdata` could be used as examples or to just easily edit what's already there rather than having to look up the file names and create a blank file containing the config desired, or potentially only part of the config (which you mention netdata is fine with).

**Comment by paulfantom** [comment]
And that's part of why we are going to ship config in `/lib` and not in `/etc`. But we are not going to create special dir just for docker.

Also I am not sure, but from what I remember netdata doesn't allow to change settings from UI.

**Comment by nemchik** [comment]
No it doesn't seem like settings are saved to the config when changed in the web. 

I don't think a separate location for docker is needed. If configs are shipped in `/lib` and copied to `/etc` if missing when netdata is run then having `/etc/netfata` as a volume would result in the folder being populated with conf files when the container runs.

**Comment by nemchik** [comment]
So when that happens if there are config files in `/etc/netdata` they will just override the default values, but are not required to run netdata? (Just making sure)

Would it be possible for the `dockerfile` to make that copy happen? This way it only happens for docker users, and that folder can be made a volume so that those files are easily editable and the users don't have to create them all manually.

**Comment by paulfantom** [comment]
> So when that happens if there are config files in /etc/netdata they will just override the default values, but are not required to run netdata? (Just making sure)

Exactly that.

> Would it be possible for the dockerfile to make that copy happen?

It would be possible, but we won't do this for couple of reasons:
- it creates unnecessary files and by extension it is not following KISS principles
- it will give different user experience between containerized and non-containerized netdata
- there will be problems with config consistency and we will need to implement upgrade mechanism which would check if file needs to be copied or it was modified by user (and for exactly this reason we want **users** to create those files, read more in #4182)
- it will create file permission problems and an influx of issues regarding that.

**Comment by nemchik** [comment]
All fair points. So the way things are right now, setting `/etc/netdata` as a volume results in a blank folder, and after the changes you've mentioned regarding `/lib` there won't be a noticeable difference for docker users.

**Comment by paulfantom** [comment]
Exactly.

**Comment by MrCaringi** [comment]
> 
> 
> And if you want to have **all** config files, why not run:
> 
> ```
> mkdir config
> docker run -d --name netdata_tmp firehol/netdata
> docker cp netdata_tmp:/etc/netdata config/
> docker rm -f netdata_tmp
> docker run -v $(pwd)/config:/etc/netdata:ro <other_options> firehol/netdata
> ```
> 
> ?

gracias!
you made my day!
