### ISSUE TITLE
net outbound too high - tracks inbound

### ISSUE THREAD

**Issue by dkebler** [netdata/netdata#4306]
I have netdata running on my gateway router (espressobin)

While queuing up some videos on my LAN device I expect to see significant net inbound but very little net outbound.  Instead they just track each other within a tenth of a mbit or so.   What interface(s) does netdata watch for this data?   I would assume the wan interface only.  Why is this not behaving as expected.  Doesn't look I can tell netdata which interface to use for net inbound/outbound.

I am running latest version of netdata, on ubuntu 18.04, using systemd-networkd set with one wan interface and two bridged lan interfaces and dnsmasq.  I have a very basic firehol conf running for a gateway router

**Comment by Ferroin** [comment]
Barring containers, cgroups, and VM's, Netdata displays networking information in three places:

* In the 'System' section of the dashboard, both in the gauges at the top and in the charts in the 'networking' sub-section.  This information is aggregate data over all interfaces that Netdata is monitoring, so what you're observing is correct behavior for traffic that's being routed through the system.  The reasoning here is pretty simple, Netdata can't tell for certain if the system is a router or not, so it just displays things the same way here regardless.
* In the 'IPv4 Networking' and 'IPv6 Networking' sections of the dashboard.  This is also aggregate data over all interfaces, and thus the traffic graphs here should be displaying the same behavior as the ones in the 'System' section for routed traffic.
* In the 'Network Interfaces' section of the dashboard.  This is where the data you appear to be looking for is located, it includes per-interface traffic graphs.

By default, Netdata collects data From almost all interfaces except the loopback interface.  You can disable data collection for certain interfaces by adding lines like the  following to `/etc/netdata/netdata.conf`:

    [plugin:proc:/proc/net/dev:eth0]
	enabled = no

Replace `eth0` in the above lines with the name of the interface you want to ignore.  However, this approach is not recommended,a s the data Netdata reports will not give you a complete representation of what your system is doing.

Alternatively, if you just care about the gauge at the top of the dashboard displaying info only from the WAN interface, you could just create a custom dashboard that's minimally modified from the regular one.  @ktsaou is probably a better person to explain how to do this than I am though.

**Comment by ktsaou** [comment]
@dkebler this is easy to check.

Start a data transfer. While it is transferring do this on a console:

```
x=5; while [ $x -ge 0 ]; do x=$((x - 1)); date; cat /proc/net/dev; sleep 1; done
```

Post the output here.

When the transfer finishes, press this button on the dashboard:
![image](https://user-images.githubusercontent.com/2662304/46232347-9bf74c00-c377-11e8-847e-269cee836a02.png)

It will save a file. Put it in a zip and drag-and-drop it to your post, here in github.

**Comment by dkebler** [comment]
Below is dev output.    Note the wan port data and you'll see the large receive vs much smaller transmit.

FYI  lo and br0 are the virtual devices.  This board has a topaz network chip so wan is derived from eth0 (basically eth0 can be ignorned) 

According to the summary page
```
network
Total bandwidth of all physical network interfaces. This does not include lo, VPNs, network bridges, IFB devices, bond interfaces, etc. Only the bandwidth of physical network interfaces is aggregated. Physical are all the network interfaces that are listed in /proc/net/dev, but do not exist in /sys/devices/virtual/net.
```
so netdata is just adding them all up and thus surprise they are the same which IMHO isn't very useful data.    I would suggest that netadata have a config parameter which would be the name the interface you want to track in/out.   It could by default look for `wan`.  To aggregate interfaces at least in a gateway router doesn't lead to any useful data.  In a typical server with a single Ethernet interface this would be fine.

```
Thu Oct 11 15:32:55 UTC 2018
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
  lan0: 26341666  396854    0    0    0     0          0         0 914680578  676012    0    0    0     0       0          0
  eth0: 1307395509 1541586    0    0    0     0          0         0 1326900130 1537730    0    0    0     0       0          0
  lan1: 40254939  139083    0    0    0     0          0         0 300459737  253341    0    0    0     0       0          0
   br0: 66596385  535935    0   10    0     0          0         0 1208823538  919985    0    0    0     0       0          0
   wan: 1206884012 1005649    0    0    0     0          0         0 99456391  608353    0    0    0     0       0          0
    lo: 37987394  160301    0    0    0     0          0         0 37987394  160301    0    0    0     0       0          0
Thu Oct 11 15:32:56 UTC 2018
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
  lan0: 26344048  396896    0    0    0     0          0         0 914777357  676088    0    0    0     0       0          0
  eth0: 1307498094 1541722    0    0    0     0          0         0 1327015020 1537866    0    0    0     0       0          0
  lan1: 40254939  139083    0    0    0     0          0         0 300459737  253341    0    0    0     0       0          0
   br0: 66598767  535977    0   10    0     0          0         0 1208920317  920061    0    0    0     0       0          0
   wan: 1206981223 1005743    0    0    0     0          0         0 99473414  608413    0    0    0     0       0          0
    lo: 38004473  160349    0    0    0     0          0         0 38004473  160349    0    0    0     0       0          0
Thu Oct 11 15:32:57 UTC 2018
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
  lan0: 26345532  396921    0    0    0     0          0         0 914829898  676132    0    0    0     0       0          0
  eth0: 1307556562 1541816    0    0    0     0          0         0 1327085699 1537959    0    0    0     0       0          0
  lan1: 40256320  139087    0    0    0     0          0         0 300459953  253344    0    0    0     0       0          0
   br0: 66601632  536006    0   10    0     0          0         0 1208973074  920108    0    0    0     0       0          0
   wan: 1207034758 1005808    0    0    0     0          0         0 99490592  608459    0    0    0     0       0          0
    lo: 38021545  160397    0    0    0     0          0         0 38021545  160397    0    0    0     0       0          0
Thu Oct 11 15:32:58 UTC 2018
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
  lan0: 26347284  396951    0    0    0     0          0         0 914898969  676186    0    0    0     0       0          0
  eth0: 1307632746 1541926    0    0    0     0          0         0 1327174164 1538069    0    0    0     0       0          0
  lan1: 40258388  139091    0    0    0     0          0         0 300460880  253348    0    0    0     0       0          0
   br0: 66605452  536040    0   10    0     0          0         0 1209042262  920165    0    0    0     0       0          0
   wan: 1207104702 1005884    0    0    0     0          0         0 99508179  608511    0    0    0     0       0          0
    lo: 38038606  160445    0    0    0     0          0         0 38038606  160445    0    0    0     0       0          0
Thu Oct 11 15:32:59 UTC 2018
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
  lan0: 26363848  397224    0    0    0     0          0         0 915659622  676713    0    0    0     0       0          0
  eth0: 1308563264 1542899    0    0    0     0          0         0 1328116436 1539040    0    0    0     0       0          0
  lan1: 40264860  139130    0    0    0     0          0         0 300593662  253466    0    0    0     0       0          0
   br0: 66628488  536352    0   10    0     0          0         0 1209935697  920810    0    0    0     0       0          0
   wan: 1207990778 1006545    0    0    0     0          0         0 99549248  608837    0    0    0     0       0          0
    lo: 38056451  160501    0    0    0     0          0         0 38056451  160501    0    0    0     0       0          0
Thu Oct 11 15:33:00 UTC 2018
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
  lan0: 26366004  397263    0    0    0     0          0         0 915710495  676772    0    0    0     0       0          0
  eth0: 1308727009 1543157    0    0    0     0          0         0 1328293945 1539296    0    0    0     0       0          0
  lan1: 40298024  139177    0    0    0     0          0         0 300664665  253546    0    0    0     0       0          0
   br0: 66663808  536438    0   10    0     0          0         0 1210057573  920949    0    0    0     0       0          0
   wan: 1208113527 1006717    0    0    0     0          0         0 99602833  608954    0    0    0     0       0          0
    lo: 38075974  160565    0    0    0     0          0         0 38075974  160565    0    0    0     0       0          0
```

**Comment by ktsaou** [comment]
So, you are saying in your setup, the network driver reports 2 network interfaces (`wan` and `eth0`), for one physical connection. Right?

ok, we could add an option to filter which interfaces should participate in the `system.net` chart.

**Comment by ktsaou** [comment]
I see in the code netdata already provides plenty of controls for this:

To disable a network interface, uncomment the following option and append the network interface you want to disable (in `netdata.conf`):

```
[plugin:proc:/proc/net/dev]
	# disable by default interfaces matching = lo fireqos* *-ifb
```

The above provides the default value for `enabled = yes/no` for each interface.

You have the following section for each of your interfaces. You can set `enabled = no` here, but also you can set `virtual = yes`, to keep the interface collected and visualized but mark it as virtual.

```
[plugin:proc:/proc/net/dev:eth0]
	# enabled = yes
	# virtual = no
	# bandwidth = auto
	# packets = auto
	# errors = auto
	# drops = auto
	# fifo = auto
	# compressed = auto
	# events = auto
```

Remember to uncomment options you change.

You can find the right version of `netdata.conf` by fetching `http://your.netdata.ip:19999/netdata.conf`.

**Comment by chuwza** [comment]
> I see in the code netdata already provides plenty of controls for this:
> 
> To disable a network interface, uncomment the following option and append the network interface you want to disable (in `netdata.conf`):
> 
> ```
> [plugin:proc:/proc/net/dev]
> 	# disable by default interfaces matching = lo fireqos* *-ifb
> ```
> 
> The above provides the default value for `enabled = yes/no` for each interface.
> 
> You have the following section for each of your interfaces. You can set `enabled = no` here, but also you can set `virtual = yes`, to keep the interface collected and visualized but mark it as virtual.
> 
> ```
> [plugin:proc:/proc/net/dev:eth0]
> 	# enabled = yes
> 	# virtual = no
> 	# bandwidth = auto
> 	# packets = auto
> 	# errors = auto
> 	# drops = auto
> 	# fifo = auto
> 	# compressed = auto
> 	# events = auto
> ```
> 
> Remember to uncomment options you change.
> 
> You can find the right version of `netdata.conf` by fetching `http://your.netdata.ip:19999/netdata.conf`.

Hi, I use OpenWrt 21.02, and I have the same need as dkebler, but after I use such netdata.conf, the system overview still shows the sum of all the network ports, and at the same time the network interface is only pppoe-wan, which is the opposite of my need, is it because of my wrong setting somewhere? Could you please help me?

this is my file before modified configuration
`Sun Aug 20 11:13:19 CST 2023
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
  eth0: 2433217532 3757285    0    0    0     0          0    126207 12319322599 10997994    0    0    0     0       0          0
br-lan: 8468351633 19063599    0 112764    0     0          0    660260 42250652048 39229486    0    0    0     0       0          0
pppoe-wan: 41405624819 35402379    0    0    0     0          0         0 4219086152 18681561    0    0    0     0       0          0
    lo: 91837199  879515    0    0    0     0          0         0 91837199  879515    0    0    0     0       0          0
  eth2: 42189075583 35421011    0 14935    0     0          0         0 4630191357 18685255    0    0    0     0       0          0
WireGuard:  584424    2065    0    0    0     0          0         0  3003180   15221 1648 15435    0     0       0          0
  eth1: 14105591004 22709784    0    0  471     0          0    534078 38013232033 36554122    0    0    0     0       0          0
  utun: 15930836072 17476100    0    0    0     0          0         0 13897957490 16112857    0  581    0     0       0          0
Sun Aug 20 11:13:20 CST 2023
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
  eth0: 2433217945 3757289    0    0    0     0          0    126208 12319330195 10998023    0    0    0     0       0          0
br-lan: 8468497815 19063895    0 112765    0     0          0    660278 42250934282 39229896    0    0    0     0       0          0
pppoe-wan: 41405896903 35402724    0    0    0     0          0         0 4219147275 18681762    0    0    0     0       0          0
    lo: 91837791  879523    0    0    0     0          0         0 91837791  879523    0    0    0     0       0          0
  eth2: 42189355317 35421356    0 14935    0     0          0         0 4630256902 18685456    0    0    0     0       0          0
WireGuard:  584424    2065    0    0    0     0          0         0  3003328   15222 1648 15436    0     0       0          0
  eth1: 14105741517 22710085    0    0  471     0          0    534095 38013514170 36554527    0    0    0     0       0          0
  utun: 15931109732 17476480    0    0    0     0          0         0 13898020889 16113108    0  581    0     0       0          0
Sun Aug 20 11:13:21 CST 2023
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
  eth0: 2433218671 3757296    0    0    0     0          0    126210 12319338357 10998052    0    0    0     0       0          0
br-lan: 8468728387 19064193    0 112766    0     0          0    660296 42251151874 39230243    0    0    0     0       0          0
pppoe-wan: 41406102100 35402948    0    0    0     0          0         0 4219162734 18681898    0    0    0     0       0          0
    lo: 91837791  879523    0    0    0     0          0         0 91837791  879523    0    0    0     0       0          0
  eth2: 42189565537 35421581    0 14936    0     0          0         0 4630275353 18685592    0    0    0     0       0          0
WireGuard:  584424    2065    0    0    0     0          0         0  3003328   15222 1648 15436    0     0       0          0
  eth1: 14105977404 22710394    0    0  471     0          0    534111 38013732110 36554874    0    0    0     0       0          0
  utun: 15931318860 17476727    0    0    0     0          0         0 13898043036 16113275    0  581    0     0       0          0
Sun Aug 20 11:13:22 CST 2023
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
  eth0: 2433223131 3757310    0    0    0     0          0    126212 12319349116 10998084    0    0    0     0       0          0
br-lan: 8468812612 19064422    0 112768    0     0          0    660318 42251419750 39230615    0    0    0     0       0          0
pppoe-wan: 41406342324 35403206    0    0    0     0          0         0 4219177362 18682027    0    0    0     0       0          0
    lo: 91838699  879535    0    0    0     0          0         0 91838699  879535    0    0    0     0       0          0
  eth2: 42189811455 35421839    0 14936    0     0          0         0 4630292819 18685721    0    0    0     0       0          0
WireGuard:  584424    2065    0    0    0     0          0         0  3003328   15222 1648 15437    0     0       0          0
  eth1: 14106064431 22710620    0    0  471     0          0    534131 38014003990 36555252    0    0    0     0       0          0
  utun: 15931561628 17477030    0    0    0     0          0         0 13898059183 16113448    0  581    0     0       0          0
Sun Aug 20 11:13:23 CST 2023
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
  eth0: 2433224386 3757321    0    0    0     0          0    126214 12319356923 10998113    0    0    0     0       0          0
br-lan: 8468896873 19064737    0 112770    0     0          0    660335 42251759553 39231052    0    0    0     0       0          0
pppoe-wan: 41406671321 35403572    0    0    0     0          0         0 4219197737 18682249    0    0    0     0       0          0
    lo: 91839291  879543    0    0    0     0          0         0 91839291  879543    0    0    0     0       0          0
  eth2: 42190148552 35422205    0 14936    0     0          0         0 4630318078 18685943    0    0    0     0       0          0
WireGuard:  584424    2065    0    0    0     0          0         0  3003328   15222 1648 15437    0     0       0          0
  eth1: 14106152267 22710930    0    0  471     0          0    534146 38014343626 36555685    0    0    0     0       0          0
  utun: 15931893039 17477438    0    0    0     0          0         0 13898082382 16113731    0  581    0     0       0          0
Sun Aug 20 11:13:24 CST 2023
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
  eth0: 2433225234 3757331    0    0    0     0          0    126215 12319364483 10998143    0    0    0     0       0          0
br-lan: 8469153341 19065209    0 112772    0     0          0    660351 42252042636 39231520    0    0    0     0       0          0
pppoe-wan: 41406940855 35403951    0    0    0     0          0         0 4219389338 18682617    0    0    0     0       0          0
    lo: 91839291  879543    0    0    0     0          0         0 91839291  879543    0    0    0     0       0          0
  eth2: 42190426424 35422584    0 14936    0     0          0         0 4630517775 18686311    0    0    0     0       0          0
WireGuard:  584424    2065    0    0    0     0          0         0  3003328   15222 1648 15437    0     0       0          0
  eth1: 14106414885 22711398    0    0  471     0          0    534161 38014626273 36556144    0    0    0     0       0          0
  utun: 15932176321 17477922    0    0    0     0          0         0 13898304834 16114233    0  581    0     0       0          0`

and this my netdata.conf after modified configuration
`[global]
	update every = 1
	memory deduplication (ksm) = no
	debug log = syslog
	error log = syslog
	access log = none
	run as user = root

[web]
	allow connections from = localhost 10.* 192.168.* 172.16.* 172.17.* 172.18.* 172.19.* 172.20.* 172.21.* 172.22.* 172.23.* 172.24.* 172.25.* 172.26.* 172.27.* 172.28.* 172.29.* 172.30.* 172.31.*
	allow dashboard from = localhost 10.* 192.168.* 172.16.* 172.17.* 172.18.* 172.19.* 172.20.* 172.21.* 172.22.* 172.23.* 172.24.* 172.25.* 172.26.* 172.27.* 172.28.* 172.29.* 172.30.* 172.31.*

[plugins]
	cgroups = no
	apps = no
	charts.d = no
	fping = no
	node.d = no
	python.d = no

[health]
	enabled = no

[plugin:proc:ipc]
	shared memory totals = no

[plugin:proc:/proc/net/dev:br-lan]
	enabled = no
	virtual = yes

[plugin:proc:/proc/net/dev:eth0]
	enabled = no
	virtual = yes
	
[plugin:proc:/proc/net/dev:eth1]
	enabled = no
	virtual = yes
	
[plugin:proc:/proc/net/dev:eth2]
	enabled = no
	virtual = yes
	
[plugin:proc:/proc/net/dev:utun]
	enabled = no
	virtual = yes
	
[plugin:proc:/proc/net/dev:WireGuard]
	enabled = no
	virtual = yes`
