### ISSUE TITLE
[SPIKE] Investigate switch to CMake and use CPack

### ISSUE THREAD

**Issue by paulfantom** [netdata/netdata#4310]
Our current autotools setup solves only problems generated by a core part of netdata and creates unnecessary problems in other parts (like plugins, CI system or packaging). Additionally we are already shipping with CMakeLists.txt file which isn't used in build system. Maybe it would be better to switch to CMake at some time in the future?

Also, it turns out that cmake is by default shipping with cpack which could provide us a generic way to provide binary packages for various distros (more in https://cmake.org/cmake/help/v2.8.12/cpack.html). So it seems that we can kill two birds with one stone.

**Comment by Ferroin** [comment]
Also, if done right, using CMake would make us a bit more agnostic of the exact underlying build system that gets used (`make` versus whatever else), and potentially give us really nice output from the build process itself.

**Comment by paulfantom** [comment]
There is also one more benefit: we could ditch those `.in` file extensions and use proper ones.

**Comment by paulfantom** [comment]
Related issue #4610

**Comment by cakrit** [comment]
Also related to #5159

**Comment by amoss** [comment]
I've started to look into this. Rough plan for doing this is:
1. Investigate if CMake can replace autotools - can we generate the build system from CMake that replicates what autotools currently does.
2. Look at the integration between the installer and the CMake build generation.
3. Look at how the build system generation can be cleaned up / simplified (#5159).

Initial results are that the current CMake configuration has some differences to the autotools configuration that are causing issues:
1. Tries to find dependencies in the package db instead of locating the libraries and checking that symbols are present.
2. The conditional logic for which libraries should be pulled in is different.
3. The command-line flags for enabling / disabling features are not present.

I will update this as I work through the first stage of getting CMake to parity with autotools.

**Comment by Ferroin** [comment]
> The command-line flags for enabling / disabling features are not present.

The typical approach with CMake to doing stuff like this is to use variables in the CMakefile to control whether the feature gets built or not and define them in such a way that users can override the default values from the command-line using the `-D` option.  It's not quite as convenient for features with a binary state as autoconf-style `--enable-foo` flags, but still usable.

**Comment by amoss** [comment]
I'm experimenting with using cache variables in CMake and the `-D` command-line option. I think that we can replicate the behaviour of the `--enable-foo` style flags although the syntax will be slightly different: `cmake .. -DENABLE_FOO=ON`.

**Comment by amoss** [comment]
Some initial results of the investigation so far (thanks to @vlvkobal for the help).

The current CMake configuration initially looks as if it works as a build environment on all systems, as the following sequence will rebuild netdata:

`git clean -dxf; autoreconf -ivf; ./configure --enable-maintainer-mode; mkdir build-cmake; cd build-cmake; cmake --build ..`

However, this simply uses the existing makefiles and chains gmake so it does not actually use the CMake definition. Replacing the final step with `cmake ..` to regenerate the makefiles currently works on some system configurations and not on others. Tested on:

1. Debian 9 (CMake 3.7.2) - package failures, syntax errors, missing CMake features.
2. FreeBSD 12 box-1 (CMake 3.14) - package failures, build errors
3. FreeBSD 12 box-2 (CMake 3.14) - working build
4. Arch (CMake 3.15.4-1) - working build

## Path differences on FreeBSD

Standard paths on not passed onto CMake, fixed with:

```
IF(FREEBSD)
       set(CMAKE_REQUIRED_FLAGS ${CMAKE_REQUIRED_FLAGS} "-I/usr/local/include")
       set(CMAKE_REQUIRED_LINK_OPTIONS ${CMAKE_REQUIRED_LINK_OPTIONS} "-L/usr/local/lib")
       include_directories(/usr/local/include)
       link_directories(/usr/local/lib)
ENDIF(FREEBSD)
```

Both changes are necessary to update the build environment for test programs within CMake, and to propagate the config changes to the generated Makefiles respectively.

## "Missing" openssl on FreeBSD

The openssl package in FreeBSD is integrated into the base-system and there is no pkg-config `.pc` to describe it. This causes the `pkg_check_modules` to fail. There are two ways around this, one is to assume the configuration of the base-system:

```
IF(NOT FREEBSD)
       pkg_check_modules(OPENSSL REQUIRED openssl)
       set(NETDATA_COMMON_CFLAGS ${NETDATA_COMMON_CFLAGS} ${OPENSSL_CFLAGS_OTHER})
       set(NETDATA_COMMON_LIBRARIES ${NETDATA_COMMON_LIBRARIES} ${OPENSSL_LIBRARIES})
       set(NETDATA_COMMON_INCLUDE_DIRS ${NETDATA_COMMON_INCLUDE_DIRS} ${OPENSSL_INCLUDE_DIRS})
ELSE()
       set(NETDATA_COMMON_CFLAGS ${NETDATA_COMMON_CFLAGS} "-I/usr/local/include")
       set(NETDATA_COMMON_LIBRARIES ${NETDATA_COMMON_LIBRARIES} crypto ssl)
       set(NETDATA_COMMON_INCLUDE_DIRS ${NETDATA_COMMON_INCLUDE_DIRS} "/usr/local/include")
ENDIF()
```

The other approach is to search standard paths for the library directly:

```
find_library(LIB_CRYPTO crypto)
check_library_exists(${LIB_CRYPTO} SHA256_Init "" HAVE_CRYPTO)
message(STATUS "Crypto lib ${CRYPTO} ${HAVE_CRYPTO}")
```

This relates to a more general issue about having `pkg-config` as a hard dependency that I will discuss more below.

There is an alternative work-around to this issue, which is to install the openssl package explicitly, but this places two separate openssl runtimes on the machine (which could be different versions).

## Problem with the Judy library

Something that looks out of place (but does not seem to cause problems in the working system configurations) is the following:

```
-set(CMAKE_REQUIRED_LIBRARIES "Judy")
+set(CMAKE_REQUIRED_LIBRARIES ${CMAKE_REQUIRED_LIBRARIES} "Judy")
```

This affects each test program that CMake uses (so it breaks when Judy is not available) and it wipes out any previous state (which happens to be empty).

## Hard dependency on `pkg-config`

The current use of `pkg_check_modules()` creates a hard dependency on `pkg-config`, but also on the `-dev` versions of each library that we are dependent upon (as they contain the extra `.pc` files). This causes different behaviour to the current installer. The installer will work successfully if the run-time version of some dependencies is installed, but the CMake configuration will not. 

We can avoid this by using soft checks for `pkg_check_modules` so that the `.pc` configuration is picked up if it is installed, but then fall back to `find_library` when it does not work and check if the dependency is installed in the standard paths. This would be more robust and match the current installer behaviour more closely.

## Problems specific to the CMake version in Debian

There are similar path / packaging problems in Debian that can be fixed as above, but there are two other problems that are unique to the older version of CMake.

```
cmake_policy(SET CMP0069 "NEW")
```

This policy is only introduced in CMake 3.9, so we need to wrap this in some version conditions. It is used to force-enable LTO where available (although the docs suggest this only applies to the intel compiler and we are using gcc/clang ?).

The other problem is that CMake 3.7 does not like `libnetdata` being targeted as an OBJECT rather than a packaged library and throws an error. This may be a CMake forward compatability issue and I am looking at if we can fix it by changing the properties of the target.

## Next steps

We've used the differences between the systems to work out how to get CMake working on a FreeBSD system, and the next step is replicating the working Arch configuration and then looking for differences against Debian.

The patch for FreeBSD is small and can be put into a PR at the end of the spike. After replicating the working linux configurations the main focus is on checking if we can regenerate the `config.h` directly in CMake and drop the autotools dependency completely.

**Comment by amoss** [comment]
Looking into the packaging/library detection code is complete. The behaviour in the installer can be replicated in CMake - it requires a base version of 3.1, but this is the current minimum version already. The basic outline is:

* Avoid inconsistencies between the `ldconfig` cache, standard paths and the `cc` configuration by reading the current search paths from `cc`. 
* Use `pkg-config` first -> retrieve the flags / library names if possible.
* Use `find_library()` if pkg_config fails, but using the correct search paths.
* If the `find_library()` fails then check if it is a soft-dependency and continue if it is (e.g. the `json-c` case).

Next step is checking that we can implement / replicate the config.h generation.

**Comment by amoss** [comment]
What we need to replicate the current configuration logic in CMake:

- [ ] Check each of the defines generated and substitute CMake variables.
- [ ] Check that we have a way to generate each feature/check in CMake.
- [ ] Feed the config.in through `configure_file()`.
- [ ] Check the include paths from each package.
- [ ] Testing that the build completes.
- [ ] Move files, we need `config.in` as an input for CMake instead of the result of autotools.

With a working CMake build-system we need to look at the integration with the installer. There are two possibilities here to investigate:
- [ ] Replacing the use of `build.sh` with CMake.
- [ ] Using an install target in the CMakeLists.txt to replicate what the installer is doing.

**Comment by amoss** [comment]
Documenting the config cases [here](https://github.com/amoss/netdata/blob/spike_cmake/config-cases.md). When the spike finishes this link may die - but the contents will move into a more permanent form as docs for the build-system.

**Comment by amoss** [comment]
Reminder: problems in #7091 need to be addressed.

**Comment by amoss** [comment]
Each feature of the autotools configuration is now covered by a mini PoC test in CMake that works. This was performed by working through the `config.h` output, and comparing to the stanzas in m4 and checking that we can regenerate everything.

Each of the cases that we needed a PoC for and the result is recorded in the link above, however it is only intended for me to keep track of progress.

There are two final details to resolve tomorrow:
1. Is there anything left in the installer that interacts with the `.m4` that has not been covered by a PoC?
2. The description of what has been done is a complete mess as it is only aimed at me - this will be rewritten into something that communicates what has been found during the spike.

The result of closing the spike will be a new issue with a list of what we need to do to port the build-system to CMake.

**Comment by amoss** [comment]
Now that the investigation is complete, the issue #7150 will track the conversion.
