### ISSUE TITLE
USE Method: Linux Performance Checklist

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#4313]
http://www.brendangregg.com/USEmethod/use-linux.html

This could be used to get ideas of netdata alarms.
It would also be interesting to map all these to netdata charts.

**Comment by paulfantom** [comment]
Add RED to it: https://www.weave.works/blog/the-red-method-key-metrics-for-microservices-architecture/

**Comment by Ferroin** [comment]
We've got much of the frameworks for both of these implemented already, and in fact already have some decent implementations in a few cases (if fully configured, the `web_log` module provides RED for web servers).

I'll look at getting alarms added for USE stuff that we don't currently have alarms for and putting together a set of feature requests for stuff from that which we don't currently track.

**Comment by Ferroin** [comment]
So, the more I'm looking at this, the more it's seeming to me like we already have what appropriate alarms make sense given what metrics we collect.  Much of the other stuff we don't have alarms for we can't realistically create specific alarms for simply because they're specific to how the system is supposed to work.  For example, high `iowait` CPU time is pretty universally indicative of a problem, but many of the other CPU usage types are functionally dependent on what the system is supposed to be doing normally, and therefore it doesn't make sense to ship alerts for, for example, high `guest` CPU usage.

**Comment by ktsaou** [comment]
Probably we have most of them. I think however we need to work even on naming the alarms properly.

The USE method defines 3 different sets of alarms:

- Utilization
- Saturation
- Errors

> For every resource, check utilization, saturation, and errors.

Terminology definitions:

- `resource`: all physical server functional components (CPUs, disks, busses, ...)
- `utilization`: the average time that the resource was busy servicing work
- `saturation`: the degree to which the resource has extra work which it can't service, often queued
- `errors`: the count of error events


The above could also be applied to software applications (e.g. mysql, postgres, etc).

So, the idea is to come up with a list of `resources`, the alarms we have for `utilization`, `saturation` and `errors` and find possible ways to collect information and configure alarms for the ones we don't currently have.

This list, would ideally be part of the documentation and being available for the users to examine and make suggestions.

RED (request Rate, request Errors, requests Duration) is also very interesting. For example `web_log` is already providing RED for web servers.

This work will save thousands of work-hours to all those using netdata. It will also give us a checklist when implementing new plugins, give our users a way to work on monitoring and significantly improve the usability of netdata.

I strongly believe we need our compliance with USE and RED documented.

So, @Ferroin 	can you make this list for USE?

@cakrit 	I think we should have USE and RED as part of the data collection modules checklist. We should have a documentation pages for describing USE and RED in general and then on each data collection module state the alarms and the corresponding USE/RED function.

**Comment by Ferroin** [comment]
@ktsaou The issue with that approach is that it ends up deviating from the standard terminology for a lot of the stuff we monitor, which makes it more difficult for people who are familiar with the monitored resources to understand what Netdata is doing.  Saturation in particular is rarely, if ever, used for referring to things other than hardware-level communications links (network, disk, etc).  Load average is essentially scheduler saturation, but you never hear anybody call it that because everybody just calls it the load average.

**Comment by Ferroin** [comment]
Regarding USE though:

* CPU:
    - Utilization: Covered by `system.cpu`, `cpu.cpu*`, and associated alarms.  Further alarms beyond what we already ship are likely to cause issues as anything other than hardirq, softirq, and iowait ends up being system specific.
    - Saturation: Partially covered by `system.load` and `system.idlejitter`.  Further coverage is likely to be complex and have severe performance impacts, as well as requiring special kernel configuration.
    - Errors: **Not currently covered.**
* Memory:
    - Utilization: Covered by `system.ram`, `system.swap`, most of the `mem.*` charts, and the associated alarms.
    - Saturation: Covered by `mem.pgfaults` and `mem.writeback`.  **Could be supplemented** by a chart tracking swap I/O independent of regular disk I/O.  Alarms are notoriously difficult, and mostly matter for one-shot events like OOM that we can't realistically track.
    - Errors: **Appears to not be currently covered.**
* Network Interfaces:
    - Utilization: Covered by `system.net`, `system.ip`, `system.ipv6`, `ipv*.*packets`, `net.*` and most associated alarms.
    - Saturation: Covered by `net.*` alarms and various error related `ip*` charts.
    - Errors: Covered by `ip.errors`, some `ip.tcp*` dimensions, `ipv*.*errors` charts, and associated alarms.
* Storage I/O:
    - Utilization: Covered by `system.io`, `system.pgpgio`, `disk.*`, `disk_ops.*`, `disk_util.*`, `disk_iotime.*`, and associated alarms.
    - Saturation: Covered by `disk_backlog.*`, `disk_await.*`, `disk_svctime.*`, and associated alarms.
    - Errors: Covered partially by the smartd python.d module.
* Storage Capacity:
    - Utilization: Covered by `disk_space.*` and associated alarms.
    - Saturation: Acknowledged by the USE method authors as nonsensical, possibly covered by the time-to-full disk alarms.
    - Errors: **Not currently covered**, _but_, coverage ranges from difficult to near impossible depending on the filesystem.
* Storage and Network controllers: Covered by appropriate Storage I/O and Network Interface items.
* CPU, Memory, and I/O interconnects: **Not currently covered**, coverage is non-trivial and likely to impose significant performance penalties.
* Kernel Mutex: **Not currently covered**.  Actual coverage requires special kernel options to be enabled which impose a non-negligible performance penalty.
* User Mutex: **Not currently covered**.  Actual coverage requires special instrumentation of userspace programs.
* Task Capacity:
    - Utilization: Partially covered by `system.load`, `system.processes`, and `system.active_processes`.See #2239 for discussion of enhancements.
    - Saturation: Partially covered by `system.load`, `system.processes`, and `system.ctxt`.  Additional coverage could be provided by looking for certain values in `/proc/$PID/wchan`, but would be non-trivial to implement and highly non-portable.  Coverage beyond that is functionally infeasible because it reduces to a combination of invasive instrumentation of the whole system and solving the halting problem.
    - Errors: **Not currently covered**.  Practical coverage requires potentially invasive instrumentation of the whole system.
* File Descriptors/Handles:
    - Utilization: Partially covered by `{apps,groups,users}.files`.  Further coverage requires tracking data for the whole system, as well as exposing a few sysctl values.
    - Saturation: Acknowledged by USE method authors as nonsensical.
    - Errors: **Not currently covered**.  Practical coverage requires potentially invasive instrumentation of all of userspace.

**Comment by ktsaou** [comment]
@Ferroin 	you rock!

For memory errors we have: `mem.hwcorrupt`

I guess most errors that have marked as "not currently covered", could potentially be implemented with eBPF...

**Comment by Ferroin** [comment]
@ktsaou Updated to include `mem.hwcorrupt`.  I don't have any systems running Netdata currently that report memory errors, so I don't have the chart on any of my systems, but I couldn't remember if we covered it or not.

As far as the others, none should require eBPF, but all of them other than CPU errors will have non-negligible performance penalties.

In particular:

* Task capacity, file descriptors, and storage capacity errors all require tracing for specific return values on specific system calls.  This can be done with strace, but is _extremely_ invasive and will add overhead to all the associated system calls (which is about 80% of the system calls regularly used by userspace applications outside of the networking stack).
* Kernel mutex related measurements require specific kernel options to be enabled.  Supporting them from the Netdata side might make sense, except no sane person runs with those options enabled in production because the performance penalty is steep enough that it can be measured without even needing to use `perf`.
* User mutex related measurements require use of a tool like `valgrind`, which is, again, something that imposes a sufficient performance penalty that no sane person uses it in production.
* The various system interconnects mostly require some form of special instrumentation provided by the hardware, and beyond that may require `perf`.  Some of them may be easily handled natively (for example, PCIe AER can probably be easily handled on Linux, as it gets routed through the EDAC interface, but it requires a special kernel boot parameter to be used to enable reporting beyond dmesg).  Most of them shouldn't need eBPF, but will require at minimum some level of kernel support.

**Comment by ktsaou** [comment]
hm... are you sure eBPF does not cover these? I probably need to read more about it. I had the impression it can see the return value of specific kernel calls. But, I may be mistaken.

**Comment by Ferroin** [comment]
eBPF may be able to cover task capacity errors, storage capacity errors, and file descriptor errors, but that doesn't change the fact that it's _still_ invasive, performance impacting instrumentation.  It still adds overhead, it still requires Netdata to be able to `ptrace()` _everything on the system_, and it's just as much of a pain to set up as having everything running under `strace`.  We _might_ be able to get away with leveraging the auditing subsystem in the Linux kernel to track this instead, but that still has really nasty security implications, adds non-negligible overhead, and is not something we can configure ourselves (it will have to be like the `web_log` plugin, we tell people how to configure things, but leave it to them to do so).

AFAIK, it can't cover the kernel locking stuff, at least, not how we would want to cover it.  We ultimately need lockdep and a bunch of the other locking related debugging stuff enabled to track that kind of thing, and _nobody_ sane runs a production kernel with that stuff enabled, it exposes too much of an attack surface and imposes too much of a performance penalty (it means _every_ lock in the kernel has extra instrumentation on it, depending on the workload this can easily lead to 10%+ performance degradation).

The userspace mutex stuff we can't use eBPF for because there are not any kernel calls that directly correlate to it.  `futex` usage comes close, but it's not everything.  

The interconnects have no associated kernel calls to watch in most cases.  Some of it really is trivial enough that we shouldn't need anything beyond the regular EDAC system (again, PCIe AER support as an example), and much of the rest we could track by watching kernel logs, but there's only so much we can do for these types of things given that the kernel doesn't even track a lot of it, and what it does or can track needs specific hardware support.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
