### ISSUE TITLE
Request statsd backend

### ISSUE THREAD

**Issue by aronneagu** [netdata/netdata#4353]
Hello. I am very impressed with netdata and what it can do.
I would like to push these metrics into Splunk, and as of Splunk 7.0 it supports ingesting metrics, but the only formats it understands are statsd and collectd line protocols.

The graphite protocol is very similar statsd so I was wondering if it would be possible to create statsd backend?

Thank you

**Comment by ktsaou** [comment]
Could you please point the relative splunk documentation?
If it does not require authentication, it would be quite simple to build it.

**Comment by aronneagu** [comment]
It doesn't require authentication. Splunk will listen on particular TPC or UDP port, but the format of the data needs to be in StatsD format: eg: 
 <metric_name>:<_value>|<metric_type>
https://docs.splunk.com/Documentation/Splunk/7.1.3/Metrics/GetMetricsInStatsd

**Comment by halr9000** [comment]
Splunker here, just found the project. Can I help?

**Comment by vlvkobal** [comment]
Hey @halr9000, glad you are willing to help! I read about getting metrics into Splunk from other sources. Did I understand correctly that it is possible to do with graphite protocol, and all we need is to create `props.conf` and `transforms.conf`?

**Comment by halr9000** [comment]
Actually, yes! But that advice was before we shipped the metric store feature. (Overview: https://docs.splunk.com/Documentation/Splunk/7.2.5/Metrics/Overview). The metric store is the right way to store Netdata metrics, so that should be called out specifically so that customers can see the performance benefits. The easiest way to get them in (if Netdata supports it) would be using the statsd protocol over either TCP or UDP. The second preferred option would be over HTTP/S POST with a certain JSON body. These two options would require almost no configuration on the Splunk side. These are documented here: https://docs.splunk.com/Documentation/Splunk/7.2.5/Metrics/GetStarted. 

We didn’t get around to supporting Grpahite protocol in the same way, but we did actually add a transformation feature more recently, and as luck would have it, we included a Graphote example in the docs: https://docs.splunk.com/Documentation/Splunk/7.2.5/Metrics/GetMetricsInOther#Get_metrics_in_from_clients_over_TCP.2FUDP

What are your thoughts @vlvkobal ?

**Comment by vlvkobal** [comment]
@halr9000 thank you for the clarifications. I'm putting statsd backend implementation to my backlog, assigning low priority though, as far as it is possible to export metrics using the transformation feature.

**Comment by ilyam8** [comment]
Closing this issue due to the low interest in this feautre.

If there is anybody who is interesed in having this implemented please visit our Community Forums and create a new topic in the [Netdata Agent Feature Requests](https://community.netdata.cloud/c/feature-requests/agent-fr/21) category.
