### ISSUE TITLE
please parse config when using alarm-notify.sh test

### ISSUE THREAD

**Issue by working-name** [netdata/netdata#4362]
This thing **ROCKS**. You are a wizard as far as I'm concerned, getting so much with such a tiny footprint. Ah-mazing. Thank you for making it open source as well.

Here's an improvement request, which I would do myself if I knew how to pull the config in... short of a bunch of `grep` and `if else`.

```php
Your netdata version: 1.10.0-763-ga441c0a2_rolling
Your netdata commit: a441c0a
```

I shot `/usr/libexec/netdata/plugins.d/alarm-notify.sh test` from one of my hosts and the notification arrives to me via telegram with the hostname as the output of `hostname` instead of what I set under `[global]`. 

I looked at the bash script but I have no idea where or what provides `${host}` so not off to a great start :( 

In addition, `alarm-notify.sh` has a default registry url when ran manually that is your own (netdata.io), making it tough to actually follow URLs in messages sent. The reason I bring that up is that, again, the host passed in that URL is the box's own host rather than the custom name assigned in `[global]`. Netdata says "sorry don't have a server named `real-host-name-but-no-tld`" when one changes the default registry URL in the file and clicks the *new* test notification link.

Thank you!

**Comment by cakrit** [comment]
Apologies for not replying sooner. 

Running alarm-notify.sh in test mode does not behave exactly as netdata does when it dispatches a notification. netdata actually does pass to alarm-notify what you configure in [global] as the host. The link in the notification actually goes to the registry with the exact same host, so that the registry can find the actual URL to redirect you to. It wouldn't work only if the registry had never seen that host before (e.g. if you never opened that specific console).

I'm closing this, but please comment if you feel your question wasn't answered and we'll look into it more.
