### ISSUE TITLE
Deleting server from personal list (registry) fails: "Sorry! this command was rejected by the registry server."

### ISSUE THREAD

**Issue by 74cmonty** [netdata/netdata#4375]
Hello!
When I try to delete a server from personal list (registry) this fails with the following error: "Sorry! this command was rejected by the registry server."
![2018-10-10_11-15-00](https://user-images.githubusercontent.com/12523591/46735513-b34b0900-cc96-11e8-9086-1230093005a8.png)

How can I fix this?

THX

**Comment by rob-duewer** [comment]
I've got the same question.  The old entries I need to remove in my list have now been configured to register only to the machine serving as private registry and have been configured to have no web front end of their own.

Thanks!

**Comment by ktsaou** [comment]
Could you please press F12 on your browser to open the console and repeat that?
it should report something like:

```
ERROR 412: DELETE command failed.
``

Which error code does it say?

**Comment by cakrit** [comment]
This happens when you switch to a different registry. I experimented with this and discovered that I had to `clear` my `local storage` to get rid of the servers that the local registry wasn't aware of, which appeared in key `registryCallback`:

![screenshot from 2018-12-16 19-01-25](https://user-images.githubusercontent.com/43294513/50057045-6e939080-0165-11e9-8fbc-eb3ac831e4af.png)

After I cleared it and reloaded the page, I got the info from my new, local registry (i.e. just my own server, since I hadn't been anywhere else). 

Pressing the trash icon had no effect of course, because my local registry didn't know those servers anyway, they only appeared because my browser had them. If you don't want to lose some of those servers, perhaps there's a way to just manipulate those values, though chrome told me that I could just refresh them. A workaround would be to switch back to the netdata registry, delete the ones you don't want, and then switch back to your registry.
