### ISSUE TITLE
Feature Request: support multiple stream destination

### ISSUE THREAD

**Issue by Ehekatl** [netdata/netdata#4395]
It would be awesome if streaming could support multiple destinations, say a backup node for redundancy, or send different charts to different destination with the filtering feature from #4361

**Comment by ktsaou** [comment]
Yes, this would be good.

Keep in mind netdata supports some kind of fault tolerance. You can configure the slave with:

```
destination = master1:19999 master2:19999
```

Using the above, `master2` will be used only when `master1` is offline.
You could also configure `master1` to mirror its metrics to `master2`.

So, it will be like this:

`slave` -> `master1` -> `master2`

If `master1` is down, the slave will automatically switch to `master2`.

**Comment by ktsaou** [comment]
Since we plan to add compression and streaming of past metrics, another perfect solution would be:

`slave` -> `master1` <-> `master2`

In this scenario, `master1` and `master2` form a loop, so that only the one receiving the metrics from `slave` will stream to the other end.

This implementation would not need multiple streaming threads at the slave.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
