### ISSUE TITLE
How to setup the tc plugin 

### ISSUE THREAD

**Issue by ryanmatthieu** [netdata/netdata#4563]
##### Question summary
Hello ,

I am using netdata on a project for school about Quality of Service. The tool is working great but I have an issue on how to setup the tc plugin (https://github.com/netdata/netdata/tree/master/collectors/tc.plugin)

I tried to run the **tc-qos-helper.sh.in** script but it kept showing me this message : 

```
2018-11-04 22:59:56: tc-qos-helper.sh.in: WARNING: FireQoS is not installed on this system. Use FireQoS to apply traffic QoS and expose the class names to netdata. Check https://github.com/netdata/netdata/wiki/You-should-install-QoS-on-all-your-servers
2018-11-04 22:59:56: tc-qos-helper.sh.in: WARNING: Cannot find file '@libconfigdir_POST@/tc-qos-helper.conf'.
2018-11-04 22:59:56: tc-qos-helper.sh.in: WARNING: Cannot find file '@configdir_POST@/tc-qos-helper.conf'.
/home/server/tc-qos-helper.sh.in: line 175: /home/server/loopsleepms.sh.inc: No such file or directory
```
And no charts have been added to the netdata web interface .
I am not using fireQoS but the native tc tools , am I doing something wrong ?

How should I set it up so it shows charts with _**tc.world_in**_ and _**tc.world_out**_ as shown on the demo of the plugin ?

Sorry if I misread or misunderstood anything and many thanks in advance for your help .

##### OS / Environment
lubuntu-16.04.3-desktop-amd64
Using a VM on Virtual Box 

##### Component Name
tc.plugin

##### Expected results
Show charts for tc metrics

**Comment by ktsaou** [comment]
Hi, there is not much to configure for `tc` plugin.
Just install netdata and start it up.

If you have QoS running (no matter if it is configured by FireQoS or not), netdata should be able to pick it up and show it.

To configure class names, you will have to edit `/etc/iproute2/tc_cls`. With FireQoS this is not needed (the plugin picks up the names set by FireQoS).

**Comment by ktsaou** [comment]
You can create `etc/iproute2/tc_cls`. This is just to pick up the names.

Can you post the output of:

```sh
/usr/libexec/netdata/plugins.d/tc-qos-helper.sh
```

Leave it running for 2-3 seconds and stop it with Control-C.

**Comment by ryanmatthieu** [comment]
This was the output : 
```
root@server-VirtualBox:/usr/libexec/netdata/plugins.d# ./tc-qos-helper.sh 
2018-11-07 20:37:59: tc-qos-helper.sh: WARNING: FireQoS is not installed on this system. Use FireQoS to apply traffic QoS and expose the class names to netdata. Check https://github.com/netdata/netdata/wiki/You-should-install-QoS-on-all-your-servers
2018-11-07 20:37:59: tc-qos-helper.sh: WARNING: Cannot find file '/usr/lib/netdata/conf.d/tc-qos-helper.conf'.
2018-11-07 20:37:59: tc-qos-helper.sh: WARNING: Cannot find file '/etc/netdata/tc-qos-helper.conf'.
BEGIN enp0s8
qdisc htb 1: root refcnt 2 r2q 10 default 10 direct_packets_stat 17708 direct_qlen 1000
 Sent 362614284 bytes 250547 pkt (dropped 0, overlimits 654991 requeues 0) 
 backlog 0b 0p requeues 0 
END enp0s8
WORKTIME 0
BEGIN enp0s8
qdisc htb 1: root refcnt 2 r2q 10 default 10 direct_packets_stat 17708 direct_qlen 1000
 Sent 362614284 bytes 250547 pkt (dropped 0, overlimits 654991 requeues 0) 
 backlog 0b 0p requeues 0 
END enp0s8
WORKTIME 0
BEGIN enp0s8
qdisc htb 1: root refcnt 2 r2q 10 default 10 direct_packets_stat 17708 direct_qlen 1000
 Sent 362614284 bytes 250547 pkt (dropped 0, overlimits 654991 requeues 0) 
 backlog 0b 0p requeues 0 
END enp0s8
WORKTIME 6
BEGIN enp0s8
qdisc htb 1: root refcnt 2 r2q 10 default 10 direct_packets_stat 17708 direct_qlen 1000
 Sent 362614284 bytes 250547 pkt (dropped 0, overlimits 654991 requeues 0) 
 backlog 0b 0p requeues 0 
END enp0s8
WORKTIME 16
BEGIN enp0s8
qdisc htb 1: root refcnt 2 r2q 10 default 10 direct_packets_stat 17708 direct_qlen 1000
 Sent 362614284 bytes 250547 pkt (dropped 0, overlimits 654991 requeues 0) 
 backlog 0b 0p requeues 0 
END enp0s8
WORKTIME 16

**Comment by ktsaou** [comment]
So, there should be a chart about `enp0s8`.

Like this:

![image](https://user-images.githubusercontent.com/2662304/48197770-6757b680-e35f-11e8-8d5d-48d7ae00f286.png)

Do you have it?

**Comment by ryanmatthieu** [comment]
I don't have it ... Here is a screenshot of the VM : 
![capture](https://user-images.githubusercontent.com/44787786/48211647-c6e99e00-e32e-11e8-93ef-c8c2f27ceab4.PNG)

**Comment by laneshields** [comment]
Since I stumbled across this when I was trying to remember what I did to set this up in the past, I'll add the steps I used

First, I setup the tc rules in rc.local using the following commands to assicn different DSCP markings to different classids (I'm also using netem on these interfaces to inject impairments which is why I create the root qdisc that way):

`tc qdisc add dev eth5 root handle 1: netem loss 0%
tc qdisc add dev eth5 parent 1: handle 2: htb default 1
tc class add dev eth5 parent 2: classid 2:1 htb rate 1gbit burst 1gbit
tc class add dev eth5 parent 2: classid 2:8 htb rate 1gbit burst 1gbit
tc class add dev eth5 parent 2: classid 2:10 htb rate 1gbit burst 1gbit
tc class add dev eth5 parent 2: classid 2:16 htb rate 1gbit burst 1gbit
tc class add dev eth5 parent 2: classid 2:18 htb rate 1gbit burst 1gbit
tc class add dev eth5 parent 2: classid 2:24 htb rate 1gbit burst 1gbit
tc class add dev eth5 parent 2: classid 2:26 htb rate 1gbit burst 1gbit
tc class add dev eth5 parent 2: classid 2:32 htb rate 1gbit burst 1gbit
tc class add dev eth5 parent 2: classid 2:34 htb rate 1gbit burst 1gbit
tc class add dev eth5 parent 2: classid 2:40 htb rate 1gbit burst 1gbit
tc class add dev eth5 parent 2: classid 2:46 htb rate 1gbit burst 1gbit
tc class add dev eth5 parent 2: classid 2:48 htb rate 1gbit burst 1gbit

tc filter add dev eth5 protocol ip parent 2: prio 1 u32 match ip dsfield 0x20 0xff classid 2:8
tc filter add dev eth5 protocol ip parent 2: prio 1 u32 match ip dsfield 0x28 0xff classid 2:10
tc filter add dev eth5 protocol ip parent 2: prio 1 u32 match ip dsfield 0x40 0xff classid 2:16
tc filter add dev eth5 protocol ip parent 2: prio 1 u32 match ip dsfield 0x48 0xff classid 2:18
tc filter add dev eth5 protocol ip parent 2: prio 1 u32 match ip dsfield 0x60 0xff classid 2:24
tc filter add dev eth5 protocol ip parent 2: prio 1 u32 match ip dsfield 0x68 0xff classid 2:26
tc filter add dev eth5 protocol ip parent 2: prio 1 u32 match ip dsfield 0x80 0xff classid 2:32
tc filter add dev eth5 protocol ip parent 2: prio 1 u32 match ip dsfield 0x88 0xff classid 2:34
tc filter add dev eth5 protocol ip parent 2: prio 1 u32 match ip dsfield 0xa0 0xff classid 2:40
tc filter add dev eth5 protocol ip parent 2: prio 1 u32 match ip dsfield 0xb8 0xff classid 2:46
tc filter add dev eth5 protocol ip parent 2: prio 1 u32 match ip dsfield 0xc0 0xff classid 2:48

tc qdisc add dev eth6 root handle 1: netem loss 0%
tc qdisc add dev eth6 parent 1: handle 2: htb default 1
tc class add dev eth6 parent 2: classid 2:1 htb rate 1gbit burst 1gbit
tc class add dev eth6 parent 2: classid 2:8 htb rate 1gbit burst 1gbit
tc class add dev eth6 parent 2: classid 2:10 htb rate 1gbit burst 1gbit
tc class add dev eth6 parent 2: classid 2:16 htb rate 1gbit burst 1gbit
tc class add dev eth6 parent 2: classid 2:18 htb rate 1gbit burst 1gbit
tc class add dev eth6 parent 2: classid 2:24 htb rate 1gbit burst 1gbit
tc class add dev eth6 parent 2: classid 2:26 htb rate 1gbit burst 1gbit
tc class add dev eth6 parent 2: classid 2:32 htb rate 1gbit burst 1gbit
tc class add dev eth6 parent 2: classid 2:34 htb rate 1gbit burst 1gbit
tc class add dev eth6 parent 2: classid 2:40 htb rate 1gbit burst 1gbit
tc class add dev eth6 parent 2: classid 2:46 htb rate 1gbit burst 1gbit
tc class add dev eth6 parent 2: classid 2:48 htb rate 1gbit burst 1gbit

tc filter add dev eth6 protocol ip parent 2: prio 1 u32 match ip dsfield 0x20 0xff classid 2:8
tc filter add dev eth6 protocol ip parent 2: prio 1 u32 match ip dsfield 0x28 0xff classid 2:10
tc filter add dev eth6 protocol ip parent 2: prio 1 u32 match ip dsfield 0x40 0xff classid 2:16
tc filter add dev eth6 protocol ip parent 2: prio 1 u32 match ip dsfield 0x48 0xff classid 2:18
tc filter add dev eth6 protocol ip parent 2: prio 1 u32 match ip dsfield 0x60 0xff classid 2:24
tc filter add dev eth6 protocol ip parent 2: prio 1 u32 match ip dsfield 0x68 0xff classid 2:26
tc filter add dev eth6 protocol ip parent 2: prio 1 u32 match ip dsfield 0x80 0xff classid 2:32
tc filter add dev eth6 protocol ip parent 2: prio 1 u32 match ip dsfield 0x88 0xff classid 2:34
tc filter add dev eth6 protocol ip parent 2: prio 1 u32 match ip dsfield 0xa0 0xff classid 2:40
tc filter add dev eth6 protocol ip parent 2: prio 1 u32 match ip dsfield 0xb8 0xff classid 2:46
tc filter add dev eth6 protocol ip parent 2: prio 1 u32 match ip dsfield 0xc0 0xff classid 2:48
`

Then I mapped the classids to names by creating /etc/iproute2/tc_cls
`2:1 Standard
2:8 LowPriorityData
2:10 HighThroughputData
2:16 OAM
2:18 LowLatencyData
2:24 BroadcastVideo
2:26 MultimediaStreaming
2:32 RealTimeInteractive
2:34 MultimediaConferencing
2:40 Signalling
2:46 Telephony
2:48 NetworkControl
`
For netdata, I needed to add this configuration option in /etc/netdata.conf
`[plugin:tc]
        enable show all classes and qdiscs for all interfaces = yes
`

And finally, I needed to create /etc/netdata/tc-qos-helper.conf with this content
`tc_show="class"`

**Comment by cakrit** [comment]
@laneshields I want to add this to our official docs. Can you please look at PR #5221 and provide your approval?

**Comment by cakrit** [comment]
This issue has been referenced in the docs. 
https://docs.netdata.cloud/collectors/tc.plugin/#qos-configuration-with-tc

Closing it.
