### ISSUE TITLE
Proposal for improved Git workflow

### ISSUE THREAD

**Issue by gmosx** [netdata/netdata#4579]
Currently, new features are merged from contributor-branches or feature-branches directly into the `master` branch. Moreover, users that have enabled automatic updates, pull the latest `master` branch, _daily_.

This is not robust, it's very easy to push poorly-tested features to end-users. Moreover, it's not easy to merge big features that are under development so that contributors can build on each other's work.

Instead, I propose the following scheme:

* The `master` branch is used exclusively to build releases. Additionally, hot-fixes for the current release will be merged into master (and minor releases created, e.g. 1.11.1).

* We introduce a `beta` branch where stable/safe features of the _next_ release are merged. The users with enabled automatic updates will pull from the `beta` branch. When the next release is stabilized and sufficiently tested, `beta` will be merged into `master` to create the new release. Hot-fixes in `master` are merged (forward-ported) into `beta`.

* We introduce a series of `dev-X.Y` branches for the upcoming 2 releases (i.e. currently, we should introduce the `dev-1.12` and `dev-1.13` branches). Features under development that are not safe to push to end-users should be merged in the `dev-X.Y` branches.

Such a scheme will give us more flexibility (and peace of mind).

What do you think?

**Comment by paulfantom** [comment]
This is not "improved" and more like going back.

First of all git-flow makes project much more unreadable due to much more complex git history. It also creates problems with rebases between branches due to frequent incompatibility. If you look into what github offers for project management it is mostly incompatibile with git-flow and needs workarounds with bots and additional CI pipelines. Another issue is the fact that this flow is different from default one on github, which can be confusing for new contributors.

Now for other parts:
> Moreover, users that have enabled automatic updates, pull the latest master branch, daily.

We already have nightly builds, so why not use them for this? Also bear in mind that we want to move from using git/installer script as an update method and move to binary packages.

> This is not robust, it's very easy to push poorly-tested features to end-users.

Git flow doesn't prevent that if you don't have a test suite and if you have a test suite then what's stopping you from running it in CI on every PR? There is even an issue with it here: https://github.com/netdata/netdata/issues/4222

> We introduce a series of dev-X.Y branches for the upcoming 2 releases

It seems like this was already tried by Costa (branch `1.3.0-support`) and this experiment failed. Additionally this hugely complicates current CI system.

**Comment by gmosx** [comment]
Let me describe the motivating problem: 

I need to merge a big PR (`split-js-2`) somewhere so that I can keep working on it. I cannot merge into `master` because it lacks sufficient testing (and the test-coverage for `dashboard.js` ...leaves a lot to be desired 😀). I cannot keep working on my feature-branch because the eventual PR will be un-reviewable.

I suspect we will have issues like this more often as new people will start actively contributing. I understand that the proper solution requires a lot of effort (including proper testing). The question is, given your expertise, can you think of an easy solution for the short-term? 

Also, ignoring this specific problem, I still believe some kind of 'consolidation' branch would be beneficial.

**Comment by ktsaou** [comment]
@paulfantom 	@gmosx 	the problem we have at hand:

1. A big change is to be merged, which is not sufficiently tested.
2. @gmosx 	feels better to have this merged "somewhere", so that we can add things to it.

I wouldn't generalize the situation.

So, I agree with @paulfantom 	that following a git-flow procedure is not ideal for us, but at the same time I understand that we need to collaborate on significant changes. I respect the fact that @gmosx 	wants it "merged".

So, I suggest to create a branch on the master repo for this special case. @paulfantom 	we won't follow git-flow, but let's be flexible a bit.

So, please create that branch, let's merge there the changes @gmosx 	wants, let's add there related to his work PRs and let's merge the whole thing when we have tested it enough.

It is an ad-hoc action that seems reasonable for this case.

**Comment by paulfantom** [comment]
I don't understand what would that solve? What is the difference between having a not used branch in netdata repo vs a branch in a PR? You can test it in both ways, you can collaborate on both of this and you can merge/rebase stuff on both.

**Comment by ktsaou** [comment]
I guess there is no difference in either way.
Psychological maybe?

What I suggest, is to leave the discussion about git-flow or github-flow for our meetup. Now, just ad-hoc, create a branch and let's proceed.

We (all together) will take the final decision in 15 days.

**Comment by cakrit** [comment]
Indeed this is something we need to discuss and agree in person. Some of us are used to a different way of testing and releasing code, so it's more of an alignment on how the common risks in all projects with multiple contributors can be mitigated.

**Comment by paulfantom** [comment]
We agreed not to do this :smile:
