### ISSUE TITLE
Feature like 'who' command

### ISSUE THREAD

**Issue by petrukngantuk** [netdata/netdata#4619]
Is There A Feature that can monitoring user that connect to our server using ssh?
like command `who` in linux

##### Feature idea summary
Add feature that can monitor who is connect to our server like who commad in linux, thats shown user pts and ip, and if alarm enabled it's send to info to alarm,

##### Expected behavior
So we can monitor who connect to the server using ssh, if anything bad happend we can monitor it,

**Comment by Ferroin** [comment]
For simple user and session counts, you can use the `logind` python.d module (info about setup can be found [here](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/logind)).  This provides user counts per session type and total session counts per type.  This depends on either running systemd, or having something on the system that provides an API equivalent to the `loginctl` command provided by systemd (such as Gentoo's `elogind`).

For tracking which individual users are using resources on the system, you can use the `apps.plugin`, which includes charts for tracking resource usage per-user.  This covers basic resource usage (CPU, memory, storage I/O, network I/O, and process counts).  It doesn't depend on anything, but has one big limitation for this in that it lists all users who have running processes, which is not necessarily the same as all users who are logged in to the system (because it also tracks system users, and it's possible for users to start long-lived processes that don't terminate when they log out).  This plugin is enabled by default and the charts for this can be seen in the 'Users' section of the dashboard.

**Comment by petrukngantuk** [comment]
Thanks for the answer...

**Comment by petrukngantuk** [comment]
can I replace the loginctl with who command?

**Comment by Ferroin** [comment]
Unfortunately no, the parsing is pretty specific and won't work with the regular `who` command.

**Comment by ktsaou** [comment]
This is another raw list we could expose on the dashboard raw / as-collected.
We should probably collect all those lists at an issue.

**Comment by ilyam8** [comment]
> Add feature that can monitor who is connect to our server like who commad in linux, thats shown user pts and ip

> shown user pts and ip

i see no way to represent it on the current dashboard

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
