### ISSUE TITLE
Netdata cpu tags

### ISSUE THREAD

**Issue by springerst94** [netdata/netdata#4677]
Is it possible to use wildcards, i.e.  an * as a wild card in a tag?  I'd like to create a variable that gives me the ability to create a drop down window in grafana - using netdata to feed an influxdb database using an opentsdb format.

the current os is Ubuntu 16.04 on all systems

Kubernetes containers are running

**Comment by springerst94** [comment]
In netdata there are graphs that are based upon cpu.cpu0, cpu.cpu1, etc. I have not been able to create a tag withing netdata that uses wild card so I can specify cpu.cpu* and select multiple systems via one tag. The tags I've tried are in the influxdb database, port into grafana, but do not allow multiple selections. 
The issue is I need to create/specify one tag in netdata backend that equals cpu.cpu* allowing any cpu number to be selected.

**Comment by ktsaou** [comment]
I think this is a problem of the opentsdb format.
In prometheus, we use the `context` as the metric and the chart id is a label attached to the values pushed.

So, instead of `cpu.cpu1.user`, in prometheus we push `cpu_cpu{chart="cpu.cpu1",dimemsion="user"}`. This allows grouping them in grafana.

I don't know if OpenTSDB supports this kind of labels attached to metrics.
If it supports it, it would be nice to follow the prometheus way for OpenTSDB too.

**Comment by springerst94** [comment]
I'm using influxdb. Is ther a format in influxbd that supports how netdata records the individual cpu data.
