### ISSUE TITLE
new database format design

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#4687]
##### Feature idea summary

netdata internal database v2.
Specs to follow.

**Comment by cakrit** [comment]
One of the things the new DB will ensure is that obsolete metrics are removed (mentioned in #896, #4987).

**Comment by mfundul** [comment]
> 
> 
> Some of the discussion from #3333 is probably of interest here.

It is definitely relevant.

**Comment by cakrit** [comment]
Let's please put the design here so we can close this one and create issues for the different releases we'll be doing. It will be clearer to the community.

**Comment by mfundul** [comment]
# netdata time-series database

## Overview

There are 3 functions related to the time-series database:

1. Data Collection
2. Data Queries
3. Database Management

The principles of the above 3 should define the design of the new netdata database.

## Data Collection

The key motivation in data collection is to minimize its memory requirements. So, when a netdata daemon collects data, the memory required should be the minimum possible.

Of course, this means that data collection will have some kind of permanent disk writes. We call the persistent storage module **netdata storage engine**.

### Design

Netdata collects metrics using multiple threads. Each metric is allowed to be collected by only one data collection thread.

So, each metric will have 2 entities:

1. A working page of data
2. Completed pages of data, ready to be archived

#### Pages of Data

Pages of data (4 KiB) are always allocated by the **database cache**. All pages of data are treated as equal (so they can be loaded and saved to disk), even when incomplete (e.g. netdata exits while a page of data is half-full).

#### Working Page of Data

While data collection runs, each thread works on a number of metrics and each metric has a **working page of data** (this is incomplete, most of the time). When a **working page of data** is completed, this page is sent for archiving and a new working page of data is created.

#### Completed Page of Data

Once a ** working page of data** is full or forced to be flushed (a timeout or program exit), it is marked as **completed page of data** and is ready to be saved to disk. The process of saving pages is part of the **netdata storage engine** and is initiated by the **database cache**.

## Data Queries

The key motivation in data queries is again to minimize their memory requirements. So, whenever there is a netdata data query, the memory used should only concern the **pages of data** that have been requested, and only for the duration that they were needed.

This means that data queries will trigger read I/O requests to **netdata storage engine**. 

## Database management

The motivation behind database management is that:
* Resource consumption should be minimal in the system. The biggest problem with the current database is I/O interference. Random I/O requests should be avoided when writing to persistent storage. Syncing with persistent storage should also be avoided if possible. Rotating media should be supported.
* Metrics should support various tiers with different granularity in the same database, e.g. every second, hourly, weekly etc.
* _EXTEND / SHRINK WITHOUT REBUILDING?_
* _LOADING TIME SHOULD BE FAST_

### Database Cache

The **database cache** is the part of the database that handles uncompressed data, indices and other metadata in memory. The metric data can be cached in memory only up to a certain configurable limit, and the rest of them only reside in the **data files**. On the other hand, there is no metadata cache in this design. The metadata in its entirety should always fit in memory.

All changes to metrics metadata are persistently stored in **Write-Ahead Log** files. The metadata that are native to this time series database design reside exclusively in the data structures called **page cache** and **metrics index**.

The rest of the metadata being stored in the **WAL** files are considered external to this design and are handled by the application (netdata). For example, the mapping of metric UUIDs to description strings, or the mapping of metrics to charts are metadata that the **database cache** is not aware of. Those metadata are to only be handled by the application directly and stored in the **WAL** in a data agnostic manner.

#### Page Cache

The metrics reside in **pages of data** and those pages comprise the **page cache**. The **page cache** is responsible for indexing all metric data in memory and initiating disk I/O writes to serve data collection. Locating completed **pages of data** on disk and the mapping of timestamps to those locations to serve data queries is also handled by the **page cache**.

There is a maximum amount of **pages of data** that are allowed to remain in memory. Whenever there is a new data query or memory pressure from data collection and the **page cache** is full, a **completed page of data** is evicted to create space (via an eviction policy).

#### Metrics Index

The **metrics index** is a hash table that maps metric UUIDs (128 bit) to the corresponding **page cache** indices. Any additional metadata of the metrics (e.g. string names, descriptions, chart associations, alarms) are considered external to this database design and are handled by the application (netdata). _WHEN TREE IS EMPTY DELETE METRIC FROM METRICS MAP_

#### Metrics Map

The purpose is to map metric names (strings) to metric UUIDs. Add this to checkpoints. WAL has nothing to do with this. Use its own file, like an operation log, checkpoints clean it up. Threshold that triggers cleanup (e.g. 10% unused maps). _Plugins API protocol?_

Example (these commands would create RRDIM):
`VERSION 1.2`
`ADD  <uuid>\t<host>\t<chart>\t<dimension>\t<flags>`
`VERSION 1.3`
`ADD <uuid>\t<host>\t<chart>\t<dimension>\t<flags>\t<ext1>`
`DELETE <uuid>\t<host>\t<chart>\t<dimension>`

If the file had only the first two ADD commands, after clean up with the first 2 commands for the same uuid  in the file, I would end up with:
`ADD <uuid>\t<host>\t<chart>\t<dimension>\t<flags>\t<ext1>`

If the file had the two ADD and the one DELETE command for the same uuid, after clean up we would end up with nothing for this uuid.

Note that the trigger for a DELETE command is that the last file with metrics for the particular UUID has been removed from the DB and the page cache index for this uuid is now empty. 

When a new version comes in, ADD commands will be dumped from memory to the file with the new version, so that a cleanup can retain only the new version commands.

### netdata Storage Engine

The **netdata storage engine** contains metric **data files** and their corresponding commit log files (**Write-Ahead Log**). The **data files** contain data pages of metrics. The metrics’ metadata and indexing structures can be recreated in memory by reading and replaying the **WAL** file of the set. The **netdata storage engine** supports progressively thinning of metrics by organizing them into tiers (_What about supporting different types of data, not only metrics, e.g. LOGS??? use blob per page???_).

#### Design

Each **data file** is mapped to exactly one journaling file (**WAL**). Each set of **data file** and **WAL** file is independent of all other sets. The oldest set of files is automatically deleted when the maximum allowed disk space quota is exceeded. A set of a **data file** and its **WAL** can be safely deleted by the user without corrupting the database as long as netdata is offline.

There can be different tiers of those sets. The first tier is always real-time monitoring (**tier-1**). The second tier (**tier-2**) is lower rate, has a larger sampling interval. Similarly, there can be more tiers that progressively thin out the metrics. The objective is for each tier to have a different granularity (e.g. per second, hourly, daily)  so as to store metrics for longer periods of time. **Tier-1** has configurable granularity per metric whereas **tier-N** where N > 1 has a global sampling rate for all metrics belonging in it (OR NOT).

**Tier-N** metrics are created by a transformation from **tier-(N-1)** by downsampling with a consolidation function (e.g. an averaging function). Ideally, tiers should not contain derivative metrics but raw metrics (e.g. sums). This ensures that the transformation avoids statistical errors such as averaging of average values. For such an aggregation of metrics to be relatively accurate there is the need for the resolution of **tier-(N-1)** be divisible by the resolution of **tier-N**. If the timescale difference of the two tiers is quite large then the margin of error is not considered significant (_configurable?_).

We use Little-Endian byte order in **netdata storage engine**. This allows for lower overhead implementations in the most popular architectures, since no transformation need take place (_maybe native byte order? No portability then_).

##### Data File

The **data files** are organized in 1MiB(_configurable?_) **extents** of metric data. An **extent** may contain multiple metrics. The **extents** are immutable and the **data files** are append only. One **extent** contains 256 4KiB-blocks, each block containing exactly one **completed page of data**.

The **extent** is compressed and stored in a **data file** with a low overhead algorithm (e.g. lz4). The alignment of the compressed **extent** (plus the header and trailer) in the **data file** is 4KiB (same as the block size). For example, if 1MiB is compressed to 3000 bytes then the compressed **extent** payload plus its header and trailer should allocate 4KiB of file space.

The 1MiB extent size was chosen because (_MAKE THIS CONFIGURABLE and dynamic at real time? make everything 64 bits maybe?_):
* It improves compression efficiency and approximates local (within the extent) de-duplication of data compared to smaller extent sizes.
* It is not too large as shown by the majority of storage products in the industry that utilize this exact extent size.
* It is large enough to improve spinning disk utilization even when they are doing random I/O and even SSD utilization to some degree. Spinning disks take great advantage of large I/O requests since this minimizes the frequency of seek operations. SSD disks prefer large I/O requests because it’s easier on their controller firmware and it may even lead to less metadata traffic or smaller write amplification.

The 4KiB alignment in the data files has several advantages:
* We can send direct I/O requests to the files thus avoiding polluting the file system buffer cache, limiting our interference with the rest of the system and gaining guaranteed real-time control over disk I/O performance and error conditions. We can effectively throttle the database’s I/O traffic on demand.
* We avoid Read-Modify-Write operations that may hurt performance and increase complexity in the case of direct I/O.
* Simplifies indexing due to the 4KiB granularity versus the arbitrary byte range granularity.

The **pages of data** from the **extents** are also indexed in memory in the **database cache**. The dirty (**working pages of data**) **pages of data** in the **page cache** are pinned, and cannot be evicted. The clean **pages of data** however can be evicted with an LRU eviction policy. Indexing granularity is per **page of data**, however, we prefer reading whole **extents**, instead of single **pages of data**, from disk for retrieving metrics because we can take advantage of the spatial and temporal locality exhibited when observing metrics.

##### Write-Ahead Log

The application (netdata) structures and meta-data are persisted in the **Write-Ahead-Log** files. Chart creation, names, indices and other metadata are written as transactions of the operation log. Those structures only reside in the application memory. They must always be able to be reconstructed by replaying the **WAL** files and interpreting the operations.

Losing any **WAL** file would be catastrophic, since we would have lost metadata. Moreover, replaying the logs can be time-consuming when the database becomes large enough. Also, ephemeral metadata can consume a lot of space unnecessarily. For those reasons we use checkpointing.

The application (netdata) provides a function that serializes its data structures in a byte-stream format only know to the application. The serialization process only takes place after the database decides to create a checkpoint, asynchronously. The ideal time for checkpointing is when the database is creating a new **WAL** file. The ideal place for the application byte-stream is the beginning of the new **WAL** file. _KEEP CHECKPOINT FILE SEPARATE_

All operations that are native to the **netdata storage engine** such as storing metrics in **data files** or creating new metrics when journaled by the **WAL** are automatically replayed to produce the in-memory data structures of the **database cache**. All other operations that are external to the **netdata storage engine** are explicitly journaled by the application and are replayed by **WAL** which calls the corresponding application hooks.

We split the database metadata into 2 categories, **serializable** and **non-serializable**:
* **Serializable** metadata are stored both as transaction records in the **WAL** and as a byte stream provided by the **database cache** or the application(netdata). A serialized metadata byte stream can be requested by the **WAL** on demand to create checkpoints.
* **Non-serializable** metadata are never checkpointed and are only stored as transaction records in the **WAL**.

The only **non-serializable** metadata are those describing the metrics as they are stored in **extents** in the **data files**. We categorize these metadata as of **page cache** type. In order for the **page cache** to rebuild its in-memory state from those metadata it needs to scan all available **WAL** files and replay all relevant transaction records.

We split the **serializable** metadata into 2 types, **metrics index** type and application type:
* **Metrics index** type metadata describe the creation or hiding of metrics. The **metrics index** rebuilds its state from those metadata.
* Application type metadata describe application specific transactions and the **netdata storage engine** does not interpret them. Some examples are netdata charts, contexts, families etc.

There are 2 ways to restore the **serializable** metadata state from the **WAL**:
* Scan all available WAL files and replay all relevant transaction records.
* Read the last WAL and restore the metadata in-memory state from the latest checkpoint. After that, replay all relevant transaction records that are newer than the checkpoint.

For metadata of application type you the application must register 2 hooks that the **WAL** calls. The first hook is called per transaction record replay operation and it has the transaction record payload as input. The second hook is called when there is a checkpoint restore operation and it has the serialized application metadata dump as input.

The 2 aforementioned ways to restore the **serializable** metadata state from the **WAL** will lead to the same result if no **WAL** files have been manually deleted. However, only the second way (using the latest checkpoint) will ensure that no metadata updates have been missed.

The caveat here is allowing hide operations. Hide operations is what allows the application and the **metrics index** to reduce their memory footprint by dismissing pieces of metadata that have been marked as hidden. That means the corresponding metrics are effectively deleted from a presentation point of view since their metadata are unavailable. However, they still reside in the **WAL** files if there is a need to retrieve them.

With application support, we can allow a special mode of replaying the **WAL** files, so that all hide operations are ignored. This mode cannot utilize checkpoints and will take longer to load the metadata, and also consume a lot of memory. However, there is information in memory to interpret any metric stored in the **data files** no matter how old.

### Space Management

The netdata database effectively never forgets, other than for space management reasons. This means that you cannot delete metrics or metadata from the database, even if the application (netdata) deletes them from memory. Data and metadata are normally automatically deleted when the disk quota limits are exceeded.

There is one way to effectively render metadata inaccessible to the application, and that is only for external metadata (not native to this database). When a checkpoint is created in the **WAL** the application serializes its external metadata. The **WAL** need only replay the metadata since that checkpoint, rendering the older metadata invisible to the application.

However, there is a caveat with this approach. That is, when there is a data query for old data the application may lack the information to interpret the old metrics due to the absence of application metadata, since they have been explicitly deleted by the application itself.

#### Tiering

We use the **WAL** and **data file** name itself to store its serial number which we call the **epoch**. The **epoch** has two parts. The most significant bits define the tier class and the least significant bits define a relative timestamp, in the way that a bigger serial number is considered a later time than a smaller one. For example, `netdata-db-1-11.wal` means **tier-1**, timestamp 11 and is of a later date than `netdata-db-1-10.wal`. Semantically, a higher class tier is considered to be older than a lower class tier (e.g. **tier-2** is older than **tier-1**), even though the higher class tier files were actually generated from the lower tier ones at a later wall clock time.

Each tier has a space quota that it must not exceed. Whenever a new **data file** is created that is expected to eventually exceed its tier’s quota, an asynchronous metrics aggregation process begins. That is, the oldest **data file** of **tier-N** is scanned and the consolidation function is applied on its metrics to generate new **working pages of data** and eventually new **extents**. Those new **extents** are added to the newest file in **tier-N+1** the same way as data collection adds them to **tier-1**. When this transformation ends the **tier-N** database files are deleted.

Whenever a **tier-N+1** extent is generated all the corresponding **tier-N** **completed pages of data** that were input to the consolidation function are removed from the **page cache** and replaced by the **tier-N** **completed pages of data**. While this is keeps the **page cache** consistent, there is a time windows for inconsistencies in the **data files** and the **WAL** files. This time window closes when the **tier-N** files are eventually deleted. In the event of a crash or an application shutdown those inconsistencies are resolved by doing a sanity check on timestamps when starting the database. **Tier-N+1** files are scanned before **tier-N** files, and any metric’s timestamp that is earlier than the latest timestamp is ignored.

The asynchronous transformation process is throttled so as not to consume many resources or interfere with the system’s performance. The **data file** scan  is __not__ guaranteed to be sequential due to the way metrics are stored in the **extents**. On the other hand, the metrics can exhibit spatial and temporal locality due to the **extents** organization which could help limit the performance degradation of rotating disk media. The only way to avoid random disk accesses completely is to have exactly one tier for data collection, the real time **tier-1**.

In normal conditions, this transformation is expected to be faster than data collection. However, when a critical condition is met, such as hitting the quota limit or an out of space error is returned by the file system, the throttling mechanisms are bypassed and the aggregation process becomes a high priority job for the database. That way, the old files are deleted as soon as possible.

### Metadata design

#### Page Cache

page of data index node (AVL tree or B-tree or radix tree, indexed by start time):
* Start time timestamp (64 bits)
* sampling rate (32 bits, in milliseconds - up to every 50 days)
* number of data points (16 bits)
* LRU pointer
* status flags
* **data file** **epoch** (32 bits, 2 bits for tier, 30 bits for timestamp)
* **extent** block address in file (16 bits, maximum **data file** size 256MiB)
* **extent** byte length (to minimize IO)
* private pointer (e.g. to RRDDIM)

#### Metrics Index

hash table key:
* metric UUID (128 bits)

hash table value:
* root tree node for **page cache** index

#### Data File

super-block metadata:
* **data file** magic number
* version string
* tier number (1 for real-time data collection)

**extent** header metadata:
* compression algorithm type (e.g. “lz4”)
* byte length of compressed payload (16 bits)
* //////////////////////////////
* number of **completed pages of data** (8 bits, up to 256 metrics per **extent**)
* Start time timestamp array (64 bits per timestamp)
* sampling rate array (32 bits per sampling rate, in milliseconds - up to every 50 days)
* number of data points array (16 bits per number of data points)
* //////////////////////////////
* number of metrics (8 bits, up to 256 metrics per **extent**)
* metric UUID array (128 bits per UUID)
* metric allocation bitmaps (1 bitmap per metric, 8 bits per bitmap, 1 bit per **page of data** in the **extent**)

extent trailer metadata:
* CRC32 checksum of the **extent** (32 bits)

#### Write-Ahead Log

super-block metadata:
* **WAL** magic number
* version string
* tier number (1 for real-time data collection)
* serialized byte stream of external (application, e.g. netdata) metadata dump generated from checkpointing

transaction record metadata:
* byte length of record
* transaction ID (32 bits)
* transaction flag
  * transaction type (**page cache**, **metrics index** or application)
  * hide operation (true, false)
* transaction payload
  * **page cache** type (**non-serializable**, **native**)
    * **extent** metadata dump
  * **metrics index** type (**serializable**, **native**)
    * UUID creation/hide operation
  * application type (**serializable**, **external**)
    * application operation dump
* CRC32 checksum of the record (32 bits)

#### Metadata Synopsis

Metadata per **page of data**:
* in **page cache**, **WAL** and **data file** (in the extent header)
  * Start time timestamp (64 bits)
  * sampling rate (32 bits)
  * number of data points (16 bits)
* in **page cache** and **WAL**
  * **extent** block address in file (16 bits)
* only in **page cache**
  * LRU pointer
  * tree node indexed by start time
  * status flags
  * **data file** **epoch** (32 bits, 2 bits for tier, 30 bits for timestamp)
  * private pointer
