### ISSUE TITLE
CockroachDB monitoring

### ISSUE THREAD

**Issue by hazcod** [netdata/netdata#4696]
##### Feature idea summary
CockroachDB is a cloud-native SQL database for building global, scalable cloud services that survive disasters. https://github.com/cockroachdb/cockroach
They already expose a lot of metrics via their web interface, so it should be easier to implement.

##### Expected behavior
Provide an agent that monitors cockroachdb metrics.
Datadog: https://docs.datadoghq.com/integrations/cockroachdb/#metrics
Prometheus endpoint: https://www.cockroachlabs.com/docs/stable/monitoring-and-alerting.html

**Comment by cakrit** [comment]
The lack of a plugin for cockroachdb is also mentioned in #4574 
@HazCod can you help out with additional info on what should be collected, how it should be presented and the types of alarms that should be added?

This will help the devs [understand what they have to do](
https://github.com/netdata/netdata/blob/master/CONTRIBUTING.md#help-the-developers-understand-what-they-have-to-do), so that netdata can provide [meaningful metrics](https://github.com/netdata/netdata/blob/master/CONTRIBUTING.md#meaningful-metrics)

**Comment by cakrit** [comment]
Hi again @HazCod,

To get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.

He/she will assist us with the following:
  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

Would you be willing/able to play this role?

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by HazCod** [comment]
@cakrit Hello!
I'm not using CockroachDB in production yet, I'm POCing it versus Postgresql that i'm running right now. Will let you know!

**Comment by ilyam8** [comment]
Since we are using `CockroachDB` ourselves it is time to start working on it.

`CockroachDB` has wonderful documentation!.

### Endpoints

According [Monitoring and Alerting](https://www.cockroachlabs.com/docs/stable/monitoring-and-alerting.html) section it has following endpoints:

- [prometheus](https://www.cockroachlabs.com/docs/stable/monitoring-and-alerting.html#prometheus-endpoint) - `/_status/vars`
- [health](https://www.cockroachlabs.com/docs/stable/monitoring-and-alerting.html#health-endpoints) - `/health`
- [raw status](https://www.cockroachlabs.com/docs/stable/monitoring-and-alerting.html#raw-status-endpoints)

There is `/monitoring` dir in the `cockroach` repo - [link](https://github.com/cockroachdb/cockroach/tree/master/monitoring)

It looks scrape `prometheus` endpoint is enough.

### Representation


It is very likely it exposes huge amount of metrics but we are lucky - there is `/grafana-dashboards` dir in the `/monitoring`.

[It contains](https://github.com/cockroachdb/cockroach/tree/master/monitoring/grafana-dashboards) following dashboards:

- replicas
- runtime
- sql
- storage

I assume this is pretty grouping (since it is written by developers).

### Alerts

There is even [`Alerts On`](https://www.cockroachlabs.com/docs/stable/monitoring-and-alerting.html#events-to-alert-on) section in the documentation.

We need to alert if:

- Node is down for 5+ minutes.
- Node is restarting more than 5 times in 10 minutes.
- Node has less than 15% of free space remaining.
- Node is not executing SQL despite having connections.
- CA certificate on a node will expire in less than a year.
- Node's certificate will expire in less than a year.


All needed data for these alarms can be found in `/_status/vars`.

### Lab

There is an instruction how to create 3-node cluster in docker

> https://www.cockroachlabs.com/docs/stable/start-a-local-cluster-in-docker-mac.html

___

So it looks like we have all info to write the collector.

@fracasula what do you think about alert? I guess we need more? If so please suggest.

**Comment by hazcod** [comment]
Thanks for the followup @ilyam!

**Comment by ilyam8** [comment]
cockroachdb is a complex thing and grouping is hard because of it and netdata dashboard limitations, both cockroachdb (built-ing) and grafana dashboards have same problem - they mix dimension with diferent units.

I did some initial grouping but it can be improved

https://github.com/netdata/go.d.plugin/tree/master/modules/cockroachdb#charts

**Comment by ilyam8** [comment]
will be available when https://github.com/netdata/netdata/pull/7882 is merged
