### ISSUE TITLE
RFC: service discovery at run-time and auto-detection

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#4731]
## Motivation

Netdata already supports service auto-detection, to find the sources available for collecting metrics. This works very nice for a quick start, but it has certain limitations:

1. Netdata has to be restarted to run auto-detection again

2. Netdata has to be restarted to add or remove sources at runtime

3. There is no way for letting netdata know it should insist in collecting certain sources (though, I think we have added `required: yes/no` to python.d.plugin only)

4. The default configuration files are not very flexible for adding or removing a single source in an automated way (i.e. via a provisioning system or via package management)

5. There is no central configuration of all these sources, across all plugins

Unlike centralized monitoring solutions, like prometheus, that require a networked service discovery method (e.g. Consul), netdata is simpler, since it is expected to run on each monitored host or container. However, there are cases that netdata needs to discover remote endpoints.

## Feature request

- [ ] Allow central configuration (e.g. in `netdata.conf`) of all plugins and their modules (enable / disable).

- [ ] Support monitoring `/etc/netdata` (via `inotify`) for configuration file changes during runtime and reload these changes without restarting netdata. This could be implemented by restarting all data collection plugins without restarting the whole daemon.

- [ ] Support a flexible configuration mechanism for loading individual data collection jobs from files in the filesystem, even during runtime.

- [ ] Support configuring individual data collection jobs via Consul.

- [ ] Support reloading / reconfiguring netdata via a signal.

---

I know this feature request is somewhat vague, but I think we have to discuss it and have a common understanding of the issues and possible solutions.

**Comment by daniel-baumann** [comment]
since #5090 got closed in favour of this issue, which looks like a larger work: please implement "conf.d/*.conf"-handling first so everyone can profit from it immediately (shoudn't be much work anyway), and then attack the 'larger' restructuring/unifying of the configs. without conf.d/*.conf handling, large-scale deployment via distributions is not really possible yet.

**Comment by Ferroin** [comment]
> Support monitoring /etc/netdata (via `inotify`) for configuration file changes during runtime and reload these changes without restarting netdata

Unless something we actively need to support (like Alpine or RHEL 7) doesn't have support for `fanotify`, we should be using that in preference to `inotify` on the Linux side, it's more efficient and has fewer odd edge cases to deal with.

> Support reloading / reconfiguring netdata via a signal.

SIGHUP please for this, then it will work out of box with most existing service managers without needing special configuration. That said, what I really think it should be is forcing a recheck of all config files and then re-opening all log files.

**Comment by ilyam8** [comment]
> UC7 - Intermediate step, support .d directories with one config file for each job in python and go.d plugins.

Why this is needed? I don't remember this being requested.
And `Central configuration` will responsible for that, we don't need this functionality in plugins.

**Comment by ilyam8** [comment]
One of `service discovery plugins` of `Central configuration` is the plugin which reads files - it should implement UC7.

**Comment by nielsk** [comment]
I think this belongs in this feature request, too: when a service starts for which netdata has a configured service after netdata has started, netdata won't collect its data until it is restarted. This can be annoying at boot time.
For example: netdata starts, dovecot starts and needs longer than netdata, thus the socket is not yet available for netdata. The netdata-plugin for dovecot fails and no data will be collected. It would be great if netdata could at least regularly check if failed plugins recovered. 
Btw.: I am using FreeBSD on some of my machines, thus there is no inotify available (and inotify wouldn't work if the configuration is correct but something like a socket comes up later because inotify monitors only file systems).

**Comment by ilyam8** [comment]
@nielsk 

> For example: netdata starts, dovecot starts and needs longer than netdata, thus the socket is not yet available for netdata.

https://github.com/netdata/netdata/blob/72e9f6c93a86d4224efbebb1b68417581e00a0f6/collectors/python.d.plugin/dovecot/dovecot.conf#L34-L38

**Comment by nielsk** [comment]
@ilyam8 thanks a lot. The same exists for redis.
Thus dismiss my comment and I go back to school and learn to read >_<

**Comment by cakrit** [comment]
We will continue on #6317 and #6295

**Comment by cakrit** [comment]
We are closing all other issues in favor of #6432
