### ISSUE TITLE
Netdata recompiling every night?

### ISSUE THREAD

**Issue by tbblake** [netdata/netdata#4785]
##### Bug report summary
When the netdata updater runs every morning around 6:30am from /etc/cron.daily/netdata-updater on my raspberry pis it seems to be reinstalling/recompiling it every night.  I've got Zabbix monitoring on the pis and the CPU load was spiking every morning, but I was never awake to research why.  This morning I happened to be up, saw netdata being recompiled when looking at the output of 'ps -aefl'.  I somehow doubt there's a new version every day....  

How can I begin to troubleshoot this?  Is there some verbose logging I can turn on?

I also have netdata running on two Centos 7 installs that is not experiencing the same behavior.

##### OS / Environment
Raspbian GNU/Linux 9 (stretch)
Raspberry Pi Zero W
Raspberry Pi 3B+
Raspberry Pi 2B

##### Component Name
Netdata

##### Steps To Reproduce
Just let the daily update script run from /etc/cron.daily

##### Expected behavior
Only update when necessary?

**Comment by paulfantom** [comment]
That's not a bug, it is an effect of how updater was designed. It should update netdata every day if there are new commits added to master branch. Since we are currently working hard on netdata, this results in adding commits almost every day and thus also triggering updates every day.

Does you CentOS boxes have netdata updates enabled? Seems like you either have auto-updates disabled for them or you run into a bug which we accidentally introduced couple of weeks ago before v1.11.0 release (more info in release notes: https://github.com/netdata/netdata/releases/tag/v1.11.0)

**Comment by Ferroin** [comment]
> Seems like you either have auto-updates disabled for them or you run into a bug which we accidentally introduced couple of weeks ago before v1.11.0 release 

Or, it's just not being noticed there because they have more processing power than the Raspberri Pi's, and thus the build finishes quickly.
