### ISSUE TITLE
Netdata is not generating any alarms

### ISSUE THREAD

**Issue by yuvapradeep** [netdata/netdata#4793]
In alarm section we have never received any alerts, is it default config or Do we have to enable any parameters.

![nedata_alarm](https://user-images.githubusercontent.com/8336280/49248999-23793e00-f441-11e8-9274-4f8bda8c3e51.PNG)

**Comment by cakrit** [comment]
Please click the "All" tab to see which alarms are enabled. 
If it does show alarms enabled, then the triggers haven't fired. You can also look click the "Log" tab, to see if any alarms were ever raised. If you want to receive alarms without being on the UI, you will need to [configure notifications](https://docs.netdata.cloud/health/notifications/)

**Comment by yuvapradeep** [comment]
![image](https://user-images.githubusercontent.com/8336280/49338087-82a6a080-f643-11e8-9909-076d43a22fd5.png)

Could you please suggest which parameter on .conf file has to be enabled.?

**Comment by cakrit** [comment]
Also what's your OS and how did you install Netdata?

**Comment by ktsaou** [comment]
We just fixed a bug with #4898 
Some filesystems do not report the file type of files (they return `DT_UNKNOWN` instead of `DT_REG` or `DT_LNK` - check `man readdir`).
Once that PR is merged, please check again.

**Comment by yuvapradeep** [comment]
@cakrit 

Below command doesn't work for my environment as there is no external internet connection to those servers.
**# bash <(curl -Ss https://my-netdata.io/kickstart.sh) all**

**netdata-v1.10.0-752-g07060aec-x86_64-20181002-042930-firehol.gz.run**   downloaded this file manually and installed on the server.

**Comment by cakrit** [comment]
Unfortunately you can't get the fix unless you get the latest version from GitHub. The binary you have is old and the fix was just committed last night. We have static binaries that are built nightly, but the update will be there tomorrow. Can you try that? The instructions are in the installation documentation. Otherwise, perhaps you can build on one server temporarily connected to the internet and then copy the binary to the others.

**Comment by cakrit** [comment]
Check out [the relevant installation method](https://docs.netdata.cloud/installer/#linux-64bit-pre-built-static-binary).

**Comment by yuvapradeep** [comment]
Hi @cakrit 
Please check netdata status, I see "cannot load user config" from stream.conf. Can we do anything on stream.conf file
![image](https://user-images.githubusercontent.com/8336280/49383369-9551d000-f73e-11e8-9f44-9c6f2482668d.png)

**Comment by cakrit** [comment]
All that this line on stream.conf says is that it didn't find a stream.conf edited by you (which is true, since you don't have anything in `/opt/netdata/etc/netdata/health.d`. That's not a problem, it goes and uses the default configuration file, from `/opt/netdata/usr/lib/netdata/conf.d/health.d`

I got a bit confused though, did you download a fresh binary with kickstart64.sh? If so, do you see any enabled alarms now?

**Comment by yuvapradeep** [comment]
Hi @cakrit ,

No, that was previous installation status.
![image](https://user-images.githubusercontent.com/8336280/49446464-46697080-f7fa-11e8-9ed2-64aac6d5d2e3.png)
Now binaries are installed and "Netdata Alarms > All" section displaying various sections.
And able to see logs also.

Thank you very much :+1:  :)

@ktsaou Thank you.

**Comment by cakrit** [comment]
Excellent, spread the word! :+1:
