### ISSUE TITLE
Jenkins monitoring

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#4876]
We are willing to support monitoring ***[Jenkins](https://jenkins.io/)*** with netdata.

To get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.
He/she will assist us with the following:

  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by cakrit** [comment]
We have a lot of interest in this one, but we still need someone to assist us by assuming the sponsor role. Can anyone help here?

**Comment by ilyam8** [comment]
Jenkins monitoring:

> https://wiki.jenkins.io/display/JENKINS/Monitoring


There is jenkins monitoring plugin (`java`) source code:

> https://github.com/jenkinsci/monitoring-plugin

JenkinsAPI python lib:

> https://pypi.org/project/jenkinsapi/

Some examples how it can be used:

> https://jenkinsapi.readthedocs.io/en/latest/using_jenkinsapi.html#using-jenkins-api

___

If someone can help with understanding how metrics can be gathered, what endpoints should be used, etc it would be awesome.

**Comment by ilyam8** [comment]
A lot of 👍 @n0guest do you guys use jenkins? Willing to help to implement this collector? 😃

**Comment by sannithkk** [comment]
Hi I would like to contribute for this project.

**Comment by OdysLam** [comment]
Thanks @sannithkk,

There are 2 avenues. We can either use the already implemented [Prometheus endpoint collector](https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/modules/prometheus) or use the [Prometheus package helper function](https://github.com/netdata/go.d.plugin/tree/master/pkg/prometheus) to easily code a new collector in Golang.

1) the First option is very easy since we only have to add 2 lines to the configuration file. The downside is that the collector limits us in terms of how we can organize the available data into meaningful charts. Moreover, it limits us in processing the raw metrics that we gather into something more meaningful (e.g turn kbs to mbs). 
2) the second option is far more exciting. We will use the helper function to create a brand new collector in Golang. If you have knowledge of the language, it should be fairly [easy](https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/docs/how-to-write-a-module) to "copy" the structure of an existing collector that uses the Prometheus endpoint. 

The real challenge here is to know what metrics matter and how to organize them into meaningful charts. Me and @ilyam8 will help you along the way, so have no fear!

**Comment by sannithkk** [comment]
That's sounds good,

Am interested in Option 2.
Am new to GO, but would like to contribute for sure.

**Comment by OdysLam** [comment]
Awesome!

When you are ready, create a topic in our forum and we will continue the discussion there with @ilyam8 . We will give you a good example collector to start working from and whatever question, you can post there. 

This forum topic will serve as a good guide for other people !

https://community.netdata.cloud/c/agent-development/9

**Comment by ilyam8** [comment]
I would [start from](https://github.com/netdata/netdata/issues/4876#issuecomment-593272919)

> If someone can help with understanding how metrics can be gathered, what endpoints should be used, etc it would be awesome.

#### We have answers (not 100% sure)

- how metrics can be gathered?
  - Jenkins has REST API (`http://my-jenkins-instance:8080`)
- what endpoints should be used?
  - jobs metrics: `/api/json`
  - nodes metrics: `/computer/api/json`

 
#### We have no answers

- do we need both jobs and nodes metrics?
- we need a sample for both jobs and nodes response to understand what metrics needs to be collected, how to group them, etc.
