### ISSUE TITLE
Mailchimp monitoring

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#4879]
We are willing to support monitoring ***[Mailchimp](https://mailchimp.com/)*** with netdata.

To get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.
He/she will assist us with the following:

  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by SlavikCA** [comment]
Not sure, if I'm clear on everything required for me to be sponsor.
I'm interested and would be willing to help / suggest / QA.

Here is my suggestions.

Useful metrics:
- Number of subscribers (total OR per list)
- Number of new subscriptions for the day (total OR per list)
- Number of unsubscriptions for the day (total OR per list)
- Number of undelivered emails. Usually that number is per campaign. But may be more useful to report per day? May be more specific, as undelivered because of wrong email / non-existing user / rejected by mail server / etc...

Alarms:
- high rate of unsubscriptions
- high rate of undelivered emails.

As far as I understand `netdata` - it usually runs on the targeted system itself nad reports from it.
So, in case of `mailchimp` - apparently we can't run `netdata` on `mailchimp` servers. So, architecture would be different?

**Comment by cakrit** [comment]
@ilyam8 it didn't take long to find https://mailchimp.com/developer/reference/reports/ from the `telegraf` code you shared. So let's plan this.

**Comment by ilyam8** [comment]
I would like to have at least one `Mailchimp` active user during working on it.

**Comment by ilyam8** [comment]
Closing this issue due to the low interest in this feature.

If there is anybody who is interested in having this implemented please visit our Community Forums and create a new topic in the [Netdata Agent Feature Requests](https://community.netdata.cloud/c/feature-requests/agent-fr/21) category.
