### ISSUE TITLE
space allocation in /var/cache/netdata is >2GB and growing - why is no cleanup after service restart?

### ISSUE THREAD

**Issue by 74cmonty** [netdata/netdata#4987]
##### Bug report summary
I observer large space allocation in directory /var/cache/netdata on multiple servers:
```
Server A: 1.6G    /var/cache/netdata/
Server B: 2.8G    /var/cache/netdata/
```
##### OS / Environment
SLES 12SP3 bare-metal (no virtualization)
##### Component Name
netdata 1.11.1
##### Steps To Reproduce
1. Start netdata service
2. Observe space allocation in /var/cache/netdata
##### Expected behavior
Storage allocation should not exceed 1GB unless this depends on monitored hardware.

**Comment by csamsel** [comment]
> Storage allocation should not exceed 1GB unless this depends on available hardware.

1 GB is just an artificial value. Why not make it 10 GB?

The space used is dependent on the configuration. If you want less used space, lower the reporting interval.

**Comment by 74cmonty** [comment]
1GB is a value that is taken based on the avg. space allocation of directory `/var/cache/netdata` deployed on +200 servers with different HW equipment.
If you could explain what drives the space allocation of `/var/cache/netdata` I can adjust my monitoring accordingly.

**Comment by Ferroin** [comment]
You can get a reasonable guess of how much space Netdata 'should' be using by looking at the dashboard.  At the very bottom of the menu on the right, there's some text that will tell you how many metrics, charts, and alarms are being tracked, as well as how much memory that takes (and how long the history is).  If the memory usage reported there matches up with the space usage in `/var/cache/netdata` to within about 1% or so, this is a configuration issue.  If the usage in `/var/cache/netdata` is significantly higher than that value, you've found a bug in Netdata itself.

----

As far as what actually contributes to space usage there, overall usage should be directly proportionate to the number of metrics collected (roughly linearly), the history size (roughly exponentially), and the collection interval (also roughly exponentially).

So, options to reduce this include:

* Disable collection of some metrics on that system.
* Reduce the number of data points of history you're keeping.
* Increase the collection interval.

You could also set `memory mode = ram` in the `[global]` section of your Netdata configuration, which will almost completely eliminate any usage of `/var/cache/netdata` (but will also make Netdata lose state when it restarts).

**Comment by cakrit** [comment]
Nice post @Ferroin.
@74cmonty you can find a lot more info [here](https://docs.netdata.cloud/database/) and [here](https://docs.netdata.cloud/docs/performance/).

**Comment by cakrit** [comment]
In one of the servers, can you do the `du` inside `/var/cache/netdata`?
Also, can you please put here your [global] config?

**Comment by cakrit** [comment]
I wanted to see if a particular directory is using most of the disk space, or if it's spread out relatively evenly. Since your config shows you're running with default settings, it doesn't make sense to have 2.5G of storage in the cache and we need to find what's causing it. You will have a lot of subdirectories under /var/cache/netdata, so just sort them by size and send the top 10 or so.

**Comment by 74cmonty** [comment]
```
ld2870:/var/cache/netdata # du -m --max-depth 1 | sort -rn | head -21
2533    .
37      ./cpu.cpu479_interrupts
37      ./cpu.cpu478_interrupts
37      ./cpu.cpu477_interrupts
37      ./cpu.cpu476_interrupts
37      ./cpu.cpu475_interrupts
37      ./cpu.cpu474_interrupts
37      ./cpu.cpu473_interrupts
37      ./cpu.cpu472_interrupts
37      ./cpu.cpu471_interrupts
37      ./cpu.cpu470_interrupts
37      ./cpu.cpu469_interrupts
37      ./cpu.cpu468_interrupts
37      ./cpu.cpu467_interrupts
37      ./cpu.cpu466_interrupts
37      ./cpu.cpu465_interrupts
37      ./cpu.cpu464_interrupts
37      ./cpu.cpu463_interrupts
37      ./cpu.cpu462_interrupts
37      ./cpu.cpu461_interrupts
37      ./cpu.cpu460_interrupts
```

**Comment by Ferroin** [comment]
Does the system in question _actually_ have almost 500 logical CPU's?  If not, I think we may have found part of the issue (each CPU translates to at least 4-5 chart, some of which can easily have dozens of dimensions, so if Netdata erroneously thinks you have 500+ CPU's, that's 2000-2500 such charts).

**Comment by cakrit** [comment]
But we know that ld2870 collects a lot of metrics:
> collects every second 65,709 metrics, presented as 4,298 charts and monitored by 898 alarms, using 1,047 MB of memory for 1 hour, 6 mins and 36 secs of real-time history.

The question is how 1GB turns into 2.5GB. Worse, how on ld2872 we get from 336 MB to 2.8 G.

**Comment by Ferroin** [comment]
@cakrit Good point.

I could have sworn there was a bug like this recently (past few months) where Netdata wasn't properly cleaning up `/var/cache/netdata` and as a result it was growing to ridiculous sizes, but I can't seem to find the issue for that bug (and I'm fairly certain it got fixed in 1.11).

**Comment by cakrit** [comment]
Indeed netdata doesn't clean the old files, but the ids shouldn't be changing all the time. I found a very similar discrepancy on my laptop. On my cpu1.cpu_interrupts I have the following:
```
-rw-rw----   1 netdata netdata 16384 Dec 14 19:43 12.db
-rw-rw----   1 netdata netdata 16384 Dec 14 19:43 131.db
-rw-rw----   1 netdata netdata 16384 Dec 14 19:43 CAL.db
-rw-rw----   1 netdata netdata 16384 Dec 14 19:43 IWI.db
-rw-rw----   1 netdata netdata 16384 Dec 14 19:43 LOC.db
-rw-rw----   1 netdata netdata  4960 Dec 14 19:43 main.db
-rw-rw----   1 netdata netdata 16384 Dec 14 19:43 MCP.db
-rw-rw----   1 netdata netdata 16384 Dec 14 19:43 RES.db
-rw-rw----   1 netdata netdata 16384 Dec 14 19:43 TLB.db
```
But my chart only shows 4-5 of the dimensions. Even after a restart, all the files are refreshed with new dates, I just don't see the dimensions on the charts. This explains the discrepancy between the calculated metrics and what is actually stored. In @74cmonty's case, I think it's exaggerated due to the very high number of CPUs. Need to dig deeper into how this could be happening, but the reality @74cmonty is that perhaps you really do need this space. You won't need it only if we find that the additional ids you see are not really there and the chart that's shown is the one with the correct data.

**Comment by cakrit** [comment]
> Netdata doesn't display 'empty' (constantly 0) dimensions, especially in the IRQ related charts, which is why you're seeing what you're seeing.

I think you nailed it @Ferroin. These extra identifiers that are not shown correspond to counters that are definitely incremental and don't change. Since netdata understands that some of them are constantly 0, it doesn't show them in the charts (and I'm pretty sure it saves memory this way). But it has already taken the disk space for them, because when it started it didn't know anything about which metric would end up increasing. ergo the difference between the disk space used and what's calculated on the UI. My `/proc/interrupts` shows the id I see in the cache for the particular CPU, but it never changes. So my netdata UI doesn't show it.

Perhaps we could see if we can optimize this behavior with the new DB. But for this issue, I think that the only way to save space would be to reduce the polling period, or store less than one hour of history.

**Comment by 74cmonty** [comment]
FYI
I'm using netdata on servers with hundreds of CPUs and TB RAM.
```
ld2870:~ # cat /proc/cpuinfo | grep 'core id' | wc -l
480

ld2870:~ # free -h
             total       used       free     shared    buffers     cached
Mem:           11T       5.9T       5.9T       107G       130M       146G
-/+ buffers/cache:       5.7T       6.1T
Swap:         256G       890M       255G
```

Don't get me wrong: I don't complain about the space usage in `/var/cache/netdata`, but I need to understand how this space allocation correlates to the hardware monitored. Then I can reserve the required disk space and adjust the monitoring/alerting accordingly.

**Comment by 74cmonty** [comment]
Hi,
I decided to clean cache.
Therefore I stopped netdata, cleaned any *.db file in `/var/cache/netdata` and restarted netdata on both servers ld2870 & ld2872:
```
ld2870:~ # systemctl stop netdata
ld2870:~ # ls /var/cache/netdata/ | wc -l
4315
ld2870:~ # find /var/cache/netdata/ -type f -name "*.db" | wc -l
1139063
ld2870:~ # netdata -v
netdata 1.11.1_rolling
ld2870:~ # rm -rf /var/cache/netdata/*
ld2870:~ # systemctl start netdata
ld2870:~ # systemctl status netdata
● netdata.service - Real time performance monitoring
   Loaded: loaded (/usr/lib/systemd/system/netdata.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2018-12-17 10:24:45 CET; 10s ago
  Process: 225711 ExecStartPre=/bin/chown -R netdata:netdata /var/run/netdata (code=exited, status=0/SUCCESS)
  Process: 225705 ExecStartPre=/bin/mkdir -p /var/run/netdata (code=exited, status=0/SUCCESS)
  Process: 225699 ExecStartPre=/bin/chown -R netdata:netdata /var/cache/netdata (code=exited, status=0/SUCCESS)
  Process: 225693 ExecStartPre=/bin/mkdir -p /var/cache/netdata (code=exited, status=0/SUCCESS)
 Main PID: 225717 (netdata)
    Tasks: 22 (limit: 512)
   CGroup: /system.slice/netdata.service
           ├─225717 /usr/sbin/netdata -P /var/run/netdata/netdata.pid -D -W set global process scheduling policy keep -W set global OOM ...
           ├─225732 bash /usr/lib/netdata/plugins.d/tc-qos-helper.sh 1
           ├─225744 /usr/lib/netdata/plugins.d/apps.plugin 1
           └─225751 /usr/bin/python /usr/lib/netdata/plugins.d/python.d.plugin 1

Dec 17 10:24:45 ld2870 systemd[1]: Starting Real time performance monitoring...
Dec 17 10:24:45 ld2870 systemd[1]: Started Real time performance monitoring.
ld2870:~ # ls /var/cache/netdata/ | wc -l
4224
ld2870:~ # find /var/cache/netdata/ -type f -name "*.db" | wc -l
70931
ld2870:~ # du -hs /var/cache/netdata/
17M     /var/cache/netdata/
```
```
ld2872:~ # ls /var/cache/netdata/ | wc -l
2875
ld2872:~ # find /var/cache/netdata/ -type f -name "*.db" | wc -l
1131336
ld2872:~ # netdata -v
netdata 1.12.0-rc0-46-gbe261beb
ld2872:~ # rm -rf /var/cache/netdata/*
ld2872:~ # systemctl start netdata
ld2872:~ # systemctl status netdata
● netdata.service - Real time performance monitoring
   Loaded: loaded (/usr/lib/systemd/system/netdata.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2018-12-17 10:24:46 CET; 15s ago
  Process: 15925 ExecStartPre=/bin/chown -R netdata:netdata /var/run/netdata (code=exited, status=0/SUCCESS)
  Process: 15919 ExecStartPre=/bin/mkdir -p /var/run/netdata (code=exited, status=0/SUCCESS)
  Process: 15913 ExecStartPre=/bin/chown -R netdata:netdata /var/cache/netdata (code=exited, status=0/SUCCESS)
  Process: 15907 ExecStartPre=/bin/mkdir -p /var/cache/netdata (code=exited, status=0/SUCCESS)
 Main PID: 15931 (netdata)
    Tasks: 24 (limit: 512)
   CGroup: /system.slice/netdata.service
           ├─15931 /usr/sbin/netdata -P /var/run/netdata/netdata.pid -D -W set global process scheduling policy keep -W set global OOM s...
           ├─15943 bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
           ├─15976 /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
           └─15979 /usr/libexec/netdata/plugins.d/apps.plugin 1

Dec 17 10:24:46 ld2872 systemd[1]: Starting Real time performance monitoring...
Dec 17 10:24:46 ld2872 systemd[1]: Started Real time performance monitoring.
ld2872:~ # ls /var/cache/netdata/ | wc -l
2772
ld2872:~ # find /var/cache/netdata/ -type f -name "*.db" | wc -l
23784
ld2872:~ # du -hs /var/cache/netdata/
11M     /var/cache/netdata/
```

I'll report the updated space allocation after 1 hour.

**Comment by 74cmonty** [comment]
Update after +1hrs netdata runtime:
```
ld2870:~ # date
Mon Dec 17 12:55:01 CET 2018
You have mail in /var/spool/mail/root
ld2870:~ # du -hs /var/cache/netdata/
17M     /var/cache/netdata/
```
```
ld2872:~ # date
Mon Dec 17 12:55:07 CET 2018
ld2872:~ # du -hs /var/cache/netdata/
11M     /var/cache/netdata/
```

In my opinion the bug is now not related to the allocated space in /var/cache/netdata but to the missing cleanup process after service restart.

**Comment by Ferroin** [comment]
@74cmonty I don't think we ever heard what memory mode you're using on these systems.  If it's anything _except_ `memory mode = map` though, you won't see anything in the cache until you restart Netdata, because it doesn't save anything there except on shutdown in any other mode.  There's no cleanup because the whole point of the cache is persisting state across restarts of Netdata (so you can do things like upgrading it without losing history).

As far as how much space is used, could we see a comparison of `/proc/interrupts` from ld2870 and ld3852?  I suspect that they have drastically different interrupt utilization, and that that's probably what's causing the difference in space utilization.  If you run the irqbalance daemon on either of them, the configuration for that might be useful too (if it's not running in one-shot mode, it may be making things worse by changing interrupt routing regularly).

**Comment by cakrit** [comment]
He is right about this though:
> the bug is now not related to the allocated space in /var/cache/netdata but to the missing cleanup process after service restart.

This will be resolved with the new database format (#4687).

**Comment by Ferroin** [comment]
@cakrit Indeed, though I would love to figure out definitively why there was so much variance between systems with otherwise identical hardware.

**Comment by 74cmonty** [comment]
I'm running the default memory mode, means `memory mode = save`.
Basically I'm running netdata with default settings mainly; the only exceptions are for registration server.

So, let's continue with the requested info of `/proc/interrupts`; as you didn't specify what information you need I can provide you this:
```
ld2870:~ # cat /proc/interrupts  | wc -l
2321
```
```
ld2872:~ # cat /proc/interrupts  | wc -l
2317
```

With regards to irqbalance, the related service is only running on ld2870:
```
ld2870:~ # systemctl status irqbalance
● irqbalance.service - irqbalance daemon
   Loaded: loaded (/usr/lib/systemd/system/irqbalance.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-11-14 08:31:46 CET; 1 months 2 days ago
 Main PID: 16812 (irqbalance)
    Tasks: 1 (limit: 512)
   CGroup: /system.slice/irqbalance.service
           └─16812 /usr/sbin/irqbalance --foreground

Nov 14 08:31:46 ld2870 systemd[1]: Started irqbalance daemon.
```
```
ld2872:~ # systemctl status irqbalance
● irqbalance.service - irqbalance daemon
   Loaded: loaded (/usr/lib/systemd/system/irqbalance.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
```

Based on the active configuration of irqbalance on ld2870 I consider this to be irrelevant:
```
ld2870:~ # more /etc/sysconfig/irqbalance
## Path:        System/Kernel/IRQ Balancing
## Description: IRQ Balancing configuration
## Type:        string
## Default:     ""
## ServiceRestart:      irqbalance
#
# Bitmap of CPUs that are banned from IRQ balancing
#
IRQBALANCE_BANNED_CPUS=""

## Type:        string
## Default:     ""
## ServiceRestart:     irqbalance
#
# Pass specific irqbalance(1) options when the service is started via
# systemctl. For example --debug will show additional output via
# systemctl status irqbalance
#
IRQBALANCE_ARGS=""
```

**Comment by ninjakitteh69** [comment]
Hi. I'm having the same issue where Our memory is running up to 2GB+. in netdata it shows:
netdata on server01, collects every second 1 648 metrics, presented as 314 charts and monitored by 95 alarms, using 27 MB of memory for 1 hour, 6 mins and 36 secs of real-time history.

I have noticed that everytime there is a jump in memory, there is a spike of pagefaults for netdata that occurs at the same time. Not sure if this will help to identify the issue.

image attached.
![netdata](https://user-images.githubusercontent.com/21240594/53724486-a5c73300-3e72-11e9-875f-e6f810372676.png)

**Comment by ktsaou** [comment]
@ninjakitteh69 	minor page faults are not that important. It means that netdata accesses memory that it has not been accessed in the past. With Linux (4KB page size), this happens every 20 minutes because data collection starts writing to a new page.

For the servers that are using a lot of disk space, could someone please provide the output of the following command, via pastebin:

```sh
tree -sugpDQ /var/cache/netdata/
```

btw, the new database format we are building will solve this. The database will always have a fixed size on disk and we will use compression to improve its footprint significantly. But still, we need to find how the database gets that bigger. Most probably there are chart dimensions that change names all the time, thus resulting in an always increasing number of files on disk.

**Comment by 74cmonty** [comment]
I can share the content of _/var/cache/netdata_ allocating ~2GB disk space.

[netdata_cache.zip](https://github.com/netdata/netdata/files/2956051/netdata_cache.zip)

**Comment by cakrit** [comment]
With `grep -E '"[0-9]+.db' netdata_cache | wc`, I see over 100k db files for the cpu interrupts, with 16k allocated to each one.

**Comment by 74cmonty** [comment]
There must be a syntax error:
`ld3195:/var/cache/netdata # tree -sugpDQ /var/cache/netdata/ | grep -E '"[0-9]+.db' netdata | wc
grep: netdata: No such file or directory
      0       0       0
`

**Comment by vlvkobal** [comment]
I glanced over the `netdata_cache` file. There are 240 processors and 540 interrupts for every processor. 240 * 540 * 16384 = 2025 GiB.

**Comment by 74cmonty** [comment]
Well, this is a big server.
If you tell me the allocated disk space is normal for servers with many processors I'm fine with this. Then I can reserve sufficient disk space.

**Comment by Ferroin** [comment]
@74cmonty For the time being, it probably is the case that this amount of disk usage is normal for big servers.

**Comment by cakrit** [comment]
I spoke with @ktsaou and he noticed that most of the .db files were created on 3 Dec, so it was probably a bug. The suggestion is to remove the files under the cpu interrupt directories and the expectation is that we won't see so many created again.

**Comment by Ferroin** [comment]
> the expectation is that we won't see so many created again.

We only create dimensions for combinations of CPU and IRQ number that have a non-zero total value in `/proc/interrupts`, correct?

If that's the case, I could see this being 'normal' behavior for systems that dynamically rebalance interrupts, which unfortunately is pretty common on really big servers (the more CPU's you have the more it matters to have interrupts balanced properly).
