### ISSUE TITLE
Error every second PLUGIN[proc]

### ISSUE THREAD

**Issue by XTREMRUST** [netdata/netdata#4994]
Hi,

Do you have an idea to fix this error?
I have searched but I can not find.
Thanks for your help.

[Graph](https://i.imgur.com/62Rr6ih.png)

[Error](https://i.imgur.com/H4eerVZ.png)

Please help

**Comment by XTREMRUST** [comment]
Someone would have an idea of what I need to correct ?

**Comment by cakrit** [comment]
To stop the errors, you can disable the /proc/stat plugin by putting the following in `netdata.conf` and restarting netdata.

```
[plugin:proc]
	/proc/stat = no
```

However, the question is why you don't have the file `/proc/schedstat` on your system. I digged a bit and found [this](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=cb2517653fccaf9f9b4ae968c7ee005c1bbacd). Apparently schedstat may be disabled by default on some systems. 

Question: Wasn't the plugin disabled automatically by netdata?
@vlkobal, perhaps we can do something more graceful here instead of always retrying?

**Comment by XTREMRUST** [comment]
Thank you for your reply !
Can you give me the way to reactivate the schedstat please ?

**Comment by Ferroin** [comment]
> I expect you'll have a disabled service called schedstats or something like that, that will be disabled. I couldn't find the exact name.

Nothing in `/proc` is provided by systemd.  WRT to the `/proc/schedstat` error message, it means that the kernel just doesn't support that interface, which is not unusual on tightly secured systems, as it is supposed to primarily be a debug interface.  I'm not 100% certain what Netdata is using the info there for though.

---------------------------------------------

As far as the UDP send buffer alarm, UDP send buffer errors are almost always buffer overruns (that is, something is trying to send UDP packets faster than the system can transmit them).  If they're infrequent and you serve things like NTP or DNS that use UDP as the primary transport from this system, then you can probably safely ignore them because they're most likely just responses to large numbers of queries.  If they're frequent, your system is struggling to keep up with the network load, and you should look into either reducing the networking load, or upgrading the system (CPU, RAM, and NIC's are the primary things to look at here).

**Comment by XTREMRUST** [comment]
Hello,
Thank you for your reply!
Unfortunately I can not find a solution to my problem.
I uninstalled and reinstalled NETDATA but I still have the error  :(

**Comment by cakrit** [comment]
> I uninstalled and reinstalled NETDATA but I still have the error 

Which "error"? We have explained why schedstat may not be available on your system and how to disable the specific plugin. We have also explained that alarms are not "errors". Netdata can't fix the the system itself, it just reports the problems it finds. Please go through the previous responses and follow up with specific questions on them, so we can assist you further.

**Comment by XTREMRUST** [comment]
Hello,
OK, thanks.

So I disabled the PROC plugin, but it disables all netdata scans that's a shame.
NETDATA informs me that my system always has the same error on '/ proc / schedstat'.

I made the command "systemctl list-unit-files | grep schedstat" but it gives nothing. I ran it root, root and Netdata folder. Nothing.

Could you help me understand how to repair my system please?

**Comment by vlvkobal** [comment]
Fixed in #5059. @XTREMRUST Please update your netdata and check if the problem has gone.

**Comment by XTREMRUST** [comment]
> Fixed in #5059. @XTREMRUST Please update your netdata and check if the problem has gone.

Thank you for your help !
The plugin's error has disappeared.
I have a new fault: [New error](https://i.imgur.com/WkRFwX3.png)

And I always have an error every minute on IPv4 but I do not know where it comes from.
[IPv4 error](https://i.imgur.com/KCiCDnI.png)

**Comment by vlvkobal** [comment]
A similar INFO string
`2018-12-27 21:21:02: netdata INFO  : WEB_SERVER[static4] : POLLFD: LISTENER: client slot 1 (fd 113) from 'fcXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:41282' is idle for more than 60 seconds - closing it.`
is in #5067 so it looks like there is a problem regardless of the address type.

**Comment by cakrit** [comment]
> I made the command "systemctl list-unit-files | grep schedstat" but it gives nothing. I ran it root, root and Netdata folder. Nothing.

Based on this, I don't think you'll be able to get these statistics @XTREMRUST. 
As @Ferroin said,

> t means that the kernel just doesn't support that interface, which is not unusual on tightly secured systems, as it is supposed to primarily be a debug interface

Since the bug was closed, please create a new issue with the question on the IPv4 error or anything else you need help with.
