### ISSUE TITLE
Continuous Build Pipeline should allow us to do QA in a container

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#5007]
##### Feature idea summary
The CD process showcased in [this video](https://www.youtube.com/watch?v=07jq-5VbBVQ), starting at 10:56 and especially from 12:36 onwards will allow us to easily test changes from PRs, saving a lot of time and paving the road for more automations in the future. 

##### Expected behavior
We don't need everything described in that video immediately and perhaps we can do it without Kubernetes as well. The minimum to increase productivity is to be able to have URLs where we can preview the deployed netdata, exactly as netlify does it.

**Comment by paulfantom** [comment]
Since we are not dependent on any third-party library (and is we are it also lives here) build reproducibility can be easily achieved by running a specific commit in a controlled environment. This is already implemented by putting build process inside containers (that's the whole reason behind https://github.com/netdata/helper-images repository), what is left is to have a simpleway on how to use those images. This way is futher described in https://github.com/netdata/netdata/pull/5015.

I don't see any large benefits from running a user-facing PR preview (like netlify) as main netdata scope is not it's UI interface and allowing SSH access to such instances is like publicly asking people to log in to our servers to mine bitcoins.

Personally I see much more benefit in increasing test coverage than implementing this.
