### ISSUE TITLE
Run netdata-update cronjob

### ISSUE THREAD

**Issue by breezytm** [netdata/netdata#5022]
Can I run the netdata-updater in crontab?
0 3 * * * /opt/netdata/netdata-updater.sh 

I notice when I run the script manually, i asked me to press enter to continue hence why i am asking.

**Comment by paulfantom** [comment]
Since today updater is installed into `/etc/cron.daily/netdata-updater` or into `/etc/periodic/daily/netdata-updater` when using our installation script with an `--auto-update` flag. 

Previous scripts have some logic in them which were detecting if they can be run in interactive way or not, so they could be used in cron (that was their whole purpose).
