### ISSUE TITLE
Show current scaling governor in cpufreq graph

### ISSUE THREAD

**Issue by NikTheDusky** [netdata/netdata#503]
Yeah, it would be nice if the #cpu_cpufreq graph would show the current CPU scaling governor, just as an infotext above or under the actual frequency graph.
E.g. could be read out from `/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`
What could be thinked about too is that the scaling mode can differ from cpu core to core, so `cpu/cpu0` could be `conservative` and `cpu/cpu1` could be on `powersave`., so that the text that is showed could differ (like "The scaling is set to 'powersave'" and, if it differs; "On 'cpu0' the scaling is set to conservative and on 'cpu1' it is set to 'ondemand'")

This is just an idea and has no priority, but it would be nice-to-have.

Greetings, Nik

**Comment by ktsaou** [comment]
nice! There already a few issues that request information about the system be exposed on the dashboard. I'll keep this open so we will implement it when we build this functionality.

**Comment by thinrope** [comment]
And what happens when you change the governor, while netdata is running?
Probably the only hackish way to implement that (given RRDs cannot store string values) is to encode the current governor in a number and create additional graph. This will be system dependent and may break with time (e.g. change of kernel config, fewer governors available), so prone to errors.
If we ever implement #1114, then this might be solved as well.

**Comment by ktsaou** [comment]
@simonnagl did much of the work at https://github.com/firehol/netdata/pull/430, but it now needs to be updated.

**Comment by ktsaou** [comment]
I am closing this in favor of #531 (just to have one issue for all these cases).
