### ISSUE TITLE
feasible idlejitter collector alarm

### ISSUE THREAD

**Issue by socomsystems** [netdata/netdata#5041]
Regarding the idlejitter collector what would be a feasible alarm metric for its data?  The Readme states how to measures jitter but not what is metrics are acceptable, warning, critical with regard to VoIP etc...

I can't seem to locate any alarms or example alarms for this metric.

**Comment by socomsystems** [comment]
@Ferroin thanks for the quick feedback.  Looking further into this metric I'm not so sure its fair to say its useful for VoIP health due to the number of variables at play.  As you've stated in detail, its super subjective.  QoS buffers, loss, latency, jitter, codec negotiated, signaling protocols end-point to end-point...  ITU G.114 standard states 150-ms one-way delay budget is acceptable for high voice quality one-way communications, however (Internet Traversal) aka in the wild quality mean opinion scores (MOS) with 200-ms delay budgets seem to be acceptable to some carriers.  Using the fping plugin and tracking simply ms times between PBX <-> client edge router endpoints though rudimentary, may be more suitable to start with.  

[MOS calculations](https://en.wikipedia.org/wiki/Mean_opinion_score), also subjective but at least heuristic are standard in most PBX platforms these days, however, they calculate based on each call made.  Where I'm going with this is to have netdata be able to monitor the channel health between two endpoints from an MOS perspective (with and without active calls) 24/7.  

Thanks for the nudge!

**Comment by Ferroin** [comment]
I wouldn't say it's _completely_ useless for VoIP setups, just that it's really not the first thing I would be looking at.  The problem is that what you really need to know is the idlejitter for the VoIP process itself, not the Netdata process, and there's not really any way to properly measure that short of coding the VoIP software to do it itself and report it somehow.  If, however, you have ruled out everything but the local system as a source of latency issues, and you see high idlejitter, that may help figure out what to look for (namely, that it's probably the system and not the network).

Personally though, I'd be looking primarily at end-to-end network latency as a first metric for this type of thing, and then ideally monitoring individual links for latency too.  The end-to-end latency will give you a good estimate of whether QoS targets are being met, and the per-link monitoring will help track down issues when they do happen.
