### ISSUE TITLE
Use BabelJS to transpile dashboard.js and main.js to ES3

### ISSUE THREAD

**Issue by gmosx** [netdata/netdata#5042]
Some of our users run the Netdata Web GUI in older browsers (e.g. #4710). These browsers do not support modern (ES6+) JavaScript Features (e.g. for-of, const, etc.) A good solution would be to leverage a transpiler like [BabelJS](https://babeljs.io) to compile `dashboard.js` and `main.js` into ES3 (or ES5, as BabelJS seems to support only ES5). 

An alternative would be to use TypeScript's compiler for this transpilation.

**Comment by HostChefs** [comment]
I am experiencing the same issue. Can we use an older js file so as it will be working until this is fixed?
If yes, which version will it be compatible?

**Comment by rpirsc13** [comment]
Any update on this issue ? It would be nice if @gmosx @gpapamathND  can answer previous comment of @HostChefs . Which is the last commit where netdata worked for old browsers so we can revert to that until a final fix is pushed.

**Comment by ilyam8** [comment]
@jacekkolasa please take a look

**Comment by rpirsc13** [comment]
@jacekkolasa Thank you for the update. I will revert to that asap.

The browser that I am using is the integrated webos browser from LG TV ( issue #4710 ). Same result is for IE9-10-11. I don't plan on using IE for netdata but unfortunately I cannot use the browser of my choise on TVs.

**Comment by jacekkolasa** [comment]
@rpirsc13 i think your firmware version can be old, is it easy for you to update to newer firmware version? From my research it seems that you have `webOS TV 2.x` or `webOS TV 3.x` version, but `webOS TV 4.x` should have necessary support for all used ES6 features.

It's not optimal to add babel transpilation before we finish FE refractor, but we'll finish that soon. I'l close the issue now because https://github.com/netdata/netdata/issues/6515 will probably fix it, but please comment/answer here. Thanks for your input! We'll give more attention to have proper fallbacks to older browsers.
