### ISSUE TITLE
Autoload all servers in registry in mynetdata menu item

### ISSUE THREAD

**Issue by emagaliff** [netdata/netdata#505]
As it stands now, servers only appear in the mynetdata menu if you have visited them from your machine / browser. There should be a way to auto-populate the many to display all servers in the registry, allowing people to go to a singe page and view all servers without having to visit each one individually.

**Comment by ktsaou** [comment]
So you want everyone accessing your registry to get by default all the servers your registry knows.

Ok. I am leaving this as enhancement related to #416

**Comment by emagaliff** [comment]
@ktsaou After more thought, a "landing page" would be nice, similar to NewRelic's server page like [this](https://docs.newrelic.com/sites/default/files/thumbnails/image/servers-list_1.png), where you have a list of servers with basic stats and then you can select one and it loads that server. Of course, the mynetadata menu item would be present at the top to change servers.

**Comment by ktsaou** [comment]
even better. ok.

**Comment by Deshke** [comment]
Aloha, any progress on this?

**Comment by ktsaou** [comment]
sorry... not yet... I'll try to check how hard that can be...

**Comment by ktsaou** [comment]
ok, I did some research..

We need to decide how exactly this will work.

Alternatives:

1. all machines are given to all users the first time they register with the registry. So, additional machines will not be assigned to them automatically.

   I don't like it.

2. all machines are re-assigned to each user when this user accesses any machine. So, users will not be able to delete a machine from their list. Even if they do, the machine will keep re-appearing.

   From an implementation standpoint, this seems relatively easy. However, with the current implementation, there will be no way to remove a host. Even if all users delete a host, it will still be there, reappearing on all users by itself.

   I already need to add self-cleaning code to the registry. The global registry is going too big (133.000 persons, 43.000 machines, 33.000 urls, 260.000 links between persons and machines), so I need to fix that. But it requires at least a week of work (to add unit tests and make sure everything works properly).

   Once this work completes, if all users delete a machine, the machine will go away.

   If we go this way, and until we add the self-cleaning functionality, the only way to filter out a host, will be to remove (`grep -v`) the removed machine from the registry db files.

3. each user is having his/her own list of machines (as is today), but we add some functionality to let them know there are more machines available and select them.

   This is probably the most user-friendly option for this functionality. Each user will still maintain his/her own list of machines and there will be a way to get all the other machines known by the registry.

   Though, this would require some UI and another API method to get all the available machines. This is probably a day or two of work.

4. I am already in the process of researching authentication methods for netdata. The whole idea is to use some kind of OAUTH2, so that the registry can be the central point for accounts management. All other netdata will just trust the registry for authentication.

   From my point of view, this is one of the most important functions for netdata today. It will change netdata significantly, allowing read-write access on the dashboard (i.e. silence alarms, setup new alarms on-demand, create custom cross-server dashboards from the browser, etc).

   This will change a lot of the registry, almost all API calls and the UI.

So, I suggest to wait a bit more. I hope you will agree...

**Comment by emagaliff** [comment]
My thought process for how it would work is this:

1. Install netdata on all servers you want
2. Set custom registry (registry.company.com)
3. In the config, have an option for `autoload = true`
4. Go to netdata page for one of the machines
    a. Any other machines in the registry with `autoload = true` added to menu to easy access
    b. If not set to autoload, ignore
5. The autoloaded servers are *not* stored locally in the browser cache / cookies.

The above would essentially allow for an isolate netdata registry that provides access *only* to that specific set of servers to everyone who needs it. Having the list populate each time allows for an always up to date list and helps prevent "cross contamination" with servers not in the registry showing up in your list.

**Comment by jchrisweaver** [comment]
Checking status of accessing the registry entries.  I'm running an auto-scaling group, each will forward data to master netdata instance, and want to monitor it as it grows and shrinks using a single page.  I need to be able to get a list of slaves that are currently forwarding data to the master.  Is there a current way to do this?

**Comment by ktsaou** [comment]
@gmosx 	this will be solved with the sharing feature of the new netdata hub we build.
So, it is on our roadmap.

**Comment by cakrit** [comment]
We will not be building this on the netdata registry directly, so private registries will not have this functionality. We will however cover the need via netdata cloud. See #6318 .
