### ISSUE TITLE
rpm build errors in netdata-1.12.1-1.el7.centos.x86_64

### ISSUE THREAD

**Issue by wcallgair** [netdata/netdata#5053]
##### Bug report summary
Receive the following when running contrib/rhel/build-netdata-rpm.sh from the freshly cloned official repo without any modifications. 
```
RPM build errors:
    Directory not found: /root/rpmbuild/BUILDROOT/netdata-1.12.1-1.el7.centos.x86_64/usr/lib64/netdata/conf.d/node.d
```
##### OS / Environment
Centos 7.4.x

##### Component Name
netdata-1.12.1-1.el7.centos.x86_64

##### Steps To Reproduce
git clone https://github.com/netdata/netdata.git
cd netdata
contrib/rhel/build-netdata-rpm.sh
##### Expected behavior

Build process from unmodified source should result in a compiled rpm

**Comment by paulfantom** [comment]
Closing in favor of #5033 as those issues are the same and #5033 was first :)

I am currently working on cleaning up build and installation process which can be disruptive for non-official distribution methods. However since the end goal of this is to provide netdata binary packages, we will get back to this issue pretty soon.

Right now I don't think that the only problem is a lack of this one directory. For example current versioning schema doesn't map one-to-one with rpm spec.
