### ISSUE TITLE
String as a metric

### ISSUE THREAD

**Issue by anubhav96gupta** [netdata/netdata#5060]
I am thinking of implementing a plugin where I want to collect MAC of the WiFi clients connected to an AP. Is it possible to upload string as a metric in netdata?

**Comment by cakrit** [comment]
Well, what would you do with a metric that is a string? I mean, what do you graph, what kind of an alarm would you want etc? 

It would probably make more sense to use [families](https://docs.netdata.cloud/docs/charts/#families) so you can group together various interesting metrics about those connected clients. Note though that if you have a lot of ephemeral connections, you will probably end up will a lot of useless old files in your cache, because currently they are not cleaned up properly.

**Comment by anubhav96gupta** [comment]
@cakrit I am not planning to graph or trigger an alarm but for some kind of analytics by pushing it to a remote server. I am very very new to netdata and just looking what all capabilities are there.

**Comment by cakrit** [comment]
Sounds similar to #3086. We'll probably need to plan adding "table charts" pretty soon. For now though, I think that the only thing you can do is to create a collector that either adds a single chart with multiple, dynamic dimensions with each dimension named as the MAC of the connected device, so you can do a single call to the netdata API "data" method, to get some charted value for all of them (getting the dimension name as well).

Do you by any chance have an AP manager that exports any useful information you can process from that collector? A sample output would help provide more direction.
