### ISSUE TITLE
packages installer failed on Tiny Core linux

### ISSUE THREAD

**Issue by felipeb2it** [netdata/netdata#5085]
Hi people! I tryed to install Netdata manually in Tiny Core linux but got this message bellow.
I installed bash and the essential utilities but I could not solve this. Can you take a look please?

This is what it says:

curl -Ss 'https://raw.githubusercontent.com/netdata/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh -i netdata
Cannot find /etc/os-release
Cannot find valid distribution with lsb-release

The distro is this one http://tinycorelinux.net/

**Comment by paulkatsoulakis** [comment]
Hello,
 I got a tiny  core running on docker and will elaborate on a solution, probably within the day

**Comment by paulkatsoulakis** [comment]
Ok so we do not seem to support the specific package manager on tiny core linux, that explains some of the problems you probably faced.

@felipeb2it Could you please try again following these instructions:
https://docs.netdata.cloud/packaging/installer/#install-netdata-on-linux-manually

In short:

1) Install these packages: `zlib1g-dev uuid-dev libuv1-dev liblz4-dev libjudy-dev libssl-dev libmnl-dev gcc make git autoconf autoconf-archive autogen automake pkg-config curl`
    Note: Make sure you find the respective names that might exist for tiny core specifically

2) Bring on-board netdata source and run the installer
```
 # download it - the directory 'netdata' will be created
git clone https://github.com/netdata/netdata.git --depth=100
cd netdata

# run script with root privileges to build, install, start Netdata
./netdata-installer.sh
```
   Note: You can run `./netdata-installer.sh --help` to see all the available options

**Important note**: Dont forget to install bash before running any of the scripts.

I will resolve this issue for now, but please @felipeb2it do come back and reopen the issue if the problem is not solved. 

Thank you so much for using netdata, you rock!
