### ISSUE TITLE
Use GCS instead of git for updating netdata

### ISSUE THREAD

**Issue by paulfantom** [netdata/netdata#5110]
##### Feature idea summary
Since we are storing netdata nightly build packages in GCS (public bucket `netdata-nightlies`) we may proceed with decoupling distribution channel from development channel and remove dependency on git in an updater script.

This have some consequences:
- directory containing netdata source code won't be important anymore and could be deleted after installation
- uninstaller script will need to be changed to allow deletion of netdata even when there is no source code directory (issue #5031)
- GUI mechanism responsible for checking if new version exists will need to be updated

@Ferroin @ktsaou your input on this would be nice.

##### Expected behavior
- Updater doesn't use `git`.
- Broken `master` branch doesn't result in broken update procedure.

**Comment by Ferroin** [comment]
Overall, I think this is a great idea.  Only three things come to mind beyond what you've mentioned:

* Unless we absolutely _need_ to have this decoupled from `git`, I would suggest instead providing the option to use `git`, but preferentially use GCS if not told otherwise.  GCS will _usually_ be the better option (especially if the user chooses to not update daily), but the differential nature of `git` makes it attractive for some people (especially those who have limited network bandwidth).

* I can also see some potential benefit to allowing the user to specify a custom URL to fetch the updates from.  That way, people who use Netdata on a huge number of systems on the same network can download it from GCS on one or two, and then download it from those systems on everything else.  People who are willing to set things up this way then get the benefit of only having to hit GCS once or twice, and then having a faster update on their other systems, while at the same time reducing the load on the GCS bucket (and possibly the cost to us?).

* If we want to support updating only to full releases or only to fulls and release candidates with the updater script, this is probably the best time to look at doing that since the script is going to be changing anyway.  If we do want that, we should probably also add some logic to support that with the update indicator on the dashboard.

**Comment by paulfantom** [comment]
For the code simplicity I would like to remove git from updater process as this aligns closer to how binary packages are distributed and all this is done as a slow transition to that distribution method.

I like the idea with URL and it fairly simple to accomplish.

As for choosing distribution channel (nightly vs stable) I was thinking of distributing stable packages in a separate GCS bucket, this way we have more data who is using what and in an updater script it is just a matter of changing source bucket. However it would need to be reflected in GUI.

**Comment by Ferroin** [comment]
> For the code simplicity I would like to remove git from updater process as this aligns closer to how binary packages are distributed and all this is done as a slow transition to that distribution method.

OK, I'd say that that is a good reason to not keep `git` support then.

> As for choosing distribution channel (nightly vs stable) I was thinking of distributing stable packages in a separate GCS bucket, this way we have more data who is using what and in an updater script it is just a matter of changing source bucket.

Agreed, though I'd go one step further and do one for nightlies, one for unstable (releases and release candidates), and one for stable (releases only).  That way people can easily test RC's, but don't have to run nightlies, and the RC's don't potentially cause problems for people who prefer only the stable releases.

> However it would need to be reflected in GUI.

Agreed

---

On the note of configuring all of this, I think the best option is going to be having a dedicated config file for it which both the updater and Netdata itself can read.  Probably as simple as having a key for the branch (nightly/rc/stable) and an optional key for overriding the base URL to download from.  Then changing things just amounts to updating a single value in a config file, and it works immediately for both Netdata and the updater.

**Comment by paulfantom** [comment]
I purposefully left release candidates from updater since they aren't really adding anything over nightlies. We are using them more like a marker to show when sprint ends and when sth should get done (github milestones) :smile: There is no additional testing, no release notes, no pre-release in github or anything. Maybe in the future we will do sth with them and then we could add this as a release channel. For now let's start small with nightly channel and add stable after v1.12.0 leaving rc/unstable for undefined future.

**Comment by Ferroin** [comment]
Unless @paulfantom had something unusual planned, we're probably going to end up using either `curl` or `wget` for downloading things, which means you should be able to just define `http_proxy` and/or `https_proxy` in the environment you run the script in, and it should just work.

**Comment by paulfantom** [comment]
We will use `curl` as this is widely available.

**Comment by Ferroin** [comment]
> Possibly with wget as fallback if someone will need it.

In the Linux world `wget` is more ubiquitous than cURL (pretty much all Linux distros have at least the Busybox version of `wget` as part of the base install, only a handful have cURL as part of the base install), so I think it's probably worth having a fallback to `wget` if `curl` isn't present.  It might be worth limiting the use of `wget` to only the options supported by the Busybox implementation, too, as that would allow people running really minimal systems to potentially use Netdata as well.

---

@hellweiss Given the use of `curl`, once this change gets made, you should be able to set the `https_proxy` environment variable to control what proxy gets used (and I'm fairly certain that both `curl` and `wget` support embedding a username and password in the proxy URL).

**Comment by paulfantom** [comment]
I don't have any strong opinions on this, we can use `wget` as default.
