### ISSUE TITLE
Documentation is too hard to understand.

### ISSUE THREAD

**Issue by Laurel-rao** [netdata/netdata#5143]
Situation:
    I can't build my-netdata  from documentation to collect the information of Switch and Router.
    I feel the documentation about Get-Started is too easy when I finished reading.
    when i read the documentation I can't understand sort of Noun like  'metrics, orchestrator'. 
    Documentation don't tell how the Netdata work for and what problem you solved.
    I feel helpless that i don't know how to configure a useful system.
    My English is poor, sorry about that, i just hope the Netdata can be use from more and more people.
   
##### Expected behavior
I think your documentation should be easy to understand，be friendly with new guys.
And for the middle-level part of documentation, i thought it should provide more information about how to use it.Not just show a lots of API and easy Get-Started.

**Comment by cakrit** [comment]
We're sorry it was difficult for you, we constantly try to improve the documentation. 
Unfortunately we don't have out of the box support to collect information from switches and routers, so you would need to [configure the SNMP collector](https://docs.netdata.cloud/collectors/node.d.plugin/snmp/), in order to start seeing charts for these devices. However, you do need to know a few things about SNMP OIDs and the metrics (i.e. information) you want Netdata to collect. One metric could be for example the traffic through a particular interface. 
Once you get a chart shown on the Netdata UI with the information you want, you can [configure alarms](https://docs.netdata.cloud/health/) for that chart. Without a good understanding of English, I'm afraid that it will be difficult to walk you through the process, but we'll be happy to try. 

 The "Get-Started" could definitely use an explanation of the features on our current dashboard (#4779). However, what you need for your case would not be helped with this. We are also constantly trying to improve the new [configuration guide](https://docs.netdata.cloud/docs/configuration-guide/), with more and better HOW-TOs.
