### ISSUE TITLE
Determining "cron" CPU usage

### ISSUE THREAD

**Issue by Daniel15** [netdata/netdata#5167]
##### Question summary
If Netdata shows a lot of CPU usage for "cron", is there a way to determine which cronjob is causing the CPU usage?

![](https://d.sb/2019/01/firefox_13-22.15.56.png)

##### OS / Environment
Debian buster

**Comment by cakrit** [comment]
I think that since it's cron, you can just look at  crontab to see what runs at 22:00. I would love to hear about a possible addition/change though, because a high cpu time from X is not as easy to trace.

**Comment by Daniel15** [comment]
The tricky thing is that I have a lot of cronjobs, so I'm not sure exactly which one it is (short of commenting them out one by one, or watching `top` output when they run). I usually use the application CPU usage graph to narrow down high CPU usage, but in this case it's all lumped into "cron" as shown in my screenshot.

**Comment by ilyam8** [comment]
@Daniel15 you have start time on graph, check the logs and see what job was started at that time.

**Comment by cakrit** [comment]
I learned something more since the last time we discussed this. The solution is actually simple. You just modify the apps plugin configuration, so that the charts show all the processes you have in your crontab. Do `/etc/netdata/edit-config /etc/netdata/orig/apps_groups.conf`, the file contains instructions on how to show different processes.
