### ISSUE TITLE
apps.plugin memory usage bug

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#5237]
##### Bug report summary

apps plugin shows wrong memory usage

##### OS / Environment
4.19.14-1-MANJARO

##### Netdata version (ouput of `netdata -V`)
`netdata v1.12.0-rc3-15-gde6ab08`

##### Component Name
`/collectors/apps.plugin`

##### Steps To Reproduce
example, memory usage of [prometheus node_exporter](https://github.com/prometheus/node_exporter)

Problem exist if i start `node_exporter` before `netdata` process.

Problem:
 * start `node_exporter`
 * start `netdata`

(restart doesn't solve the problem)

No problem:
 * start `netdata`
 * start `node_exporter` 

(restart = wrong memory usage again)

See the screenshot.

![screenshot_20190121_103713](https://user-images.githubusercontent.com/22274335/51459176-ba3ee880-1d68-11e9-8d1f-bfb71fd2b9f6.png)

##### Expected behavior

show correct numbers

**Comment by vlvkobal** [comment]
I was able to reproduce the bug. Actually, it is not a bug. It is a predefined behaviour. We have the following in our documentation:

*For the Applications section, only groups configured in this file are reported. All other processes will be reported as other.*
*For each process given, its whole process tree will be grouped, not just the process matched. The plugin will include* **both parents and children**.

The problem appears when the parents of the `node_exporter` (or any other process) don't have any groups assigned. For example, it happens when a window manager is not included in `apps_groups.conf`.

I think we have two options to make grouping more clear for users:
1)  - Make a statement in our documentation, that if somebody wants to change this behaviour, the line
`other: *` should be added to the end of `apps_groups.conf`.
     - Add more names of high-level processes to `apps_groups.conf` as they are identified.
2) Disable target group inheritance from a child to its parent and include all parents with group undefined into the `other` group. It can be done in the source code or by adding `other: *` to the end of the default `apps_groups.conf`.

**Comment by ilyam8** [comment]
confirm, adding `other: *` to the end of the conf file fixed the problem
