### ISSUE TITLE
Failed to run in linux deploy(debian arm64 stretch)

### ISSUE THREAD

**Issue by hexesdesu** [netdata/netdata#5268]
Hello,
    I tried to install netdata in Linux Deploy(Debian arm64 stretch) on my phone(Nexus 5X with Pie) ,using `bash <(curl -Ss https://my-netdata.io/kickstart.sh)` .
    I finished the install process (netdata is installed and running now!)
    Open 'http://this.machine.ip:19999/' in browser but said : **ERROR 405: Cannot download charts index from server: http://'this.machine.ip':19999/api/v1/charts** 
    Is that a permission fault or something else?

   Thanks

**Comment by cakrit** [comment]
You do get this due to permission issues, for sure, but not when you just do a fresh install and with the default config.

Did you configure a different user? Did you start it with sudo systemctl?

You can see all the directories netdata uses at http://'this.machine.ip':19999/netdata.conf

Please let us know what you see.
