### ISSUE TITLE
permissions error after install from source

### ISSUE THREAD

**Issue by vicioustriangle** [netdata/netdata#5274]
Hi, I have installed netdata from source on a CentOS 6 server with cpanel/apache. 
the install script failed with the same issue as this:
https://github.com/netdata/netdata/issues/5251
(source directory does not include netdata-installer.sh), which I then ran in a directory
I found under /root/netdata and it seemed to install ok.

after opening port 19999 on the firewall I try to access it with serverip:19999 and get this error page:
Access to file is not permitted: /usr/share/netdata/web//index.html

I ran the install as root. Is that a good idea? /usr/share/netdata is owned by root
/usr/share/netdat/web is owned by user netdata
the files in that directory are mostly owned by root, including index.html

thanks for your help

**Comment by cakrit** [comment]
The install script when you install from source **is** netdata-installer.sh. See https://docs.netdata.cloud/packaging/installer/#install-netdata. It needs to be executed as root, as you did, so that it creates the netdata user and give the appropriate permissions. I suppose that /root/netdata was where you cloned the gIt repository, otherwise it would fail.

In a proper installation, the web directory file ownership is `netdata:netdata` so there's definitely something wrong. Let's not try to fix it manually, can you please go back to the directory where you cloned git, run the installer as root and show us the output after the compilation is done? There are several chown/chmod commands there. 

I looked at the other issue as well, the error didn't make sense. Let's try to do repeat the installation by source first, to see where things go wrong.
