### ISSUE TITLE
Qmail plugin

### ISSUE THREAD

**Issue by arkamar** [netdata/netdata#5298]
Hi,

I wrote a netdata external [`qmail.plugin`](https://github.com/arkamar/netdata_qmail_plugin) and I would like to make it part of the upstream netdeta, but before I start to work on pull request itself, I would like to ask, if you want it.

It is written in C and it is curently Linux specific, because I use `inotify`, `timerfd` and `signalfd` syscalls.

Write me if you have any qeustion about the plugin.

Thank you for **netdata**, you already have my star :)

**Comment by cakrit** [comment]
I'm thinking that we may try something that will help us even more.
We're moving collectors to a new go.d plugin that we've been building. We're already preparing the cgo version of that plugin, that can get linked to c libraries and we'll be providing a separate library project that people can use in their own repos, so that anyone who wants such plugins will be able to install it. 

The ideal scenario for me would be for @ilyam8 and @kataras to help you convert your project to one that utilizes that library, so that we have at least one 'third-party' plugin, as a proof of concept. Don't worry if you're not comfortable with go, I'm sure the gents can help you out.

**Comment by ilyam8** [comment]
Hi @arkamar.

As a third-party plugin we can leave it as-is, just add a link to it in the `third-party plugin` page.

If we want to have it in netdata in C - @vlvkobal please answer OP questions. 

If we don't want to have it in C for some reason, it should be rewritten in another language, for example in `go`.

**Comment by ilyam8** [comment]
use cgo == write a go library which uses c code ([example](https://github.com/mindprince/gonvml/blob/master/bindings.go)), which makes not sense in that case.

**Comment by cakrit** [comment]
Ok gents, but since we have essentially zero documentation on writing C plugins, it would be worth it if we described anything that  @arkamar would need to look at. @akamar give it a shot, note the use of Makefile.am in the plugins @vlvkobal mentioned, so you can get it to compile. Don't forget to set up alarms under `health/health.d` and a required README.md that explains what is collected, what charts are produced, any prerequisites and the supported configuration options.

**Comment by arkamar** [comment]
Ok, thanks. I'll look to the `freeipmi` or other C external plugin and prepare the pull request. I believe that you told me everything important for now. Anyway, I will ask if there will be some issue.

Thanks again.

**Comment by ilyam8** [comment]
Closing this issue due to the low interest in this feature.

If there is anybody who is interested in having this implemented please visit our Community Forums and create a new topic in the [Netdata Agent Feature Requests](https://community.netdata.cloud/c/feature-requests/agent-fr/21) category.
