### ISSUE TITLE
show static system information on the dashboard

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#531]
in several occasions it is required to show static system information on the dashboard.

Examples:
- [ ] swappiness next to the swap chart #355 
- [ ] show cpu governor #503

Please post here any other ideas you have, and I am going to add them.

**Comment by GeorgeTG** [comment]
It would be nice to have lists of alphanumeric values, instead of just numeric data.

For example:

- List of running/failed systemd services
- List of DHCP leases
- List of connected clients to access point
- List peers connected to a specific service(VPNs etc)
- List of known routers in the network
- List of other `netdata` hosts in the network
- List of IP routes - subnets

Those could be reported as key-value or key-tuple pairs they same way they are reported from plugins right now, but the values have to be arbitrary(strings?) and not just numeric.

Example plugin output:
----------------------------------
`LIST ipv4.leases '' 'IPV4 Leases' leases dhcp ipv4.dhcp
ENTRY leases '' 4 # number of columns
BEGIN ipv4.leases
ADD leases =  1 aa:bb:cc:dd:11:22 10.0.0.12 example_hostname
ADD leases =  2 aa:bb:cc:dd:33:44 10.0.0.13 another_hostname
END
`
Then this data would be rendered almost as it is now, but instead of a graph, a list with columns is used.
This seems like a major feature, and I am not sure if it's worth the effort needed to implement it, or if it fits the purpose of the project, but nonetheless I am posting it as an idea.

**Comment by davidak** [comment]
>List of running/failed systemd services

that would be amazing + notification for failed services (optionally also for failed ones that was succesfully restarted)

**Comment by thinrope** [comment]
Adding non-numeric values to a RRD database is not possible ATM, AFAIK.
There are very few "static" things in a running system, esp. cpuferq_governer (I change it on my laptop).
Given that netdata displays historical data as well, I think limiting this to a very few things, up next to the hostname will be the best.

Probably some hardware info (RAM/CPU), identification (model/SN) and kernel version. Those should be fixed/static file created at start/restart of the daemon. We'll need new API for that as well.

**Comment by Ferroin** [comment]
Certain things are not likely to change frequently, if at all, on most of our targeted types of systems (servers/IoT).  Swappiness probably fits this, as does the CPU governor (and driver, because the governor is useless without knowing the driver too (thanks Intel)).  Other possibilities that come to mind include:

* `/proc/sys/kernel/pid_max` Should also be exposed as a chart variable on the `system.active_processes` chart.  I think there was an issue related to this, but I can't seem to find it.
* `/proc/sys/vm/vfs_cache_pressure`  Indicates how likely the kernel is to evict entries from the page cache over other forms of memory reclamation.
* Network link characteristics:
    * Hardware address (`/sys/class/net/*/address`).
    * Link speed and duplex (I think we expose the first as a chart variable on the `net.*` charts, values are in `/sys/class/net/*/{speed,duplex}`).
    * Link state (`/sys/class/net/*/operstate`).
    * MTU (`/sys/class/net/*/mtu`).
* Storage device characteristics:
    * Device serial/WWN (not sure where to find this in `/sys`, but I know it's there).
    * Device rotational speed (I think this one needs an ioctl, but I'm not sure, `hdparm`, `sdparm`, and `smartctl` all seem to find it).
    * Device link type (for example, NVMe/SAS/SATA, not sure how to figure this out properly, obvious answers generally don't work because Linux routes _a lot_ of things through the SCSI layer).
    * Device I/O scheduler (the bracketed value in `/sys/block/*/queue/scheduler`).
    * Underlying storage device (for LVM/MD/DM devices, can't recall how to figure this out reliably).
* Filesystem characteristics:
    * UUID
    * Underlying storage devices (trivial for the common case, somewhat easy for BTRFS (`/sys/fs/btrfs/*/devices`, but needs to be re-checked frequently because it can change while the volume is mounted), possibly easy for ZFS (not sure), non-trivial for XFS and ext4 with dedicated journal device).
* General system info beyond hostname:
    * `/etc/machine-id`
    * `uname -s` + `uname -r`
    * Core count and CPU type (we expose core count as a chart variable, though I forget which chart it's on, CPU type can be scraped from `/proc/cpuinfo` or `uname -p`).
    * Total RAM (not userspace addressable, but actual total system RAM).

**Comment by thinrope** [comment]
Just a tiny idea that might be helpful in coding (I am using this in another system):
Note that Netdata deals (mainly) with time-series, i.e. timestamp->value that nicely fit in a RRD; data discussed here ("static", as seen during the short timeframes other Netdata fluctuates) and in #1114 (annotations) is more of a value->timestamp type (and thus does not fit the RRD model), thus another storage is needed (sqlite, csv, hashtable, python dictionary, etc.).
Also, some data may need value->{timestamp_start,timestamp_end} when there is gap in data collection, so value=NaN for time_A till time_B, and also other data is point_in_time (e.g. annotation), so time_A=time_B (e.g. "HDD crash" label).

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
