### ISSUE TITLE
my-netdata and registry

### ISSUE THREAD

**Issue by dankott** [netdata/netdata#5336]
Is there any way to disable cloud and use the old my-netdata?

If not is there a way to install older versions?

**Comment by cakrit** [comment]
Hi @dankott, you can always [run your own registry](https://docs.netdata.cloud/registry/#run-your-own-registry), but we would greatly appreciate your feedback on this. We will be providing **a lot** of features via the new sign-in functionality that we wouldn't be able to do otherwise, so we really want to hear about what you did not like.

**Comment by tino** [comment]
Hi, I would also like to use the old method. It worked fine. I don't want to run a registry and I don't want an extra account at some cloud provider.

Please enable the old way, it worked great.

**Comment by benagricola** [comment]
Related to this: I'm running my own registry, my netdata instances are configured to talk to it, but i still see 'sign in to netdata cloud' when trying to view the list of nodes.

**Comment by cakrit** [comment]
We have a long roadmap of features that will require sign-in and a central repository. We'll have a cloud version and an on-premise version. We also thought that the old way was fine, but let's not forget that many people disagreed fervently (e.g. #2760 and #3937). 

Everyone can get an older release from https://github.com/netdata/netdata/releases of course, but what you'll see gradually coming out in the cloud console in the next few months will address all the top improvements users have asked for in [our survey](https://docs.google.com/forms/d/1lXKZd8YOKJxF1clQHkv8N1tx2rF4PqPjhRwLYDceA3g/edit).
