### ISSUE TITLE
How can it be done so that the servers show up as the demo?

### ISSUE THREAD

**Issue by lengmiguel** [netdata/netdata#5375]
How can I make my servers display as follows?

![image](https://user-images.githubusercontent.com/22181854/52673417-b5480180-2eee-11e9-9777-152bf1d1e5bf.png)

**Comment by cakrit** [comment]
This what is called a [custom dashboard](https://docs.netdata.cloud/web/gui/custom/).  Lots of info on that link, with links to other examples as well. You'll be able to do what you need. 
Stay tuned for a custom dashboard editor that is in the works, so that you can do these things via a UI instead.

**Comment by lengmiguel** [comment]
Thank's You
