### ISSUE TITLE
add rpm build on release page

### ISSUE THREAD

**Issue by Wing924** [netdata/netdata#5377]
##### Feature idea summary
add rpm build on release page so that user can download rpm and install.

##### Expected behavior
release page have rpm to download.

**Comment by aboubeta** [comment]
I made a very simple CI job on gitlab in order to create RPM nightly packages:

https://gitlab.com/boube/netdata

The packages are published here:

https://packagecloud.io/boube/Netdata

Maybe this could be useful for anybody.

The process is fully automated, I don't touch the code at all. Feel free to suggest improvements or other repo providers.

**Comment by cakrit** [comment]
Our binary packages are now on https://packagecloud.io/netdata/netdata and https://packagecloud.io/netdata/netdata-edge (nightlies). They're still in beta, but the installation method is described in the docs, so closing this one.
