### ISSUE TITLE
Need more graceful handling of duplicate machine GUIDs

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#5488]
##### Bug report summary

We spent a lot of time trying to identify the root cause of some problems in a master slave setup. The root cause ended up being that one of the slaves was created by cloning the master, taking the same machine GUID with it. We should have at least a detection of such cases, so we can warn users about it.

##### Steps To Reproduce
Master and slave with the same GUID.
The master hostname configured in netdata.conf is overwritten by the slave's hostname and we have issues with the charts as well. 

##### Expected behavior
Report an error, or have a self-cleaning behavior (e.g. regenerate a machine GUID when a duplicate is reported).

**Comment by paulkatsoulakis** [comment]
It seems that the current implementation is informing the user with a warning, while at the same time  replaces the host information with the one that just arrived.

Offending line: https://github.com/netdata/netdata/blob/3b28e0f5ed1ab1eb441be9bcc74de0a0722aea82/database/rrdhost.c#L364

From a brief research, i could see the following possible solutions:

- The change with the least customer impact:  Always calculate the GUID upon start-up instead of attempting to find it on file first. Offending method: https://github.com/netdata/netdata/blob/8fbf817ef83b3524b15f908251909d9d6feb5532/registry/registry_internals.c#L277
To do this though, we will have to rethink the GUID calculation, so that we can statically define it on each machine. 
Then we need to make the warning in the following line a hard error that would prompt the user of the situation and stop the start up (in case this happens again on some unpredictable scenario)
https://github.com/netdata/netdata/blob/3b28e0f5ed1ab1eb441be9bcc74de0a0722aea82/database/rrdhost.c#L364 


- If GUID uniqueness can't be approached in a way that the identifier will be regenerated at run-time instead of being saved on the file, then we could simply fail the start-up when this happening to at least avoid raising that conflict. The downturn here is that we add the effort to our customer to take action and fix the conflict.


- A much more risky approach to mitigate this could be the auto-fixing of GUID when it arrives on the master host. Conflicting GUIDs could be specially treated on master by adding an extra identifier on the GUID string when saving it locally. For example we could append the md5 of the IP, so that it can be reconstructed  every time is seen and not conflict with the master. It might sound easy change, but it might require quite a few adjustments to do it right (i haven't gone through it thoroughly)

**Comment by cakrit** [comment]
> The change with the least customer impact:  Always calculate the GUID upon start-up instead of attempting to find it on file first.

The machine guid is supposed to be a rather permanent identification of a host. The registry depends on that more than it does on hostnames and urls. So we can't be changing it all the time.

The other two options seem better. If we already identify the situation (you said you saw a warning), then we could auto-correct it on the master. We don't want to change the GUID format, but we could regenerate it. There is a question though on whether by that time we will already have some corrupted data. So it may actually be necessary for the master to refuse to process any of the slave's data, until the duplicate GUID situation is resolved, either manually or automatically.

**Comment by ktsaou** [comment]
Fixed in https://github.com/netdata/netdata/pull/5497

**Comment by cakrit** [comment]
@paulkatsoulakis please test that PR and we'll merge.

**Comment by paulkatsoulakis** [comment]
The fix does not seem to get us all the way there.
We are still allowing the execution of rrdhost_find_or_create() that modifies our configuration, thus resulting on the UI showing the wrong host as the default host that should be the master.

https://github.com/netdata/netdata/blob/2ee2d94891e88d9c773f7633746a38fb341f2bac/streaming/rrdpush.c#L874 

If i get the change right, we do block the eventual data corruption, but we still need to make sure we avoid modifying the master host details. So.. probably this check should go at the very beginning to completely avoid any further processing ?

**Comment by cakrit** [comment]
Ok, can you do a different PR based on #5497 to take care of the UI as well?

**Comment by paulkatsoulakis** [comment]
Good morning, sure i 'm on it

**Comment by paulkatsoulakis** [comment]
I think we can resolve this now (i can't resolve)
