### ISSUE TITLE
apps_plugin plots zeroes for empty groups

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#5514]
##### Bug report summary

`apps_plugin` plots zeroes for group even if there is no processes in that group.

related issue #5510 	

##### OS / Environment

any

##### Netdata version (ouput of `netdata -V`)

netdata v1.12.1-16-g2ee2d948

##### Component Name

[collectors/apps.plugin](https://github.com/netdata/netdata/tree/master/collectors/apps.plugin)

##### Steps To Reproduce
 - add an entry to `apps_groups.conf`
 - run a process that maches that entry
 - stop the process
 - see charts

##### Expected behavior

`apps_plugin` shouldn't return any values for group if there is no processes in that group

**Comment by ilyam8** [comment]
@ktsaou please check, maybe this is expected behavior and there is some logic behind this which i don't understand.

**Comment by ilyam8** [comment]
Ok, i've discussed it with @vlvkobal in detail, and now i see that the behavior is `as expected`.

**Comment by ilyam8** [comment]
still

___
restart.netdata

t1 (process is not running): no zeros on grpahs
t2 (process is running): values on graphs
t3 (process is not running): zeros on graphs

___

t1 == t3, process is not running, but the `apps_plugin` output is different. I find it confusing.

**Comment by cakrit** [comment]
@vlvkobal please write a bit more about why it is expected. I also don't understand the last post at all.

**Comment by vlvkobal** [comment]
On start, if there is no data for a group, the corresponding dimension is not displayed in `apps.plugin` charts. After any process from the group starts - the dimension appears. When all processes in the group exited, zeroes are displayed for this group in every chart. Zeroes are logically correct because the group doesn't use any resources anymore. But, yes, for consistency with the absence of data on the beginning we can suppress sending zeroes after all processes from the group have been exited.

**Comment by ilyam8** [comment]
>  Zeroes are logically correct because the group doesn't use any resources anymore.

yes, yes, but i find it misleading because of _zero use != don't use_

Although i agree that current behavior is ok, if it is documented. So updating the docs is enough imo.
