### ISSUE TITLE
nightlies.sh should stop on error

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#5580]
##### Feature idea summary
Currently, .travis/nightlies.sh just sets an exit code upon failure and proceeds to create and publish the artifacts. 

##### Expected behavior
Stop on error, with `set -e` so that:
- We can easily see what failed
- We don't risk publishing corrupted artifacts

**Comment by paulfantom** [comment]
This was the initial design. It was changed with https://github.com/netdata/netdata/pull/5219

**Comment by cakrit** [comment]
Right. The problem now is that it's practically impossible to find what failed in thousands of lines of logs. How can we know what failed?

**Comment by paulkatsoulakis** [comment]
Do we really need all these scripts to be in BASH?
Is there a limitation from rewriting them in python for example?

**Comment by paulfantom** [comment]
There is no such limitation

**Comment by cakrit** [comment]
> There is no such limitation

Except time of course! :)

**Comment by paulkatsoulakis** [comment]
> Except time of course! :)
Of course :P

**Comment by paulkatsoulakis** [comment]
Ok so, after checking out #5219 from what i understand in order to cover the use case @Ferroin mentions we don’t have to remove set -e. It is enough to add  `UNSTABLE_COMMAND || FAILED=1` Where “UNSTABLE_COMMAND” is for example the build script and then report a message on whether it failed or not, without breaking execution. Then strict execution checking will be valid for the rest of the commands as it should

So to attend this:
1) I reinstate `set -e` option
2) Adjust the commands we want to be handled as soft errors in the way i mentioned above.

Any thoughts? It is not 100% clear for which commands we want this done, i will prepare the PR with the docker commands handled like this for now, but let me know

**Comment by paulfantom** [comment]
The only "soft error" should be probably a changelog generation. Everything else should fail hard. Which means that we should revert to old design and just add `|| FAILED=1` to execution of changelog generation script.

**Comment by cakrit** [comment]
Again, what really matters is to be able to quickly find the error that caused a step to fail, without breaking the process for the steps that don't depend on the failed step. There are hundreds if not thousands of lines in that output.

**Comment by paulfantom** [comment]
Those hundreds of lines are present due to netdata-installer.sh not having a "silent mode". Introduce this and problem is solved.

**Comment by paulkatsoulakis** [comment]
merged fixes, closing
