### ISSUE TITLE
go.d.plugin perm should be not 750 but 755

### ISSUE THREAD

**Issue by Wing924** [netdata/netdata#5586]
##### Bug report summary

The perm of `go.d.plugin` is 750 while other external plugins are 755.

```
$ ls -l *.plugin
-rwsr-x--- 1 root    netdata   150160 Feb 22 04:24 apps.plugin
-rwxr-xr-x 1 netdata netdata    19147 Feb 22 04:24 charts.d.plugin
-rwxr-xr-x 1 netdata netdata     5540 Feb 22 04:24 fping.plugin
-rwxr-x--- 1 netdata netdata 13114089 Feb 22 04:24 go.d.plugin
-rwxr-xr-x 1 netdata netdata    11084 Feb 22 04:24 node.d.plugin
-rwxr-xr-x 1 netdata netdata    14827 Feb 22 04:24 python.d.plugin
```

##### OS / Environment

CentOS 7

##### Netdata version (ouput of `netdata -V`)

netdata v1.12.2 (static binary)

##### Component Name

install script

##### Steps To Reproduce

```
ls -l /opt/netdata/netdata-plugins/plugins.d
```

##### Expected behavior

The perm of `go.d.plugin` should be 755.

**Comment by ilyam8** [comment]
i see there is a little mess with ownership/permissions in the `plugins.d`

> -rwxr-xr-x 1 root root         154 мар  9 12:04 alarm-email.sh
-rwxr-xr-x 1 root root       74185 мар  9 12:04 alarm-notify.sh
-rwxr-xr-x 1 root root         301 мар  9 12:04 alarm-test.sh
-rwxr-xr-x 1 root root        6407 мар  9 12:04 anonymous-statistics.sh
-rwxr-x--- 1 root netdata   100848 мар  9 12:04 apps.plugin
-rwxr-xr-x 1 root root        5408 мар  9 12:04 cgroup-name.sh
-rwsr-x--- 1 root netdata    43376 мар  9 12:04 cgroup-network
-r-xr-x--- 1 root root        8178 мар  9 12:04 cgroup-network-helper.sh
-rwxr-xr-x 1 root root        1259 мар  9 12:04 charts.d.dryrun-helper.sh
-rwxr-xr-x 1 root root       19147 мар  9 12:04 charts.d.plugin
-rwxr-xr-x 1 root root       42216 мар  9 12:04 cups.plugin
-rwxr-xr-x 1 root root        5540 мар  9 12:04 fping.plugin
-rwxr-x--- 1 root netdata 13114089 мар  9 12:04 go.d.plugin
-rwxr-xr-x 1 root root        8194 мар  9 12:04 health-cmdapi-test.sh
-rw-r--r-- 1 root root        6631 мар  9 12:04 loopsleepms.sh.inc
-rwxr-xr-x 1 root root       11084 мар  9 12:04 node.d.plugin
-rwxr-xr-x 1 root root       20684 мар  9 12:04 python.d.plugin
-rwxr-xr-x 1 root root        7318 мар  9 12:04 tc-qos-helper.sh

**Comment by ilyam8** [comment]
should be root/netdata if 750

**Comment by Wing924** [comment]
go.d.plugin should be same as python.d.plugin.

**Comment by ilyam8** [comment]
i think we need 750 and root:netdata for all plugins

**Comment by paulkatsoulakis** [comment]
Adding for reference that we have PR #5505 that may be attending the issue.
I will check

**Comment by paulkatsoulakis** [comment]
Ok so #5505 does things quite different. 
The end result is the following, which i don’t think is the desired one.
I think we should use `netdata:netdata` for all files, unless explicitly required for functional reasons.

Here’s the complete list of files created from the PR code:

[paul@netdata-test-container2 ~]# ls -l /usr/libexec/netdata/plugins.d/
total 316
-rwxr-xr-x 1 root netdata   154 Mar  8 10:12 alarm-email.sh
-rwxr-xr-x 1 root netdata 74125 Mar  8 10:12 alarm-notify.sh
-rwxr-xr-x 1 root netdata   301 Mar  8 10:12 alarm-test.sh
-rwxr-xr-x 1 root netdata  6371 Mar  8 10:12 anonymous-statistics.sh
-rwsr-x--- 1 root netdata 89976 Mar  8 10:12 apps.plugin
-rwxr-xr-x 1 root netdata  5384 Mar  8 10:12 cgroup-name.sh
-rwsr-x--- 1 root netdata 35736 Mar  8 10:12 cgroup-network
-r-xr-x--- 1 root netdata  8178 Mar  8 10:12 cgroup-network-helper.sh
-rwxr-xr-x 1 root netdata  1259 Mar  8 10:12 charts.d.dryrun-helper.sh
-rwxr-xr-x 1 root netdata 19123 Mar  8 10:12 charts.d.plugin
-rwxr-xr-x 1 root netdata  5516 Mar  8 10:12 fping.plugin
-rwxr-xr-x 1 root netdata  8158 Mar  8 10:12 health-cmdapi-test.sh
-rw-r--r-- 1 root netdata  6631 Mar  8 10:12 loopsleepms.sh.inc
-rwxr-xr-x 1 root netdata 11060 Mar  8 10:12 node.d.plugin
-rwxr-xr-x 1 root netdata 14949 Mar  8 10:12 python.d.plugin
-rwxr-xr-x 1 root netdata  7294 Mar  8 10:12 tc-qos-helper.sh
[root@netdata-test-container2 netdata]#

Here’s the files created from the current master code:

[root@netdata-test-installer1 ~]# ls -l /usr/libexec/netdata/plugins.d/
total 13132
-rwxr-xr-x 1 root root         154 Mar  8 10:12 alarm-email.sh
-rwxr-xr-x 1 root root       74125 Mar  8 10:12 alarm-notify.sh
-rwxr-xr-x 1 root root         301 Mar  8 10:12 alarm-test.sh
-rwxr-xr-x 1 root root        6371 Mar  8 10:12 anonymous-statistics.sh
-rwsr-x--- 1 root netdata    89976 Mar  8 10:12 apps.plugin
-rwxr-xr-x 1 root root        5384 Mar  8 10:12 cgroup-name.sh
-rwsr-x--- 1 root netdata    35736 Mar  8 10:12 cgroup-network
-r-xr-x--- 1 root root        8178 Mar  8 10:12 cgroup-network-helper.sh
-rwxr-xr-x 1 root root        1259 Mar  8 10:12 charts.d.dryrun-helper.sh
-rwxr-xr-x 1 root root       19123 Mar  8 10:12 charts.d.plugin
-rwxr-xr-x 1 root root        5516 Mar  8 10:12 fping.plugin
-rwxr-x--- 1 root netdata 13114089 Mar  8 10:12 go.d.plugin
-rwxr-xr-x 1 root root        8158 Mar  8 10:12 health-cmdapi-test.sh
-rw-r--r-- 1 root root        6631 Mar  8 10:12 loopsleepms.sh.inc
-rwxr-xr-x 1 root root       11060 Mar  8 10:12 node.d.plugin
-rwxr-xr-x 1 root root       20660 Mar  8 10:12 python.d.plugin
-rwxr-xr-x 1 root root        7294 Mar  8 10:12 tc-qos-helper.sh
[paul@netdata-test-container1 ~]#

**Comment by paulfantom** [comment]
I don't know why this file should be executable by other users (perm 0755), but here is a fix making it 0755: #5603

**Comment by ilyam8** [comment]
> I don't know why this file should be executable by other users (perm 0755),

So do i, i see no practical use for it - if there is module configuration file and **the file is not readable**/has syntax errors module will fail to start (lack of module config is ok tho).

**Comment by Ferroin** [comment]
> I think we should use netdata:netdata for all files, unless explicitly required for functional reasons and of course use 750 instead of 755

Permissions for anything Netdata executes need to be such that the `netdata` user cannot write to the files. Otherwise, a bug allowing a user with access to Netdata to write arbitrary files with the permissions of the `netdata` user goes from being a DoS or data corruption risk into being a far more serious ACE exploit (and from there potentially into privilege escalation).

> I don't know why this file should be executable by other users (perm 0755),

I would argue that it shouldn't be executable by other users, and the `go.d` plugin is one of the only ones doing things correctly here.  A lot of these plugins allow for retrieving information that may not be otherwise accessible to anybody who does not have access to the Netdata API or dashboard for the system.  Making them executable by other users allows for reasonably trivial disclosure of this information.

The only advantage I can see to having them world executable is to simplify debugging, but the only people who should be debugging things should already have sufficient privileges to use `sudo -u netdata` or whatever the local equivalent is to run the plugins as the `netdata` user.

**Comment by paulkatsoulakis** [comment]
@Wing924 Hello, in order for us to evaluate the permanent solution for this, could you elaborate a bit on the use case exactly that broken or raised problem due to this lack of permission? Or perhaps it is just something you observed and you did not face any functional problems?

thanks

**Comment by ilyam8** [comment]
> The only advantage I can see to having them world executable is to simplify debugging

> if there is module configuration file and the file is not readable/has syntax errors module will fail to start (lack of module config is ok tho).

It is more disadvantage than advantage.

**Comment by Wing924** [comment]
> @Wing924 Hello, in order for us to evaluate the permanent solution for this, could you elaborate a bit on the use case exactly that broken or raised problem due to this lack of permission? Or perhaps it is just something you observed and you did not face any functional problems?
> 
> thanks

* simplify debugging
  * I run `sudo -u netdata ./go.<tab>` but found no bash completion.
* can't check go.d.plugin version without sudo
* many executables which must be run as root (ex. /sbin/*) have 755 perm
* give plugins `o+x` won't increase or decrease security risk
  * they're designed to run as normal user

So I suggest:
* apps.plugin should be root:netdata 4750 because it have SUID
* other plugins should be 0755 same as other normal executables

**Comment by ilyam8** [comment]
> they're designed to run as normal user

normal user != any user

**Comment by Ferroin** [comment]
> I run sudo -u netdata ./go.<tab> but found no bash completion.

This is an issue with your distro or your system configuration.  Filename tab completion is absolutely possible with that command, it just needs to be configured just like for any other shell tab completion.

> can't check go.d.plugin version without sudo

This is actually an issue, but it could easily be solved by providing a command that's SUID `netdata` which queries the version for each plugin and reports it.  On top of that, this won't be an issue once we get proper package manager integration (you can at that point just query the package manager).

> many executables which must be run as root (ex. /sbin/*) have 755 perm

There are two reasons for this:

* Tradition (not a valid argument here).
* The fact that you don't _need_ root to run most of those commands.  `mount` and `ping` can be run just fine by normal users on most systems, and it's not particularly hard to configure a system to allow running many of the other commands there as a normal user in a useful manner.

> give plugins o+x won't increase or decrease security risk

First off, you can't prove that.  Proving the lack of _any_ security risk in any practical situation is functionally equivalent to the halting problem.

Second, it _will_ increase security risk, independent of the information disclosure issue I'll cover in a moment, because it increases the system's attack surface.  The more code an attacker has access to, the more likely they can successfully exploit the system because more code == more bugs.

Third, independent of that, much of what we collect is not data that normal users have any business seeing.  At minimum, just by running Netdata plugins, I can potentially figure out all of the following about a system:

* What software the system is running.
* Network latency.
* Certain baseline configuration for a variety of software the system may be running.
* High-level table layout in most database systems we monitor.
* How accurate the system's time is.
* Environmental conditions within and around the system.
* A number of things that can be used for fingerprinting the underlying hardware, including potentially very detailed topological information about certain hardware subsystems.

Most of that info can't normally be obtained by a user who does not already have administrative access to the system, and all of it is potentially useful to an attacker.  Hell, even just the _first_ item (what software the system is running) is a gold mine for an attacker, as it significantly narrows down what possible attacks there are against the system.

> they're designed to run as normal user

As mentioned by @ilyam8, 'normal' user is not the same as 'any' user.

**Comment by Wing924** [comment]
@Ferroin I agree with you.

**Comment by paulkatsoulakis** [comment]
We will be finalising this issue, as soon as we merge in the netdata-installer.sh clean-up PR that was prepared by Pawel and will be completed by me.

**Comment by paulkatsoulakis** [comment]
After the latest changes, the only thing that i see pending to do is correlate the permissions amonst plugins to 0750.

So after the change the permissions will look like this:
```
[root@d28c32151328 plugins.d]# ls -ltr *plugin
-rwxr-x--- 1 root netdata    19123 Apr 12 15:11 charts.d.plugin
-rwxr-x--- 1 root netdata     5516 Apr 12 15:11 fping.plugin
-rwxr-x--- 1 root netdata    11060 Apr 12 15:11 node.d.plugin
-rwxr-x--- 1 root netdata    21336 Apr 12 15:11 python.d.plugin
-rwsr-x--- 1 root netdata    89976 Apr 12 15:11 apps.plugin
-rwxr-x--- 1 root netdata 14818313 Apr 12 15:11 go.d.plugin
[root@d28c32151328 plugins.d]# 
```

Reasoning:
1. We don't want broad permissions to the plugins. Only people with authoritative access should have permission to run this plugin for any reason
2. We always run with a user that has either user or group permissions, so no need for "other" permissions. When we run as root, we establish the netdata:netdata (or root when netdata not possible) and when we run as simple user we have user/group to the user's user/group information so netdata should not be affected by this change.  Also the users won't be affected. When i am root, i am authorized to execute the plugin and when i have installed as simple user i again have permissions

**Comment by paulkatsoulakis** [comment]
For the sake of clarity, i am resolving this as won't fix and will create new issue that will incorporate the adjust of permissions to be 0750 for all plugins, as concluded from the overall discussion in here
