### ISSUE TITLE
AWS Kinesis as backend collector

### ISSUE THREAD

**Issue by irvintim** [netdata/netdata#5596]
##### Question summary
I am wondering if there has been any work in pushing netdata streams to an AWS Kinesis data stream.
##### OS / Environment
AWS
##### Component Name
backend or streaming
##### Expected results
Sending JSON blobs to Kinesis data stream with appropriate authentication headers and metadata as data is collected.

**Comment by cakrit** [comment]
Let's see how much interest there is from the community for this one first. Adding a new backend isn't a trivial task. Adding an intermediate layer that uses some of the available [resources](https://aws.amazon.com/kinesis/data-streams/resources/) could be an alternative, but at first glance I don't see anything in languages that are built for high performance with low resource utilization, except for the [C++ library](https://github.com/awslabs/amazon-kinesis-producer). On the other handk not using one of those resources would make the implementation much harder.

**Comment by irvintim** [comment]
Thanks for the response, so we've been talking about this and looking at the docs and code and think that we can probably tackle this, in one of 2 ways -- and are hoping you might be able to provide some guidance for these questions:

1. If we were to try to push the "streaming" netdata to kinesis, we could accomplish this perhaps thorugh a local proxy that listens for netdata streams and outputs the stream to kinesis.  What we'd be interested in reviewing is the protocol that is used between streaming netdata servers, is that documented?

2. The other option, which might be better (easier to implement) or worse (less scalable), is to use the JSON backend and push that data at the 1 second granularity to kinesis.  JSON streams are a natural for Kinesis to ingest, so it should be easy get the data there.  But I'm wondering if there is a reverse to the backend process that will take JSON docs and turn that data back into netdata data for processing and streaming by a backend netdata server.

Maybe I should also step back and explain what our goal is:  we would like to have many thousands of netdata collectors (many ephemeral, but others within long lasting physical servers) they will be scattered all over the Internet and we need a way to stream that data into a centralized place in an elastic/scalable manner.  We won't have the option of putting netdata proxies or other collectors in location to aggregate those streams, so we want a funnel at the edge that can accept the data at whatever rate it comes in and caches that until we can process it.  We also want to ensure that no data is lost, and that all data is processed.  Kinesis is an ideal scalable collector of streaming data.   In addition to having this data-stream fed back into internal netdata servers, the stream will also go into a backend datalake for other  for other processes to handle.

Thanks for any insights you can provide.

**Comment by cakrit** [comment]
I would advise against trying to work with the streaming prototocol, it's internal and we are certain to make changes to it. It's only meant to be used between netdata instances.

I would suggest a variant of the architecture shown in the diagram [here](https://docs.netdata.cloud/streaming/#archiving-to-a-time-series-database), possibly with more masters. 

Here are some options:

1. Local clusters pushing metrics to one netdata master per cluster, each master pushing to Kinesis
![netdata-scale](https://user-images.githubusercontent.com/43294513/54877912-37e4aa80-4e25-11e9-89dc-90ae69097c05.jpg)

The only issue with such a set up is that the stream from the slaves to the masters is not encrypted, so you may want to consider using a VPN with encryption. This applies to other options that have slaves sending to a master over the internet. 

2. Local netdata proxies, pushing to a single master, which then pushes to kinesis (the single central master is optional of course, but does provide benefits* and could also be added to option 1).
![netdata-scale2](https://user-images.githubusercontent.com/43294513/54878195-93189c00-4e29-11e9-83dd-7fabdf63fc7f.jpg)

3. All slaves pushing to a single master, which pushes to kinesis
![netdata-scale3](https://user-images.githubusercontent.com/43294513/54878198-99a71380-4e29-11e9-958e-1a0cf5dcf92c.jpg)

4. All slaves pushing to a single master and also to kinesis.
![netdata-scale4](https://user-images.githubusercontent.com/43294513/54878201-a592d580-4e29-11e9-9b3d-7229d5e4542a.jpg)

One confusing think in all of this is that you said
> We won't have the option of putting netdata proxies or other collectors in location to aggregate those streams

But your option 1 says that you can have
> a local proxy that listens for netdata streams and outputs the stream to kinesis

This last sentence describes precisely what a netdata master can do for you. So what makes the custom local proxy you are considering different, so that it can be collocated, when a netdata master can't? Our architecture for kubernetes works very similarly, with one ephemeral headless collector per cluster node and one stateful netdata master aggregating the metrics in a persistent volume. All of them are in the same cluster and we don't need to worry about encryption of the slave to master data stream. 

* Some benefits of having a single master: Can do all health checks and produce alarms centrally, can choose to have persistent storage only there (reducing resource requirements elsewhere).

**Comment by irvintim** [comment]
Thanks for these suggestions.  My overall concern with this architecture is the lack of elasticity in having the netdata masters at the top of the funnel, this is why we are looking at kinesis since it's "infinitely" scalable.  What we are trying to build is basically #3, but with the master inside the kinesis (basically just swap master and kinesis on that diagram and you have what we are trying to accomplish.)  Our assumption is that netdata masters have a finite amount of data they can ingest, and kinesis can ingest the data streams at whatever rate we throw at them, this data is then available to be pushed into a netdata master (or other processes) at the rate that it can handle.  We won't have to worry about losing data if the master is overloaded.  (Plus as you mentioned the netdata stream isn't encrypted, so that is another point in favor of this architecture.) 

I think I'm convinced at not trying to use the netdata stream itself (but instead deliver the JSON backend feed to kinesis), most of this will be fairly simple to accomplish (if your code was C++ it would be slam dunk easy since there is a C++ AWS SDK -- I think we'll just write out own Kinesis C library functions based on libcurl instead of trying to do a C -> C++ wrapper, but that's TBD).  The challenge with this is how to convert the JSON back into netdata consumable info.  That's what I'll have to look at next.

I really appreciate all the suggestions!  I'll be happy to share what we come up with.

Tim

**Comment by irvintim** [comment]
Sorry to keep bugging you guys, but I just read in the issue stream that you are thinking of integrating with h20 which would give you Websockets capability out-of-the box.  Is that still on the roadmap?  If so, then we can use the AWS API Gateway to stream a Websockets stream to Kinesis with no additional work, that would be my number 1 option if that is coming soon.

I looked at the JSON output from the backend and it seems almost complete, the one bit of data that is missing are the graph setup details.  So if I wanted to push that data back into netdata I'd be missing those initialization components.  I have a feeling that is my problem to solve, but just thought I toss it out there in case there is an easy flag to flip on that might add that extra data.

**Comment by cakrit** [comment]
@irvintim you're not bugging us. You have identified really important issues that we definitely want to resolve, because we also want to be infinitely scalable. The big difference between netdata and your normal cloud services is that we will always leverage the monitored infrastructure itself. So we actually WANT to keep the data distributed on many servers that users already have on the field, so that they don't need to pay huge infrastructure costs to cloud providers. Our design for the netdata cloud doesn't put any master servers anywhere, except to cater for ephemeral containers. Even then, we would never expect to have a single master database, we'll put the logic necessary to give users a holistic view on netdata cloud and the browser UI. I think Peter Levine has described the benefits of such an approach very well [here](https://a16z.com/2016/12/16/the-end-of-cloud-computing/). 

Going back to helping you plan what you'll be doing. 
- Do NOT try to push all that data to netdata yourself. Seriously, don't try. You'd essentially be attempting to write a super-collector that will take you a very long time and is guaranteed to have performance issues itself. If you MUST have a single netdata master, then consider one of the other suggestions, or a variation of them. 
- The migration to H2O and libuv hasn't started yet, we'll be looking at it probably in Q4 '19. It still won't resolve the issue of possible gaps in the metrics, as a master netdata treats the slaves as data collectors and always gets the last values. 
- @vlvkobal has already started looking into the required changes to support Kinesis as a backend, he should be able to assist you to create a PR to add support for it to netdata. 

I don't think I've missed any of your questions, let me know if I have. 
If I were you and I really had to have all data collected in a single master, I'd go for option 4. I really wouldn't worry about scalability, just give that master netdata cpu and memory it needs to have enough data for the last few hours, so you can have it calculating the alarms. Your main limitation is memory vs history stored and our new Database that will take care of that is coming in early May. We'd love to have a use case like yours with that new DB, so we can kick it in the teeth early on. :)

**Comment by vlvkobal** [comment]
@irvintim could you test #5914?

**Comment by irvintim** [comment]
Awesome, thank you so much for putting this together. I'll try to schedule
some testing time for a little later this week.

**Comment by irvintim** [comment]
Here is a copy of the comment I left in the PR:

Vladimir,

Thank you for creating this. JSON data is streaming to our Kinesis stream from our test instance, so that is working well. I'll let it run for a few days, and will toss some additional data at it to see how it scales.

I have a few suggestions and an issue.

ISSUE:

Following the AWS C++ SDK installation instructions to build and install this library, it by default installs the shared library in /usr/local/lib64/. Netdata can't find the library there out of the box, so I had to do the following before running netdata:
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib64
Since this is the default location for this library, this should be added to the library path that netdata searches if kinesis is activated?
SUGGESTION:

I'd suggest changing "auth key id" to "aws_access_key_id" and "secure key" to "aws_secret_access_key" in the config (and perhaps throughout the code). This is the standard nomenclature in the aws config files.
Along those lines, I'd suggest making the auth key and secret key optional, since the SDK will obtain those credentials via a standard method if they aren't provided on the client class constructor -- see https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/credentials.html
Thanks again! This is super helpful.

Tim
