### ISSUE TITLE
Ensure that `jq` is available in netdata installations 

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#5621]
##### Feature idea summary
To get the cgroup names for k8s, we introduced the use of the `jq` command in #5576. 
As @ktsaou commented there:
> We should probably do something about the `jq` command to make sure it is installed with netdata.
I mean, to be installed by `kickstart.sh` and `netdata.spec`.

##### Expected behavior
Ensure `jq` will be there when used.

**Comment by paulkatsoulakis** [comment]
After discussing again with @cakrit and @ktsaou, we decided that is not a good idea to enforce jq existence. The main reason is the fact that in the centOS flavour, we would have to install epel-release to get jq installed, which is not a good idea for our installer to do so.

For the current time being, we will adjust the runtime, so that when jq is not available we will emit an error to our logs and inform our user that this particular functionality that requires jq can't run.
That way we leave it up to the user's decision to install jq if he wants that functionality to work
