### ISSUE TITLE
notify package maintainers of the new netdata releases

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#5682]
I'm using the latest netdata release that's available as a FreeBSD package, which is 1.11.0_rolling

As  far as I can see that's still the newest available: https://www.freshports.org/net-mgmt/netdata

I can try a manual install from source to see if that makes a difference

_Originally posted by @WoLpH in https://github.com/netdata/netdata/pull/5670#issuecomment-474783086_

___ 

From what i heard it is done manually, we need to automate the task.

I guess we need a special mailing list.

i would like to have input from @paulfantom on this.

So:
 - ensure that [package-maintainers](https://github.com/netdata/netdata/tree/master/packaging/maintainers#package-maintainers) list is up to date
 - notify package maintainers in an automated way

**Comment by paulfantom** [comment]
System already exists and it is provided by GitHub. Package maintainer can "Watch" this repo and track "Releases Only". It is up to maintainers to use it.

**Comment by ilyam8** [comment]
That is the point. @cakrit

**Comment by paulkatsoulakis** [comment]
Hello,
   @ilyam8 I am assuming you have in mind the automation of the freshports update, so that it doesn't have to be triggered by our users?

**Comment by cakrit** [comment]
It's not certain that the maintainer monitor our releases, as you can see in https://repology.org/project/netdata/versions

It's in our interest to notify them, as several distros are far behind.

**Comment by ilyam8** [comment]
@paulkatsoulakis i am just saying that `It is up to maintainers to use it` (our current) approach have its own drawbacks (see OP) and it seems we need something more robust in addition.

**Comment by paulfantom** [comment]
It is up to package maintainer to track development of software they are packaging. Community maintainers don't work for you and they are doing it in free time, so you cannot force them to do anything (sending notifications is a mechanism to put pressure). 
What you can do is clearly communicate what is going on in the project regarding build system, advertise new releases more, have a release schedule and wait. Or just package it yourself.

**Comment by paulkatsoulakis** [comment]
1) We are in the process of offering packaging ourselves, on top of what our precious community already does for us
2) We are working on our web presence and cloud offering, that among other things it includes forums and announcements so that we can get closer to our community
3) Pawel was right that maintainers can indeed "watch" our releases from github and get notified

I think we can call this resolved. Indeed we can't put pressure on people who voluntarily support us, but we need to strive instead of doing things for them and keep them up to date with our on going work.
