### ISSUE TITLE
Chart name includes job name in some cases

### ISSUE THREAD

**Issue by ionuttocila** [netdata/netdata#5696]
##### Question summary
I am using netdata into production and all apache charts have a name like "apache.bytesperreq", where apache is module name (python plugin) and bytesperreq is the chart. 

When I install netdata on ubuntu 18.04 on local machine (mac os x) into a docker container, the chat name is "apache_local.bytesperreq".

This breaks some of my custom plugins because I don't have a consistent way to get the chart from netdata master using the original chart name + job name.

There a rule when _local is added to chart name?

##### OS / Environment
ubuntu 18.04

##### Component Name
apache python module

##### Expected results
chart name to be "apache_local.bytesperreq" for all situations where jobname is "local"

The same issue applies to all python plugins

**Comment by ilyam8** [comment]
hey @alteringres 	

> chart name to be "apache_local.bytesperreq" for all situations where jobname is "local"

https://github.com/netdata/netdata/blob/71e4d0a764124bd80c936d1683688cc97c11dc58/collectors/python.d.plugin/python_modules/bases/charts.py#L123

https://github.com/netdata/netdata/blob/71e4d0a764124bd80c936d1683688cc97c11dc58/collectors/python.d.plugin/python_modules/bases/FrameworkServices/SimpleService.py#L90-L93

___

```yaml
job_name:                  # job name
  override_name: new_name  # override name
```

if job has `override_name` then chart name is `plugin_name_override_name.chart_name`, otherwise `plugin_name_job_name.chart_name`.

If job has no *_name or job_name == module_name, then chart name is `plugin_name.chart_name`.

**Comment by ionuttocila** [comment]
@ilyam8  thank you for your time and answer.

**Comment by ilyam8** [comment]
Thanks, do you have any other question?

If not i think we can close the issue.
