### ISSUE TITLE
Feature: Netdata alarms as POST events to a configurable endpoint in health_alarm_notify.conf

### ISSUE THREAD

**Issue by jeremyjpj0916** [netdata/netdata#5702]
##### Feature idea summary

Simple request: I would like the ability to give an endpoint such as (http||https://my-api-service.com/netdata/alarms that Netdata will send a POST json body to in the event that alarms are triggered, I prefer this to email route so I can build application logic around some of the alarms we see and it will just give a cleaner programmatic approach.  This means that alarms have to have some sort of standard JSON structure we can model POJO's(plain old java objects) or model any object in your language of choice to parse the alarm data and act on it.

This also requires documenting the structure of the alarm netdata will send, which I currently see no such json/yaml structure outlined anywhere.

The existing conf of netdata alarms reads like the system already can use underlying curl, so it sounds like we are close to being here already, we just need to allow custom integration of our own endpoints as opposed to these vendor app notification systems with a public data structure format of all netdata alerts. 

Lastly the log level for events worthy of having POST events sent should be configurable as well, for instance in prod I want CRITICAL events only to keep noise down and such. 

Edit - I am also aware of the api endpoints we can scrape alarm data off of too, but I rather write a listening app that waits on netdata pushes to send me details than polling a given endpoint every __ seconds.

##### Expected behavior

Alarm starts going off in netdata, it sends a json body post request to an endpoint every time it triggers, to which we can take action on from an application ingesting those POST requests.

**Comment by cakrit** [comment]
You are already able to do that, by definining a `custom_sender` function. Search for custom_sender in `health_alarm_notify.conf`, it contains instructions and a list of all the parameters you can use. 

Let's keep this as a request to add the same info to the docs.

**Comment by jeremyjpj0916** [comment]
@cakrit That is awesome, and I see that you have a pending PR for the documentation as well. Still a bit confused on what a real life example of this config would be:

In alarm-notify.sh in plugins.d I do see:
```
# custom configs
DEFAULT_RECIPIENT_CUSTOM=
declare -A role_recipients_custom=()
``` 

I see in the health_alarm_notify.conf the custom section near the bottom as well:
```
# custom notifications
```
In here I don't see a place to configure my URL API Service the custom notifications will send to?

Why would a recipient need to be populated in the event of alert data being posted to a service endpoint? And what should it be populated as? Can you give me an example of what a basic config in  ```health_alarm_notify.conf```` would look like where it points to a URL service you host and has picked out a few of the variables you describe in your doc too as a custom notification block as well as what a recipient gets set to in these situations?

**Comment by cakrit** [comment]
Just take a look at the various `send` functions in https://github.com/netdata/netdata/blob/master/health/notifications/alarm-notify.sh.in

You will be writing your `send_custom` function inside `health_alarm_notify.conf`, so you can do anything you like. You'll essentially replace the existing `send_custom` there, to do a call to your endpoint. The only trick is that DEFAULT_RECIPIENT_CUSTOM can't be empty, otherwise `send_custom` won't be called.  If all you need is a single endpoint, you can put it in that variable, though I'd keep it simple and say DEFAULT_RECIPIENT_CUSTOM=default. You can then hard-code your endpoint URI into your function. No one else will see it. 

Just make sure you copy `health_alarm_notify.conf` to your `/etc/netdata` (or wherever the config directory resides in your system), so that your changes don't get overwritten when you update netdata.
