### ISSUE TITLE
netdata/packaging/build: Build getting broken sporadically at times in py2-psycopg2 package

### ISSUE THREAD

**Issue by paulkatsoulakis** [netdata/netdata#5713]
##### Bug report summary
We have sporadic build failures at py2-psycopg2 . 

Here's the end of the log with the details of the error

```
(41/54) Replacing gdbm (1.13-r1 -> 1.13-r1)
(42/54) Replacing sqlite-libs (3.26.0-r3 -> 3.26.0-r3)
(43/54) Replacing python2 (2.7.15-r3 -> 2.7.15-r3)
(44/54) Replacing mariadb-connector-c (3.0.8-r0 -> 3.0.8-r0)
(45/54) Replacing py-mysqldb (1.2.5-r1 -> 1.2.5-r1)
(46/54) Replacing py-psycopg2 (2.7.5-r0 -> 2.7.5-r0)
(47/54) Replacing py-egenix-mx-base (3.2.9-r0 -> 3.2.9-r0)
(48/54) Replacing db (5.3.28-r1 -> 5.3.28-r1)
(49/54) Replacing libsasl (2.1.27-r1 -> 2.1.27-r1)
(50/54) Replacing libldap (2.4.47-r2 -> 2.4.47-r2)
(51/54) Replacing libpq (11.1-r0 -> 11.1-r0)
(52/54) Replacing py2-psycopg2 (2.7.5-r0 -> 2.7.5-r0)
[91mERROR: py2-psycopg2-2.7.5-r0: failed to rename usr/lib/python2.7/site-packages/.apk.e6a4129270b3b99b221d1dbc3289eb2ec9dd67d2f0113746 to usr/lib/python2.7/site-packages/psycopg2-2.7.5-py2.7.egg-info.
[0m(53/54) Replacing py-yaml (4.1-r0 -> 4.1-r0)
(54/54) Replacing py2-yaml (4.1-r0 -> 4.1-r0)
Executing busybox-1.29.3-r10.trigger
Executing ca-certificates-20190108-r0.trigger
1 error; 99 MiB in 60 packages
fetch http://mirrors.polyverse.io/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://mirrors.polyverse.io/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/1) [APK unavailable, skipped] Reinstalling py2-psycopg2 (2.7.5-r0)
1 error; 99 MiB in 60 packages
The command '/bin/sh -c if [ "$(uname -m)" == "x86_64" ]; then         curl https://sh.polyverse.io | sh -s install gcxce5byVQbtRz0iwfGkozZwy support+netdata@polyverse.io;         apk update;         apk upgrade --available --no-cache;         sed -in 's/^#//g' /etc/apk/repositories;         apk fix py2-psycopg2;     fi' returned a non-zero code: 1
travis_time:end:1a5b5934:start=1553612453881497060,finish=1553612545608492052,duration=91726994992
[0K[31;1mThe command "./packaging/docker/build.sh" exited with 1.[0m

Done. Your build exited with 1.
```

##### OS / Environment

```
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```

##### Netdata version (ouput of `netdata -V`)
latest

##### Component Name
netdata/packaging/ci: Alpine build

##### Steps To Reproduce
Unfortunately i can't propose reproductive behaviour as i haven't identified the pattern

##### Expected behavior
The build should not break

**Comment by paulkatsoulakis** [comment]
@archisgore Could you please have a look and let me know we can deep dive on this?

**Comment by archisgore** [comment]
Looking...

**Comment by paulkatsoulakis** [comment]
FWIW if i just retry the process it works. So it seems like a non-regular issue, but i can't figure out what triggers it. Let me know if you need further details from the run

**Comment by paulkatsoulakis** [comment]
Hello @archisgore, any news? Is there any way i can help you with this?

**Comment by archisgore** [comment]
I'm sorry. I had a weird other fire to put out. I'm on this today top priority. I'm working on a repro now. Will post status updates here.

**Comment by paulkatsoulakis** [comment]
Hello @archisgore, any news?

**Comment by cakrit** [comment]
@archisgore you are aware that we've been facing intermittent failures since we started using Polyverse in our docker image. Can we please have a fix and some kind of assurance that we won't keep facing these issues in the future?  We are debating disabling the feature, until things become more stable. We appreciate what Polyverse does, but I'm sure you understand that we can't go on like this. We'd be happy to have a call on the matter, if you believe it will help us better understand what's happening.

**Comment by archisgore** [comment]
@cakrit and @paulkatsoulakis I totally understand. I'm sorry for being quiet on the thread. I'm working to repro this. This absolutely cannot continue.

Just so you know, while the current fix is for the `py2-psycopg2` package, we're fully aware any random package can have broken reinstall triggers, and can cause this. So we've got a parallel investment (including fixing the issue in APK upstream) track to ensure you won't face this forever.

You're not being unreasonable here. Intermittent upstream bugs are a bit annoying since they take so long to repro. I'm sure once I do have a repro, I'll have a fix ASAP.

Can you point me to a URL of a failed Travis build with this error - perhaps the full log will shed some light for me. In the meantime, I'm checking out the history too.

**Comment by archisgore** [comment]
I began with this `Dockerfile`:

```
FROM netdata/base:amd64
  
# Conditional subscribiton to Polyverse's Polymorphic Linux repositories
RUN if [ "$(uname -m)" == "x86_64" ]; then \
        curl https://sh.polyverse.io | sh -s install gcxce5byVQbtRz0iwfGkozZwy support+netdata@polyverse.io; \
        apk update; \
        apk upgrade --available --no-cache; \
        sed -in 's/^#//g' /etc/apk/repositories; \
        apk fix py2-psycopg2; \
    fi

```

And built it a bunch yesterday. Works each time.

**Comment by archisgore** [comment]
I'm looking at failed builds under this:
https://travis-ci.com/netdata/netdata/builds

I saw every failed build in the past 12 days and couldn't find the failing alpine container packaging job. Where else can I look? I think a full log will help me.

**Comment by paulkatsoulakis** [comment]
Hello @archisgore, you 're in luck. It just happened on my forked repository, yesterday.
here's the log, i removed the verbose netdata installation part to reduce the noise.

[build_log_failing.txt](https://github.com/netdata/netdata/files/3025458/build_log_failing.txt)

**Comment by archisgore** [comment]
Here's the three remedies we're taking right away:
1. I've submitted a PR
2. We're going to blacklist the `py2-psycopg2` package in our repos (so it won't be served)
3. We've found the offending issue in upstream APK and are looking at fixing it in Alpine.

**Comment by archisgore** [comment]
I've now knocked out (1) and (2) from the list above and actively working on (3) upstream.

1. ~~I've submitted a PR~~
2. ~~We're going to blacklist the py2-psycopg2 package in our repos (so it won't be served)~~
3. We've found the offending issue in upstream APK and are looking at fixing it in Alpine. - In progress.

**Comment by paulkatsoulakis** [comment]
Hi @archisgore thanks for attending the issue with priority.
Why you remove psycopg2? Is there an alternate package that can cover us (transparently ideally)?

I am asking this because from what is see we have dependencies on psycopg2, removing that package will break parts of python tooling

**Comment by archisgore** [comment]
@paulkatsoulakis Sorry for the confusion.

1. I removed the package from `apk fix` because it is no longer reinstalled.

2. We removed the package from Polyverse repositories which act as mirrors, in front of upstream APK repositories.

So the package will work perfectly and get installed from Alpine just fine, only that it will not get reinstalled with a scrambled version from us, and thus avoiding the failure it triggered during reinstall.

**Comment by paulkatsoulakis** [comment]
> @paulkatsoulakis Sorry for the confusion.
> 
> 1. I removed the package from `apk fix` because it is no longer reinstalled.
> 2. We removed the package from Polyverse repositories which act as mirrors, in front of upstream APK repositories.
> 
> So the package will work perfectly and get installed from Alpine just fine, only that it will not get reinstalled with a scrambled version from us, and thus avoiding the failure it triggered during reinstall.

Ok makes sense now :))

**Comment by paulkatsoulakis** [comment]
Thanks for your prompt responses and handling of the issue @archisgore 
I will close this issue as soon as we hear from you the results on point 3: "We've found the offending issue in upstream APK and are looking at fixing it in Alpine. - In progress."

**Comment by paulkatsoulakis** [comment]
Hi @archisgore are there any news around this issue?
Is there an ETA for the last remaining item?

**Comment by archisgore** [comment]
@paulfantom I'm down with a flu/cold so I'm just moving really slow. I'll need till end of the week - this shouldn't block anything for you though.

**Comment by archisgore** [comment]
Just so you know, we've filed an upstream bug: https://bugs.alpinelinux.org/issues/10201

And we're going to track the fix there. I'd say this is safe to close. We've figured out root cause pretty accurately now, and are looking at long term fixes in Alpine.

**Comment by archisgore** [comment]
Also to close out the complete root cause and what we've done to fix it:
1. The bug posted on Alpine basically states that when you update a Package from V1->V2, if V1 had a directory called `/FooBar`, but V2 has a file called `/FooBar`, then the rename function fails (it cannot rename a file into what was previously a directory.

2. Why did this happen? Because upstream Python packages are compiled in an environment which has the package `py-setuptools` installed. Our automated build system downloads dependencies as the package manifest or APKBUILD files contain. This was not a dependency.

Now here's what happens, when you build a python package such as `py2-psycopg2` without that package installed, the Python Egg is generated as a single `.egg-info` file. When that package is installed, then it is generated as a `.egg-info` directory.

So Upstream Alpine created a directory with the name `py2-psycopg2-2.7.5.egg-info` whereas the Polyverse version of the package created a file with the same name.

This compounded with (1) causing the rename to fail, causing APK to go into a bad state.

We're fixing (2) on our end so this will never happen again. BUT, what if upstream changes the build environment in the remote future? That's why we're also offering to fix (1) in Alpine, and that'll be a while since this is our first code contribution.

Definitely let me know if you have any questions or followups. And thank you again for giving us a chance to remedy this. I really appreciate the patience.

**Comment by paulkatsoulakis** [comment]
seems like you have it under control, i am resolving this for now and we 'll re-iterate if we face any problems again. Thanks for the support @archisgore
