### ISSUE TITLE
How can i set syslog facility for netdata daemon?

### ISSUE THREAD

**Issue by iredmail** [netdata/netdata#5717]
According to netdata doc, netdata daemon can send log to syslog, and it works fine. But how can i set the syslog facility? Which parameter name should i use? I tried to search 'facility' in github repo, no parameter found.

```
access log = syslog
error log = syslog
debug log = syslog
```

**Comment by cakrit** [comment]
It's hard-coded in https://github.com/netdata/netdata/blob/master/libnetdata/log/log.c#L26 
It's very easy to make it configurable, but there are 24 facilities I see, so it will need some lines to be able to accept all of them. Is there a subset that would make sense to support?

**Comment by Ferroin** [comment]
> Is there a subset that would make sense to support?

We by definition can't support the `kern` facility (at least, on any sane syslog platform we can't support it) because messages sent there by users get converted to another facility (usually `user`, but not always).

Other than that, I see no practical reason to restrict what facilities we support.  Some of the facilities may not make sense to use (`auth`, `mail`, `uucp`, etc), but that doesn't mean they make no sense for everybody.

**Comment by iredmail** [comment]
I think it's ok to just let sysadmin set the one he/she want.
Usually i use `localX` (X is 1-7).
