### ISSUE TITLE
How to save performance data for an ephemeral container for later visualization

### ISSUE THREAD

**Issue by f18m** [netdata/netdata#5732]
##### Question summary
I create containers for automatic testing of my application... they are created and destroyed automatically.
I would like to use netdata to save data about performances of my test container, and be able later on to inspect that performance data.
A more detailed example of what I would like to do is:
 a) start netdata in some configuration; point it to the my just-created LXC container 
 b) save the graphs of CPU/memory used by the container, as collected by netdata, in an HTML standalone file that I can store together with testing results obtained from the LXC container

I tried to use the JSON backend and then simply spin a netcat server:

 nc -l 5488 > mycontainer.json

but I don't have any idea how to generate a nice graph later from that JSON file...

Thanks!

##### OS / Environment
Linux (Ubuntu/Centos)

**Comment by cakrit** [comment]
There are two parts in this:
- Write a collector so that you can convert your JSON to charts. You want to start [here](https://docs.netdata.cloud/collectors/plugins.d/) and then select a language you are comfortable with, to write your collector (Go, Python, node.js, bash). All of the plugins have instructions and examples, so you can start by copying an example, or something else that you see is close to what you're doing. 

- Dynamically discover endpoints to collect the data from. Right now, the logic needs to reside in your collector. So it has to somehow know what to query and then iterate through these endpoints to generate charts for each of your containers. You want  to use each container's identifier to fill in the [family](https://docs.netdata.cloud/docs/charts/#families) field of a chart, because you'll probably have multiple charts for each instance of your application. 

Keep asking questions as you move forward, there are people here who can help you a lot if you get into trouble.

**Comment by f18m** [comment]
Hi @cakrit ,
thanks for the fast answer!!

Regarding the collector: I actually thought to use the cgroups plugin already present:
   https://github.com/netdata/netdata/tree/master/collectors/cgroups.plugin
My idea would be to (automatically, using the testing framework I'm using) set 
  " enable by default cgroups matching = /lxc/name-of-my-container"
inside netdata.conf, and then start netdata.
Do you think that this could work?

I however don't know/understand how to export historical data (the container stays alive for a few minutes so I'm planning to actually save a very short netdata trace) directly plotted or in a format that I can plot later.

I also looked into the OpenTSDB option but I still don't understand how to actually graph the data once I get that into OpenTSDB (or Graphite or whatever)... should I use Grafana?
Is there no simpler option that allows me to just "screenshot" a few minutes of CPU/memory benchmarks for later visualization?

Thank you so much!

**Comment by ilyam8** [comment]
@f18m you are right, you need to export data to some tsdb and graph it using, for example, Grafana.

**Comment by f18m** [comment]
Hi @ilyam8 ,
I think the 
   netdata -> OpenTSDB -> Grafana
chain is optimal for real-time monitoring of large systems but I wonder: is there any faster option to just get a self-contained graphical representation of CPU/memory usage other than that?

I'm looking into a simpler tool like "nmon":
  http://nmon.sourceforge.net
which simply produces a small trace file and then provides an utility to produce an HTML page from that with a few (detailed) CPU/memory/disk/network graphs... something like that (just cgroup-aware) would be nice for me... thanks!

**Comment by cakrit** [comment]
If you really need something that simple, then disable all the collectors you don't want and increase the `history` to keep the few metrics you will have left for as long as your server's memory allows you to (it will be a lot). The [configuration guide](https://docs.netdata.cloud/docs/configuration-guide/) can guide you to the documentation to do it. If not, we'll improve it :)

**Comment by f18m** [comment]
Ok, thanks for all replies!
I will see what I manage to do. I'm closing this issue for now, thanks.
