### ISSUE TITLE
Process uptime

### ISSUE THREAD

**Issue by hamzash9500** [netdata/netdata#5757]
Hi All,

can the netdata represent uptime for a specific process such as uptime for nginx?
if this feature is not available, can be added to the next release.

Thanks advance,
Hamza

**Comment by ilyam8** [comment]
Disscussed with @vlvkobal 	

 - process uptime = `current time - /proc/<pid> mtime` 
 - process name = `/proc/<pid>/comm`

**Comment by hamzash9500** [comment]
please any update .
@ilyam8

**Comment by ilyam8** [comment]
@hamzash9500 no updates, the feature is low priority. It will be implemented eventually tho.

**Comment by donets420** [comment]
Well, process uptime is important metric. In my case I need to find different monitoring solutions, not netdata unfortunately.

**Comment by alpes214** [comment]
@cakrit @ilyam8 @vlvkobal 

I would like to confirm with you the following approach for implementing this functionality:
- this will be python.d module **proc_name**
- the config will contain parameter **names** with the list of processes names for monitoring
- during initialization module will read configuration, load pids for configured process names, generate self.order and self.definitions
- calculate process uptime according to the comment above `current time - /proc/<pid> mtime`. This will be done during initialization as well.
- on _get_data recalculate uptime and send data to netdata parent process

**Comment by ilyam8** [comment]
@alpes214 i think it is more complex.
I am not a specialist, but i think that there is no guarantee that `process_name` has same `pid` on next iteration and in theory there are 2 options:
 - `pid` is not exist (process restarted for example)]
 - `pid` exist but it is `pid` of other `process`

And i think `python` is no go for this, currently all stuff that reads `/proc` is implemented in `c`.

**Comment by alpes214** [comment]
@ilyam8
> I am not a specialist, but i think that there is no guarantee that process_name has same pid on next iteration
Yes, this is true. I missed possibility of the process restart during monitoring. In this case process pid will be changed.

The possible place for C implementation is apps.plugin. And the possible solution is to use libuv file system events handling for /proc/<pid>

**Comment by ilyam8** [comment]
> The possible place for C implementation is apps.plugin.

Apps plugin monitors groups of processes (matched by defined simple pattern). I think we shouldnt add matching **specific process logic** to it because it is not his job. I may be wrong here but that is what i think.

**Comment by cakrit** [comment]
That's the difficulty with the apps plugin. Grouping processes is fine for cpu, RAM etc, but when we talk about uptime, it doesn't make much sense. If we're talking about using `libuv` file system events, it sounds like a different C collector anyway, right @alpes214 ?

**Comment by cakrit** [comment]
I'm thinking about what the goal would be here. If it's events like start/restart that we are really looking for, then a chart isn't exactly useful here.  With a chart, even if we find an efficient way to collect and present data for all running processes, we would end up seeing charts with constantly increasing values, some of them so small compared to others, that they would be invisible, until you select a specific process from the chart legend. That doesn't sound like a useful chart. 

I also considered the "table chart" described in #3086 and that's on our roadmap. That would give you a ps-like view, with the uptime in a column. Again, probably not the most useful way to present information, if what we're interested in is identifying issues with process starts/restarts.

I believe that what we want here is the event timeline we've began to describe in #6523. If we display process-related events in a timeline synched with the charts, we'll have a much more useful and actionable representation.

**Comment by alpes214** [comment]
> If we're talking about using libuv file system events, it sounds like a different C collector anyway, right @alpes214 ?

@cakrit  yes, creating separate C collector with libuv is one option. Another option is (*probably*) to call libuv from python. Calling libuv from python will require additional dependency and I am not sure about performance. However this dependency might be usefull for other cases. I need some time to look over the existing code deeper.

> I'm thinking about what the goal would be here. If it's events like start/restart that we are really looking for, then a chart isn't exactly useful here. 

Yes, there is already one chart that shows uptime as a constantly increasing value. It is not nice, but it is usefull to see when measurements were started/stopped/interrupted etc. So I though you keep it because of this information. I will check issues that you mentioned and will come back.

**Comment by Saruspete** [comment]
Hello,

For what is worth, I did a small python plugin for this kind of usage, as apps.plugin wouldn't match the needs.
My requirements were to monitor specific groups of processes: 
- re-discover process to monitor every X seconds
- for each of these group, graph their memory usage (vsz, rss), their per-cpu consumption, number of threads & scheduling class, 
- for each group, the number of process that are up

I also tried to graph the PIDs of monitored process, but that was not relevant as too hard to get alerts on it easily. We could see restarts, but it left a dead dimension behind. And as the dimensions changed, upon restart the old values were mangled.


Also, as stated by @ilyam8 the logic on "what process to monitor to what group" is very custom and dependant. Can be a regex, a pid file, a name... very different for each usage. 
The effort of providing many configuration features for matching would be much more useful elsewhere. So I guess a python + libuv + python logic for maching would be the best way here.

Main issue are indeed related to CPU consumption, as drifts / lags in the tight-loop between CPU-Wide ticks and per-thread ticks generates fluctuating values, instead of a steady line.

**Comment by vlvkobal** [comment]
I discussed the issue with @ilyam8 and @mfundul. The idea is to utilise the apps plugin for collecting and displaying process uptime information. Tracking pids doesn't make sense, so the existing process grouping based on process names is OK. Four charts would be useful:
- group uptime (the period in which at least one process was running)
- minimum uptime (of the process with the shortest time running)
- average uptime
- maximum uptime (of the process with the longest time running)

In conjunction with the number of processes in the group, which is already displayed by the apps plugin, it should be enough for tracking process uptime in most possible cases.

**Comment by cakrit** [comment]
What's the difference between the group uptime and the maximum uptime here? For the group uptime we'll be keeping a virtual uptime for the entire group and as long as any process in the group is running we increment it ourselves? Where do we store that uptime then?

**Comment by mfundul** [comment]
> 
> 
> What's the difference between the group uptime and the maximum uptime here? For the group uptime we'll be keeping a virtual uptime for the entire group and as long as any process in the group is running we increment it ourselves? Where do we store that uptime then?

I guess it would be stored in the same place as min,avg,max. Maybe something like this:
- first process in group: get timestamp
- are there processes in group? : group-uptime = current - timestamp

**Comment by vlvkobal** [comment]
> For the group uptime we'll be keeping a virtual uptime for the entire group and as long as any process in the group is running we increment it ourselves?

Correct.

**Comment by ilyam8** [comment]
i think group uptime logic is:

find all processes in the group

if any and group uptime is 0:
 - get max uptime among all processes
 - group uptime = max uptime
elif any:
 - group-uptime += update_every
else:
 - group-uptime = 0
