### ISSUE TITLE
fresh install of ubuntu 18.04.1 and netdata missing no "read" showing up in Disk

### ISSUE THREAD

**Issue by nexusofdoom** [netdata/netdata#5817]

**Comment by nexusofdoom** [comment]
![image](https://user-images.githubusercontent.com/16519553/55692173-07dff000-596b-11e9-9160-98b721f8b041.png)

**Comment by nexusofdoom** [comment]
netdata 1.9.0

**Comment by nexusofdoom** [comment]
netdata was installed with apt-get install 

is there a way to update vs the apt-get update ?

**Comment by cakrit** [comment]
Well, [this page](https://repology.org/project/netdata/versions) suggests that you can only have up to v1.9.0 in Ubuntu 18.04. I suggest you uninstall from the package manager and use our [one-line installation](https://docs.netdata.cloud/packaging/installer/#one-line-installation).

**Comment by paulkatsoulakis** [comment]
Hi @nexusofdoom, Has the above instructions helped you solve your problem? For the near future we plan to provide our own repository so that package management fans can enjoy the latest netdata software in time, with zero effort. More details on issue #5963 

In the mean time i will be resolving this issue, as it has been idle for too long.
If you still facing issues, we 'd be happy to help! All you have to do is reopen the task and let us know how we can be of assistance, cheers!
