### ISSUE TITLE
USB thermometers supported?

### ISSUE THREAD

**Issue by NetwarSystem** [netdata/netdata#5828]
I have some machines in a mixed office/warehouse environment in a climate where summer temperatures can hit 46C. Conditioned temperatures range from 21C to 32C depending on time of day and how many people are coming/going.

I've been lobbying for a separate "cool room", both for heat and dust control, but it's not been approved yet.

I see there are a bunch of different OEM versions of TEMPer USB thermometers in the $15 range on Amazon. I did a few searches and I am surprised there are no quick results showing Netdata supporting something like this.

Is there an inexpensive environmental monitor that is already supported?

**Comment by PanosJee** [comment]
I guess it's not in the scope of the project to support such peripherals. I guess you could write some code and use the statds plugin to feed netdata the values. [This](https://www.balena.io/blog/build-an-environment-and-air-quality-monitor-with-raspberry-pi/#deployingthesoftware) tutorial by @chrisys  could serve as a good starting point, just skip influx for netdata.

**Comment by NetwarSystem** [comment]
The software will collect thermal data for the processors, and it appears it will for my Nvidia card, too. Seems to me ambient air temperature would be a common point of interest for anyone tracking those things, especially for remote systems.

Is the dividing line that it must be software/inside the box?

**Comment by ktsaou** [comment]
Hi, no there is no such line.

netdata will automatically collect information for all sensors that are reported by lm-sensors.

The lm-sensors module overlaps with the charts.d.plugin (bash) sensors module, that collects sensor information directly from /proc. Only one of them should be enabled at a given time. Try disabling python.d.plugin/lm-sensors and enabling charts.d.plugin/sensors. It may solve your problem.

If your sensors are not supported by lm-sensors, and are not exposed in /proc sensors, but you can somehow collect their values via console access, it would be extremely easy to write a bash module for netdata to collect data from USB sensors (check charts.d.plugin, there are many examples).

We welcome PRs. If you build a new data collection module for netdata, please make a PR so that the community can benefit from your work.

**Comment by ilyam8** [comment]
> Try disabling python.d.plugin/lm-sensors and enabling charts.d.plugin/sensors. 

 - uncomment and set `sensors` to `no` in [`python.d.conf`](https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/python.d.conf)
 - uncomment and set `sensors` to `force` in [`charts.d.conf`](https://github.com/netdata/netdata/blob/master/collectors/charts.d.plugin/charts.d.conf)
 - restart `netdata`
