### ISSUE TITLE
Implement CPU limits for cgroup v2

### ISSUE THREAD

**Issue by vlvkobal** [netdata/netdata#5850]
##### Feature idea summary
Thanks to the work @skrzyp1 have done in #5407 netdata supports cgroup v2. As far as cgroup v2 provides cpu.max, CPU limits should be implemented.

##### Expected behavior
cgroups plugin shows CPU limits for cgroup v2.

**Comment by skrzyp1** [comment]
@vlvkobal I have to find a way to enable this controller on my machine. I will try to investigate and possibly implement this next week.

**Comment by Ferroin** [comment]
I'm still a bit confused as to why it's believed that it makes sense to track this.  It's a CPU bandwidth limiting parameter that is functionally read-only on the kernel side (the kernel will _NEVER_ change it, it only reads the value the user sets), standard usage involves setting it once at cgroup creation and then never changing it, and the few rare cases where it is adjusted dynamically at runtime by whatever is managing the cgroup change it so slowly that it just doesn't make sense to graph at the timescale Netdata operates at.

**Comment by vlvkobal** [comment]
The reason is to use `cpu.max` for calculating the percentage of the cgroup cpu usage relative to an allowed cpu bandwidth, to have a gauge with a useful upper limit, and to set a corresponding health variable and use it in alarms.

**Comment by skrzyp1** [comment]
Here is WiP PR https://github.com/netdata/netdata/pull/5895
Reading cpu limits works, however it behaves weirdly on charts when limits are changed (there are peaks).
After first limit change chart fluctuates instead of being straight line.
Probably reading values goes out of sync with each other.
![Screenshot from 2019-04-19 00-45-04](https://user-images.githubusercontent.com/10044651/56396091-9858e300-623d-11e9-91f6-aa7f3ccff415.png)
I don't know if this behavior also occurs in cgroups-v1and if its problem / something to be fixed.

**Comment by vlvkobal** [comment]
For cgroups-v1 you'll also have a spike on the chart when you have lowered a CPU quota. This behaviour was chosen because scheduler can't limit CPU consumption precisely, so it is possible to have CPU load over the limit. Instead of cutting the over-limited values and hide from a user the actual information we consented to allow some weird spikes on the chart. 

Also, because of the scheduler behaviour, the higher quota you set, the fewer fluctuations you get.

**Comment by skrzyp1** [comment]
I removed WiP code and changed reviewed lines. Should be ready to merge.
I was thinking if cpu cores number is something that changes during runtime.
In memory limits logic [here](https://github.com/netdata/netdata/blob/master/collectors/cgroups.plugin/sys_fs_cgroup.c#L3034) we cache ram total number into static variable, maybe we should also do it for cpu cores instead of invoking `get_system_cpus` for each update?

**Comment by vlvkobal** [comment]
Theoretically, the number of CPU cores can change at runtime. So it's safer to invoke `get_system_cpus` on every update.

**Comment by vlvkobal** [comment]
Thank you @skrzyp1 for your work! 👍
