### ISSUE TITLE
Netdata does not monitor Docker Containers running

### ISSUE THREAD

**Issue by raigarcia** [netdata/netdata#5861]
Netdata is not able to get data from docker containers that running on my environment. 

Weird is that on some servers Netdata is able get informations from all the containers that are running, but in others servers he can't.

![image](https://user-images.githubusercontent.com/30247941/56055717-9c15d280-5d30-11e9-862a-af4593296e8b.png)

In this image we can see Netdata getting data from the containers that are running perfectly.

**Comment by ilyam8** [comment]
Hi @raigarcia

> Netdata is not able to get data from docker containers that running on my environment.

I see you are talking about `dockerd` collector.

In order to get it running you need python docker package v3.2.0+
https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/dockerd/README.md

If you installed and collector is not working i suggest:
 - check netdata error.log
Restart netdata service;wait a bit; `grep dockerd error.log`

OR

 -  run `python.d.plugin` in debug mode
https://docs.netdata.cloud/collectors/python.d.plugin/#how-to-debug-a-python-module

___

And check `docker_engine` collector, it shows number of running containers too
https://github.com/netdata/go.d.plugin/tree/master/modules/docker_engine

**Comment by raigarcia** [comment]
Hello @ilyam8 

Thanks for your reply. My currently docker package is 2.7.0, I have to upgrade to v3.2.0+.

**error.log:**

2019-04-15 13:42:18: python.d ERROR: dockerd[local] : installed 'docker' package version 2.7.0, minimum required version 3.2.0, please upgrade

How can I upgrade it ?

Thanks.

**Comment by ilyam8** [comment]
> My currently docker package is 2.7.0, I have to upgrade to v3.2.0+.

Then it is still not upgraded. Check what version of python is netdata uses (2 or 3). You need to update docker package for appropriate python version.

That is how you can check docker python package version yourself using ppython interpreter:



```python
import docker

print(docker.__version__)
```

**Comment by raigarcia** [comment]
Got it ! Tks @ilyam8. Please, you can close this issue.

Thanks for your help.
