### ISSUE TITLE
how to view monitored applications on master netdata

### ISSUE THREAD

**Issue by makutamatey** [netdata/netdata#5874]
I am monitoring zookeeper and kafka on a netdata slave. The slave is directly connected to the master and even though the master is receiving streams from the slave I cannot see the zookeeper and kafka on the master.  Is there a way I can see the applications being monitored on master ?

**Comment by cakrit** [comment]
To see the slave's metrics you actually need to select the slave from the top left menu. For example, to see the metrics streamed from the slave called "fedora" below, I have to select it from that menu. Otherwise, you only see what the master collects (in the example below, that's metrics from "chris-msi").

![Screenshot from 2019-04-17 09-18-34](https://user-images.githubusercontent.com/43294513/56286941-52a3f980-611b-11e9-9b98-0eaa9eb79306.png)

**Comment by makutamatey** [comment]
After reading the docs I got the impression that netdata aggregates the streams from all the slaves and display them on the dashboard. So looking at the Application section or the users section of the master I should see all the apps being monitored by the slaves.

**Comment by makutamatey** [comment]
From the "my_data" menu on a current slave I can reach all the other slaves  if I am logged in. But if that is how the master also works then do you think I need a master?

**Comment by makutamatey** [comment]
Please bear with me. I am new to this tool. I want to understand it and recommend it to my company because it is a great tool. Thank you for the quick response so far. I am grateful.

**Comment by cakrit** [comment]
I wasn't able to respond earlier. The master has a lot of uses and gives you a great deal of flexibility, especially when you have a lot of ephemeral nodes. Viewing all the slave data by accessing only the master GUI is one of the uses, streaming data to a long term storage from a single point (just the master) is another, getting alerts only from one server instead of many is a third and I'm sure people use it for more than that. e.g. in our default kubernetes set up, it's only the master that actually stores the metrics, the slaves just collect them and forward them. Let us know if you need any more help and don't apologize, providing help is what we're here for! :)
