### ISSUE TITLE
Installation does not work 18.04.2 LTS (Bionic Beaver)

### ISSUE THREAD

**Issue by PauloBoaventura** [netdata/netdata#5875]
It is with regret that I open this call.
Well, I was very happy with the project.
I tried several times and several tutorials and unfortunately I could not succeed.

My Machine:
NAME: Ubuntu
VERSION: 18.04.2 LTS (Bionic Beaver)
ID: ubuntu
ID_LIKE: debian
VERSION_ID: 18.04

We detected these:
Distribution: ubuntu
Version: 18.04
Codename: 18.04.2 LTS (Bionic Beaver)
Package Manager: install_apt_get
Packages Tree: debian
Detection Method: / etc / os-release
Default Python v: 2

WARNING
package autoconf-archive is not available in this system.
You may try to install without it.

 > Checking if package 'zlib1g-dev' is installed ...
 > Checking if package 'uuid-dev' is installed ...
 > Checking if package 'libmnl-dev' is installed ...
 > Checking if package 'python-yaml' is installed ...
 > Checking if package 'python-pymongo' is installed ...

-------------------------------------------------- ------------------

Autoconf-file is installed but it does not recognize ...

Well, to summarize a process over 6 hours.
It installs but I can not access.
And in the logs ...
I have several issues with Plugins, which are already on the server as NGINX and NOde.js

Very similar to the reported case = https://github.com/netdata/netdata/issues/3844#issue-333424777

I hope they solve it quickly because it causes great inconvenience.
And it seems to be only minimal errors of re-discovery.

**Comment by paulkatsoulakis** [comment]
Hi @PauloBoaventura, it is with great regret that i hear you had to spent hours on setting up netdata. We are doing great efforts to provide a zero-hustle default setup, so i will try to help you out and understand what went wrong, so that we can improve our platform too.

Let me repeat your problems you mention and please confirm if i understood them correctly.
1. You noticed a warning about package `autoconf-archive` that is not correct because the package is already on the system, yet the installation completed successfully.
2. Even though the installation is successful, you cannot access the URL.

Are these the two problems reported indeed?
Now, i will need the following information from you, if that is possible:

1. Provide me with the complete netdata installation log in question and the commands you executed to run the install.

2. Can you tell me whether netdata is running on the system after the installation process finishes? do the following:
    a) Check if the service is up (a simple `ps -ef | grep netdata` would do)
    b) Check whether port 19999 is open and bind on any IP (`netdata -na | grep 19999` should do the trick). If you have changed the port number, just grep the respective port.
    c) if you do a `wget -O netdata.page.html 'http://localhost:19999'`, is the html in netdata.page.html the expected netdata page?

Thanks!

**Comment by paulkatsoulakis** [comment]
Hi @PauloBoaventura it seems that you probably no longer interested in this issue.
I will resolve it for now as the issue has been idle for too long.

If this case remains a problem to you and you need your assistance, we 'd be happy to pick up the discussion were we left it off. 
You can just reopen the issue and provide the feedback we need to continue our analysis, so that we can give the right answer.

See you soon!

**Comment by PauloBoaventura** [comment]
Hello, sorry for the delay in answering ...
I've been busy and I just saw your email today. Thank you for answering me ... I'm happy ...

Well, I'll explain all my procedure ...
And we keep in touch to resolve ...
(Even if it takes time to respond)

Well, after these errors I ended up removing it from the server.
I will install it as soon as possible and I will publish the whole process, which detailed above ... ok ...
