### ISSUE TITLE
[RFC] Chart name duplication

### ISSUE THREAD

**Issue by vlvkobal** [netdata/netdata#5883]
##### Bug report summary
There is a problem with chart naming. If names are not provided explicitly, charts are named automatically using chart IDs. The issue is that due to troubles of handling special characters in JavaScript names are 'normalised' in a way that any non-alphanumeric character except "." is converted to "_". So, if names differ in the special characters only, core routines consider them as duplicates, and it leads to visualization problems.

The question is how to treat chart names in a better way.

The start of the discussion is [here](https://github.com/netdata/netdata/issues/5829#issuecomment-482827946).

An example of charts with "bad" names:
```
		{
			"id": "segfault.random-1",
			"name": "segfault.random_1",
			"type": "segfault",
			"family": "random",
			"context": "random",
			"title": "A random number (segfault.random_1)",
			"priority": 90000,
			"plugin": "python.d.plugin",
			"module": "segfault",
			"enabled": true,
			"units": "random number",
			"data_url": "/api/v1/data?chart=segfault.random_1",
			"chart_type": "line",
			"duration": 3996,
			"first_entry": 1555533504,
			"last_entry": 1555534370,
			"update_every": 1,
			"dimensions": {
				"random1": { "name": "random1" }
			},
			"green": null,
			"red": null,
			"alarms": {

			}
		}
```

```
		{
			"id": "segfault.random_1",
			"name": "(null)",
			"type": "segfault",
			"family": "random",
			"context": "random",
			"title": "A random number ((null))",
			"priority": 90001,
			"plugin": "python.d.plugin",
			"module": "segfault",
			"enabled": true,
			"units": "random number",
			"data_url": "/api/v1/data?chart=(null)",
			"chart_type": "line",
			"duration": 3996,
			"first_entry": 1555533504,
			"last_entry": 1555534370,
			"update_every": 1,
			"dimensions": {
				"random2": { "name": "random2" }
			},
			"green": null,
			"red": null,
			"alarms": {

			}
		}
```

![image](https://user-images.githubusercontent.com/22008543/56312526-fbbd1500-6158-11e9-8852-212e5a0aeb0b.png)

##### Component Name
core netdata

##### Expected results
Charts with subtly different names are displayed and transferred to backends correctly.

**Comment by vlvkobal** [comment]
@jacekkolasa please look if we can solve the problem on the frontend side. If it's possible, we'll get rid of symbol replacing in core Netdata.

**Comment by jacekkolasa** [comment]
@vlvkobal cc @ilyam8 can we instead extend the set of allowed characters in chart name? I've tested how Agent Dashboard works with `-` in name, and it's working ok, i can for example see both `segfault.random_1` and `segfault.random-1` with different variables, if i'll do:
```
if(c != '.' && !isalnum(c) && c != '-')
```
in this line https://github.com/netdata/netdata/blob/6c2bab0543ee8df1df0ef4b4f4633841f6de9d7f/database/rrdset.c#L127

**Comment by ilyam8** [comment]
@jacekkolasa the question is do we really need to replace other characters? Why? If so we need to document it.

**Comment by jacekkolasa** [comment]
@ilyam8 i am just being defensive here. If the issue is only the `-` vs `_` sign problem, then perhaps easiest and safest solution would be just to add support for `-`. It will work on FE side without any changes. But of course we can talk about allowing other characters, but do we need that? If yes, we'll have to do a little more research. So for i've seen that we would need to escape `&`, `#` and `%` characters when doing `data?chart=chart.name` call. I've tested it and BE is properly doing unescape.

Important is the fact that adding this escape/unescape change to dashboard.js could cause problems in the cloud - because there's a possibility that old dashboard.js will be working with newer Netdata server. That's the problem we have to solve somehow...

Another thing: `=` sign is not working on Agent side, as i see - if i have a chart name: `example.qwerty-r!@=foo`, from `api/v1/charts?` endpoint i'm getting `charts["example.qwerty-r!@"]` chart

**Comment by jacekkolasa** [comment]
I agree about the documentation part, we'll have to write down the characters that chart name can support

**Comment by ilyam8** [comment]
Well, `-` is a very specific case, it doesnt solve the problem in general. The problem is 

```c
if(c != '.' && !isalnum(c)) 
```

this behaviour is undocumented.

> easiest and safest solution would be just to add support for -

Unfortunately it is kind of breaking change, it will change chart label value in export.

@jacekkolasa we are trying to understand and make restrictions clear.

**Comment by jacekkolasa** [comment]
Thanks, so i think that restriction were made to prevent problems with those api calls i mentioned. It would be better to escape characters properly when doing calls, but right now we cannot do it because it would break that `chart label value in export` you mentioned and also it would break some cloud configurations. 🙁

We'll be able to fix the cloud problem someday if we'll be running it from iframe

**Comment by ilyam8** [comment]
so, if we 

> escape characters properly when doing calls

we will be able to remove that mangling func completely?

**Comment by jacekkolasa** [comment]
Yes, if:
- there will be no breaking changes on the Agent, like the one you mentioned:
> it will change chart label value in export.

- we'll fix the problem with `=` on Agent side
- i'll do more tests for other characters. But there's no sense to do that now, because of those problems with breaking changes, right? Also don't you think that we should have the normalising function anyway, just make it less restrictive?

**Comment by amoss** [comment]
The current status seems to be that we are still discussing this issue to pick a good way to move forward:

* We can remove the restriction on the FE for `-` without any problems in the javascript.
* If we change the mangling behaviour then it will break existing installations (as chart names will change).
* This breaking change will be observable on the exporting interface.
* We do not currently have a good process for making breaking changes and communicating them to users.

Current options for fixing the bug seem to be:
1. Change the mangling set and allow `-`  -> this causes us a process problem in the release.
2. Making the mangling set configurable  -> this over-complicates the code.
3. Decide not to fix it  -> it already causes problems in some configurations.
4. Put in an error message for illegal characters but continue to use them -> this just hides the problem in the logs.

**Comment by cakrit** [comment]
The easiest thing to do that will be backwards compatible is to force the collectors to only send the allowed characters, in the first place. If we allow more characters, we need to take into consideration the allowed format for all different exporters as well. I suggest we ensure that we can accept and properly handle in the FE all valid characters in the prometheus and openmetrics exporting formats. What are they?
