### ISSUE TITLE
netdata environment var with path to python.d dir

### ISSUE THREAD

**Issue by donets420** [netdata/netdata#5908]
Hi all,
i am working on script, which will modify mongodb.conf.   
So I need to define absolute path to python.d dir - does netdata have any env variable with path to python.d dir?

**Comment by ilyam8** [comment]
Hi

That is what `pyhton.d.plugin` uses

https://github.com/netdata/netdata/blob/3e53f7d32fe4d35bd9b9f453ebe17dae152cb74d/collectors/python.d.plugin/python.d.plugin.in#L35-L78

___

> i am working on script, which will modify mongodb.conf.

Why? Just curiosity! :smile:

**Comment by paulkatsoulakis** [comment]
Hi @donets420,
  In order to reach the python.d directory, you can read `NETDATA_PREFIX` from `${NETDATA_USER_CONFIG_DIR}/.environment`. On a default installation, NETDATA_PREFIX is empty and NETDATA_USER_CONFIG_DIF is set to /etc/netdata. 

 Once you have NETDATA_PREFIX, refer python.d directory as: `${NETDATA_PREFIX}/usr/libexec/netdata/python.d`
