### ISSUE TITLE
Error in default config

### ISSUE THREAD

**Issue by agc-software** [netdata/netdata#5922]
##### Bug report summary
Netdata Version v.1.14.0-11-nigthly
Comes with the specified values

`web files owner = netdata`
`web files group = netdata`

Which was supposed to be set as ``web files owner = root``
This will result in `Access to file '/usr/share/netdata/web/index.html' is not permitted` under NGINX when using unix domain sockets 

Installed via one-liner curl script, is this intended?

The remedy is as follows: Set `web files owner = netdata` as `root` and `chown /usr/share/netdata/` as `root:netdata`

Related: https://github.com/netdata/netdata/issues/3764
##### OS / Environment
Ubuntu 18.04
##### Netdata version (ouput of `netdata -V`)
Version v.1.14.0-11-nigthly

**Comment by cakrit** [comment]
The way the ownership works is a bit complicated. 
- At install time, the installer first looks in `netdata.conf` section `web` for `web file owner`.
  - If it finds an uncommented line with a value, it uses that for the owner in the `chown` command.
  - If it does not find it, it does the same search in section `global` for `run as user`. 
     - If it finds an uncommented line with a value, it uses that for the owner in the `chown` command.
     - If it does not find it, it uses `netdata`

So the ownership depends on `web/web file owner` and `global/run as user`.

Now, when netdata runs, it seems to do the same thing. First looks for `web/web file owner` and if that's not found, it uses the `pw_name` from `getpwuid(geteuid())`. This should give the user netdata is running as, which comes from `global/run as user`. The relevant function is [here](https://github.com/netdata/netdata/blob/master/web/server/web_client.c#L204).

From what I can tell, we can run into trouble if:
1. Either `web/web file owner` or `global/run as user` is changed manually after the installation. But an update would fix it.
2. netdata is not started as the user in the configuration. 

Now, since you mentioned using a web socket, I remember having to manually `touch` it and `chown` it myself, to make it work, because I run netdata as a different user (`christopher`). I did a small test to try and start netdata from the command line as user root with a unix socket and I actually got this:
```
2019-04-29 12:38:16: netdata ERROR : MAIN : LISTENER: UNIX bind() on path '/run/netdata/netdata.sock' failed. (errno 2, No such file or directory)
```

So a couple questions so we can replicate the exact issue:
- Do you get the problem with all the default configurations? Give us the values of `web file owner` and `run as user` from your `http://host:port/netdata.conf`.
- Is netdata started from systemd with the default config?
- Can you show the ownership and permissions of the unix socket you have configured?

**Comment by paulkatsoulakis** [comment]
It seems that there is no further activity on this issue.
Dear @agc-software i will be closing this issue, but please by all means do reopen if the above feedback did not cover your questions and you have the required input @cakrit requested so we can try to further analyse your issue.

Again, thank you so much for staying in touch with us and we 'll be happy to help if you face any issues or if you have any further questions around netdata

**Comment by donets420** [comment]
Hi all, today, during migration to 1.15 we had the same issue. 
To fix it:
[web]
-    web files owner = {{ netdata_user.name }}
+    web files owner = root

**Comment by paulkatsoulakis** [comment]
> Hi all, today, during migration to 1.15 we had the same issue.
> It was added in this [commit](https://github.com/netdata/netdata/commit/1abb8faa8cba373a530993fea982c92eaf9f176f)
> So the correct config:
> [web]
> 
> * web files owner = {{ netdata_user.name }}
> 
> * web files owner = root

Hi @donets420, my apologies for the late reply on this one.
Could you provide answer @cakrit feedback questions so that we can pick it up?

Quoting the questions again:

```So a couple questions so we can replicate the exact issue:

Do you get the problem with all the default configurations? Give us the values of web file owner and run as user from your http://host:port/netdata.conf.
Is netdata started from systemd with the default config?
Can you show the ownership and permissions of the unix socket you have configured?
```

**Comment by paulkatsoulakis** [comment]
Hello, i 'll be resolving this until we manage to get our hands on some feedback.
@donets420 feel free to reopen once you get the chance to provide us with some more details about the problem you are facing.  Also please answer the questions mentioned above by @cakrit, so that we can drive our troubleshooting to the right direction

Thanks for entrusting monitoring to netdata, talk to you soon, cheers!
