### ISSUE TITLE
[Usability Issue] Automatic docker container names and PGID

### ISSUE THREAD

**Issue by Thann** [netdata/netdata#5924]
##### Bug report summary
according to the docks:
> If you want to have your container names resolved by netdata it needs to have access to docker group. To achive that just add environment variable `PGID=999`

Why cant netdata check the docker.sock groupid and just automatically do this?  If there is no reason then I would be happy to contribute a fix.

##### OS / Environment
Docker

**Comment by paulkatsoulakis** [comment]
Hi @Thann, thanks for your feedback.

The current approach seemed like the straight forward way to avoid complexities when it comes to security (User/Group management, elevated rights on services that will be performing the add/remove and so on). It is not guaranteed that neither the service runtime nor the installer will run with elevated rights that will allow defining permissions, plus not all users would want to have this capability enabled for security reasons, because docker socket access comes with a security concern.

I 'd be happy to see your proposal in a PR though and we can discuss over it further if you like.

**Comment by paulkatsoulakis** [comment]
It seems that our user is no longer interested on this issue.
We 'd be happy to assist with anything further @Thann, i will be closing this issue for now.

If you see that there is anything else that we can support you with regarding netdata, we 'd be happy to accept a new report from you. See you!
