### ISSUE TITLE
HTTPS implementation

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#5943]
##### Question summary
Hello everyone, I am working here with Openssl to bring the HTTPS to Netdata case the user desires, but the Openssl can be used in other fronts inside the Netdata, so I would like to ask you few things about the new OpenSSL configuration options for I make the whole structure that will be useful for all developers, following the doubts:

1) The Netdata already have sections well defined and in my opinion we can define the SSL options like the certified in the [global] section, but SSL is another layer of communication, so we could create another section specific for safety. What is the best option?
2) We already have defined the default port of Netdata to 19999, in normal situation WEB servers have different ports to HTTP and HTTPS. Will we have 2 different ports?  In my opinion it is a good idea to have 2 ports opened.
3) Considering that we agree to have 2 ports. What  port will we will open for the HTTPS requests?
4) This question has direct relationship with the previous. Case we decide to keep both ports opened (one with HTTP and other with HTTPS) the client can send a request to upgrade the connection (Upgrade-Insecure-Requests: 1 ), case this happen, I am thinking to upgrade the connection directly to HTTPS, but we can ignore it too and following without HTTPS. What is your opnion about this subject?
5) I cannot see any possibility for we avoid self signed certifieds by users. Can you give me one?
6) As you could see in my question 4 I cited a header and I am updating soon the parser for requests with a new function to work with this kinds of requests and to fix the issue 4717. Considering that I am already working with the headers, are you needing some feature related with HTTP(S) headers for I prepare?

##### OS / Environment
This will affect all environments including Microsoft when we start it.

**Comment by Ferroin** [comment]
For item 1:

Just put it in the `web` section of the config, that's where most people will look for it anyway, and it doesn't need to be any more complicated than just a few options there.

---

For items 2, and 3:

We let the user decide.  In short, give a separate config option for the port for the encrypted connection and make it possible to disable unencrypted connections.  I don't think we should define a default port for encrypted access though.  I see little to no benefit to running both unless we explicitly allow different path ACL's for encrypted and unencrypted connections, but I can't think of any practical situation where that would make more sense than having a proxy to handle the access control.  People will want support for both though, and they can just decide themselves what port to use for that.

----

For item 4:

I think you have a misunderstanding about what the `Upgrade-Insecure-Requests` header is supposed to do.  it's intended to be a mechanism for the client to request a redirect to the secure version of the site (if one exists), not an HTTP equivalent to the STARTTLS command found in some other protocols.  You may have it confused with the CSP directive of the same name which instructs the client to treate any `http://` URL's for the local domain it encounters in the returned document as if they were instead L's.

---

For item 5.

Unless we want to manage TLS certificates for our users (hint, we don't), we need to support self-signed certificates.  This isn't an issue on the server side, it's only really tricky for the streaming side of things, but that can easily be handled by having an option in the streaming config to accept self-signed SSL certificates.

**Comment by cakrit** [comment]
Let's first clarify that we're only talking about the web server here. We will also need to consider the cases where netdata functions as a client, i.e. streaming and backends, but let's focus just on the first part for now.

For 1 and 5, @Ferroin is correct. 

For 2 and 3, look first at https://docs.netdata.cloud/web/server/#binding-netdata-to-multiple-ports. You will see that we can have numerous ports that netdata could listen to, at the same time, for potentially different uses. I also see limited value in accepting both http and https requests at the same time, but:
- The idea is to not require a proxy just for encryption (authentication/authorization is also coming pretty soon).
- I can think of at least a short period during which we haven't encrypted streaming (i.e. ensured that a netdata slave can encrypt its communication to a netdata master), so we could have a dedicated http port for streaming and have all the other ports be https.
I suggest the following:
- Setting(s) in the `[web]` section enables SSL for all ports defined in `bind to` by default (question @Ferroin : how about unix sockets?) 
- Users can add exceptions to make one or more ports http, by modifying `bind to`. E.g. `bind to = 127.0.0.1=dashboard 10.1.1.1:19998=management|netdata.conf^HTTP` would make port 19998 accept http connections. 

For 4, I'd rather not add such a functionality at all. Since ports can also be attached to ACL and we want to keep supporting multiple ports, deciding where to redirect the client won't be easy. I doubt actually it's even desirable; can proxies handle such redirects without any side-effects?

**Comment by Ferroin** [comment]
> question @Ferroin : how about unix sockets?

They should be left untouched by this.  Data sent over a UNIX socket is functionally secure against anyone who does not have either read access to the socket (which is trivial to manage through regular UNIX DAC mechanisms or whatever MAC system your platform uses) or the ability to bypass virtual memory access protections in the kernel (for example, someone who can read arbitrary physical memory locations), so encryption is just waste of processing power.

> I doubt actually it's even desirable; can proxies handle such redirects without any side-effects?

It depends on the proxy.  Most reverse proxies can't, and most forward proxies don't though, so I think it's safe to say that it would only be useful for people accessing Netdata directly.  That said, it's something that's generally agreed to be a bad thing among security experts because the unencrypted connection can trivially be hijacked to issue a redirect wherever an attacker wants.

---

One other thing to think about:  Do we want to support separate TLS configurations for different ports? 

I can think of only one practical use case for this (using a dedicated internal certificate infrastructure for streaming while using regular certificates for the dashboard), and I don't think it's a likely use case, but this is the time to add it if we want to do so.

**Comment by cakrit** [comment]
Thanks @ferroin, awesome as usual.

**Comment by cakrit** [comment]
> Do we want to support separate TLS configurations for different ports?

We will leave this one aside for now, we will be supporting 1.1, 1.2 and 1.3.

For the configuration, we have the following cases:

- netdata not configured for SSL: We ignore any directives in "bind to" related to SSL and always default to unsecure connections.

- netdata configured for SSL:
  - unix sockets and udp communications: always unencrypted. 
  - tcp sockets for HTTP (most of what the web server does): 
     - No protocol parameter provided in `bind to`. HTTP requests get redirected to HTTPS
     - Protocol parameter in `bind to` is `^SSL=optional` - We accept both HTTP and HTTPS requests
  - streaming sockets (not HTTP protocol)
    - No protocol parameters provided in `bind to` - We accept both insecure and secure requests
    - Protocol parameter in `bind to` is  `^SSL=force` - Ignore and do the previous, until netdata slaves can actually use SSL. After we implement that, only accept encrypted connections.

**Comment by thiagoftsm** [comment]
I do no know whether my solution can have problems with other ACL, I have doubt whether I selected the best place to define the checks for "bind to", but at least it worked for the tests that I ran.

**Comment by thiagoftsm** [comment]
This was merged days ago!
