### ISSUE TITLE
Does reducing the scanning frequency reduce the accuracy?

### ISSUE THREAD

**Issue by kousu** [netdata/netdata#5961]
https://docs.netdata.cloud/docs/configuration-guide/#change-what-i-see says I can adjust `global.update_every` and `global.history` to change how much memory I need and how far back my logs go (and I have and it's great), but I can't find anywhere that explains how that affects accuracy. Does reducing this (to, say, a minute) potentially make me miss information?

For example, if I have bursty traffic with lots of small transfers none of which take longer than a minute, will I completely miss this fact in my logs?

I've figured out the answer might be plugin-specific. I assume the web log reader is smart enough to read the last `n` seconds of logs, but I imagine the loadavg plugin just get the current value and is done with it. I'm especially interested in how the disk and network I/O monitoring is affected and if I can be censoring problems from myself in trying to lengthen my log history.

**Comment by cakrit** [comment]
You are correct of course. In general, you obviously lose resolution when you reduce the sampling rate. Some counters (I think such as data in/out of an interface) are incremental, so you would still see some abrupt changes even with a 1 minute `update_every`, but netdata is meant to be running in 1 sec resolution (in the future we'll go to 1ms). 

People generally prefer keeping a short history with 1 sec resolution and using a [backend](https://docs.netdata.cloud/backends/) for long-term storage. We're very close to releasing a new DB engine that will decouple the required RAM from the retained history, to finally do away with this limitation.

**Comment by Ferroin** [comment]
As @cakrit mentioned, it really depends on the collector.  Overall, one of three things might be the case for any given collector:

* Lower frequency reduces temporal precision, but loses no data.  IOW, you still see everything, but can't tell as precisely when a given spike in the value occurred.  This includes the CPU time counters, disk and network I/O counters, network error counters, and interrupt counters, among other things.
* Same as above, but there's a chance to lose data.  This includes pretty much everything that involves reading log files (they already have a chance to lose data because of log rotation, the chance just gets higher as the collection frequency goes down).
* Lower frequency inherently drops some data.  This includes the load average, disk space, memory usage, CPU frequency tracking, sensors plugins, and most other things where the source doesn't track historical information itself.

The first two cases will also result in small spikes in usage being less visible.  In essence, because each collection period is longer, the 'normal' value for each point will be higher, and short spikes that would otherwise be rather prominent will look smaller in comparison.

**Comment by kousu** [comment]
Thanks so much both of you for the detailed and quick responses!

I think I understand now. Lowering the resolution smooths the data but it shouldn't lose I/O information because the Linux kernel reports that as counters, and you shouldn't lose smartd or nginx weblog information for the similar reason that those are pulling from append-only logs (barring minor `logrotate` glitches). You might lose information in the non-counter metrics, though, like temperature sensors, disk, RAM or CPU utilization?

I guess I just rephrased what you told me. Anyway, proves I get it.

As a followup question, it doesn't make sense to send all metrics to a backend with the same mode right? Counters should be sent as "sum" and RAM with "average"? That's what `send_charts_matching` is for? And if you mix them up you'll be Very Confused?

**Comment by cakrit** [comment]
You understood correctly.

>  it doesn't make sense to send all metrics to a backend with the same mode right? Counters should be sent as "sum" and RAM with "average"? That's what send_charts_matching is for? And if you mix them up you'll be Very Confused?

I haven't played with backends much, but I think you're right that you'll get confused. I'd stick with just "average" or "raw" (as collected), depending on what you want to see. "raw" is the recommended mode for Prometheus. Why don't you just give it a try and change it until you're satisfied?

**Comment by kousu** [comment]
> I haven't played with backends much, but I think you're right that you'll get confused. I'd stick with just "average" or "raw" (as collected), depending on what you want to see. "raw" is the recommended mode for Prometheus. Why don't you just give it a try and change it until you're satisfied?

Ah because I haven't taken the time to set up a backend. I picked netdata because it worked without doing a whole deployment. I like the one-node-one-chart mode.

> People generally prefer keeping a short history with 1 sec resolution and using a [backend](https://docs.netdata.cloud/backends/) for long-term storage. We're very close to releasing a new DB engine that will decouple the required RAM from the retained history, to finally do away with this limitation.

In designing your new DB engine have you taken any inspiration from [rrdtool](https://oss.oetiker.ch/rrdtool/tut/rrdtutorial.en.html)? It seems like they have thought a lot about how to handle fixed-size time series databases, including how to keep but compress older data ^_^

**Comment by cakrit** [comment]
@mfundul can tell you a lot about our dbengine. In the tests we're doing it's already pretty awesome and it will only become better in the following releases. v1.15 will have the first version, optionally enabled.

**Comment by mfundul** [comment]
Our original design is [this](https://github.com/netdata/netdata/issues/4687#issuecomment-458504481). Since this is a huge project we're implementing it in steps. The first step towards the complete solution is [this](https://github.com/netdata/netdata/issues/5303). Some more information in the relevant Pull Request (#5282).
