### ISSUE TITLE
Help me configure streaming the right way

### ISSUE THREAD

**Issue by JessedeJonge** [netdata/netdata#5986]
I am trying to create a master/slave system with Netdata. As a test I am using 'testcontainer' as my master and 'testcontainer2' as my slave. testcontainer has the default Netdata settings and testcontainer2 is configured with a stream.conf the following way:
[stream] enabled = yes, apikey= guuid of testcontainer, destination= ip of testcontainer.

This setup works correctly. Testcontainer 2 shows up at testcontainer (as streamed database). However, the 'statistics' seems to get merged. Whenever I start a stress test on testcontainer2 the dashboard of testcontainer also shows a 100% use of CPU and the other way around. I would like the statistics to be completely seperate of eachother. Is this even possible and how do I configure this?

##### OS / Environment
Linux Ubuntu 16.04 testcontainers via Proxmox

**Comment by cakrit** [comment]
The statistics you're looking at are the host system's stats. To see the container-specific cpu/mem/network stats, you need to scroll down. Find your containers on the right-side menu and you'll see there the separate stats for each container. If you have trouble finding it let us know, otherwise please close the issue.
