### ISSUE TITLE
Support new type of webhooks in Slack notifications

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#6017]
@cakrit I just got the following response:
 
> Thanks for getting in touch about this. Unfortunately, I'm afraid that the issue is due to the fact that app incoming webhooks cannot be overridden to send to specific channels.
> 
> For this use case where you need to be able to send messages to different channels, it would be better not to use an app incoming webhook because those are restricted to a single channel so you cannot override the channel when using this component type.
> 
> Instead, you should use our chat.postMessage API method (https://api.slack.com/methods/chat.postMessage) with a bot token (https://api.slack.com/docs/oauth#using_tokens).
> 
> To start, you need to create a Slack API app (from here: https://api.slack.com/apps), add a bot user, and then install the app which will generate two types of tokens:
> 
> User access token (starts with xoxp-)
> Bot access token (starts with xoxb-)
> It's the second of the above two tokens that you'll need to use. The only issue is that the app bot user needs to be invited to the channels where they will be posting messages.
> 
> In case you're wondering, app incoming webhooks get added at the time that the app is installed and therefore, the channel assignment for that webhook is manually specified by the installing user.
> 

Just wondering what to do now and how you are able to get this to work?

_Originally posted by @JessedeJonge in https://github.com/netdata/netdata/issues/6003#issuecomment-492356505_

**Comment by cakrit** [comment]
We need to support both the legacy incoming webhooks that require the installation of the [Incoming Webhooks App](https://slack.com/apps/A0F7XDUAZ-incoming-webhooks) and the new way of creating incoming webhooks, as documented [here](https://api.slack.com/incoming-webhooks#enable_webhooks).

One way to do this, is to add a new, optional parameter in `health_alarm_notifications.conf`, that will tell us to use the channel-specific webhooks, created via the instructions at https://api.slack.com/incoming-webhooks#enable_webhooks. We could alternatively have a special word that can go to SLACK_WEBHOOK_URL, to indicate the mode. 
When we are in the 'new' mode, the webhook URLs will need to appear in `DEFAULT_RECIPIENT_SLACK`, or in the roles. The send method will ignore any channel specifications. 

One thing to investigate is whether it's still possible with the new webhooks to send a notification to a specific user. If it is, then the solution becomes a bit more complex. 

I think that this is a nice first issue for anyone willing to pick it up, you only need bash scripting knowledge.

**Comment by parthjoshi2007** [comment]
Instead of implementing this as webhooks, could you please look at implementing this using the `chat.postMessage` API (as mentioned in the message cited in the OP) if it is at all possible so that we do not need to create separate webhooks for each channel we need to post to.

I've also been recently testing the Slack integration out and it seems even with the Legacy webhooks I can no longer post to individual users with `@user` but only to multiple channels. This is not a big deal for our setup but I just wanted to put this information out there in case someone else also faces the same issue since the docs mention that this can be done. Haven't looked into why as yet.

Thank you so much for netdata, It has proved to be a lifesaver for our MongoDB deployments. I don't have the time right now but would love to contribute.

**Comment by cakrit** [comment]
I just repeated the test with the legacy webhook and successfully sent the notification to the user (me).

**Comment by parthjoshi2007** [comment]
I just tested the notifications using the instructions [here](https://github.com/netdata/netdata/tree/master/health/notifications#testing-notifications) and realized that the notifcations were trying to post to a Slack channel `#@user`. It turns out that I had an older version of netdata and upgrading it did the trick. Tho it seems a little weird to me that netdata is set up to automatically upgrade when installing using the default script and yet my netdata version was too old.

Anyways, it is working now so thanks again.

**Comment by cakrit** [comment]
The [current functionality](https://docs.netdata.cloud/health/notifications/slack/#slack) has resolved the issues we had in previous versions.
