### ISSUE TITLE
How to understand the rate of statsd's counter?

### ISSUE THREAD

**Issue by ramonli** [netdata/netdata#6019]
> The application sends name:value|c, name:value|C or name:value|m, where value is a positive or negative integer number of events occurred, statsd reports the rate and the number of times it was updated (events).

[The document](https://docs.netdata.cloud/collectors/statsd.plugin/#metrics-supported-by-netdata) here mentions that statsd will report the **rate** and the number of events. I really got confused by the **rate**, seem no any further documents explain this concept. My question is how stats calculate this rate? 

For example, I send a single metrics like below:
`echo "foo:10|c" | nc  10.160.1.2 8125`

and then query the data api(http://10.160.1.2:19999/api/v1/data?chart=statsd_counter_foo.counter&after=-200&before=0&points=200&group=sum&gtime=0&format=json&options=seconds,jsonwrap), the returned result will give me to points:
`[ 1557910236, 4.187377, 0.4187377],`
`[ 1557910235, 5.812623, 0.5812623],`

The 1st element should be timestamp in seconds, but how to explain the other two elements? and why I send a only single metrics, but the data API return two data points?  

I really have did some research, just got no answer. pls help.

**Comment by cakrit** [comment]
netdata will interpolate all values at second boundaries.it's impossible to send your value on the exact second, so you see it split between two second bucket, with the sum equal to what you send. 

Regarding the rate: That sentence is not very well written. It's referring to the [sampling rate](https://docs.netdata.cloud/collectors/statsd.plugin/#sampling-rates) that you can pass. I don't personally understand very well how people use it, but the effect of the following was to see the value multiplied by 10:  
`echo "foo:10|c@0.1" | nc localhost 8125`

```
 "labels": ["time", "counter", "events"],
    "data":
 [
...
      [ 1557920846, 94.03019, 0.9403019],
      [ 1557920845, 5.969812, 0.0596981],
```

It looks like I got pretty close to the exact second 1557920846 in this particular request, which is why you see 94% of the value I sent in one bucket and only 6% in the other.

**Comment by ramonli** [comment]
Thanks
