### ISSUE TITLE
prometheus metric names in 1.15

### ISSUE THREAD

**Issue by donets420** [netdata/netdata#6072]
Hello netdata team,
it already was discussion [#5527](https://github.com/netdata/netdata/issues/5527) about changing prometheus metric names.
I didn't find information about any changing in release notes for netdata 1.15, but I am afraid that I will lost any metrics in prometheus after upgrade to 1.15.
Do you have any list of changing regarding prometheus metric names?
 Thanks in advance!

**Comment by cakrit** [comment]
Apologies @donets420 , we have a test script that we haven't included in our lifecycle tests. I'll run it and see what has changed and why.

**Comment by cakrit** [comment]
The tests are on a small sample of all metrics (just 94), because we can't have all metrics on a single server (too many collectors). From the ones that are monitored, I noticed no general change on the metrics format.
 
@vlvkobal The following are no longer there: `ip_tcp_accept_queue_total`, `ip_tcp_accept_queue_packets_persec_average`. Was `ip_tcp_accept_queue` removed?

So @donets420 it's definitely not the case that all metrics are lost, at least not on my installation. Can you investigate a bit more and provide more details on what you see?

**Comment by ilyam8** [comment]
@donets420 is just asking if there any changes or not.

**Comment by donets420** [comment]
I am trying to understand that.
The problem for me here - I am using netdata as source for prometheus in production. I didn't install 1.15 to production yet.

**Comment by cakrit** [comment]
Oh, I see, thanks @ilyam8 . I was thrown off by the `I will lost`. So the answer is no, there are no changes in the structure of the metrics. We always add new metrics and we don't specify them one by one in the release notes. Let's just get the answer on the `ip_tcp_accept_queue` here and we can close it then.

**Comment by donets420** [comment]
Well, I have checked diff 1.14 and 1.15 on few servers in production zone. The different is in chart name. In general it's not critical for me.

**Comment by vlvkobal** [comment]
Nothing has changed in `proc_net_netstat.c`
