### ISSUE TITLE
[feature] collect active processes limit

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#6133]
#6116 uses hardcoded maximum number of active processes (default actually).

it is configurable value, we could collect it and calculate system active processes usage % and warn user based on it.

some info from @apardyl 

> Yes, we can do that. We would probably also need to read /proc/sys/kernel/threads-max - pid_max is the max PID that can be assigned, threads-max is the actual limit of threads/processes (by default higher than pid_max, but can be set lower that it), at least if I understand http://man7.org/linux/man-pages/man5/proc.5.html correctly.
I'm not sure if this is needed - 32768 processes is quite a number, I don't think many users get close to it on a single (virtual)machine. I can implement this as well, I see it would require adding one or two (if we want to check threads-max) new files to monitor to the proc.plugin.

___

Expected behaviour:
 - collect active processes limit and add it as a cvariable to the `system.active_processes` chart.
 - use collected value as limit.

**Comment by cakrit** [comment]
`active_processes` is in `collectors/freebsd.plugin/freebsd_sysctl.c` and `collectors/proc.plugin/proc_loadavg.c`
cc @vlvkobal

**Comment by Ferroin** [comment]
@apardyl is mostly correct, except that threads on Linux functionally have to have an assigned PID, so the highest possible PID value (the value listed in `/proc/sys/kernel/pid_max`) is a hard limit regardless of the maximum number of threads, while the `threads-max` file functionally places a hard limit on how many threads a single process can create.  So, the correct thing to track here is the max PID, not the max number of threads.

Also, just for the record, 32768 is only a lot of processes on small systems averaged over the long-term.  Because of that whole 'each thread must have a PID' thing, it can be really inadequate on large systems doing large scale parallel computation (or _lots_ of pthread-based asynchronous I/O).  Even on smaller systems though, it may not be unusual to get close to that limit.  When sitting idle, my laptop has about 1.2k assigned PID's at any given time, and it's not unusual for it to go above the 10k mark at times.  Also, it's not unusual for admins to bump up the max PID to mitigate the issues that could arise from frequent reuse of PID's.

**Comment by mfundul** [comment]
> 
> 
> @apardyl is mostly correct, except that threads on Linux functionally have to have an assigned PID, so the highest possible PID value (the value listed in `/proc/sys/kernel/pid_max`) is a hard limit regardless of the maximum number of threads, while the `threads-max` file functionally places a hard limit on how many threads a single process can create. So, the correct thing to track here is the max PID, not the max number of threads.
> 
> Also, just for the record, 32768 is only a lot of processes on small systems averaged over the long-term. Because of that whole 'each thread must have a PID' thing, it can be really inadequate on large systems doing large scale parallel computation (or _lots_ of pthread-based asynchronous I/O). Even on smaller systems though, it may not be unusual to get close to that limit. When sitting idle, my laptop has about 1.2k assigned PID's at any given time, and it's not unusual for it to go above the 10k mark at times. Also, it's not unusual for admins to bump up the max PID to mitigate the issues that could arise from frequent reuse of PID's.

In my experience `threads-max` is the maximum number of threads in linux kernel and depends on physical memory, like it's described [here](https://stackoverflow.com/questions/344203/maximum-number-of-threads-per-process-in-linux).

**Comment by Ferroin** [comment]
@mfundul You're correct, I was mistaken about `threads-max`, though my comment about `pid_max` still being a limiting factor stands.

Given that, Netdata should probably look at both and only list the lower of the two.

**Comment by Ancairon** [comment]
I digged a little into the processes.conf file and figured I would try and alter it to calculate percentages. Here is what I came up with (for the linux os part):

```javascript
   alarm: active_processes_limit
      on: system.active_processes
      os: linux
   hosts: *
    calc: $active
   lookup: average -2s percentage of used
   units: %
   every: 5s
    warn: $this > 85
    crit: $this > 95
   delay: down 5m multiplier 1.5 max 1h
    info: number of active processes
      to: sysadmin
```
Will this work or it will still be hardcoded cause I use `used`?

Excuse me if I'm wrong, I am kinda new here🙂
