### ISSUE TITLE
Send to two backend

### ISSUE THREAD

**Issue by katsil** [netdata/netdata#6136]
##### Question summary
Hello. Guys, can someone help me please?
Is there any way to configute netdata sending metrics to 2 backends instead of one. I mean i want to send metrics to opentsdb and graphite simultaneously.

What i`m expecting:
```
[backend]
	# host tags =
	enabled = yes
	# data source = average
	type = graphite <<<--- type = graphite opentsdb  (like 2 destination hosts)
	# destination = localhost
	# prefix = netdata
	# hostname = superhub-x-clear
	# update every = 10
	# buffer on failures = 10
	# timeout ms = 20000
	# send names instead of ids = yes
	# send charts matching = *
	# send hosts matching = localhost *
```
Is there any way to do that? Or i cant? 
##### OS / Environment
Ubuntu 18.04
##### Component Name
Netdata.Backend
##### Expected results
Allowing to send netdata metrics to 2 backend

**Comment by cakrit** [comment]
The request is to be able to send to two different *types* of backends from a single netdata instance. 
It can't be done by just parsing the `type` config option differently, because multiple hosts can already be configured on `destination` and we'd need to know which backend type to use for which host. 

In fact, looking at how `destination` is defined, it looks like we don't even replicate to multiple hosts of the same `type`, which is strange:
From https://docs.netdata.cloud/backends/#configuration:
 ```destination = space separated list of [PROTOCOL:]HOST[:PORT] - the first working will be used, or a region for kinesis```

The proper way to implement this would be to allow multiple backends to be configured, with all the options in the current `[backend] section`. E.g. for backwards compatibility, expect `[backend]' but also allow `[backend2]`, `[backend3]` etc. 

Right now though, all you can do is [stream](https://docs.netdata.cloud/streaming/) one netdata's metrics to another host and have the second backend configured on that host.

**Comment by katsil** [comment]
wait. 
can on the same host (i mean on this host) use 2 backends like:

```

**Comment by katsil** [comment]
wait. is there any way to do somethink like that: (on the same host without using stream metrics):

```
[backend]
	enabled = yes
	type = graphite 
<...>
```
and the second
```
[backend2]
	enabled = yes
	type = opentsdb
```

**Comment by katsil** [comment]
can i do somethik like that?

**Comment by cakrit** [comment]
No, I said you can't do that today. It's a very nice feature request though, so let's leave it open and we'll put it in the backlog.

**Comment by katsil** [comment]
Okay. So now the only way is to use streaming?
But is this gonna works with 2 netdata`s and 1 stream?

I mean:

netdata1: backend -> opentsdb
netdata2: backend -> opentsdb

both netdata[1,2] pushing their metrics to `netdata-stream` and netdata-stream`s backend -> graphite.

will netdata-stream created folders for each netdata?
i mean this in graphite:
[photo](http://img.superhub.xyz/uploads/big/2ab5080e55aa23cfd880f97b6bb5c7ac.png)

![](http://img.superhub.xyz/uploads/big/2ab5080e55aa23cfd880f97b6bb5c7ac.png)

**Comment by katsil** [comment]
![](https://share.superhub.xyz/download/4e6d63e4499ccb5c6a8fc09e86f8a0fa)

**Comment by katsil** [comment]
![](http://p10.superhub.xyz/XHxYoTvV)

**Comment by vlvkobal** [comment]
Yes, it will create different folders for each host. You can also stream data from both agents to a master netdata and then push metrics to the backend.

**Comment by cakrit** [comment]
https://docs.netdata.cloud/backends/#features : 
> metrics are sent to the backend server as prefix.hostname.chart.dimension. prefix is configured below, hostname is the hostname of the machine (can also be configured).

**Comment by vlvkobal** [comment]
It has been already [implemented](https://github.com/netdata/netdata/blob/master/exporting/README.md).
