### ISSUE TITLE
MacOS Path Issues

### ISSUE THREAD

**Issue by warrenkerrigan** [netdata/netdata#6165]
##### Bug report summary
I am having some issues with netdata paths and system integrity protection on MacOS High Sierra. The application itself is running, however if I attempt to run anything like edit-config, it fails due to incorrect paths.

##### OS / Environment
MacOS High Sierra (10.13.6)
Installed via Homebrew

##### Netdata version (ouput of `netdata -V`)
netdata v1.15.0

**Taken from https://hostname.dom:19999/netdata.conf**
* config directory = /usr/local/etc/netdata
* stock config directory = /usr/local/Cellar/netdata/1.15.0/lib/netdata/conf.d
* log directory = /usr/local/var/log/netdata
* web files directory = /usr/local/Cellar/netdata/1.15.0/share/netdata/web
* cache directory = /usr/local/var/cache/netdata
* lib directory = /usr/local/var/lib/netdata
* home directory = /usr/local/var/cache/netdata
* plugins directory = "/usr/local/Cellar/netdata/1.15.0/libexec/netdata/plugins.d" "/usr/local/etc/netdata/custom-plugins.d"

##### Component Name
Multiple

##### Steps To Reproduce
# Example 1 - edit-config 
If I run `./edit-config` in `/usr/local/etc/netdata/edit-config` I get the following output.

> USAGE:
>   ./edit-config FILENAME
> 
>   Copy and edit the stock config file named: FILENAME
>   if FILENAME is already copied, it will be edited as-is.
> 
>   The EDITOR shell variable is used to define the editor to be used.
> 
>   Stock config files at: '/usr/lib/netdata/conf.d'
>   User  config files at: '/etc/netdata'
> 
>   Available files in '/usr/lib/netdata/conf.d' to copy and edit:
> 
> ./edit-config: line 35: cd: /usr/lib/netdata/conf.d: No such file or directory

If I look inside the edit-config file I can see that it specifies the stock and user file locations. I could manually create a symlink for the user config file directory from `/etc/netdata` to `/usr/local/etc/netdata/`. However the same is not true for the `/usr/lib/netdata/netdata/conf.d`, due to MacOS System Integrity Protection. 

I could disable SIP, but that is not really a desirable solution.

# Example 2 - alarm-notify.sh

If I run the alarm test script by using the following command: 

`/usr/local/Cellar/netdata/1.15.0/libexec/netdata/plugins.d/alarm-notify.sh test`

I get the below output:

> \# SENDING TEST WARNING ALARM TO ROLE: sysadmin
>2019-05-29 15:56:05: alarm-notify.sh: WARNING: Cannot find file '/usr/lib/netdata/conf.d/health_alarm_notify.conf'.
> 2019-05-29 15:56:05: alarm-notify.sh: WARNING: Cannot find file '/etc/netdata/health_alarm_notify.conf'.
> 2019-05-29 15:56:05: alarm-notify.sh: FATAL: All notification methods are disabled. Not sending notification for host 'luxo.canfactory.org', chart 'test.chart' to 'sysadmin' for 'test_alarm' = '100' for status 'WARNING'.
> \# FAILED

> \# SENDING TEST CRITICAL ALARM TO ROLE: sysadmin
> 2019-05-29 15:56:05: alarm-notify.sh: WARNING: Cannot find file '/usr/lib/netdata/conf.d/health_alarm_notify.conf'.
> 2019-05-29 15:56:05: alarm-notify.sh: WARNING: Cannot find file '/etc/netdata/health_alarm_notify.conf'.
> 2019-05-29 15:56:05: alarm-notify.sh: FATAL: All notification methods are disabled. Not sending notification for host 'luxo.canfactory.org', chart 'test.chart' to 'sysadmin' for 'test_alarm' = '100' for status 'CRITICAL'.
> \# FAILED

> \# SENDING TEST CLEAR ALARM TO ROLE: sysadmin
> 2019-05-29 15:56:05: alarm-notify.sh: WARNING: Cannot find file '/usr/lib/netdata/conf.d/health_alarm_notify.conf'.
> 2019-05-29 15:56:05: alarm-notify.sh: WARNING: Cannot find file '/etc/netdata/health_alarm_notify.conf'.
> 2019-05-29 15:56:05: alarm-notify.sh: FATAL: All notification methods are disabled. Not sending notification for host 'luxo.canfactory.org', chart 'test.chart' to 'sysadmin' for 'test_alarm' = '100' for status 'CLEAR'.
> \# FAILED

If I look inside that file, it has a line mentioning that it has a hard coded user and stock config files so the notifications script can be called separately. Once again, I could edit these values, or partially fix the issue with the symlink that I can create.

However, before I started down that road, I just wanted to make sure I wasn't missing anything. Should I be changing something or supplying some kind of install variable to have those values updated on install?

Thanks in advance.

##### Expected behavior

**Comment by cakrit** [comment]
The only thing we have now, is passing to the installer `--install /usr/local/Cellar/netdata/` (I'm not sure why you put the version in the path, it can only cause problems). With this option, everything will go under that path. Better comment out the rest of the paths you manually changed in `netdata.conf`. 

Having said that, I also don't like the fact that these paths are hard-coded in the scripts that can be executed from the command line. You could always add to the environment the variables `NETDATA_USER_CONFIG_DIR` and `NETDATA_STOCK_CONFIG_DIR` and `NETDATA_CACHE_DIR` (this one is just for `alarm-notify.sh`). It's not good though.

We also have a symlink called `orig` under the `user config directory`, that's supposed to point to the `stock config directory`. I'm sure that we won't change that link if you manually modify `netdata.conf`, but not sure if we ever use that link. I believe it's only there for users to be able to quickly find those files. 

It's really difficult (perhaps impossible without a big performance hit) to have the scripts discover these paths when they are executed from the command line. We can't assume anything about the location of netdata.conf, or how to reach netdata to get the config info from there. If anyone can suggest a solution that would allow people to modify anything in netdata.conf and have these scripts be aware of the change, it would be great. Perhaps a change to the installer so that it updates the scripts and even the `stock` symlink based on an existing override in netdata.conf? (would be done only after an upgrade, but at least you'd know that if you changed the paths in these scripts manually before the upgrade, netdata wouldn't override them again!)

**Comment by warrenkerrigan** [comment]
Hi @cakrit 

Thank you for the response. Just to be clear, I had no intention of setting any paths. 

This was a clean install by running the command `brew install netdata`

The paths were set by the installer, not manually added by me.

I am happy to remove all references to netdata and start again, but this is the same on two servers I run the brew installer on.

This is what my netdata.conf looks like.

```
# netdata configuration
#
# You can download the latest version of this file, using:
#
#  wget -O /etc/netdata/netdata.conf http://localhost:19999/netdata.conf
# or
#  curl -o /etc/netdata/netdata.conf http://localhost:19999/netdata.conf
#
# You can uncomment and change any of the options below.
# The value shown in the commented settings, is the default value.
#

[global]
    run as user = netdata

    # the default database size - 1 hour
    history = 3600

[registry]
    # Registry Register on Dug (Luxo)
    enabled = no
    registry to announce = https://netdata.canfactory.org

[web]
    # by default do not expose the netdata port
    bind to = localhost 10.10.10.5
    web files owner = admin
    web files group = staff

[plugin:proc:diskspace]
    exclude space metrics on paths = /Volumes/com.apple.TimeMachine.localsnapshots/ /private/var/vm/
```

**Comment by cakrit** [comment]
No, wait. WE provide the instructions to use brew install, so we need to get this sorted out. Assigning to @paulkatsoulakis to take a look.

**Comment by paulkatsoulakis** [comment]
I just did a review of the homebrew version of netdata and this is interesting.
We need to review the formulae that homebrew using to install netdata (https://formulae.brew.sh/formula/netdata --> https://github.com/Homebrew/homebrew-core/blob/master/Formula/netdata.rb)

Apparently they are not using our netdata installer.  I 'll get back on this once i get more info

**Comment by paulkatsoulakis** [comment]
finally spotted the issue. It was kinda tricky to figure out what was wrong.
The problem wasn't at the formulae after all (even though we should sync the formula with how we build netdata in all other places).
We shipped edit-config on the distribution tarball, resulting in not re-generating unless someone did:
configure
make
make clean
configure
make

so that our scripts finally clean edit-config and re-generate it.

I removed edit-config from the tarball, so now brew will manage to re-generate edit-config properly each time

**Comment by paulkatsoulakis** [comment]
The change should be visible through brew once we got our 1.17 or 1.16.1 patch out

**Comment by paulkatsoulakis** [comment]
provided different solution, initial netdata PR was not solving the problem after all.

**Comment by paulkatsoulakis** [comment]
Issue merged on brew, should be resolved for our users if they re-install through brew.
@warrenkerrigan feel free to retry and let us know if the problem persists.

Thanks again for your report and my apologies for the late resolution on this one!

**Comment by warrenkerrigan** [comment]
Thank you for sorting! That seems to work now. Well done team!
