### ISSUE TITLE
RFC: Test automation tools 

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#6167]
From #4256: We need a test framework either integrated with Travis CI, or not. We already have a few tests that are not automatically executed and we will certainly be spending a lot more time on adding automated regression tests. This issue is to investigate the available solutions. 

Based on current research:
- We will continue to use Travis CI 
- We will use [bats-core](https://github.com/bats-core/bats-core) for many/most test automations. 
- We MAY incorporate netdata cloud REST API tests using https://golang.org/pkg/testing/ and/or https://golang.org/pkg/net/http/httptest/
- We MAY use additional tools for netdata's API testing (e.g. [integrate with postman](https://blog.getpostman.com/2017/08/23/integrate-api-tests-with-postman-newman-and-travis-ci/)), if bats-core starts causing issues.
- We will use [k6](https://k6.io/) for load testing
- We will use OSS fuzz (#6162) for dynamic analysis

Tests must clearly appear on Travis CI and it will must be easy to figure out what went wrong (i.e. no binary pass/fail results without logs that explain the failure).

**Comment by gpapamathND** [comment]
Regarding the below:
- We MAY use additional tools for netdata's API testing (e.g. [integrate with postman](https://blog.getpostman.com/2017/08/23/integrate-api-tests-with-postman-newman-and-travis-ci/)), if bats-core starts causing issues.
- We will use [k6](https://k6.io/) for load testing

We could use:
1. [blazemeter](https://www.blazemeter.com) -> It combines simplicity of `postman` with load testing features. **(Free version doesn't allow much to do though)**
2. [gatling](https://gatling.io/) -> It is used mainly for load testing [8 Reasons You Should Use Gatling for Your Load Testing](https://www.blazemeter.com/blog/eight-reasons-you-should-use-gatling-for-your-load-testing) 
**It supports only the following languages to write tests: Scala, Akka and Netty**

**Comment by cakrit** [comment]
> 1. [blazemeter](https://www.blazemeter.com) -> It combines simplicity of `postman` with load testing features. **(Free version doesn't allow much to do though)**

It's cloud-based though and I don't like the limitations  see [here](https://www.blazemeter.com/pricing) for their pricing. If we want a UI (which is not necessarily true), we can use the cloud-based add-on to k6 ([pricing](https://loadimpact.com/pricing/)). The good thing about k6 is you can choose which tests you will use the cloud for (i.e. you are allowed to run them locally and push only what you want to the cloud). Even without that, we get unlimited tests for the $299/mo. 

> 2. [gatling](https://gatling.io/) -> It is used mainly for load testing [8 Reasons You Should Use Gatling for Your Load Testing](https://www.blazemeter.com/blog/eight-reasons-you-should-use-gatling-for-your-load-testing)
>    **It supports only the following languages to write tests: Scala, Akka and Netty**

Yes, I don't want more programming languages, if I can avoid them.

**Comment by ilyam8** [comment]
i agree with suggestions from OP.

Speaking about tests i want to add that we need a clear picture on testing - what parts of netdata should be tested, which of them are tested and how they are tested (some public document?).

**Comment by mfundul** [comment]
Something that is very important to me is to somehow be able to run most tests locally and not depend on infrastructure and waiting indefinitely. This is very important for rapid testing cycles from the developer's perspective.

**Comment by cakrit** [comment]
> Something that is very important to me is to somehow be able to run most tests locally and not depend on infrastructure and waiting indefinitely. This is very important for rapid testing cycles from the developer's perspective.

This makes a lot of sense.
We discussed with @paulkatsoulakis and he'll write a script for us to be able to run any travis stage we want locally.

**Comment by gmosx** [comment]
The team already implements REST API calls using the standard Go testing infra as you describe. So +1 on this.

**Comment by cakrit** [comment]
> i agree with suggestions from OP.
> 
> Speaking about tests i want to add that we need a clear picture of testing - what parts of netdata should be tested, which of them are tested and how they are tested (some public document?).

The rules are generic, see the details in https://bestpractices.coreinfrastructure.org/en/projects/2231#quality

To be able to comply with these, we need unit and integration testing. Note that all of the items listed there are for **new functionality**

Where it gets hairy, is with "dynamic code analysis". See https://bestpractices.coreinfrastructure.org/en/projects/2231#analysis 
There, we need the analysis to cover ~80% of the code base. That's the last thing though, we first need to check the "quality" boxes.

**Comment by stephfz** [comment]
Regarding Load Testing, [locust](https://locust.io/) could be used since is python based (a programming language already in the stack)

About API testing, using newman sometimes can get hard to maintain, also a good alternative would using python request library as an API suite of tests, which can be added to the Travis or CI job.

**Comment by cakrit** [comment]
My concern with Python-based suites is that it's no longer a very popular language. All devs need to be able to write their own unit tests. I may be wrong of course, happy to continue the discussion.

**Comment by mrkphpps** [comment]
After some thought overnight I’ve come up with what could loosely be described as a test framework proposal. 

Just sketched it out aligned with a triangular landscape as a starter for discussion on my office whiteboard and attached to this comment.

![IMG_2386](https://user-images.githubusercontent.com/9035352/60504853-5971ef80-9cba-11e9-9a0d-9e482d21722b.JPG)

My thinking is:
~ Karma sits across all of the tests (as already referenced in the readme in the tests folder below root)
~ If BDD is wanted (discussion on this perhaps as I can argue it both ways) then Jasmine also sits across all of the tests
~ We could use KS6 to achieve the functional API/load testing but this might not sit well with either Karma or Jasmine - an option would be to just develop functional API tests using ‘pure’ JS (eg ‘request’) and have the load testing separate. Keeping everything inside a JS framework makes a fair amount of sense I think
~ PACT (or similar) could be used for pre-integration testing of components
~ webdriverio sits at the top and provides the UI capability.

In terms of a progression I would expect the triangle to start out top heavy.

I’ve found through experience that whilst it seems a little counter intuitive to do it, we might find that quickly creating a bunch of web driver tests to get some coverage ‘at the top’ isn’t necessarily a bad idea. A lot of these tests are thrown away over time as they get replaced by more coverage further down but short term they bring some testing into the pipeline and hence add confidence-albeit at the end of the build/deploy cycle.

There are some queries in my mind about how we would manage state (indeed what that state is) and testing ‘components’ in isolation using mocks etc (again, largely because I’m in the dark about what these mocks would need to be-perhaps PACT could be used for some of the contract stuff for instance), but broadly this proposal fits nicely into almost any conceivable CI pipeline and would also enable local execution of one, some, many tests as well.

**Comment by glaucoalmirramalho** [comment]
Hey folks, how are you doing?
I decided to install the application and see what happens. I ended up with a working POC with some Cucumber tests, ready for dockerization, and also some API testing in Postman. The project is at github with a wiki page in which you can take a look: [Wiki](https://github.com/glaucoalmirramalho/netdataatf/wiki). The repository is here: [Repo](https://github.com/glaucoalmirramalho/netdataatf)
This is the content of the wiki:

### Automate the API.
In this proposal just the communications between the Netdata application installed locally and the local monitoring web page. As a monolithic structure, no Contract or Integration tests will be applied among webservices. Only the following tests will be applied:

* Response Code tests: will check return code for the local service;
* Schema tests: will check Json schema for every response from local service;
* Functional tests: will check the functionalities of the local service.

**Method applied**

The API tests will be executed through Java code using the libraries httpclient and EverIt Json Schema validator. Another way of testing the APIs is by Postman, but is better to use it now only as a developer tool.

### Automate the Web page.

Netdata uses huge Mutant DOM in its web pages, so it is necessary to use a library compatible with such elements. Also we need a BDD framework and a good report system. So the Serenity framework will be used here. This framework allows to manipulate mutant DOM elements (AngularJs, Native, React), Cucumber scripts and good reports support. Some working Cucumber tests example is being provided which does the following:

- Navigate to landing page and check navigation;
- Get System Overview monitors and check if they are visible;
- Navigates to CPU, Memory and Swap panels through side menu and check navigation.

No Docker images are being used right now, but I can provide it easily upon request as a POC. To run these tests inside Docker the headless option is ready to be used.

### Allow developers to do some testing before push
**API**
As requested, the developers need a way to test their new code before pushing it. Postman is not my personal choice for complete API testing due to following reasons:

* Some difficulties integrating it to CI/CD;
* Hard to maintain big number of tests;
* Add more things to the test stack.

Although, Postman is very useful to perform local tests before pushing code to repository, and also is a good manner of keeping developers and QA working together keeping a central repo for the Json Schemas to be used. Both Java code and Postman tests are included in the POC.

**WEB**
To speed up the developing process here, the developers responsible to create the web page needs a form of mocking the webservices to test their new functionalities before pushing. To do so Postman may be a choice, but I would suggest using a simple mock server in Java using Fixture Factory as template manager, which allows better control over the data being used.

### Perform Load tests.

Currently Netdata has an internal process to load test their application, but it needs to be inserted in the CI/CD flow. Although I don't have good experience doing any Performance tests, I would recommend to try adding it to the CI/CD flow and just run it as a command. A Docker image can be used to do so. If more Load tests is required, or the current way don't works a good alternative is using Load Ninja, which allows very good browser testing. Unfortunately I couldn't give a better look in the internals of the system, so I couldn't check what is the best Load testing for the application alone, but I imagine that the current testing method can be applied.

### Proof of Concept.
A working Proof of Concept is being included and performs the following operations in Java:
* Perform Schema tests in the local API;
* Perform Status code;
* Perform some functional tests;
* Perform page navigation and verifying;
* Perform monitor data verification;
* Perform side menu navigation.

Also some tests are included in Postman (/src/test/resources/postman):
* Perform Schema tests in the local API;
* Perform Status code;
* Perform some functional tests;

**Preconditions.**
Java 8, Maven 3.6, latest Netdata, Firefox version 67.0.4.

**Instructions.**
1. Clone project from [Repo](https://github.com/glaucoalmirramalho/netdataatf.git);
3. In the command line type `mvn clean verify`;
4. The test results will be included in the path <project>/target/site/serenity/index.html

### The Future.
To the future of the automation process (in which I can provide a POC if requested), Docker can be used to limit resources of a container. By doing that, we can easily manipulate the running container in the CI/CD process by filling its hard disk for disk tests, or making it perform huge operations for memory and cpu consumption (like HASH calculations), providing any test scenario we want.
