### ISSUE TITLE
Qemu-KVM stats not correct help wanted

### ISSUE THREAD

**Issue by manojdhanda** [netdata/netdata#6171]
Hi, 

We just installed netdata and found it's a great tool to monitor infra, We using kvm for host vms.

We able to track correct matrix for network and disks but CPU and RAM usages not seams correct.

<img width="997" alt="Screenshot 2019-05-30 at 2 52 02 AM" src="https://user-images.githubusercontent.com/4649986/58592632-80d23880-8286-11e9-8e4e-edaa87808f88.png">

**Comment by vlvkobal** [comment]
CPU usage is correct in your case: 1% of total CPU usage = 72% of single core CPU usage. The problem I see is the precision of the chart, which can't be less than 1.0%.
Please check #6172. It should slightly increase the precision of the cpu_limit chart.

What is the problem with RAM usage metrics?

**Comment by manojdhanda** [comment]
Thank you for the response, I have updated same but no luck.

Not able to see how much ram in usage and CPU core showing of hypervisor machine, not the particular VM.

Please have a look live test screen and you can see the difference of stats here.

<img width="989" alt="Screenshot 2019-05-30 at 5 20 22 PM" src="https://user-images.githubusercontent.com/4649986/58631232-85870300-82ff-11e9-83eb-37eea863344e.png">
<img width="875" alt="Screenshot 2019-05-30 at 5 19 51 PM" src="https://user-images.githubusercontent.com/4649986/58631234-85870300-82ff-11e9-819e-7b815f3d1ace.png">

**Comment by Ferroin** [comment]
@manojdhanda Do I understand correctly that you're expecting Netdata to show the same CPU and RAM usage that tools run from _inside_ the VM in question do?  Because if so, that's not possible without running Netdata in the VM itself.  

What's actually being shown here by Netdata is the VM activity that the host system sees, namely how much CPU time QEMU/KVM consumes, and how much memory QEMU is using.

The memory usage you're showing is actually exactly in-line with what I would expect for a QEMU VM that's been allocated 10G and isn't using KSM (by the way, you probably want to be using KSM if you've got that much free memory in your VM's on a regular basis) and has it's storage configured to use the host's page cache (which you probably also want to avoid doing unless you're using backend storage that has issues with direct I/O).

The CPU usage also looks like it's probably correct other than the issue @vlvkobal pointed out about the chart resolution, but I can't be certain as you only have some of the data from `top` shown.

**Comment by manojdhanda** [comment]
Noted and Thanks for the suggestion :)

Is there any way to monitor VM usages for CPU and RAM in percentage if we unable to get exact usages inside the VM?

Are you able to suggest any tool for that?

**Comment by Ferroin** [comment]
@manojdhanda There are two options for getting this kind of data from a VM:

* Run Netdata inside the VM itself.  If you set up the Netdata instance in the VM to stream all it's metrics to an instance of Netdata running on the host and disable saving anything locally in the VM, this is actually pretty efficient and not hard to set up, and it will give you all the data for the VM's in one place (the host systems Netdata dashboard).  Once set up, it also requires no special additional configuration to handle ephemeral VM's.
* Use SNMP to extract the relevant data.  This requires a non-trivial amount of setup inside the guest unless you're using FreeBSD (which just requires enabling SNMP) because the required MIB data isn't part of the standard set on most platforms, and also needs a non-trivial amount of setup for Netdata on the host.  You can actually use this to get a whole lot more data than just CPU and RAM usage (the standard set of MIB's on FreeBSD for bsnpmd includes info on disk usage, as well as uptime, and a lot of data about networking), but the overhead of setting it up is pretty significant, and right now it needs you to add new configuration for each new VM you want to monitor.  It does, however, work with Windows guests too to a certain extent (though still requires non-trivial configuration inside the VM).

Beyond that though, there's really not any good way to do this with QEMU.  There is a Netdata collector that can fetch CPU data for Xen, and I think I saw some work being done to get equivalent data for VMWare, but both of those have easy standard ways to get the required information from the hypervisor itself, which is something QEMU itself really doesn't have.  There _might_ be some way to get the CPU usage data from the kernel because of KVM, but I don't know how granular it would actually be (I know for certain you can get the total across all VM's, because that's what the `guest` and `guest_nice` values in the host CPU usage charts are, I just don't know if you can get it per-VM or per-core-per-VM).

RAM is even more complicated, because the _only_ way to get info about the memory utilization inside the guest is to ask the guest OS itself.  You just can't tell from the guest page tables (the part that the Hypervisor would be able to scan to see usage) what memory is actually in use and what isn't.  This is the entire reason that memory ballooning for virtual machines needs the guest OS to have a driver, the guest OS is the only one who knows for certain how much memory it's using.

**Comment by webdock-io** [comment]
@Ferroin 

> Run Netdata inside the VM itself. If you set up the Netdata instance in the VM to stream all it's metrics to an instance of Netdata running on the host and disable saving anything locally in the VM, this is actually pretty efficient and not hard to set up, and it will give you all the data for the VM's in one place (the host systems Netdata dashboard). Once set up, it also requires no special additional configuration to handle ephemeral VM's.

This is exactly what I'd like to accomplish on my systems. I have tried googling a bit and looking at the docs, but Netdata has changed a lot since 2019 :)

Do you have any quick and easy guidelines on how to accomplish this anno 2022? I would like to script this so whenever I spin up a VM I automatically install netdata with the correct config to stream metrics to the host, which then passes that along to netdata cloud / my own systems.
