### ISSUE TITLE
State Node view - Group nodes by Tags in Master

### ISSUE THREAD

**Issue by gamefundas** [netdata/netdata#6176]
I was going through Netdata cloud feature and my understanding is that it provides a personalized view of application cluster/nodes and information is sort of categorized according to the user's preferences. As an enterprise feature this kind of makes a whole lot of sense. I also like the way the nodes are grouped along with corresponding alerts in those boxes. 

However it also makes me think if the registry in Netdata master/slave configuration can achieve the same with slave nodes sending tags (metadata) as part of the registration. The master can save the nodes/tags data in some kind of local store and provide the same view in the UI. Remember discussing this with @ktsaou sometime back about this. May be I am leaning towards this idea because cloud is not really an option for us.

Even if Netdata needs a differentiating factor between cloud and on-premis, its still there in terms of the whole personalized view in case of the former.

**Comment by cakrit** [comment]
The request depends on the implementation of https://github.com/netdata/netdata/issues/4986
So we do have tags/labels on our roadmap and the standalone netdata agent will also utilize them, but we were only considering their use for the metrics it collects. What you're saying does make sense for a master/slave configuration though and it would definitely be a perfect fit for our kubernetes master. The slave info you already see doesn't use the registry at all (the cloud is essentially registry v2). So it's definitely technically doable (would need some clever UI design and of course to use similar abilities without signing in). I can't say when we'd be able to work on it though, the roadmap is very heavy right now. 

If you don't mind, could you explain a bit the blocker even with the on premise version of the cloud? Because we haven't heard of that before...

**Comment by cakrit** [comment]
@ilyam8 said something very nice. For host tags, we don't need to wait for tags/labels in metrics. So we can definitely look at it independently, without even involving the DB at first.

**Comment by gamefundas** [comment]
@cakrit makes sense. It will be something to look forward to.

About the on-premise/cloud version I am not quite sure how the security on that will be. In our environment the lowest we can operate is using LDAP, if any external authentications come along then it gets trickier. 

If I misunderstood this and its merely about hosting a module in an accessible location internally/running along with Netdata master, docker even better then no complaints at all. I am sure the team will keep us posted on the progress of it.

**Comment by cakrit** [comment]
> About the on-premise/cloud version I am not quite sure how the security on that will be. In our environment the lowest we can operate is using LDAP, if any external authentications come along then it gets trickier.

The email authentication method we use doesn't even store passwords, so it might be ok temporarily with security, as long as the corporate emails are used. They'd have to evaluate it of course. LDAP & probably Active Directory integration will definitely be one of the enterprise features we'll be offering. 

I picture the on-premise version as a stand-alone host (a docker image is definitely a good idea), like you described below. You'd have it on your infrastructure, so no data would ever leave your premises.

**Comment by cakrit** [comment]
Closing in favor of #6503
