### ISSUE TITLE
Registry not working & related issues

### ISSUE THREAD

**Issue by alexcernat** [netdata/netdata#6267]
##### Bug report summary
"master / slave" environment, streaming is ok, but private registry doesn't seems to be working
##### OS / Environment
master: Debian 10
slave: Debian 9
##### Netdata version (ouput of `netdata -V`)
master: netdata-core  1.12.0-1 (netdata v1.12.0)
slave: netdata-core 1.12.1-2~bpo9+1  (netdata v1.12.1)
##### Component Name
registry
##### Steps To Reproduce
Master config (dashboard is on port 80, behind password protected nginx, proxied through unix socket):
[global]
        run as user = netdata
        web files owner = root
        web files group = root
        bind socket to IP = 127.0.0.1
[web]
    bind to = unix:/var/lib/netdata/netdata.sock X.X.X.X:9999=dashboard|streaming|registry X.X.X.X:9998=registry # X.X.X.X is public ip of master
[registry]
    enabled = yes
    registry to announce = http://X.X.X.X
[api-xxx-guid]
    ... stream parameters
Slave config:
[global]
    run as user = netdata
    web files owner = root
    web files group = root
    bind socket to IP = 127.0.0.1
    memory mode = none
[health]
    enabled = no
[web]
    mode = none
[registry]
    enabled = no
    registry to announce = http://X.X.X.X:9998
[stream]
    enabled = yes
    destination = X.X.X.X:9999
    api key = xxxx-xxxx-xxxx-guid
##### Expected behavior
Streaming works perfectly, I can see "slave" dashboards directly on master , but the registry database/system/feature is not working (registry.db is empty).
Worse, tcpdump on master (capturing port 9998) does not show any package after slave netdata restart (a subsequent telnet X.X.X.X 9998 works, so no firewall/network problem).
The private registry does not work nor in dashboard (hello is ok, but subsequent actions give 403 forbidden), but this later ...
Also a strange thing: http://X.X.X.X:9998/api/v1/registry?action=hello requires also dashboard access on that port (only "hello" action, as seen in sources), not only registry access.

In order to understand exactly how the registry works (beside debugging in the sources) can anyone explain which sends what to whom ? Have I made any mistakes in this very simple test config ?

**Comment by cakrit** [comment]
Looks like you're missing the port 9998 on your master `registry to announce`. 
```
[registry]
enabled = yes
registry to announce = http://X.X.X.X
```

Regarding the `bind to` section, you've essentially permitted the registry to be accessible via the unix socket (default is to accept all queries) and via the other two ports. So you should definitely not be getting any connection errors, as long as the port is configured properly (needs netdata restart of course)

It's only your browser that communicates with the registry, you can debug by turning your browser's console on. 

Hint: You don't need the registry, if all you want to see is the slaves that are streaming their data to the master. You can see the master and slaves on the nodes menu in the top left side, regardless of whether a registry is enabled. The slaves will appear there, as soon as they establish the communication with the master (will need a page refresh).

**Comment by alexcernat** [comment]
Thanks for the quick answer.
Unfortunately, if I add the port to the "registry to announce" option, that setting is exported to the browser, and the browser will ask for registry at port 9998, which I want to avoid (the browser must access only the nginx server on 80 - later ssl on 443, both password protected, netdata ports should not be accessed directly by browser).

Indeed, for now all I need is the list of monitored servers, but only master server appeared, tried in several tabs (also incognito) and nothing.
Update: tried in a fresh now browser (firefox) and the list appeared, and then dissapeared.
But something strange: if I choose "switch identity" and just click "impersonate" (not modifying my person uuid) and the slaves list is again there.

As conclusion:
1. seems that my chrome data got screwed up, I will clean the cookies and other site data and try again
2. it is normal that erratic behaviour described above ? sometimes full list of slaves is shown - plus my nodes, sometimes only my nodes; doing "impersonate" as myself and the list appears again

(v.1.12.0)

**Comment by alexcernat** [comment]
And let's see if I fully understood about the master/slave and registry.
I was under impression that streaming the data is one process, but the slave must also "register" separately to the master, but seems I have it wrong.

So:
1. ONLY THE BROWSER TALKS TO THE REGISTRY
2. "registration" on master (as putting in the list of slaves) is done automatically on the first streamed data; also "de-registration" on master is done automatically (after the slave had not streamed more than configured interval and the proper garbage collection option is set)
3. there is no communication between slave and master through the registry api/service (same as 1); the "registration" is done automatically through "stream" service
4. on a slave the option "registry to announce" is used only when browser connects directly to it, so ...
5. on a headless slave (stream to master only, with web disabled), the option "registry to announce" is useless, only need to disable the registry, i.e. to save some memory

maybe some of the above should be specified better in the documentation, especially for the ones new in netdata

**Comment by cakrit** [comment]
I started replying twice and got interrupted, finally got around to it.

- The second comment with the list is spot on. Any contributions are always welcome, feel free to add the information in a PR and I'll review/merge.
- Since you access netdata via a proxy, your proxy should be sending the requests for location `/api/v1/registry` to a host:port that accepts registry requests (in your case even the unix socket accepts them, but I guess you wanted it to be X.X.X.X:9998).
- What you see depends on the "person" mentioned in the documentation. That "person" is stored on a browser cookie, so you'll see different things in incognito mode, different from a different browser and definitely from another PC. The `switch identity` you saw will update that cookie. This is also definitely a poorly documented detail. The cloud sign in doesn't have these limitations, but for a private registry, it's definitely still there. 
- Slightly unrelated: I suggest you keep netdata updated, even if that means not using your system's package manager. 1.15.0 is the latest, our nightly even has SSL support. 

What confused me a bit was that I understood you saw the "person" affecting the slaves you were seeing on the menu. It shouldn't at all. Links to the master and the slaves appear on the top part of menu based solely on what is being to that host. Clicking on a slave asks the master to show you the view of  the slave's charts. What could change is if each slave was not headless and you accessed its UI directly. I understand you got that part too, but it's also something that could be detailed in the documentation. 

Again, we'd greatly appreciate a contribution to enhance the documentation. If you're not able to do it, let's keep this open and we'll get to it.
