### ISSUE TITLE
Collector auto-detection (service state auto-detection)

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#6295]
Related: #6119, #4266

#### We want netdata:

 1. to start as soon as possible
 2. be able to monitor services started after netdata

That can't be achieved modifying boot order (violates 1). 

**Question is how to achieve this?**
___

#### Current auto-detection:

Basically no autodetection. We have bunch of predefined jobs. 

How it works:
 - netdata starts
 - netdata starts plugin resposible for data collecion (`python.d`, `go.d`, etc.) [no delay]
 - plugin reads modules config files, creates and starts jobs [no delay]

We good only if service is up and returns metrics.
If it is not the case then collection job considered `failed`. Plugin drops the job and you need to restart netdata to start it again.

#### Current workaround:

We have `autodetection_retry` option, it can be set per `module` and per `job`. Plugin will try to restart job every `autodetection_retry` seconds if the option is not zero.

This feature is disabled by default.

___
#### How to solve the problem and to have both 1 and 2.

**Option 1** [easy]:
 > enable `autodetection_retry` feature for all modules by default.

This will do.
But it doesn't scale well. Netdata has a lot of predefined jobs (150+) and it is not rare when only couple of them are running at a time.
Retry all the jobs is very cpu intensive task.

**Option 2** [easy]:
 > delay orchestrator start (or delay specific module start)

Dead simple. Start netdata as soon as possible. Start service collection after N seconds. Could be implemented as a temporary solution.

Doesn't solve the problem, just masks it.

**Option 3** [???]:
 > check if the process is up and able to return metrics, start collector only after it

Wow! That is it! The problem with it that it is not clear if the option is even achievable.

Lets think. 
Who is responsible for service status check?
 - a collector
 - a separate thing (service watchdog :dog:)

It seems that it should be the collector.

Another problem that it is not *service*, it is *services*. And the service could be containerized.

Example: server with 5 apache instances, all of them running in docker containers. How should the collector check their statuses?

A lot of question. I come to the conclusion that the most precise way to check the service status is to make a check (job.Check).

But it means `Option 1`. So maybe optimizing `autodetection_retry` algorithm will do ? :thinking:

**Comment by vlvkobal** [comment]
I vote for a conservative algorithm which is relatively modest in CPU resource usage as we already discussed it in a call:
- Start Netdata as soon as possible
- Scan for available services right on the start
- Rescan on 10 sec, 30 sec, 1 min, 2 min after the start
- Stop scanning

**Comment by ilyam8** [comment]
Well, looks ok. The problem part is

> Scan for available services right on the start

What is `can for available services`? 

I guess you are voting for OP `Option 1` but with 

> a conservative algorithm which is relatively modest in CPU resource usage

am i right?

**Comment by vlvkobal** [comment]
Yes. I'm talking about starting all jobs.

**Comment by Ferroin** [comment]
My initial thoughts on this are pretty well summarized in https://github.com/netdata/netdata/pull/6119#issuecomment-502076563

I do, FWIW, think that providing `autodetection_retry` for everything with a (preferrably user configurable) back-off on the interval is a good idea, independent of anything else that is provided to handle this.

Two other thoughts come to mind though:

* Any collector that needs to fork a command for the data collection should probably automatically hard-fail by default if it can't find the command it needs to run instead of rechecking each iteration.  Unlike most other things, it's pretty unlikely in most cases that the user will suddenly install the required command.  We should probably do the same for the python.d collectors that depend on specific Python modules being present, for the same reasons.
* It would still be really useful to be able to configure collectors to check the status of the service they're supposed to be collecting data from.  This could be as simple as providing a hook for a custom command to be called prior to other checks, configured on a per-job basis.  I don't think it makes sense as the default behavior in most cases, as it's likely to be expensive, but I still think it's useful enough to warrant inclusion.

**Comment by cakrit** [comment]
I'm adding a couple of things we discussed with @ktsaou and we'll have an internal call tomorrow to go more deeply into the various options:
- For a quick win, we should be keeping track of which jobs were active before the last netdata restart. For those jobs only, we should retry for ~5 minutes, every 30 sec. 
- We need to validate our auto-detection for all monitored applications supported by us in what we'll call "Gold OSs" , i.e. LTS from Ubuntu, Debian, RHE, SuSE, CentOS. There will be some applications that we mark as community-supported, such as `freeipmi`.  
- We then get to the issue of configuration management, i.e. #4731. That centralized configuration management hub should have a plugin architecture, allowing it to be notified of changes not only by monitoring files, but also by receiving commands or events from other sources. It should then be able to create/update/delete jobs and trigger the checks on the appropriate collectors.

**Comment by cakrit** [comment]
The last part regarding configuration management will be tackled in #6432

**Comment by vlvkobal** [comment]
I'm closing the issue. We implemented workarounds. Further development is discussed in #6432.
