### ISSUE TITLE
Brave (browser) fails to access registry

### ISSUE THREAD

**Issue by AaronRobinson** [netdata/netdata#6298]
##### Bug report summary

<img width="1676" alt="Screenshot 2019-06-17 at 17 17 43" src="https://user-images.githubusercontent.com/1792811/59620207-337a1600-9124-11e9-9465-9b9308d3e031.png">

Using Brave browser on a Mac fails to access the registry. It works fine on Chrome. The node drop down menu just says '....please wait...'. The cloud nodes gives me a white screen. Browser error in attachment.

##### OS / Environment
Mac OS Mojave 10.14.5

##### Netdata version (ouput of `netdata -V`)
netdata v1.15.0-98-nightly

##### Steps To Reproduce
Access the node menu using the Brave browser

##### Expected behavior
Node options should show

**Comment by jacekkolasa** [comment]
Unfortunately Brave features are preventing our SSO mechanism from working properly. This is caused by "Cross-site cookies blocked" setting in Brave Shields. Safari does the same thing but it auto-enables cookies for 30 days when user access the original domain in main frame (when users are redirected to https://netdata.cloud/account/sign-in-agent)

i've done few experiments and login works only when you tweak those settings settings:

![image](https://user-images.githubusercontent.com/5786722/66314533-7b5fbb80-e914-11e9-8214-a2e225991af4.png)

Unfortunately It has to be done on every Netdata Agent page you go to...

@cakrit perhaps we should display some notification for the user when we detect such limitation?

**Comment by jacekkolasa** [comment]
We need to remember that Google Analytics will not show any statistics of Brave Browser usage

**Comment by cakrit** [comment]
I'm not worried about GA, but I am worried about having to repeat an action on every agent. Doesn't that link "Change global shield defaults" allow more permanent settings? Isn't there anything more specific than "All cookies allowed" to permit cookies just from https://netdata.cloud?

**Comment by cakrit** [comment]
@jacekkolasa can we have an answer on this and close it if there's nothing else we can do? Not even sure it's relevant any more, after the introduction of the new cloud.

**Comment by jacekkolasa** [comment]
I was trying to get some info from Brave community, but i had no luck (maybe i didn't tried hard enough). I think there's not much i can do now, but we can wait, perhaps a feature called Storage Access API will be brought to Brave, which will allow us to ask users if they're ok with being tracked.

We can track this issue to know if Brave Browser is ready - https://github.com/brave/brave-browser/issues/8514
