### ISSUE TITLE
[Question] Netdata install options - Docker/Binary

### ISSUE THREAD

**Issue by gamefundas** [netdata/netdata#6308]
Have few questions here as I am looking to simplify my Netdata installation through a binary install or docker based setup.

Binary install: 
Where can I get the precompiled binary for Linux 64bit. I ended up on a Archived/Deprecated release location which doesn't host the latest binaries anymore. Also I wont be able to run the kickstart-static64.sh script to download as my organization runs behind a proxy with very limited access to internet. It would be good to download the .run files to the host machine and then trigger an install

Alternately Docker install:
I would consider using this as its the most convenient way to run anything on our cloud but is it documented somewhere what the trade-offs are. I do see the disclaimer that some features wont be available in a Netdata docker instance and less detailed too.

**Comment by gamefundas** [comment]
Still looking for an answer to this.

**Comment by joelhans** [comment]
@gamefundas I'm not sure if you're still looking for ideas for this, but I'll leave some answers for anyone else who might be looking for thoughts on this.

**Binary install**: Because you can't run `kickstart-static64.sh` the normal way due to limited internet, you could use our [offline installation method](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/offline), which supports the static build. You just need to be able to move the downloaded files onto that system. You can then use the `--local-files` option with `kickstart-static64.sh` to use the downloaded files instead of the installer trying (and failing) to grab remote bundles.

**Docker**: Perhaps we should better document what specific metrics might not be available, but when using our [recommended Docker installation](https://learn.netdata.cloud/docs/agent/packaging/docker#run-the-agent-with-the-docker-command), the metrics collected via Docker quite robust. I only seem to be missing systemd and eBPF metrics, the latter of which I believe is a known issue that our packaging team is working on.
