### ISSUE TITLE
Claiming nodes for netdata cloud and easier addition of known agents

### ISSUE THREAD

**Issue by weijing24** [netdata/netdata#6318]
#### Question summary
hi,
I have deployed netdata in several nodes and It's really awesome. But I have two problems as follows:
* When I want to see my nodes, I visit console.html. Each node needs google oauth
* I can't share the console to my teammates

In detail, the console just shows a part of my nodes I have visited in browser. If I want to see some more nodes not listsed in console, I have to visit http://not-listed-node-in-console:19999 and click the Nodes(beta) icon then google oauth2.
![image](https://user-images.githubusercontent.com/8737314/59848478-d71f2c80-9397-11e9-85db-4752c2843bbf.png)
The most important is that I can't share my console to my teammates .It's really painful.

#### Component Name
console.html and netdata cloud

#### Expected results
Is there any possible to see all nodes in console without google oauth2 ?What I want just visit console.html see all my nodes that I have deployed,And during this visit,I can bypass google oauth2.Or just like zabbix,the console can be seen by every teammates.

Thank you for sparing your precious time answering my questions.I'm looking forward to speaking to you on this matter

**Comment by cakrit** [comment]
We know that is a real issue and we have two things on the immediate roadmap:
#4771 will be the definitive way to do it. You'll be able to get a key from the cloud, put it in your agents configuration and they will always appear on the nodes view. You'll also be able to share that view with your team (either all the nodes, or specific nodes shared with specific teams).

Another thing on our roadmap related to this is the improvements described below:

With the current solution, we force users to login at least once for every URL they visit, so that SSO can be activated. For users with hundreds or thousands of servers that just doesn't work. We can do MUCH better than this. 

- Trust machine GUID instead of URL. The mechanism that checks if should go ahead with SSO should be using the viewed host's machine GUID, so that we don't force a new sign in every time we view the same server with a different URL 
- When I visit an unknown host *and I'm already signed in on any other host from this browser* (#687):
  - Show me as signed in. 
  - The registry and netdata.cloud get the guid, hostname and URL. netdata.cloud adds the server to the list of known hosts, but marks the host guid as untrusted. 
  - If the user clicks on the menu, don't show the list of servers from netdata.cloud, and disable the console button. We don't allow management from untrusted servers. In the menu, we show a message that this host is not trusted. Give user a button to "Trust this host". When the user clicks it, a hidden netdata.cloud iframe sets the server to trusted and shows the full menu. The same message and button can appear if the user clicks to see the nodes view. 
- Show the difference between trusted and untrusted hosts in the node view, with a button to "trust all". 
- In a master/slave scenario (streaming), if at least one of the hosts is trusted, then all of the others are automatically added and are trusted as well. 
- Any changes to the list of hosts, their URLs and the trusted status must be synchronized between the agent view and the node view.

**Comment by cakrit** [comment]
cc @gpapamathND

**Comment by weijing24** [comment]
excuse me, i would venture to ask two questions:

- Will all these features release together in a verision ?

- when can I discovery these gorgous features you mentioned above？Do you have exactly time or release？

**Comment by cakrit** [comment]
I'm a bit hesitant to commit to a timeline today, as we've had a few hickups that caused significant delays. We would certainly like to have them in 1.17, which is mid-August (will create the milestones now), with the nightlies of 1.16 having the features earlier of course. We'll update here when we have a concrete, fact-based plan.

**Comment by Shagon94** [comment]
There appears to be a bug with the claimed servers, namely what is shown:

I have 4 servers, this is what is shown when I visit the servers IP address:19999

![Screen Shot 2019-09-06 at 9 40 52 AM](https://user-images.githubusercontent.com/9140783/64410056-7c3dcd00-d08a-11e9-8c5a-775be4604106.png)

However I were to visit my main server, the one on https://domain.com

![Screen Shot 2019-09-06 at 9 40 44 AM](https://user-images.githubusercontent.com/9140783/64410121-9d9eb900-d08a-11e9-8414-51b8439f58f7.png)

I get a reverse thing, showing that my 3 other servers are down but that it is up. Additionally, I cannot remove added server, e.g. that london3 one. I've tried to tinker with the API on how the website does it but at no use, I cannot get rid of your london server.

Is there any reason these are not in sync? How can I view all my of my servers on one centralized dashboard without skipping between the two?

**Comment by weijing24** [comment]
@Shagon94 
 > Additionally, I cannot remove added server, e.g. that london3 one. I've tried to tinker with the API on how the website does it but at no use, I cannot get rid of your london server.

if you want to delete london server, you can click london server first
![image](https://user-images.githubusercontent.com/8737314/64412526-1b31eb80-d0c2-11e9-9354-7a5c19a5dd34.png)
There will be summary in sidebar. Pull your mouse to bottom, click this.
![image](https://user-images.githubusercontent.com/8737314/64413012-4cf78200-d0c3-11e9-84ee-637924b500dd.png)

**Comment by gpapamathND** [comment]
@weijing24 thanks for your comment. I was about to answer :)  Much appreciated. 

@Shagon94  Regarding the unreachable servers, I would say that the second instance of the browser cannot ping them, for some reason (might be a firewall issue or something else). 

I would appreciate your help to troubleshoot:
1) Click on the "unreachable" node and on the right panel click the button "Check"
2) Track the API calls/responses at the Network tab of the browser (I am using chrome)
3) If you see the **`registry?action=hello`** having no response, it means your browser cannot ping this agent (might be a network access problem between the Node(agent) and your PC)

![image](https://user-images.githubusercontent.com/48526360/64414012-46edab00-d09b-11e9-9a76-3fac57d24fa8.png)

Could you please check and get back ? I would really appreciate your help to troubleshoot this issue.

**Comment by WinstonPrivacy** [comment]
Wondering if this is still on the roadmap for Q4? We are hesitant to implement netdata unless there is a scalable way to add nodes.

**Comment by cakrit** [comment]
@WinstonPrivacy we're now targeting February. Apologies for the delay, but I think you'll be very happy with what you'll see then! :)

**Comment by marcelmfs** [comment]
Hi, I'm seeing something similar, but slightly different, instead of unreachable, I see a greyed out `outdated` node. No matter what I do, clean `/var/cache/netdata/*`, or even going to host:19999 then clicking Nodes, no strat mentioned worked.

**Comment by cakrit** [comment]
> Hi, I'm seeing something similar, but slightly different, instead of unreachable, I see a greyed out `outdated` node. No matter what I do, clean `/var/cache/netdata/*`, or even going to host:19999 then clicking Nodes, no strat mentioned worked.

Hi @marcelmfs , can you open a different issue for this, with perhaps a screenshot of what you see? Also mention in that issue what happens when you delete that node's URLs (it should disappear).

**Comment by cakrit** [comment]
This epic is obsolete, claiming for the new cloud release has been implemented via other issues.

**Comment by weijing24** [comment]
> claiming for the new cloud release has been implemented via other issues
Can you tell me the latest reference about the 'other issues', I have been focusing on the feature for a long time. Thanks.

**Comment by cakrit** [comment]
We will have a release in a couple of months that includes claiming. We have it implemented in a major new version of the cloud, that's still in development. Stay tuned for release announcements! :)
