### ISSUE TITLE
Is it possible to disable list of 'Demo netdata node' from registry drop down?

### ISSUE THREAD

**Issue by Avik1993** [netdata/netdata#6346]
##### Question summary
Is it possible to disable the list of demo netdata nodes from registry drop down?
I need to use Netdata in client network and it won't help my cause to show list of servers not a part of my deployment.

##### OS / Environment
Centos
##### Component Name
Registry
##### Expected results
Drop down should only show a list of servers that broadcast to my local configured registry on master node, and NO demo netdata nodes should appear.

**Comment by Avik1993** [comment]
Also, I am giving a custom name for 'registry hostname' key, but it still shows up as the default one only.
Any idea why?

**Comment by Avik1993** [comment]
I checked in inspect in browser for any errors. And i did see some interesting logs.
![netdata_errors_updated](https://user-images.githubusercontent.com/8459729/60159428-c72ca000-9810-11e9-8b65-681e92ea0fb5.png)
Here, I could see the 'CUSTOM NAME'  I had given to the master server, but no logs for other servers which broadcast to this registry

**Comment by cakrit** [comment]
- You'll only see the master and the demo nodes if netdata fails to contact the registry AND found no nodes to show in the browser's local storage. 
- The error `annot open registry file: '/var/lib/netdata/registry/registry.db'` is not important. I believe it gets created only if the file `/var/lib/netdata/registry/registry-log.db` gets too big, but didn't go in deeper to investigate. You can `cat /var/lib/netdata/registry/registry-log.db` to see what's written there actually. 

The last post confused me, because we were first talking about the registry and then about streaming. If you `tail -f /var/log/netdata/error.log` on a slave, you will see if has successfully opened a connection and started streaming data. The registry has nothing to do with this. If you can open a socket from the slave to the master's listening port and you have the correct GUIDs set up, streaming will work

**Comment by Avik1993** [comment]
Hi @cakrit Thanks for replying.
This is new for me. 
So if I understand you correctly, along with setting the registry endpoint in file `/etc/netdata/netdata.conf` in slave node, I need to setup streaming as well?
Can you point me to some documenation to setup this up.

**Comment by cakrit** [comment]
Ok, the two are completely different and completely unrelated. Go through the following documentation first and we'll be happy to assist further:
- https://docs.netdata.cloud/streaming/
- https://docs.netdata.cloud/registry/

**Comment by Avik1993** [comment]
Great Thanks @cakrit

**Comment by cakrit** [comment]
Happy to help! Closing this, go ahead and open a new one if you need anything else.
