### ISSUE TITLE
Windows Support Spike

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#6395]
This task is to do initial preparations/investigation so we can plan to deliver #92, probably via #2637 and a lot of additional tasks.

**Comment by thiagoftsm** [comment]
During this last sprint I worked to test our necessity to migrate the Netdata to Microsoft Windows, after few days of tests I arrived in the following conclusions:

- I am assuming that until the development proofs that I am wrong, we can use Mingw w64 ( https://mingw-w64.org/doku.php ) as our cross compiler.
- Unless there is a better option, we can use ( https://nsis.sourceforge.io/Main_Page ) to create installer. @paulkatsoulakis you gave me a suggestion during the presentation, but I did not write it (I am sorry!), can you write in the comments the another installer for we use?
- Our installer must carry the Python 3 installer and the Go installer. @ilyam8 and @vlvkobal  am I forget something installer for the collectors? I will write more about collectors in the next options.
- Optional: There are libraries that will never be on present on Microsoft(libuuid), unless they decide to use the Linux kernel definitively, but they have their own library, so we can do as the first step of the migration to remove the hard code libraries and move to a dynamic loaded library.
- Exchange between Libuv and pthreads: Considering that libuv is the basis for the dbegine that is here to stay, we can use another feature of the libuv to help us, the libuv works with Windows Thread on Microsoft and pthread on Linux, so I think we can go in the direction to use only libuv to threads.
- Rewrite part of daemon/ directory: Microsoft does not have nothing like fork(), probably the CreateProcess() (NtCreateProcess() )is the nearest that they arrive on this. This is because according to Microsoft vision, they work with threads instead process. I thought to use the cigwin, but according different people, this slow down the process, so I discarded this option, so my suggestion is to use a service instead a daemon on Microsoft Windows.
- The following libraries were used without any problem, where "without any problem" in this case means, I could cross compile, I could call the functions and it does not slow down the test system created:
| Library | Source |
| Liblz4 | https://github.com/lz4/lz4.git |
| JSON-C | https://github.com/json-c/json-c |
| Libuv | https://github.com/libuv/libuv |
| OpenSSL | https://github.com/openssl/openssl |
| Zlib | https://github.com/madler/zlib |
- The unique library tested that created problem was libJudy (http://judy.sourceforge.net/ ), when I tested the version from sourceforge and the DLLs from cygwin, it was slow or it did not let the executable to complete the tasks. @mfundul gave me another option, but I did not have time to test yet.
- Windows does not have bash script, so we will need to convert our shell scripts to VBscripts or to write a software that will work together the Netdata on Windows, for the second case, my suggestion is to use a shared memory like PostgreSQL does.
- Another necessary conversion, the syscalls are differences between Unix and Microsoft, so everything that is calling a Unix syscall, must be converted to a Microsoft function.
- We do not have a /proc on microsoft, so we will need to check the correspondent functions to obtain the data. Probably a reverse engineer on Perfmon (https://www.cse.wustl.edu/~jain/cse567-06/ftp/os_monitors/index.html#sec2.1 ) can give us some answers for this.
- Another thing about perfmon, it is possible that it can give us some ideas.

For while I think these are the important points to consider during the migration.

**Comment by Ferroin** [comment]
> I am assuming that until the development proofs that I am wrong, we can use Mingw w64 ( https://mingw-w64.org/doku.php ) as our cross compiler.

While it's true that we _can_ use mingw-w64, I can tell you now people will want to be able to build with Visual Studio.  ISTR that current versions of Visual Studio allow free licensing provided they're not being used for commercial development (so as long as you don't use it for anything you're actually selling, it should be fine).

> Unless there is a better option, we can use ( https://nsis.sourceforge.io/Main_Page ) to create installer. @paulkatsoulakis you gave me a suggestion during the presentation, but I did not write it (I am sorry!), can you write in the comments the another installer for we use?

Not sure whether it's a better option than NSIS for Netdata or not, but [WiX](https://wixtoolset.org/) is probably worth a look.

> Our installer must carry the Python 3 installer and the Go installer. @ilyam8 and @vlvkobal am I forget something installer for the collectors? I will write more about collectors in the next options.

Unless we're building the Go plugin locally, we may not actually need the Go installer.  I don't remember if there are any special run-time requirements we would need to bundle, but we should be able to get a static build of the go.d plugin that just works on Windows (that's kind of the point of Go).

On the note of Python, please make sure that the installer checks for an existing Python install.  If the system already has a version of Python that we support, there's no point in wasting time and space installing our own copy.

> Windows does not have bash script, so we will need to convert our shell scripts to VBscripts or to write a software that will work together the Netdata on Windows, for the second case, my suggestion is to use a shared memory like PostgreSQL does.

Please for the love of god use PowerShell, not VBScript.  We're not targeting anything older than XP, and realistically probably not anything older than Windows 7, so PowerShell is essentially guaranteed to already be present on the system.  PowerShell doesn't have the issues that come with being 20 years old and based on Basic, provides a more UNIX-like (but still distinctly different) environment, generally runs faster, and gives you access to a lot of stuff that VBScript has a hard time working with.  It's also generally what sane Windows sysadmins use these days, so you're more likely to get actual community support for the scripts if they're PowerShell instead of VBScript.

Alternatively, just use Python, since it's already being bundled (that would additionally mean we don't need to find some alternative to `sendmail` on Windows, since Python has a native SMTP client in it's standard library).

One caveat on the scripting though.  Windows, by default, restricts execution of scripts in it's native scripting languages in current versions for security reasons.  I'm not sure if the installer will be able to selectively set the execution policy for scripts or not, so we may have to add some extra instructions to explain how to do so for users.

**Comment by mfundul** [comment]
About replacing `popen()` we can use [this](https://docs.microsoft.com/en-us/windows/win32/procthread/creating-a-child-process-with-redirected-input-and-output) as reference.

**Comment by vlvkobal** [comment]
Why VBScript and not PowerShell?

**Comment by thiagoftsm** [comment]
No problem @vlvkobal , it looks like I was the unique person in the world using VBscript yet, you are more one vote to change me ! :)

**Comment by mfundul** [comment]
> One caveat on the scripting though. Windows, by default, restricts execution of scripts in it's native scripting languages in current versions for security reasons. I'm not sure if the installer will be able to selectively set the execution policy for scripts or not, so we may have to add some extra instructions to explain how to do so for users.

I believe we can sign our powershell scripts with a netdata certificate and that should do the trick.

**Comment by Ferroin** [comment]
> I believe we can sign our powershell scripts with a netdata certificate and that should do the trick.

Possibly.  I was under the impression though that the default execution policy on at least client systems doesn't even allow signed script execution.

**Comment by mfundul** [comment]
> 
> 
> > I believe we can sign our powershell scripts with a netdata certificate and that should do the trick.
> 
> Possibly. I was under the impression though that the default execution policy on at least client systems doesn't even allow signed script execution.

It appears that you are correct, non-server systems without a group policy will be restricted by default. That is going to be problematic, especially since you can't set group policy in Windows 10 Home editions.

**Comment by Ferroin** [comment]
> It appears that you are correct, non-server systems without a group policy will be restricted by default. That is going to be problematic, especially since you can't set group policy in Windows 10 Home editions.

Does `set-executionpolicy` work from an administrative PowerShell instance in Home editions?  Because that's the other way to go about it, and I'm pretty sure it doesn't need GPO support.

Even if that does work though, this would be another reason to look at using Python (since it doesn't have such restrictions).

**Comment by mfundul** [comment]
> 
> 
> > It appears that you are correct, non-server systems without a group policy will be restricted by default. That is going to be problematic, especially since you can't set group policy in Windows 10 Home editions.
> 
> Does `set-executionpolicy` work from an administrative PowerShell instance in Home editions? Because that's the other way to go about it, and I'm pretty sure it doesn't need GPO support.
> 
> Even if that does work though, this would be another reason to look at using Python (since it doesn't have such restrictions).

If I recall correctly it works, I can't test it right now, I only have access to Windows 10 Professional edition.

**Comment by thiagoftsm** [comment]
Considering the GPO I think it is the best option we use Python, because it will be useful for all OS case we decide to abandon the shell script one day.

**Comment by Ferroin** [comment]
> Please let me assume (make explicit statement) that Windows support will be done in the current project - there will be no separate netdata project for Windows.

I can't say conclusively yes since I'm only a volunteer, but that does appear to be the intended direction here.  Unless I'm mistaken, a large part of this is a plan to shift as much as possible to libuv, which should, in theory, allow us to avoid many of the cross-platform issues.

> Windows. One possible way to do this is to use CMake (http://www.cmake.org) CMake is very popular build tool which is used in many opensource projects for cross-platform compilation, testing and packaging. Many developers are familiar with it. The Visual Studio supports CMake projects, and the command line build is also possible on Windows platform.

I believe that there are already plans to shift to CMake in general, though there hasn't been much news in that area recently.

**Comment by thiagoftsm** [comment]
Hi @alpes214 ,

We already had initial tests using an executable and our final goal is to have a windows service. About Cmake, it is already present in Netdata. 
Do not worry, we won't have two different Netdata, the same will run on all operate system, as @Ferroin said we will use common APIs like libuv for both. 
Thanks to remember us about C runtime libraries! I already had bad experience in the past in try to run a software without it on some hosts running Windows.
Considering that VB has a free version now, we will also use it, but the majority of the development time will be with Mingw. 

Thanks a lot @alpes214 and @Ferroin  by your tips, all them will be considered while we are developing!

**Comment by alpes214** [comment]
> Thanks a lot @alpes214 and @Ferroin by your tips, all them will be considered while we are developing!
@thiagoftsm the Windows support task is really big one. If you know parts of this task that I can work on, then please let me know. I will be able to help you with coding/testing.
