### ISSUE TITLE
rpm version should be 1.16.0 not v1.16.0 (extra "v")

### ISSUE THREAD

**Issue by Wing924** [netdata/netdata#6409]
##### Bug report summary
rpm package version should be `1.16.0` not `v1.16.0`

##### OS / Environment
CentOS 6/7

##### Component Name
package

##### Steps To Reproduce
```
$ yum info netdata
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: ftp.tsukuba.wide.ad.jp
 * extras: ftp.tsukuba.wide.ad.jp
 * updates: ftp.tsukuba.wide.ad.jp
Available Packages
Name        : netdata
Arch        : x86_64
Version     : v1.16.0
Release     : 1.el7
Size        : 8.4 M
Repo        : netdata/x86_64
Summary     : Real-time performance monitoring, done right!
URL         : http://my-netdata.io
License     : GPLv3+
Description :   netdata is the fastest way to visualize metrics. It is a resource
            : efficient, highly optimized system for collecting and visualizing any
            : type of realtime timeseries data, from CPU usage, disk activity, SQL
            : queries, API calls, web site visitors, etc.
            :   ne
```

##### Expected behavior
`Version     : v1.16.0` -> `Version     : 1.16.0`

**Comment by paulkatsoulakis** [comment]
Hello @Wing924, thanks for your report!
Is this from our own distribution?
We have #5983 to permanently eliminate the 'v' from our versioning schemes, which is a bit complicated and planned for the near future.

In the meantime, our provided binary distributions by packagecloud.io have stripped that 'v' so that versions are compatible.

**Comment by Wing924** [comment]
@paulkatsoulakis 
Yes, it's form packagecloud.io.

**Comment by paulkatsoulakis** [comment]
Yikes, you are right. Hang on tight, because i am reworking a bit on the way we generate the stable RPM because it does not comply 100% with our process and that will include a proper fix on the version too. Sorry for that @Wing924, i 'll be re-generating the packages once i am ready later today.

Thanks for reporting it, you rock!

**Comment by paulkatsoulakis** [comment]
I will be re-publishing the packages and then resolve the issue

**Comment by paulkatsoulakis** [comment]
@Wing924 Hey ya, could you try again and let me know of any issues?
Feel free to reopen if you find any other impediments !
Thanks!

**Comment by paulkatsoulakis** [comment]
```
[root@XXXXX netdata]# yum info netdata
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: mirror.serverius.net
 * extras: mirror.serverius.net
 * updates: mirrors.xtom.nl
Available Packages
Name        : netdata
Arch        : x86_64
Version     : 1.16.0
Release     : 1.el7
Size        : 8.4 M
Repo        : netdata_netdata/x86_64
Summary     : Real-time performance monitoring, done right!
URL         : http://my-netdata.io
License     : GPLv3+
Description :   netdata is the fastest way to visualize metrics. It is a resource
            : efficient, highly optimized system for collecting and visualizing any
            : type of realtime timeseries data, from CPU usage, disk activity, SQL
            : queries, API calls, web site visitors, etc.
            :   ne
```
