### ISSUE TITLE
Hierarchical disk usage for directories

### ISSUE THREAD

**Issue by dozham** [netdata/netdata#6456]
##### `baobab`-like disk usage analysis
Hey there,
Is it possible to add a plugin like `baobab` (on GNOME systems) which analyzes the disk usage of every directory? (Or does something like this already exist?)
I guess it would be quite useful for server monitoring tasks.

Thanks in advance.

**Comment by mfundul** [comment]
Let me add that adding such a collector would need to scan thousands or millions of files and it's **not** going to be lightweight. In my opinion this would need to be off by default.

**Comment by vlvkobal** [comment]
For the Ideation phase.

**Comment by thiagoftsm** [comment]
Hi @mfundul ,

We can trace this using eBPF, but we would need to have a great storage to save all changes.

**Comment by Ferroin** [comment]
@thiagoftsm Strictly speaking, we would only need to store history for the volume root (we're already doing this though), leaf directories, and any folders that are being tracked via alarms (because that needs to be fast as possible). The overhead of computing history for other nodes on-demand shouldn't matter much for most users, so there's not much point in tracking it constantly.  If we then store changes instead of continuous values for everything except the volume root, we could cut down on storage use even further for the common case of most directories only changing infrequently.

Even if we get optimal efficiency though, I agree with @mfundul that this should be off by default, as any approach is going to have some issues (event-based gives users another potential DoS vector to attack the system with, polling uses tons of resources).

Very high granularity configuration would be nice too.  For most people, most of what this is likely to be used for is tracking usage in specific directories that are potentially problematic.

**Comment by thiagoftsm** [comment]
Hi @Ferroin ,

This would reduce the number of data that we will store, I am working now with eBPF related to Network, when I have a time, I will write a test code that will measure this possible feature more deep for we have a better estimation of sizes.

**Comment by mfundul** [comment]
@thiagoftsm I don't think eBPF is a good idea when there are already user-space mechanisms such as inotify, kqueue etc. There is also the libuv FS event API.

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
