### ISSUE TITLE
SSL=force redirection doesn't include port

### ISSUE THREAD

**Issue by KrisShannon** [netdata/netdata#6471]
##### Bug report summary

With SSL=force and using the default port of 19999 the Location header returned for the redirect has no port.

Connecting to http://localhost:19999/ returns a 301 to https://localhost/

##### Netdata version (output of `netdata -V`)

netdata v1.16.0

##### Expected behavior

The location returned should include the port (e.g. https://localhost:19999/ )

I believe this is due to [web/server/web_client.c lines 1030-1040](https://github.com/netdata/netdata/blob/master/web/server/web_client.c#L1030-L1040)

**Comment by cakrit** [comment]
Thanks @KrisShannon, we'll publish a patch to 1.16 when this issue and #6457 are resolved.

**Comment by thiagoftsm** [comment]
Hi @KrisShannon ,

You are right when say the code that mounts the URLs that are delivered back for the user, but I identified the problem in other region of the code. In the PR(#6468) that I am delivering the fix for this specific problem, I could get the correct redirect with the script that is together the PR as you can see in the logs bellow:

log_badge.txt:< Location: https://127.0.0.1:19999/api/v1/badge.svg?chart=cpu.cpu0_interrupts
log_health.txt:< Location: https://127.0.0.1:19999/api/v1/manage/health?cmd=LIST
log_index.txt:< Location: https://127.0.0.1:19999/
log_info.txt:< Location: https://127.0.0.1:19999/api/v1/info
log_nc.txt:< Location: https://127.0.0.1:19999/netdata.conf

Be free to test the solution that we are giving before we commit it!

Best regards,
