### ISSUE TITLE
allmetrics endpoint and metric unit

### ISSUE THREAD

**Issue by fmercier-almerys** [netdata/netdata#6482]
Hi

Just simple question . Is allmetrics endpoint return fixed metrics units or it can change dynamically (like charts) or by plugins configurations ?

**Comment by cakrit** [comment]
> can units change dynamically (like charts)?

Autoscaling is done by the UI only (`dashboard.js`). So you won't see MiB now and GiB later. 

> can units change by plugins configurations?

I had never tried to change the `units` of a chart in `netdata.conf` before, since the units are coming directly from the collector. I just did it for one chart and it immediately changes the units string I see in the allmetrics response and on the chart. So the answer to this second question is yes.
