### ISSUE TITLE
Metric Association: Tag Support for Containers (K8s)

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#6503]
### Target
- Support labels and tags in Netdata data model. 
 
### Why?
- Labels/tags are a primary enabler for several projects like Kubernetes data collections, and custom charts. They enable aggregation of metrics across different dimension. For example, aggregate CPU/Memory across containers (see example below).

Cluster:
  - Namespace
    - pod
       - container
         - [metrics] resource util (cpu. mem)
         - applications
           - [metrics] app1 (app specific)
           - [metrics] appN (app specific)
        - containerN
    - podN
  - NamespaceN

### What?
[ ] Assign a team to perform a feature design

**Comment by Saruspete** [comment]
Hello,

Would that feature also include "events" (like a vertical bar) in the graphs ? That would be very helpful to have a pinpoint of some events for troubleshooting. 
Multiple times I would have loved to add a mark for "kernel changed", "Application restart", "time adjustment", and many many others events that may be manual or automated.

Many thanks

**Comment by cakrit** [comment]
We definitely want to provide support for events as well. Surprisingly, I couldn't find an open issue on that, so I created #6523. 
They won't be covered by labels/tags though, that's just a way to group and filter metrics (or possibly charts).

**Comment by cakrit** [comment]
Writing in more detail what a user would want to do with labels. Of course we urge the community to jump in. But first off, what are labels? 
- Labels are name/value pairs attached to particular entities: hosts, charts and dimensions to begin with, but they could also be useful for alarms, events and log entries. 
- Labels can be automatically generated during runtime, or be configured ahead of time.
- Labels are supposed to be relatively stable and fixed across large periods of time. i.e. even if they are auto-generated, we do not expect to see differences in the labels attached to a particular instance within a few hours or days. Of course, new instances with the exact same labels could be added and removed all the time. 

Note: Several netdata entities already have several such name/value pairs, we just don't call them labels or support most of the use cases described below. Examples:

Interesting host name/value pairs (from `api/v1/info`):
```
	"version": "v1.16.1-189-gda883914",
	"os_name": "Manjaro Linux",
	"os_id": "manjaro",
	"os_id_like": "arch",
	"os_version": "18.0.4",
	"os_version_id": "unknown",
	"kernel_name": "Linux",
	"kernel_version": "4.19.59-1-MANJARO",
	"architecture": "x86_64",
	"virtualization": "none",
```

Interesting chart name/value pairs:
```
                        "id": "system.swapio",
			"name": "system.swapio",
			"type": "system",
			"family": "swap",
			"context": "system.swapio",
			"title": "Swap I/O (system.swapio)",
			"plugin": "proc.plugin",
			"module": "/proc/vmstat",
			"chart_type": "area"
```

Dimension name/value pairs (converted to labels for prometheus, via the `api/v1/allmetrics` call):
```
netdata_info{instance="chris-msi",application="netdata",version="v1.16.1-189-gda883914"} 1
nd_system_swapio_KiB_persec_average{chart="system.swapio",family="swap",dimension="in"} 0.0137776
```

To keep the posts short, the next comment will have a list of high level use cases for the agent and the cloud.

**Comment by cakrit** [comment]
## High level user stories - Essential

### Agent

As a user, I want to:

- Configure static labels for each of my hosts via `netdata.conf`. E.g:
```
host labels = region=EMEA purpose="Web Server" infra=Staging
```
- Configure static labels for each chart in `netdata.conf`. e.g.
```
[system.idlejitter]
labels = my-chart-groupings="Interesting system charts"
``` 
- Configure static labels for each collector job. E.g. for `/etc/netdata/go.d/nginx.conf`
```
jobs:
  - name: local
    url: http://localhost/stub_status
    labels: type=Customer customer="Acme Inc."
```
- Search and filter my hosts from the drop-down nodes menu, based on labels attached to those hosts. The list of labels should include host name/value pairs generated by netdata, such as the ones mentioned in https://github.com/netdata/netdata/issues/6503#issuecomment-531163160. All searches and filters should accept wildcards
- Filter the charts I see based on labels attached to those charts, including at least context, family. All searches and filters should accept wildcards.
- Save filters for hosts and charts, (e.g. bookmarks) so I can use them later. Regardless of whether I filtered only on hosts or only on charts or both, the bookmark should take me to the same view. 
- Include all host and chart labels to the archiving streams (e.g. Prometheus). 
- _Specify which metrics should be included in the archiving streams by specifying host and/or chart labels?_

## Cloud

As a member, I want to:

- Search and filter hosts using labels, everywhere where a node search/filter is presented. 
- Save the filter itself, so that any new nodes matching the saved criteria are automatically added to a room. 

## High level user stories - Phase 2

Once custom dashboard are available on netdata.cloud, I want to:
- Use host and chart labels to search and filter the charts that will be shown in a custom dashboard. As with hosts, any new charts matching the filter should also be displayed.
- Create custom charts comprised of dimensions from hosts and charts that match the specified host and chart labels.

*Note* - Labels on dimensions have been deliberately left out these stories, as we can offer significant functionality without that capability. TBD based on comments and follow-up refinement if and when we will need to add such support.

**Comment by thiagoftsm** [comment]
@cakrit , please, only to confirm, when you wrote:

> All searches and filters should accept wildcards

Were you talking about Netdata simple patterns? Or will we extend the concept for the most common used wildcards?

**Comment by Ferroin** [comment]
The most useful application I can think of for labels is actually alarms.  You could use them to group a collection of resources that are logically related (for example, all the disks in a specific external enclosure, or all the NIC's connected to a particular NUMA node, or all the portcheck dimensions for a particular remote system) and then use the label information to provide specific alarms for that group of resources.  If we were to do this and also send the labels with alarm notifications, they could also be used for alarm correlation (for example, if all the disks in a particular external enclosure are having issues, it may be a problem with the enclosure or it's connection to the system instead of the disks themselves).

**Comment by cakrit** [comment]
> @cakrit , please, only to confirm, when you wrote:
> 
> > All searches and filters should accept wildcards
> 
> Were you talking about Netdata simple patterns? Or will we extend the concept for the most common used wildcards?

I was just thinking about wildcards like * but you're correct, [simple patterns](https://docs.netdata.cloud/libnetdata/simple_pattern/) are much better and have the additional benefit of including NOT and OR in the statement.

**Comment by cakrit** [comment]
> The most useful application I can think of for labels is actually alarms. You could use them to group a collection of resources that are logically related (for example, all the disks in a specific external enclosure, or all the NIC's connected to a particular NUMA node, or all the portcheck dimensions for a particular remote system) and then use the label information to provide specific alarms for that group of resources. If we were to do this and also send the labels with alarm notifications, they could also be used for alarm correlation (for example, if all the disks in a particular external enclosure are having issues, it may be a problem with the enclosure or it's connection to the system instead of the disks themselves).

Where do you envision these labels defined? host, chart and job as I mentioned and then it's just a matter of attaching the labels to the alarms, or something different? If it's the same configuration, then we can start with two more stories:

### Agent Health Monitoring

As a user, I want to:
- Receive alarm notifications that include host and chart/job labels for the particular alarm.
- Search and Filter alarms based on host and chart/job labels.

For centralized health monitoring (in netdata.cloud) we'll need some more thought/discussions.
For alarm correlation, I'm not clear on the what and how. Haven't had any experience with it.

**Comment by Ferroin** [comment]
> Where do you envision these labels defined? host, chart and job as I mentioned and then it's just a matter of attaching the labels to the alarms, or something different? 

What I'm thinking is just using the labels defined on host/chart/job/dimension directly.  That way the user can still leverage the same logical groupings through the alarm configuration that they can through the dashboard.  In fact, having that close linkage between what's seen in the dashboard and what's seen in alerts is kind of important for being able to actually understand the alerts.

> For alarm correlation, I'm not clear on the what and how. Haven't had any experience with it.

You probably already do it to a certain degree 'by hand' by looking at things like the chart name.  In essence, I'm talking about using labels as a way to see that a given series of alerts are probably related.  Expanding a bit on the example I made previously, if you've got an external disk enclosure with a bunch of disks, and all the disks are showing errors on a regular basis, correlating those errors leads to the logical conclusion that it's probably an issue with the enclosure (or the cabling to it, or the storage controller it's connected to), not the disks themselves.  If you've got some label to help remind you all those disks are in a specific external enclosure, it saves you from having to remember yourself that disks `sdg` through `sdn` are all in a single external enclosure.

Internally to Netdata, this could be used as one way to control whether alerts trigger based on the state of other alerts, or alternatively coalesce multiple alert conditions into a single actual alert.

Externally, it would provide another way to sort and categorize alert messages, as well as helping to determine the root cause of a high-level error observed in a system monitored by Netdata.

**Comment by vlvkobal** [comment]
We had a short discussion with Ilya, and I'd say that labels should be attached to metrics, not to other entities. Hosts, charts, jobs are kind of labels by itself.

It's a universal solution we can use everywhere: alarms, UI, archiving... it doesn't matter where exactly.

**Comment by Ferroin** [comment]
> We had a short discussion with Ilya, and I'd say that labels should be attached to metrics, not to other entities. Hosts, charts, jobs are kind of labels by itself.

I think that's sensible for internal usage, but I would argue that there are cases where you need to group charts, jobs, and hosts that don't just fall into that hierarchy.  In fact, I can think of a few dozen complex queries that are perfectly reasonable things to look up through Netdata but couldn't be directly represented unless you had some way to either label all dimensions in a host/job/chart or have labels for hosts/jobs/charts.

Note, I'm not saying that we need to actually apply labels to charts/jobs/hosts, just that there should be some way to configure things like 'all dimensions from host X should have label Y' so that users don't have to think about what specific dimensions are provided by any given host/job/chart, but can specify logical groupings like this.

**Comment by cakrit** [comment]
Metrics MUST inherit the labels from the host/chart/job either directly (i.e. in the metrics DB for each dimension) or indirectly (don't bother saving the same exact host label for every single metric from that host, just make sure you can retrieve the info when you try to filter). As @Ferroin said though, this is a somewhat internal matter. We still need to be able to efficiently filter entire hosts, as described in the stories. 

Metrics could also potentially have additional labels that only exist on the level of a dimension. Examples:
 - I could group in `disk_space` the dimensions `used` and `reserved for root` together with a label `category=used` and leave the dimension `avail` in `category=free`. 
 - I can label the k8s `Bytes Used By The Pod Logs On The Filesystem (k8s_kubelet.kubelet_pods_log_filesystem_used_bytes` dimension `kube-dns-b46cc9485-4mt4f` as `type=kube-dns`.

However, while writing the stories, I noticed that the most important cases can be covered even without these additional, metric-level labels.

**Comment by Saruspete** [comment]
Hello,

Taking the multiples issues netdata helped me to investigate on my 2k parc, I had :
- On the same server, different people may want to focus on different metrics. Eg, one team will want CPU+RAM+Interrupts, another on the same server will want  Overview + Network
- Some tags are changing. For performance sensitive applications, we isolate some CPUs from the linux scheduler (or put them in cgroup) and (don't) want to focus on these. Same for their affiliated softirq and interrupts.
- For the disk_space, most users don't care about /, /opt or multiple other FS. they just want their subset of interesting charts (eg, "myapp", which would filter on their FS + The interface hosting their IP + the CPUs on which their app is in the same cgroup.

Same goes for the alerting: we currently give teams the ability to create a health file where their team name is appended, then filter on this: if a custom file with their team-name  is created (disk.myteam.conf) and the alert comes from the "parent" file "disk.conf" or another team "disk.otherteam.conf", discard the alert.
Being able to filter on the label would be nice as "configure one place only": If you receive an alert, send a notification for all recipients in the "team" or "notify" label.

For the web interface, being able to select / filter the Charts i'm interested in would avoid veeeeery long scroll back and forth (ever tried to scroll over the CPU section with 40 cores ?).
Or maybe to "pin" some charts that would be of interest to follow the scrolling, atop.

**Comment by mfundul** [comment]
I think we need to clarify the definitions a little bit. What are the implications of changing a label of an entity (host, chart, dimension, etc)?

Is it the same entity as it was before, or is it a new entity defined by the combined uniqueness of its id and label? In case:
  - it remains the same entity, any query with the old labels will fetch no results. This means that historical data (for the entity) will be tagged with the new label for any time range in the past. In this case we define the label lifetime as universal but the labels themselves are ephemeral (they are forgotten if the user changes them).
  - it defines a new entity, then the labels are part of the id of the entity. Every entity should be stored in some kind of database, and historical data (for the entity) will be tagged with the labels that were defined in that time period. In this case the label lifetime is tied to the entity lifetime and the labels are persisted as part of the historical data.

**Comment by Ferroin** [comment]
@mfundul Perhaps have a history for labels, but not new entities each time they're changed?  IOW, you can search on old labels, and get the relevant data within the time range they applied, but you don't have 'new' dimensions or charts when you change labels, the existing ones just have different labels.

It would be nice though to be able to specify a point in time to use as the reference for labels though during searches.  I can think of many cases where you might want to search old data based on current labels, or vice-versa.

**Comment by mfundul** [comment]
So @Ferroin what you're proposing is:
  - define entities with a unique ID
  - define labels with a pointer to an entity and a time range (in addition to the name - value pair)

This is going to be the toughest to implement I reckon!

**Comment by mfundul** [comment]
An issue with your proposal @Ferroin is that labels are already part of the definition of entities. For instance, for a `chart` entity the `id` `type` or `family` labels are already part of the unique id of the chart itself.

It is going to be ugly to have 2 very different types of labels, one type that defines entities and another one that has its own history.

**Comment by cakrit** [comment]
- Host unique ID is the MACHINE_GUID
- Chart unique ID is the chart id (not true that type or family are part of the unique id, e.g. `net.virbr0` and `net.wlo1`. They can both have the same `context`, but that can also be treated as another label).
- Job unique ID I think is the job name
Metrics are the ones that need careful design with the metrics map.

**Comment by mfundul** [comment]
@cakrit the chart id is a concatenation of the chart `id` and chart `type`. Moreover, in your example the prometheus conversion uses the `family` label as well. Moreover, it's even more complicated than that, since those are not really unique outside of their context. What is unique the the host GUID, and then the chart "id" is only unique per host, and then a dimension "id" is only unique per chart.

So, if we're to treat all those properties as labels then my point stands.

If we want to keep some existing fixed properties as they are and implement a new functionality for labels I believe we will confuse the users. As a user I would like to treat everything as a label.

**Comment by Ferroin** [comment]
> It is going to be ugly to have 2 very different types of labels, one type that defines entities and another one that has its own history.

I'm curious why you think we won't need two types of labels anyway if you want to expose chart properties as labels.  They _will_ need special handling because they should not be user editable (unless you want a bunch of users doing stupid things and complaining to us that it doesn't work).  Given that, there's no reason to handle them any differently than we do now, we just need whatever computes labels to read chart properties and expose them as labels.

**Comment by cakrit** [comment]
> If we want to keep some existing fixed properties as they are and implement a new functionality for labels I believe we will confuse the users. As a user I would like to treat everything as a label.

No one blocks you from adding as many labels as you like. Go ahead and create your own "my-family" label if you like, you're just not allowed to mess with the reserved labels that we already have. We could make a very clear distiction between the search/grouping params that are user-defined labels and the ones that netdata provides itself, but I don't see the benefit of the separation anywhere outside the docs. So, I see no reason why I would want to make such a distinction visible on the UI, but the API calls underneath may or may not treat the two types differently.

I suggest we go back to finalizing the user stories though, without any mention of the implementation.
@Saruspete, I need to understand if you believe that the stories I wrote cover the use cases you mentioned, or if we need something additional. The part about the alarm notifications did throw me off a bit, but it sounds like the rest are covered?

**Comment by mfundul** [comment]
In my mind the ideal solution would be that an entity is defined by its labels. All labels will be declared in the database somehow, there will be special handling for storing the default labels, similar to a database migration across netdata versions, but not fundamentally.

This way we can query about labels using time ranges without any distinctions. I also like @Ferroin 's idea about separate timelines of labels but we will need to introduce new GUIDs for entities, and maybe break compatibility. In any case, I don't consider defining labels an implementation detail. I feel it's important to define what a label is as far as users are concerned.

**Comment by Ferroin** [comment]
> This way we can query about labels using time ranges without any distinctions. I also like @Ferroin 's idea about separate timelines of labels but we will need to introduce new GUIDs for entities

Can you please concretely explain why you believe we need some new ID mechanism for labeled entities if we explicitly prevent users from modifying chart properties?  For all the entities we care about we already have some existing ID that's guaranteed to be unique at each instant in time that it exists (hosts have the MACHINE_GUID, charts have the chart name, jobs have the tuple of job name and collector name (you actually can have multiple jobs with the same name provided that they're all for different collectors), and metrics have the tuple of metric name and chart name).  Netdata is _already_ reusing all of those if they are removed and a new one is added with the same ID, so temporal uniqueness isn't a good argument unless you want to completely stop that reuse, but I see no practical benefit to doing so (in fact, it seems to me that it will cause more issues than it might solve).

> In any case, I don't consider defining labels an implementation detail. I feel it's important to define what a label is as far as users are concerned.

Agreed.  How the labels work from a user perspective is an important detail when determining whether they will work for the desired use case.

**Comment by mfundul** [comment]
> 
> Can you please concretely explain why you believe we need some new ID mechanism for labeled entities if we explicitly prevent users from modifying chart properties? For all the entities we care about we already have some existing ID that's guaranteed to be unique at each instant in time that it exists (hosts have the MACHINE_GUID, charts have the chart name, jobs have the tuple of job name and collector name (you actually can have multiple jobs with the same name provided that they're all for different collectors), and metrics have the tuple of metric name and chart name). Netdata is _already_ reusing all of those if they are removed and a new one is added with the same ID, so temporal uniqueness isn't a good argument unless you want to completely stop that reuse, but I see no practical benefit to doing so (in fact, it seems to me that it will cause more issues than it might solve).

My motivation is the following:

At the moment netdata is unable to query about anything that is not currently being collected, let alone something that was collected a year ago. Since all those "fixed properties" are defined by the collector itself, there are many things that can change. The collector may be generating ephemeral charts and metrics with pretty much dynamic "fixed properties". The only way to actually know those entities existed in the first place is for labels to be in indexed storage. Only then can we query for those entities in any meaningful way.

Reusing the same properties later is not going to create a different timeline, it is still the same entity, so we get to keep that functionality.

Moreover, in our roadmap we will at some point try to decouple charts from metrics in some way or another. In general, I don't think we will prevent users from modifying chart properties either directly or indirectly.

**Comment by Saruspete** [comment]
@cakrit quoting your story:

> Configure static labels for each of my hosts via `netdata.conf`

It doesn't provide significant data for a standalone server, but will be useful for cloud. It may be redundant with the tags in the backends, but is still useful when streaming to another netdata host (as you stated in a next point)

> Configure static labels for each chart in `netdata.conf`
> Configure static labels for each collector job

Yes, nice indeed. I would guess the labels for a collector would be inherited by the charts the collector creates ? And then, an inherited label can be overriden on a by-chart basis ?

> All searches and filters should accept wildcards

Wildcard and maybe regex, or at least multiple values. eg, something allowing to sub-select in this kind of pattern (i'm using numbers, but codes are used too): 
- app01-dc1-inst01
- app11-dc9-inst01
- db01-dc5-inst50

If I want a couple db + app, on 3 DCs 1,4, 6, I would write something like: 
`(app|db)01-dc[146]-inst(01|50)`
I think you could apply this to AWS or GCP usual naming.

> Save filters for hosts and charts, (e.g. bookmarks) so I can use them later. Regardless of whether I filtered only on hosts or only on charts or both, the bookmark should take me to the same view.

Yay ! Maybe if it can be generated from the URL, would be nice too when generating the URLs for the user, or when copy/pasting the link between colleagues.

> Include all host and chart labels to the archiving streams (e.g. Prometheus).

I'm not sure about the impact of this one on the generated volumetry in the backend tsdb. This question is mostly for its default value, as it will be useful to many people nonetheless.

Or that would encourage people to put server related (location, model, os...) in these "host-level" labels instead of "backend tags" that are currently appended ? Looks nice too !

> Specify which metrics should be included in the archiving streams by specifying host and/or chart labels?

Yes, a more precise filter would be very nice here. As for the alarms, it's to avoid duplicating work between labels, alerting, configuration, backend filters...

Also, once we could send data to multiple backends (#6769) it would be useful to filter on them: "Backend-TeamA wants labels `system teamA`,  "Backend-Infra" wants labels `!team* *`...


> Note - Labels on dimensions have been deliberately left out these stories, as we can offer significant functionality without that capability. TBD based on comments and follow-up refinement if and when we will need to add such support.

Agreed. A more significant feature would be dimension renaming for backend. It would allow to group dimensions to the same table (lifting some tsdb limits), and with current backend charts filtering, that would allow to select dimensions.

The usage provided by @Ferroin are real-life scenarios, hard to detect by standard tools / counters. But I don't see the difference of just applying the label on a chart (instead of dimension), then applying the filter on the label, the same way it's currently done for templates & families/host/os alarms.
Most elements are already grouped by chart, and they get their real meaning with all dimensions of that chart. Eg, is 64GB RAM usage considered high ? What if it also includes buffer/cache ? Or if the server had its ram upgraded from 128 to 512GB ? 

I'm not against putting labels on dimension, but it seems rather overkill to be, provided the charts are the logical grouping of elements (one chart per interface, per disk, per CPU...).


So, the story looks good to my use-case.

**Comment by Ferroin** [comment]
> It may be redundant with the tags in the backends, but is still useful when streaming to another netdata host

Possible thought on this point, perhaps we could make it such that you could have labels automatically become tags for backends that allow it?

----

On the note of per-dimension labels, the primary benefit I see to having that would be selecting the dimensions for a specific service/application out of the charts provided by the `apps.plugin` collector together with all the charts for that application from other collectors.  How useful that is varies based on what the user is trying to do though.

**Comment by cakrit** [comment]
From @amoss 

> Does this epic cover tags on charts inside each host (#6503 in the netdata repo) ?
> 
> The wording of "When filtering for Nodes or graphs, users can search for these tags" in the acceptance criteria suggests that it might. Some rough questions for the ideation phase:
> 
> * If a user configures labels on a node (i.e. in the config file) how are they communicated to the cloud UI? (I'm wondering if should have a dependency on the agent-cloud link).
> * If a user tags a node, what should the relevant node do?
> * Should the pre-canned fields be a set of known label names that the agent / installer will instantiate with values?
> * How does a user tag a specific chart on a specific node - config-file, cloud UI, combination of both?
> * If a node is restarted and the config-file has changed, which set of labels take priority (new labels on the node, existing labels in the cloud)?

**Comment by cakrit** [comment]
> If a user configures labels on a node (i.e. in the config file) how are they communicated to the cloud UI? (I'm wondering if should have a dependency on the agent-cloud link).

The first step is for the web API to be able to provide labels as metadata for hosts/charts/metrics. The  rest is for the design of the Agent-Cloud Link (ACL).

> If a user tags a node, what should the relevant node do?

- Present the tag on all relevant API calls (if we're talking only about a host tag, that means showing it in api/v1 `info`, `charts`, `chart`, `data`, `alarm_variables` If the tag is at the chart level and below, it doesn't appear in `info`
- Return charts that have that tag in the query for `charts`
- Be able to trigger alarms taking into account that tag (needs a bit more digging)

> Should the pre-canned fields be a set of known label names that the agent / installer will instantiate with values?

Yes, see https://github.com/netdata/netdata/issues/6503#issuecomment-531163160 above.

> How does a user tag a specific chart on a specific node - config-file, cloud UI, combination of both?

Config-file is the only way.  Other methods to change them require #6432 

> If a node is restarted and the config-file has changed, which set of labels take priority (new labels on the node, existing labels in the cloud)?

Cloud learns the labels from the agents, it doesn't maintain its own labels.
