### ISSUE TITLE
Generate an overall status badge/chart for the health of category

### ISSUE THREAD

**Issue by rirze** [netdata/netdata#6536]
##### Question summary
Is there a way to gather the health of multiple charts into one metric/status? For example, if all disks still have free space, have a badge that shows 'Ok' status. If any of the disks are full, that same badge shows "Not Ok" status. 

Is there any way I could conglomerate the status of multiple charts/metrics into one status value? I'm open to using badges, alarms, additional charts, etc.. 

##### Expected results

Example of what I'm looking to emulate [[ https://grafana.com/grafana/plugins/vonage-status-panel ]]

**Comment by ilyam8** [comment]
> Is there any way I could conglomerate the status of multiple charts/metrics into one status value?

Unfortunately no.

**Comment by cakrit** [comment]
This is quite easy to do, if we limit it to alarms. `api/v1/alarms` already returns alarm family, we should be able to add `context` to it and create a new `api/v1/alarmcount` endpoint, with some input params that let us specify which alarms to count. We could do the same with a new badges endpoint (or even the same endpoint that based on a param looks at alarms instead of metrics).

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
