### ISSUE TITLE
[SPIKE] Investigate alternative CI solutions

### ISSUE THREAD

**Issue by paulkatsoulakis** [netdata/netdata#6605]
#### Feature idea summary
It's been a few months we have been heavily using Travis CI for our CI/CD solution.
The problems we have been facing all this time, do not justify the cost behind this.

With this story we intend to investigate the possible alternatives out there and decide on solution that would be a better fit for our needs.

##### Expected behaviour
A more robust, reliable and flexible CI/CD solution for all of Netdata projects

**Comment by cosmix** [comment]
I would consider Gitlab and Prow as options, but the latter is based on (and requires the use of) Kubernetes, which complicates things. I would probably favour Gitlab at this time, given the fact that we will need VMs to properly run e2e/integration tests on different kernels/distros/OSs (so container based solutions don't suffice).

**Comment by paulkatsoulakis** [comment]
There is also github actions that just released, i wouldn't feel confident using a BETA feature though

**Comment by prologic** [comment]
@cosmix Landscape has changed somewhat since the comments herein... I would strongly evaluate either Github Actions and/or [Build Kite](https://buildkite.com/)

We're already using _some_ Github Actions now and so far its working out nicely.

I'd like to spin up our own custom Github Action Runners at some soon (_real soon_) to do our CI/CD packaging which will point Github Action on par with Build Kite.

The _biggest_ thing for me right now with Github Actions is the fact we can leverage Docker-based tooling, knowledge and experience in the same way we're doing with everything else. e.g: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-a-docker-container-action

But also running our own Runners/Agents is a **huge** plus too :)

**Comment by prologic** [comment]
@cosmix Since we've already explored some other CI/CD systems recently and we now have a mix of Travis Ci and Github Actions I'd like to close this and consider this "SPIKE" Done.

Also FWIW between all of us we have experience in the following:

- Jenkins
- CircleCI
- Build Kite
- Drone CI
- Gitlab CI
- Travis CI
- Github Actions
- _and probably a few others_

I _think_ we have more than enough experience/expertise to come up with a decision finally and document it. cc @Ferroin

**Comment by Ferroin** [comment]
> @cosmix Since we've already explored some other CI/CD systems recently and we now have a mix of Travis Ci and Github Actions I'd like to close this and consider this "SPIKE" Done.
> 
> Also FWIW between all of us we have experience in the following:
> 
> * Jenkins
> * CircleCI
> * Build Kite
> * Drone CI
> * Gitlab CI
> * Travis CI
> * Github Actions
> * _and probably a few others_
> 
> I _think_ we have more than enough experience/expertise to come up with a decision finally and document it. cc @Ferroin

Agreed, I'll try to get started on the basic matrix today.
