### ISSUE TITLE
Is there a way to add message on startup?

### ISSUE THREAD

**Issue by arielman** [netdata/netdata#6637]
Hi
My organization agreed to install this tool on our servers, but on condition that a proper message will be present to the user, mentioning this tool is for internal use only. is there a way to do it?

**Comment by ilyam8** [comment]
Hi @arielman 

> a proper message will be present to user

Present where?

**Comment by arielman** [comment]
On welcome screen

**Comment by ilyam8** [comment]
Sorry, i dont understand what is welcome screen.

 - user open `http://x.x.x.x:19999`
 - see msg there? popup msg or what?

**Comment by arielman** [comment]
Yes. popup msg will be great

**Comment by cakrit** [comment]
There's an old "welcome" modal with code to show it that is commented out in main.js, probably because it keeps appearing without checking if you've seen it before. Search for `#welcomeModal` there and you'll find its content in index.html. Of course these files are not customizable, we'd need a PR to enable such a message based on a configuration setting. The configuration should also say if we want it to appear always, or only once per browser, based on a cookie. 

Are you able to make such a PR @arielman? If not, we'll put it on the backlog, it's not a bad idea. We want to do much more with dialogs in the future, e.g. telling people about new features that they may not be aware of.

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
