### ISSUE TITLE
Question: Netdata in a virtualized environment

### ISSUE THREAD

**Issue by gaia** [netdata/netdata#6722]
##### Question summary
A Proxmox host's network is managed by a guest VM running pfSense (proxmox is behind pfSense).

Will Netdata have full access to network metrics?
What would I lose if I installed Netdata as a guest VM?

##### OS / Environment
Debian 10/Proxmox 6.x

**Comment by paulkatsoulakis** [comment]
Hello @gaia, I am not 100% sure i understood your use case, but thinking on the top of my head i would probably do the following:

1) Set up a netdata instance on the pfsense host to make sure we get complete visibility on the machine that has the network management(Instructions: https://docs.netdata.cloud/packaging/installer/#pfsense)

2) Set up a new guest VM, with enough RAM and Disk and install a netdata instance there following these instructions: https://docs.netdata.cloud/packaging/installer/#one-line-installation

3) Set up netdata on pfsense to be slave host on the netdata instance on the guest VM, so that you can access your guest VM to view the stats for the pfsense netdata instance (and any other instance you may want to add in the future).  Details on the various master slave scenarios and how to tackle those you may find here: https://docs.netdata.cloud/streaming/

Also, to answer your questions:

>Will Netdata have full access to network metrics?

The netdata instance on the pfsense host that is managing the network, should have visibility to give you insights. We will probably have to test it out though to be sure, as personally i don't have experience with this specific OS

>What would I lose if I installed Netdata as a guest VM?

Adding netdata on a guest VM will only give visibility to whatever resources are available within that guest VM. In there, the only options to get things outside of the guest VM would be collectors that allow remote access of resources for information like for example kubernetes collectors, vmware  collectors and many more.

@cakrit Kindly confirm my thoughts in case i missed anything

**Comment by gaia** [comment]
Thanks @paulkatsoulakis

I take that _instance_ is what is commonly referred to as _agent_ in other apps.

Seems like I would need to setup:

1. a VM for netdata
2. an instance in pfsense (for network visibility)
3. an instance in the proxmox host (for visibility into HW, LXC and other VM guests)

For #2, as you prob know pfsense runs FreeBSD, and the NIC made available to the pfsense VM is of type VirtIO (with HW offloading off).

I hope this explains better?

**Comment by paulkatsoulakis** [comment]
> Thanks @paulkatsoulakis
> 
> I take that _instance_ is what is commonly referred to as _agent_ in other apps.
> 
> Seems like I would need to setup:
> 
> 1. a VM for netdata
> 2. an instance in pfsense (for network visibility)
> 3. an instance in the proxmox host (for visibility into HW, LXC and other VM guests)
> 
> For #2, (as you prob know) pfsense runs FreeBSD. The two NICs (WAN & LAN) made available to the pfsense VM are of type VirtIO.
> 
> WAN is bridged on the proxmox host to a HW NIC (single uplink).
> LAN bridge is an entirely virtual NIC.
> 
> I hope this explains better.
> 
> PS: Alternatively, I could setup Netdata directly on the host and put an instance in pfSense for network visibility.
> 
> Do I have this right?

Sounds like a good enough approach also.
Keep in mind that the netdata instance that will be used for web access, needs to be carefully set up security-wise to avoid any security risks (in case this is for monitoring a mission critical infrastructure)

**Comment by gaia** [comment]
thanks again.

I will wait for @cakrit to chime in, and for the deb binaries to be released.

**Comment by cakrit** [comment]
I haven't looked into how we get metrics in these cases, I asked @vlvkobal to chip in.

**Comment by vlvkobal** [comment]
I don't see any flaws in the approach, stated in @gaia's [message](https://github.com/netdata/netdata/issues/6722#issuecomment-524558925).

**Comment by cakrit** [comment]
`debian/stretch` and `debian/buster` binary packages are released at https://packagecloud.io/netdata/netdata
They're considered Beta, but you can try them out and let us know. We have some issues with `debian/jessie` that we're trying to figure out.

**Comment by gaia** [comment]
thanks! I will report back.

**Comment by gaia** [comment]
is it possible to get notified when it is out of beta or at least when the build passes?

**Comment by cakrit** [comment]
The nightly DEB build has been passing lately. What did you notice?

**Comment by cakrit** [comment]
Regarding the notification, I created  #6898, which you can follow for updates.

**Comment by gaia** [comment]
> The nightly DEB build has been passing lately. What did you notice?

https://i.imgur.com/eivLv0x.png

**Comment by cakrit** [comment]
Yes, the RPM has issues with RHEL. We've taken them out of the i386 and we'll keep trying to get the issues fixed.

**Comment by gaia** [comment]
So I installed netdata via the .deb in a KVM guest. Thanks for getting that up!
I want to install an agent on the proxmox host and another on the pfsense KVM guest.

I'm confused as to whether there is an agent only install, or it is the same install for the proxmox host and per instructions above for the pfsense guest.

**Comment by gaia** [comment]
still waiting on a update. the team has been very helpful

**Comment by ilyam8** [comment]
@gaia are you still waiting for an answer? 😄i read the issue but i am not clear to be honest

**Comment by gaia** [comment]
@ilyam8 yes, pls see https://github.com/netdata/netdata/issues/6722#issuecomment-544194994.
thank you for popping in :)

**Comment by ilyam8** [comment]
> I want to install an agent on the proxmox host and another on the pfsense KVM guest.

> I'm confused as to whether there is an agent only install, or it is the same install for the proxmox host and per instructions above for the pfsense guest.

Have you installed it on the proxmox host? If no what problems did you face?
