### ISSUE TITLE
netdata/packaging: Create an offline install wrapper for kickstart

### ISSUE THREAD

**Issue by paulkatsoulakis** [netdata/netdata#6748]
##### Feature idea summary
We want to create a mechanism that will make the steps of preparing and executing an offline installation much easier.

At the moment we have only taken the steps to make our kickstart installers capable of executing an installation without the need of downloading any netdata artifacts.

To fully meet the expectations of an offline install, we want to provide a wrapper tool that will do the necessary actions to get netdata on an isolated server in a few easy steps

##### Expected behavior

You are basically asking for a preparation script, which is a layer on top of the offline install of kickstart.

This script will gather all required elements for an offline install basically.
The `offline-install.sh` script would execute the following steps with the `--prepare` switch:

1) Download all required netdata items that kickstart now needs in a folder, including the kickstart.sh script
2) Download all needed binary packages into a folder from the respective repo (yum, apt, etc)

Then using the `--install` switch, it would:
1) Install offline packages to the system
2) run the kickstart with the right flags.

_Originally posted by @paulkatsoulakis in https://github.com/netdata/netdata/pull/6693_

**Comment by ramotswa** [comment]
Something I was thinking - you could just make an ‘offline install’ folder available with every release as part of the assets? That way people can just download that one and move it straight to the target server. Basically means you automate the —prepare part of this process.

**Comment by paulkatsoulakis** [comment]
> Something I was thinking - you could just make an ‘offline install’ folder available with every release as part of the assets? That way people can just download that one and move it straight to the target server. Basically means you automate the —prepare part of this process.

It doesn't sound like a good idea, because we will need the binary packages for all dependencies for the particular distribution. That can't be pre-packaged.

**Comment by paulkatsoulakis** [comment]
hm, unless we create offline tarballs for each distribution.
let me take it with the team also, might be applicable after all

**Comment by Ferroin** [comment]
For Debian and it's derivatives, we could (and absolutely should) leverage [apt-offline](https://github.com/rickysarraf/apt-offline), it's designed for doing exactly this type of thing.

-----

However, why not do something ourselves along the lines of what apt-offline actually does?

At the highest level, what I'm thinking of would look like this:

1. On an internet connected system: Run `kickstart.sh` with a special flag indicating that you're prepping an offline install bundle (probably requiring the distro this runs on to match the target system). It then fetches the Netdata tarball/package for that system type, as well as all the packages needed for the system, and wraps all of them together into a (optionally compressed) tarball.
2. On the target system: Run `kickstart.sh` with a special option, passing in the tarball generated in step 1.  It then uses the contents of the tarball instead of fetching them itself, while intelligently only installing packages that aren't already installed (that should be easy).

This could theoretically be extended to generate a self-extracting archive that handles the install automatically instead of generating a plain tarball.

We could also go a step further for efficiency, and have a special command to get a list of all the packages (and their versions) installed on the target system that could be passed into step 1 above to generate a minimal list of required packages.

**Comment by paulkatsoulakis** [comment]
Actually, i was thinking exactly what you mentioned in the end.
Bundle all requirements together into a tarbal, including binary packages depending the distro we are on.

I don't know if i would want to pump `kickstart.sh` though with more functionality.
i would prefer a wrapper named for example `kickstart-offline.sh` with `--prepare` option that would handle:
1) Fetch all netdata elements in a folder (kickstart.sh, tarballs, checksums, the works)
2) Fetch all binary packages for that particular distro you run the preparation on

Then you get this bundle and including `kickstart-offline.sh` on the bundle and then the user can run `kickstart-offline.sh --install`  to install the local packages and then run kickstart with the --local-files option

**Comment by paulkatsoulakis** [comment]
I like the idea of utilizing apt-offline, but keep in mind that this mechanism will have to work for all supported distros so it might cause some overhead on maintenance

**Comment by Ferroin** [comment]
@paulkatsoulakis Yeah, having a separate tool kind of makes sense.  Perhaps have it leverage `kickstart.sh` for the actual install of Netdata itself, but make sure all the required packages are installed ahead of time.  Might make sense to have it create a bundle as a single file that can be run directly (that is, something like the files produced by [shar](https://linux.die.net/man/1/shar)).

> I like the idea of utilising apt-offline, but keep in mind that this mechanism will have to work for all supported distros so it might cause some overhead on maintenance

I was more suggesting just using it for Debian and Debian-derived systems if possible.  However, depending on exactly how we're doing things, that may just introduce overhead in general even for Debian systems.

**Comment by Ferroin** [comment]
Properly working offline install support will be added as part of the impending overhaul of our installer/updater code.
