### ISSUE TITLE
Stop using GA for anonymous-statistics

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#6765]
##### Feature idea summary
Investigate GA alternatives for our telemetry.

##### Expected behavior
GA does some very strange sampling of the START, STOP, FAILED events we send from our telemetry, resulting in very strange counts. It also has some limitations on the reports we can produce and there's a good chance that requests to GA may be blocked. We want to find something else that exposes an API and permits flexibility in presenting/analyzing the data. 

I had tried Matomo in the past, but had some issues and got the following responses:
```
> The limitation of 16 chars for the unique visitor ID (_id), is problematic though, as we use UUIDs
It's possible to assign UUID as User ID which will eliminate the issue you are facing. Learn more about User ID

> For our use case we have 15 custom dimensions and I saw the limit of 10 active (between action and visit)
You will be able use up to 30 dimensions once you purchase Business Plan.
```

**Comment by cakrit** [comment]
I removed the milestone, we should commit to this before planning it again.

**Comment by cakrit** [comment]
We ask @andrewm4894 to provide an endpoint in Google Cloud so we can send the data directly to our own BigQuery DB. All we'll need to change in the script that sends the anonymous statistics will be the URL of the endpoint and the name of the parameters we send, to make their content more explicit. Any objections?

**Comment by cosmix** [comment]
This is something we can do very easily with a Google Cloud Function. It's a good example why this is going to work well, until in the short term, while we use BigQuery for this, as:

1. It will autoscale to support our needs
2. It provides the APIs to write to BigQuery (via PubSub or other means)
3. It's easy to maintain without having to use third-party systems/services/etc.

At scale, this might get expensive (as can all serverless platforms) and it's also tied to Google/GCP, but we can revisit this if/when this is a problem.

**Comment by cakrit** [comment]
@andrewm4894 we need a public endpoint that accepts either HTTP POST or JSON PUT requests (whatever is easier) with the fields listed below. The result will be an entry in a table called `agent-events` or something similar, with the timestamp of the request and a column for each of the fields. 

It would be great if you could also do a PR to modify the `curl` and `wget` commands in https://github.com/netdata/netdata/blob/master/daemon/anonymous-statistics.sh.in so that it calls that new endpoint. 

Note that we may add more columns/fields in the future, which would obviously require a change to the endpoint, the schema and the script. 

```
NETDATA_REGISTRY_UNIQUE_ID
NETDATA_VERSION
ACTION
ACTION_RESULT
ACTION_DATA
NETDATA_HOST_OS_NAME
NETDATA_HOST_OS_ID
NETDATA_HOST_OS_ID_LIKE
NETDATA_HOST_OS_VERSION
NETDATA_HOST_OS_VERSION_ID
NETDATA_HOST_OS_DETECTION
NETDATA_SYSTEM_KERNEL_NAME
NETDATA_SYSTEM_KERNEL_VERSION
NETDATA_SYSTEM_ARCHITECTURE
NETDATA_SYSTEM_VIRTUALIZATION
NETDATA_SYSTEM_VIRT_DETECTION
NETDATA_SYSTEM_CONTAINER
NETDATA_SYSTEM_CONTAINER_DETECTION
NETDATA_CONTAINER_OS_NAME
NETDATA_CONTAINER_OS_ID
NETDATA_CONTAINER_OS_ID_LIKE
NETDATA_CONTAINER_OS_VERSION
NETDATA_CONTAINER_OS_VERSION_ID
NETDATA_CONTAINER_OS_DETECTION
```

**Comment by andrewm4894** [comment]
i wonder if we should push messages to pubsub instead of a cloud function, and then use a cloud function (or dataflow) to stream from pubsub into BQ. 

I'll look into the various trade offs in the below two options:

(1) send messages straight to a cloud function.
(2) send message to pubsub.

I think (2) might be better as easier to set up dataflow (https://cloud.google.com/dataflow) streaming job using templates like this (https://cloud.google.com/dataflow/docs/guides/templates/provided-streaming#cloudpubsubtobigquery). This might overall have some more advantages over sending things directly to a cloud function. 

Will have a look and update back here.

**Comment by cakrit** [comment]
The tech. solution is for @andrewm4894 and @cosmix, I won't get involved.

**Comment by prologic** [comment]
This _might_ be a stupid question; but why can't we just piggy back off the MQTT telemetry (_yes double word here!_) link to the Netdata cloud itself? ANd take that stream of messages and write a µService whose sole job it is to process these messages -- What it does is entirely implementation dependent -- But we are then free to do whatever we want + plus we are decoupled from any specific tech because we can just swap out this µService for some other implementation (_even take advantage of Go itnerfaces here_). Just a thought and my $0.02 worth.

**Comment by cakrit** [comment]
Because we also need agent telemetry from agents that don't use the cloud. Some of the events have to do with not being able to install the ACLK dependencies

**Comment by cakrit** [comment]
Closing in favor of #8597
