### ISSUE TITLE
Redesign archiving engine

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#6769]
##### Feature idea summary
We will redesign the way we add what used to be called backends into a pluggable archiving engine that can send metrics to multiple different archiving endpoints.

**Comment by vlvkobal** [comment]
# Existing design and its constraints
## Backends

Backend | Type | Buffer type | Formatting | Batch
-- | -- | -- | -- | --
JSON | socket | text (JSON) | per metric | one buffer
JSON plaintext | socket | text (JSON) | per metric | one buffer
Graphite | socket | text | per metric | one buffer
Graphite plaintext | socket | text | per metric | one buffer
OpenTSDB | socket | text | per metric | one buffer
OpenTSDB telnet | socket | text | per metric | one buffer
OpenTSDB http | socket | text | per metric | one buffer
OpenTSDB https | SSL_write | text | per metric | one buffer
Prometheus Remote Write | driver | binary (protocol buffers) | per iteration (form a structure from metrics) | dispatched buffer
Kinesis | driver | text (JSON) | per iteration | dispatched buffer
Kinesis plaintext | driver | text (JSON) | per iteration | dispatched buffer
MongoDB | driver | binary (BSON) | per iteration | dispatched buffer
MongoDB plaintext | driver | binary (BSON) | per iteration | dispatched buffer
Prometheus | API call | text | per metric | one buffer per query

The Prometheus backend has its own format. It’s a special case. It is not related to the archiving engine at all. It doesn’t use backends thread. A Prometheus server scrapes metrics from a Netdata agent using a Netdata API call.

## Architecture
There is only one thread for simple text backends. All data is sent directly through a socket. The send operation is non-blocking. After sending data the read function is called in a loop. If the response is not OK 10 times in a row, the buffer is flushed.

One thread doesn’t allow us to archive metrics to several databases at once.

Backends which use their own drivers dispatch buffer processing to separate threads using means of the drivers.

The Prometheus backend does not push data to a database. The database pulls(scrapes) data from the Netdata agent.

The problem with the existing formatter is that it formats only one metric and is not aware of the whole batch format.

Actually, we have three data flows:
- Text buffer sent through a socket
- API call for Prometheus
- Proprietary drivers

Two types of data:
- text
- binary (created from text data in Prometheus or JSON format)

Two types of formatting:
- per metric
- per iteration (the most tricky is the Prometheus remote write API. It uses a structure so every metric should be packed to a structure and then all these structures should be packed to a big request structure)

Two types of batching:
- buffer flush. Buffer is appended on every iteration. No separation between iterations.
- separate processing of buffer for every iteration.

We have a lot of #ifdefs in our code and further development is blocked by the complexity of the code.

# Future design

## Features to be implemented
- modular design
- multiple backends at the same time
- nonblocking operations

Every backend instance should have a separate thread.

The main thread should prepare a batch. The main thread should prepare data for all dispatching threads. It would be nice if the main thread went through the metrics just once.

Formatters should be extended. Possible pluggable formatters: start and end formatting functions for batches, hosts, charts, metrics.

Information about active backends should be stored in a linked list of structures with formatters, buffers, processing functions, backend monitoring metrics, and communication parameters.

Socket operations should be removed from the main thread. They are not applicable to all backends. Proprietary drivers usually do communication staff by themselves.

Ring buffer for every backend instance (dispatched thread).

After refactoring the archiving engine should be ready for external Web-server library usage. We should use external Web-server library (H2O or curl) instead of raw text buffers and sockets.

Some backends need initialization and shutdown.

At the moment we can standardize the method for configuration of endpoints for all backends as far as all of them use URI. But we have plans to support more external databases so we can’t rely on this method. It’s better to use sections and configure endpoints using a native  

The problem with configuration is how to configure several backends at once and do not introduce a breaking change. It’s possible to use the “type” option as a marker for multiple backends configuration.

Example:
```
[backend]
type = multiple // can be the default value
destination = json:localhost graphite:localhost kinesis:us-east mongodb:https://mongoserver.com/
```

If type is not “multiple”, then only one backend is active and old-style configuration is used.

There is a problem with credentials. We can’t write them to netdata.conf because this file is exposed to all users.

We can use a separate backends.conf for special options/credentials. For every backend there could be a section for every backend instance. backends.conf shouldn’t be exposed. As a destination name, we could use the name of the section and put the URI into this section. It will also solve the problem with sensitive information in URI. Every type of backend can have different options available in its section.

## Questions to deal with

If there is more than one backend of the same type, who should handle the buffer duplication? It depends on the scheme: engine -> instance or engine->backend type->instance. What is the most optimal way?

Should we copy a buffer for every backend thread? Can we share one buffer between two backends of one type? What if one of the backends receives data flawlessly and another one experiences communication problems? What if timeout for one batch of metrics exceeds the update period * number of buffers?

What should we do with the bash backend? nc-backends.sh

# Terminology

The **backend** term can be confusing sometimes, it is used though by some other products in the same sense as we use it. It’s tempting to start applying more accurate terminology, but it is disputable if it worth putting in the effort it needs to be implemented.

Some terms which are used in the industry:
archiving, storage, backing
adapter, driver, plugin, provider, endpoint

**Comment by Saruspete** [comment]
Hello,

I would love if we had a way to store the data in a local file, and to group it by time (eg, rotate the file every hour, or day).
What I have in mind is for servers in DMZ, where you don't want them to open connection, and don't want to load your network link for receiving administrative (non-business) data. That way, if netdata could store the data locally as gzip or lzma, a machine in the lan could connect (eg ssh), retrieve the file, and delete it remotely.

That would allow to act as a "pull" (or scap) from a network view, and bufferize long-term (1 day) the data until the link is not used / reserved for business.

I'm currently implementing it with "nc" & shell, but it's not elegant, nor resilient.
having netdata doing it itself would be a perfect feature !

**Comment by cakrit** [comment]
> Hello,
> 
> I would love if we had a way to store the data in a local file, and to group it by time (eg, rotate the file every hour, or day).
> What I have in mind is for servers in DMZ, where you don't want them to open connection, and don't want to load your network link for receiving administrative (non-business) data. That way, if netdata could store the data locally as gzip or lzma, a machine in the lan could connect (eg ssh), retrieve the file, and delete it remotely.
> 
> That would allow to act as a "pull" (or scap) from a network view, and bufferize long-term (1 day) the data until the link is not used / reserved for business.
> 
> I'm currently implementing it with "nc" & shell, but it's not elegant, nor resilient.
> having netdata doing it itself would be a perfect feature !

So a new archiving endpoint (formerly known as backend) that just writes to disk, in any of the usual formats. How about letting `logrotate` take care of compression/retention/rotation though? Would be nice if we could avoid that hassle.

**Comment by vlvkobal** [comment]
Have you looked at https://github.com/netdata/netdata/blob/master/backends/nc-backend.sh?
> Netdata also ships nc-backend.sh, a script that can be used as a fallback backend to save the metrics to disk and push them to the time-series database when it becomes available again. It can also be used to monitor / trace / debug the metrics Netdata generates.

**Comment by Saruspete** [comment]
> So  a new archiving endpoint (formerly known as backend) that just writes  to disk, in any of the usual formats. How about letting `logrotate` take care of compression/retention/rotation though? Would be nice if we could avoid that hassle.

For logrotate, it would need a signal or an API endpoint to tell netdata to either hop on next file or reopen the default logfile. But that's indeed way less pain than doing the full processing.

> Have you looked at https://github.com/netdata/netdata/blob/master/backends/nc-backend.sh?
Yes, but I don't need the sending part, only the local storage and a little logic to do the split & gzip in files by hour.

**Comment by vlvkobal** [comment]
I've updated the [document](https://github.com/netdata/netdata/issues/6769#issuecomment-530360489) and drawn a [flowchart](https://github.com/netdata/netdata/files/3646533/Archiving.design.pdf).

![Archiving design](https://user-images.githubusercontent.com/22008543/65501939-881ef100-deca-11e9-91c3-bd25661ebaf1.jpg)

**Comment by vlvkobal** [comment]
The only thing left is to decide about a new name for the engine and connectors. So the actual design is done.
