### ISSUE TITLE
Is there a way I can check what was the status in specific time frame?

### ISSUE THREAD

**Issue by arielman** [netdata/netdata#6780]
I have many env installed with Jenkins, and sometimes it gets stuck, and the fastest solution is to restart the Jenkins (unfortunately, there is no much time frame for investigation). Is there a way to go to a specific time frame and see what was the status at that time (CPU, Memory, etc...)?

**Comment by ilyam8** [comment]
I assume you are asking about the GUI. Unfortunately no, there is no way to do it. Actually very nice feature.

**Comment by cakrit** [comment]
I believe @arielman is asking whether it's possible to see what the metrics were in the past, which of course is quite easy, by panning the charts. See https://docs.netdata.cloud/web/#using-charts

You need to have sufficient `history` to do that, so we recommend you set `memory mode` to `dbengine`. 

More options to quickly navigate to the past will be available in future versions. We first need to complete the refactoring of the UI to React.js, a project that's already in progress.

**Comment by ilyam8** [comment]
> by panning the charts

Oh, ofc, in my defense - i had something completely different in mind while answering. 

Because of

> a way to go to a specific time frame

Like go to a specific time period in one click withoud panning

**Comment by cakrit** [comment]
I know what you had in mind, which is why I mentioned quickly navigating to the past. Perhaps we'll also have a calendar on the new navigation to set from/to, it's something @ivorjvr and @jacekkolasa will look at carefully.

**Comment by mfundul** [comment]
You can try doing the following trick:
- Select the chart you want from the right side of the dashboard.
- Hold the `Shift` key pressed and select a region of the chart with your mouse.
- Notice the address bar that generated a URL such as:
`http://127.0.0.1:19999/#menu_system_submenu_cpu;after=1567755306000;before=1567755570000;theme=slate;help=true`
- `after` is the starting time and `before` is the ending time of the query in milliseconds since epoch. Use something like the [epochconverter](https://www.epochconverter.com/) to convert a time period from your timezone to milliseconds since epoch.
- Update the URL with the new timestamps and refresh your browser window.

This way you can jump to an arbitrary time frame in the netdata dashboard.

**Comment by Ferroin** [comment]
> Use something like the epochconverter to convert a time period from your timezone to milliseconds since epoch.

If you've got access to the command line on a POSIX-like system (such as Linux or BSD), the following command will do the conversion directly:

    echo $((`date -d '<timestamp>' +%s` * 1000))

Just replace `<timestamp>` with the date and time you want to convert.
