### ISSUE TITLE
packages installer failed

### ISSUE THREAD

**Issue by AdPatat** [netdata/netdata#6846]
The experimental packages installer failed.

This is what it says:

Cannot find /etc/os-release
Cannot find valid distribution with lsb-release

I NEED YOUR HELP
It seems I cannot detect your system automatically.
And it seems I cannot find a known package manager in this system.
Please open a github issue to help us support your system too.
admin@RT-AC68U:/tmp/home/root#

please paste your screen here

```

**Comment by paulkatsoulakis** [comment]
Hello,  it looks like you are trying to install on a router.
Your only solution may be to use the pre-compiled binary package.

We had another user trying to install netdata on a router and he faced some problems due to hardware cpu ARCH. (https://github.com/netdata/netdata/issues/6818)

Try the following instructions

1) `curl -Ss https://my-netdata.io/kickstart-static64.sh > /tmp/kickstart-static64.sh` or if this fails, try `wget -O /tmp/kickstart-static64.sh https://my-netdata.io/kickstart-static64.sh`

If both of the above command fail, paste the errors here and i 'll see for another alternative based on your busybox environment

2) `chmod +x /tmp/kickstart-static64.sh`

3) `/tmp/kickstart-static64.sh --dont-wait`

Paste the results here once you 're done.

**Comment by AdPatat** [comment]
Hello @paulkatsoulakis thanks for your thinking with me!
Yes I want to install netdata on mij router but the pre-compiled package gives me version 1.14.0-1.
I did your following instructios:

curl -Ss https://my-netdata.io/kickstart-static64.sh > /tmp/kickstart-static64.sh
chmod +x /tmp/kickstart-static64.sh
/tmp/kickstart-static64.sh --dont-wait

/tmp/kickstart-static64.sh: line 159: id: not found
[: bad number
 ABORTED  Static binary versions of netdata are available only for 64bit Intel/AMD CPUs (x86_64), but yours is: armv7l.

Indeed also a problem due to hardware cpu ARCH.

For now i'm back at the pre-compiled package with:
admin@RT-AC68U:/tmp/home/root# opkg install netdata
Installing netdata (1.14.0-1) to root...
Downloading http://bin.entware.net/armv7sf-k2.6/netdata_1.14.0-1_armv7-2.6.ipk
Configuring netdata.
admin@RT-AC68U:/tmp/home/root# /opt/etc/init.d/S60netdata restart
 Starting netdata...              done.

It works but sadly ;-( an old version

**Comment by paulkatsoulakis** [comment]
We will be working on this, that is an interesting finding i wasn't aware of.
It seems that we have a contributor for opkg

**Comment by AdPatat** [comment]
Great! Let me know if I can help testing in the future.

**Comment by paulkatsoulakis** [comment]
Hello @AdPatat, i think we can close this issue. You can follow #6847 and/or #6848 instead.
Participation from our community is something we love, so feel free to jump in

Thanks again for being part of netdata's culture!
