### ISSUE TITLE
Documentation issues with the standard dashboard

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#6851]
Something is wrong with https://docs.netdata.cloud/web/ and https://docs.netdata.cloud/web/gui/   The second one now has some broken links, e.g. to "contexts", because that section is on the first one. I'm not sure why `checklinks.sh` didn't catch this, it will need some investigation. But it looks like we either have a lot of content on the first one that belongs in the second one, or that we need to move the content of the second one in the first one. 

As an additional note, under "Contexts" we explain that the mouse over shows the context, but we probably need another section to explain that the same mouse over also shows the collector and module that generated this chart.

**Comment by joelhans** [comment]
I thought I'd take a minute to explain some of my thinking when it comes to how I organized these two pages. Mostly, I wanted to decouple information about _all_ dashboards (including custom ones) from information about Netdata's pre-configured dashboard. 

The web dashboards overview page (`web/`) includes information about using charts, and charts/contexts/families/etc, because that information is relevant to _any_ dashboard created with `dashboard.js`.

The standard web dashboard (`/web/gui/`) contains information specific to the dashboard that's available at `http:blahblah:19999`, which is why it's focused on different areas that our specific to our dashboard.

Now, if we need to move content, I would argue for making `web/` more comprehensive in favor of the other way around.

Happy to keep the discussion going—just wanted to be clear about my intentions.

**Comment by cakrit** [comment]
No got it, that's clear.
