### ISSUE TITLE
Config AWS SNS Issue

### ISSUE THREAD

**Issue by zhonglinwei** [netdata/netdata#6865]
##### Question summary
Netdata can't publish the message to SNS, but I try "aws sns ...", its success.
When try to trigger the alarm, error log show me as follow:
2019-09-17 07:20:17: netdata INFO  : MAIN : SIGNAL: Received SIGUSR2. Reloading HEALTH configuration...
Traceback (most recent call last):
  File "/var/lib/netdata/.local/bin/aws", line 19, in <module>
    import awscli.clidriver
ImportError: No module named awscli.clidriver
2019-09-17 07:20:18: alarm-notify.sh: ERROR: failed to send Amazon SNS notification for:
##### OS / Environment
# su netdata
sh-4.2$ echo $PATH
/var/lib/netdata/.local/bin:/root/.local/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin
sh-4.2$ aws --version
aws-cli/1.16.239 Python/2.7.5 Linux/3.10.0-957.1.3.el7.x86_64 botocore/1.12.229
sh-4.2$ aws sns publish --region us-east-2 --subject "test" --message "test" --target-arn myarn
{
    "MessageId": "fdc04413-4619-56c1-9507-11e9cb8f78f1"
}

**Comment by Ferroin** [comment]
> ImportError: No module named awscli.clidriver

This translates to some issue with Python when run by Netdata not being able to find one of the modules that's part of the AWS command-line tool.  It's (probably) not a configuration issue with Netdata itself, but it still shouldn't be happening.

On that note, some extra info would be helpful:

* What specific OS/platform are you on (looks like a RHEL 7 derivative based on the kernel info in the `aws --version` output, but I'm not certain so I'd like confirmation)?
* Which Netdata version are you using?
* How did you install Netdata on this system (package, kickstart.sh, static build, etc)?
* How did you install the AWS CLI tools on this system (through the package manager, manual build and install, etc)?
* Can you try the same `aws sns` command in a shell started using `sudo -u netdata -s` instead of `su netdata`?  This should replicate the actual environment that Netdata would be running the command from much better than `su` does (and will help narrow down the possible causes regardless of whether it works or not).

**Comment by zhonglinwei** [comment]
> > ImportError: No module named awscli.clidriver
> 
> This translates to some issue with Python when run by Netdata not being able to find one of the modules that's part of the AWS command-line tool. It's (probably) not a configuration issue with Netdata itself, but it still shouldn't be happening.
> 
> On that note, some extra info would be helpful:
> 
> * What specific OS/platform are you on (looks like a RHEL 7 derivative based on the kernel info in the `aws --version` output, but I'm not certain so I'd like confirmation)?
> * Which Netdata version are you using?
> * How did you install Netdata on this system (package, kickstart.sh, static build, etc)?
> * How did you install the AWS CLI tools on this system (through the package manager, manual build and install, etc)?
> * Can you try the same `aws sns` command in a shell started using `sudo -u netdata -s` instead of `su netdata`?  This should replicate the actual environment that Netdata would be running the command from much better than `su` does (and will help narrow down the possible causes regardless of whether it works or not).

- My OS/platfrom is CentOS 7.
- Netdata version is 'netdata v1.17.1-35-gfab0d4b'.
- The way to install netdata is 'Install Netdata on Linux manually', the link is https://docs.netdata.cloud/packaging/installer/#install-netdata-on-linux-manually
- Install AWS CLI tools by `pip3 install awscli --upgrade --user`.
- When I try `sudo -u netdata -s aws sns ...`, the result is aws command not found. I think it may related to environmental variables. In xsehll, my login user is centos, then I will change to root by `sudo -s` to install netdata. I have install aws cli tools in centos, root and netdata user for test, but the result is not my expect. Now I have no idea.

**Comment by zhonglinwei** [comment]
> > > ImportError: No module named awscli.clidriver
> > 
> > 
> > This translates to some issue with Python when run by Netdata not being able to find one of the modules that's part of the AWS command-line tool. It's (probably) not a configuration issue with Netdata itself, but it still shouldn't be happening.
> > On that note, some extra info would be helpful:
> > 
> > * What specific OS/platform are you on (looks like a RHEL 7 derivative based on the kernel info in the `aws --version` output, but I'm not certain so I'd like confirmation)?
> > * Which Netdata version are you using?
> > * How did you install Netdata on this system (package, kickstart.sh, static build, etc)?
> > * How did you install the AWS CLI tools on this system (through the package manager, manual build and install, etc)?
> > * Can you try the same `aws sns` command in a shell started using `sudo -u netdata -s` instead of `su netdata`?  This should replicate the actual environment that Netdata would be running the command from much better than `su` does (and will help narrow down the possible causes regardless of whether it works or not).
> 
> * My OS/platfrom is CentOS 7.
> * Netdata version is 'netdata v1.17.1-35-gfab0d4b'.
> * The way to install netdata is 'Install Netdata on Linux manually', the link is https://docs.netdata.cloud/packaging/installer/#install-netdata-on-linux-manually. In xsehll, my login user is centos, then I will change to root by `sudo -s` to install netdata.
> * Install AWS CLI tools by `pip3 install awscli --upgrade --user`.
> * When I try `sudo -u netdata -s aws sns ...` after` sudo -s` change to root user, the result is "/bin/bash: aws: command not found", but I try `sudo -u netdata -s /var/lib/netdata/.local/bin/aws sns publish...`, it works fine.  I have installed aws cli tools in centos, root and netdata user for test.

**Comment by zhonglinwei** [comment]
I also try custom_sender function, but it give me same result. As follow:
2019-09-19 14:40:33: netdata INFO  : MAIN : SIGNAL: Received SIGUSR2. Reloading HEALTH configuration...
Traceback (most recent call last):
  File "/home/netdata/sendmessage.py", line 5, in <module>
    import requests
ImportError: No module named requests

I think it is related to environment variable. I don't know how to configure environment variables to adapt to netdata, and there's no documentation on the wiki.

**Comment by Ferroin** [comment]
Ran some quick tests on my end, and I've not been able to reproduce this on any of my own systems.  I'm going to try on a CentOS VM next (unfortunately I probably won't get a chance to do so until this weekend) with a setup as close to what you've described as possible.

I suspect that you are correct that it's an issue with environment variables though.  The easiest way to find out is to ask Python itself where it's looking for modules using `python -m site` (should spit out a list of paths and a couple of variables).  If we could compare the results of that run from a shell as the Netdata user and run from the custom_sender function (probably redirect the output for that to a file and check the file contents), it may shed some light on what exactly is going on.

**Comment by zhonglinwei** [comment]
The result of command from shell:
sys.path = [
    '/var/lib/netdata',
    '/usr/local/python37/lib/python37.zip',
    '/usr/local/python37/lib/python3.7',
    '/usr/local/python37/lib/python3.7/lib-dynload',
    '/var/lib/netdata/.local/lib/python3.7/site-packages',
    '/usr/local/python37/lib/python3.7/site-packages',
]
USER_BASE: '/var/lib/netdata/.local' (exists)
USER_SITE: '/var/lib/netdata/.local/lib/python3.7/site-packages' (exists)
ENABLE_USER_SITE: True

The result of command from function:
sys.path = [
    '/etc/netdata',
    '/usr/local/python37/lib/python37.zip',
    '/usr/local/python37/lib/python3.7',
    '/usr/local/python37/lib/python3.7/lib-dynload',
    '/usr/local/python37/lib/python3.7/site-packages',
]
USER_BASE: '/var/cache/netdata/.local' (doesn't exist)
USER_SITE: '/var/cache/netdata/.local/lib/python3.7/site-packages' (doesn't exist)
ENABLE_USER_SITE: True

How to fix it perfect?

**Comment by Ferroin** [comment]
I suspect you may be able to get it working by creating a symbolic link at `/var/cache/netdata/.local` pointing at `/var/lib/netdata/.local`, although that's really just a short term fix. The import search paths shouldn't be different to this degree in the first place, though I'm not sure why they would be different.

@ilyam8 Any ideas?  Looks to me like we might be overriding environment variables that we shouldn't be when invoking external commands, but I wouldn't begin to know where to look to confirm this.

**Comment by Avik1993** [comment]
@Ferroin Were you able to resolve this? 
I am facing similar issue, `aws sns` command works fine with `netdata` user but when triggering alerts, logs file say:
```
2019-10-18 11:19:15: alarm-notify.sh: ERROR: failed to send Amazon SNS notification for: ...
```

@ilyam8 any pointers?

**Comment by ilyam8** [comment]
to be honest i dont really understand the problem

> 2019-10-18 11:19:15: alarm-notify.sh: ERROR: failed to send Amazon SNS notification for: ...


So it says `failed` without the reason?

Have you tried debug it?

> https://docs.netdata.cloud/health/notifications/#testing-notifications

**Comment by Ferroin** [comment]
@ilyam8 It's not finding the AWS python modules used by the `aws` command because the Python search paths are wrong.

See https://github.com/netdata/netdata/issues/6865#issuecomment-533390508 for an example, but I've confirmed similar behavior on my Gentoo systems as well.  We're doing _something_ (I'm not sure what) that's causing Python to use different search paths when invoked by Netdata itself (or a command called by Netdata) than when it's run from a shell as the `netdata` user.  The issues I was seeing when testing #4008 may be related, but I've had no more luck here tracking down the root cause.

**Comment by ilyam8** [comment]
> We're doing something (I'm not sure what) that's causing Python to use different search paths when invoked by Netdata itself (or a command called by Netdata) than when it's run from a shell as the netdata user.

i see it uses `~` to get userbase, usersite paths

> https://docs.python.org/3/library/site.html#site.USER_SITE

**Comment by ilyam8** [comment]
Where are `the AWS python modules`? In what dir?

**Comment by Ferroin** [comment]
@ilyam8 Indeed, though that shouldn't be making a difference.  Unless I'm mistaken, it should be using the same logic as [`os.path.expanduser()`](https://docs.python.org/3/library/os.path.html#os.path.expanduser) to figure out the correct prefix for the user base, and nothing I can find is modifying anything that that would be looking at.

However, I may have missed something in the C code, and if we're setting the `HOME` environment variable from there, that would end up propagating out to both the `python.d` plugin (thus probably explaining the issues with #4008) and the environment for `alarm-notify.sh` (which would be causing the issue here).

**Comment by Ferroin** [comment]
> Where are the AWS python modules? In what dir?

In the case reported by @zhonglinwei, they're installed in the local user base for Netdata using `pip`.  That would also mean the explanation from my previous comment would explain why I couldn't reproduce this issue on CentOS when I tried, I installed them at the system level, not locally for the Netdata user, so the different user base wouldn't have affected me.

**Comment by ilyam8** [comment]
https://github.com/netdata/netdata/blob/7ff016ea74261246def5500308f17cb575059856/daemon/main.c#L627

**Comment by Ferroin** [comment]
@ilyam8 Yep, that's almost certainly the root cause.

Kind of curious _why_ we're setting that unconditionally (I mean, it makes sense in a container where Netdata is PID 0, but otherwise it should (in theory) be a no-op).

**Comment by Ferroin** [comment]
Setting up a test to confirm that the above mentioned line is indeed the root cause here (should be easy to reproduce now that I know what's going on).  I'll report back once I've finished testing.

**Comment by ilyam8** [comment]
i am 100% sure it is the root cause 😄

**Comment by Ferroin** [comment]
@ilyam8 There might be something else in addition to that though.  I doubt it, but it's still good to check. Build just finished for the test version with that line commented out, checking now to ensure that I can't repro the issue without that line.

**Comment by Ferroin** [comment]
OK, it does appear to be the sole cause here.  Given that, I'd be inclined to say that this is a bug, and should be treated as such.

**Comment by ilyam8** [comment]
@thiagoftsm @vlvkobal @cakrit

**Comment by ilyam8** [comment]
@Avik1993 i guess you install asw cli via

> $ pip3 install awscli --upgrade --user

?

To get it working you need to install it w/o `--user` flag

**Comment by Ferroin** [comment]
Creating a symlink where Python thinks the modules should be like I mentioned in https://github.com/netdata/netdata/issues/6865#issuecomment-533516217 should also work.

**Comment by Ferroin** [comment]
This has been root-caused as an issue in our handling of the environment on startup. We're unconditionally setting `$HOME` instead of preserving any existing value that may be set, which leads to us using the wrong Python search paths. In theory I could fix this myself, but it's almost certainly better to have someone from @netdata/agent do so as I'm not a C dev.

**Comment by cakrit** [comment]
The value env variable "HOME" can be provided in `netdata.conf` `[global]` section, `home directory`. (See https://github.com/netdata/netdata/blob/master/daemon.main.c#L544)
The default value is `CACHE_DIR`, i.e. the same as the cache directory (https://github.com/netdata/netdata/blob/master/daemon/common.c#L14)

So to set a better default value, we could perhaps define one more directory like the others in `common.c` and get its value the same way we get the others (I don't remember if it's at compile time or install time).

**Comment by cakrit** [comment]
Where do we use `HOME` though, other than in Python? Tests to verify that we're setting it correctly can be done just by playing with `netdata.conf` and then we can modify the code to get a better default.

**Comment by Ferroin** [comment]
The problem here is not that we're able to set this value, it's that we do not honor it in the existing environment we get on startup even if we're not configured to ignore it.

IOW, running `HOME=/foo netdata` _does not work_, the value of `$HOME` passed to processes we call will not be `/foo` even if there is nothing in the config that says it should be otherwise.

This, in turn, causes problems with anything we do that touches Python (including both our AWS SNS notification support and our Python collectors) because the resultant Python runtime environment cannot see modules that were installed via `sudo -u netdata pip install`on most systems (because the value we unconditionally use as a default for the home directory does not match up with what we set in `/etc/passwd`).

The correct solution here is either to pass the environment variable through if it's already set and `home directory` is not set in the config file, or to determine the correct default value at runtime by calling `getpwent_r()` on the user we're configured to run as and using the home directory that that returns as the default.

**Comment by cakrit** [comment]
Plz check PR #9711 then, I just set the default value to the environment's HOME. I started netdata locally and nothing broke, but this one will need some serious testing, in various environments.

**Comment by Ferroin** [comment]
One other thing I just noticed that's a contributing factor here, our default value for `$HOME` that we're using in the agent (the cache directory) does not match up with what we set for our user (which is the `/var/lib/netdata` directory). Those need to be synced up, and we can't easily change the password entry (it won't help on existing installs, and it runs the risk of breaking user configurations to a greater degree than fixing the agent).

If we were to go with the runtime determination of the default using `getpwent_r()` this would be fixed automatically, but if we're just honoring `$HOME` if it's already set we need to update what we use if `$HOME` is not already set.
