### ISSUE TITLE
Coverity outstanding defects

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#6924]
We still have 17 outstanding: https://scan4.coverity.com/reports.htm#v42935/p15826
Please don't close until all of them are handled. "Handling" may be just using the coverity UI to acknowledge/explain some of them.

**Comment by mfundul** [comment]
The `unit_test.c` ones will be taken care of by the new benchmark code.

**Comment by thiagoftsm** [comment]
Hi @cakrit ,

I am  trying to access coverity, but it is not allowing me, I tried to change the password, because I thought I could have forgot it, but the site only gives 404.
Please, can you send to my e-mail this report?

**Comment by cakrit** [comment]
@thiagoftsm you need to access it, I sent you a note.

**Comment by thiagoftsm** [comment]
I tried to access again and I could not, and when I try to change  the password I am receiving:

```

Page Not Found (404)

We're sorry, the page you are looking for does not exist.

Click here to be redirected to the Coverity Scan home page.

```

**Comment by thiagoftsm** [comment]
There are two issues in the report, that I will need time to study it and fix and probably I won't have time this sprint, because I have to understand how collectors works, because they can be false positive. I am talking about the issues CID 348646 and CID 348639. @vlvkobal can you take care about them in the next days? Case it is not possible, I can reserve a time in the next sprint to study them.
The issues CID 349684 and CID 349552 are now false positive, but I will check case it can be rewritten. 
The other CID are related with Database.
