### ISSUE TITLE
Why netdata kickstart installer don't create systemd netdata file in docker ubuntu systemd image?

### ISSUE THREAD

**Issue by kozicpetar** [netdata/netdata#6971]
I write some playbook for netdata installation. Because I using molecule and DroneCI for continues testing I need to install netdata in docker image with systemd.

I found image, several ubuntu systemd image on which systemd works, I tried manually. But, when I install netdata, installer don't create systemd file. I tried also with Centos 7 systemd image, same issue.

When I tried in container to run:
`systemctl status netdata`

I get: 
`Unit netdata.service could not be found.`

##### OS / Environment
Centos 7 systemd docker image
Ubuntu 18.04 systemd docker image
Molecule framework

##### Component Name

Netdata systemd service

**Comment by Fauxsys** [comment]
I just ran across this myself.. curious of what the solution is.

**Comment by paulkatsoulakis** [comment]
Good morning,
  Thanks for reaching out with questions.  our installer intentionally does not attempt to install the systemd file within a docker container. systemd is not in use by design within containers, because usually you are only interested in running a single task within the scope of a container and you are not really interested of all the things systemd can do for you.  It may also be the case that you might end up breaking the isolation containers offering, if you use systemd and you make your container run with the privileged flag. Netdata publishes an [official docker image](https://hub.docker.com/r/netdata/netdata) for the people who wish to run netdata in docker.

   Now, i have not understood what is exactly the use case you are trying to cover with your playbook, but it seems that you will probably be better with using netdata docker image rather than installing it yourself (unless you need plugins or modules we haven't yet provided in the docker image)

 Let me know if that covers your questions, if not, please share more details on the tests you would like to run so that we can advise or consider our strategy around the matter.

Thanks again!

**Comment by kozicpetar** [comment]
Hello @paulkatsoulakis, 
thank you very much for your answer. Unfortunately, this answer don't help me much.

I will try to explain to you what I try, sorry on my bad English.

When I writing Ansibe roles, every role I testing with molecule framework. For testing I'm using docker images. When I finish Ansible role in DroneCI I setup automatic testing. One time at week my role doing automatic deploy and do all tests.
Because I using that roles for deploy on barematal and VPS servers I need to do real testing before deploy on production system.

In this task, I have role which doing the installation of netdata, because all my system on which I install them was systemd I need to do testing on systemd docker images.

Problem is because netdata installer don't setup netdata systemd service in docker systemd image. 
If I manually login to docker container and run on example installation of nginx, that service works from systemd and I can start, restart service with systemctl, on that way I'm sure that systemd works on that image.
Also, if I run command
`systemctl list-units --type=service`

I get outpout:
```
UNIT                               LOAD   ACTIVE SUB     DESCRIPTION
nginx.service                      loaded active running A high performance web server and a reverse proxy server
systemd-journald.service           loaded active running Journal Service
systemd-tmpfiles-setup-dev.service loaded active exited  Create Static Device Nodes in /dev
systemd-tmpfiles-setup.service     loaded active exited  Create Volatile Files and Directories
```

where you can see that nginx is loaded, but netdata isn't, but netdata works in backend.

Thank you.

**Comment by paulkatsoulakis** [comment]
Hi @knatsakis,
  I think it is a good idea to take over handling of this issue too. It will be a good ramp up, i will help with any insights and review of the final solution of course. Below is some background on the problem and the possible solutions

   We had modified our netdata installer in order to avoid installing service start files when netdata is installed within docker container, because this caused misguiding soft errors on the installer, exactly because under normal circuimstances there is no systemd or other start up daemon running.  The relative code that decides that on installer is below

``` 883 if grep -q docker /proc/1/cgroup >/dev/null 2>&1; then
 884         echo >&2 "We are running within a docker container, will not be installing netdata service"
 885         echo >&2
 886 else
 887         install_netdata_service || run_failed "Cannot install netdata init service."
 888 fi
```

What i can think of as a solution to our friends problem is to add an extra condition on line 884 and before ignoring netdata service install, when we have seen that we are indeed within a docker container, check whether the OS runs either systemd or init and if it does, then attempt to install netdata service.  This is to explicitly allow install of netdata service within docker, if systemd or init running. The method `instal_netdata_service` does more things to take care multiple types of OSes, that is why i want to allow this exception within the "is docker container" branch, otherwise it will be more complex to make sure we run properly for all occasions.

By all means of course any other suggestions that look more efficient are welcome, this is just my thought.

Thanks!
