### ISSUE TITLE
chart name and nav bar/menu name wrapping

### ISSUE THREAD

**Issue by scomoletti** [netdata/netdata#6972]
##### Question summary
Is there a way to disable or increase the length/size of the char name and nav menu link names before it starts to shorten them by trimming the middle of the name and replacing it with '...'? 
I'm fine with 3 line wraps in the nav and a typical 1080p monitor has plenty of space for longer chart names. 

##### OS / Environment
CentOS 7.6.1810
Netdata 1.17.1.20

##### Component Name
web

##### Expected results
name shorten boolean to disable or size/length definition in netdata.conf to increase the size based on expected environment the web ui will be used in.
I dont mind updating the css or html if thats what it takes for now but ultimately I think this should be a configuration item. If it turns out to be css/html then I'd like to know where/how to update it until such time a better solution is available.

**Comment by ilyam8** [comment]
Hi @scomoletti, by 

> nav bar/menu

you mean `family` thing (sub menu), right?

**Comment by scomoletti** [comment]
@ilyam8 

Sorry yes the family.

**Comment by ilyam8** [comment]
@jacekkolasa please take a look. This makes sense, it is not clear why we need to shorten `family`.

**Comment by jacekkolasa** [comment]
@scomoletti if you need a quick solution, you can remove following lines from main.js:
https://github.com/netdata/netdata/blob/master/web/gui/main.js#L1296-L1300

I personally would also prefer to not see the ellipsis in very long family names. This is how it could look like, if you remove those 4 lines in main.js:
![image](https://user-images.githubusercontent.com/5786722/65868491-a1b3b300-e378-11e9-8f48-5e9ce0b655a8.png)

this is how it looks now:
![image](https://user-images.githubusercontent.com/5786722/65868533-c019ae80-e378-11e9-971c-6d5b9bda19fa.png)

@cakrit what do you think, should we remove those dots (...)? I don't know if this is common to use such long `family` names.

I don't know if we should add another variable, because we'll be doing soon a refractor of the Agent Dashboard and we'll be able to add ellipsis (...) only when there's not enough space, and add tooltip with full name on hover - so perhaps it's not good to introduce a new config var now, just for several weeks.

**Comment by ilyam8** [comment]
> This is how it could look like

👍

**Comment by scomoletti** [comment]
@jacekkolasa the changes to main.js work perfectly for me. I can wait for labels and the other work already in progress with this.

**Comment by ilyam8** [comment]
@scomoletti those changes will be overwritten on next update

**Comment by ilyam8** [comment]
I see no pros in shortening families. It is not clear what problem does it solve.

**Comment by ilyam8** [comment]
@jacekkolasa is this an easy change? why dont just fix it?

**Comment by jacekkolasa** [comment]
@ilyam8 how about i add this fix along with new Dashboard release?

**Comment by ilyam8** [comment]
@jacekkolasa depends on new dashboard release data 😄 

i see the fix is super easy

> @scomoletti if you need a quick solution, you can remove following lines from main.js:
/web/gui/main.js@master#L1296-L1300 

My point **if we want to fix it** we could do it right now, because why not? But do it as you feel is better.

**Comment by jacekkolasa** [comment]
I just don't know if there are some families for which it makes sense to add ellipsis in the middle. I thought that the proper fix would be to remove ellipsis from submenu title above chart, and keep it as it is now in the menu on the right side. What do you think?

**Comment by ilyam8** [comment]
I think it depends. But to be honest - i dont like `family` shorten thing at all. We use families to navigate. It is impossible to navigate when `family` is mangled.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.

**Comment by zengrotrust** [comment]
@jacekkolasa @ilyam8 Hi team, just wanted to confirm these are still the lines to remove and if not, which lines were you referring to? Thanks.

https://github.com/netdata/netdata/blob/master/web/gui/main.js#L1296-L1300
