### ISSUE TITLE
Responses to API calls not properly documented in swagger.yaml

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#7005]
All `200` responses should be properly documented. e.g. we currently show the `chart` response in the `data` call, which is incorrect and misleading.

**Comment by cakrit** [comment]
This is an easy task that will help one of the new people in our team review all the API requests and responses.

**Comment by thiagoftsm** [comment]
I will try to do it until this sprint finishes.

**Comment by amoss** [comment]
I've found the swagger editor and the relevant handler code. I'll check that they match up.

**Comment by stelfrag** [comment]
Analyzing as well to get familiar with the API

**Comment by cakrit** [comment]
So @thiagoftsm leave it to the other two, it's a good exercise. 
The process to update the swagger docs has a few steps:
- Click on the link in the documentation page for the APIs
- Edit the yaml using the UI (helps to see the output)
- Export/Save as both .yaml and .json
- In a new branch, mv the .yaml and .json to web/api/netdata-swagger.yaml and web/api/netdata-swagger.json.

**Comment by thiagoftsm** [comment]
All right, I will review their work!
@amoss and @stelfrag , please, be free to ask me anything related to the API.

**Comment by thiagoftsm** [comment]
I remember something that will help you this morning, I executed a map of the web server last sprint, you can find it here https://github.com/netdata/netdata/issues/6831.

**Comment by amoss** [comment]
Relates to #6968.

**Comment by amoss** [comment]
Initial review of the code suggests a simple typo in the swagger definition. The schema definition for the `api/v1/data?` response is currently:

```
          schema:
            $ref: '#/definitions/chart'
```
The correct format of the schema is already defined under a different name so this should be:
```
          schema:
            $ref: '#/definitions/json_wrap'
```
I still need to go through each of the parameter definitions and the format of the response in more detail to check that they match the code before making any patch.

**Comment by stelfrag** [comment]
@amoss Indeed *json_wrap* looks close and swagger editor reports it "never used in the document"

**Comment by thiagoftsm** [comment]
Guys, I will bring @joelhans to help us, becaus he is responsible for our documentation.

**Comment by amoss** [comment]
I think it's close but it does not quite describe the structure of the `"result"` value. Playing with the `"dimension"` parameter it seems that the results are always a pair of (labels,values) that looks like this:

```
  "result": {
    "labels": [
      "time",
      "guest_nice"
    ],
    "data": [
      [
        1570456830,
        0
      ],
      ... one array element per sample...
```

**Comment by thiagoftsm** [comment]
What were the URL that you used to generate?
Another suggestion that will help you to work with the API and I remember now, we have inside our directory `tests` a shell script called `urls/request.sh` this shell script does thousands of requests combining different parameters of API and it stores the results in files.
I agree 100% that it is important you run to understand what is happening, I had to do this before to write this shell script in the past, but I decided to say something about it case some parameter is not clear for you.

**Comment by amoss** [comment]
I'm using the built-in testing in the swagger editor (default field values and then putting in different different chart / dimension values). I think this covers the set of tests in `urls/request.sh` that touch the `/api/v1/data?` path. The URL looks like:
```
curl -X GET "https://registry.my-netdata.io/api/v1/data?chart=system.cpu&dimension=time%2Cguest_nice&after=-600&before=0&points=20&group=average&gtime=0&format=json&options=seconds,jsonwrap" -H  "accept: application/json"
```

PR#7012 is the typo fix and the changes to the `result` schema so that you can see directly what I'm changing. It won't turn into a real PR until I've gone through each of the paths / handlers and compared them to the swagger definitions.

**Comment by thiagoftsm** [comment]
All right, you are correct.

For you know the dimensions available for the charts, you can run the following command:

``` 
curl -k https://192.168.0.17:19999/api/v1/charts?all 
```

This will give you all the charts and dimensions associated to them.

Now about the request you are doing, the output message that you are receiving is making using two files, the first `web/api/formatters/json_wrapper.c` will make the header and footer of the message, the other data is make using functions available in the file `web/api/formatters/json/json.c`. 

Finally the interpretation, yes, you are having the pair, where "labels" describes the name of the columns for the request you did and the data are the results for that value.

**Comment by amoss** [comment]
I've realised that there is a problem with using the more detailed schema to describe the `/api/v1/data?' response. The schema description works for json-formatted data, but it is incorrect when the user selects a different format. For example, if I request:
```
https://registry.my-netdata.io/api/v1/data?chart=system.cpu&dimension=time%2Cguest_nice&after=-600&before=0&points=20&group=average&gtime=0&format=csv&options=jsonwrap,min2max,milliseconds
```
Here the URL parameters indicate `format=csv` and the structure of the response is a different shape:
```
  "format": "csv",
  "result": "time,guest_nice\n1570466820000,0\n1570466790000,0\n... more data..."
```
i.e. the schema for the `result` property has changed and no longer matches the more detailed version in the commit. 
The way around this would be to make the schema polymorphic so that we can reference different sub-schemas for the structure. Unfortunately this does not seem to be possible in Swagger2.0, as the `oneOf` operator is introduced in OpenAPI3.0. I am still staring at the Polymorphism example in the Swagger2.0 docs but I don't think it does what we need, so we are left with some different options to discuss:

1. Remove the more detailed structure and go back to the `description: 'The result requested, in the format requested.'` original.
2. Convert the swagger files to OpenAPI3.0 - but this seems like a major change and I don't know what else it would impact.
3. Leave the structure in place to describe the json formatted cases, and add a note that it is wrong if the format is changed in the request - this may have an impact on validating the schema.

Comments?

**Comment by ilyam8** [comment]
I read only 3rd option and instanlty agree with! It looks the easiest one 😄 

To see other schema's we could suggest `try it out` -> `execute`

**Comment by thiagoftsm** [comment]
I do not know swagger, but I think that the option 2 could be the longest way to reach the final goal.
I agree with Ilya that the third option is good, but I cannot discard the option number 1 now, because I think this is the most important part of the message. Can you use the third option and we talk about the results specifically with the first optoion? I know I am mixing two here, but I could not select between them.

**Comment by amoss** [comment]
Worked out how to model polymorphism in Swagger2.0 - it is not perfect as the editor does not use the discriminator field to show the sub-type, but I've explained it in the user-visible descriptions. Latest commit is partly done - shows the different subtypes. I just have to work through the rest of the format cases.

**Comment by cakrit** [comment]
Let's create an issue for the migration to OpenAPI3.0 though. We can add a 'help wanted' label to it as well, to see if anyone from the community wants to work on it.

**Comment by amoss** [comment]
There are some differences between the documentation and code for the `badge.svg` that look like bugs in the code. @thiagoftsm you are more familiar with this code, please could you take a look?

In `web/api/badges/web_buffer_svg.c`, `web_client_api_request_v1_badge`:
line 869-871:
```
        buffer_svg(w->response.data, "chart not found", NAN, "", NULL, NULL, -1, scale, 0);
        ret = HTTP_RESP_OK;
        goto cleanup;
```
and then again lines 880-822:
```
            buffer_svg(w->response.data, "alarm not found", NAN, "", NULL, NULL, -1, scale, 0);
            ret = HTTP_RESP_OK;
            goto cleanup;
```
It looks as if the `ret` value should be set to 400 (`HTTP_RESP_BAD_REQUEST`). I can fix this in the PR, but I have two questions:

1. Does this seem like the correct functionality?
2. Is there anything that relies on the return codes that may break?

**Comment by amoss** [comment]
I've finished going through the endpoints and updating the docs / code with two exceptions:
1. I have not looked at the `api/v1/alarms` endpoint as it is covered by issue #6968 .
2. The documentation of the `api/v1/allmetrics` endpoint is a bit sparse, but the data model is quite a lot of work - should I raise a separate issue on implementing it? (@cakrit)

After resolving the svg badges differences above I'll finish the PR and put it in for review.

**Comment by stelfrag** [comment]
One can argue on both sides. IMO it can be a 200 just fine since its a "logical error" (e.g chart
id is given but chart is not found). 

At the same time if a chart id is not given in the request (bad request), 400 is returned

**Comment by amoss** [comment]
It is true that both return codes can be viewed as the correct response from the server's perspective.

I think that interpreting the result would be easier from the client's perspective if the return codes differed. At the moment if a `200` is received the client has to check the message body and decide if it looks like a valid `.svg` or an error message string.

**Comment by thiagoftsm** [comment]
It was good you bring this subject, there are other places that Netdata is not returning like normal web servers would return, case we agree, we can change this without any problem for the server.

**Comment by amoss** [comment]
@cakrit: I've finished up working through @thiagoftsm 's review and we are both happy with the changes. Is there any urgency to merging this? 

* If there is I can ping Joel and ask for a second review.
* If not then I can leave it open and give Stelios some days to go through it.

What do you think?

**Comment by stelfrag** [comment]
I should be done with the review by Monday

**Comment by OdysLam** [comment]
Our swagger UI [link[9https://registry.my-netdata.io/swagger/#/default/get_data) produces an error in parsing the .json. We need a curly bracket at line 876. I am not sure what file should be changed in order for the registry to be updated.

**Comment by amoss** [comment]
> Our swagger UI [link](https://registry.my-netdata.io/swagger/#/default/get_data) produces an error in parsing the .json. We need a curly bracket at line 876. I am not sure what file should be changed in order for the registry to be updated.

Could you raise a new issue - nobody will see a notification on this old issue.
