### ISSUE TITLE
[Spike] investigate random high values from #4962 and #5297

### ISSUE THREAD

**Issue by mfundul** [netdata/netdata#7049]
##### Bug report summary
Spike investigate random high values from #4962 and #5297 and how we can improve on this.

**Comment by mfundul** [comment]
I propose we disallow the use of low precision counters for writing collectors since it is impossible to differentiate between a counter reset and a counter overflow.

**Comment by Ferroin** [comment]
@mfundul I think it makes more sense to avoid them whenever possible, document why, and clearly document what collectors actually use them (as well as the implications of those collectors using low-precision counters).  There are simply going to be some cases where we can't avoid them, and that way we'll let the users decide if having the data is worth it or not.

**Comment by mfundul** [comment]
> 
> 
> @mfundul I think it makes more sense to avoid them whenever possible, document why, and clearly document what collectors actually use them (as well as the implications of those collectors using low-precision counters). There are simply going to be some cases where we can't avoid them, and that way we'll let the users decide if having the data is worth it or not.

The problem is that the counter overflow code is creating the effect of #4962 , which is actually a regression for netdata caused by PR #4538 . This counter overflow code is conflicting with counter resets.

**Comment by Ferroin** [comment]
> The problem is that the counter overflow code is creating the effect of #4962 , which is actually a regression for netdata caused by PR #4538 . This counter overflow code is conflicting with counter resets.

I understand that.  My point was that there are numerous use cases where users just won't care about that, and we should account for those use cases.  Using high-precision counters internally will just shift where the problem is (we'll start showing restarts for low-bit width counters instead of properly tracking overflows).  We could probably do even better by having Netdata watch the rate of change and factor that into whether it thinks we've reset or overflowed, or by teaching Netdata about the bit-width of the counters it's collection (that way it knows for certain where the overflow point is, and thus can better guess if we overflowed).  However, we really can't completely solve this unless we figure out a way to know for certain when whatever we're monitoring restarts, which is not realistically possible.  So, we're at the mercy of whatever we're collecting regardless, and should just properly acknowledge that fact.

**Comment by mfundul** [comment]
> 
> I understand that. My point was that there are numerous use cases where users just won't care about that, and we should account for those use cases. Using high-precision counters internally will just shift where the problem is (we'll start showing restarts for low-bit width counters instead of properly tracking overflows). We could probably do even better by having Netdata watch the rate of change and factor that into whether it thinks we've reset or overflowed, or by teaching Netdata about the bit-width of the counters it's collection (that way it knows for certain where the overflow point is, and thus can better guess if we overflowed). However, we really can't completely solve this unless we figure out a way to know for certain when whatever we're monitoring restarts, which is not realistically possible. So, we're at the mercy of whatever we're collecting regardless, and should just properly acknowledge that fact.

I've discussed this with @vlvkobal and @ilyam8 and we have agreed on some things:
- It appears prometheus does not handle counter overflows at all so as to safely detect counter resets.
- It is theoretically impossible to always be 100% sure about things such as hardware counters that overflow.
- As a result it is theoretically impossible to both solve the counter reset and the counter overflow prroblem.
- The counter reset is the common case whereas the counter overflow is the edge case.
- Any solution that attempts to solve both issues will have to mostly err on the safe side as if it was a counter reset.
- 8-bit and 16-bit or any arbitrary precision counters are too much effort, it's simpler to handle the 32-bit case only.
- There could be a rate that could identify most of the 32-bit wrap-arounds without creating too many false negatives for counter resets.

**Comment by Ferroin** [comment]
> The counter reset is the common case whereas the counter overflow is the edge case.

This very much depends on the application.  If the system being monitored is designed for extremely long uptime without restarting services (IOW, if it's an IoT application or an older server application), then overflows may be more common than resets.  Hell, even if the system is just designed for moderate uptime and the counter is counting an event that occurs with high frequency, overflows may be more common (for example, a 32-bit unsigned counter tracking some event that happens approximately 10k times a second will roll over in less than a week (about 4.97 days)).

OTOH, we can, in some cases, just blindly assume it's a reset and not an overflow with near 100% confidence.  For example, if the system uptime is still in the double-digit seconds range and Netdata just started up, then a sudden low value for the counters is almost certainly a reset and not an overflow.

> 8-bit and 16-bit or any arbitrary precision counters are too much effort, it's simpler to handle the 32-bit case only.

Agreed on 8 and 16 bit, but nothing outside of hardware uses those anyway at this point, so it really doesn't matter.  We should, however, properly handle both signed and unsigned 32 and 64 bit counters, as all four are common enough for us to need to care, which is why I was commenting about teaching Netdata about the bit width of the counters it's tracking (there's no point in using the logic for handling 32-bit overflows on a 64-bit counter, it would just increase the false-positive rate). 

> There could be a rate that could identify most of the 32-bit wrap-arounds without creating too many false negatives for counter resets.

My point about looking at the rate of change was that if assuming a counter overflow would result in a rate that's really close to what was being observed just previous to the transition point, it can provide extra confidence that it was an overflow and not a reset. If the difference before and after the reset fits the existing rate of change leading up to the transition to within about half a percent (possibly more depending on what specifically you are monitoring) and the rate of change was low enough (less than a few dozen items per second), it's a pretty good indicator that it was probably an overflow and not a reset.
