### ISSUE TITLE
How to filter the log

### ISSUE THREAD

**Issue by ExchequerNL** [netdata/netdata#7071]
I would like to take a look at the latest warnings and critical. How do I filter these from the UI?

When I put 'warn' in the searchbox also "CLEAR" and "REMOVED" show up. There probably is a way but I haven't found it.

**Comment by jacekkolasa** [comment]
@ExchequerNL you probably see those rows because the searched status is visible in `old_status` property. Unfortunately there is no way right now to filter only via "visible" fields, if you don't want to modify .js files.

We could change the behaviour for the whole table, to filter only via `visible` fields, but then it could break others experience. Perhaps in the future (after we'll finish FE refractor) we can add a checkbox to toggle that setting.
