### ISSUE TITLE
CMake build doesn't work on Ubuntu 18.04

### ISSUE THREAD

**Issue by vlvkobal** [netdata/netdata#7091]
##### Bug report summary
If you try building Netdata with CMake version 3.10.2 there are errors:
```
CMake Error at CMakeLists.txt:728 (target_link_libraries):
  Target "libnetdata" of type OBJECT_LIBRARY may not be linked into another
  target.  One may link only to STATIC or SHARED libraries, or to executables
  with the ENABLE_EXPORTS property set.
```

Changing `add_library(libnetdata OBJECT ${LIBNETDATA_FILES})` to `add_library(libnetdata STATIC ${LIBNETDATA_FILES})` fixes the problem.

Another way to fix the problem is to move `libnetdata` from `target_link_libraries` to `add_executable` using `$<TARGET_OBJECTS:libnetdata>`. Something like that:
```
add_executable(netdata config.h ${NETDATA_FILES}
            $<TARGET_OBJECTS:libnetdata>
            ${CGROUPS_PLUGIN_FILES}
            ${DISKSPACE_PLUGIN_FILES}
            ${PROC_PLUGIN_FILES}
            ${TC_PLUGIN_FILES}
            )
```

##### OS / Environment
Ubuntu 18.04.3 LTS
cmake version 3.10.2

##### Netdata version (ouput of `netdata -V`)
netdata v1.18.0-25-g2d248dfa

##### Component Name
CMake build configuration 

##### Steps To Reproduce
Run CMake build on Ubuntu 18.04 with CMake installed from a standard package.

##### Expected behavior
We can build Netdata with CMake on Ubuntu 18.04

**Comment by amoss** [comment]
I don't think that this is a bug:

* CMake is not yet a support build environment.
* It breaks on most systems because of this issue (definitely CentOS as well).
* The CMakeLists.txt don't need small changes - they will be almost entirely rewritten.

There are already two issues open to track the change in build-system:
* #4310 for the investigation to check that we can make everything work in CMake.
* #5159 on the initial RFC about the change.

I think that we should close this, it makes more sense to me to open an issue after #4310 to track the work in switching over the build-system - not as a bug-fix, it is a substantial rewrite / new-feature.

What do you think?

**Comment by vlvkobal** [comment]
I don't mind closing the issue. I created it just as a reminder.

**Comment by amoss** [comment]
Ok, makes sense. I'll close it, but it will become part of the "Moving to CMake" that I create on Thursday. Thanks for the reminder.
