### ISSUE TITLE
As a user, I want to attach custom labels to hosts, so that I can more easily filter them in the nodes list dropdown.

### ISSUE THREAD

**Issue by gpapamathND** [netdata/netdata#7095]

**Comment by cakrit** [comment]
- [ ] Extend the existing search in the nodes list, so that it filters nodes by their host labels/tags. 
![image](https://user-images.githubusercontent.com/43294513/69633319-d94f7c00-1004-11ea-953a-74e25ecf41cc.png)
- [ ] Users don't need to write the entire name/value pair. Any match on the value of any label or on the name of any server will show the list. 

Note: We may eventually replace this search with the more powerful search/filtering we'll implement for the cloud, so we're not doing fancy things right now, like showing what exactly we are matching on, or allowing search only on a specific label and not on a hostname. The purpose is just to show fewer results, not to create a query language.

**Comment by cakrit** [comment]
- Agents need to send label info for the hosts to the cloud (visited nodes) in order to permit this filtering
- Cloud needs to accept and store the labels, in order to allow filtering.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
