### ISSUE TITLE
Shell script not verified properly on GitHub

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#7100]
##### Bug report summary
During my tests with the PRs #7082 and #7083 I verified that there are old problems with our shell script files, so I arrived in the conclusion that the shellcheck is not working properly here at GitHub, because this kind of old merges could not happen, but this looks like problems after some update, because part of the problems that I will show in the next images was reported to me in the past.

![66782843-2a2c6a80-eec6-11e9-9ad4-031029248f13](https://user-images.githubusercontent.com/49162938/66835851-c3ec2a00-ef4f-11e9-8b62-bc6fd8b845d5.png)

![66782037-5b0ba000-eec4-11e9-906d-e504c4a7dda0](https://user-images.githubusercontent.com/49162938/66835856-c77fb100-ef4f-11e9-9271-9e2e5e697c9d.png)

##### OS / Environment
Linux and BSD
##### Netdata version (ouput of `netdata -V`)
netdata v1.18.0-36-gb79da30c
##### Component Name
Installer
##### Steps To Reproduce
run `shellcheck` on the files that appear in the image.
##### Expected behavior
A clean return from shellcheck

**Comment by knatsakis** [comment]
It turns out that only *.sh.in files (please note: files ending in *.in) have been shellchecked up until now. After a discussion with @paulkatsoulakis, I understand that there is no particular reason for this.

@cosmix do you want to enable shellcheck for all *.sh files? This will mean quite a few changes to battle tested scripts (e.g. kickstart.sh, install-or-update.sh and functions.sh)

My opinion is to do so.

**Comment by cosmix** [comment]
@knatsakis, yes of course, please add the issue!

**Comment by thiagoftsm** [comment]
I agree with @cosmix , we carried different warnings related to shell, because we were avoiding this checks.

**Comment by knatsakis** [comment]
> @knatsakis, yes of course, please add the issue!

@cosmix, this is the issue

**Comment by paulkatsoulakis** [comment]
Hello,
  Just a clarification, the title should be adjusted to something more clear. Scripts are not "broken", but they rather not confirming to the styles and syntax shellcheck is expecting a BASH script to be.
  For some of our scripts, we are forced to enable overrides to silence shellcheck because we can't conform to what shellcheck is asking.

**Comment by thiagoftsm** [comment]
Thank you @paulkatsoulakis
