### ISSUE TITLE
Netdata web server can't use all available CPU resources in FreeBSD

### ISSUE THREAD

**Issue by vlvkobal** [netdata/netdata#7116]
##### Bug report summary
After #6796 Netdata doesn't use more than 7% of CPU time on FreeBSD when it is tested with the following command:
```
wrk -t12 -c50 -d600s "http://192.168.0.153:19999/api/v1/alarm_variables?chart=system.cpu"
```

![image](https://user-images.githubusercontent.com/22008543/66955368-da3ad880-f06a-11e9-9a3b-538df253e3ec.png)

Before this PR Netdata used 90%

![image](https://user-images.githubusercontent.com/22008543/66955600-5c2b0180-f06b-11e9-8084-4def3867a76f.png)

##### OS / Environment
FreeBSD 12.0-RELEASE-p10

##### Netdata version (ouput of `netdata -V`)
v1.18.0-42-g9f27500f

##### Component Name
web

##### Steps To Reproduce
Put Netdata under test using the following command
```
wrk -t12 -c50 -d600s "http://192.168.0.153:19999/api/v1/alarm_variables?chart=system.cpu"
```

##### Expected behavior
Netdata should be able to use all available resources.

**Comment by amoss** [comment]
Something has broken the config file handling, we need to bisect the problem.

On nightly running `./wrk -t8 -c100 -d30s "http://192.168.1.6:19999/api/v1/alarm_variables?chart=system.cpu"` replicates the problem. About 3-4% cpu-load and the log is full of messages that the connection is rejected because it does not match the pattern. Adding the appropriate configuration has zero effect on the behaviour:
```
     allow connections from = localhost 192.168.1.*
```

Reverting to commit `187620911c06585882350ff871ef49bb6e6acd1e` and rerunning the same test with the same configuration produces no log messages and about 50-60% cpu-load on outbound traffic of about 600mbs.

**Comment by amoss** [comment]
Initial investigation shows that the config file is not being read correctly. This causes the incoming connection to fall back to a more complex check that is I/O bound rather than CPU-bound. This causes a bottleneck on the performance.

The wildcard is not being processed in the default configuration:
```
    allow connections from = localhost *
```

Because the wildcard is not processed the agent attempts to perform reverse-dns lookup on the incoming connection, which is the I/O-bound task. On linux this is failing instantly so the problem is invisible. On FreeBSD this is failing in a different way causing the issue to be visible.

Further investigation is required.

**Comment by amoss** [comment]
Further investigation has occurred.

The problems with reading the configuration are phantom issues that arise from testing in two ways:
1. When we pull different version out of the repo and rerun the installer it preserves the old configuration file. So we get state that leaks between tests.
2. It is possible to run two copies of netdata at once, both bound to the same port. This is very weird and should not happen, I have a video of the behaviour that it causes.

More systematic testing has revealed that the system is working as expected (although it still requires improvement). The default configuration for the agent includes the following:
```
    allow connections from = localhost *
    allow management from = localhost
```

This means that when a connection is received from an external IP the internal check from the API for management privileges causes an external DNS lookup that works differently on FreeBSD and linux. On linux it fails quickly (and in @vlvkobal test-data it looks as if there is a name bound to the IP from a local `hosts` file?), and on FreeBSD it fails slowly. The slow failure slows down the connection rate and causes the behaviour seen.

I have a PR that improves the logging to make this visible, tomorrow I will see if we can detect the lack of wildcards in the management pattern and make a definite failure to match without the external lookup. This will improve the performance in scenarios beyond those we are testing.

**Comment by amoss** [comment]
We have a possible fix, but it introduces a costly run-time check. Summary of a discussion with @vlvkobal about how to solve this more effectively:

1. Move the pattern-heuristics into the initialization. Early in `poll_events` call `simple_pattern_is_potential_name` for each of the configuration options and store the results.
2. Use the array to avoid evaluating the heuristic on each connection.

This removes the performance issue in the test-case that we are looking at, but it does not remove it in all cases. Any configuration that uses wildcards will cause a non-matching incoming address to trigger the DNS check. A better solution would be to cache the capabilities of each address:

1. Use an AVL tree to cache the incoming addresses and the results of querying the capabilities.
2. Keep track of the age of each entry.
3. Introduce a configuration parameter for the size of the cache.
4. A mechanism (T.B.D) to flush entries from the cache (possibilities include evicting the oldest entry, or allowing arbitrary growth but flushing on a timer).

Target configurations have a large number of connecting nodes (e.g. a collector/aggregator node with many clients) where we want to avoid a high per-connection cost. Important factors to consider are:

* The cost of rebalancing the tree.
* The cost of DNS queries.
* Memory usage of an unbounded cache (particularly w.r.t. denial-of-service attacks).

**Comment by amoss** [comment]
After careful consideration we have decided that we do not have the data to demonstrate that the work required to cache the connection ACLs is necessary at present. It may make a useful feature in the future, but this PR fixes the problem that we can see today.
