### ISSUE TITLE
Implement reading of a new configuration file for Exporting engine

### ISSUE THREAD

**Issue by vlvkobal** [netdata/netdata#7170]

**Comment by stelfrag** [comment]
# Introduction
The current main Netdata configuration file (netdata.conf) includes a `[backend]` section which specifies the backend we wish to stream metrics to.
At this point only one backend can be active at a time. 

We want to change that by introducing the term `exporting engine` to refer to the new subsystem which implements `exporting connectors` (what is now known as backend systems). The term exporting connector will be used for the rest of this description

The exporting engine should support the streaming of metrics to multiple exporting connectors

## Current configuration section

Notice that the current configuration section allows for one type of exporting connector
```
[backend]
    enabled = yes | no
    type = graphite | opentsdb:telnet | opentsdb:http | opentsdb:https | prometheus_remote_write | json | kinesis | mongodb
    host tags = list of TAG=VALUE
    destination = space separated list of [PROTOCOL:]HOST[:PORT] - the first working will be used, or a region for kinesis
    data source = average | sum | as collected
    prefix = Netdata
    hostname = my-name
    update every = 10
    buffer on failures = 10
    timeout ms = 20000
    send charts matching = *
    send hosts matching = localhost *
    send names instead of ids = yes
```

## Options
1. We can expand the current configuration file to allow for more sections like the one shown above
The current functions that read the configuration won't work. New ones will be needed to loop through the list of exporting connectors specified
1. We can define a new type of configuration file for exporting connectors using for example yaml (possible filename for the new config file -- connectors.yaml)
    1. We will migrate the existing settings [bankend] section to the new yaml configuration
    1. The old [backend] config section will be removed from netdata.conf
    1. New functions to read the yaml configuration will be implemented to be used by the new exporting engine

**Comment by vlvkobal** [comment]
We can't expand the current configuration file, because sensitive data (credentials) might be present in exporting connector configuration. So, we need a separate file with restricted access, not a world-readable one.

We can use a script to move an existing configuration to a new file.

**Comment by stelfrag** [comment]
This is the initial discussion about the options. 

The migration will be part of __installing a new Netdata version__  and will be done by providing a migration script

For example if we choose a __connectors.yaml__ file configuration approach. We will do 
something like: 

- Scan the current netdata.conf for [backend]
- Write the new config file __connectors.yaml__
- Keep a backup of the old configuration
Or comment out the backend configuration section and add an extract comment that points
to the new file (we will groom this at the technical meeting) 

Of course the documentation needs to reflect this. The versioning part will be needed. Something like pre 1.xx version config section or similar

**Comment by ilyam8** [comment]
> We can use a script to move an existing configuration to a new file.

We have a lot of installation options, will it work not only for installing from source?

> connectors.yaml

All our configuration files are `.conf`

**Comment by stelfrag** [comment]
> All our configuration files are .conf

No problem, it can be a `connectors.conf` file which a comment that says its ".yaml" actually

**Comment by thiagoftsm** [comment]
> Hi
> 
> > We will migrate the existing settings [bankend] section to the new yaml configuration
> 
> How?
> 
> What is about docs? We will have two section in the docs? For old netdata and for new netdata?
> 
> @joelhans what is our plan on documentation? How to handle such cases? I rememeber you and @thiagoftsm were talking about versioning or something.

When I talked with @joelhans about the documentation, he explained that nowadays with the tool that we are using to create our documentation, it would not be possible to have a documentation for each specific version. This will force us to do what we are already doing, to say in our documentation that `Since the version X.Y.Z Netdata....`.

**Comment by joelhans** [comment]
There's currently no support for documenting separate versions of Netdata. It may be coming someday with the Learn site, but I haven't been working on it there either. So it's TBD with no roadmap.

One solution would be to put notices on the top of relevant pages to say something like, **If you're using Netdata `vx.xx.x` or newer, please refer to this page about the new exporting engine.**

Who's the lead on this? @vlvkobal or @stelfrag, or both? I should get on a quick call next week to better understand what this change means for the docs and how to best help prepare.

**Comment by stelfrag** [comment]
@joelhans we will talk when we finished the tech part on how we will proceed probably Tue 29th. I will explain what will change so we will figure out how to structure the docs accordingly.

**Comment by amoss** [comment]
This may relate to #6432 and #6872.

**Comment by stelfrag** [comment]
> This may relate to #6432 and #6872.

Good point!!!

It relates (redesign)  but I am not sure it can be done at this point (huge). 

But I am thinking it could direct us to a workaround solution for now (pending a complete overhaul of the conf system)

**Comment by amoss** [comment]
It looks pretty large, I agree that it can't be done at this point. Perhaps it is useful context though?

**Comment by stelfrag** [comment]
After our meeting today we decided to go with the following:

- Maintain the backend section in the `netdata.conf` for compatibility
  - Actually that section can define a fully running instance
- Introduce a new file `exporter.conf` that can have 3 sections
  - A global section with configuration parameters that may affect all connectors
  - A section (e.g `[opentsdb]`) that specifies global parameters for a specific connector
    - This part will have section names that match the names of the exporting engines **opentsb, json** etc
  - An instance section that will specify the specifics of an engine e.g. hostname, credentials etc.
    - The instance name is user defined (e.g. `[my_opentsdb_1]`) so that it will be easy to trace in logfiles etc

---
* Configuration options will be read in the order of instance -> connector -> global
* The `exporter.conf` format will be the same as `netdata.conf`

### sample config
```
[global]
    host tags =
    enabled = yes    
    prefix = netdata
    update every = 10
    buffer on failures = 10
    timeout ms = 20000
    send names instead of ids = yes
    send charts matching = *
    send hosts matching = localhost *

[opentsdb]
    enabled = yes
    update every = 10
 
[my_tsdb1]
    type = opentsdb
    destination = 192.168.0.50
    update every = 20

[my_tsdb2]
    type = opentsdb
    enabled = yes
    destination = 192.168.0.51
    timeout ms = 50000

```
Note that:
- my_tsdb1 is enabled because opentsdb is enabled
- my_tsdb2 updates every 10 seconds
- my_tsdb2 timeout overrides the default in the global section

We may change the name for the global section if we think it will confuse people

**Comment by stelfrag** [comment]
### Update

- Changes applied so that the `exporting.conf` file is read _ahead_ of the `netdata.conf` file. 
The reason for this is to allow the processing of: 
  - The connector's global configuration section (currently named **`[connector_global]`**)
  - The definition of connectors
  - The definition of the instances
- Processing of the `netdata.conf` file allows the processing of the `[backend]`(if available) which at this point is treated like an instance configuration (named **backend**, quite possibly with all the configuration settings already set (or using the default values).
   - Note that the default values for this **backend** connector will be the ones defined in the connector's global configuration (see above)

Running more tests to ensure backwards compatibility

**Comment by stelfrag** [comment]
Adjusting code, so that the new exporting.conf is not exposed via `http://localhost:19999/netdata.conf`

**Comment by stelfrag** [comment]
#### Update / summary

- exporting.conf file is now read on demand by the new engine (code exists to read it in main.c for testing purposes)
- `[backend]` section in netdata.conf is maintained for backwards compatibility
