### ISSUE TITLE
add ability to tc-qos-helper.sh to run fireqos start automatically if needed

### ISSUE THREAD

**Issue by ofirule** [netdata/netdata#7207]
Add ability to `tc-qos-helper.sh` to run `fireqos start` automatically if needed

Since  FireQOS is not a daemon and it's configuration doesn't survive after system reboot, I think it's a good feature for `tc-qos-helper.sh` to run `fireqos start` if it finds that the configuration wasn't applied

**Comment by ilyam8** [comment]
Hi @ofirule 

See

https://github.com/firehol/firehol/issues/198

If it doesnt work for you please [open an issue in the `firehol`](https://github.com/firehol/firehol/issues/new) repo

**Comment by amoss** [comment]
Thank you for the suggestion. We've had a discussion internally about how this could work and decided that it would be difficult for the NetData agent to decide when it was valid to execute `fireqos start`. Our reasoning is that fireqos is a state-less mapping from the friendly configuration to the `tc` run-time state.

Have you considered asking cron to run `fireqos` for you at boot time:
```
sudo crontab -e
```
Then add a line like this:
```
@reboot /full/path/to/fireqos start
```

**Comment by ilyam8** [comment]
Ok, found.

> https://github.com/firehol/firehol/issues/250

**Comment by ofirule** [comment]
Both solutions have pros and cons.

In my environment I install fireqos inside docker so it's either installing it outside of docker or some workaround it.

Another issue that needs consideration is waiting for networks which doesn't start-up on system reboot , such as vpns.

What are the cons for running `fireqos start` multiple times (every time tc-qos-helper.sh runs)?

**Comment by amoss** [comment]
If you have systemd then my estimate would be that the fixes to the service would be more robust than putting in a cron job (because the dependencies should trigger it after the network is up and running) - but we can't provide more information than that. 

Please create an issue in the `firehol` repository and ask the question there. They will know the pros / cons of the different approaches in more detail than we could. A question in the firehol repo will reach someone with more expertise in `fireqos` (as it is not a part of netdata) and also your question may be useful to other uses of `fireqos`.
