### ISSUE TITLE
Uninstaller does not kill the daemon that is running on FreeBSD

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#7248]
##### Bug report summary
The uninstaller script should kill an active daemon process if it is running. In both privileged and non-privileged installs the uninstall script fails to kill the daemon.

##### OS / Environment
FreeBSD bamse 12.0-RELEASE-p6 FreeBSD 12.0-RELEASE-p6 GENERIC  amd64

##### Netdata version (ouput of `netdata -V`)
netdata v1.18.1-47-gcb906c08

##### Component Name
Installer

##### Steps To Reproduce
Install netdata.
Run the uninstaller until it says that netdata has been stopped.
Switch to another shell and run `ps -A` to verify that it is still running.

##### Expected behavior
The netdata process should be terminated.

After some testing with @knatsakis - there is no `/proc` file-system by default in FreeBSD. The uninstaller is being very careful about terminating processes. After the pid-file is read the `/proc/<pid>/stat` is checked to ensure it really is a netdata instance that is running. On FreeBSD we have no pid-file created at run-time, and the proc filesystem is not accessible so no process is killed.

A possible solution is to add a fall-back that detects this situation and asks for user confirmation to run `killall netdata`.

**Comment by Saruspete** [comment]
IIRC, "kill -0" is supported among multiple OS to check if a PID is still existing: https://lists.freebsd.org/pipermail/freebsd-hackers/2017-March/050671.html

**Comment by Ferroin** [comment]
> IIRC, "kill -0" is supported among multiple OS to check if a PID is still existing: https://lists.freebsd.org/pipermail/freebsd-hackers/2017-March/050671.html

While true, I'm not sure that's especially useful here. The issue is that we try to verify that a given PID is netdata before we try to kill it, but that's failing on FreeBSD due to the combined lack of `/proc` and a PID file. The problem should be trivial to solve, because the logic for updates/upgrades works correctly on FreeBSD and terminates Netdata, we're just using different code.

Regardless, I plan to deal with this together with #7585.
