### ISSUE TITLE
Sign In via email issue

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#7263]
From a user:
> When trying to sign in to netdata cloud, I input my email end receive the link, but when I click on the link I end up at the netdata website and never get signed in.

**Comment by cakrit** [comment]
Can you please let us know:
- how you started the sign-in process
- your netdata agent version
- your browser and version 

Also, for us to have some additional info to trace it, please:
- get a new email
- copy the link from the email
- open a new browser tab
- open the console and go to network. 
- enter the link on the url (it will be some unreadable thing from sendgrid)
- Observe in the network view a link like this: https://netdata.cloud/account/sign-in-agent?id=XYZ&name=frankfurt.netdata.rocks&origin=https%3A%2F%2Ffrankfurt.my-netdata.io%2F&redirect_uri=https%3A%2F%2Ffrankfurt.my-netdata.io%2F 
- Copy and paste that link here

There's probably something wrong with that last URL.

**Comment by theflu** [comment]
Sign in proccess:
- Went to the Netdata page on my server via local address and port 19999
- Clicked "Sign In"
- Input email and clicked "access with email"
- Got the email click the link and it took me to netdata.cloud

Netdata version: v1.18.1-77-nightly
Browser: Brave Version 0.70.121 Chromium: 78.0.3904.70 (Official Build) (64-bit)

sendgrid/click 302 ->
verify-magic/link 302 ->
netdata.cloud/account/sign-in-agent 200

**Comment by theflu** [comment]
https://netdata.cloud/account/sign-in-agent?id=9faa3d88-00c7-11ea-94b6-261e239abe85&name=node-03&origin=http%3A%2F%2F10.0.0.218%3A19999%2F

**Comment by jacekkolasa** [comment]
Thanks @theflu ! It looks like the problem is the incompatibility with "Shields" in Brave Browser - we will address it in the future, in the meantime please change Shields settings according to this post: https://github.com/netdata/netdata/issues/6298#issuecomment-539026951 , or use different browser (for example Firefox). After clicking the email magic link in Brave you will still be redirected to https://www.netdata.cloud/ , but you should be logged in in your Dashboard page.

**Comment by theflu** [comment]
Thank you, I tried it with Firefox and it is working now.

**Comment by cakrit** [comment]
Excellent! Thanks @jacekkolasa
