### ISSUE TITLE
Tech refinement for agent claiming

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#7286]
There are some problems in implementing https://github.com/netdata/netdata/issues/7086 .

There is the problem of authenticating the netdata agent identification. MACHINE_GUID is not enough because:
- MACHINE_GUID is not a secret, it can be visible in the network or known to other users. Thus it is not secure. Malicious netdata agents can copy the MACHINE_GUID and connect to netdata cloud hosts without authorization. Moreover, the original netdata agent will be locked out of netdata cloud which is a Denial-Of-Service attack.
- MACHINE_GUID can be easily cloned when creating VMs or containers by mistake, thus it is not unique.
- basing MACHINE_GUID on hardware IDs does not fix the uniqueness issue because the IDs themselves are often virtualized by the hypervisor as part of the virtual machine firmware. It is entirely dependent on the hypervisor type and configuration whether those will be unique or not.

Netdata cloud being a Certificate Authority can work around the issue of agent identification in the following way:
- Agents without a Certificate will create one before claiming but after installation.
- Netdata cloud remembers the public key for a given MACHINE_GUID. Any subsequent claiming requests **or** connection attempts for this MACHINE_GUID will be denied. The agent shall be advised to change its MACHINE_GUID.

However, there is still the possibility of cloning an agent after claiming, and as a result also cloning its Certificate. In this case, when netdata cloud detects a second connection attempt the agent is advised to create a new Certificate.

The agent also needs to get the invitation token in a secure and practical way. One way to do that is by using a new netdata configuration file with suitable permissions. This file will not be globally visible.

However, we also need a command line tool to interact with the agent at runtime, with some form of Inter-Process-Communication. I have rejected the following possibilities:

- POSIX pipes: they are unidirectional and as a result not practical to return a status. Moreover, they are multi-process unsafe and not portable to Windows.
- network sockets: there is no easy and obvious security model with networking even though its low performance is not likely to be an issue since we don't intend to use commands in rapid succession.
- message queues: we do not want asynchronous messages like a mailbox, we need real-time communication with the agent when it's online.
- shared memory: it's way too complicated to implement some sort of IPC queue, that is both multi-process safe and secure, from scratch.

The best solution seems to be libuv IPC pipes:
- They have a well defined file-based security model.
- They are cross platform (based on UNIX sockets and Windows named pipes).
- They are bidirectional so that commands can return status or other information.
- They are multi-process safe.

This command line tool will conveniently solve another problem of the netdata agent, which is that the signals are inadequate for communication with the agent, and that is especially true for Windows. There is some reference code in #7255 that adds IPC command support to the netdata agent. One can pass commands running:

```socat - UNIX-CONNECT:/tmp/netdata-cli```

The work to support agent claiming from the netdata agent side can be broken down to the following tasks:

- Introduce a new configuration file for claiming-related information storage and retrieval. Integrate it with the agent configuration modules and any relevant scripts such as installers. Create claiming-related state in the netdata agent memory that will be used by the command server and the agent-cloud communication modules. This state also includes tokens, client and server(CA) Certificates. Harden said state to be thread-safe and support asynchronous events. (5 days)
- Implement a command server in the netdata agent to receive commands from a command line tool in addition to the configuration file over libuv IPC pipes (based on #7255). (3 days)
- Implement a command line script (2 days)
- Implement the agent-cloud communication protocol (to be determined). (5 days?)

_Originally posted by @mfundul in https://github.com/netdata/netdata/issues/7052#issuecomment-549891013_

**Comment by amoss** [comment]
The description of the process currently has some holes to be refined. These questions arise:
1. How will the Cloud be informed of the public key for a MACHINE_GUID (in a way that cannot be spoofed)?
2. What is in the invite token, and how does it authenticate the claiming request?
3. Why is there a possibility of cloning after claiming, and can we remove it?
4. How do we handle exposure of an agent's private key?

We seem to be making the assumption that the channel that carries the token from the Cloud to the Agent (i.e. the user cutting-and-pasting from a https session to a ssh session) is private. This allows a simple solution by putting the CA / Server certficate processing in the Cloud, and using the token to carry the certificate and private key to the agent. This removes the need for the Agent to communicate any information to authenticate the claiming request. Individual Agent-Cloud links (after claiming) can then be authenticated by the pair of Certificates at connection time. A sketch of this is attached to try to clarify.

![Claiming_diagram](https://user-images.githubusercontent.com/1043609/68576349-362c2d80-046e-11ea-96ce-421bf8fba6c5.jpg)

**Comment by cakrit** [comment]
Two notes on the last comment:
- Cloning: An admin can take an existing image and use it to create multiple instances. We have seen the results of this happening after netdata has run at least once, of course the guid gets copied as well. We can't prevent it from happening.
- Entering a private key manually won't work, what happens when I have thousands of nodes? The claiming process itself needs to take care of that.

Perhaps we can avoid the security hassle by enforcing GUID uniqueness *per workspace*. I will explain the thought in the next refinement.

**Comment by amoss** [comment]
Here is a modified version to include @cakrit's comments above.
![Claiming_diagram2](https://user-images.githubusercontent.com/1043609/68655051-99ca5f80-052f-11ea-8572-7bdccd89e3ca.jpg)
This should allow for automated installs. The token is assumed to be private, but can be common to many installs. It is simply a random number - knowledge of the number proves that the user installed the node. The generation of the private key and CSR has moved onto the Agent. The CSR is sent back for signing, along with the random number. The GUID is ignored as it does not seem to serve any purpose. 

After the claiming process finishes both sides know the certificate of the agent. The Agent-Cloud link can then be set up each time with both server and client certificates.

**Comment by mfundul** [comment]
The MACHINE_GUID is the common name, it is what characterizes the node as what it is. Historical data will be gathered about this MACHINE_GUID over time. It is the identity of the node itself. During claiming, we should make the agent regenerate a MACHINE_GUID if a collision is detected, but it must be part of any protocol.

**Comment by amoss** [comment]
If the `MACHINE_GUID` is to be the name of the node then it must be unique, otherwise it is not a name. If it needs to be regenerated then the historical data about it no longer has any meaning.

> An admin can take an existing image and use it to create multiple instances. We have seen the results of this happening after netdata has run at least once, of course the guid gets copied as well. We can't prevent it from happening.

There are two ways that this can happen:
1. An admin builds a base-image, installs netdata in it and then uses it as a template for deployment.
2. A running instance containing netdata is cloned - i.e. in VirtualBox there is support for snapshoting running instances and then splitting the snapshot into another live instance. I'm unfamiliar with the equivalent in container, e.g. in docker the image is a file-system rather than snapshot of fs+mem.

We can force unique GUIDs in case (1), but in case (2) the software (including netdata) inside the image needs to be repaired to rebuild uniqueness.

If we are trying to fix case (2) then why alter the GUID to use as a name at all? The agent ends up with a public key / certificate as part of the claiming - it would be easier to use that as a name.

**Comment by mfundul** [comment]
It's not practical to use a certificate as a name. Certificates have explicitly been designed to authenticate names, not be names themselves. The `MACHINE_GUID` will be visible, it will be string-comparable, it can be pattern matched and it does not have to be cryptographically strong. We can even start using FQDN at some point without changing anything in the protocol.

**Comment by amoss** [comment]
How will the `MACHINE_GUID` behave when a node is cloned - can you walk through the steps that will happen and what effect it will have on what the user sees?

**Comment by mfundul** [comment]
> 
> 
> How will the `MACHINE_GUID` behave when a node is cloned - can you walk through the steps that will happen and what effect it will have on what the user sees?

Not yet!

**Comment by cakrit** [comment]
The following should clarify it a bit. We can discuss and make modifications where needed.

![Claiming](https://user-images.githubusercontent.com/43294513/68828056-1147de00-0659-11ea-9213-95d8f692bee7.png)

Note that if someone clones a machine AFTER claiming it, there's nothing we can do on the claiming side. The agent-cloud link should deny the second connection and create an alert for the dupication.

**Comment by nicolasparada** [comment]
All right, that can work, but I'll put my input here as well.
I have to say that I have not giving thinking to the claiming process, but anyway...
I thought the certificates would be on agent side, since to my understanding, is Cloud the one who will connect to the agent to execute commands and whatsoever. And the agent should have the private key.

**Comment by cakrit** [comment]
The cloud will generate the certificate. We've been discussing today the concern on how many of those certs we'll need create (perhaps too many). The alternative to creating agent-specific certs is what @amoss suggested in https://github.com/netdata/netdata/issues/7286#issuecomment-552790515 : Create workspace-specific certs (which would function as TOKENS) and combine them with a random number for each node. If we go that way, the flow will be slightly different (not much though, basically the variables will have different names).

**Comment by cosmix** [comment]
So the way I see authentication happening is in one of the following two ways:

1. By providing a client TLS certificate to the agent upon claiming, which will be used for (a) authenticating the agent when IT tries to connect to the cloud and (b) encrypting the communication when the browser tries to connect to it directly. To this end we can either use:

1.1. A public CA, e.g. Let's Encrypt to issue certificates for all agents. This may be impossible due to the quotas that Let's Encrypt imposes on its API users.

1.2. A private CA, which would allow us to issue any number of certificates, but, in this case, in order to satisfy (b) we'd need to also provide a wildcard 'workspace level' certificate to the agent issued by a public CA (e.g. `*.my-workspace.netdata.cloud`)

2. By introducing another protocol, on top of a TLS connection, that will achieve the same thing. Keys could be exchanged during claiming and henceforth used to establish _forward secrecy_ using ephemeral session keys. I would propose we used something like the Signal Protocol to achieve this.

**Comment by nicolasparada** [comment]
If the agent would be the one generating the certificate, then we could avoid the problem of Cloud generating too many certificates.

**Comment by cosmix** [comment]
Nope. Only the cloud has access to the DNS zone (used for validating the ownership of the hostname, seeing that the agent wouldn’t be responding on that hostname:port a priori. Also, there’s the matter of trust.

**Comment by cakrit** [comment]
> So the way I see authentication happening is in one of the following two ways:
> 1.  (b) encrypting the communication when the browser tries to connect to it directly. To this end we can either use:
> 1.2. in order to satisfy (b) we'd need to also provide a wildcard 'workspace level' certificate to the agent issued by a public CA (e.g. `*.my-workspace.netdata.cloud`)

Even at the workspace level, it will be problematic. Let's Encrypt [has a limit of 50 certs/week/domain](https://letsencrypt.org/docs/rate-limits/), so we'll have a problem immediately. So I suggest we use our own CA for the agent-cloud link and for (b) we do the following:
- No direct browser-agent comms via any *.netdata.cloud URLs, allow only tunneling ( browser-cloud-agent) when the agent is http. We can temporarily give unlimited such accesses for free (agreed with Costa in Athens last week), with the warning that we will be charging - e.g. based on usage - in the future. 
- Ask users to install their own certs and configure their https URLs, so that a browser-agent link can be used by default (fallback to tunneling only when agent is not reachable directly from the user's browser, due to firewalls, VPNs etc). 

If we do these two, then we completely decouple (a) from (b) and are free to do whatever we like for the agent-cloud link.

**Comment by cosmix** [comment]
> Even at the workspace level, it will be problematic. Let's Encrypt [has a limit of 50 certs/week/domain](https://letsencrypt.org/docs/rate-limits/), so we'll have a problem immediately.

You're right. But, there's also the 'rate limiting form' which provides for higher limits etc. (same URL), let alone other possible avenues we could pursue to get the certificates issued (other CAs, partnerships etc.)

>  So I suggest we use our own CA for the agent-cloud link

Well, this is also troublesome, as we'll need to support/maintain more infra.

> Ask users to install their own certs and configure their https URLs,

This, to my eyes, is too complex for a user to have to do. It should be turn-key. My €.02

**Comment by amoss** [comment]
When will the certificates be placed on the agent?

* If they are supplied at install time then we have a similar problem to unique tokens - i.e. how do we script large deployments?
* If they are sent to the agent from the cloud - how does the cloud know that it is supplying the certificate to a real node - i.e. we have the same problem in the node proving its identity.
* If they are sent to the agent after a successful claiming then they can secure the agent-cloud link but don't help us prove the identity of the node during claiming.

**Comment by amoss** [comment]
![IMG_0175](https://user-images.githubusercontent.com/1043609/69113325-fcb57c80-0a82-11ea-9545-3cd56bc57046.JPG)

Here is another version for discussion with ephemeral tokens, no certificates during the claiming (although they can optionally be stored at the end) and a separation of the security aspects from the functionality that we need. Includes the steps discussed for handling GUID collisions.

**Comment by stelfrag** [comment]
This is essentially an invitation to auto signup for a service (claiming) using an invite code (token, time or otherwise restricted) so that an _end user_ (agent) eventually will need to use a username (GUID) and password to connect.

Maybe an overkill but I would consider adding the following to the steps @amoss above **only so that** we don't store _passwords_ that can be leaked (the cloud side). I like the fact that certificates are not 
involved right from the start.

- AGENT claim (token, GUID, **password**) 
  - Agent generates and stores password locally
- CLOUD verifies (token, GUID) is invited to be claimed 
   - Cloud generates SALT key and does e.g SHA256 on (GUID, password) => AGENT_KEY 
      - Stores link (GUID, AGENT_KEY,  workspace)
      - Stores (GUID, SALT) separately

Further needed communication is done with (GUID, PASSWORD) and is verified by the cloud side
with  (GUID, PASSWORD) , lookup (GUID, SALT) recompute AGENT_KEY and match (GUID, AGENT_KEY) to workspace

**Comment by fracasula** [comment]
Sorry guys just a quick question, maybe I'm just confused by the whole conversation.
Is there any reason why we're not just using the good ol' pub-priv key pair encryption for securing the claiming?
As in having the agent generate a pair, the user copies the pubkey and pastes it in the cloud backend which generates its pair and the user copies again the cloud pubkey and pastes it in the agent. At that point we have a secure enough channel since the pubkeys won't be exposed further.

I mean, I'm sure there must be also other protocols that are secure enough and well tested. I'm just asking to make sure 1) I'm not missing something 2) we're not trying to reinvent the wheel.

**Comment by amoss** [comment]
If we go with the password idea for credentials instead of certificates then we have the issue that it is no longer a challenge-response to authenticate during connection. In a certificate-based system the cloud would store the public-key of each agent (the certificate) and send the private-key to the agent. This provides the same kind of safety - we don't store the credentials in a database on the cloud.

In the password scheme the agent authenticates itself by providing its secret. In a certificate-based scheme it authenticates itself by signing a challenge - it keeps its secret on the agent.

**Comment by fracasula** [comment]
> In the password scheme the agent authenticates itself by providing its secret. In a certificate-based scheme it authenticates itself by signing a challenge - it keeps its secret on the agent.

Exactly :+1:

**Comment by mfundul** [comment]
> 
> 
> If we go with the password idea for credentials instead of certificates then we have the issue that it is no longer a challenge-response to authenticate during connection. In a certificate-based system the cloud would store the public-key of each agent (the certificate) and send the private-key to the agent. This provides the same kind of safety - we don't store the credentials in a database on the cloud.
> 
> In the password scheme the agent authenticates itself by providing its secret. In a certificate-based scheme it authenticates itself by signing a challenge - it keeps its secret on the agent.

I think the problem is not storing any credentials in the database, since the hash that will be stored can be cryptographically strong.

The big difference is that the unencrypted password itself will be stored in the cloud's memory for a brief moment.

**Comment by hmoragrega** [comment]
The issue they talk about is after the claiming has been done; with the unique agent key/password , even if its generated in the cloud, the agent would need to send it over the wire on every request to the cloud so it can be verified, while with pair of keys the secret itself (the private key), would never leave the agent system

I really like @amoss flow completely 👏 

**1)** Cloud generates a workspace token. The token itself could contain an expiration date or max usages (although if we opt for having max usages the cloud needs to store how many times has been used successfully while you don't need this with time expiration since the token can have this information on it)
**2)** The token + the GUID is send by the agent in the claiming process
**3)** Cloud check errors (already claimed, different workspace, token expired...). If correct, it can generate a unique key pair for the agent, and then send the private key back to the agent where it is securely stored in the filesystem (so it can be read and used on a reboot/restart)
**4)** The agent can now use the private key to secure the messages while communicating with the cloud without having to send any key on the message itself

**Comment by mfundul** [comment]
Agreed, the password would be in the cloud's memory briefly every time the agent connects to the cloud. It won't be only the first time. It will also go over the wire but this is less of an issue since the communication should be encrypted.

So to sum up. Differences between salted password and public/private keys:

1. Over the wire (every connection) - public key versus encrypted password
2. In cloud storage - public key versus salted password
3. In cloud memory (every connection) - public key versus unencrypted password

Is this correct?

**Comment by amoss** [comment]
I reacted with a thumb up @mfundul but I realize there is a subtle difference - in (1) and (3) it would not be the public key but a signature of the challenge performed by the private key.

**Comment by mfundul** [comment]
> 
> 
> I reacted with a thumb up @mfundul but I realize there is a subtle difference - in (1) and (3) it would not be the public key but a signature of the challenge performed by the private key.

Yes, of course, you are correct. In (1) and (3) Public key will reside only once, and the rest of the times it should be the signature.

**Comment by mfundul** [comment]
I think we have not discussed the matter of trusting the cloud side. Is it safe to assume that agent can connect to any hostname or IP address and plainly send the token? This sounds to me that the token will leak very easily.

**Comment by amoss** [comment]
I remember this was mentioned in one of the meetings - we can assume that the cloud certificate is known (I.e. we inserted the trust root at installation time). When we connect to the cloud we can verify the (known) signature to prevent connecting to the wrong machine.

**Comment by amoss** [comment]
Design has been finished. Issues will be created for the core-team to work on implementing this and we will sync with the cloud team about their implementation.
