### ISSUE TITLE
more nodes OS icons, with fallback

### ISSUE THREAD

**Issue by romain-dartigues** [netdata/netdata#7307]
First of all, I'm not sure this FR belongs to this repository, but as I didn't find one specifically for "netdata.cloud", I open it here.

##### Feature idea summary

I would like to see more OS icons in the `agent-card__os` of the Netdata Console (β).

I would also like to have a fallback on the OS family if there is no icon for the specific version; the fallback icon could be greyed out (monochrome) to indicate it's not the accurate icon.

##### Expected behavior

For a node running Linux Mint, I would like to see the appropriate icon (publicity: there is a 1017B version at edent/SuperTinyIcons#364; if you'd like small icons I'd be happy to work on it).

For any given OS where there is no icon for the exact OS, I would like a fallback to the icon of the OS family; for example:

- Is there a logo for Linux Mint? no, `os_id_like: ubuntu`; is there a logo for Ubuntu? yes!
- Is there a logo for Elastix? no, `os_id_like: centos`; is there a logo for CentOS? maybe not, fallback to RedHat
- Is there a logo for VoidLinux? probably no, is there a `os_id_like` ? probably no, fallback to `kernel_name` -> Linux

**Comment by romain-dartigues** [comment]
BTW, if you could point me (us) where the related code live, I (or someone else) could try to work on it and submit a merge request ;^)

**Comment by cakrit** [comment]
Hi @romain-dartigues and apologies for not replying sooner. 
We will set up a new support channel, dedicated to the cloud, but  I'll add these suggestions to the relevant internal repo for now, because they're awesome!

Regarding the PR, although netdata.cloud [will remain free forever](https://blog.netdata.cloud/posts/netdata-cloud-announcement/), the code is proprietary. 

We are feverishly working on a completely revamped version of the cloud, coming in ~1 month. Stay tuned and I think you'll like what you'll see! :)
