### ISSUE TITLE
system.net in custom Multi-Host Dashboard

### ISSUE THREAD

**Issue by Xplouder** [netdata/netdata#7313]
##### Bug report summary
Using the **system.net** metadata in a dashboard template as referenced [here](https://docs.netdata.cloud/web/gui/custom/#dash-multi-host-dashboard) it's data are the same across all the charts.

##### OS / Environment
`CentOS Linux release 7.7.1908 (Core)`
`Linux master 3.10.0-1062.1.1.el7.x86_64 #1 SMP Fri Sep 13 22:55:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

##### Netdata version (output of `netdata -V`)
netdata v1.18.1

##### Component Name
Probably **system.net** collector when using a streaming architecture.

##### Steps To Reproduce
- Setup a streaming architecture (1 master and N slaves)
- Follow [this](https://docs.netdata.cloud/web/gui/custom/#dash-multi-host-dashboard) steps to create your own Multi-host Dashboard
- Edit the created dashboard and add this inside `<div class="dash-charts">` tag: 
```
<div class="dash-graph"
      data-netdata="system.net"
      data-chart-library="sparkline"
      data-dimensions="received"
      data-legend="no"
      data-title="Incoming traffic"
      data-width="100%"
      data-height="30">
</div>
```
and 
```
<div class="dash-graph"
      data-netdata="system.net"
      data-chart-library="sparkline"
      data-dimensions="sent"
      data-legend="no"
      data-title="Outgoing traffic"
      data-width="100%"
      data-height="30">
</div>
```
- Do some network trafic like  a speed test in random host like a speed test and check all the graphs be synced to each other.

##### Expected behavior
All the host owns its data, in this particular case, the **system.net** of each host be different resulting in different charts.

**Comment by jacekkolasa** [comment]
@Xplouder you are probably not using `data-dash-netdata` functionality, could you please check if changing `data-netdata=` to `data-dash-netdata=` fixes your problem?

**Comment by Xplouder** [comment]
@jacekkolasa that seems to fix the problem... may I ask you how `data-dash-netdata` differs from `data-netdata`? I couldn't find documentation for it.
Thank you!

**Comment by jacekkolasa** [comment]
Glad it works now! `data-netdata` is the base attribute which dashboard.js is using. You can read about it [here - https://docs.netdata.cloud/web/gui/custom/#adding-charts](https://docs.netdata.cloud/web/gui/custom/#adding-charts). When dashboard.js sees `data-netdata=` attribute, it builds a chart inside that node.

Multi-host Dashboard is a new feature - example build on top of dashboard.js. It checks for `div`s with `data-dash-netdata=` attributes, and based on this creates multiple nodes with `data-netdata=` attributes, which dashboard.js later uses.

Because the issue has been fixed, i'll close the issue, but if you have any questions, feel free to ask here.

**Comment by Xplouder** [comment]
Aight! Makes sense, thank you again.
