### ISSUE TITLE
Are NGINX Load Balancer Metrics Tracked?

### ISSUE THREAD

**Issue by AbdelmalekIhdene** [netdata/netdata#7344]
##### Question summary
I just found out about netdata and I was wondering if load balancer redirection metrics are tracked by netdata. I have a setup with nodes behind an NGINX reverse proxy and I want to try out netdata for system metrics tracking. If that is not the case, is that possible to do via extra plugins/modules, I would be more than happy to contribute.
##### OS / Environment
Ubuntu 18.04 LTS

**Comment by ilyam8** [comment]
yo @AbdelmalekIhdene 

How to get NGINX Load Balancer metrics? could you provide a link or give some detail on subj?

**Comment by ilyam8** [comment]
The only thing that comes into my mind is info from logs - [`$upstream_*` fields](http://nginx.org/en/docs/varindex.html)

or you are saying about nginx plus?

**Comment by AbdelmalekIhdene** [comment]
Yep, I believe the variable would be $upstream_addr, i.e. tracking the load balancer's activity.

**Comment by ilyam8** [comment]
> If several servers were contacted during request processing, their addresses are separated by commas, e.g. “192.168.1.1:80, 192.168.1.2:80, unix:/tmp/sock”.

Then we need to += 1 for every upstream server in the list?

> If an internal redirect from one server group to another happens, initiated by “X-Accel-Redirect” or error_page, then the server addresses from different groups are separated by colons, e.g. “192.168.1.1:80, 192.168.1.2:80, unix:/tmp/sock : 192.168.10.1:80, 192.168.10.2:80”.

What about this case?

**Comment by Ferroin** [comment]
> > If several servers were contacted during request processing, their addresses are separated by commas, e.g. “192.168.1.1:80, 192.168.1.2:80, unix:/tmp/sock”.
> 
> Then we need to += 1 for every upstream server in the list?

Yes, unless I'm seriously misunderstanding how nginx populates the value of `$upstream_addr`.

We need to make a point to account for IPv4, IPv6, and UDS addresses.
> 
> > If an internal redirect from one server group to another happens, initiated by “X-Accel-Redirect” or error_page, then the server addresses from different groups are separated by colons, e.g. “192.168.1.1:80, 192.168.1.2:80, unix:/tmp/sock : 192.168.10.1:80, 192.168.10.2:80”.
> 
> What about this case?

This is just me, but I'd say that we should count all of them.

---

Note that we may not be able to track how many individual requests have to be made to each upstream server. It's absolutely possible for one downstream request to result in multiple upstream requests to the same upstream server during request processing, and I'm pretty sure that in that case, nginx will only show the address for that upstream once instead of once per request in `$upstream_addr`.

**Comment by ilyam8** [comment]
> We need to make a point to account for IPv4, IPv6, and UDS addresses.

Why we need to differentiate between them? It seems the idea is to account requests per upstream server. 

> different groups are separated by colons

Not great ~not terrible~. They use colon to separate address and port, it used in ipv6 address and same symbol is used for group separating.

**Comment by Ferroin** [comment]
> > We need to make a point to account for IPv4, IPv6, and UDS addresses.
> 
> Why so we need to differentiate between them? It seems the idea is to account requests per upstream server.

I meant that the parser needs to be written so that it properly recognizes all three types of address as being valid upstream server addresses, not that we need to differentiate.  It would be unfortunate if we were to write this up and it lost it's mind when it saw an IPv6 address in the list.

Essentially, I'm assuming we're doing _some_ kind of validation of what we're parsing to make it less likely that misconfiguration leads to stuff like the parser eating the rest of the line.
> 
> > different groups are separated by colons
> 
> Not great ~not terrible~. They use colon to separate address and port, it used in ipv6 address and same symbol is used for group separating.

Agreed, though it looks like when separating groups they pad the `:` with a space on both sides so that it can't be mistaken for ports or IPv6 address components (not certain about this, but every sample I've seen that had multiple groups had a space around the colon).

**Comment by ilyam8** [comment]
> If several servers were contacted during request processing, their addresses are separated by commas, e.g. “192.168.1.1:80, 192.168.1.2:80, unix:/tmp/sock”.

> If an internal redirect from one server group to another happens, initiated by “X-Accel-Redirect” or error_page, then the server addresses from different groups are separated by colons, e.g. “192.168.1.1:80, 192.168.1.2:80, unix:/tmp/sock : 192.168.10.1:80, 192.168.10.2:80”.

> If a server cannot be selected, the variable keeps the name of the server group.

All possible variants:

> one server

-   '192.168.1.1:80'

> several servers

-   '192.168.1.1:80, 192.168.1.2:80, ...'

> two groups one sever in each group

-   '192.168.1.1:80 : 192.168.1.3:80'

> two groups several severs in each group

-   '192.168.1.1:80, 192.168.1.2:80, ... : 192.168.1.3:80, 192.168.1.4:80, ...'

> server group name

-   'some name'

How many groups can we have? Any number? Asking because there is only two in the example.

**Comment by ilyam8** [comment]
And we need to think how to represent new metrics. It is not clear because of netdata's limitation - it is impossible to show nested data on the dasbhoard. We need to take in to account that we will add other `upstream_*` metrics in the future.

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
