### ISSUE TITLE
bash script fetching unknown package libc-dev

### ISSUE THREAD

**Issue by mmccollum2** [netdata/netdata#7353]
##### Bug report summary
bash <(curl -Ss https://my-netdata.io/kickstart.sh)
ends up trying to grab http://archive.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_4.15.0-66.75_amd64.deb which doesn't exist on that repository anymore
[Pic here](https://imgur.com/a/KOMFoMP)
##### OS / Environment
Ubuntu 18.04.3 LTS
##### Netdata version (ouput of `netdata -V`)
Didn't end up installing, but current as of Nov 21 (approx v1.18.1)
##### Steps To Reproduce
Run the one liner bash and install required packages, but then it fails to find a package that isn't available on the repository anymore
##### Expected behavior
happy and successful one liner install

**Comment by mmccollum2** [comment]
Sorry all, i'm new to Github issues and submitting bugs. Hope this helps.

**Comment by Saruspete** [comment]
Hello,

Thanks for reporting, and welcome to github :)

Seems this issue is due to your package manager, more precisely to the cache of your packages index. It's your duty to do a `apt-get update`  to update your cache before working with packages.

What is more on netdata side, is the following warning that is only visible during dry-run. 

```sh
install_apt_get() {                                                        
    # download the latest package info                     
    if [ "${DRYRUN}" -eq 1 ]                             
        then                                      
        echo >&2 " >> IMPORTANT << "                                           
        echo >&2 "    Please make sure your system is up to date"     
        echo >&2 "    by running:  ${sudo} apt-get update  "                   
        echo >&2                                                               
    fi                                                                         
```

I would have displayed this warning either:
- every time (but noizy)
- when a package install fails
- when the last update is more than X days. Seems doable by checking `/var/lib/apt/periodic/update-success-stamp` or `/var/cache/apt/pkgcache.bin`

**Comment by ncmans** [comment]
@Saruspete seems to be right about the cause as I cannot reproduce. The libc-dev as of this comment is at version [`4.15.0-72.81`](http://archive.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_4.15.0-72.81_amd64.deb) which is available.

One idea is to automatically run the package manager's update command either every time or when staleness is detected so as to avoid the situation the OP encountered.
