### ISSUE TITLE
libuv becomes a hard dependency

### ISSUE THREAD

**Issue by knatsakis** [netdata/netdata#7354]
#### Bug report summary
Figure out if any of the distributions in our support matrix don't have a binary libuv package

https://docs.netdata.cloud/packaging/distributions

##### OS / Environment
All

##### Netdata version (ouput of `netdata -V`)
Current

**Comment by mfundul** [comment]
Related #7325

**Comment by knatsakis** [comment]
@mfundul has already updated our documentation regarding CentOS 6:
https://github.com/netdata/netdata/tree/master/packaging/installer#prepare-your-system

It seems that CentOS is the only problematic OS and only needs the OKay repository.

- Decide if the installer will ask user and add additional repositories in some cases like CentOS 6 (the same issue exists with DBEngine dependencies)

- Another option is to copy the libuv1 package from the OKay repository to our packagecloud repository

**Comment by Saruspete** [comment]
Hello,

For my prod, I moved `memory mode` from `map` to `dbengine`. However, I didn't see the configure step failing when building the package for RHEL6. It failed because libuv version provided by EPEL6 is 0.10.34, which is too old for netdata.

I then tried to see if I could embed the library within the package, but it's kinda the only library without env var / option to specify alternative path.

Finally, I took the specfile from [EPEL7 libuv 1.22](https://src.fedoraproject.org/rpms/libuv/blob/epel7/f/libuv.spec) and rebuilt it without trouble.

I would have loved to be able to embed the libuv as static, so not to mess too much with this need for dbengine.

**Comment by mfundul** [comment]
> 
> 
> Hello,
> 
> For my prod, I moved `memory mode` from `map` to `dbengine`. However, I didn't see the configure step failing when building the package for RHEL6. It failed because libuv version provided by EPEL6 is 0.10.34, which is too old for netdata.
> 
> I then tried to see if I could embed the library within the package, but it's kinda the only library without env var / option to specify alternative path.
> 
> Finally, I took the specfile from [EPEL7 libuv 1.22](https://src.fedoraproject.org/rpms/libuv/blob/epel7/f/libuv.spec) and rebuilt it without trouble.
> 
> I would have loved to be able to embed the libuv as static, so not to mess too much with this need for dbengine.

We do have simpler instructions about it [here](https://github.com/netdata/netdata/tree/master/packaging/installer#prepare-your-system).

Alternatively you can download the rpms themselves from:
https://centos.pkgs.org/6/okey-x86_64/libuv-devel-1.9.1-3.el6.x86_64.rpm.html
https://centos.pkgs.org/6/okey-x86_64/libuv-static-1.9.1-3.el6.x86_64.rpm.html

**Comment by Saruspete** [comment]
indeed, but we use a Satellite to distribute the packages, so to just add this package I would either have to sync the whole Okey repo (centos while being on RHEL), or either download only the package, resign it, push it in our custom distribution channel, but it would have a different build-host release and version from the RHEL7. 
Better to rebuild it to ensure RHEL6 & 7 have the same versions.

**Comment by knatsakis** [comment]
PR #7636 updated the support matrix in our documentation. Closing this.
