### ISSUE TITLE
As a user, I want to use labels to correlate my alarms/alarm notifications

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#7370]
See https://github.com/netdata/netdata/issues/6503#issuecomment-531270316
We need to discuss what we'll do and how

**Comment by thiagoftsm** [comment]
I think we can do something like we did for `template for all dimensions`. Every time that we are creating an entity that has the specific label, we can create an alarm for it, this would work for almost  everything, the unique exception that comes in my mind now is the `host` creation, because we load specific alarms for it when we are creating, but we can overcome this creating the alarm when the host creation finalizes.

**Comment by cakrit** [comment]
> I think we can do something like we did for `template for all dimensions`. Every time that we are creating an entity that has the specific label, we can create an alarm for it, this would work for almost everything, the unique exception that comes in my mind now is the `host` creation, because we load specific alarms for it when we are creating, but we can overcome this creating the alarm when the host creation finalizes.

That's the easy part, it's described at #7369. The question here is mainly on searching alarms, sending labels in alarm notifications etc.

**Comment by thiagoftsm** [comment]
To send a label in the alarm notification, I think we will need to have a pointer for the alarm(`RRDCALC`) inside (`ALARM_ENTRY`), we do not need to use `strdup` for this case, because the alarm won't be removed.

About the search, we will need to have another index exclusively for this, the `ALARM_ENTRY` structure does not have a direct `avl` structure inside it, probably we will need to set it.

About the field used to do the research, I will write on #7369.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
