### ISSUE TITLE
Allow opt-out of telemetry via environment variables and command-line args

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#7404]
See https://github.com/netdata/netdata/issues/7366#issuecomment-560169517 from @titpetric 
We need to make it simpler for people to opt-out from telemetry when installing via docker (and obviously document the fact) and add a CLI option to netdata. 

Related: https://github.com/netdata/netdata/issues/7401

**Comment by sneak** [comment]
May I recommend https://consoledonottrack.com ?

The suggestion there is to use the env var `DO_NOT_TRACK`.

**Comment by titpetric** [comment]
@sneak that's a great suggestion. @cakrit could I get a confirmation here, so I can pre-emptively implement this for titpetric/netdata before you're ready?

**Comment by sneak** [comment]
With tracking on by default, you will still be in violation of the Docker Hub ToS which prohibits nonconsensual spyware, @titpetric.

**Comment by cakrit** [comment]
That's awesome, yes. Really cool that such a variable exists.

**Comment by titpetric** [comment]
@sneak there's disagreement here if telemetry is or isn't spyware, and the exact wording of docker hub TOS is different than yours, and the technical details from end-to-end have already been discussed at length. I'm not going to enter these debates with you anymore since it's pointless.

As long as telemetry is opt-out on netdata, it will remain so on titpetric/netdata as well.

**Comment by cakrit** [comment]
@prologic let's put this in the next sprint please.
