### ISSUE TITLE
Load labels from a config file

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#7410]
- [x] Add functionality to the config file routines to reload a single section.
- [x] Add a `[host labels]` section to `netdata.conf`.
- [x] Add functionality to build a list of key/value pairs in a fresh list (using the struct from #7408) but not store it in the RRDHOST.
- [x] A separate procedure that acquires the locks, replaces the RRDHOST list of labels, releases the locks and then cleans up the old list.
- [x] Label keys must be `[a-zA-Z0-9_.-]+`.
- [x] Label values can be UTF-8 strings.
- [x] Must skip over `from environment` and `from kubernetes pods` as key values.
- [x] Load the labels from the config during agent startup.

**Comment by stelfrag** [comment]
Good job! that describes the building blocks we need to work on, then we just need
to assemble them together and verify that we have the "business" logic in place.

Comments:

- What is the `from environment` directive -- you mean if there `NETDATA_LABEL_<name> =<value>` in the environment?
- `from kubernetes` should make a note, somehow, to let the cgroup-name.sh script that it needs to fetch / parse and store the kubernetes labels (by calling the new function we will build)
   - Determine if the check for kubernetes can be done as soon as possible (The #7416 arrives just in time to further tune this) 

To sum it  up. We assume that in the labels section we have:

1. User defined labels
1. from kubernetes directive (or other container)
1. More user defined labels what may override things (especially from part 2)

We will:
- Apply the labels ASAP from section 1
- Wait for container labels to get fetched  / parsed and added
  - Need to check what it would mean to do this synchronously
    - When the config file is loaded, not everything is initialized
    - If it can be done, what impact will that have to the agent startup time
  - If not synchronously, need to examine what will happen during the time that the agent config is laoded but container labels are still missing (because we wait for step 2 to complete before we move on to step 3)
    - Metrics and alarms for example will be in place and may start using labels before we complete steps 2 and 3
- Apply labels from 3

**Comment by amoss** [comment]
The `from environment =` directive was to support labels in a docker container. We didn't specifiy in the technical refinement meeting what those variables would be, or how that interface would work so the comment about skipping over the directive is really a placeholder for a future task. This could be `NETDATA_LABEL_` as you describe if this matches how we anticipate the docker interface would work.

There would be no container labels in this task at all. Your summary about the startup time and the need to delay everything until the labels are populated is entirely correct - but it would happen after #7411 during the #7412 integration task.
