### ISSUE TITLE
Alarm muting don't do anything

### ISSUE THREAD

**Issue by stemy2** [netdata/netdata#7483]
##### Bug report summary
I tried to mute all alarms, but they're all still active.
##### OS / Environment
Yunohost
##### Netdata version (ouput of `netdata -V`)
Unknown (command return «-bash: netdata: command not found
»)
##### Component Name
Health
##### Steps To Reproduce
1)Type «curl "http://stemy.me/netdata/api/v1/manage/health?cmd=SILENCE ALL" -H "X-Auth-Token: [token]"
2) Get the confirmation that alarm are muted.
3) Alarm still coming.
##### Expected behavior
Alarms actually muted.

**Comment by thiagoftsm** [comment]
Hi @stemy2 ,

I executed a test in my side and everything worked fine, so I will do few questions for you, for we understand what is happening in your side.

1) How did you install Netdata?
2) Did you get the token from the file `/var/lib/netdata/netdata.api.key`?
3) Can you confirm us that your file `/var/lib/netdata/health.silencers.json` has the following content
```
{
        "all": true,
        "type": "SILENCE",
        "silencers": []
}
```
?

Finally I will say a difference between the command you used and the command I used, in my I used the following URL `https://192.168.0.12:19999/api/v1/manage/health?cmd=SILENCE%20ALL`, because I decided do not trust in the curl conversion from space to '%20', so my command become `curl -H "X-Auth-Token: [my token]" -k "https://192.168.0.12:19999/api/v1/manage/health?cmd=SILENCE%20ALL"`

Best regards!

**Comment by cakrit** [comment]
Closing due to no response.
