### ISSUE TITLE
Send labels from slave to master

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#7486]
The streaming protocol needs to be extended, so that slaves can send host labels to their master.

**Comment by stelfrag** [comment]
Adding a command to the protocol will require both master + slave to be at the same version (or at least, for the master, the minimum version that will support the new command). 

This is because any command that  the master does not understand, terminates the streaming connection. 

This will happen  if there are cases where slave agents may be updated and masters are not, 

Just a thought ..

If one of the existing commands is used (e.g. VARIABLE), it could allow the "labels" enabled slave to send labels to a master as special variables e.g. LABEL_ prefixed (of course the master would not know they are labels), until the master is also updated to an appropriate version and handle those LABEL_ variables

**Comment by thiagoftsm** [comment]
I agree with you, I think it will be a safe choice avoid to send the labels a second time case the streaming is closed and we will send a message for the user error log requesting an update on master side.

**Comment by amoss** [comment]
This should not be added to the sprint milestone without an estimate of the work and agreement from the team.

**Comment by thiagoftsm** [comment]
From product channel:

Streaming: We add a protocol version to the STREAM get request. The server responds with support for that version, if it has been upgraded. Then we know we can send the host labels

**Comment by amoss** [comment]
Merged but not closed?
