### ISSUE TITLE
Getting nginx status metrics from nginx-module-vts

### ISSUE THREAD

**Issue by smart-developerr** [netdata/netdata#7501]
Hello!
I want to get status metrics and graphs from [nginx-module-vts](https://github.com/vozlt/nginx-module-vts) module and show them in netdata instead of using simple [stub_status](https://docs.netdata.cloud/collectors/python.d.plugin/nginx/).
How could I get there and which [format ](https://github.com/vozlt/nginx-module-vts#description)should I use?

**Comment by ilyam8** [comment]
Hi, try to use `nginx_plus` module

https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/nginx_plus

I assume you need `/status/format/json` format.

But there is a chance `nginx_plus` wont do, i think it is outdated a bit. It is hard to fix it since netdata doesnt support labels. The data is quite nested and it is impossible to represent it on the netdata dashboard.


Go implementation is blocked
> https://github.com/netdata/go.d.plugin/pull/73
