### ISSUE TITLE
netdata log collectors for Docker?

### ISSUE THREAD

**Issue by hazcod** [netdata/netdata#7517]
### Question summary
Netdata log collectors (e.g. for nginx) offer a great way to keep tabs on network or HTTP errors.
However, those need log files on the filesystem to scrape, while we use log shipping for docker containers to e.g. ELK. What is the preferred solution here?

**Comment by Ferroin** [comment]
@ilyam8 For the generic log parser stuff that you're working on, it would be awesome to support situations like this where logs are stored in some format other than just on the filesystem.

**Comment by ilyam8** [comment]
i think this has nothing in common with generic log parser.

> those need log files on the filesystem to scrape

Yes. What other sources do we need to support? And it would be nice if you provide some examples of existing solutions which has such support.

**Comment by ilyam8** [comment]
It seems we need to get docker logs from docker remote api

https://github.com/influxdata/telegraf/tree/master/plugins/inputs/docker_log

**Comment by Ferroin** [comment]
@ilyam8 The systemd journal comes to mind immediately, as there are some systems that just log everything there instead of using regular log files (not that I think such configurations are a good idea, but they do exist).  [rsyslog has a module that can do this](https://www.rsyslog.com/doc/v8-stable/configuration/modules/imjournal.html), but it reads the journal files directly.

Being able to listen on a socket and consume log records via RELP, RFC 3195, or the old-style syslog protocol would also be potentially useful (rsyslog or syslog-ng may be helpful as references for these as well).

Most of the other possibilities (elasticsearch via logstash, various RDBMS implementations, etc) are better covered by generic database modules instead.

**Comment by nodiscc** [comment]
My workaround for docker container logs not being easily accessible from the host, is to forward them to the host's syslog https://docs.docker.com/config/containers/logging/syslog/

```json
# /etc/docker/daemon.json
{
  "log-driver": "syslog"
}
```

But I still haven't found a way to make netdata ingest these.

**Comment by ilyam8** [comment]
I am pretty sure we need to read container logs from docker remote api.

The problem that it doesnt really map on how plugin works. 

It's not a good idea to ask a user to set container id in the module config (N container - N configs).

Ideally the module should:

- get container list
- match appropriate names/labels
- start to read matched container logs

It is impossible to achieve with current plugins implementation and 2-level dashboard.

**Comment by ilyam8** [comment]
> forward them to the host's syslog

Redirect to files. Every container to a separate file 😄 

> https://www.rsyslog.com/doc/v8-stable/configuration/modules/omfile.html

**Comment by nodiscc** [comment]
> Each container logs to a separate file

This is exactly what I don't want because my logs end up scattered across many files, while I want everything to be aggregated (I use https://www.rsyslog.com/doc/v8-stable/configuration/modules/imfile.html for apps that can't natively log to syslog), and then do log analysis with something like [lnav](https://lnav.org/) (small scale) or [graylog](https://www.graylog.org/) medium/large scale. 

Graylog can do everything but is a bit heavy on resources for small setups, and lnav can't do alerts. I was hoping netdata would be a middle ground for simple things like raising alerts on failed backups in logs, dockerized web servers returning unusual amounts of error codes, etc.

**Comment by hazcod** [comment]
Sounds like the host syslog could be a great solution, however I suppose one would want it shipped to real log aggregator too to get the full logs. (Eg ELk, graylog, ...)

Are there any database drivers yet for log fetching for netdata?

**Comment by nodiscc** [comment]
>one would want it shipped to real log aggregator

This can be down at the same time (a good solution is [TCP/TLS](https://rsyslog-doc.readthedocs.io/en/stable/tutorials/tls_cert_summary.html) forwarding, and [disk queues](https://www.rsyslog.com/doc/v8-stable/concepts/queues.html#disk-queues))

> Are there any database drivers yet for log fetching for netdata?

As far as I know there are collectors for [web_log](https://docs.netdata.cloud/collectors/python.d.plugin/web_log/), `smartd_log`, `ovpn_status`_log`, but no generic collector to check for the presence/absence/rate/time since last occurence of a specific message in a log file.

This issue is not specific to docker as docker logs can easily be forwarded to syslog.

This would be a great addition

**Comment by ilyam8** [comment]
Well, please jump in

https://github.com/netdata/netdata/issues/7420

See https://github.com/netdata/netdata/issues/7420#issuecomment-567153095

**Comment by ilyam8** [comment]
We need to understand how to implement it, i am waiting for users suggestion 😄

**Comment by ilyam8** [comment]
About docker in general - i think we need to poll remote api to autodetect app and   (try) to monitor it. For instance if it is a nginx containers we need to read it logs and gather stub_status.

So we need to imporove autodetection, this would be very nice.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
