### ISSUE TITLE
Need to support Python Virtual Environments

### ISSUE THREAD

**Issue by werowe** [netdata/netdata#7519]
Some users will not like that you have to install PyMySQL system wide since users often have problems with Python.  That's why they use virtual environments. For example, on several tries it asked me to install Query, but that would not install because there was no such Python module available in the Python 2.7 environment.

**Comment by ilyam8** [comment]
Yes, all packages should be installed system wide. You cant install them using `--user` flag because of

https://github.com/netdata/netdata/issues/6865#issuecomment-543763697

I think you can run `python` interpreter from your virtual env btw

Find `[plugin:python.d]` section in the `netdata.conf`

There is `command options = `

i think this will do

```
command options = -p/path/to/virtualenv/bin/python
```

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
