### ISSUE TITLE
After upgrade to v1.19.0-129, the cross chart variable reference is no longer working

### ISSUE THREAD

**Issue by startryst** [netdata/netdata#7567]
##### Bug report summary
The below alarm configuration working fine before v1.19.0-129:

1. Three virtual NIC, each of them is a tunnel interface
2. alarm template of 'Bandwidth_over_Subscribed' is to measure the 1 minutes average speed for each vnic
3. alarm 'Receiving_Bandwidth_Over_Subscribed' attached to net.vnic1 is to add all three virtual NIC's last 1 minutes speed altogether to see if it's over 10m
4. The calc of '$this/1000 + $net.vnic2.Bandwidth_Over_Subscribed_received/1000 + $net.vnic3.Bandwidth_Over_Subscribed_received/1000' works fine before v1.19.0-129, but after 129, it's no longer working.

```
# -----------------------------------------------------------------------------
# check for speed over threshold
template: Bandwidth_Over_Subscribed
      on: net.net
families: vnic1 vnic2 vnic3
  lookup: average -1m absolute foreach received,sent
    calc: $this/1000
   units: Mbps
   every: 1m
    warn: $this > 5
    crit: $this > 7
      to: sysadmin

   alarm: Receiving_Bandwidth_Over_Subscribed
      on: net.vnic1
  lookup: average -1m absolute of received
    calc: $this/1000 + $net.vnic2.Bandwidth_Over_Subscribed_received/1000 + $net.vnic3.Bandwidth_Over_Subscribed_received/1000
   units: Mbps
   every: 1m
    warn: $this > 10
      to: sysadmin

```

##### Netdata version (ouput of `netdata -V`)
netdata v1.19.0-129-nightly
netdata v1.19.0-138-nightly
tried both version above, all not working, but before 129 it's working fine.

**Comment by thiagoftsm** [comment]
Hi @startryst ,

When you do a requests like this `http://localhost:19999/api/v1/alarm_variables?chart=net.net` and `http://localhost:19999/api/v1/alarm_variables?chart=net.vnic1`, can you see the variables used in this alarm?
Do your `error.log` says something about the alarms?

best regards!

**Comment by startryst** [comment]
> Hi @startryst ,
> 
> When you do a requests like this `http://localhost:19999/api/v1/alarm_variables?chart=net.net` and `http://localhost:19999/api/v1/alarm_variables?chart=net.vnic1`, can you see the variables used in this alarm?
> Do your `error.log` says something about the alarms?
> 
> best regards!

Yes, it's there, but the difference is before v129, the unit of received value is kbps, no matter direct/cross chart reference, or even with calc (as you see in my template 'Bandwidth_Over_Subscribed', there is a calc to divide 1000, reason is to show the Mbps), but when I reference that variable in my alarm template('Receiving_Bandwidth_Over_Subscribed), I still need to divide that variable by 1000, because before v129, I  found **that value is before calc**; but after 129, the same variable, now the unit of the variable changes to Mbps, which is **the after calc value**.

So can you help to confirm, is that the change the team made: before 129, when cross chart reference the variable, that variable is the before calc(even calc is there), but after 129, the cross chart reference variable is changed to the after calc one?

**Comment by thiagoftsm** [comment]
I was verifying our code and we continue storing data using `kilobits/s` https://github.com/netdata/netdata/blob/c1436efd00c5b9afdb3779585eb194ea8388a932/collectors/proc.plugin/proc_net_dev.c#L618 , but we merged a bug fix for our database, what is the memory mode that you are using?

**Comment by startryst** [comment]
> I was verifying our code and we continue storing data using `kilobits/s`
> 
> https://github.com/netdata/netdata/blob/c1436efd00c5b9afdb3779585eb194ea8388a932/collectors/proc.plugin/proc_net_dev.c#L618
> 
> , but we merged a bug fix for our database, what is the memory mode that you are using?

below is the related config from my netdata.

        # memory mode = dbengine
         page cache size = 64
         dbengine disk space = 1024

**Comment by thiagoftsm** [comment]
Hi @startryst ,

Firstly I apologize the delay, but I wanted to answer you only after I do a deep investigation of the case.
I was working in the last hour in this issue to try to understand the motive you are having this problem and I think I understood it. I tested the latest Netdata and Netdata 1.18.1. In both versions and I am almost sure that this happened also in old versions, because for bandwidth Netdata parses a proc file, we are always exporting values in the same order `kilobits/s`, and you can confirm this doing a request for raw data (`http://localhost:19999/api/v1/data?chart=net.vnic1`, but when we go to the dashboard we have the description `megabits/s`  every time that we cross the limit `1000 kilobits`. I arrived in this conclusion doing the following steps:

1 - I compiled the newest Netdata.
2 - I started a Netdata running `/usr/sbin/netdata` .
3 - I wait 10 minutes without to do any kind of download or upload to confirm that the chart was complete filled on the screen.
4 - I started a download. In this moment my charts changed from `kilobits/s` to `megabits/s`
5 - To have data to compare with an old version, I executed the command `curl -o values119 -k https://192.168.0.12:19999/api/v1/chart?chart=net.wlan0`.
6 - I stopped Netdata.
7 - I compiled another Netdata version, but this time I used the options `-- install /opt --dont-start-it`
8 - I started Netdata running `/opt/netdata/usr/sbin/netdata`.
9 - I executed the steps `2` - `6` again, but I changed the output name in `5` to `values1181` before to execute the command `curl`.
10 - I restart the latest Netdata.

For both versions I had exactly the same behavior on my dashboard and I could confirm this with the files `values119` and `values1181`.

>  the cross chart reference variable is changed to the after calc one?

No, the charts will continue having the same order unless the Linux kernel team changes what they are sending to `/proc` files.

Best regards!

**Comment by startryst** [comment]
Hi, @thiagoftsm 

First of all, thank for your time to investigate further, even though it may not be a hot/priorities feature, but it's essential for me, since my use case is try to summarize different interface's bandwidth together to raise the alarm. 

So I tried to digest your above finding, but due to limited knowledge of netdata, couldn't read to know all of them, but what I'm trying to say is...

for the `api/v1/alarm_variables?chart=net.vnic1`, the variable of `net.net.received` always been in `kilobits/s`, we're clear about this point.

What I'm trying to say is, when get the variable in a cross chart approach, like what I mentioned to you earlier as below:

```
# -----------------------------------------------------------------------------
# check for speed over threshold
template: Bandwidth_Over_Subscribed
      on: net.net
families: vnic1 vnic2 vnic3
  lookup: average -1m absolute foreach received,sent
    calc: $this/1000
   units: Mbps
   every: 1m
    warn: $this > 5
    crit: $this > 7
      to: sysadmin

   alarm: Receiving_Bandwidth_Over_Subscribed
      on: net.vnic1
  lookup: average -1m absolute of received
    calc: $this/1000 + $net.vnic2.Bandwidth_Over_Subscribed_received/1000 + $net.vnic3.Bandwidth_Over_Subscribed_received/1000
   units: Mbps
   every: 1m
    warn: $this > 10
      to: sysadmin
```

you see in `alarm: Receiving_Bandwidth_Over_Subscribed`, even though this alarm is `on: net.vnic1`, but it's calc use another variable from another chart: `$net.vnic2.Bandwidth_Over_Subscribed_received/1000`

So the variable of `net.vnic2.Bandwidth_Over_Subscribed_received` in chart `net.vinc2 `is of course in `kilobits/s`, but what's different between v129 and previous is:

For versions before v129, when I reference this variable, I need to divide 1000, since the value return back to me is `kilobits/s`(even though I have the calc there), but after v129, I need to remove the /1000, because the variable `net.vnic2.Bandwidth_Over_Subscribed_received` come back to is already Mbps, which exactly the after calc value, as you can see in `template: Bandwidth_Over_Subscribed`, I have the `calc: $this/1000`

Hopefully this makes us in the same page.
:-)

**Comment by thiagoftsm** [comment]
Hi @startryst,

Today I set `vlan` in my computer and I was able to use your alarm with version 1.18 and the latest version, for both versions I verified that the code that generates the alarms and the code that delivers the information for users did not change so we are working with kilobytes in both versions, to confirm that we are in the same pages, are you getting values from chart variables like the next images:

![1_19](https://user-images.githubusercontent.com/49162938/71329314-7544a880-251b-11ea-9106-0aaa2e1fc81d.png)

![1_19_1](https://user-images.githubusercontent.com/49162938/71329315-7aa1f300-251b-11ea-8ab5-7438b28ad562.png)

when you do a request for `http://localhost:19999/api/v1/alarm_variables?chart=net.wlan0` and  `http://localhost:19999/api/v1/alarm_variables?chart=net.wlan0.100`? Of course in your case the interfaces are different.

For my specific case the dimensions on vlan are small, because I do not use them. 

For vlan and normal interface in both versions tested Netdata uses this code to make the request:

https://github.com/netdata/netdata/blob/1ea64ad126c20bdd776cdf257485e28846b7c9dd/database/rrdvar.c#L263

Best regards!

**Comment by startryst** [comment]
> Hi @startryst,
> 
> Today I set `vlan` in my computer and I was able to use your alarm with version 1.18 and the latest version, for both versions I verified that the code that generates the alarms and the code that delivers the information for users did not change so we are working with kilobytes in both versions, to confirm that we are in the same pages, are you getting values from chart variables like the next images:
> 
> ![1_19](https://user-images.githubusercontent.com/49162938/71329314-7544a880-251b-11ea-9106-0aaa2e1fc81d.png)
> 
> ![1_19_1](https://user-images.githubusercontent.com/49162938/71329315-7aa1f300-251b-11ea-8ab5-7438b28ad562.png)
> 
> when you do a request for `http://localhost:19999/api/v1/alarm_variables?chart=net.wlan0` and `http://localhost:19999/api/v1/alarm_variables?chart=net.wlan0.100`? Of course in your case the interfaces are different.
> 
> For my specific case the dimensions on vlan are small, because I do not use them.
> 
> For vlan and normal interface in both versions tested Netdata uses this code to make the request:
> 
> https://github.com/netdata/netdata/blob/1ea64ad126c20bdd776cdf257485e28846b7c9dd/database/rrdvar.c#L263
> 
> Best regards!

Yes, that's the same amount of what I observed, which is the value after `calc: $this/1000`, since the original value is kbps, but anyway, it's weird, in my previous config(before v129), I need another /1000 to make sure the value come back to me is Mbps, but now, it looks no longer required.

So, looks nothing wrong from the netdata, not sure what happening from my previous config, let forgot it, and look forward then.

Thank you @thiagoftsm

**Comment by thiagoftsm** [comment]
I am glad to read your conclusion @startryst ! Let us know case you need another help.

Best regards!
