### ISSUE TITLE
Can't get streaming node to show up in list on master web ui

### ISSUE THREAD

**Issue by arebokert** [netdata/netdata#7596]
##### Question summary
I am trying to make the slave show up in the node list in the upper left corner. I do not have a registry clause in neither slave nor master configs as I've read in https://github.com/netdata/netdata/issues/6267 it should not be needed when streaming. I have setup the HAProxy to forward TCP and HTTP. 

The master does receive the slaves stream because when I go to https://netdata-master.local/host/slave-host-name/ I can see all data. I don't get any errors in the log either. However when I check the node list it is not there, I am greeted with "Please sign in to netdata.cloud to view your nodes!". If I turn on registry on master, set an announce URL and then set the announce URL on the slave, it doesn't work either. Only the master shows up in the node list then.

I could see the issue being HAProxy if the data didn't even get transmitted (due to the data not being HTTP, although I have solved this by proxying TCP) but it does get transmitted, all the data is there if I directly browse the slave endpoint URL on the master.
 
##### OS / Environment

Debian with SID added in apt sources in order to get netdata 1.19.0-2
Currently only one slave instance of netdata and one master, will add more slaves when this is solved. Slave has web and memory turned off making it run in headless mode.
HAProxy in front of netdata on the master set up to forward both HTTP and TCP requests (to make streaming work).

##### Component Name

Streaming

**Comment by arebokert** [comment]
I have checked the code to see where the list comes from and seemingly it comes from a call to https://netdata-master.local/api/v1/charts where the returned json contains a hosts array. When I go to this address and check the hosts array it does contain both slave and master.

**Comment by thiagoftsm** [comment]
Hi @arebokert ,

In normal situation I am using stream with slave having `memory mode =  none` like you, but I always used a local registry. Today I disabled my master registry, to do this I commented everything inside my `netdata.conf`. I started the master and few seconds late I started a slave, finally I used the dasboard with my URL on master `https://localhost:19999`. Initially I did not have my slave visible, but after to press "CTRL+SHIFT+R"  the browser showed both master and slave. These results are showing that when there is a direct connection between master and slave we do not need to have `registry` enabled, as it was already discussed in other issue, probably the problem is with the proxy.

Best regards!

**Comment by arebokert** [comment]
Thanks for the suggestion @thiagoftsm but I found the issue.

I use debian. The package repository for buster has version 1.12 of netdata, but the SID (experimental) repository has 1.19. I had added SID but for some reason only the netdata package had downloaded 1.19 while all support packages like core and plugins were all running 1.12. This caused some strange issues due to the slave actually having downloaded all 1.19 packages, the issue in question being one of them.

I upgraded all netdata packages on the master to 1.19 and now it works without any issues, even with haproxy tunneling the TCP stream data.
