### ISSUE TITLE
Verify/Fix usage of CI check clang-format

### ISSUE THREAD

**Issue by prologic** [netdata/netdata#7724]
#### Bug report summary

In reviewing netdata/netdata#7640 I noticed that the `clang-format` CI lint checks that are done against the codebase against `*.[ch]` files just print line counts of differences from actual code committed vs. accept formatting standards.

Example:

```bash
$ .travis/clangformat.sh | head -n 5
./database/rrddim.c: 475
./database/rrdhost.c: 1031
./database/rrdfamily.c: 73
./database/rrdcalc.h: 153
./database/rrd.h: 895
```

This currently produces ~279 lines of output I'm not sure anyone really looks at (_because its far too much output_):

```bash
$ .travis/clangformat.sh | wc -l
297
```

This issue captures this and is a discussion for how to:

- [ ] What do we want to do here?
- [ ] Should we fail CI checks?
- [ ] Should we en-mass cleanup the codebase?
- [ ] Or should we simply remove this check?
 
##### OS / Environment (output of `uname -a; command -v sw_vers && sw_vers || grep -Hv "^#" /etc/*release`)

N/A

##### Netdata version (ouput of `netdata -V`)

N/A

##### Component Name

CI

##### Steps To Reproduce

```bash
.travis/clangformat.sh
```

##### Expected behavior

This check should either:

- Fail CI

or:

- Be removed (_if not useful_)

**Comment by Ferroin** [comment]
This ultimately needs to be up to the C devs and possibly @cosmix and/or @cakrit. I'm personally of the opinion that it would be good to enforce the coding style, but I'm also not the one who's writing the code this would impact.

**Comment by amoss** [comment]
If we remove the check then it should be replaced with some measure of how much the code-base deviates from the coding-style as defined by the clang-format linter. The long-term goal is for the entire code-base to match the agreed upon coding style in a way that is mechanically checkable. The measure used is coarse but realistic. It is not being read at the moment because enforcing the code style guide is not currently a priority - but using it will become more important in the future.

**Comment by prologic** [comment]
I raised this issue only to encourage discussion of what we'd like to do here and as a placeholder for us to fix the check. Once we've decided what we'd like to do one way or the either we can easily put up a PR that either enforces the check, improves it, etc. But as @Ferroin rightfully says, this isn'y really up to either of us on the SRE team (_we've decided in team discussions that code we write and maintain will just be auto-formatted, so we would probably learn towards deviations from the agreed upon tool used would fail CI_)

**Comment by cakrit** [comment]
CI shouldn't fail due to code formatting, until we can fix all the code. I'd comment out the check in the CI.

I started writing a suggestion to fail PRs that don't have proper formatting, but that's stupid, because we'd have a terrible time finding the code that actually does the work for the PR. So this MUST become a task for someone to take on and complete, for all the codebase. It's actually such a trivial but time-consuming task, that we could outsource it completely, unless if there's a way to safely autoformat all the code according to the standard.

**Comment by cakrit** [comment]
Assigned to @amoss for a decision.

**Comment by amoss** [comment]
We can’t reformat the source tree now - this is really low priority before the release. The current check doesn’t fail anything - it just outputs a measurement. Leave it in place until we have a better solution.

After the release I am fine with either:
* Doing a single clang-format pass over the entire tree and then enforcing the check.
* Doing what @cakrit suggested and enforce the check on all new commits so that it converges over time.

I’m closing this as it is not something we should fix now. If it causes a real problem (I.e. it fails in the CI/CD) pipeline then you are free to remove it. Otherwise let’s have this discussion in April.

**Comment by prologic** [comment]
@amos I brought this up precisely to bring up exactly the two possible solutions you summarised. I'm happy with either one of these. Lets discuss in April as you propose :)

**Comment by Ferroin** [comment]
Regardless of which approach we take, this _needs_ to only run on PR's. There is zero reason that we should be failing things like release builds because the code doesn't look good.

Also, I _think_ that with how the check works currently, the two proposed options are identical. The check currently looks at all C files, not just those that changed, so it ends up requiring the first PR after we start enforcing it to fix formatting everywhere.

**Comment by mfundul** [comment]
The current `clang-format` is not agreed upon and we should not act on it.

**Comment by amoss** [comment]
@Ferroin I agree completely - this should only be running on PRs as informational output for the developer. If it is causing anything to fail in release builds then please disable it.

**Comment by prologic** [comment]
This was added in ac90f27a580aad0c4d20c5354657b34e5ceed29e

I'm going to remove it since it doesn't achieve anything right now

We can consider alternatives when we discuss this in Athens.

I'm considering this "dead code".

https://github.com/netdata/netdata/pull/8188

**Comment by cosmix** [comment]
Let me clarify something here. The current clang-format *was agreed upon during the August Meetup*. We spent more than 2 hours going over all of the rules and agreeing on it. That we haven't started reformatting the code accordingly is just a consequence of me not insisting on it and the team not caring to do what they agreed and committed to doing (at their peril).

So, if for, whatever reason, anyone now disagrees with what we agreed back in August, let's revisit this in April. What is absolutely certain is that we need to establish a codestyle and stick to it.

cc @amoss @mfundul @cakrit @prologic @Ferroin

**Comment by mfundul** [comment]
@cosmix it's true what you said, we did agree on it in August. I said what I said based on #7271 and the words "we will need to vote again, for each parameter separately".

**Comment by prologic** [comment]
I agree with @cosmix if we agreed upon this before we should stick to it. It _should_ not be difficult to configure your own editor(s) to use the right tools to keep code style consistent across the board. This is a good way to incrementally get code into better shape/style IHMO.

Right now as it stands (_hence the PR_) the current CI check doesn't surface anything useful (_unless you go looking for it and I don't think anyone will because we're not very good at doing that_) and doesn't block PR(s) for violations.
