### ISSUE TITLE
Define prioritized roadmap for the database

### ISSUE THREAD

**Issue by mfundul** [netdata/netdata#7730]
We need to define the prioritized roadmap for the netdata agent database over the next year with relation to user visible features.

Those features will require modifications, the scope of which exceeds the limited dbengine code-path and requires multiple grooming sessions to estimate the effort of implementation, identify compatibility issues and measure the distance towards the end goal.

The end goal for the next major release of the netdata  database (that effectively moves the agent to version 2.0 and breaks compatibility) is:
- There will be a flat hierarchy of metrics, which will be identified by a set of labels for any given time series. RRDHOST, RRDSET and RRDDIMM will be effectively obsoleted.
- Metrics will be indexable by labels and annotations over time ranges.
- Data types other than metrics (but always over time) will be supported such as:
  - Meaningful charts.
  - Logs.
  - Traces.
  - Static system information.
- Database metadata won't have to all reside in memory. A small subset of them should suffice. Moreover, metric data compression and deduplication techniques will reduce the data memory footprint.
- The oldest metrics will be downsampled to increase the maximum retention period.
- There will be native support for automatic and reliable replication over the network.

The user facing features that we wish to provide are:
- The ability to to query and present data from ephemeral hosts that are not being collected any more.
- The ability to query and present data from charts that are not being collected any more.
- The ability to query and present data from dimensions that are not being collected any more.
- The ability to query and present static system information.
- The ability to define labels at the host, chart and metric levels.
- The ability to define annotations at the host, chart and metric levels.
- Support custom charts.
- Reduce memory overhead.
- Increase data retention.
- Provide high availability.
- Provide observability, by supporting logs and traces.

We must define the smallest possible tasks that aim to provide the features. At the same time we should not break compatibility until the the latest possible point. All that should happen in the direction of the end goal.

## Expected Outcome

* Two calls with Dimosthenis and Costa - one mid-sprint and one end-sprint.
* Roadmap for the year.

**Comment by ilyam8** [comment]
> The oldest metrics will be downsampled to increase the maximum retention period.

Probably such simple logic wont be enough and we need some more complex retention policy. Probably we need cleanup (deletion) in addition to downsampling.

Imaging bery dynamic enviroment - kubernetes. Pods are created and deleted all the time. I am not sure suggested retention policy is ok for that case. Just thinking out loud.

**Comment by amoss** [comment]
Some of these points relate to unbundling metrics from charts. It is not clear yet what the (user-facing) advantages of this would be, and whether this should be done. If it should be done then we also need to consider how the current association of metrics/charts would be replaced so that we can still use charts as a unit of organization in all of the places that we currently do. How to achieve this without a major rewrite is a difficult question.

Further issues to discuss:
* We've talked about how the storage of new data-types will require variable-sized storage (pages, extents) but we also need to consider sparse storage as we have no guarantees that logs or traces will be produced at a constant rate.
* As well as sparse storage of time-series, how do we handle slew in the rate of a series?
* How we will handle the storage of metrics from multiple hosts in the same db, and how they will be identified / retrieved (this relates to the discussion on RRDHOST, RRDSET and RRDDIM).
* What metadata will identify the current contents of the storage, and how does it relate to the current collector protocol?

**Comment by ilyam8** [comment]
One more thing - we dont store raw values, only calculated. So all stored values are absolute (gauge) values.

This is a problem, imagine i want to chart `num of queries` for the last 5 minutes, last 3 hours, last day, last month. If we had raw values i would need only two points: first one and last one and `num of queries` would be just last one sub first one - pretty light request. Current implementation doesnt allow that and i need to get all points for the last N days and sum them which probably will result in https://github.com/netdata/netdata/issues/6733.

**Comment by mfundul** [comment]
Closed by https://github.com/netdata/docs/pull/93
