### ISSUE TITLE
Improve the system-info meta-data output.

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#7731]
##### Feature idea summary
Update the output of the `system-info.sh` script so that it includes all of the following information. 

##### Expected behavior
Each of the following data is visible in the info response and message.

Already existing, but being changed in #7488.
* Operating system
* OS version, architecture (x86, etc.)
* Kernel name, version
* Container and Virtualization technology

New, to be added as described in the discussion below:
* Number of cores
* Nominal frequency (not the current frequency)
* Amount of RAM
* Sum of available capacity on disks

The main requirement on the new information is that we use a staggered approach to allow graceful degradation of the information returned rather than failure. This should be robust across the range of architectures and systems (bare-metal, VMs and containers) discussed below. An exact definition of the variables exported by the script will appear when #7488 is complete.

**Comment by Ferroin** [comment]
We've got OS, arch, OS version, kernel name, and kernel version detection about as good as we can make it in the existing `system-info.sh` script.

For the others:

### Number of CPU cores

Trivial solution is to use `nproc --all`, provided in GNU coreutils. Assuming that fails but `/sys` exists and we can list directories in it (the normal case unless some LSM is in use), the following will do the same:

`find /sys/devices/system/cpu -mindepth 1 -maxdepth 1 -type d -name 'cpu*' | grep -Ev 'idle|freq' | wc -l`

Otherwise, we have to count entries in `/proc/cpuinfo` like so:

`grep -c ^processor /proc/cpuinfo`

### 'Nominal' Frequency

Assuming this is the 'design' frequency of the CPU, we actually need `/sys` to obtain this info, as well as cpufreq support in the kernel. The 'design' frequency for a given logical CPU core can be found in `/sys/devices/system/cpu/cpu<N>/cpufreq/base_frequency`, where `<N>` is the core number. The max frequency (which may be higher than the design frequency) can be found in `/sys/devices/system/cpu/cpu<N>/cpufreq/scaling_max_frequency`. Both report values in hertz without any scaling.

Note that we cannot rely on DMI info for this for a few specific reasons:

* `dmidecode` will actually crash or hang some virtual machines. It needs to be specially handled by the VM's firmware itself for it to work.
* DMI data is only available reliably on x86 systems.
* The data exposed by DMI might not be accurate. For example, on my laptop it reports 8.3 GHz as the max CPU frequency, which is blatantly wrong (2.8GHz design, 3.8GHz boost).

Similarly, we cannot rely on `/proc/cpuinfo`, as the listed frequency information there is the current operating frequency of the CPU, and we can't rely on the CPU model name to include frequency info like most Intel and AMD chips do.

### Amount of RAM

This is kind of tricky, as it is not actually very easy to get the total installed physical memory on Linux.

Provided we don't care about accuracy, I'd recommend instead reporting the total memory available to the system, which is usually accurate enough for most people. This corresponds to the first line in `/proc/meminfo`, which is also what's reported by the `free` command. For systems with multiple GB of RAM, it's usually off from the 'real' value (that is, what systems are advertised as having) by less than 1%.

### Sum of available capacity of disks

I assume this refers to theoretical capacity, not free disk space.

Total size of all mounted filesystems is easy:

`df -x tmpfs -x devtmpfs -l --total -BM --output=size | tail -n 1`

But total size of all disks is not quite as easy. Our best bet is probably going to be to use `/sys/block/<disk>/disksize` and filter what we factor in based on the state of the `removable` attribute and what type of device it appears to be.

----

As a side note, we can improve the virtualization and container technology detection by just doing the same things that `systemd-etect-virt` is doing ourselves. That is probably not doable entirely from a shell script though.

**Comment by cosmix** [comment]
### CPUs (additional)

Number of physical CPUs: `/proc/cpuinfo` -> grep "physical id" | sort | uniq | wc -l
Number of cores: `/proc/cpuinfo` -> grep 'cores`
Number of 'logical' CPUs: `/proc/cpuinfo` -> grep "processor" (if logical > cores, then HT enabled)

**Comment by stelfrag** [comment]
I added ```-x squashfs``` to the df command to skip the /dev/loopxx

**Comment by mfundul** [comment]
I'd like to add that it's better to talk about CPU threads instead of cores for most of those metrics, since it's not really cores when SMT is enabled. `lscpu` gives very nice information, such as `CPU MHz` for the base frequency.

**Comment by thiagoftsm** [comment]
The script also needs to be updated to get information from `FreeBSD`.

**Comment by cosmix** [comment]
@mfundul there's no guarantee that `lscpu` will be installed on the box. The same information is provided in `/sys` and `/proc`. Logical cpu is a valid term for SMT.

For FreeBSD `sysctl` can provide a slew of info. `kern.smp.active` and `kern.smp.disabled` for HT determination, `dev.cpu.*.%location`, `hw.ncpu` (divided by 2 if HT is on) for the core count. There's also `kern.smp.topology` and `kern.sched.topology_spec` with additional information. Alternatively there's always `/var/run/dmesg.boot` that can be parsed with almost everything there, including physical CPUs (packages) (on SMP systems, look for the `FreeBSD/SMP` key)

**Comment by mfundul** [comment]
`/sys/devices/system/cpu/cpu<N>/cpufreq` does not exist in VMs apparently. Moreover, `/sys/devices/system/cpu/cpu<N>/cpufreq/base_frequency` does not exist in our Threadripper machine.

**Comment by mfundul** [comment]
```
In addition, you must boot with the intel_pstate driver active. Note: Do not use the intel_pstate=disable or intel_pstate=no_hwp settings. This is necessary to allow base_frequency to appear in the cpufreq directory in sysfs
```
Probably an intel thing.

**Comment by Ferroin** [comment]
> `/sys/devices/system/cpu/cpu<N>/cpufreq` does not exist in VMs apparently. Moreover, `/sys/devices/system/cpu/cpu<N>/cpufreq/base_frequency` does not exist in our Threadripper machine.

Yeah, it shouldn't exist in VM's, we quite simply can't get that kind of info from inside a VM, because even the guest OS can't get it.

As far as the Threadripper case, we can get reasonablly good results if we use `cpuinfo_max_freq` when `base_frequency` doesn't exist. We need to use `base_frequency` if it's there though because stuff that can boost beyond design speed under certain circumstances shows the max boost frequency in `cpuinfo_max_freq` instead of the design frequency. I think you're correct that it's only an Intel thing, but I'm not 100% certain that nothing else is providing it.

> divided by 2 if HT is on

We can't rely on that. It's really rare, but there is x86 hardware with 4-way HT, and some arches also have higher-order SMT as an option (most recent UltraSPARC chips have 4-way SMT for example).

Additionally, all bets are off once virtualization is involved, as many of the better hypervisors will let you set package, core, and thread-per-core counts with no restrictions at all related to actual hardware other than addressing.

**Comment by mfundul** [comment]
Power architectures can have 8-way SMT but I'm not sure netdata compiles in this platform.

**Comment by Ferroin** [comment]
Also, if `lscpu` exists on the system, we should probably use that in preference to scraping the info ourselves. Note, however, that when dealing with Intel chips, it lists the boost frequency as the max, not the peak design frequency, which might cause some confusion as that can be well over 1GHz beyond the advertised speed for the CPU.

`hwinfo` is another good one we should probably look at. The more we can offload to tools the user might already have installed that do what we want, the more reliable we're going to be, because these tools already handle quite a few of the edge cases.

Also, if we're going this far, we might consider lookinng at NUMA info as well, though I have no idea how to get that data.

**Comment by Ferroin** [comment]
> IBM POWER architectures can have 8-way SMT but I'm not sure netdata compiles in this platform.

Actually, it works just fine from what I can tell. I don't have actual hardware, but I have build tested it myself in a QEMU VM with a POWER7 CPU. I didn't try to run it though, but the build works just fine (same for SPARC and MIPS). I'd actually be surprised if we didn't work on other architectures, as we're not doing any crazy stuff like inline assembly.

Nice point though, I forgot that you could get 8-way SMT on POWER chips.

**Comment by cosmix** [comment]
SMT with more than 2 threads/core is indeed a possibility, albeit very rare on the x86/x64 world (only Xeon Phi if I'm not mistaken). Some of the methods I described above for FreeBSD would conceivably work with any SMT implementation, be it 2, 4 or 8-way.

I agree that we can and should _try_ using `lscpu` if available, but there are caveats: e.g. `CPU Mhz` is not the base frequency. It's the current frequency.

I generally like `lscpu` as it'll actually give you much more than what you'll readily get from `proc` and `sys` (including ARM name decoding), and SMT info, but there's things it doesn't do well and it may not be in some situations and we need to support those cases too. 

`hwinfo` won't give us much more than what we discussed above. It's actually wholly obsolete afaic.

**Comment by mfundul** [comment]
True, `CPU Mhz` is current frequency. I'm not sure there is a reliable way to get base frequency unfortunately. Maybe `CPU min MHz` works for some cases.

**Comment by Ferroin** [comment]
`CPU min MHz` is the lowest frequency the CPU itself supports operating at, which is usually far below the base frequency. The i7 in my laptop, for example, has a base of 2.8 GHz, a max of 3.8 GHz, and a min of 800 MHz.

**Comment by mfundul** [comment]
> 
> 
> `CPU min MHz` is the lowest frequency the CPU itself supports operating at, which is usually far below the base frequency. The i7 in my laptop, for example, has a base of 2.8 GHz, a max of 3.8 GHz, and a min of 800 MHz.

In the Threadripper CPU it gives 2200MHz which is the base frequency and not the lowest frequency for Zen+ arch which is either 800MHz or 1.6GHz if I recall.

**Comment by Ferroin** [comment]
> > `CPU min MHz` is the lowest frequency the CPU itself supports operating at, which is usually far below the base frequency. The i7 in my laptop, for example, has a base of 2.8 GHz, a max of 3.8 GHz, and a min of 800 MHz.
> 
> In the Threadripper CPU it gives 2200MHz which is the base frequency and not the lowest frequency for Zen+ arch which is either 800MHz or 1.6GHz if I recall.

Strange, for Intel CPU's it's like I mentioned above, and it's the same on the couple of ARM systems I have too.  None of the ones I have to test on right now use the ACPI frequency governor though like all the modern AMD systems do, so maybe that's why?

**Comment by mfundul** [comment]
Ok, 2200MHz is not the base frequency. It's not an EPYC, it's a Threadripper which is higher clocked to 3.5GHz. This makes more sense. Still, `dmidecode` gives a `Current Speed` which is probably the best approximation to base frequency but not 100% unfortunately.

**Comment by mfundul** [comment]
Another thing to consider is that while a certain product may have a certain default base frequency this can be overridden in the BIOS/EFI (usually through a different multiplier) which makes the factory base frequency kind of useless information. We could consider dropping this metric.

**Comment by Ferroin** [comment]
> Another thing to consider is that while a certain product may have a certain default base frequency this can be overridden in the BIOS/EFI (usually through a different multiplier) which makes the factory base frequency kind of useless information. We could consider dropping this metric.

In those cases, most of the userspace stuff that reports the 'base' frequency on Linux except the model name in `/proc/cpuinfo` reports the adjusted frequency. I do agree that this is not very useful if we have a CPU model number though.

**Comment by mfundul** [comment]
> 
> 
> > Another thing to consider is that while a certain product may have a certain default base frequency this can be overridden in the BIOS/EFI (usually through a different multiplier) which makes the factory base frequency kind of useless information. We could consider dropping this metric.
> 
> In those cases, most of the userspace stuff that reports the 'base' frequency on Linux except the model name in `/proc/cpuinfo` reports the adjusted frequency. I do agree that this is not very useful if we have a CPU model number though.

Moreover, the model name reports base frequency for intel but not for AMD.

**Comment by amoss** [comment]
After a discussion we've decide to split this issue into two pieces. It seems that the improvement to the `system-info.sh` should be handled by @Ferroin based on experience and access to appropriate test environments. 

The second part will be to integrate the new data into the system and output it over the API, this will be done in #7751 so that it is visible in the web API, and then when the ALCK code is merged at the end of the sprint it calls the updated handler.

Some details are still undefined (the exact variables and the definition of what we will put in the API) - this will be updated in the next couple of days.

**Comment by Ferroin** [comment]
@amoss Ping me once you've got the details nailed down, as how the data is supposed to be presented in the API call may have an impact on how the script collects it.

**Comment by rduffield** [comment]
We were a bit ambiguous. _Sum of available capacity on disks_ should be _Sum of total capacity on disks_. There's some debate about whether this should be limited to only the mounted disks, which I think makes sense, but open to feedback.

**Comment by amoss** [comment]
I found some problems with the virtualization detection when I was testing the script (for the proceeding task). I've fixed the case that I saw, but we still have a lot of holes. Is it worth adding the rest of these heuristics https://unix.stackexchange.com/questions/89714/easy-way-to-determine-virtualization-technology as part of this task?

**Comment by Ferroin** [comment]
I would like to point out again that `dmidecode` is risky. It has the potential under some circumstances (such as in paravirtualized Xen domains) to quite literally cause the system to hang, and it's absolutely possible to spoof the data returned by it if the system is virtualized.

**Comment by amoss** [comment]
If we know specific cases where `dmidecode` can cause problems, is it possible to use heuristics to identify those cases first and avoid calling `dmidecode` in those configurations?

**Comment by Ferroin** [comment]
Potentially. The only case I know of for certain is Xen PV domains, and we can easily ID those without needing `dmidecode`. There may be others though, so I'm of the opinion that `dmidecode` should just be a last resort anyway.

**Comment by Ferroin** [comment]
Do we have anything conclusive yet about how picky we want to be about disks?

A naive implementation would involve checking the contents of `/sys/block/*`, filtering by name and presence of the `removable` attribute, and then summing the total sizes reported there, which should cover what we need, but won't be very  I'm going to look into trying to use `lsblk` as well if it can be found, but that still only covers Linux. I'm not quite sure how to go about this on FreeBSD.

**Comment by stelfrag** [comment]
> Do we have anything conclusive yet about how picky we want to be about disks?
> 
> A naive implementation would involve checking the contents of `/sys/block/*`, filtering by name and presence of the `removable` attribute, and then summing the total sizes reported there, which should cover what we need, but won't be very I'm going to look into trying to use `lsblk` as well if it can be found, but that still only covers Linux. I'm not quite sure how to go about this on FreeBSD.

Suggestion: 
A lot of work has already be done and can be merged. 

Can the disk part should be another issue that will allow us to think about it more? Thoughts?

**Comment by Ferroin** [comment]
> > Do we have anything conclusive yet about how picky we want to be about disks?
> > A naive implementation would involve checking the contents of `/sys/block/*`, filtering by name and presence of the `removable` attribute, and then summing the total sizes reported there, which should cover what we need, but won't be very I'm going to look into trying to use `lsblk` as well if it can be found, but that still only covers Linux. I'm not quite sure how to go about this on FreeBSD.
> 
> Suggestion:
> A lot of work has already be done and can be merged.
> 
> Can the disk part be another issue that will allow us to think about it more? Thoughts?

I was planning on handling the disk part as a separate PR, but intended to have that one close this issue instead of needing a separate issue. However, if having a separate issue for it is preferred, that's fine by me.

**Comment by stelfrag** [comment]
> > Suggestion:
> > A lot of work has already be done and can be merged.
> > Can the disk part be another issue that will allow us to think about it more? Thoughts?
> 
> I was planning on handling the disk part as a separate PR, but intended to have that one close this issue instead of needing a separate issue. However, if having a separate issue for it is preferred, that's fine by me.

Oh yes separate PR is just as good IMO

**Comment by amoss** [comment]
I had forgotten about the disk capacity. On linux would it not be something like:
```
df | grep '^/dev' | awk '{ sum += $2} END {print sum}'
```

**Comment by stelfrag** [comment]
> I had forgotten about the disk capacity. On linux would it not be something like:
> 
> ```
> df | grep '^/dev' | awk '{ sum += $2} END {print sum}'
> ```

The command Austin initially wrote is very close I think  (I added squashfs to skip the /dev/loop devices)

`df -x tmpfs -x devtmpfs -x squashfs -l --total -BM --output=size | tail -n 1`

**Comment by Ferroin** [comment]
The problem with that is you're dependent on what's actually being used off of disks, and you have to contend with stuff like LVM being involved, and the possibility of filesystems (like BTRFS) having definitions of otal capacity that don't match up with what users expect, so it's potentially horribly inaccurate (like, possibly multiple TB high or hundreds of GB low even with common storage configurations).

I think it's going to be better on Linux if we use `lsblk` if it is available (looks like this to get an exact byte total for physical disks: `echo $(($(lsblk -S -o SIZE -n -b | paste -s -d +)))`) and then fall back to scanning `/sys/block` if that doesn't work (or possibly the other way around.

Based on some digging, FreeBSD should be doable using the `geom` command, but I'm going to have to experiment with it a bit to figure out what exactly is needed.
