### ISSUE TITLE
Use system service manager to try and shut down Netdata during installs, updates, and uninstalls.

### ISSUE THREAD

**Issue by mfundul** [netdata/netdata#7798]
Confirmed, that when I manually run `netdata-updater.sh`, netdata is stopped with 6/ABRT.

I assume this is due to the following code triggering the signal which is treated as failure by systemd:

https://github.com/netdata/netdata/blob/c7e13846a87054d1e6e412d8edbc25b9dcbc684f/packaging/installer/functions.sh#L494-L506

Would it be possible to maybe check if the system is managed with systemd, and if so shut down the service with systemd?

Or just in some way that is not treated as failure by systemd?

_Originally posted by @johnramsden in https://github.com/netdata/netdata/issues/6999#issuecomment-576144967_

**Comment by Ferroin** [comment]
There are two issues here:

1. We should be trying to use whatever service management mechanism we detected during install to stop the agent before we try anything else to stop it.
2. _Something_ is triggering a SIGABRT here, which should not at all be the case since we never seem to be doing anything that explicitly triggers it. I suspect an assertion is failing somewhere in one of our dependencies and calling `abort()` explicitly. This is why systemd sees this is a failure state (because an abort _is_ an abnormal termination (see [man 3 abort](http://man7.org/linux/man-pages/man3/abort.3.html)).

Both of these need fixed, but they really are orthogonal to each other. I can take care of the first (shouldn't take me too long, but won't be until tomorrow since it's a holiday today in the US), but I don't have the expertise to track down what's causing the second.

**Comment by mfundul** [comment]
@johnramsden since this is reproducible for you can you give us the text output of running this script? There may be some very useful print in there that will help solve this.
