### ISSUE TITLE
Multi-arch builds (ARM, ARM64, X86)

### ISSUE THREAD

**Issue by prologic** [netdata/netdata#7824]

**Comment by gecube** [comment]
Hi!

What about pre-packaged DEBs for Ubuntu (aarch64) ?

**Comment by Ferroin** [comment]
Long-term we have plans to support (at minimum) x86_64, AArch64, and AArch32 (probably both ARMv8.1 and ARMv7a), but this is currently stalled pending a rework of our packaging infrastructure (which is unfortunately taking far longer than anticipated).

**Comment by carlhoerberg** [comment]
docker got experimental support for qemu-user-static, which I found made it easy to build for foreign architectures: 

```sh
echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
sudo systemctl restart docker
sudo apt-get install -y --no-install-recommends qemu-user-static
docker run --platform arm64 -it ubuntu:20.04 bash
```

or with docker buildx: https://docs.docker.com/buildx/working-with-buildx/

**Comment by Ferroin** [comment]
We’re actually using the same functionality right now for our ARM Docker image builds. It works rather well, but is unfortunately exceedingly slow. Our long-term plan is to set up dedicated build hosts for alternate architectures.

**Comment by rhenwood-arm** [comment]
@Ferroin : Travis-CI have a free tier with native AArch64 support https://blog.travis-ci.com/arm-architecture-adoption-grows-on-travis-ci

Is that helpful?

**Comment by OdysLam** [comment]
Thanks @rhenwood-arm for chiming in and welcome to our community :) 

Although I am not an expert, thanks for pointing this out. Curious 😬 on what our chief packager @Ferroin has to say !

**Comment by kiwik** [comment]
Would like to see aarch64 package landing. :)

**Comment by OdysLam** [comment]
Welcome @kiwik to our community! Thanks for chiming in. Every voice is being heard and we value your feedback. 

Cheers ;)

**Comment by pbk8s** [comment]
Hey everyone - Just want to check if there are any updates on support for Arm platforms?

**Comment by Ferroin** [comment]
As of right now,:

* Our Docker images support 64 and 32 bit x86 and ARM. There are no short term plans to extend this.
* Our static builds currently only support 64-bit x86, but this is likely to change as part of an upcoming overhaul of our installation scripts and methodology. Short term plans are to add 32 and 64 bit ARM support.
* I’m still in the process of adding 32 and 64 bit ARM support for our binary packages, though this has been delayed due to infrastructure problems (the exact same code being used to attempt the builds works any number of places, just not on GitHub Actions runners...). This unfortunately can't be comprehensive, as some of our build-time dependencies are limited to certain architectures n certain distributions (most notably, we can’t really do ARM support for CentOS as things stand right now), and some distros do not provide Docker images for all architectures they support. Current work on this can be found here: https://github.com/netdata/netdata/pull/10769
* Long-term, I hope to extend all of these to cover some other reasonably common architectures (most notably POWER 9+, but ideally also System/z, RISC-V, and MIPS), though this may be hard to convince management about (they want proof we work correctly on each despite us not doing anything that’s dependent on the CPU architecture in any way, and don’t view it was worth spending the time testing).

**Comment by odidev** [comment]
@Ferroin,  As builds are passing for Arm64 platform in  [#10769](https://github.com/netdata/netdata/pull/10769), may i know till when are you planning to add static build support for Arm64 platform in master branch?
Let me know if any help required regarding the same.

**Comment by Ferroin** [comment]
> @Ferroin, As builds are passing for Arm64 platform in [#10769](https://github.com/netdata/netdata/pull/10769), may i know till when are you planning to add static build support for Arm64 platform in master branch?
> Let me know if any help required regarding the same.

As of right now, there’s no concrete ETA, but support for it is planned as part of an ongoing overhaul of our installer and updater code. I’m hoping to have most (if not al) of that work done by the end of the year, but as of right now it’s still in the early stages, so I’m not certain when exactly it will be done.

**Comment by odidev** [comment]
@Ferroin, Thanks for the explanation.
Actually i tried building "netdata.gz.run" for Arm64 platform using the script similar to (In fact same) _"packaging/makeself/build-x86_64-static.sh"_  and it got build successfully and i've also successfully installed netdata using the built binary in Arm64 platform.
just wanted to know what else we need to add the static build support for arm64?

**Comment by Ferroin** [comment]
> @Ferroin, Thanks for the explanation.
> Actually i tried building "netdata.gz.run" for Arm64 platform using the script similar to (In fact same) _"packaging/makeself/build-x86_64-static.sh"_ and it got build successfully and i've also successfully installed netdata using the built binary in Arm64 platform.
> just wanted to know what else we need to add the static build support for arm64?

As of right now, three things would be needed:

* The filename needs to change to embed the architecture (like a lot of package managers do with their package files). This would not be especially difficult, but may break some existing installs.
* Proper CI support for building it. This is reasonably simple to do (maybe a dozen lines of code).
* The kickstart-static64.sh script would have to be updated to support detecting the system architecture and using the correct build for the system, as well as reporting an error if no build was found for the CPU. This is non-trivial, but we’re overhauling the installation process anyway and I plan to have this type of support integrated directly as part of that.

**Comment by Ferroin** [comment]
https://github.com/netdata/netdata/pull/11463 is probably of interest to anyone who is following this issue as it lays the ground work for multi-arch support in CI for our static builds (specifically, it covers the first two things mentioned in my above comment).
