### ISSUE TITLE
Install the improved SystemD Unit file on systems with SystemD v235+

### ISSUE THREAD

**Issue by prologic** [netdata/netdata#7844]
##### Feature idea summary

This to remind us that we _should_ take advantage of the work done in #7790 (_thank you @amishmm_) and actually install/ship the improved SystemD Unit file on systems that have SystemD v235+

We need to support both at this stage as we have significant systems on older SystemD.

##### Expected behaviour

Install the _appropriate_ SystemD Unit file depending on what version of SystemD we detected. This should update `kickstart.sh`, `kickstart-static64.sh` and `netdata-installer.sh`.

**Comment by bjoe2k4** [comment]
@ilyam8 Why was this closed? AFAIK the kickstart installer still uses the old systemd files if installed on a fresh Archlinux. Also I noticed that the old systemd files has much more security related settings than the new one.

**Comment by ilyam8** [comment]
@bjoe2k4 thanks for bumping this issue. I guess I was wrong because I confirm that "Expected behavior" is not implemented.

@netdata/agent-sre, take a look if we still need this. 

> Also I noticed that the old systemd files has much more security related settings than the new one.

Correct. For instance, [netdata.service.v235.in](https://github.com/netdata/netdata/blob/master/system/netdata.service.v235.in) (deb/rpm packages) has no [CapabilityBoundingSet](https://github.com/netdata/netdata/blob/cc3d232b796ca45a7d7349c2f4a1e801769063a2/system/netdata.service.in#L46-L64) and [sandboxing](https://github.com/netdata/netdata/blob/cc3d232b796ca45a7d7349c2f4a1e801769063a2/system/netdata.service.in#L66-L73) options.

**Comment by amishmm** [comment]
This happens because whenever something is added to netdata.service.in, similar changes needs to be done in netdata.service.v235.in

I had commented the same here: https://github.com/netdata/netdata/pull/8454#issue-585648223
