### ISSUE TITLE
Replace dots in hostname when sending to backend

### ISSUE THREAD

**Issue by waldner** [netdata/netdata#7856]
---- Feature idea summary

If I have `hostname = server.example.com` and send metrics to a graphite backend, the `prefix.hostname.chart.dimension` schema that netdata uses results in creation of (for example) `netdata.server.example.com.cpu....` which is probably not desired. Other tools (eg collectd) offer the option to replace dots with other characters when sending to a TSDB.
See for example https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_write_graphite, option `EscapeCharacter` and `PreserveSeparator`

---- Expected behavior

It would be nice if netdata supported a similar configuration option.

**Comment by vlvkobal** [comment]
Dots are [expected](https://graphite.readthedocs.io/en/latest/feeding-carbon.html#step-1-plan-a-naming-hierarchy) in the metic path. In addition, I can't find any mentions about the dot as an escape character in the Graphite documentation. So, I think the request is not valid. @waldner, do you have any problems with the current backend subsystem behavior?

**Comment by waldner** [comment]
I never mentioned dot as an escape character whatsoever. I'm only saying that graphite allows _replacing_ dots with other characters, to avoid creating useless (and confusing) extra levels of label hierarchy in graphite. Netdata does not currently offer an equivalent option.
If my hostname is server.example.com, I want that to be a single element in graphite's labels, but if dots are not replaced, that ends up creating three levels of hierarchy in the label tree.
My problem is that, as said, if I set hostname = server.example.com in netdata then in graphite I have labels of the form netdata.server.example.com.cpu.... which create three extra useless levels of hierarchy and complicate queries and graph creation.

**Comment by vlvkobal** [comment]
Yes, the page you mentioned states that the dot is an escape character, but it's not the official documentation for the Graphite.

Anyway, after you elaborated on your point it became more clear to me what is the essence of your request. Thank you.

You can use `hostname = server_example_com` to avoid extra levels. Is it worth to make it more complicated?

@Ferroin what do you think on the matter? Should we implement the feature?

**Comment by tlo8640** [comment]
Hello,
I support this request.
I came across the same problem.
I was thinking about using netdata as addition to icinga2.
We are using here icinga2 for monitoring and we forward performance data to graphite.
the hostnames will be converted from host.example.com to host_example_com.
The escaping schema is documented here: https://icinga.com/docs/icinga2/latest/doc/14-features/#graphite-schema
in Graphite , dots "." are path divider, so host.example.com will lead into (in my mond useless) additional paths ~/host/example/com/ instead of ~/host_example_com/ with escaped path.
It would be much easier to handle the performance data of icinga2 and netdata if the host name is coded in the same way.
netdata gives by default a lot of useful metrics wich could be an excellent addition to our icinga2 monitorng system.
Thank you very much

**Comment by ilyam8** [comment]
I think we can say that this issue is fixed in #10361 - using the `hostname` configuration in the exporting engine for replacing dots.
