### ISSUE TITLE
[discussion] external data collection 2.0

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#7897]
### Feature idea summary

This is about data collection written in go (our plan is to move almost all application monitoring in go).

Netdata **plugin output is charts** (see [docs](https://docs.netdata.cloud/collectors/plugins.d/#external-plugins-api)).
Plugin:
- creates charts
- updates charts

Chart creating:

```bash
CHART 'example.random' '' 'A Random Number' 'random' 'random' '' '' '70000' '1' '' 'go.d' 'example'
DIMENSION 'random0' 'random 0' '' '' '' ''
DIMENSION 'random1' 'random 1' '' '' '' ''
```

Chart updating:

```
BEGIN example.random
SET random0 = 10
SET random1 = 51
END
```

As a result collection and charts managing are highly coupled. It has both pros and cons.

Main problems:
- Netdata collectors are not really collectors. They are coupled with Netdata and it is impossible to use them outside Netdata.
As a result - we do not receive a lot of contributions. Only Netdata users are interested in them.
It makes keeping them up to date very difficult and sometimes impossible. Which is a big problem because **our user rely on netdata**.

- current design is not compatible with k8s.

### Suggestion

1. It is impossible to argue with the fact that prometheus exporters are widely used and it is de-facto standard way to collect metrics in k8s enviroment (exporter as a sidecar in a pod).
2. We need to keep current `install, (almost) zero config and it works` logic. **This is golden**.
3. Decouple our collectors from charts and share it with monitoring community. 

To achieve this:

- Decouple collection logic. Convert our collector to prometheus-exporters. 
If we do this people are able to use them outside netdata (more contributions). We are able use community prometheus-exporters . Win-win.

- Move charts handling logic to a separate file. In there we describe what metric to use in what charts, etc.

- Refactor our collectors. In fact we have one generic collector - it uses collect logic (imported from prometheus-exporter library) and charts managing logic (build from file). 

- **Collector output - prometheus metrics**. We can use limited PromQL to gather metrics and grafana like languge to build charts.

So our collector consist of two pieces:

- collection. Output - prometheus metrics.

- charts handling. Since we have mini db with probmetheus metrics after collection we can do it using some query language (as grafana does.)

Key ideas:
- netdata collectors (collection metrics part) => prometheus exporters
- charts => separate file.

**Comment by cakrit** [comment]
As I understand the OP, this is basically describing the solution we agreed on (at a high level), in different words:

<img width="1266" alt="prom" src="https://user-images.githubusercontent.com/43294513/73382552-9320ce00-427c-11ea-9a1c-dbab450a0ca9.png">

The "Charts handling" mentioned in the OP is called "Prom metrics to charts module". As mentioned in the internal discussion, the "chart config" itself could actually use `PromQL` and a grafana-like language, if it makes sense. The only different proposal I see is the idea of us creating our own, stand-alone, prometheus exporters, if and when we need them. That's always an option, but it doesn't mean that we must replace every collector we already have. We can do that as needed.

One way to extend our HLD would be to support the Prometheus write API ourselves. Then our generic collector wouldn't need to poll, it could also just listen. That's probably closer to what you meant here and it would look like a new netdata API, just for collectors. It's something we could definitely consider.

**Comment by ilyam8** [comment]
> Netdata collectors are not really collectors. They are coupled with Netdata and it is impossible to use them outside Netdata.
As a result - we do not receive a lot of contributions. Only Netdata users are interested in them.
It makes keeping them up to date very difficult and sometimes impossible. Which is a big problem because our user rely on netdata.

This is the main problem i would like to solve. It is a completely different way we are writing collectors actually.

My point is to **make collectors usable outside of netdata** so other people/organizations can use them/build their monitoring on top of it. This is a very good thing - take a look at [telegraf](https://github.com/influxdata/telegraf/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc). It is not coupled with anything and receives huge amount of contributions. We will use them too.

Most profitable for community way is to make them prometheus exporters. So if we need to write a collector we write an exporter and use it directly (import as a library) or indirectly - scraping it. In both cases we have prometheus metrics.

**Comment by prologic** [comment]
> current design is not compatible with k8s.

Do we mean Prometheus `/metrics` endpoints here?

**Comment by cakrit** [comment]
This is exactly what is meant here. It's a possibility that's worth discussing further, but our first priority is to build the system that can actually ingest `/metrics` endpoints and we have some work to do there.

**Comment by prologic** [comment]
Given the discussion we had internally (_the long one 🤣_) I _think_ / _believe_ we're good here!

**Comment by prologic** [comment]
> Given the discussion we had internally (_the long one 🤣_) I _think_ / _believe_ we're good here!

Sorry by "here" -- I meant having a collector that consumes Prometheus `/metrics` endpoints.

This issue is still relevant in general in terms of decoupling our collector logic from charts and generally improving our collectors overall and making them useful to contributors beyond the context of NetData itself.

**Comment by ilyam8** [comment]
> ingest /metrics endpoints

> having a collector that consumes Prometheus /metrics endpoints

It means **ingest prometheus metrics**.

No matter how we get them:
- scraping endpoint
- importing collector as a lib and invoking its `Collect`

What we have now - bunch of collectors in the `go.d.plugin` repo.

> https://github.com/netdata/go.d.plugin/tree/master/modules

They are coupled with charts - impossible to use outisde of netdata context.

My main point: **lets make them usable by monitoring community**. We will use consume their output.

- convert to exporters, move them to their own repos
- we build our plugin importing them or scraping them (two options that are available at the same time)

If their is good exporter with community support we use it instead of ours. (good example - https://github.com/percona/mongodb_exporter)
___


> having a collector that consumes Prometheus metrics

^^ that is our collector

**Comment by ilyam8** [comment]
so yes

> having a collector that consumes Prometheus metrics

but lets make our collectors prometheus metrics producers

> convert to exporters, move them to their own repos

it doesnt add much cost for development

**Comment by cakrit** [comment]
> it doesnt add much cost for development

??? For every collector, we need to convert it (if a prometheus exporter doesn't already exist), write the chart generation config, test, update CI/CD, look at migration, documentation and I'm not sure what else. You can do a pilot with a new collector and then migrate one, to see how much work it is.

**Comment by cakrit** [comment]
I had a discussion with Costa on this and he has proposed basing the generic prometheus collector on the statsd plugin, perhaps even by extending the existing code. I will discuss first with @cosmix. And then get back to this.

**Comment by cakrit** [comment]
Getting back to this. The main idea we discussed with @ktsaou was to base the new, generic prometheus collector, on the `statsd` implementation. Reasoning:

- Since we've agreed to strategically move many of our collectors to scrapers of `/metrics` endpoints and even provide our own such endpoints where none exist, performance will be crucial. The `statsd` collector is optimized to death and can handle hundreds of thousands of metrics per second. 
- Our work will significantly extend the functionality of the `statsd` collector as well, paving the way for more custom APM (i.e. people monitoring their own application with Netdata).

So what do we need in order to achieve both the prometheus `/metric` monitoring and the extension of the existing `statsd` collector?

- Make the `statsd` collector understand labels. [Datadog uses an extension](https://docs.datadoghq.com/developers/dogstatsd/?tab=python) of the `statsd` protocol that does exactly that. We can do the same.
- Make synthetic charts more flexible:
  - Add chart templates. Right now, for each distinct chart, we need to add a configuration section. Templates will allow us to do it at a context level.
  - Add regular expression support to simple patterns. This will enable us to do much more powerful groupings of metrics into charts.
  - Add support for labels to synthetic charts (not just an extension of the metric name pattern matching, but a separate directive to filter only the metrics a synthetic chart needs, based on labels).
- Make using synthetic charts MUCH easier, via documentation improvements or hopefully a wizard.
- Extend the `statsd` collector to also support incoming prometheus-formatted metrics. We should ideally be able to re-use (not copy) most of the existing code, to do the same things with prometheus-based metrics.

There is a difference however between statsd and prometheus. In general prometheus polls, statsd listens. The prometheus Remote Write API provides a solution and we should implement that API in our statsd-like code. This means that if any other solutions out there are able to stream metrics to prometheus, they will be able to stream them to netdata as well, by just configuring an endpoint. 

Still, most monitored applications will just expose a `/metrics` endpoint for querying. What we need there is a generic collector (written only once) that will scrape all those endpoints as often as it makes sense and push the information to the statsd-like internal collector. The format to push those metrics could very well be the one that the remote write API uses. If we have a better way (e.g. we write that generic collector in C, on the statsd-like collector), then we don't need to go through the remote write API at all. The statsd-like collector will do everything. 

We need to reiterate now that this solution is not a panacea. We'll always have custom collectors, for cases where even the newly improved synthetic chart directives are not enough. But we know that those will eventually be the exception, rather than the rule.

**Comment by cakrit** [comment]
cc @cosmix @vlvkobal @amoss 
Plz check the above.

**Comment by amoss** [comment]
Do we have a specific example of a `/metrics` endpoint that we can look at? I would like to understand:
* what what data is inside the endpoint.
* what the syntax of the data looks like.
* how it relates to an example that would be parsed by `stats.d`
* how the syntax for synthetic charts would relate.
After reading the existing documentation it is not clear to me yet what we want to do, or how it relates to the existing processing that already exists.

**Comment by amoss** [comment]
@ilyam8 Please put the WMI example here so that we can start discussing these points.

**Comment by cakrit** [comment]
> Do we have a specific example of a `/metrics` endpoint that we can look at? I would like to understand:

I put a couple of examples under [a shared drive](https://drive.google.com/drive/u/0/folders/13QSCQYHXsvmK-u4I1Q8GypwNh0mKRf3W).

**Comment by cakrit** [comment]
https://github.com/netdata/netdata/issues/7897#issuecomment-584331191 updated after a decision to not implement the Prometheus Remote Write API at all.

**Comment by cakrit** [comment]
Design decision depicted below:
<img width="1147" alt="Design Decision" src="https://user-images.githubusercontent.com/43294513/74754669-cffe3600-5226-11ea-8a63-560e055cff9f.png">

**Comment by cosmix** [comment]
- The …/prometheus scraper will be written in C and will be internal to the dæmon. It will make use of a non-blocking/async facility (multithreading, event loop, e.g. using libuv, we could use their event pool/worker pool abstraction) to allow fast querying of all sources.

- For k8s we will require a discovery mechanism to pick up services running on ephemeral pods and will provide `/metrics` endpoints.

Next steps:

0. Pick an endpoint that's realistic (VerneMQ is a good candidate) and try to write the synethetic charts syntax to map the metrics to charts.
1. Decide whether we'll have an internal or external openmetrics/prometheus scraper.
2. We'll need to extend the built-in statsd engine to support DogStatsd, as this is closer to the feature-set that is provided by Prometheus.
3. We'll need to expose an easier way for users to define a chart, given a number of metrics, than the one currently in the dæmon.

**Comment by KlavsKlavsen** [comment]
How is the generic prometheus scraper progressing? any place we can look - and perhaps assist? We are using netdata streaming feature - to forward all agent metrics to a central netdata proxy - so it can be reached (hosts are inaccessible from central place) - and would like to also scrape /metrics endpoints so we can get those, streamed to central location, via the netdata also.

**Comment by ilyam8** [comment]
@KlavsKlavsen i could say the work is started.

> and perhaps assist?

This is very nice! I dont have question atm, just started working on it. But ill have them for sure, ill ping you when i need something

**Comment by KlavsKlavsen** [comment]
> This is very nice! I dont have question atm, just started working on it. But ill have them for sure, ill ping you when i need something

Great - Our plan is to firstly use it with haproxy 2.0+ /metrics endpoint as that has more metrics than current netdata haproxy plugin :)

**Comment by KlavsKlavsen** [comment]
Could you share code on this ? We kinda need this too - and alternative is to implement our own "generic metrics pulling plugin"

**Comment by KlavsKlavsen** [comment]
https://github.com/netdata/go.d.plugin/pull/401/files would be the plugin I would start with

**Comment by ilyam8** [comment]
yeah, https://github.com/netdata/go.d.plugin/pull/401 is kinda ready, it is super initial version with some hardcoded stuff and zero user configurable options. We are trying to figure out how this plugin should work. Will be in the master soon.

**Comment by cakrit** [comment]
Part of this is in https://github.com/netdata/netdata/pull/9644, which contains the PR @ilyam8 mentioned above.
