### ISSUE TITLE
Metric Collection: Kubernetes Service Discovery

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#7903]
### Target 
- Enable Netdata Agent to collect metrics from apps that are running inside Kubernetes containers 

### Why?
- Zero visibility. Apps/processes that are running in Kubernetes containers are not currently monitored. 
- A nested architecture. Kubernetes is a container-orchestration that has a nested architecture. As a result collecting data and making sense out of them will require additional enhancements in the agent (e.g. labels that can associate the same metrics related to the same processes running across containers) 

### What?
**Minimal Configuration (i.e. auto-discovery)**
- As a user I want to have a preconfigured template with services I can monitor out of the box. 
    - Pe-populate the configuration file with (<=40 apps Netdata monitors with do.d.plugin)
    - Build the agent service discovery 
    - Test it against the cloud infrastructure that it works. 

**Metric Collection**
- Number of collectors delivered as part of K8 auto-discovery should be equal to number of go.d.plugin collectors (<=40).
- Display collected metrics on agent navigation bar without any additional enhancement (see attachment below).

**Instant access to new time-series metrics ** 
- As a user I want to be able to monitor new services by changing the configuration file without having to restart the agent (auto-reload).
- As a user I want to instantly access (max 10sec) to new time-series metrics, as any new containers, pods, nodes, are created or destroyed at any given time.
- My charts are updated automatically, and they are tested agents alerts.

![img.jpg](https://images.zenhubusercontent.com/5e454d0640c99e26bf734520/fc1a75aa-0d31-4e35-a608-f373a4ee2f84)

**Comment by amoss** [comment]
The data-model that was needed to define a more meaningful way to display metrics from clusters has been discussed with @ilyam8. This is the data-model that exists in Kubernetes, anything beyond this is user/application specific:

* The cluster is a sea of pods.
* Each pod is named by a set of labels: key-value pairs.
* The labels are immutable for the lifetime of the pod.
* The labels can be injected at arbitrary points to the API Server - users can specify labels in several types of object definition, although the most common will be in the deployment .yaml (where the Pod template is located).

This means that the raw data-model for the Kubernetes cluster is:
```
[ (pod, {(key,value)}) ]
```

In order to provide any useful aggregation of metrics for display we will need to specify queries of sets of matching labels (or patterns). This is because any organization beyond the specification above is **user-specific** and **cluster-specific** and cannot be modeled in Netdata.

This concludes the data-model for the Kubernetes cluster, however in parallel to this there is the physical architecture: the cluster is made of Nodes (hosts).

Our current working estimate for how we will deploy Netdata into clusters is:

* One master Netdata process per cluster.
* One slave Netdata process per Node.
* The slave process will query metrics for all Pods currently running on the Node.

This means that the metrics delivered to the top-level master Netdata will be named by:
* The GUID of the slave Netdata (persistent to the Node). This can be replaced by the `nodeName` label inside the key-value set for each metric if it is more useful.
* The set of key-value labels that are associated with the Pod running on the Node.

**Comment by ilyam8** [comment]
```yaml
Cluster:
  - Namespace
    - pod
       - container
         - [metrics] resource util (cpu. mem)
         - applications
           - [metrics] app1 (app specific)
           - [metrics] appN (app specific)
        - containerN
    - podN
  - NamespaceN
```

**Comment by ilyam8** [comment]
+ we need to monitor 
- `services` (availability OR metrics)
- `ingress` (access from outside) (availability)

**Comment by ilyam8** [comment]
link to the my diagrams (wip), view-only: 
> https://drive.google.com/file/d/1N9KmkjYVHAXIrPOTn_fP6Wk2bM8Y3o5A/view?usp=sharing

**Comment by cakrit** [comment]
This analysis isn't complete. It ignores containers and services. Many other commercial solutions monitor k8s properly, let's learn from them.

**Comment by amoss** [comment]
@ilyam8 had ruled out containers as being irrelevant and suggested that we treat pods as the basic unit of organization. 

* What would we want from each container?
* How would this impact the choice to rely on a slave Netdata in each Pod?
* What information would we gain from services?

The result of the analysis was that the basic Kubernetes data-model is very sparse so we need to rely on labels as our form of organization. Could you point @dim08 towards the specific solutions that you have in mind so that he can incorporate any additions into an initial design of how we organize the information in the Agent?

**Comment by ilyam8** [comment]
Pod is basic unit, yes. There are containers in this scheme

> https://github.com/netdata/netdata/issues/7903#issuecomment-614097700

**Comment by cakrit** [comment]
pods:containers have a 1:M relationship. A container is a cgroup that exists regardless of k8s, a pod is a k8s-specific concept. So pods are not "basic" units.

**Comment by amoss** [comment]
@ilyam8 has worked out an initial design proposal for how we can use netdata in a kubernetes deployment. The next step should be a product groom to decide what we want to achieve.
