### ISSUE TITLE
netdata spyware still tracks user even after the user has opted out of telemetry

### ISSUE THREAD

**Issue by sneak** [netdata/netdata#7981]
The documentation for netdata, comprising of a bunch of README files across various collectors and other directories, do not respect the tracking opt-out provided.

# Steps To Reproduce

1. Install netdata using the appropriate flags or env vars to disable its spyware
1. View netdata's markdown documentation on your system
1. Telemetry is still sent to Google Analytics, including the user's PII

As far as I can tell, all of the documentation includes Google Analytics tracking pixels, and none of it respects the opt-out mechanism.

Here is one of many, many instances, as an example:

https://github.com/netdata/netdata/blame/master/web/api/formatters/README.md#L73

You may easily find many more by running the following command in the root of the repository:

`grep -ir google-analytics\.com . | grep pageview`

It looks like the nonconsensual tracking is embedded over 200 different times in the codebase.

Once a user has revoked telemetry consent, continuing to leak their personally identifiable information (their IP address) to third parties in violation of their wishes is deeply unethical.

**Comment by Ferroin** [comment]
The markdown documentation is hosted at docs.netdata.cloud, and has no relation whatsoever to any particular installation of Netdata on your local systems. The pages have no way to know if you even have Netdata installed on your system, let alone if you happened to tell it at install to opt out of tracking (in fact, if they did, that would be a much more serious security issue than us happening to use Google Analytics on the pages in the first place since it would mean the pages could access almost anything on your system if they wanted to).

If you're accessing the documentation through docs.netdata.cloud, there's no reason that _you_ as the paranoid one here, can't use a browser extension (might I suggest NoScript or Chostery) to block the requests client-side (or you could use any of the other more involved solutions to blocking Google Analytics, it's not like you can't find dozens of options if you search this online).

If, for some reason, you're serving the docs locally, then there's no reason whatsoever you couldn't just patch out the Google Analytics stuff in your local copies.
