### ISSUE TITLE
ACLK SSO investigation

### ISSUE THREAD

**Issue by stelfrag** [netdata/netdata#8038]
#### Summary
Review the SSO document and implement the functionality that is needed in the agent during startup.

**Comment by amoss** [comment]
Grooms have concluded with a viable proposal. There are no immediate requirements to change the `.c` code in the agent. After release we will update claiming so that visible URLs can be specified and communicated to the Cloud over the ACLK. The changes that are required are currently being tracked as work in the dashboard update.
