### ISSUE TITLE
Install local version of libwebsockets v3 if unavailable.

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#8077]
##### Feature idea summary

If the system installing Netdata does not have libwebsockets v3+ then download and build it.
This is complicated by the library detection routines being in autotools which is called after the installer.

##### Expected behavior

* The netdata-installer should try to download the libwebsockets code, put it into a /tmp build directory and build a static version of the library. 
* This should then be copied into externaldeps/libwebsockets along with any header files.
* The configure script should check if libwebsockets v3 is in the base system, by checking if it can resolve one of the changed names as a symbol.
* If it cannot then it add the static version of the library to the build target if-and-only-if:
  * the static build of libmosquitto succeeded
  * the --disable-cloud switch was not passed to the installer (so it did not set the appropriate --disable flags for configure).
* If the build of libwebsockets fails then we splash an error message to the console (as discussed on product/282) and disable the ACLK.

Investigate whether there wide-enough support for rpath (across the linux distros, the BSDs and MacOS) to allow an alternative, in which case:

* Build v3 of libwebsockets as shared library.
* Install into an appropriate path under the installation prefix,  e.g. some variation on /usr/lib, /usr/libexec or /var/lib as appropriate?
* Set the rpath in the build.
* Change the handling of libmosquitto to use the same approach.

##### Necessary test-cases

* Feature flag disabled.
* Systems with libwebsockets v2 + libmosquitto available.
* Systems with libwebsockets v3 + libmosquitto available.
* Systems with libwebsockets v2 + libmosquitto unavailable.
* Systems with libwebsockets v3 + libmosquitto unavailable.
[Simulate the last two by artificially breaking the build].

**Comment by Ferroin** [comment]
Those first two steps should be happening _after_ we figure out if we need libsebsockets or not, not before. We're wasting resources otherwise, and may be costing our users money as a result. The check should be trivial on most systems, as we can just use `pkg-config --modversion libwebsockets` to get an exact version number.

**Comment by Ferroin** [comment]
I'm not entirely sure using RPATH is worth the effort for this. It's at least partly dependent on both the compiler and the libc being used even on Linux, and using dynamic loading for libraries we only link into one binary doesn't really get us anything. The whole point of dynamic linking is to save disk space and reduce the runtime memory footprint of binaries by dedpuplicating code that is being used by multiple binaries, which doesn't matter for us if we're only linking into one binary (or even only two or three).

This _might_ matter if we were installing libwebsockets version 3 on the system ourselvew, but we absolutely cannot do that as it will result in a very high risk of us breaking things.

@cosmix If you could comment on this it would be appreciated.

**Comment by Ferroin** [comment]
Cross-distro version info for libwebsocksts: https://repology.org/project/libwebsockets/versions

Looks like we'll need the custom build most places except Alpine, Arch, and Fedora.

**Comment by cosmix** [comment]
@Ferroin my suggestion to `rpath` was only suggested as a production-orientated alternative to `LD_LIBRARY_PATH`, which, as you know, is not supposed to be used in production/stable builds, but is intended as a development tool. I agree that `rpath` is not optimal, and I even pointed this out, mostly due to the cross-platform support (or lack thereof, to be precise) — that said, `rpath` is better than `LD_LIBRARY_PATH` in most regards, and is supported by both clang and gcc on *nix platforms.

The optimal solution in terms of compatibility would be to statically link, but that will inflate our distribution size, and — I expect soon(ish) — people will likely switch to version 3, hence my suggestion for `rpath` (again relative to `LD_LIBRARY_PATH`)

Also, I'm not clear what you mean by the 'effort'. There's `nothing` laborious about `rpath`. Care to elaborate?

**Comment by Ferroin** [comment]
> musl is another story of course, so I guess that's what you mean by the 'effort'

RPATH needs to be supported by the runtime linker to work. I'm not sure if macOS actually supports it the way we need it to work or not, I'm fairly certain that Solaris doesn't, musl may or may not, and it's entirely optional with uClibc. It's also tricky to get right in some cases, and is rather fragile since you can't do runtime configuration of it like you could for, say, `dlopen()`.

> The optimal solution in terms of compatibility would be to statically link, but that will inflate our distribution size

Um, how would we not be inflating our distribution size if we dynamically linked this? It needs to be bundled regardless on systems that don't have libwebsockets3.

As far as I see it, all we need to do is add a configure option to tell it to use a local static version of the lib, and have the installer pass that when it needs to be used.

**Comment by cosmix** [comment]
Nope that’s wrong. Both macOS and Solaris have equivalents. Not sure about the rest. Either way, we’re going with the static build.

The point of not increasing the size was related to the fact that I expect most major distributions to have libwebsockets 3.x very soon which would allow us to selectively provide the lib, _had there been no other issues with it of course_.

**Comment by cosmix** [comment]
@amoss identified issues with this. Reopening. Cc @Ferroin

**Comment by Ferroin** [comment]
This is functionally currently done for our `kickstart.sh` install method.

A PR to add this for our package builds will be forthcoming shortly.
