### ISSUE TITLE
Automatic changelog generation doesn't work well

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#8117]
##### Bug report summary

CHANGELOG.md was missing tens of PRs this time.  The [log generator we use](https://github.com/github-changelog-generator/github-changelog-generator) is buggy, extremely slow & inefficient and finally proven to be unreliable. 

##### Expected behavior
Let's check to see if we can find a much better changelog generator. If we can't, we'll need to write something ourselves. 

The info we need can be produced by something as simple as the following, as long as can feed it with a list of PRs after the last tag. 

```bash
while read a; do
curl -H "Authorization: token 91303b0a90f2d170da4dfa683f8cb2c912ac666f" -s https://api.github.com/repos/netdata/netdata/pulls/$a |
jq '. | "- \(.title) [#\(.number)](https://github.com/netdata/netdata/pull/\(.number)) ([\(.user.login)](https://github.com/\(.user.login)))"' |
tr -d '"'
done < prlist
```

Of course we would ideally get the PRs organized in categories such as bug fixes, collector improvements etc, but that's a secondary concern. The primary one is having the correct list of PRs after every nightly build.

**Comment by prologic** [comment]
I'd like to take this on :) I've had to wrestle with the same thing on many projects so I'm confident I can get this right! We _will_ however also have to define a rather strict process around PR titles; as that helps a lot with the "review" and "tidying" up if it can it can be maintained in strict-ish form. 😀

**Comment by prologic** [comment]
cc @joelhans @shortpatti Do you guys have plans for handling the ChangeLog / Release Notes in some better ways going forward for the next release/etc?

**Comment by joelhans** [comment]
@prologic I'm adding items to the release notes on an ongoing basis. I look at [commits](https://github.com/netdata/netdata/commits/master), investigate the PR a bit, and then add text to [the v1.21 release notes](https://github.com/netdata/marketing/blob/master/release-1.21.md) (not sure if you can see that).

Basically, I don't trust `CHANGELOG.md` any more.

This doesn't really improve the process, only make it slightly less painful since I won't be doing it in bulk right before the release.

**Comment by prologic** [comment]
> This doesn't really improve the process, only make it slightly less painful since I won't be doing it in bulk right before the release.

Yeah the only way to improve the process as far as I'm concerned is with #8199 __and__ enforced checks on Pull Requests so what eventually gets merged in follows a set of conventions/rules you can easily follow that _could_ be relied upon and trusted for future ChangeLog / Release Notes automation (_even if partial_). Just my $0.02 worth :) -- This is a hard thing :D

**Comment by joelhans** [comment]
@prologic I think you and Andrew are on the same page about where to go with this, but let me know if you need any feedback about the desired output for the changelog.

**Comment by prologic** [comment]
Icing this for now... See [comment](https://github.com/netdata/netdata/pull/8705#issuecomment-644078790)

**Comment by prologic** [comment]
I had a 2nd go of this (_being the type of person that doesn't accept failure and believes "Problems are Solved by Method"_)... I spent several late-hours hacking on [release-notes](https://github.com/prologic/release-notes) a tool I've put together based on prior art from the Kubernetes team that uses this approach to generate their own Release Notes.

I've now modified a forked version of this tool to suit our specific needs; but I plan to spin this into a general-purpose tool (_in my own time_). The current version as of https://github.com/prologic/release-notes/commit/0cec60796374e958302364d5362df01dedfe8d1a mostly suits our needs based on existing Netdata Agent workflows.

This produces the following output which is currently under review by both @and0x000 and @joelhans :

https://gist.github.com/prologic/4abf385b5f43e49498e7d07c6379d99e

Once the current output is acceptable, this issue will be closed and other work (_as needed_) will continue in separately tracked issue to further improve the tool and replace/refactor our uses of the old Ruby tool littered in a few places around our Travis CI (_which we are phasing out_) and various scripts.

**Comment by prologic** [comment]
For reference the upcoming `v1.23.0` Release Notes / Change Log currently looks like this:

----

## New Features

- Integration between eBPF and Apps ([#9178](https://github.com/netdata/netdata/pull/9178), [@thiagoftsm](https://github.com/thiagoftsm))
- Adds metrics for ACLK performance and status ([#9269](https://github.com/netdata/netdata/pull/9269), [@underhood](https://github.com/underhood))
- Fix consistency of kubernetes cgroup names ([#9303](https://github.com/netdata/netdata/pull/9303), [@cakrit](https://github.com/cakrit))
- update_apps_groups: Bring imunify and lsphp to apps groups ([#9284](https://github.com/netdata/netdata/pull/9284), [@thiagoftsm](https://github.com/thiagoftsm))
- Update apps.plugin documentation and dashboard.info ([#9199](https://github.com/netdata/netdata/pull/9199), [@thiagoftsm](https://github.com/thiagoftsm))
- Add support for eBPF for Netdata static64 (kickstart-static64.sh) ([#9104](https://github.com/netdata/netdata/pull/9104), [@prologic](https://github.com/prologic))
- eBPF modular ([#9148](https://github.com/netdata/netdata/pull/9148), [@thiagoftsm](https://github.com/thiagoftsm))
- Update the kernel-collector version to v0.2.0 ([#9118](https://github.com/netdata/netdata/pull/9118), [@prologic](https://github.com/prologic))
- Implement new incremental parser ([#9074](https://github.com/netdata/netdata/pull/9074), [@stelfrag](https://github.com/stelfrag))
- install and enable eBPF Plugin by default ([#8665](https://github.com/netdata/netdata/pull/8665), [@Ferroin](https://github.com/Ferroin))
- Improve the impact of health code on netdata scalability ([#8407](https://github.com/netdata/netdata/pull/8407), [@mfundul](https://github.com/mfundul))
- Fix error handling in exporting connector ([#8910](https://github.com/netdata/netdata/pull/8910), [@vlvkobal](https://github.com/vlvkobal))
- Add a Google Cloud Pub/Sub connector to the exporting engine ([#8855](https://github.com/netdata/netdata/pull/8855), [@vlvkobal](https://github.com/vlvkobal))
- Rename eBPF collector ([#8822](https://github.com/netdata/netdata/pull/8822), [@thiagoftsm](https://github.com/thiagoftsm))
- Ebpf options ([#8879](https://github.com/netdata/netdata/pull/8879), [@thiagoftsm](https://github.com/thiagoftsm))


## Documentation

- Change streaming terminology to parent/child in docs ([#9312](https://github.com/netdata/netdata/pull/9312), [@joelhans](https://github.com/joelhans))
- Add support for persistent metadata ([#9324](https://github.com/netdata/netdata/pull/9324), [@stelfrag](https://github.com/stelfrag))
- Correct the repo in the docs for CentOS 8. ([#9308](https://github.com/netdata/netdata/pull/9308), [@Ferroin](https://github.com/Ferroin))
- Add guide to exporting metrics to Graphite ([#9285](https://github.com/netdata/netdata/pull/9285), [@joelhans](https://github.com/joelhans))
- Add frontmatter to Matrix notifications doc ([#9295](https://github.com/netdata/netdata/pull/9295), [@joelhans](https://github.com/joelhans))
- Support for matrix notifications ([#9196](https://github.com/netdata/netdata/pull/9196), [@okias](https://github.com/okias))
- Add link to kernel docs for ftrace ([#9211](https://github.com/netdata/netdata/pull/9211), [@Steve8291](https://github.com/Steve8291))
- Move/refactor docs to accomodate new Guides section on Learn ([#9266](https://github.com/netdata/netdata/pull/9266), [@joelhans](https://github.com/joelhans))
- Cleanup of main README and registry doc ([#9265](https://github.com/netdata/netdata/pull/9265), [@joelhans](https://github.com/joelhans))
- Add notes/known issues section to installation page ([#9053](https://github.com/netdata/netdata/pull/9053), [@joelhans](https://github.com/joelhans))
- Fix frontmatter in circular_buffer README ([#9262](https://github.com/netdata/netdata/pull/9262), [@joelhans](https://github.com/joelhans))
- Fixes documentation ambiguity leading into issue #8239 ([#9255](https://github.com/netdata/netdata/pull/9255), [@underhood](https://github.com/underhood))
- Add new exporting "home base" document ([#9246](https://github.com/netdata/netdata/pull/9246), [@joelhans](https://github.com/joelhans))
- Fix reliability of kickstart/kickstart-static64 with checksums sometimes failing ([#9165](https://github.com/netdata/netdata/pull/9165), [@prologic](https://github.com/prologic))
- Improve dbengine docs for streaming setups ([#9177](https://github.com/netdata/netdata/pull/9177), [@joelhans](https://github.com/joelhans))
- fix small typo ([#9205](https://github.com/netdata/netdata/pull/9205), [@Steve8291](https://github.com/Steve8291))
- Added health check functionality to our Docker images. ([#9172](https://github.com/netdata/netdata/pull/9172), [@Ferroin](https://github.com/Ferroin))
- Update README.md ([#9151](https://github.com/netdata/netdata/pull/9151), [@stephenrauch](https://github.com/stephenrauch))
- Remove the experimental label from the exporting engine documentation ([#9171](https://github.com/netdata/netdata/pull/9171), [@vlvkobal](https://github.com/vlvkobal))
- Change backends to exporting engine in general documentation pages ([#9045](https://github.com/netdata/netdata/pull/9045), [@vlvkobal](https://github.com/vlvkobal))
- fix typo in step-03.md ([#9150](https://github.com/netdata/netdata/pull/9150), [@waybeforenow](https://github.com/waybeforenow))
- Move nc backend ([#9030](https://github.com/netdata/netdata/pull/9030), [@thiagoftsm](https://github.com/thiagoftsm))
- Fix docs CI to handle absolute links between docs ([#9132](https://github.com/netdata/netdata/pull/9132), [@joelhans](https://github.com/joelhans))
- Remove old docs generation tooling ([#8783](https://github.com/netdata/netdata/pull/8783), [@prologic](https://github.com/prologic))
- Fix paths to trigger docs CI workflow ([#9128](https://github.com/netdata/netdata/pull/9128), [@joelhans](https://github.com/joelhans))
- Update step-10.md ([#9000](https://github.com/netdata/netdata/pull/9000), [@Jelmerrevers](https://github.com/Jelmerrevers))
- Update eBPF documentation to reflect default enabled status ([#9105](https://github.com/netdata/netdata/pull/9105), [@joelhans](https://github.com/joelhans))
- Add ACLK Connection Details ([#9047](https://github.com/netdata/netdata/pull/9047), [@zack-shoylev](https://github.com/zack-shoylev))
- Add GitHub CI job to check Markdown links during PRs ([#9003](https://github.com/netdata/netdata/pull/9003), [@joelhans](https://github.com/joelhans))
- Included 'cmake' in the list of pkgs installed ([#9031](https://github.com/netdata/netdata/pull/9031), [@zvarnes](https://github.com/zvarnes))
- Update synology.md ([#8658](https://github.com/netdata/netdata/pull/8658), [@thenktor](https://github.com/thenktor))
- Update pfsense.md ([#8544](https://github.com/netdata/netdata/pull/8544), [@electropup42](https://github.com/electropup42))
- Docs: Update contributing guidelines ([#8781](https://github.com/netdata/netdata/pull/8781), [@joelhans](https://github.com/joelhans))
- Removeed Polyverse Polymorphic Linux from Docker builds. ([#8802](https://github.com/netdata/netdata/pull/8802), [@Ferroin](https://github.com/Ferroin))
- Fix issue #9085:  Prometheus TYPE lines incorrectly formatted (when enabled via query parm) ([#9086](https://github.com/netdata/netdata/pull/9086), [@jeffgdotorg](https://github.com/jeffgdotorg))
- Add links to promote database engine calculator ([#9067](https://github.com/netdata/netdata/pull/9067), [@joelhans](https://github.com/joelhans))
- Update the exporting documentation ([#9066](https://github.com/netdata/netdata/pull/9066), [@vlvkobal](https://github.com/vlvkobal))
- python.d/proxysql: add `Requirements` to the readme ([#9071](https://github.com/netdata/netdata/pull/9071), [@ilyam8](https://github.com/ilyam8))
- Add proc.plugin configuration example for high-processor systems ([#9062](https://github.com/netdata/netdata/pull/9062), [@joelhans](https://github.com/joelhans))
- Add frontmatter to exporting connectors ([#9052](https://github.com/netdata/netdata/pull/9052), [@joelhans](https://github.com/joelhans))
- Typo. ([#8703](https://github.com/netdata/netdata/pull/8703), [@cherouvim](https://github.com/cherouvim))
- Update freebsd.md ([#8643](https://github.com/netdata/netdata/pull/8643), [@thenktor](https://github.com/thenktor))
- claim: fix `New/ephemeral Agent containers` instruction ([#9058](https://github.com/netdata/netdata/pull/9058), [@ilyam8](https://github.com/ilyam8))
- Add agent restart note for reclaiming ([#9049](https://github.com/netdata/netdata/pull/9049), [@zack-shoylev](https://github.com/zack-shoylev))
- Docs: Remove old Cloud/dashboard and replace with new Cloud/dashboard ([#8874](https://github.com/netdata/netdata/pull/8874), [@joelhans](https://github.com/joelhans))
- Fix link in web server log guide ([#9033](https://github.com/netdata/netdata/pull/9033), [@joelhans](https://github.com/joelhans))
- removed simley face per Chris since it didn't show up ([#8872](https://github.com/netdata/netdata/pull/8872), [@MeganBishopMoore](https://github.com/MeganBishopMoore))
- Add text to claiming doc about reclaiming with id= ([#9027](https://github.com/netdata/netdata/pull/9027), [@joelhans](https://github.com/joelhans))
- Update daemon output with new URLs and dates ([#8965](https://github.com/netdata/netdata/pull/8965), [@joelhans](https://github.com/joelhans))
- Caddy section lacked data persist volumes ([#8999](https://github.com/netdata/netdata/pull/8999), [@webash](https://github.com/webash))
- Add text to ACLK doc mentioning WebSockets and port ([#8968](https://github.com/netdata/netdata/pull/8968), [@joelhans](https://github.com/joelhans))
- Fix file name weblog.conf -> web_log.conf ([#8959](https://github.com/netdata/netdata/pull/8959), [@gruentee](https://github.com/gruentee))


## Packaging / Installation

- installer: update go.d.plugin version to v0.19.2 ([#9340](https://github.com/netdata/netdata/pull/9340), [@ilyam8](https://github.com/ilyam8))
- Change streaming terminology to parent/child in docs ([#9312](https://github.com/netdata/netdata/pull/9312), [@joelhans](https://github.com/joelhans))
- Override linker and include paths for static builds. ([#9311](https://github.com/netdata/netdata/pull/9311), [@Ferroin](https://github.com/Ferroin))
- Added dummy `--enable-ebpf` flag to avoid breaking updates. ([#9310](https://github.com/netdata/netdata/pull/9310), [@Ferroin](https://github.com/Ferroin))
- Correct the repo in the docs for CentOS 8. ([#9308](https://github.com/netdata/netdata/pull/9308), [@Ferroin](https://github.com/Ferroin))
- installer: update go.d.plugin version to v0.19.1 ([#9309](https://github.com/netdata/netdata/pull/9309), [@ilyam8](https://github.com/ilyam8))
- installer: update go.d.plugin version to v0.19.0 ([#9294](https://github.com/netdata/netdata/pull/9294), [@ilyam8](https://github.com/ilyam8))
- Added support for macOS/Homebrew in `install-required-packages.sh`. ([#8286](https://github.com/netdata/netdata/pull/8286), [@Ferroin](https://github.com/Ferroin))
- Fixed handling of OpenSSL on CentOS/RHEL by bundling a static copy and selecting a configuration directory at install time. ([#9263](https://github.com/netdata/netdata/pull/9263), [@Ferroin](https://github.com/Ferroin))
- Add notes/known issues section to installation page ([#9053](https://github.com/netdata/netdata/pull/9053), [@joelhans](https://github.com/joelhans))
- Add a random offset to the update script when running non-interactively. ([#9245](https://github.com/netdata/netdata/pull/9245), [@Ferroin](https://github.com/Ferroin))
- Fix reliability of kickstart/kickstart-static64 with checksums sometimes failing ([#9165](https://github.com/netdata/netdata/pull/9165), [@prologic](https://github.com/prologic))
- Really prevent overwriting netdata.conf on static installs. ([#9174](https://github.com/netdata/netdata/pull/9174), [@Ferroin](https://github.com/Ferroin))
- Update eBPF to use kernel-collector version 0.4.0. ([#9212](https://github.com/netdata/netdata/pull/9212), [@Ferroin](https://github.com/Ferroin))
- Added health check functionality to our Docker images. ([#9172](https://github.com/netdata/netdata/pull/9172), [@Ferroin](https://github.com/Ferroin))
- Fix missing ebpf packaging files from dist archive ([#9182](https://github.com/netdata/netdata/pull/9182), [@prologic](https://github.com/prologic))
- Fix error > emerge openssl-devel ([#9141](https://github.com/netdata/netdata/pull/9141), [@vsc55](https://github.com/vsc55))
- Introduce a random sleep in the Netdata updater ([#9079](https://github.com/netdata/netdata/pull/9079), [@prologic](https://github.com/prologic))
- Add CI for our Static Netdata builds (which kickstart-static64 uses) ([#9130](https://github.com/netdata/netdata/pull/9130), [@prologic](https://github.com/prologic))
- Added required bundle for libuuid on ClearLinux. ([#9060](https://github.com/netdata/netdata/pull/9060), [@Ferroin](https://github.com/Ferroin))
- Fix incorrect issue link URL in install-required-packages.sh ([#8911](https://github.com/netdata/netdata/pull/8911), [@prologic](https://github.com/prologic))
- Remove the unused Dockerfile.docs and associated Docker Hub image ([#9126](https://github.com/netdata/netdata/pull/9126), [@prologic](https://github.com/prologic))
- Fix macOS builds building and linking against openssl ([#8865](https://github.com/netdata/netdata/pull/8865), [@prologic](https://github.com/prologic))
- Fixes enable/start of netdata service in debian package ([#9005](https://github.com/netdata/netdata/pull/9005), [@MrFreezeex](https://github.com/MrFreezeex))
- Remove old docs generation tooling ([#8783](https://github.com/netdata/netdata/pull/8783), [@prologic](https://github.com/prologic))
- Package: obsoletes conflicting EPEL packages (#6879 #8784) ([#9108](https://github.com/netdata/netdata/pull/9108), [@Saruspete](https://github.com/Saruspete))
- Fix suid bits on plugin for debian packaging ([#8996](https://github.com/netdata/netdata/pull/8996), [@MrFreezeex](https://github.com/MrFreezeex))
- Don't overwrite netdata.conf on update on static installs. ([#9046](https://github.com/netdata/netdata/pull/9046), [@Ferroin](https://github.com/Ferroin))
- Included 'cmake' in the list of pkgs installed ([#9031](https://github.com/netdata/netdata/pull/9031), [@zvarnes](https://github.com/zvarnes))
- Update synology.md ([#8658](https://github.com/netdata/netdata/pull/8658), [@thenktor](https://github.com/thenktor))
- Update pfsense.md ([#8544](https://github.com/netdata/netdata/pull/8544), [@electropup42](https://github.com/electropup42))
- Docs: Update contributing guidelines ([#8781](https://github.com/netdata/netdata/pull/8781), [@joelhans](https://github.com/joelhans))
- Removeed Polyverse Polymorphic Linux from Docker builds. ([#8802](https://github.com/netdata/netdata/pull/8802), [@Ferroin](https://github.com/Ferroin))
- Update freebsd.md ([#8643](https://github.com/netdata/netdata/pull/8643), [@thenktor](https://github.com/thenktor))
- Docs: Remove old Cloud/dashboard and replace with new Cloud/dashboard ([#8874](https://github.com/netdata/netdata/pull/8874), [@joelhans](https://github.com/joelhans))
- Caddy section lacked data persist volumes ([#8999](https://github.com/netdata/netdata/pull/8999), [@webash](https://github.com/webash))


## Bug Fixes

- Fix remote write HTTP header ([#9302](https://github.com/netdata/netdata/pull/9302), [@vlvkobal](https://github.com/vlvkobal))
- Fixed cmake build affected by #9074 ([#9186](https://github.com/netdata/netdata/pull/9186), [@stelfrag](https://github.com/stelfrag))
- cov_358988: Remove coverity bug ([#9180](https://github.com/netdata/netdata/pull/9180), [@thiagoftsm](https://github.com/thiagoftsm))
- OpenTSDB and TLS ([#9068](https://github.com/netdata/netdata/pull/9068), [@thiagoftsm](https://github.com/thiagoftsm))
- Fixed bug in accepting empty lines in parser ([#9158](https://github.com/netdata/netdata/pull/9158), [@stelfrag](https://github.com/stelfrag))
- Correctly track last num vcpus in xenstat_plugin ([#8720](https://github.com/netdata/netdata/pull/8720), [@rushikeshjadhav](https://github.com/rushikeshjadhav))
- Regenerate topic base on connect ([#9044](https://github.com/netdata/netdata/pull/9044), [@amoss](https://github.com/amoss))
- Restore SIGCHLD signal handler after being replaced by libuv ([#9107](https://github.com/netdata/netdata/pull/9107), [@mfundul](https://github.com/mfundul))
- Reduce minimum size for dbengine disk space ([#9094](https://github.com/netdata/netdata/pull/9094), [@mfundul](https://github.com/mfundul))
- Account for zfs.arc_size.min, and correct calc ([#8913](https://github.com/netdata/netdata/pull/8913), [@araemo](https://github.com/araemo))
- Fix wrong hostnames in the exporting engine ([#8892](https://github.com/netdata/netdata/pull/8892), [@vlvkobal](https://github.com/vlvkobal))


## Other Notable Changes

- Fix coverity errors CID 359774 and CID 359773 ([#9338](https://github.com/netdata/netdata/pull/9338), [@mfundul](https://github.com/mfundul))
- Fixed compiler warnings ([#9337](https://github.com/netdata/netdata/pull/9337), [@stelfrag](https://github.com/stelfrag))
- Change streaming terminology to parent-child in the code ([#9323](https://github.com/netdata/netdata/pull/9323), [@amoss](https://github.com/amoss))
- Remove Gentoo from CI ([#9327](https://github.com/netdata/netdata/pull/9327), [@prologic](https://github.com/prologic))
- Fixed invalid memory access ([#9326](https://github.com/netdata/netdata/pull/9326), [@stelfrag](https://github.com/stelfrag))
- Fix check for remote write header in unit tests ([#9318](https://github.com/netdata/netdata/pull/9318), [@vlvkobal](https://github.com/vlvkobal))
- Adds missing files for streaming changes into cmake build ([#9316](https://github.com/netdata/netdata/pull/9316), [@underhood](https://github.com/underhood))
- apps_groups.conf: add agent-service-discovery ([#9315](https://github.com/netdata/netdata/pull/9315), [@ilyam8](https://github.com/ilyam8))
- Add verbose prints when spawn server fails to spawn. ([#9305](https://github.com/netdata/netdata/pull/9305), [@mfundul](https://github.com/mfundul))
- minor copy edits ([#9298](https://github.com/netdata/netdata/pull/9298), [@MeganBishopMoore](https://github.com/MeganBishopMoore))
- Fix crash in #9291 ([#9297](https://github.com/netdata/netdata/pull/9297), [@amoss](https://github.com/amoss))
- dashboard_info.js: ebpf: fix close code block ([#9293](https://github.com/netdata/netdata/pull/9293), [@ilyam8](https://github.com/ilyam8))
- single quote apostrophe ([#8723](https://github.com/netdata/netdata/pull/8723), [@zack-shoylev](https://github.com/zack-shoylev))
- Fix Coverity defects 359164, 359165 and 358989. ([#9268](https://github.com/netdata/netdata/pull/9268), [@amoss](https://github.com/amoss))
- Gap-detection and slew ([#9214](https://github.com/netdata/netdata/pull/9214), [@amoss](https://github.com/amoss))
- fix compilation for older systems ([#9198](https://github.com/netdata/netdata/pull/9198), [@ktsaou](https://github.com/ktsaou))
- Add CI check for building against LibreSSL ([#8842](https://github.com/netdata/netdata/pull/8842), [@prologic](https://github.com/prologic))
- Fix exporting unit tests ([#9183](https://github.com/netdata/netdata/pull/9183), [@vlvkobal](https://github.com/vlvkobal))
- Ceph: Added OSD size collection ([#8649](https://github.com/netdata/netdata/pull/8649), [@elelayan](https://github.com/elelayan))
- Clean type_name in exporting connector instance configuration ([#9188](https://github.com/netdata/netdata/pull/9188), [@vlvkobal](https://github.com/vlvkobal))
- Remove knatsakis and ncmans from CODEOWNERS for the agent. ([#9173](https://github.com/netdata/netdata/pull/9173), [@Ferroin](https://github.com/Ferroin))
- Fixed coverity warning (CID 358971) ([#9157](https://github.com/netdata/netdata/pull/9157), [@stelfrag](https://github.com/stelfrag))
- Missing checks exporting ([#9034](https://github.com/netdata/netdata/pull/9034), [@thiagoftsm](https://github.com/thiagoftsm))
- New alarms (exporting and Backend) ([#9075](https://github.com/netdata/netdata/pull/9075), [@thiagoftsm](https://github.com/thiagoftsm))
- Missing error aws ([#9048](https://github.com/netdata/netdata/pull/9048), [@thiagoftsm](https://github.com/thiagoftsm))
- Exporting cleanup ([#9098](https://github.com/netdata/netdata/pull/9098), [@thiagoftsm](https://github.com/thiagoftsm))
- Check update interval for exporting connector instance ([#9131](https://github.com/netdata/netdata/pull/9131), [@vlvkobal](https://github.com/vlvkobal))
- Send anonymous statistics from backends and exporting engine ([#9125](https://github.com/netdata/netdata/pull/9125), [@vlvkobal](https://github.com/vlvkobal))
- Fix buffer splitting in the Kinesis exporting connector ([#9122](https://github.com/netdata/netdata/pull/9122), [@vlvkobal](https://github.com/vlvkobal))
- Dynamic memory cleanup for Pub/Sub exporting connector ([#9112](https://github.com/netdata/netdata/pull/9112), [@vlvkobal](https://github.com/vlvkobal))
- Improve system-info.sh to better handle certain cases when gathering info on the system's disk capacity. ([#7902](https://github.com/netdata/netdata/pull/7902), [@Ferroin](https://github.com/Ferroin))
- Dynamic memory cleanup for MongoDB exporting connector ([#9103](https://github.com/netdata/netdata/pull/9103), [@vlvkobal](https://github.com/vlvkobal))
- Prepare the main cleanup function for the exporting engine ([#9099](https://github.com/netdata/netdata/pull/9099), [@vlvkobal](https://github.com/vlvkobal))
- Fix typo in dashboard description ([#9096](https://github.com/netdata/netdata/pull/9096), [@Neamar](https://github.com/Neamar))
- Clean instances ([#9081](https://github.com/netdata/netdata/pull/9081), [@thiagoftsm](https://github.com/thiagoftsm))
- [python.d/samba] Only use sudo when not running as root user ([#9038](https://github.com/netdata/netdata/pull/9038), [@Duffyx](https://github.com/Duffyx))
- Sort alphabetically and automatic scroll ([#8762](https://github.com/netdata/netdata/pull/8762), [@tnyeanderson](https://github.com/tnyeanderson))
- Fixed formatting in API swagger json file ([#8814](https://github.com/netdata/netdata/pull/8814), [@dpsy4](https://github.com/dpsy4))
- Update news section of main README with 1.22 news ([#8963](https://github.com/netdata/netdata/pull/8963), [@joelhans](https://github.com/joelhans))
- postgres.chart.py: fix template databases ignore ([#8929](https://github.com/netdata/netdata/pull/8929), [@slavaGanzin](https://github.com/slavaGanzin))
- [varnish] : added compatibility for varnish-plus ([#8940](https://github.com/netdata/netdata/pull/8940), [@pgjavier](https://github.com/pgjavier))

**Comment by and0x000** [comment]
> This produces the following output which is currently under review by both @and0x000 and

@prologic I'm sorry, but you have lost me on this. I'm not aware of any recent contribution of mine to this topic. Did I miss something? Is there anything that I'm expected to actively participate in?

**Comment by prologic** [comment]
> > This produces the following output which is currently under review by both @and0x000 and
> 
> @prologic I'm sorry, but you have lost me on this. I'm not aware of any recent contribution of mine to this topic. Did I miss something? Is there anything that I'm expected to actively participate in?

My apologies, I accidentally tagged you somehow :)

**Comment by prologic** [comment]
This is "done" for now. I will create further issues with @joelhans's help to improve the tool and replace all our usages of the old ruby one everywhere. This will be for `v1.24`.
