### ISSUE TITLE
Automatically enable and configure cloud parameters during claiming.

### ISSUE THREAD

**Issue by cosmix** [netdata/netdata#8622]
When claiming an agent, the configuration needs to be updated to point to the correct Netdata Cloud URL and the relevant settings updated to enable the Cloud.

This should be automatic and transparent to the user to minimize friction. It should, ideally, be done in the claiming script. 

One way of doing this would be:

1. Determine whether the `[cloud]` section is already there:

```
GOT_CLOUD_SECTION=`grep -q "\[cloud\]" $NETDATA_USER_CONFIG_DIR/netdata.conf
```

If it's not, just append it to the file with the right values (not shown here)

If it is, use `awk` to replace the relevant lines. E.g. to properly set the `cloud base url` line we could use something like:

```
awk -v URLBASE=$URL_BASE '/[cloud]/ {ok=1}
ok==1 && /cloud base url/ {print " cloud base url = URLBASE"; ok=0; next}
{print $0} ' $NETDATA_USER_CONFIG_DIR/netdata.conf > /tmp/tmp
```

We'd also need to similarly set/update the `netdata cloud` variable in the `[global]` section, which is presumably always there by default (but is missing the key) — we could, of course, check for its existence in a similar manner to make sure.

**Comment by cosmix** [comment]
Of course, an alternative would be for the agent itself to deal with the configuration update during the `netdatacli reload-claiming-state` which would need to be updated to support updating the configuration etc.

**Comment by amoss** [comment]
@mfundul / @Ferroin - can you see any corner cases that the dev implementing this will need to be aware of?

**Comment by Ferroin** [comment]
I can't think of any special corner cases right now other than the usual one of making sure that the lines aren't commented out when we go to update things.

Long term though I think that we're far better off having the agent update the config instead of doing it from a script. If we modify the config file from a script, we have to signal the agent to re-check it's config, which I believe right now requires restarting the agent itself.

**Comment by amoss** [comment]
The script can be called directly by the user, or it can be called from the agent itself.

The alternative might be easier - Thiago put support into the config for reloading single sections during the labels+tags work. Reloading the cloud section during `netdatacli reload-claiming-state` would work, but the cloud base url is in the global section which is more dangerous to reload.

**Comment by mfundul** [comment]
My opinion is that the work should be done by `netdatacli`. The reason being that only the netdata deamon knows exactly which values are default, which values are set without any duplicated information.

Things that can go wrong by `grep`ing:
1. You can match a commented line, but you cannot assume this is a default value because:
  - This may be a stale default value from a previous installation, only the netdata agent knows the real default value which is hardcoded in its binary at compile time.
  - This may be a value from a previous experiment from the user.
  - There may be multiple such lines and grep will return many lines as output.
  - There can be another line that is not commented.
2. You can also match multiple uncommented lines, and you don't know how the agent has parsed them and what precedence has taken place, or whether it was considered an invalid configuration file.
3. The configuration file can be mostly empty, where once again the default values are hardcoded in the netdata agent binary.

By using `netdatacli` you can consult the netdata agent as the single source of truth, getting rid of all the above problems by taking advantage of its integrated configuration parser. Moreover, the netdata agent is already capable of creating a configuration file dump when asked.

**Comment by cosmix** [comment]
I agree with the proposal to do this in `netdatacli`. It's the right way to do it. 

One note, however:

Re: defaults, we cannot trust the agent with any default, we'll be passing it as part of the claiming script invocation at all times (people may use on-prem, we may move the URL to another location at some point and older agents being installed, e.g. as part of a VM image or container image shouldn't need to be updated just for this) etc.

**Comment by amoss** [comment]
We have some undocumented functionality in the code that achieves this already. There is a command-line argument:
```
netdata -W get ...
```
This will load the config / retrieve the key and output the value. I will check that there is no problem using this to access the config when netdata is already up and running. This will be the basis of how we communicate config values to the claiming script.

For the reverse direction (i.e. updating the url) I will look into either:
* Adding `netdata -W update` that rewrites the config file from C.
* Or `netdata -W diff` that loads the config to get canonical answers and then outputs a `sed` patch.

**Comment by amoss** [comment]
I've starting working on this and checking the cases that we need. Claiming can be performed in three ways:

![Claiming cases](https://user-images.githubusercontent.com/1043609/79763512-7a2c3400-8324-11ea-8da8-48e896fbab50.jpeg)

Problem 1: not picking up config properly
* The `run as user` setting needs to be read properly (to overcome the problems in @mfundul 's comment above).
* If the cloud is disabled in a way that cannot be flipped (e.g. the build failed, or the agent was compiled with the disable flag)  then the script needs to fail.
* The cloud is disabled in a way that can be flipped (only the cloud setting in the config) then the script needs to know to update it.

Problem 2: rewriting config from the script
* Overwrite the `cloud base url` safely and update the agent in all three cases as if it had been started with the new setting.
* Overwrite the `cloud setting` safely and update the agent in all three cases as if it had been started with the new setting.

As well as the internal variables there is the `NETDATA_REGISTRY_CLOUD_BASE_URL` env var that needs to be updated, and it needs to propagate correctly to any scripts that are spawned that use it (such as the alarm notify script). @mfundul: how will a change in the env var be communicated to the spawn server?

Plan
----

For reading the config state from the agent:
* If netdata is running then use the clitool to read the config value (cases 1 + 2).
* If netdata is not running then use `netdata -W get` to parse the config correctly.

For writing the config state into the agent:
* Rewrite the config file so that any non-comment line that defines the setting becomes a comment.
* Add a new entry at the end of the target section that defines the setting.
* If netdata is running then use a new cli command to reload, needs to check which value is being updated and propagate appropriately (e.g. update env vars)

Notes:
* We can't rely on `$NETDATA_USER_CONFIG_DIR` being set when the script runs so we need to interface to the autotools substitutions to get the location.

**Comment by amoss** [comment]
Ah, so unfortunately `netdata -W get` does not retrieve the defaults as they are unknown. We need to move all the defaults to a sane place instead of scattering them over many code paths. So if both checks fail then there will be a hardcoded "default default" in the claiming script for both values.

**Comment by amoss** [comment]
> I agree with the proposal to do this in `netdatacli`. It's the right way to do it.
> 
> One note, however:
> 
> Re: defaults, we cannot trust the agent with any default, we'll be passing the URL as part of the claiming script invocation (this is to support people that may use on-prem, we may move the URL to another location at some point and older agents being installed, e.g. as part of a VM image or container image shouldn't need to be updated just for this) etc. So `netdatacli` should accept the cloud base url as part of its parameters and apply it when called from the claiming script. @amoss

I've finished the part that handles reading config from the agent, it works like this:
* The default value of the cloud base url is read from the agent (to handle cases where the command line argument is missing).
* The default is overwritten by the `-url` switch that is always displayed on the cloud claiming instructions.

The next step will overwrite the agent configuration with the url used, in the event that the `-url` was missing this will be a no-op and in the case that it was supplied it will guarantee that the cloud supplied url is used / stored.

**Comment by amoss** [comment]
> By using `netdatacli` you can consult the netdata agent as the single source of truth, getting rid of all the above problems by taking advantage of its integrated configuration parser. Moreover, the netdata agent is already capable of creating a configuration file dump when asked.

This is partly true - the generated configuration is not pristine as it does not preserve ordering or comments. Overwriting the user configuration with this generated output would be a massive UX problem.

Here is how I propose to  handle the configuration updating:
* If we find an uncommented line within the relevant section that is a valid configuration line for the setting being modified...
* Then it will be converted into a comment and preserved.
* A new line will be added at the end of the section with the fresh setting.

This should preserve the user supplied (and owned) config file as much as possible, while addressing the requirements in the issue.

**Comment by mfundul** [comment]
As long as we add parameters to existing scripts such as `alarm-notify.sh`, that set the netdata cloud URL, then the spawn server can receive those parameters as a string and should work fine.

**Comment by mfundul** [comment]
Fixed by https://github.com/netdata/netdata/pull/8843
