### ISSUE TITLE
Mismatch of file permissions between spec file and installer

### ISSUE THREAD

**Issue by jorti** [netdata/netdata#8673]
##### Bug report summary
For the external plugins that require additional privileges, there is a mismatch of the file capabilities and permissions in the spec file and what the installer configures:
 
```
# netdata.spec.in
%caps(cap_dac_read_search,cap_sys_ptrace=ep) %attr(0750,root,netdata) %{_libexecdir}/%{name}/plugins.d/apps.plugin
%caps(cap_setuid=ep) %attr(4750,root,netdata) %{_libexecdir}/%{name}/plugins.d/cgroup-network
%caps(cap_setuid=ep) %attr(4750,root,netdata) %{_libexecdir}/%{name}/plugins.d/perf.plugin
%caps(cap_setuid=ep) %attr(4750,root,netdata) %{_libexecdir}/%{name}/plugins.d/slabinfo.plugin
%caps(cap_setuid=ep) %attr(4750,root,netdata) %{_libexecdir}/%{name}/plugins.d/freeipmi.plugin
```

```
# netdata-installer.sh
/usr/libexec/netdata/plugins.d/apps.plugin = cap_dac_read_search,cap_sys_ptrace+ep (root:netdata 0750)
/usr/libexec/netdata/plugins.d/cgroup-network (root:netdata 4750)
/usr/libexec/netdata/plugins.d/perf.plugin (root:netdata 4750)
/usr/libexec/netdata/plugins.d/slabinfo.plugin (root:netdata 4750)
/usr/libexec/netdata/plugins.d/freeipmi.plugin (root:netdata 4750)
```

##### OS / Environment
```
/etc/fedora-release:Fedora release 32 (Thirty Two)
/etc/os-release:NAME=Fedora
/etc/os-release:VERSION="32 (Workstation Edition)"
/etc/os-release:ID=fedora
/etc/os-release:VERSION_ID=32
/etc/os-release:VERSION_CODENAME=""
/etc/os-release:PLATFORM_ID="platform:f32"
/etc/os-release:PRETTY_NAME="Fedora 32 (Workstation Edition)"
/etc/os-release:ANSI_COLOR="0;34"
/etc/os-release:LOGO=fedora-logo-icon
/etc/os-release:CPE_NAME="cpe:/o:fedoraproject:fedora:32"
/etc/os-release:HOME_URL="https://fedoraproject.org/"
/etc/os-release:DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
/etc/os-release:SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
/etc/os-release:BUG_REPORT_URL="https://bugzilla.redhat.com/"
/etc/os-release:REDHAT_BUGZILLA_PRODUCT="Fedora"
/etc/os-release:REDHAT_BUGZILLA_PRODUCT_VERSION=32
/etc/os-release:REDHAT_SUPPORT_PRODUCT="Fedora"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION=32
/etc/os-release:PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
/etc/os-release:VARIANT="Workstation Edition"
/etc/os-release:VARIANT_ID=workstation
/etc/redhat-release:Fedora release 32 (Thirty Two)
/etc/system-release:Fedora release 32 (Thirty Two)
```

##### Netdata version
netdata v1.21.0
 

##### Component Name
packaging

##### Steps To Reproduce
1. Install netdata with netdata-installer.sh
2. Compare the permissions of the binaries at `/usr/libexec/netdata/plugins.d/` with what is defined in netdata.spec.in

##### Expected behavior
Some questions:

- Why the spec file sets CAP_SETUID and the installer does not? This looks clearly like a bug and both should be in sync.
- What capabilities do these binaries really need? For each one of them, it must be clearly defined what they need, for example, UID=0 and a list of capabilities. They should be installed with the minimum required privileges.

**Comment by Ferroin** [comment]
Of the plugins in question:

* `apps.plugin` actually does need those exact capabilities in a vast majority of cases.
* None of the plugins need `CAP_SETUID`.
* The `cgroup-network` plugin needs to be SUID root because it needs to run other commands as root that are not themselves SUID root (and cannot be made SUID root because they are shell scripts).
* `perf.plugin` can probably get by with `CAP_PERFMON`.
* `slabinfo.plugin` can probably get by with `CAP_DAC_READ_SEARCH` instead of being SUID root (it needs read access to `/proc/slabinfo`, which is only readable by the root user, but CAP_DAC_READ_SEARCH should bypass that).
* `freipmi.plugin` needs to be SUID root because it needs to be able to run other commands as root that are not SUID root themselves.

There are actually a handful of other plugins I need to look into.
