### ISSUE TITLE
Deafult sort for dash.html

### ISSUE THREAD

**Issue by ScottAtConvesio** [netdata/netdata#8749]
I note the storage of the nodes in browser local storage. For my use case it would be better to have the nodes auto-sort alphabetically, as the menu on the main dashboard does. Is this easily modified so each user does not have to go through the tedious process of manually sorting 30+ nodes?

**Comment by ilyam8** [comment]
@tnyeanderson 👋 is it dash.html responsibility to sort things or not?

**Comment by tnyeanderson** [comment]
Hmm... I actually think this is a great idea! Right now there is no sorting done at all, and I think it should in fact be alphabetically sorted by default. What does everyone else think? Is there any sanity regarding the order in which the Netdata API returns the nodes? If so, maybe this should be an option instead of default. I'm open for whatever the community and the Netdata team think is best :)

**Comment by ilyam8** [comment]
Well, `dash.html` is your thing @tnyeanderson, i agree with you it should be alphabetically sorted by default too. I suggest to make it default and not an option. We will return to this question if there will be requests.

**Comment by ilyam8** [comment]
> Is there any sanity regarding the order in which the Netdata API returns the nodes?

I think it is unlikely. @thiagoftsm ?

**Comment by thiagoftsm** [comment]
> > Is there any sanity regarding the order in which the Netdata API returns the nodes?
> 
> I think it is unlikely. @thiagoftsm ?

Hello  everybody,

You are right @ilyam8 ! The nodes are not sorted, they are returning according the order they were registered.

Best regards!

**Comment by tnyeanderson** [comment]
This is implemented in #8762 . Thanks for the suggestion @warp10host !
