### ISSUE TITLE
Netdata API swagger files are missing definition for `alarms_values` model

### ISSUE THREAD

**Issue by dpsy4** [netdata/netdata#8816]
##### Bug report summary

The API swagger documents (`.yml` and `.json`) reference `#/components/schemas/alarms_values` as the return type for `GET /alarms_values` route. However, this data type is not defined under the `components` section of the swagger files.

##### OS / Environment

```
Darwin 172-18-26-54.vpn.dejero.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
ProductName:	Mac OS X
ProductVersion:	10.15.3
BuildVersion:	19D76
```

##### Netdata version
netdata v1.20.0

##### Component Name

web/api

##### Steps To Reproduce

I found this issue while trying to generate a REST client for the API using the provided swagger file. However, it is not necessary to do so to verify this issue.
 
1. Note that the swagger definiton for `GET /alarms_values` returns a `200` with a body of `#/components/schemas/alarms_values`
2. Check the `components/schemas` portion of the file for a matching component.

This can also be verified by:
1. Navigating to https://apitools.dev/swagger-parser/online/
2. Entering `https://raw.githubusercontent.com/netdata/netdata/master/web/api/netdata-swagger.yaml` as the swagger file
3. Note the validation errors that are returned.

##### Expected behavior

There should be a matching object defined for `#/components/schemas/alarms_values`.

**Comment by amoss** [comment]
@thiagoftsm Please check if this is still a problem and then fix / close it.

**Comment by thiagoftsm** [comment]
Hi @dpsy4 and @amoss ,

I observed that our `netdata-swagger.yaml` has the definition for the object:

https://github.com/netdata/netdata/blob/4a4696e091cdc4deb8f482b3f837153a9c666d33/web/api/netdata-swagger.yaml#L1547

I also used the [link](https://apitools.dev/swagger-parser/online/) you gave us with the URL `https://raw.githubusercontent.com/netdata/netdata/master/web/api/netdata-swagger.yaml` and the final result looks like a successful result for me:

![chart32](https://user-images.githubusercontent.com/49162938/89736369-6eda5100-da58-11ea-8890-6ebcf973a32f.png)

I think the problem was fixed considering the links and tests I made, so I am closing this issue, if I am wrong, please, reopen it and give us additional information for I fix this during the week.

Best regards!
