### ISSUE TITLE
Netdata health disregards settings

### ISSUE THREAD

**Issue by Pingger** [netdata/netdata#8877]
##### Bug report summary
When having multiple recursive alarms defined, some settings spill from one alarm to another like so:
![image](https://user-images.githubusercontent.com/4761298/80869310-0719aa80-8ca0-11ea-8e40-db18fa5671bf.png)
Additionally `units` is disregarded

##### OS / Environment

```
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"
```

##### Netdata version

 `netdata v1.21.1-120-nightly`

##### Component Name

`health.d`

##### Steps To Reproduce

The picture above results from the following settings:
```
template: monthly_limit
      on: net.net
families: *
    calc: 80*1024
   green: nan
     red: nan
   units: GB
   every: 1m
    info: Monthly Datacap
      to: silent
```
This bad behaviour can be seen in several alarms defined in this config.
The full .conf is attached. This specific alarm is at line 110.
[datalimit.conf.txt](https://github.com/netdata/netdata/files/4568155/datalimit.conf.txt)
File is placed at /etc/netdata/health.d/datalimit.conf (ans without .txt, but github refuses to accept file otherwise)

Yes, I have previously tried not setting `green `and `red `at all, or setting to `0`.

##### Expected behavior

This *photoshopped* image. So: `units`, `red` and `green` are respected
![image](https://user-images.githubusercontent.com/4761298/80869535-70e68400-8ca1-11ea-95cb-df2f9e13585e.png)

**Comment by thiagoftsm** [comment]
Hello @Pingger,

I was debugging now the bug you reported, and I verified that Netdata agent is doing what is expected, this means that the alarms are created independently and your description "some settings spill from one alarm to another" is not happening. You can confirm this accessing the URL `http://localhost:19999/api/v1/alarms?all`, on the other hand, I can confirm that our dashboard is not showing what is defined in the specified alarm. @jacekkolasa , please, get the example the @Pingger gave us https://github.com/netdata/netdata/files/4568155/datalimit.conf.txt and verify what is happening on the dashboard.

Now a note about the alarm you report, I verified that it gives to `calc:` a constant, was this alarm raised? 

Finally about the `green` and `red` to be `NAN`, this is their default value when a value is not given.

Best regards!

**Comment by Pingger** [comment]
The alarm was not raised.
The values of `green` and `red` are supposed to be `nan`, because it is just a constant used in several calculations, and no actual alarm should be raised. This idea was taken from the disks.conf, since my server provider has a monthly datacap.

Very interestingly, the badge actually changed over night and is now proplery showing GB instead of kbits/s. The green and read threshold are still being shown
![image](https://user-images.githubusercontent.com/4761298/80920095-e3bd3100-8d6d-11ea-9562-8de70eaa38c8.png)

The json from the api lists the following entry:
```
		"net.eth0.monthly_limit": {
			"id": 1584896641,
			"name": "monthly_limit",
			"chart": "net.eth0",
			"family": "eth0",
			"active": true,
			"disabled": false,
			"silenced": false,
			"exec": "/usr/libexec/netdata/plugins.d/alarm-notify.sh",
			"recipient": "silent",
			"source": "147@/etc/netdata/health.d/datalimit.conf",
			"units": "GB",
			"info": "Monthly Datacap",
			"status": "UNDEFINED",
			"last_status_change": 1588487252,
			"last_updated": 1588523852,
			"next_update": 1588523912,
			"update_every": 60,
			"delay_up_duration": 0,
			"delay_down_duration": 0,
			"delay_max_duration": 0,
			"delay_multiplier": 1.000000,
			"delay": 0,
			"delay_up_to_timestamp": 1588487252,
			"warn_repeat_every": "0",
			"crit_repeat_every": "0",
			"value_string": "81920 GB",
			"last_repeat": "0",
			"calc":"80*1024",
			"calc_parsed":"(80 * 1024)",
			"green":null,
			"red":null,
			"value":81920
		},
```

**Comment by thiagoftsm** [comment]
I am happy the alarm was not raised. :)
I had the same `JSON` you are having. 
It is possible the browser had problem to render the object or the problem was fixed during an update. Does your machine update Netdata every night?

**Comment by Pingger** [comment]
Don't know if every night, but auto updates are enabled.
But as I have said, the `red` and `green` value are still displayed and they also still show the wrong units. (as can be seen from the screenshot in my previous post).

**Comment by Pingger** [comment]
Well now I noticed, that another alarm is having a the same issue, but it is actually **raised**. The weird thing is, that it is not repeated. But the dashboard has it permanently marked as raised and the badge is constantly red.

![image](https://user-images.githubusercontent.com/4761298/80925173-ffd0ca80-8d8d-11ea-99d2-07ed80e4c9bc.png)
the config for that alarm is:
[datalimit.conf.txt](https://github.com/netdata/netdata/files/4571583/datalimit.conf.txt)
```
template: datacap_used_up_in
families: *
      on: net.net
    calc: ($monthly_limit-$total_used_30d)/$datacap_use_rate
   every: 5m
   units: hours
     red: 720
   green: 1440
  repeat: 1h
    warn: ($this>0||$this<0) && ($this < $green)
    crit: ($this>0||$this<0) && ($this < $red)
    info: The time until the datacap is used up
      to: sysadmin
```
`monthly_limit` is in GB
`total_used_30d` is in GB
`datacap_use_rate` is in GB/h
720h == 30 days
1440h == 60 days

**Comment by thiagoftsm** [comment]
> But as I have said, the `red` and `green` value are still displayed and they also still show the wrong units. (as can be seen from the screenshot in my previous post).

As you could see in your alarm, the `green` and `red` are NULL, so somehow the  dashboard is using a wrong value to show the alarms.

**Comment by thiagoftsm** [comment]
About the missing repeat notification, as you can see in our [documentation](https://learn.netdata.cloud/docs/agent/health/reference/#alarm-line-repeat) you only specified the duration without to specify `warning` and `critical`, a line with the correct format would be like this

```
repeat: warning 30s critical 60s
```

Another possibility to have the default repeat enabled is to have the following variables in your `netdata.conf`

```
[health]
    enabled = yes
    default repeat warning = 4s
    default repeat critical = 2s
```

Please, could you confirm that you configured these parameters?

Best regards!

**Comment by Pingger** [comment]
changed the `repeat` to `repeat: critical 1m` and am now getting the warning every minute. So the `red` and `green` values configured for this alarm are ignored and the entries of another alarm are used.
```
template: datacap_used_up_in
families: *
      on: net.net
    calc: ($monthly_limit-$total_used_30d)/$datacap_use_rate
   every: 5m
   units: hours
     red: 720
   green: 1440
  repeat: critical 1m
    warn: ($this>0||$this<0) && ($this < $green)
    crit: ($this>0||$this<0) && ($this < $red)
    info: The time until the datacap is used up
      to: sysadmin
```

**Comment by thiagoftsm** [comment]
Hi @Pingger ,

I was debugging now your alarms again, and I probably found the problem, but I will need an additional information from you to confirm. Firstly I will described what I did:

1 - I ran the request `https://localhost:19999/api/v1/alarms?all` to confirm that the alarms were parsed correctly

![err51](https://user-images.githubusercontent.com/49162938/81000278-93110b00-8e35-11ea-82a5-412baa04450b.png)

After to compare all alarms, I verified that Netdata is not doing a wrong parse.

2 - After this I ran another request `https://localhost:19999/api/v1/alarm_variables?chart=net.wlan0` and I got this:

![err52](https://user-images.githubusercontent.com/49162938/81000717-34985c80-8e36-11ea-87d8-4d00cd3e0d70.png)

I verified that in my case Netdata is returning `NULL` for a variables used to do math. According to the alarm, Netdata should select values from the last 30 days to set this variable.

@Pingger firstly a question for you, what are the specified values for `memory mode`, `page cache size` and `dbengine disk space`?

@mfundul and @stelfrag , when Netdata selects a sum for value in the last 30d each 5 minutes, should we not sum the current values?

**Comment by Pingger** [comment]
```
	memory mode = dbengine
	page cache size = 32
	dbengine disk space = 4096
```
Contents of the cache folder. Enough data for a bit more than 1 month
![image](https://user-images.githubusercontent.com/4761298/81002406-77affb00-8e49-11ea-8288-6e7227856d22.png)
The alarm_variables:
![image](https://user-images.githubusercontent.com/4761298/81002624-d8d7ce80-8e49-11ea-82f7-ec33e77e180d.png)
The alarm itsself, the value isself is even higher than `red` and `green` and the formulas and for `warn` and `crit` state to only elevate, when the value is smaller (and not close to 0/nan). It also displays the current status as `CRITICAL`:
![image](https://user-images.githubusercontent.com/4761298/81002739-0cb2f400-8e4a-11ea-80d0-934d75cd7b3f.png)

**Comment by thiagoftsm** [comment]
Hi @Pingger ,

Thank you for all the data.
Now about the `units`, when I got the [file](https://github.com/netdata/netdata/files/4571583/datalimit.conf.txt) you shared with us I observed that the cited alarm has `hours` as units:

```
template: datacap_used_up_in
families: *
      on: net.net
    calc: ($monthly_limit-$total_used_30d)/$datacap_use_rate
   every: 5m
   units: hours
     red: 720
   green: 1440
  repeat: 1h
    warn: ($this>0||$this<0) && ($this < $green)
    crit: ($this>0||$this<0) && ($this < $red)
    info: The time until the datacap is used up
      to: sysadmin
```

Did you give us a different file? As you can see the alarm I copied here has all values correctly set on your last image.

Best regards!

**Comment by Pingger** [comment]
No I gave you the real file.
The only changes I made since then are
line 177 in which I fixed the `repeat` setting to `repeat: critical 1m`
and line 181 where I made the alarm silent for the moment `to: silent`
This results in this file, which is currently in use. 
[datalimit.conf.txt](https://github.com/netdata/netdata/files/4578335/datalimit.conf.txt)
The `hours` unit has been copied from the disks.conf since I noticed, that it get properly converted to days + hours visually.

> Now about the units, when I got the file you shared with us I observed that the cited alarm has hours as units:

Yes that is what is supposed to be and how the **value** is displayed. The `red` and `green`. that displayed in the dashboard are not only not existing in that alarm, but also display completly different units, than the alarm has.

The dashboard still looks like this:
![image](https://user-images.githubusercontent.com/4761298/81024758-b9a26680-8e74-11ea-9a61-9a9be6b6f187.png)

> As you can see the alarm I copied here has all values correctly set on your last image.

No it has not! The alarm is still raised as `CRITICAL` while it shouldn't be. If you'd looked closely at the image you would have seen, that the values displayed are contradicting each other. This makes absolutely no fucking sense: (same screenshot, now with big red arrows )
![image](https://user-images.githubusercontent.com/4761298/81024925-3a616280-8e75-11ea-8326-f4ddc679246d.png)

I also think I found the culprit for the issue:
This screenshot (also from before) shows only a single `green` and a single `red` parameter for all alarms. which is not correct, since not all alarms share the same `green` and `red` values.
![image](https://user-images.githubusercontent.com/4761298/81025068-b3f95080-8e75-11ea-999f-b08dc49ea987.png)


**I am willing to grant access to the server for further investigation**, but for obvious reasons won't drop the credentials publicly and will be monitoring what will be performed on the server.
I don't see, why I should send you different data than I use? I really would like to have that bug fixed and providing you with wrong data would be counter-productive.

So again, a summary of everything, that is currently wrong in this file:
**downloaded_used_30d** shows `green` and `red,` while not set at all with wrong units:
![image](https://user-images.githubusercontent.com/4761298/81025355-b4461b80-8e76-11ea-913d-e31ea459e7ec.png)
**uploaded_used_30d** shows `green` and `red,` while not set at all with wrong units:
![image](https://user-images.githubusercontent.com/4761298/81025410-d475da80-8e76-11ea-8f1d-bd556ce1e654.png)
**total_used_30d** shows `green` and `red,` while set to entirely different values (`75` and `90` (%)) AND with wrong units (should be displayed as GB):
![image](https://user-images.githubusercontent.com/4761298/81025423-e5265080-8e76-11ea-8a36-407a165e80a4.png)
**downloaded_used_last_month** shows `green` and `red,` while not set at all with wrong units (no value, because not enough data as expected):
![image](https://user-images.githubusercontent.com/4761298/81025470-1141d180-8e77-11ea-8abc-7232c8765782.png)
**uploaded_used_last_month** shows `green` and `red,` while not set at all with wrong units (no value, because not enough data as expected):
![image](https://user-images.githubusercontent.com/4761298/81025518-346c8100-8e77-11ea-89bd-de11eae0b374.png)
**total_used_last_month** shows `green` and `red,` while set to entirely different values (`75` and `90` (%)):
![image](https://user-images.githubusercontent.com/4761298/81025537-43533380-8e77-11ea-8ee4-41ad5dabb0a1.png)
**monthly_limit** shows `green` and `red,` while not set at all with wrong units:
![image](https://user-images.githubusercontent.com/4761298/81025585-6251c580-8e77-11ea-9078-c575e90580a2.png)
**datacap_use_rate** shows `green` and `red,` while not set at all with slightly wrong units (kbit/s can be converted to GB/h, but still probably wrong units as it would be a very stupid conversion and the parameters are not configured at all for this) :
![image](https://user-images.githubusercontent.com/4761298/81025592-68e03d00-8e77-11ea-8bc2-68feb101dae1.png)
**datacap_used_up_in** shows `green` and `red,` while set to entirely different values AND wrong units:
![image](https://user-images.githubusercontent.com/4761298/81025673-acd34200-8e77-11ea-9474-915454e58af2.png)

**Comment by thiagoftsm** [comment]
Hi @Pingger ,

I am accessing your dashboard now and I could confirm some of the following problems:

#### Dashboard error
> downloaded_used_30d shows green and red, while not set at all with wrong units:

Case you access `https://netdata.iskariot.info/api/v1/alarms?all` and see the alarm, you will see that it is defined as `NULL`, so Netdata does not use to raise alarms, but there is a bug on our dashboard ( @jacekkolasa, please, take a look on it ).

The same thing happens with all the other charts that has `green` and `red` set on dashboard, but does not have it defined on the alarms.

#### Error with values

By steps, I did not use the dashboard, because as I said, there is a bug there and the values you are seeing for `red` and `green` are  not helping us to understand the problem. So I requested for your server the chart the variables that it is using to raise alarms:

![err54](https://user-images.githubusercontent.com/49162938/81099935-32e49c80-8efb-11ea-9d5d-b4c13578cf88.png)

I also requested with the smallest delay possible ( the time to change from one tab to other) the alarms raised:

![err53](https://user-images.githubusercontent.com/49162938/81100090-74754780-8efb-11ea-8207-855acfa0d30d.png)

Finally I copied all the values that I had on my screen to `bc` and I did some math to confirm that the values were correct:

![err55](https://user-images.githubusercontent.com/49162938/81100255-c1f1b480-8efb-11ea-9da0-c83045b41395.png)

The conclusions that I got from these values:

1 - Dashboard is really wrong, I apologize you for the bug, and I am sure that our front end developer (@jacekkolasa ) will work to fix this when he has a time.
2 - With the values that I got from your server and after to do some math, the values that we have now do not look wrong.
3 - Is there a possibility to have an error when Netdata is translating from one dimension (KB) to other (GB)? Or the used formulas to be somehow inaccurate? Both cases can be true, and I will do math chart by chart to confirm this.

I gave this short answer for you, because I did not want let you waiting the debug, mainly considering that I also have other things to do, but stay sure that I will test the `3` in the next 24 hours. Please, keep this site accessible for I have condition to do the last steps.

Best regards!

**Comment by thiagoftsm** [comment]
Hi @Pingger ,

Firstly I apologize for the delay, but I had busy schedule these days.
I ran the first part of the debug I wanted to do. To study the alarms and the expected results, firstly I ran three queries on your server:

```
curl -o data.txt "https://netdata.iskariot.info/api/v1/data?chart=net.eth0&after=-17280"
curl -o alarm_variables.txt "https://netdata.iskariot.info/api/v1/alarm_variables?chart=net.eth0"
curl -o alarms.txt "https://netdata.iskariot.info/api/v1/alarms?all"
``` 

After this I imported the data from `data.txt` to a PostgreSQL 12.2 server to have conditions to do the math faster and I got the following results:

| variable                  |   expected |   PostgreSQL  table  |
| ------------------------ | ------------- | -------------------------- |
|"downloaded_average"|  4512.70500|  4510.36708 |
|"uploaded_average"       | 4536.26989| 4407.914692892561 |
|"total_average"           | 9048.97489| 8918.28177553719 |
|"downloaded_average_3h"	  | 5154.75755| 5153.794451096705 | 
|"uploaded_average_3h"     |19891.76900| 19873.075001827878 |
|"total_average_3h"        |25046.52655| 25026.869452924584 |

As you can see we have divergence between the results that Netdata collects and the result that PostgreSQL reports. This is somehow expected, because Netdata uses truncated value, on the other hand, this can be a source of problem for the error you are reporting.

During my initial tests, I was able to only test these 6 charts, because I did not get yet from your server a whole month of data, and I do not have a sample like this on my computers. 

Please, answer the next question using UTC for we synchronize correctly. Is there a better time for I collect 30 days of data from your server?

Or could you get these days doing a request for `https://netdata.iskariot.info/api/v1/data?chart=net.eth0` and attaching the result in the answer?

I already have the whole structure to do the debug everything, I am only missing the data now.

I sincerely apologize again for the delay, but we are having busy days.

Best regards!

**Comment by Pingger** [comment]
Hi,

> Please, answer the next question using UTC for we synchronize correctly. Is there a better time for I collect 30 days of data from your server?

I'm not quite sure, what you mean with this question. My guess you'd like to know a time, when to best download data from the server: anytime you want, it is very unlikely you exceed 10GBit/s and even then, you would be limited on a fairuse system, that prevents server overloading by small groups of computers.

> Or could you get these days doing a request for `https://netdata.iskariot.info/api/v1/data?chart=net.eth0` and attaching the result in the answer?

You should be able to run this yourself, but there you go [data.json.txt](https://github.com/netdata/netdata/files/4601481/data.json.txt)

> I sincerely apologize again for the delay, but we are having busy days.

No worries. 

> As you can see we have divergence between the results that Netdata collects and the result that PostgreSQL reports. This is somehow expected, because Netdata uses truncated value, on the other hand, this can be a source of problem for the error you are reporting.

To me this looks like too small of a divergence to cause an alarm to be triggered, when that value is reported at 5000 (or greater) and the condition to alert is **be lower than 1440**. I mean that is quite a stretch.
Also on those 6 variables you mentioned everything seems fine. The limits are correct and trigger correctly. The display of the `red` and `green` value also seem to be correct.

Greetings.

**Comment by thiagoftsm** [comment]
Hi @Pingger ,

I could get the data and I already could debug 11 alarms, there are few remaining, but I won't finish today, because it is too late in my timezone, tomorrow this will be the first thing that I will do.

Best regards!

**Comment by thiagoftsm** [comment]
Hi @Pingger ,

I finished the work with the alarms, and once again I used the PostgreSQL to import the data and do math. I got data from the interval `2020-04-09 23:06:20` to `2020-05-09 23:06:15` using the queries

```
curl -o data.txt "https://netdata.iskariot.info/api/v1/data?chart=net.eth0&after=-2592000"
curl -o alarm_variables.txt "https://netdata.iskariot.info/api/v1/alarm_variables?chart=net.eth0"
curl -o alarms.txt "https://netdata.iskariot.info/api/v1/alarms?all"
```

After this I created a very simple table 

```
CREATE TABLE debug_logs(id SERIAL, event_time timestamp, received float8, sent float8);
``` 

and I imported the data. After this I ran the following queries on the database:

```
# SELECT avg(received) as downloaded_average, -avg(sent) as uploaded_average, avg(received) -avg(sent) as total_average FROM debug_logs where event_time between to_timestamp(1589065575.0 - 600.0) AND to_timestamp(1589065575.0);
# SELECT avg(received) as downloaded_average_3h, -avg(sent) as uploaded_average_3h, avg(received) -avg(sent) as total_average_3h, ((avg(received) -avg(sent))/8/1024/1024)*60*60 as datacap_use_rate FROM debug_logs where event_time between to_timestamp(1589065575.0 - 10800.0) AND to_timestamp(1589065575.0);
# SELECT 80*1024 as monthly_limit, sum(received)/8/1024/1024 as downloaded_used_30d, -sum(sent)/8/1024/1024 as uploaded_used_30d, sum(received)/8/1024/1024  - sum(sent)/8/1024/1024 as total_used_30d FROM debug_logs;
# SELECT sum(received)/8/1024/1024 as downloaded_used_30d, -sum(sent)/8/1024/1024 as uploaded_used_30d, sum(received)/8/1024/1024  - sum(sent)/8/1024/1024 as total_used_30d FROM debug_logs where event_time between '2020-04-09 23:59:59' and '2020-05-08 00:00:00';
# SELECT (81920 - 358.2013314006006)/0.42047286056115213;
```

After to run the queries, I created the next table to compare the data:

| Variable                     |    Netdata |  SQL Query |    
| -------------------------- | ------------- | ---------------- |
|"downloaded_average" | 229.31702 | 228.0901645454545  |
|"uploaded_average" | 2027.91264 | 2014.7167423140495|
|"total_average" | 2257.22966 | 2242.806906859504|
|"downloaded_average_3h" | 182.22753 | 182.1544870615456|
|"uploaded_average_3h" | 797.79300 | 797.618291240167|
|"total_average_3h" | 980.02052 | 979.7727783017126|
|"monthly_limit" | 81920.00000 | 81920|
|"downloaded_used_30d" | 102.65785 | 102.65770300982474 |
|"uploaded_used_30d" | 367.63272 | 367.6286285612485 |
|"total_used_30d" | 470.29090 |  470.2863315710732 |
|"downloaded_used_last_month" | 88.34992 | 87.36000500878964 |
|"uploaded_used_last_month" | 275.09801 | 270.8413263918125 |
| "total_used_last_month" | 363.44793 | 358.20133140060216 |
|"datacap_use_rate" | 0.42053 | 0.42047286056115213 |
"datacap_used_up_in" |  193683.67221 | 193976.36879523959496669 |

I need to say something important here, for I calculate the correct data for the aligned alarms, I would need to do another request to your server to get more one day, instead to do another query, I decided to calculate for 29 days, because I was expecting the order value do not change and as you can see the results show us that this happens. Considering this, we can see that the results obtained for the alarm variables when calculated on PostgreSQL are almost identical to data calculated on Netdata.

After the conclusion about the results obtained with the Math, I will describe possible problems with some alarms:

- `downloaded_used_30d`, `uploaded_used_30d`, `downloaded_used_last_month`, `uploaded_used_last_month`  : the `crit` and `warn` are using values for `red` and `green` to raise an alarm, but when you see the values for `red` and `green` they are defined as `NULL`:

```
 "green":null,
 "red":null,
```

- `datacap_use_rate`: Here you do not have errors, unless you wanted to calculate bytes instead bits. To generate this data you get the `total_average_3h` and divide for `8/1024/1024/` and after this you multiply for `60*60`.  The result is used to calculate `datacap_used_up_in`. The final result here is given in `bits * hour`. For the majority of the cases I tested, this value was smaller than 1.

- `datacap_used_up_in`. - `monthly_limit` is the constant 81920, `total_used_30d` is given in `bits`. Here we have two problems case I understood correctly what you wanted to do:
   -   When we divide `bits` by `bits hour`, the unit is `1/hour` instead `hour`.
   -   Everytime that `datacap_use_rate` is smaller than 1, the final result will increase instead decrease. And as you can see in the table, we have a value bigger than the defined `red` and `green`.

Finally it looks like that Netdata is doing all the steps correctly, but some alarms does not have `green` and `red` values defined. Case I missed something, please, let me know.

**Comment by Pingger** [comment]
> * `downloaded_used_30d`, `uploaded_used_30d`, `downloaded_used_last_month`, `uploaded_used_last_month`  : the `crit` and `warn` are using values for `red` and `green` to raise an alarm, but when you see the values for `red` and `green` they are defined as `NULL`:
> 
> 
> ```
>  "green":null,
>  "red":null,
> ```

Fixed, I messed up some copy paste there.

> * `datacap_use_rate`: Here you do not have errors, unless you wanted to calculate bytes instead bits. To generate this data you get the `total_average_3h` and divide for `8/1024/1024/` and after this you multiply for `60*60`.  The result is used to calculate `datacap_used_up_in`. The final result here is given in `bits * hour`. For the majority of the cases I tested, this value was smaller than 1.

**No,** the final result given here is `Gibi Byte / hour`
To me the unit for `datacap_use_rate` should be `GB / hour`. I have `kbit/s` from `total_average_3h`. divding by 8 gives me `kbyte/s`, dividing by 1024 results in `MByte/s`, dividing again in `GByte/s`. now multiplying by 60 results in `GByte/minute`, multiplying again in `GByte/hour`. The server usually just uses about `0.5 - 1.0 GByte/hour` bandwidth.

> * `datacap_used_up_in`. - `monthly_limit` is the constant 81920, `total_used_30d` is given in `bits`. Here we have two problems case I understood correctly what you wanted to do:
>       
>   * When we divide `bits` by `bits hour`, the unit is `1/hour` instead `hour`.
>   * Everytime that `datacap_use_rate` is smaller than 1, the final result will increase instead decrease. And as you can see in the table, we have a value bigger than the defined `red` and `green`.
> 

monthly_limit is a constant with applied unit `GB`, so `81920 GB` (equivalent to `80 TB`). Substracting the already used up data (in my case less than `1024 GB`), results in `~79 TB`.
Now dividing the 79TB by the 1 GB/h
![image](https://user-images.githubusercontent.com/4761298/81510076-872eb880-930f-11ea-9e79-a9724d991791.png)
Which is greater than the `1440 hours` for the `green` and greater than the `720 hours` for the `red` value.
the `warn` equation checks if our `value` is **smaller** than the `green` value. According to common sense: `80896 < 1440 == FALSE`. 
same goes for `crit`
the `crit` equation checks if our `value` is **smaller** than the `red` value. According to common sense: `80896 < 720 == FALSE`. 
So, both `warn` and `crit` are `false`, why is the alarm raised?

**And Even if** the units didn't match up, this would be the full equation without units:
Having `81920 GB` data, of which `1024 GB` are already used. with (my server's current) network speed of `2400kbit/s`
![image](https://user-images.githubusercontent.com/4761298/81510507-703d9580-9312-11ea-90e4-59b365e43c2f.png)
As can be seen, that value is greater than the given limits of `720` and `1440` and an alarm should not be raised.

> 
> Finally it looks like that Netdata is doing all the steps correctly, but some alarms does not have `green` and `red` values defined. Case I missed something, please, let me know.

Yes, I somehow failed to add the `red` and `green` values to `downloaded_used_30d`, `uploaded_used_30d`, `downloaded_used_last_month` and `uploaded_used_last_month`, which has now been fixed. But even after adding these, all mentioned issues still persist.
And just in case, the resulting 
[datalimit.conf.txt](https://github.com/netdata/netdata/files/4606759/datalimit.conf.txt)

Greetings

**Comment by thiagoftsm** [comment]
> So, both warn and crit are false, why is the alarm raised?

You are right, I am sorry for this. You have 13 alarms testing `this > VALUE`, and somehow I assumed the last alarm followed the same comparison pattern but now I could see it is different.

I am running your alarms today on my environment, but I changed the time interval from hours and days to seconds and minutes respectively. Until now I did not receive any alarm, but I will be running these tests in the next hours. I will bring another update today yet.

Best regards!

**Comment by thiagoftsm** [comment]
@mfundul I ran during more than 8 hours the alarms after to change all `every` to be sure they would be raised during this interval, but this did not happen. What is the possibility of the pages not being read correctly from memory and Netdata is raising the last alarm of https://github.com/netdata/netdata/files/4606759/datalimit.conf.txt .? I do not think this can happen, but I would like to confirm.

@Pingger a last doubt for you, how did you install Netdata on this server? Did you use `kickstart` or debian packages?

**Comment by mfundul** [comment]
> 
> 
> @mfundul I ran during more than 8 hours the alarms after to change all `every` to be sure they would be raised during this interval, but this did not happen. What is the possibility of the pages not being read correctly from memory and Netdata is raising the last alarm of https://github.com/netdata/netdata/files/4606759/datalimit.conf.txt .? I do not think this can happen, but I would like to confirm.
> 

What pages are you talking about exactly? If you're talking about dbengine pages then this would only be relevant to the `lookup:` lines in the alarms. We can confirm what values the database returns by executing the data query. I'm not sure I understand your question.

**Comment by Pingger** [comment]
> @Pingger a last doubt for you, how did you install Netdata on this server? Did you use `kickstart` or debian packages?

using this exact command, run as root: `bash <(curl -Ss https://my-netdata.io/kickstart.sh) --disable-telemetry --auto-update --enable-ebpf`

**Comment by thiagoftsm** [comment]
> What pages are you talking about exactly? If you're talking about dbengine pages then this would only be relevant to the `lookup:` lines in the alarms. We can confirm what values the database returns by executing the data query. I'm not sure I understand your question.

I was talking about the dbengine page. I thought that probably during runtime we could have a problem, but after the last answer for @Pingger we can ignore this possibility. Thank you!

@prologic and @Ferroin , this is the second issue that we are having in the last weeks where users are installing Netdata with `kickstart.sh` and the alarms are raising false positives. The first user cleaned the database and everything worked for him, but in this case this would be very complicated, please, can you confirm that the libraries used to generate Netdata with `kickstart.sh` are the newest?

Best regards!

**Comment by prologic** [comment]
> @prologic and @Ferroin , this is the second issue that we are having in the last weeks where users are installing Netdata with kickstart.sh and the alarms are raising false positives. The first user cleaned the database and everything worked for him, but in this case this would be very complicated, please, can you confirm that the libraries used to generate Netdata with kickstart.sh are the newest?

`kickstart.sh` effectively builds from source and ensures all build dependencies exist on a user's system. What I _am not_ sure of however is whether we ensure they are up-to-date.

**Comment by prologic** [comment]
> What I am not sure of however is whether we ensure they are up-to-date.

But the `configure` script should be checking this right?

**Comment by jacekkolasa** [comment]
@thiagoftsm do you still think there is problem with Dashboard here? I'm not sure if i should spend time on this issue

**Comment by thiagoftsm** [comment]
No @jacekkolasa , I am thinking it is a problem related with the compilation process.
You do not need to spend a time here, I am trying to recreated the alarm situation, but I did not have success yet.
Thank you!

**Comment by prologic** [comment]
> No @jacekkolasa , I am thinking it is a problem related with the compilation process.

I'm actually really confused here. Can someone fill me in on a theory as to what's going on here? Alarms just don't suddenly start firing false positive and I find it hard to believe a compilation option would have affected this per se?

**Comment by Pingger** [comment]
Ok, interresting thing:
When the `value` of the time remaining is greater than `256000h`, the alarm stops being raised. The wrong value, that is displayed in the dashboard, is the value, that is used to determine if the alarm should be raised.
![Screen Shot 2020-05-21 at 12 42 05](https://user-images.githubusercontent.com/4761298/82551452-85ab8e80-9b60-11ea-86e9-f627d24db06a.png)

So the issue is not the dashboard displaying wrong information, but something else in the logic of parsing the config.

**Comment by Pingger** [comment]
Well, I just found this in the documentation (https://github.com/netdata/netdata/blob/master/health/REFERENCE.md):

> $green and $red the threshold defined in alarms (these are per chart - the charts inherits them from the the first alarm that defined them)

This information should be placed at the `red` and `green` property documentation and not somewhere miles below.

Closing this as it seems to be intended behaviour. 
Also after changing all alarms in the given file to not use `red` and `green`, the alarm now actually trigger when they are supposed to.
