### ISSUE TITLE
Metric "memory utilization time" - the amount of time the memory is busy with something? (Not the "#GB being used")

### ISSUE THREAD

**Issue by fzyzcjy** [netdata/netdata#8883]
##### Feature idea summary

When looking at disks, we have a `Disk Utilization Time (disk_util.sda)`, telling us `the amount of time the disk was busy with something`. Thus, I would appreciate it if we could have something similar for memories. For instance, "memory utilization time - the amount of time the memory is busy with something".

##### Expected behavior

See above.

Thanks very much!

**Comment by Ancairon** [comment]
@Ferroin I did some searching and that could be quite something because the way `proc_diskstats.c` handles the disk utilization time from what I see is: it calculates the busy time in ms so it can be used in the respective `.conf` file. The eqivalent .c file for ram (memory) doesn't use the same method and instead gives us `free`,`used`,`cached` and `buffers`. Would it be possible to implement the same thing as for disks? 

Also on here https://learn.netdata.cloud/docs/agent/collectors/proc.plugin on the netdata.conf section third line from the bottom says that it has the "ram" disk excluded. Would including it make it possible to make a metric in ms also for ram?

**Comment by Ferroin** [comment]
I'm curious what, exactly, you think 'memory busy time' should be.

'disk busy time' literally tracks the amount of time that the storage controller spends transferring data to and from a given disk. it's very well defined and trivial to measure.

There's not really any equivalent for RAM though. The only possibility I can think of is measuring time spent migrating pages between nodes on NUMA systems, but for that it arguably makes more sense to count pages migrated and track what node distance they were migrated from, not the total time spent migrating pages (because it's easier to track, easier to understand, and actually more useful than the time measurement).

As far as RAM disks, it makes zero sense to track 'busy time' for those, they run at memory speed and have zero functional access latency as a result (and they're only rarely used anymore).

**Comment by Ancairon** [comment]
Thats what I thought considering latency it didn't make sense... So this request is actually not possible to implement in the same way it is used in the disks.

**Comment by fzyzcjy** [comment]
@Ancairon @Ferroin Thanks very much! My naive thought (when creating this issue in May) is to look at memory bottlenecks. For instance, say I have lots of memory and lots of Redis instances (or Memcached), then is its performance bound by memory, or bound by CPU? i.e. maybe the memory is very busy and cannot do anything more but the CPU is idle, or the memory is free and sleeping while the CPU is busy.

**Comment by mfundul** [comment]
I wouldn't say it's impossible. I would even say it is in the roadmap to do something related to CPU IPC (instructions per cycle). This can depend on the CPU architecture, but the high level idea is that low IPC means you're hitting a memory bottleneck, whereas high IPC means you're hitting a CPU bottleneck. In any case, this is something more sophisticated than a simple disk utilization calculation.

**Comment by mfundul** [comment]
Found a related issue, there may be more: https://github.com/netdata/netdata/issues/3232

**Comment by fzyzcjy** [comment]
@mfundul Thanks very much! The IPC and the tool in that issue sound promising

**Comment by Ferroin** [comment]
Short-term, [pressure stall information](https://www.kernel.org/doc/html/latest/accounting/psi.html#:~:text=The%20psi%20feature%20identifies%20and,workloads%20or%20even%20entire%20systems.) seems to cover what you are interested in. On systems that actually have the required kernel options enabled (which I believe includes most major distros official kernels at this point) Netdata will automatically collect this data and present it near the top of the dashboard.

**Comment by fzyzcjy** [comment]
@Ferroin Thanks very much! I will have a look at it
