### ISSUE TITLE
DNT breaks chart loading

### ISSUE THREAD

**Issue by mwalbeck** [netdata/netdata#9036]
##### Bug report summary
When Do Not Track is enabled in your browser and Netdata is set to respect DNT, charts no longer load. It seems Netdata requests **/api/v1/registry?action=hello** every time you access the web interface. This request errors with a HTTP 400 when DNT is enabled, and causes an error in the JavaScript code, which I assume causes the charts to no longer load.

If DNT is disabled in the browser or Netdata is set to not respect DNT, then chart loading works as intended.

I should also note, I'm not trying to access or use any of the registry features.

Related to #7465

##### OS / Environment
Tested with Netdata running on Debian 10, installed with the kickstart.sh script.

Tested with Firefox 76 and Chromium 81.0.4044.138

##### Netdata version
v1.22.1-17-nightly
 
##### Steps To Reproduce
1. Enable Do Not Track in browser
2. Set **respect do not track policy** to yes in the web section found in netdata.conf
3. Load Netdata web interface

##### Expected behavior
Charts should load with DNT enabled.

**Comment by jacekkolasa** [comment]
Thanks @mwalbeck for detailed report! There was indeed a bug, the fix should go soon to Nightly build.

BTW DNT stops users from accessing Netdata Cloud, @cakrit @dim08 @manos-saratsis do we want to stick with that? It happens because `cloud-base-url` is not accessible in this case (registry call returns error). If you confirm that, maybe we should update `respect do not track` section in https://learn.netdata.cloud/docs/agent/web/server/#other-netdataconf-web-section-options so that is clear (CC @joelhans)

**Comment by cakrit** [comment]
We are making privacy policy and other changes to link usage of the cloud with acceptance of tracking. So yes, DNT should prevent users from accessing Netdata Cloud and the documentation should reflect that fact.

**Comment by jacekkolasa** [comment]
closing, the main problem has been fixed
