### ISSUE TITLE
FAILED not critical -> after installing using the official installation script

### ISSUE THREAD

**Issue by thoggs** [netdata/netdata#9077]
Hello,
After running the `netdata.io/kickstart.sh` installation script, at the end of the installation, you receive the following error:
**Note:** cronie is already installed
![Captura de Tela 2020-05-17 às 12 54 45](https://user-images.githubusercontent.com/43221193/82153620-f55b0a00-983e-11ea-8d4d-f8ac182ab102.png)

**Note 2:** installation made on a clean operating system, without any customization or any type of software that may interfere with the proper functioning of Netdata

**OS:** Clear Linux* OS v3110 (Server) - Kernel v5.6.13
**Netdata:** v1.22.1-48-nightly

**Comment by prologic** [comment]
@thoggs Hi 👋-- To be clear your issue is that we don't install the cron job for the `netdata-updater` on your system? If so this is a bit of a KP and we lack support for cronie, busybox's cron and maybe others (_those are just the ones I'm  aware of_).

**Comment by thoggs** [comment]
> Hi 👋-- To be clear your issue is that we don't install the cron job for the `netdata-updater` on your system? If so this is a bit of a KP and we lack support for cronie, busybox's cron and maybe others (_those are just the ones I'm aware of_).

I am happy for the work in progress; the Netdata development team is amazing.

**Comment by prologic** [comment]
> I am happy for the work in progress; the Netdata development team is amazing.

Thank you ! We appreciate the positive feedback. I will make sure we support more Corn schedulers. At least the two I mention. I also want support for busybox's userland myself.

**Comment by Ferroin** [comment]
This is potentially a bit more complicated than 'supportcronie and busybox crond' The issue isn't that we don't support them, it's that we don't support the approaches used by some distros that use them. _Most_ distros have `/etc/cron.daily` directories and provide default crontabs for whatever cron implementation you install through their PM that will execute the stuff in that directory on a daily basis. Some just don't, and some only do so for some cron implementations.

I can look at adding support for injecting a crontab directly on systems where we can do that and can't find `/etc/cron.daily`, and also at support for installing a systemd timer unit on systems that don't have cron but do have systemd., but there will always be some systems we can't support because we _really_ cannot go around modifying the system's master crontab or the root user's personal crontab.

**Comment by prologic** [comment]
> I can look at adding support for injecting a crontab directly on systems where we can do that and can't find /etc/cron.daily, and also at support for installing a systemd timer unit on systems that don't have cron but do have systemd., but there will always be some systems we can't support because we really cannot go around modifying the system's master crontab or the root user's personal crontab.

Let's do this please. Nice and simple and should be quite effective.

**Comment by Ferroin** [comment]
I've opened a draft PR (rather ironically it's #9577) with initial work on this. I should have it ready for review some time later this week (hopefully tomorrow, more realistically probably Thursday if we account for testing).
