### ISSUE TITLE
Remove nodes from netdata cloud

### ISSUE THREAD

**Issue by AndreasUfert** [netdata/netdata#9124]
##### Question summary

In an automated environment, adding nodes to netdata cloud is really simple: just run the claim script. I wonder whether there's a possibility to remove terminated nodes in a similar manner. Like if there's a "un-claim script" that removes the node from netdata cloud.

##### OS / Environment

Any. Ubuntu 18.04 in my case.

##### Component Name

netdata cloud

##### Expected results

remove nodes in a similar way like claiming them.

**Comment by vsc55** [comment]
Hi,
That same problem I have encountered.
The way I've fixed it is by removing the cloud node by hand.
And on the node, removed all the files in "/var/lib/netdata/cloud.d/" except cloud.conf

**Comment by manos-saratsis** [comment]
@AndreasUfert @vsc55 Thanks for using Netdata Cloud. We will soon ship a feature to unclaim nodes initially via running the claim script with certain parameters.

**Comment by adocampo** [comment]
Yes, I did a test with a wrong email account and I'm unable to remove the node from that account, I did moved the content of "/var/lib/netdata/cloud.d/" minus cloud.conf and tried to claim on the correct email account, but it didn't worked either and now I see as "UNREACHABLE" the node on the orioginal claimed netdata account, and I cannot do anything with this... :|
The error when trying to add this node to the correct account is: 
```
Failed to claim node with the following error message:"Unknown HTTP error message"
```

**Comment by manos-saratsis** [comment]
The unclaiming feature will be delayed by a month due to other priorities.

**Comment by manos-saratsis** [comment]
For Unclaiming users will have to wait a bit as we prioritized other cool feature and the work-around is sufficient for now.

**Comment by markkrj** [comment]
@manos-saratsis Wouldn't this issue stay open until "unclaiming" feature lands? Just for tracking and so people don't keep opening issues for a know problem. I was about to open an issue for this.
By the way, just out of curiosity, is there and ETA for this?

**Comment by RoberTo1111** [comment]
@manos-saratsis do you know when the unclaim function will be released?

**Comment by manos-saratsis** [comment]
Unfortunately this has been moved to Q1 22. Reopening this

**Comment by stevecharon** [comment]
Got stuck with this crap not being solved
How hard could it be to remove a dataset?
I clearly miss any insight on this project but it cant be that hard to figure out in two years

**Comment by sheldsdeac** [comment]
Any movement on this functionality?

**Comment by JfrAziz** [comment]
any update for this issue?

**Comment by apertureless** [comment]
I had around 15 Severs in netdata cloud. However the agent update did not work properly. And then I could not update the agents manually, because the "installation method" could not be determined. Even tho I just installed them over the curl script.

So I ended uninstalling and re-installing netdata on the servers.
Now I have duplicates in the UI, which are not reachable. And how can I remove them?!

**Comment by cakrit** [comment]
Since there hasn't been an update on this specific ticket for a while, let's summarize first the current situation:
 - The step to disconnect a node from the cloud is documented at https://learn.netdata.cloud/docs/agent/claim#remove-and-reconnect-a-node . It is simply an `rm` command, followed by a restart of the agent. One can put it in a script if needed.
 - A functionality deployed recently to the cloud allows the manual removal of obsolete (unreachable) nodes from the UI, one by one. We're working on allowing this to be done in bulk too. This is not a hard deletion from the backend (see next point). 
 - We will not implement a hard deletion from the cloud, except for nodes that remain unreachable for a long time (the current process requires 90 days). There are many reasons for this product decision and we can cover every use case without the need for a hard deletion from the UI, or via an `unclaim` script.
 - There's some work in progress to add an `unclaim` command, but its purpose would be to simplify the steps to disconnect and reconnect and reconnect a node, listed in https://learn.netdata.cloud/docs/agent/claim#remove-and-reconnect-a-node  To my knowledge, the effect would be essentially the same. 

Please let us know if (other than the bulk delete from the UI in the second bullet) there's something else that we have missed.

**Comment by ralphm** [comment]
As an additional update, we have since added bulk remove. I believe this ticket can be closed now.
