### ISSUE TITLE
Netdata crashes daily on my Arch Linux system. Is there a log file I can send you? I also need the uninstall instructions.

### ISSUE THREAD

**Issue by technsandiego01** [netdata/netdata#9232]

**Comment by yasharne** [comment]
Hi @technsandiego01 , 
you can read you configuration file using `http://YOUR_NETDATA_ADDRESS:19999/netdata.conf`, 
It is probably inside `/var/log/netdata/debug.log` or `/opt/netdata/var/log/netdata/debug.log`
You can also uninstall your netdata using the script located in `/usr/libexec/netdata/netdata-uninstaller.sh` or `/opt/netdata/usr/libexec/netdata/netdata-uninstaller.sh`

**Comment by underhood** [comment]
Hi @technsandiego01 it is sad to hear you have issues with netdata.
It would be great help if you could send us `debug.log` and `error.log` from your machine after the crash happens so that we can look into the issue and fix it. (@yasharne already gave you instructions on where to find those logs.)

Thank you

**Comment by underhood** [comment]
@technsandiego01 sad to hear you have issues with Netdata. Unfortunately without any additional details (logfiles), we are not able to identify the issue. Only way might be it being accidentally solved in new release based on another bug report/change.

I will close this issue as there is no response. Please feel free to reopen in case you have the logfiles or need help finding the logfiles.
