### ISSUE TITLE
Go web_log - bad req url

### ISSUE THREAD

**Issue by Jessimon** [netdata/netdata#9271]
##### Bug report summary
I use the web_log module of netdata to get metrics for my apache logs. I use the go version.For most logs this works as expected, but for some logs i see that the url is viewed as bad.

'http://cxgatesdev1inc.testabcd.be/cxContent/cxMain/vacanciesPublic.php?txtSearchTerm=0&chkFunctionGroups=0&selSearchCountry=0&selSearchRegion=0&thisPage=1&wpSite=&wpSiteID=11&wpHost=devlogin.hrlinkit.be&wpHostInc=cxportaldev.carerix.com&openApplPubID=0&lang=nl&mediumCode=web': bad req url
is an example.

I use up to date version of apache.
The logformat is:
LogFormat "%h %l %u %t \"%r\" %>s %O %I %D \"%{Referer}i\" \"%{User-Agent}i\"" netdata
mod_logio is enabled.

Could it be that the url is too long?

I did a debug with ./go.d.plugin -d -m web_log
Results are include.

##### OS / Environment
This happens on debian 10 as well as on Amazon linux.

##### Netdata version
netdata v1.22.1-190-nightly
 

##### Component Name
Go web_log

##### Expected behavior
As all the log are formatted the same i would expect that it would work for all the logs.

[Web_log-debug-output.txt](https://github.com/netdata/netdata/files/4729608/Web_log-debug-output.txt)

**Comment by ilyam8** [comment]
hi @Jessimon 

> Could it be that the url is too long?

No.

URL check method was

https://github.com/netdata/go.d.plugin/blob/b33118b931768edbb5803166905555576e4c17db/modules/weblog/logline.go#L492-L498

https://github.com/netdata/go.d.plugin/blob/b33118b931768edbb5803166905555576e4c17db/modules/weblog/logline.go#L500-L509

I changed it because of

https://github.com/netdata/go.d.plugin/issues/377

to

https://github.com/netdata/go.d.plugin/blob/e90c8f86724c1de1e10263512f288014aa744a44/modules/weblog/logline.go#L491-L497

But is seems it is still to restrictive

your case is GET and URL starts with `http://`

It seems taking all cases into account it is better to remove that check completely 🤔

**Comment by ilyam8** [comment]
ok

> %r: First line of request.

> For example, the format string "%m %U%q %H" will log the method, path, query-string, and protocol, resulting in exactly the same output as "%r".

> %U: The URL path requested, not including any query string.


From the internet

> The path refers to the exact location of a page, post, file, or other asset. It is often analogous to the underlying file structure of the website. The path resides after the hostname and is separated by “/” (forward slash).

I dont get why there is `http://...`

**Comment by Jessimon** [comment]
I tested with the python version of web_log and there all work fine.
As i understand it netdata recommends to use go in stead of python.

**Comment by ilyam8** [comment]
Yeah, it is better (performance, features). I will fix the _bug_. Will be fixed in the new version of go.d (next week).

**Comment by ilyam8** [comment]
> Will be fixed in the new version of go.d (next week).

fixe, but new version is not realeased. In a few days.
