### ISSUE TITLE
Unreachable in netdata cloud, and error shows required indendencies to enable netdata cloud

### ISSUE THREAD

**Issue by startryst** [netdata/netdata#9317]
`netdata v1.22.1-240-nightly`

it was fine couple of days ago and can report back to netdata cloud, but now it's unreachable on netdata cloud

and when I open the device netdata page, it shows below:
![image](https://user-images.githubusercontent.com/22472752/84350227-837ea200-abeb-11ea-9800-42ab07a7029f.jpeg)

but actually the json-devel and all dependencies already installed, I even run the one-line bash command to re-install netdata a few times.

**Comment by startryst** [comment]
```
uname -a
Linux box10 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by startryst** [comment]
when try to claim the node, get back to me below:
`This agent was built without the dependencies for Cloud and cannot be claimed`

**Comment by lds-lds** [comment]
same error with ubuntu/xenial ubuntu/bionic solus

**Comment by PStoner3** [comment]
Same issue On CentOS 7 7.4.1708

I see these errors when the scripts runs:

```
 --- Prepare custom libmosquitto version ---
curl: (28) Connection timed out after 10002 milliseconds
 FAILED  Unable to find usable archive for mosquitto
 FAILED  Unable to fetch sources for libmosquitto.

 --- Prepare libwebsockets ---
curl: (28) Connection timed out after 10001 milliseconds
 FAILED  Unable to find usable archive for libwebsockets
 FAILED  Unable to fetch sources for libwebsockets.
```
The issue seems to be in `/packaging/bundle-mosquitto.sh:7` on line 7 where the script attempts to download Mosquitto version v.1.6.8_Netdata-4 from https://github.com/netdata/mosquitto/archive/. There is no file v.1.6.8_Netdata-4.tar.gz in https://github.com/netdata/mosquitto/archive. That file is only available from https://github.com/netdata/mosquitto/releases/download/v.1.6.8_Netdata-4/libmosquitto-v.1.6.8_Netdata-4-linux-amd64.tar.gz

**Comment by PStoner3** [comment]
Apologies. My last comment appears to be incorrect. Still investigating

**Comment by PStoner3** [comment]
Continued investigation found similar situations in the netdata-installer.sh script. Scanning all applicable scripts and adding the proxy flag to all curl commands, I was bale to then manually install netdata successfully.

It would seem prudent to add a --proxy flag to the kickstart script to allow folks to pass in a proxy url to be used throughout the install process

**Comment by lds-lds** [comment]
Hello
the error seems to be resolved with the last agent version v1.22.1-294-g79c06c88

**Comment by prologic** [comment]
Hello @PStoner3 You should also be able to export `http_proxy` / `https_proxy` too right? I'm not convinced we should add `-proxy` flags to all our `curl` commands per se. Can you confirm setting the environment variable also works for you?

**Comment by prologic** [comment]
@lds-lds How did you install Netdata? From `kickstart.sh` or `kickstart-static64.sh`?

**Comment by prologic** [comment]
Please note that we are also tracking all relevant issues we come across with connecting Netdata Agents to Netdata Cloud in #9239 -- many of which have been fixed since.

**Comment by prologic** [comment]
@startryst Could you please let us know if you are still having problems connecting your nodes?

**Comment by startryst** [comment]
> @startryst Could you please let us know if you are still having problems connecting your nodes?

no, fixed after re-install netdata.

**Comment by startryst** [comment]
thanks

**Comment by prologic** [comment]
Nice Thanks!

**Comment by PStoner3** [comment]
I realize this issue has been closed but I did want to address the question posed to me about exporting the http(s)_proxy env variables.

I have since installed netdata on a different server and again encountered the same issue. I did try exporting both the http_proxy and https_proxy variables and no change in response. I also added a .curlrc specifying the proxy value with no change. From what I understand of the curl command the `-q` flag will override the curl config. My only solution was to go through all pertinent scripts and remove the `-q` flag which allowed the curl commands to execute using the .curlrc. Hence the suggestion of supplying a --proxy input variable

Again, I am behind a corporate firewall and run cntlm to provide an ntml proxy before the firewall. The `-q` flag bypasses the local ntlm proxy and the calls through the corporate proxy fail. Another solution would be to dynamically use the `-q` flag in the absence of a .curlrc file.

In the event the owners do decide to not make a change, I at least have a work around.

Thank you. You all have done a great job with netdata and the install script

**Comment by prologic** [comment]
@PStoner3 Thanks! Appreciate your feedback. I'm a bit surprised exporting `(http/https)_proxy` doesn't work in this case. The curl `-q` option is only meant to disregard a user's `$HOME/.curlrc` which can cause problems for us. I'm happy to explore adding the `--proxy` flag if applicable somehow, if you could open a separate issue for this and tag me I'll gladly explore this a bi more?
