### ISSUE TITLE
Add directory for storing lock files + Env variable

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#9347]
##### Feature idea summary

Related: https://github.com/netdata/product/issues/1143

One and only one job with same `moduleName_jobName` should be in the running state. It is easy to achieve for a plugin and we do it.

The problem: we cannot guarantee that this condition is met globally - across all plugins. There is no single source of truth at the moment.

We decided to go with locking files approach:

- try to lock  `moduleName_jobName.lock` file
- success: start the job, do not release the lock while the job is up and running.
- fail: the job with the same name is being served by another plugin - drop it.

---

We need:
- a directory to store all those locks
- enviroment var that points to the dir
 
@thiagoftsm suggested to use `/var/lock/netdata`.

I am not sure about that, i see not all systems have it. I see it is a symlink to `/run/lock` on my manjaro and it seems other [distros moved to `/run/lock` too](https://wiki.debian.org/ReleaseGoals/RunDirectory#How_to_transition_from_.2Fvar.2Frun_to_.2Frun_and_.2Fvar.2Flock_to_.2Frun.2Flock.3F)

🤷‍♂️ we could use `/var/lib/netdata` ?

@Ferroin i am sure you know what the best way is!

**Comment by Ferroin** [comment]
Quick thoughts on this:

* The lockfile prefix path should be a config option, and needs to have the default set at compile time (because it should be relative to the installation prefix just like all of our other paths are).
* The _ideal_ situation on Linux is to use `/run/netdata` for this (possibly with a dedicated sub-directory).
* The fallback (default for the default) should be under `/var/lib/netdata`.
* Netdata (the core, not the collectors) should create the lockfile directory on startup if it does not exist.
* The Netdata core should nuke stale lockfiles on startup.

**Comment by ilyam8** [comment]
@Ferroin it is up to you 😄 for me (plugins) it is just `NETDATA_LOCK_DIR`, right?

**Comment by ilyam8** [comment]
@amoss take a look at @Ferroin comment, we need some @netdata/agent guy to help with that issue

**Comment by amoss** [comment]
These points seem mostly correct.
* Prefix does need to be config option as stated, it becomes one of the `_POST` subst options.
* I'm unclear on why `/run/netdata` is ideal - the advice that I read suggested it was intended for `.pid` files only and that lock-files should go in `/var/lock/netdata` - is there any background to this?
* I don't see how a fallback would work. Our default is the default, and if it does not exist then we would create it. Do you have a different process in mind?
* Stale files should get removed on startup.

**Comment by amoss** [comment]
@ilyam8 - have you not learned C yet... this could be a beautiful experience.... ;)

**Comment by Ferroin** [comment]
> Prefix does need to be config option as stated, it becomes one of the _POST subst options.

I wasn't even thinking it needed to be a post build substitution. Is there some reason to not have this handled as part of the regular agent config and thus have the default baked into the `netdata` binary?

Put differently, my thought was to have this be a configuration option for the core in `netdata.conf`, which then sets the above mentioned environment variable in the environment of any plugins it runs.

> I'm unclear on why /run/netdata is ideal - the advice that I read suggested it was intended for .pid files only and that lock-files should go in /var/lock/netdata - is there any background to this?

It's far from just PID files under `/run`, it's any truly small files that are only relevant over the lifetime of an instance of the service. Flag files, sockets, pipes, lock files, and even small state files are normally kept there as well, the only real 'restriction' is that it has to be stuff that the service only cares about from when it's started until when it's stopped (IOW, stuff scoped to the lifetime of the running instance of the service).  `/run/lock` is the norm anymore for lock files for system services, but it's also not unusual for everything for a service to be in  adirectory named after that service. Long term this is where the pipe used by `netdatacli` should go as well, but that's kind of orthogonal to this.

> I don't see how a fallback would work. Our default is the default, and if it does not exist then we would create it. Do you have a different process in mind?

'Fallback' was probably not the best term, my meaning here is what we set the default value to if the user doesn't explicitly change it at build time. For portability reasons, it needs to be under `/va/rlib/netdata` not anywhere under `/run` (because it needs to work on all platforms and it's simpler for everyone if it's consistent across platforms).

**Comment by amoss** [comment]
> > Prefix does need to be config option as stated, it becomes one of the _POST subst options.
> 
> I wasn't even thinking it needed to be a post build substitution. Is there some reason to not have this handled as part of the regular agent config and thus have the default baked into the `netdata` binary?

The installation prefix is normally handled as a substitution during the build, which then propagates to the constant strings that are the default for the related config options.

**Comment by amoss** [comment]
> It's far from just PID files under /run, it's any truly small files that are only relevant over the
> lifetime of an instance of the service. Flag files, sockets, pipes, lock files, and even small state 

Ok, I see that `/var/lock` on Debian is actually a sym link to `/run/lock`.

**Comment by amoss** [comment]
> 'Fallback' was probably not the best term, my meaning here is what we set the default value to if the user doesn't explicitly change it at build time. For portability reasons, it needs to be under `/va/rlib/netdata` not anywhere under `/run` (because it needs to work on all platforms and it's simpler for everyone if it's consistent across platforms).

So then it seems that `/var/lock` would be a better default then `/run/lock` if it is consistent. Can we rely on `/var/lock` or do we need to use `/var/lib/netdata/lock` ?

**Comment by ilyam8** [comment]
there is no `/var/lock` in macOS (i see no any `*lock*` in the `man hier`)
