### ISSUE TITLE
WMI exporter v13 debug error (check failed)

### ISSUE THREAD

**Issue by TSD26** [netdata/netdata#9359]
Hello - I've setup NetData to run wmi_exporter via the Go orchestrator.   Using WMI exporter v13 this does not work and the debug error is: "check failed".   I tested one Windows server with exporter v12 (prior to the recent changes to the exporter in v13) and it works fine.    Is there a way to address this error in NetData ?
https://github.com/prometheus-community/windows_exporter/releases
https://github.com/prometheus-community/windows_exporter/issues/519#issuecomment-633249466

**Comment by ilyam8** [comment]
Hi @TSD26 

Indeed, i see breaking changes in v0.13.0

> https://github.com/prometheus-community/windows_exporter/releases/tag/v0.13.0

I think it doesn't make much sense to support older versions, we need to support the most recent one

**Comment by ilyam8** [comment]
@TSD26 thx for reporting, i _watch_ `wmi_exporter` repo, but somehow i missed that release 🙈

**Comment by ilyam8** [comment]
@TSD26 i fixed the issue, however `go.d.plugin` version with the fix is not in the netdata latest and i think we wont include it (code freeze) in the nd upcoming release (next week).

Still you can build the plugin from the source and move it to the `plugins.d` dir (replace). Netdata aut-update script doesnt overwrite it.
