### ISSUE TITLE
/opt/netdata is hardcoded in system/install-or-update.sh

### ISSUE THREAD

**Issue by glennie** [netdata/netdata#9440]
Hello,

##### Bug report summary

I use ``netdata-vX.YY.Z.gz.run`` downloaded from the release section as the part of my automated installed process.

Using this executable, I should be able to change the installation path passing ``--target`` option.

But, when I use the target option installation process fails because the installation path is hard coded in ``system/install-or-update.sh`` script.

In fact, instead hardcoding ``NETDATA_PREFIX`` to ``/opt/netdata``, installer should use the parameter provided by the ``--target`` option.

##### OS / Environment
```
/etc/os-release:PRETTY_NAME="Debian GNU/Linux bullseye/sid"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"
```

##### Netdata version
* Tested with latest release.

 

##### Component Name
* Installer provided by github releases page. (https://github.com/netdata/netdata/releases)
##### Steps To Reproduce
1. ``wget -O /tmp/netdata-v1.23.0.gz.run /tmp/ https://github.com/netdata/netdata/releases/download/v1.23.0/netdata-v1.23.0.gz.run``
2. ``sudo bash /tmp/netdata-v1.23.0.gz.run --accept --nochown --quiet --noprogress --nox11 --target /usr/local/netdata/1.23.0 --disable-telemetry -- --dont-start-it``

##### Expected behavior

* Netdata should installed properly in ``/usr/local/netdata/1.23.0``

**Comment by Ferroin** [comment]
Due to how our build process works, we cannot support arbitrary installation prefixes for pre-built copies of Netdata. We have to bake default paths into the binary at build time, and there is no sane way to override these at install time.

If you absolutely require a custom installation prefix, you will need to either use our [official installation script](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart) or build netdata yourself.

Closing this as won't fix.
