### ISSUE TITLE
Is there a package for Schumann resonance?

### ISSUE THREAD

**Issue by CLUB777ONE** [netdata/netdata#9608]
Is there a package for Schumann resonance?

**Comment by underhood** [comment]
Do you mean a collector? Not that I know of. Writing a collector is however relatively easy (if you have the data source) due to the text-based nature of the protocol. 

List of supported collectors: https://learn.netdata.cloud/docs/agent/collectors/collectors
The description on how to write custom collector: https://learn.netdata.cloud/docs/agent/collectors/plugins.d#external-plugins-api

**Comment by CLUB777ONE** [comment]
@underhood Thank you for the info. Will try to find accessible data source and then try to create a custom collector.

**Comment by underhood** [comment]
@CLUB777ONE no problem. Good to hear you will try to use Netdata. If you have some questions or need help writing the collector let us know. I am sure I or some other colleague from Netdata will be glad to help you.

**Comment by prologic** [comment]
@CLUB777ONE If you have any other questions or need help feel free to open a new issue. If you write the collector feel free to contribute it back so others in the community can benefit! Thanks!

**Comment by origanoinitalian** [comment]
Hi, still nothing on this data?
