### ISSUE TITLE
Web_Log not recognising Apache LogIOTrackTTFB Directive

### ISSUE THREAD

**Issue by TheOldMan2000** [netdata/netdata#9611]
##### Bug report summary
Netdata Web_log doesn't seem to recognise the Apache custom log format string %^FB which can be enabled for tracking of time to first byte (TTFB).

LogIOTrackTTFB Directive

Delay in microseconds between when the request arrived and the first byte of the response headers are written. Only available if LogIOTrackTTFB is set to ON.
Available in Apache 2.4.13 and later.

http://httpd.apache.org/docs/current/mod/mod_logio.html#logiotrackttfb

##### OS / Environment

Apache 2.4.13 and later.

##### Netdata version
v1.23.2-67-gcdc91264

##### Component Name

Web_Log 

##### Steps To Reproduce

1. Enable LogIOTrackTTFB. WHM -> Apache Configuration -> Include Editor -> 

Example:
```
<IfModule log_config_module>

LogIOTrackTTFB ON

LogFormat "%v %a %p %m %H \"%U\" %t %>s %O %I %D %^FB \"%{Referer}i\" \"%{User-Agent}i\" \"%r\"" vhost_combined

CustomLog /var/log/apache2/access_log_combined vhost_combined

</IfModule>

```

Or enable and add the format string **%^FB** to WHM -> Apache Configuration -> Global Configuration -> LogFormat 

2. Restart Netdata using the web_log collectors.

##### Expected behavior

Netdata web_log to display Time To First Byte statistics, chart and possibly histogram as appropriate by utilising the Apache custom log format string **%^FB** as it currently does with the other format strings.

Thank you.

**Comment by ilyam8** [comment]
@TheOldMan2000 hey

show some lines with `%^FB`

**Comment by TheOldMan2000** [comment]
Sure...





```
example.co.uk 45.xx.xx.55 443 GET HTTP/1.1 "/forums/topic/5-are-dogs-allowed-at-the-show/" [27/Jul/2020:14:59:42 +0100] 200 20861 1483 1898159 1895667 "https://www.example.co.uk/forums/topic/5-are-dogs-allowed-at-the-show/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36" "GET /forums/topic/5-are-dogs-allowed-at-the-show/ HTTP/1.1"

example.co.uk 66.249.65.157 443 GET HTTP/1.1 "/calendar/1-events-calendar/week/2019-05-15/" [27/Jul/2020:15:04:22 +0100] 200 17371 1350 3504455 3502293 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.92 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)" "GET /calendar/1-events-calendar/week/2019-05-15/ HTTP/1.1"
example.co.uk 45.xx.xx.55 443 GET HTTP/1.1 "/forums/topic/7-beginners-guide/" [27/Jul/2020:14:59:44 +0100] 200 22167 1455 1511514 1508882 "https://www.example.co.uk/forums/topic/7-beginners-guide/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36" "GET /forums/topic/7-beginners-guide/ HTTP/1.1"

```

From File: /opt/netdata/etc/netdata/go.d/web_log.conf

```

# centos
- name: apache
    path: /var/log/apache2/access_log
    log_type: csv
group_response_codes: yes
csv_config:
format: '%v %a %p %m %H \"%U\" %t %>s %O %I %D %^FB \"%{Referer}i\" \"%{User-Agent}i\" \"%r\"' 
custom_fields:
- name: '{User-Agent}i'
patterns:
- name: Googlebot
match: '~ Googlebot'
- name: Bingbot
match: '~ bingbot'
- name: Yahoo
match: '~ yahoo'
- name: Applebot
match: '~ Applebot'
histogram: [1,3,10,30,100]



```

**Comment by TheOldMan2000** [comment]
> I think we could add `custom_time_field` (we have [`custom_field`](https://github.com/netdata/go.d.plugin/blob/ed553a8dcef88a63e2681f4c2489708c22dda8ed/config/go.d/web_log.conf#L80-L96))
> 
> for instance
> 
> ```yaml
> custom_time_fields:
>   - name:  field_name1  # Field name. Should match field name from log format.
>     histogram: [1,3,10,30,100]
>   - name:  field_name2  # Field name. Should match field name from log format.
>     histogram: [1,3,10,30,100]
> ```
> 
> @TheOldMan2000 what do you think?

Any idea if and when Apache Logio TTFB value will be supported? Many thanks.

**Comment by ilyam8** [comment]
Hi @TheOldMan2000, it's been delayed because i want to think about https://github.com/netdata/netdata/issues/7420#issuecomment-564017041 - perhaps it is possible to convert weblog to generic plugin - so there are several options how you can chart a log field and it is user configurable. We need to discuss it @vlvkobal @thiagoftsm

**Comment by TheOldMan2000** [comment]
Thanks @ilyam8 I honestly and probably naively thought it was just a quick addition, since %^FB is just a numerical value, like the others Netdata already displays %I %O etc. I realise you are the experts and code ninjas though! :)

**Comment by ilyam8** [comment]
ok, i think https://github.com/netdata/netdata/issues/9611#issuecomment-678757105 is good

@hamedbrd are you willing to pick up this issue ?

**Comment by hamedbrd** [comment]
@ilyam8 

> i think #9611 (comment) is good

Is this look like the module I have created two years ago for python plugins? Do we want to do something like that?
[PR 4900](https://github.com/netdata/netdata/pull/4900)

**Comment by ilyam8** [comment]
Yes, we want in general, related issue - https://github.com/netdata/netdata/issues/7420.

This issue is to add `custom_time_fields` feature to the go weblog. In addition to [`custom_fields`](https://github.com/netdata/go.d.plugin/tree/master/modules/weblog#custom-fields-feature).

Let me think a bit and i provide some suggestion about the implementation.

**Comment by ilyam8** [comment]
@hamedbrd i check weblog code and it doesn't look simple/friendly, my firt intention was to simplify it but it could take some time.

I think we could add `custom_time_field`, then simplify the code.

We need:
 - add custim fime field metrics to the metrics.go and add them to the `metricsData`

since we want avg/min/max and histogram it is ~

```go
	customTimeFieldMetrics struct {
		Time     metrics.Summary   `stm:"time"`
		TimeHist metrics.Histogram `stm:"time_hist"`
	}
```

 - add `custom_time_field` option the [the weblog config](https://github.com/netdata/go.d.plugin/blob/7959eff02c96b23a994f1d1e532aa43203bb2138/modules/weblog/weblog.go#L52-L60)

- modify [`createCustomFields` method](https://github.com/netdata/go.d.plugin/blob/7959eff02c96b23a994f1d1e532aa43203bb2138/modules/weblog/init.go#L47)

- modify `createCharts` method ([custom fields part](https://github.com/netdata/go.d.plugin/blob/7959eff02c96b23a994f1d1e532aa43203bb2138/modules/weblog/charts.go#L589-L593))

- modify [`collectCustomFields` method](https://github.com/netdata/go.d.plugin/blob/7959eff02c96b23a994f1d1e532aa43203bb2138/modules/weblog/collect.go#L303-L321)

something like (not sure)

```go
	for _, cv := range w.line.custom.values {
        if patterns, ok := w.customFields[cv.name]; ok {
			for _, pattern := range patterns {
				if !pattern.MatchString(cv.value) {
					continue
				}
				v, ok := w.mx.ReqCustomField[cv.name]
				if !ok {
					break
				}
				c, _ := v.GetP(pattern.name)
				c.Inc()
				break
			}
		} else if ...
	}
```

**Comment by hamedbrd** [comment]
@ilyam8 May you explain this part a bit more?

> Yeah, custom_fields counts number of matches per **pattern**, custom_time_fields could count **min/avg/max + histogram.**

 if we want to fetch  `%^FB` without any patterns then how should we fetch this log field from apache log file? it would be great to give me an example withing netdata to see how we should fetch such log field.

And does it need to add one more case to this method?
https://github.com/netdata/go.d.plugin/blob/1305e1afb4b57776ce29daa2fedfa631c16dde1d/modules/weblog/logline.go#L106-L148

**Comment by ilyam8** [comment]
@hamedbrd my proposal is to not add `%^FB` but add `custom_time_field` feaute like we have [`custom_field`](https://github.com/netdata/go.d.plugin/tree/master/modules/weblog#custom-fields-feature)

**Comment by hamedbrd** [comment]
@ilyam8  you earlier mentioned 

> Field name. Should match field name from log format.


So does that mean in config file, in case of apache log, we should have something like this:
custom_time_fields:
  - name:  FB 
    histogram: [.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10]
  - name:  D 
    histogram: [.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10]

**Comment by ilyam8** [comment]
yes, something like this

```yaml
jobs:
  - name: apache
    ...
    custom_time_fields:
     - name:  '^FB' 
       histogram: [.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10]  # optional
```
