### ISSUE TITLE
Incorrect visualization of stacked charts with negative values

### ISSUE THREAD

**Issue by vlvkobal** [netdata/netdata#9663]
##### Bug report summary
If there are negative values/negative multiplier in stacked charts they are sometimes visualised as if they were positive:
![image](https://user-images.githubusercontent.com/22008543/89402638-d70af900-d71f-11ea-8314-750643294463.png)
Another possible appearance - incorrect colors:
![image](https://user-images.githubusercontent.com/22008543/89402656-df633400-d71f-11ea-8742-dbd570fa5fdc.png)

##### OS / Environment
Windows 10 2004
Chrome 84.0.4147.105

@underhood and @thiagoftsm reported the same issue in different environments.

##### Netdata version
netdata v1.23.2-131-ga772f1c16

##### Component Name
Dashboard

##### Steps To Reproduce
Display stacked charts with negative values

##### Expected behavior
Sign and color are correctly displayed in the stacked charts.

**Comment by Ferroin** [comment]
Discussion in #3327 regarding stacked charts is probably relevant here.

**Comment by jacekkolasa** [comment]
i converted it from `bug` to `feature request`, because this was never working, due to Dygraph.js limitations (thx @Ferroin for linking the issue).

I have built a prototype, by summing the values on FE - i'm attaching a screenshot below. This is kind of a hack, so i hope we won't break anything. I apply it when `chart_type` is `stacked` and `min` property in `/data` response is negative. It would be better if we could have a separate explicit chart type for this (like `stacked-bidirectional`?). @netdata/agent please let me know if that would be problematic. If yes, i'll try with autodetect.

![image](https://user-images.githubusercontent.com/5786722/90021042-01752d00-dcb1-11ea-9f48-8242c25df7cb.png)

**Comment by jacekkolasa** [comment]
it got close automatically (when i wrote "fixes #9663` in the dashboard PR and merged it). The fix will come here soon, i'll make a dashboard release
