### ISSUE TITLE
How to make netdata docker container run on rootful podman?

### ISSUE THREAD

**Issue by andrew-kennedy** [netdata/netdata#9693]
##### Question summary
In principle, netdata docker containers should be able to be run on fedora under podman as long as they run as rootful podman. However, the provided instructions do not allow the docker container to run in podman. Can anyone point me in the right direction to get this running in a container on fedora 32 without installing docker?
##### OS / Environment
Fedora 32, podman 2.0.4

**Comment by dnk8n** [comment]
I would also be keen to know about this.

**Comment by dnk8n** [comment]
Think it is best to just install Netdata uncontainerized for now? Do containers provide a superset or a subset of uncontained Netdata features?

**Comment by ilyam8** [comment]
Hi @dnk8n 

> a subset

**Comment by dnk8n** [comment]
Ok, so something worth running on the host if convenient anyway.

Are there similar issues to running netdata container on kubernetes? Just thinking that maybe the answer to that question could be useful to the future of solving this issue.

Personally, I am going to avoid the issue and install netdata on the host.

**Comment by ilyam8** [comment]
What issues? 

If your container runtime is docker there is no OP problem.

See https://github.com/netdata/helmchart#netdata-helm-chart-for-kubernetes-deployments

**Comment by dnk8n** [comment]
By this issue, I am referring to https://github.com/netdata/netdata/issues/9693 :)

This issue is all about rootful podman, which is **not** a docker container runtime. And I was referring to Kubernetes based netdata containers **without** a Docker container runtime. Does it run into the same problems as podman based netdata containers would? Or are they slightly different problems?

To emphasize what I meant, to avoid [issue 9693](https://github.com/netdata/netdata/issues/9693), one must run netdata on the host or in a container with the docker container runtime.

**Comment by ilyam8** [comment]
I am not a specialist and have 0 exp with podman, but i think that k8s is not related, since all the problems are only container runtime related in that case.

**Comment by OdysLam** [comment]
Hey @dnk8n ,

Welcome to our community :) 

Thanks @andrew-kennedy for the question!
