### ISSUE TITLE
Is it possible to get time sync deviation from Netdata?

### ISSUE THREAD

**Issue by mbarper** [netdata/netdata#9747]
#### Question summary

I know I can get the status of my time sync process like ntp, timesyncd, etc... but I was wondering if it is possible to know the time deviation because I need to control my servers are always in the right time or trigger and allert

##### OS / Environment

Mainly Ubuntu 18, but I guess this could be important for any distribution

##### Component Name

Netdata? a plugin? I really don't know if anything already exists

##### Expected results

Get a metric with the drift time or time difference in seconds with the NTP server, or any other way to know there is a deviation from the NTP server date.

**Comment by Ferroin** [comment]
It's not realistically possible to track the system clock's offset from 'real' time unless you have a high precision time source locally available (such as a WWVB receiver or a GPS timecode unit), and at that point you should just tell NTPD (or whatever other tool) to use that as a reference clock for the system, at which point you should have an offset of exactly zero from that reference. All you can measure otherwise is offset relative to other systems. However, that's almost certainly what actually matters for your usage (actually needing sub-second accuracy for absolute times is rather unusual).

For the NTPD collector (which works with both the official NTPD implementation, as well as `ntpsec` and possibly OpenNTPD (though I've not checked that one)), there's a chart (with a context of `ntpd_local.sys_offset' with the default configuration) which tracks the system clock's offset relative to the active peer being used for time synchronization, which is about the best you can get with NTP  unless you want to get into the complicated territory of tracking frequency correction factors (which I strongly advise against, there are way too many variables than influence the required correction factor, so it's actually rather unstable over long periods of time). A lower offset roughly correlates with a more accurate clock (because it usually indicates less overall delay relative to the reference clock), with values less than 100ms being more than sufficient for most applications, mid to upper single digit ms values being 'normal' on good physical hardware, and values less than 0.1ms being theoretically possible but requiring a lot of effort to achieve.

I'm not sure if there's an equivalent for our chrony collector, and AFAIK we do not have any collectors that work with systemd-timesyncd or PTPD.

---

I would like to mention that if your goal here is to keep time in sync across a bunch of systems, your best option is likely to be running a local NTP server either syncing off of `pool.ntp.org`, a curated selection of stratum 1 and 2 NTP servers, or a local reference clock, configuring your systems to sync off of that server, and then configuring all of the relevant systems to peer with each other as well (that will keep them in sync relative to each other better than just syncing off of the same server will).

**Comment by mbarper** [comment]
In first place thank you very much for your detailed explanation. Impressive!

Secondly, what I would like to check is exactly what you said: "tracks the system clock's offset relative to the active peer being used for time synchronization", the think is that if we don't have a similar collector for systemd-timesyncd and chrony would be a problem for me now as I have multiple instances with different time sync tools.

Anyway, I can start with NTPD collector and move forward from there.

I leave the ticket open just in case anybody else have some useful information and will close the question in few days.

**Comment by Ferroin** [comment]
FWIW, there _is_ a collector for Chrony, I've just never used it so I don't know if it has equivalent metrics or not. I suspect it probably provides something similar, as this information is an important part of NTP in general, but I can't say for sure simply because I've never really looked at it.
