### ISSUE TITLE
REST API / Charts not displaying correctly

### ISSUE THREAD

**Issue by Unfairz** [netdata/netdata#9796]
##### Bug report summary

Hello, it appears that recently the netdata API isn't returning properly formed JSON and visualizing the charts is failing. I have also double-checked the code on here - https://learn.netdata.cloud/docs/agent/web/api and can confirm that the code, grabbing the charts is the same, however, in the console output, I am getting malformed JSON errors.

```
Error: Parse error on line 1:
{version:'0.6',reqId:
-^
Expecting 'STRING', '}'
```
##### OS / Environment

```
CloudLinux release 7.8 (Alexei Leonov) 
```

##### Netdata version
```
netdata v1.24.0
```
##### Component Name
```
Netdata REST API / Google Charts API
```
##### Steps To Reproduce

1. In order to test it, simply copy and pasted the code given in your Wiki page or directly call the API:
```
/api/v1/data?after=-60&format=datasource&options=nonzero&chart=system.load#
```
##### Expected behavior
JSON is formed correctly and charts are displayed on the page.

Thank you for your time and let me know if any further information is needed :sparkles:

**Comment by ilyam8** [comment]
Hi

could you show https://github.com/netdata/netdata/issues/9745#issuecomment-674019270

could be the same issue

**Comment by Unfairz** [comment]
Sure! Here is the output:

<details>
<summary>JSON Output</summary>

```
{
version: "v1.24.0",
uid: "3eec1832-831b-11ea-a9c9-42010a9a0022",
mirrored_hosts: [
"X"
],
alarms: {
normal: 187,
warning: 0,
critical: 1
},
os_name: "CloudLinux",
os_id: "cloudlinux",
os_id_like: "rhel fedora centos",
os_version: "7.8 (Alexei Leonov)",
os_version_id: "7.8",
os_detection: "/etc/os-release",
cores_total: "2",
total_disk_space: "111454736384",
cpu_freq: "2000000000",
ram_total: "3972739072",
container_os_name: "none",
container_os_id: "none",
container_os_id_like: "none",
container_os_version: "none",
container_os_version_id: "none",
kernel_name: "Linux",
kernel_version: "3.10.0-962.3.2.lve1.5.38.el7.x86_64",
architecture: "x86_64",
virtualization: "kvm",
virt_detection: "systemd-detect-virt",
container: "unknown",
container_detection: "none",
host_labels: {
_os_name: "CloudLinux",
_os_version: "7.8 (Alexei Leonov)",
_kernel_version: "3.10.0-962.3.2.lve1.5.38.el7.x86_64",
_system_cores: "2",
_system_cpu_freq: "2000000000",
_system_ram_total: "3972739072",
_system_disk_space: "111454736384",
_architecture: "x86_64",
_virtualization: "kvm",
_container: "unknown",
_container_detection: "none",
_virt_detection: "systemd-detect-virt",
_is_parent: "false"
},
collectors: [
{
plugin: "apps.plugin",
module: ""
},
{
plugin: "proc.plugin",
module: "/proc/uptime"
},
{
plugin: "python.d.plugin",
module: "mysql"
},
{
plugin: "proc.plugin",
module: "/proc/meminfo"
},
{
plugin: "tc.plugin",
module: ""
},
{
plugin: "idlejitter.plugin",
module: ""
},
{
plugin: "proc.plugin",
module: "/proc/net/dev"
},
{
plugin: "proc.plugin",
module: "/proc/net/stat/nf_conntrack"
},
{
plugin: "proc.plugin",
module: "/proc/loadavg"
},
{
plugin: "proc.plugin",
module: "ipc"
},
{
plugin: "statsd.plugin",
module: "stats"
},
{
plugin: "cgroups.plugin",
module: "stats"
},
{
plugin: "python.d.plugin",
module: "ntpd"
},
{
plugin: "python.d.plugin",
module: "apache"
},
{
plugin: "proc.plugin",
module: "/proc/stat"
},
{
plugin: "netdata",
module: "stats"
},
{
plugin: "diskspace.plugin",
module: ""
},
{
plugin: "web",
module: "stats"
},
{
plugin: "proc.plugin",
module: "/proc/sys/kernel/random/entropy_avail"
},
{
plugin: "python.d.plugin",
module: ""
},
{
plugin: "cgroups.plugin",
module: "/sys/fs/cgroup"
}
],
cloud-enabled: true,
cloud-available: true,
agent-claimed: false,
aclk-available: false
}
```
</details>

**Comment by ilyam8** [comment]
Ok, seems it is another problem, there is no `prometheus` module in the output 🤔

**Comment by Unfairz** [comment]
It's a bit of an odd one indeed!

The code in the API docs is also returning "Script errors" which I would assume would the malformed JSON as well. :frowning:

**Comment by ilyam8** [comment]
@jacekkolasa any ideas?

**Comment by amoss** [comment]
There is a problem with the code in the jsfiddle (@jacekkolasa / @joelhans ) please take a look. It seems to be something different to the report above. @Unfairz - the json output that you posted is part of the respone to an `/api/v1/info` request but something has removed the quotes from the output which is why it does not validate. That is not the format returned by the agent.

**Comment by jacekkolasa** [comment]
The output from `format=datasource` is actually not JSON, but a format prepared specifically for Google Charts. You can see it for example in the response from https://london3.my-netdata.io/api/v1/data?chart=system.cpu&after=-60&format=datasource&options=nonzero. We don't use that library in our standard dashboard, so that functionality is not well known. I will need some time to figure out what is wrong in those jsFiddles because i never used Google Charts in this way before.

@Unfairz do you need specifically to use Google Charts, or maybe other ways, like creating your own static custom dashboard (https://learn.netdata.cloud/docs/agent/web/gui/custom#dashboardjs) will work for you?

**Comment by Unfairz** [comment]
Thank you for your time looking into this!

I have been using Google Charts mainly due to the fact that I wasn't aware ot the Dashboard JS option, which I will surely look into now as it seems much nicer to deal with. :rocket: 

Thank you for your time once again.

**Comment by jacekkolasa** [comment]
@Unfairz I'm glad that option is ok for you! We shouldn't have not working docs, for sure. 

Re: jsfiddles, something is wrong with that usage of Google Charts, maybe their api has changed, or we broke something? Anyway, this use case is very old, we shifted our efforts to `data-netdata=""` charts (static custom dashboards), and dygraph charts instead of google. Also that version of Google Charts is old/outdated. @joelhans do you think we could hide `Google charts API` section for now? IMO it's confusing, and I don't think we'll have time now to fix those examples.

**Comment by joelhans** [comment]
@jacekkolasa Yeah, let's remove that information, as it's not really a supported use of the API any more. I'll make a PR for it momentarily.
