### ISSUE TITLE
Mass Alarm "out of disk space time = 0h" "out of disk inodes time = 0h"

### ISSUE THREAD

**Issue by andrezaycev** [netdata/netdata#9802]
##### Bug report summary

Every day received mass alarm _"out of disk space  time = 0h _" "_out of disk inodes time = 0h_" from multiply nodes. it's happened at the same period everyday - (02:50-03:00 UTC). I have about 15 nodes in production with netdata and 3-4 of them send me alarms with all existed partitions(for example `/, /dev/shm, /run/netdata, /run/lock`). Different nodes send alarms every day

Graph during alarm looks like miss data (_time on graph UTC+9_)
![image](https://user-images.githubusercontent.com/9984761/90859433-370dca80-e3c3-11ea-96ee-aca247ec29c7.png)

##### OS / Environment
Ubuntu 16.04

##### Netdata version

 v1.24.0-93-nightly

##### Component Name

Alarm component

**Comment by amoss** [comment]
I get similar alerts from production servers. That alarm works by taking the current rate of disk-fill and projecting it forwards to see when the limit will be reached. The problem that I've seen is that it cannot know how long to average this measurement over  so if there is a burst of disk writes that fill the sample window for the alarm then it (correctly) predicts that the disk will fill if the rate continues. Normally it gets triggered about the same time for me (around 3am), as most of my cron jobs kick in at about that time and one of them sets up a huge temporary file as cleans part of the system. 

Technically the prediction is correct - but it might not be helpful. It can be tuned by changing the alarm definition in:
`/etc/netdata/edit-config health.d/disks.conf`. I've left mine at the default values because it has correctly predicted a full disk several times.

The options are:
* Increase the `1h` sample to a longer period, this will reduce false positives but may miss some real problems.
* Change the thresholds to higher values (the `48` / `8` and `24` / `2` values).

@thiagoftsm / @stelfrag Any experience in tuning this alarm to be less noisy?

**Comment by stelfrag** [comment]
> @thiagoftsm / @stelfrag Any experience in tuning this alarm to be less noisy?

I will play a little bit with it but in general it does what it is supposed to do. 

The assumption here is that the fill rate is "expected regular system activity". Any spikes will throw it off. 

So if at 3am there is a job that:

- Fetches 500MB from the internet 
- Processes and produces 2.5 GB of data in the next 40 mins
- Processes the data and outputs a final report file of just a few KBs 
- Deletes the 3GB

This is not a sustained fill rate that will make the system run out of disk space 

The option to disable the alarm between 3am - 4am could be the only solution (see #9097)
