### ISSUE TITLE
Dashboard gauges missing in Go.d version of web_log

### ISSUE THREAD

**Issue by TheOldMan2000** [netdata/netdata#9810]
Please can you add the dials or equivalent that are in the original Python.d version of web_log into the go.d version?

Python.d version from your London demo:

<img width="1024" alt="london3 my-netdata io netdata dashboard" src="https://user-images.githubusercontent.com/13329789/90981039-aff15b80-e556-11ea-870e-27819c84dac5.png">

My Go.d version Netdata v1.24.0-97-gf717969c:

<img width="824" alt="vps40877 inmotionhosting com netdata dashboard" src="https://user-images.githubusercontent.com/13329789/90981045-ba135a00-e556-11ea-98e7-454044c36a1c.png">

>  'speedometer style dials/gauges' that the Python.d version has?

Yeah, this actually pretty easy to add, i think i just forgot about it (should add some things to the dashboard_info.js).

_Originally posted by @ilyam8 in https://github.com/netdata/netdata/issues/9611#issuecomment-678779331_

**Comment by TheOldMan2000** [comment]
Polite bump!

**Comment by ilyam8** [comment]
@hamedbrd can you help with this issue?

**Comment by hamedbrd** [comment]
@ilyam8 I will check it out and keep this issue updated

**Comment by ilyam8** [comment]
It seems [go weblog charts](https://github.com/netdata/go.d.plugin/blob/master/modules/weblog/charts.go) has different context names or something 

---

These are weblog gauges

https://github.com/netdata/netdata/blob/b9bc990af36ce8917fc037f681d0b1987b78eb81/web/gui/dashboard_info.js#L1959-L2082

and info

https://github.com/netdata/netdata/blob/b9bc990af36ce8917fc037f681d0b1987b78eb81/web/gui/dashboard_info.js#L615-L629

---

We need to understand what we are missing and update `dashboard_info.js` file.

**Comment by TheOldMan2000** [comment]
Thanks for both for working on this.

**Comment by ilyam8** [comment]
@hamedbrd 

**Prepare python and go weblog jobs**

We need apache/nginx logs, we don't need a webserver, we need just logs, i suggest to take go weblog testadata: https://raw.githubusercontent.com/netdata/go.d.plugin/master/modules/weblog/testdata/full.log

```cmd
[ilyam-pc logs]# pwd
/opt/logs

[ilyam-pc logs]# wget -q https://raw.githubusercontent.com/netdata/go.d.plugin/master/modules/weblog/testdata/full.log

[ilyam-pc logs]# wc -l full.log 
499 full.log
```

Then we need to add python and go weblog jobs:

```cmd
[ilyam-pc netdata]# cat python.d/web_log.conf 
python:
  path: '/opt/logs/full.log'

[ilyam-pc netdata]# cat go.d/web_log.conf 
jobs:
  - name: go
    path: /opt/logs/full.log
```

And restart `netdata.service`. After it there are 2 weblog jobs on the dashboard:
- `web log python`

<img width="1137" alt="Screenshot 2020-10-05 at 11 57 37" src="https://user-images.githubusercontent.com/22274335/95059743-f911ff00-0701-11eb-9483-d03e4118d63a.png">

- `web log go`

<img width="1147" alt="Screenshot 2020-10-05 at 11 57 52" src="https://user-images.githubusercontent.com/22274335/95059760-0202d080-0702-11eb-8a86-b587adbc03e5.png">


As you so go weblog job has no gauges. We want to have them.

---

We use `dashboard_info.js` to change chart titles, add additional info, gauges, etc.

These are first 4 gauges

https://github.com/netdata/netdata/blob/b9bc990af36ce8917fc037f681d0b1987b78eb81/web/gui/dashboard_info.js#L1959-L2034

And 5th

https://github.com/netdata/netdata/blob/b9bc990af36ce8917fc037f681d0b1987b78eb81/web/gui/dashboard_info.js#L2047-L2066

They dont work for python because of different chart context - as you see it expects `web_log.response_statuses` and `web_log.response_time`.



We need to add new gauges for go weblog charts.

How to do it:
- add changes to the `dashboard_info.js`
- replace current `dashboard_info.js` with modified
- empty cache and hard reload to see the changes

<img width="1007" alt="Screenshot 2020-10-05 at 12 07 23" src="https://user-images.githubusercontent.com/22274335/95060754-5c506100-0703-11eb-8233-c402f5b3de4d.png">

If everthing is ok - commit and make a PR. Hope this help!

**Comment by hamedbrd** [comment]
@ilyam8 thank you for clarification, by some changes on go web_log then I enabled the go web_log gauges on my local machine.
now we have two options, edit chart ID names in go web_log or adding current go web_log chart IDs to dashboard_info.js

which one do you recommend? I would say by changing go web_log chart ID names would be better as these two modules are doing the same job

**Comment by ilyam8** [comment]
Yes, you understand it right, it is either change go weblog chart id's or add new gauges to the `dashboard_info.js`

About python `response_time` - this is wrong name and in fact it is `request_processing_time`.

`response_statuses` doesn't seem correct for me either. Let me think 🤔

**Comment by hamedbrd** [comment]
@ilyam8 if we want to change `response_time` to something, then it going to be a significant change for clients because I'm pretty sure many dashboards/queries were created base on this name. right?

**Comment by ilyam8** [comment]
> or adding current go web_log chart IDs to dashboard_info.js

^^Yes, we are not changing python chart ids. We will have duplicates in the `dashboard_info.js`.

**Comment by TheOldMan2000** [comment]
Thank you 🙏🏻 @hamedbrd @ilyam8
