### ISSUE TITLE
What to do if I wanna use collector  only?

### ISSUE THREAD

**Issue by oleotiger** [netdata/netdata#9818]
If I wanna use collector only to get metrics and information about my system/service/app, what should I do?

Can I have a main function as interface with `-h` printing help infomation?

What if I wanna to control collector flexibly? For example, get all metrics 1 time and after 5s get another round of all metrics.

**Comment by thiagoftsm** [comment]
Hello @oleotiger ,

Netdata allows you to enable only the collectors you want, but we start all to simplify users' life. To disable collectors you can set inside your `netdata.conf` the option  `enabled = no` for all collectors that you do not wanna see data.

Best regards!

**Comment by amoss** [comment]
We don't support the collectors in a stand-alone configuration, they are designed to be integrated into the Netdata application. It would be possible to use them stand-alone by running them in the same way that Netdata does:

* For each of the external collectors look at how they are spawned in the C code.
* They can be spawned directly from a shell if you set the environment up the same way.
* The output of the collectors is a stream of text documented at https://github.com/netdata/netdata/tree/master/collectors/plugins.d

The design of the collectors is based around push rather than pull though - so each collector starts and then decides when to send samples to Netdata, rather than Netdata pulling samples from the collector. If you want to control the flow of metrics in the way that you describe then you would need to write a real-time application to filter the stream.
