### ISSUE TITLE
[Bug]: the source directory does not include netdata-installer.sh

### ISSUE THREAD

**Issue by ndsda** [netdata/netdata#9863]
I run  `bash <(curl -Ss https://my-netdata.io/kickstart.sh)`

The first line output says `/dev/fd/63: line 167: /tmp/netdata-test.GTtLvJePOp: Permission denied`

And it ends:
`ABORTED Cannot install netdata from source (the source directory does not include netdata-installer.sh). Leaving all files in /tmp/netdata-kickstart-Q30do8Yo21`

**It's the first time I get an error when installing Netdata. Can anyone advise me how to solve this problem?**

Full output:

`[root@daisy-5 ~]# bash <(curl -Ss https://my-netdata.io/kickstart.sh)
/dev/fd/63: line 167: /tmp/netdata-test.GTtLvJePOp: Permission denied
System            : Linux
Operating System  : GNU/Linux
Machine           : x86_64
BASH major version:
 --- Fetching script to detect required packages... ---
[/tmp/netdata-kickstart-y8DEbXhhIM]# curl -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-y8DEbXhhIM/install-required-packages.sh https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/install-required-packages.sh  OK

 --- Running downloaded script to detect required packages... ---
[/tmp/netdata-kickstart-y8DEbXhhIM]# /usr/bin/bash /tmp/netdata-kickstart-y8DEbXhhIM/install-required-packages.sh netdata Loading /etc/os-release ...
You should have EPEL enabled to install all the prerequisites.
Check: http://www.tecmint.com/how-to-enable-epel-repository-for-rhel-centos-6-5/
 > CentOS Version: 7 ...
 > Checking for epel ...

/etc/os-release information:
NAME            : CentOS Linux
VERSION         : 7 (Core)
ID              : centos
ID_LIKE         : rhel fedora
VERSION_ID      : 7

We detected these:
Distribution    : centos
Version         : 7
Codename        : 7 (Core)
Package Manager : install_yum
Packages Tree   : centos
Detection Method: /etc/os-release
Default Python v: 2 (will install python3 too)

Searching for distro_sdk ...
Searching for autoconf_archive ...
 > Checking if package 'autoconf-archive' is installed...
Searching for libz_dev ...
 > Checking if package 'zlib-devel' is installed...
Searching for libuuid_dev ...
 > Checking if package 'libuuid-devel' is installed...
Searching for libmnl_dev ...
 > Checking if package 'libmnl-devel' is installed...
Searching for json_c_dev ...
 > Checking if package 'json-c-devel' is installed...
Searching for libuv ...
 > Checking if package 'libuv-devel' is installed...
Searching for lz4 ...
 > Checking if package 'lz4-devel' is installed...
Searching for openssl ...
 > Checking if package 'openssl-devel' is installed...
Searching for judy ...
 > Checking if package 'Judy-devel' is installed...
Searching for libelf ...
 > Checking if package 'elfutils-libelf-devel' is installed...

All required packages are already installed. Now proceed to the next step.

 OK

[/tmp/netdata-kickstart-y8DEbXhhIM]# curl -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-y8DEbXhhIM/sha256sum.txt https://storage.googleapis.com/netdata-nightlies/sha256sums.txt  OK

[/tmp/netdata-kickstart-y8DEbXhhIM]# curl -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-y8DEbXhhIM/netdata-latest.tar.gz https://storage.googleapis.com/netdata-nightlies/netdata-latest.tar.gz  OK

[/tmp/netdata-kickstart-y8DEbXhhIM]# tar -xf netdata-latest.tar.gz  OK

 ABORTED  Cannot install netdata from source (the source directory does not include netdata-installer.sh). Leaving all files in /tmp/netdata-kickstart-y8DEbXhhIM

**Comment by thiagoftsm** [comment]
Hello @ndsda ,

It looks like that your `/tmp` is mounted readonly or without exec permission, please, can you run the following command before to start the installation:

```
mount /tmp -o remount,rw
```

as you can see in [this comment](https://github.com/netdata/netdata/issues/9579#issuecomment-665384044) other users already had problems like this and to remount `/tmp` fixed the problem for them.

Best regards!

**Comment by ndsda** [comment]
Hi @thiagoftsm ,

I've tried remounting `/tmp` but I still encounter the same problem.

`/dev/fd/63: line 167: /tmp/netdata-test.5wLY4JpoF6: Permission denied`

**Comment by thiagoftsm** [comment]
@Ferroin and @prologic can you give us a tip for this problem on CentOS?

**Comment by prologic** [comment]
@ndsda Could you please list the contents of `/tmp/netdata-kickstart-y8DEbXhhIM` in a [Gist](https://gist.github.com)? Thanks! Could you also include the output of `mount` in that same Gist too please either as a comment or additional file.

**Comment by Redominus** [comment]
It also happens to the updater cron(happening in centos6.10 and centos 7)
`/etc/cron.daily/netdata-updater:

/etc/cron.daily/netdata-updater: line 77: /tmp/netdata-test.huHeA0BnbW: Permission denied
Wed Sep  2 04:05:55 CEST 2020 : INFO:  Current Version: 001024000137
Wed Sep  2 04:05:55 CEST 2020 : INFO:  Latest Version: 001024000171
./netdata-latest.tar.gz: OK
Wed Sep  2 04:05:55 CEST 2020 : INFO:  Re-installing netdata...
/etc/cron.daily/netdata-updater: line 225: ./netdata-installer.sh: Permission denied
Wed Sep  2 04:05:55 CEST 2020 : ERROR:  FAILED TO UPDATE NETDATA : FAILED TO COMPILE/INSTALL NETDATA
`
It started like a week ago.

**Comment by ndsda** [comment]
@prologic Thank you!
https://gist.github.com/ndsda/65787f77095b5df668e63ed3c1f61ac5

**Comment by nguyentuandat** [comment]
I have the same issue here, I am using Ubuntu 18.04.5 LTS

**Comment by prologic** [comment]
@Ferroin I seem to recall a week or so ago you made some changes to how we compute a suitable "temporary directory" in the updater/installer. Please have a look at what you changed, audit it and determine whether it was an appropriate change here, as we seem to have broken pre-existing "working" behaviour for others. Thanks! 🙇‍♂️

**Comment by Ferroin** [comment]
At least one line similar to`/tmp/netdata-test.huHeA0BnbW: Permission denied` is expected if `/tmp` is mounted noexec. It's a side-effect of the code that determines if we can actually use `/tmp` or not (namely, that it's writable and we can run files we write there) because we have to actually try to run a file off of it to reliably determine if we can use it (because there may be permissions beyond the mount options that would prevent it from working, or it might not be a mountpoint).

If you see that line and the installer or updater is trying to use a path under `/tmp` anyway, that's a bug that we need to fix (because it should be falling back to whatever directory it gets run from and use that for storing temporary files instead).

Short term, you should be able to side-step any such issues by running the scripts with the environment variable `TMPDIR` set to a path that allows both writing and executing files.

**Comment by Ferroin** [comment]
I cannot reproduce this locally with the current nightly build of Netdata. Tested on both CentOS 7 and Ubuntu 18.04 with multiple configurations for `/tmp` (tmpfs, separate filesystem on disk, etc).

@ndsda Can you please re-test with the most recent nightly as well and confirm if you're still seeing this or not?

**Comment by ndsda** [comment]
Hi @Ferroin, I can confirm that I still get the same issue.

This week I have installed Netdata successfully on 4 low spec VPS servers, yet I've encountered this problem with the 3 dedicated servers I've tried. All are CentOS 7: centos-release-7-8.2003.0.el7.centos.x86_64

**Comment by cube-dan** [comment]
This worked for me:

where (below):
+ `/tmp/netdata-kickstart-Q30do8Yo21` is the path that kickstart.sh tells you that it's: `Leaving all files in /tmp/netdata-kickstart-Q30do8Yo21` 
+ `{your_user}` is your logged in user

```bash
# copy extracted tmp folder somewhere you "do stuff"
sudo cp -r /tmp/netdata-kickstart-Q30do8Yo21 ~/netdata-kickstart
# give yourself ownership of the files
sudo chown -R {your_user} ~/netdata-kickstart
# enter the kickstart-dir
cd ~/netdata-kickstart
# run the installer script
./netdata-installer.sh
```

**Comment by Redominus** [comment]
The problem with that is the updater. It will break anyway.

**Comment by prologic** [comment]
@Ferroin ☝️

**Comment by cube-dan** [comment]
@Redominus, @prologic, 

In that case guys sorry for the thread jacking. I ran into the error message "the source directory does not include netdata-installer.sh" while trying to do a manual update* and this page was somewhere in the "google knows everything" list. 

Would you guys like me to delete my message from this thread?

PS: 
**using the command `bash <(curl -Ss https://my-netdata.io/kickstart.sh)`

**Comment by Ferroin** [comment]
@cube-dan Even if it doesn't completely fix the issue, it's still a good observation and would let someone having this problem at least install Netdata, even if updates don't work.

In theory we could actually make that behavior automatic (even for the updater). The issue is that it doesn't really solve the problem (namely, thing shouldn't be getting extracted the way they are in these cases).

**Comment by kozicpetar** [comment]
Hi,

just to inform, same "problem" here.
I have production system with installed netdata in February.

Looks like I have latest version and updated don't need to do anything, but first what I can see that is permission error.

```
./netdata-updater.sh
Tue Sep 29 13:09:51 CEST 2020 : INFO:  Running on a terminal - (this script also supports running headless from crontab)
./netdata-updater.sh: line 77: /tmp/netdata-test.ZHSG81CUc6: Permission denied
Tue Sep 29 13:09:52 CEST 2020 : INFO:  Current Version: 001025000000
Tue Sep 29 13:09:52 CEST 2020 : INFO:  Latest Version: 001025000000
Tue Sep 29 13:09:52 CEST 2020 : INFO:  Newest version (current=001025000000 >= latest=001025000000) is already installed
```

**Comment by prologic** [comment]
@kozicpetar I believe your _specific_ problem is quite different:

> `./netdata-updater.sh: line 77: /tmp/netdata-test.ZHSG81CUc6: Permission denied`

This is more related to #9626

**Comment by Ferroin** [comment]
Indeed, @prologic is correct, at least one line like:

```
./netdata-updater.sh: line 77: /tmp/netdata-test.ZHSG81CUc6: Permission denied
```

Is expected if the system has `/tmp` mounted with the `noexec` option. The only way we can reliably test for this is to actually try to run a file there, and we can't reliably suppress the error message this generates, hence this line.

**Comment by Mosney** [comment]
Same issue, I mount /tmp with `noexec` and autoupdater will not work until I remount `exec` manually. Any other way to avoid use /tmp in autoupdate process without set environment variables?

**Comment by OdysLam** [comment]
@Mosney welcome to our community :)

I think at this moment you can not. There is a number of improvements we can do on the installer, but it's not currently on our priority. @Ferroin can provide more insight!

**Comment by Mosney** [comment]
> but it's not currently on our priority.

True, a month pass away since it been reported. 
For those who come after. In conclusion, you can only upgrade netdata manually with an environment variable `TMPDIR` has been set if you don't wanna change `/tmp` mount `noexec `to `exec`.

**Comment by Ferroin** [comment]
It’s not so much that it’s not a priority as it is that we have not been able to consistently reproduce the issue ourselves, which makes it rather difficult to figure out what exactly is going wrong.

**Comment by erselbey** [comment]
> I have the same issue here, I am using Ubuntu 18.04.5 LTS.
> I just finger out that it work with x64
> `bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)`
> 
> Hope this help

I have solved problem. Thank you

**Comment by OdysLam** [comment]
Welcome to our community @erselbey, we are on top of it!

**Comment by Redominus** [comment]
Sorry to inform the error has not been fixed. noexec flag keeps breaking the installer.
Installer output:
`Cannot install netdata from source (the source directory does not include netdata-installer.sh). Leaving all files in /tmp/netdata-kickstart-5A3lNliAvd`
ls command output:
`ls -l /tmp/netdata-kickstart-5A3lNliAvd/netdata-v1.26.0-333-gae04be5a/ | grep installer `
`-rwxrwxr-x  1 2000 2000  66670 dic  8 02:35 netdata-installer.sh`

**Comment by Ferroin** [comment]
Just to clarify, are you saying that if you remount `/tmp` without the `noexec` flag, this does not happen?

**Comment by kozicpetar** [comment]
@Ferroin does it exists some solution without remounting /tmp without noexec because that is hard on WHM servers. In general I think anyone don't  want to remount /tmp on dozen server that can update netdata.
Make sense?

**Comment by Ferroin** [comment]
@kozicpetar You can set `$TMPDIR` for the script to a location that is both writable by the user the script is running as and allows running of executables.

The logic at the moment around the `noexec` thing is:

* If `$TMPDIR` is set, allows writing files, and allows execution, use that path for our temporary files.
* Otherwise, try the same checks on `/tmp` and if they pass use that.
* If both of those fail, try with the current working directory of the script itself.
* If all three fail, refuse to run and spit out an error message indicating that we can’t find a usable temporary directory.

This _should_ be independent of the issue with not being able to find the installer script though.

**Comment by kozicpetar** [comment]
@Ferroin thank you for answer. I understand this.
Where I can found some walk-throught for updating existing installation which they could not auto update in the past one month?

I tried to run but failed:
`bash <(curl -Ss https://my-netdata.io/kickstart.sh) --reinstall --dont-wait --stable-channel`

Thank you !

**Comment by Ferroin** [comment]
> @Ferroin thank you for answer. I understand this.
> Where I can found some walk-throught for updating existing installation which they could not auto update in the past one month?
> 
> I tried to run but failed:
> `bash <(curl -Ss https://my-netdata.io/kickstart.sh) --reinstall --dont-wait --stable-channel`
> 
> Thank you !

If you’re using the stable channel, then there should not have been an update since 2020-10-14 (just short of two months ago). The next stable release should be out within the next two weeks (originally planned for 2020-12-14, possibly delayed due to a criticla bug in the updater).

**Comment by kozicpetar** [comment]
@Ferroin 
Sure, but on servers is netdata update cron which trying to update every day and fails.
Do I need to do some manual step when new stable release?
Thank you.

**Comment by Ferroin** [comment]
By ‘fails’ do you mean it reports that there is no newer version, or that you actually see some failure?

**Comment by kozicpetar** [comment]
@Ferroin 
```
/etc/cron.daily/netdata-updater:

/etc/cron.daily/netdata-updater: line 77: /tmp/netdata-test.280dDS8WIL: Permission denied
Sun Dec  6 03:50:31 CET 2020 : INFO:  Current Version: 001025000000
Sun Dec  6 03:50:31 CET 2020 : INFO:  Latest Version: 001026000000
./netdata-latest.tar.gz: OK
Sun Dec  6 03:50:34 CET 2020 : INFO:  Re-installing netdata...
/etc/cron.daily/netdata-updater: line 225: ./netdata-installer.sh: Permission denied
Sun Dec  6 03:50:34 CET 2020 : ERROR:  FAILED TO UPDATE NETDATA : FAILED TO COMPILE/INSTALL NETDATA
```

**Comment by ndsda** [comment]
I get exactly the same error as I got on 1 Sep.

**Comment by easaw** [comment]
After some trials, I've found a way that seems to work for Ubuntu 20.04

`bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)  --stable-channel --disable-telemetry`
(This assumes you do not want nightly)

rather than
`cd /etc/netdata`
another location might be:
`cd /opt/netdata/usr/sbin/`
then do this:
`sudo chmod +x netdata-claim.sh`

finally, while still in the /sbin directory use
`sudo ./netdata-claim.sh `

OR grab your Claim Command from your War Room's dashboard, for example:
`sudo netdata-claim.sh -token=YOURTOKENHERE -rooms=YOURROOMHERE -url=https://app.netdata.cloud`
(Please: do NOT use the above Claim Command, ensure you get the correct one from your own war room).

Hope that works for you all, Happy New Year! 😄  👍

**Comment by ShaneHutter** [comment]
I think the main issue with the installer executing out of /tmp, is that things should not execute out of /tmp.  Having the noexec flag on the mount is a good move for securing your server.

Why not change the install to always use /usr/src/netdata, and install from a directory where most things do?

**Comment by Ferroin** [comment]
Strictly speaking, no matter _where_ we choose to install from, we still have to potentially deal with noexec or other more complex limitations (such as things possibly imposed by SELinux or other LSMs).

Our choice to use `/tmp` as the default path is a result of a number of factors:

* It ensures on most systems that anything we accidentally leave behind will get cleaned up on the next reboot.
* It’s available on _all_ platforms we support, which means we don’t need to do anything special on a per-platform basis.
* It’s accessible to all users, so non-root installs do not need special handling.
* It actually speeds up the install on a majority of systems because we never touch persistent storage until we actually go to install the files for Netdata.

I agree that we should handle this better, but the number of install scenarios we need to handle make it less than trivial to do so (for example using something under `/usr/src` will not work for non-root users on a vast majority of systems, and may not work on macOS systems (due to system integrity protection)).

**Comment by twkonefal** [comment]
Would it be possible to allow a command-line argument to the installer / updater where the user can set the tmpdir? This may help users tailor the update/install with minimal changes to tmp dir detection.

**Comment by Ferroin** [comment]
Somehow it did not get mentioned here, but the install scripts (and updater) now try to properly respect the value of the `$TMPDIR` variable if it’s present in the environment. if set, they’ll try to use that before falling back through the list of default temporary directories (and if set on install, it will be automatically recorded so that the updater will use the same path as well).

**Comment by godismyjudge95** [comment]
Just wanted to pitch in and say I am having a similar issue on several WHM/cPanel Centos 7 servers I manage.
```
/etc/cron.daily/netdata-updater:

/etc/cron.daily/netdata-updater: line 107: /tmp/netdata-test.x2KeeUAwfu: Permission denied
/etc/cron.daily/netdata-updater: line 107: /tmp/netdata-test.njN0pzBfjF: Permission denied
/etc/cron.daily/netdata-updater: line 207: /tmp/netdata-updater-jvFBTN6bBU/netdata-updater.sh: Permission denied
```

I am currently trying out a fix by setting the env variable `NETDATA_TMPDIR` to the following line in `/opt/netdata/etc/netdata/.environment`:
```
NETDATA_TMPDIR="/root/netdata/tmp"
```

I realize this is not a long term solution, as this environment file might get overwritten by an update at some point, but perhaps there is a more permanent way of setting the variable?
I will write back if it works tonight.

**Comment by kozicpetar** [comment]
Yes, on Centos WHM you need to set and export variable in `~/.bash_profile` file, otherwise will not work.

```
export TMPDIR="/root/netdata/tmp"
```

I have set variable in netdata .env file `/opt/netdata/etc/netdata/.environment` but updater not work if I don't have set in bash profile variable.

**Comment by godismyjudge95** [comment]
> Yes, on Centos WHM you need to set and export variable in `~/.bash_profile` file, otherwise will not work.
> 
> ```
> export TMPDIR="/root/netdata/tmp"
> ```
> 
> I have set variable in netdata .env file `/opt/netdata/etc/netdata/.environment` but updater not work if I don't have set in bash profile variable.

Yeah my method of setting it in the  `/opt/netdata/etc/netdata/.environment` file did not work.  I will try in the `/root/.bash_profile` file to see if that works like you mentioned.  I feel like either way this should be a part of the official installation documentation, so that this unexpected error does not occur without any sort of preface.

**Comment by Ferroin** [comment]
> so that this unexpected error does not occur without any sort of preface.

Ideally, the goal is to not have this error at all, though that’s a bit difficult to achieve given that we’ve still not been able to properly replicate it for testing.

On a side note, I just noticed that it was apparently never mentioned here, but we do have [pre-built binary packages](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/packages) for most of the common distros (including CentOS 7 and 8, though only for 64-bit x86 at the moment) that completely avoid this issue (because they use the system package manager). Long term our plan is to pivot to those as a primary install method when possible (the kickstart script will eventually automate setup of our package repository and install the Netdata agent from there), though that’s probably at least 3-6 months out at this point.

**Comment by cayetanohernandez** [comment]
> Hello @ndsda ,
> 
> It looks like that your `/tmp` is mounted readonly or without exec permission, please, can you run the following command before to start the installation:
> 
> ```
> mount /tmp -o remount,rw
> ```
> 
> as you can see in [this comment](https://github.com/netdata/netdata/issues/9579#issuecomment-665384044) other users already had problems like this and to remount `/tmp` fixed the problem for them.
> 
> Best regards!

It works for me. 

Thanks

**Comment by Ferroin** [comment]
We do still have an issue here in that we don’t reliably handle the install correctly on systems where `/tmp` is mounted with the `noexec` option.

OTOH, we probably should have an entry in the FAQ about handling of the temporary directory and `$TMPDIR` in the install process.

**Comment by Ferroin** [comment]
This should be completely resolved at this point for 99% of users with the release a while back of our completely new kickstart script.

If you are still seeing this issue on an _existing_ install, please comment about it here.

If you are seeing this issue when trying to install on a system for the first time, please open a new issue about that, selecting the ‘Bug’ issue template, and provide detailed info there as requested by the issue template.

**Comment by ndsda** [comment]
I still cannot install Netdata. I now get a different error with the new installer.

https://packagecloud.io/netdata/netdata-edge/el/7/x86_64/repodata/repomd.xml: [Errno -1] Gpg Keys not imported, cannot verify repomd.xml for repo netdata-edge
Trying other mirror.

 One of the configured repositories failed (Netdata Edge)...

**Comment by godismyjudge95** [comment]
> This should be completely resolved at this point for 99% of users with the release a while back of our completely new kickstart script.
> 
> If you are still seeing this issue on an _existing_ install, please comment about it here.
> 
> If you are seeing this issue when trying to install on a system for the first time, please open a new issue about that, selecting the ‘Bug’ issue template, and provide detailed info there as requested by the issue template.

We are on the latest version of Netdata, and we are still having the update issue on CloudLinux OS.  Unfortunately, there is not a package for CloudLinux so we have to use a static build and the static build still relies on the /tmp directory to run the script.  It would be great if we could have an official solution in the docs somewhere on how to resolve this issue.

**Comment by Ferroin** [comment]
@godismyjudge95 Can you create a new issue specifically for that problem with the static build and include the output you see when you run into these issues? It’s (almost certainly) unrelated to the original issue here, but it’s definitely a bug.

**Comment by Ferroin** [comment]
@ndsda  Please see https://github.com/netdata/netdata/issues/12154 for more details on that particular problem.

**Comment by godismyjudge95** [comment]
> @godismyjudge95 Can you create a new issue specifically for that problem with the static build and include the output you see when you run into these issues? It’s (almost certainly) unrelated to the original issue here, but it’s definitely a bug.

So I found that our servers were having two separate issues.
I did have to set the tmp directory because even after uninstalling and re-installing netdata it was still having an issue not being able to execute inside the /tmp directory.
Netdata updates properly after putting the following in the `/root/.bash_profile`:
```
export TMPDIR="/root/tmp"
```

However, there is a 2nd issue which I have opened a new bug report for:
https://github.com/netdata/netdata/issues/12286

I would still really love it if Netdata documented this tmp directory fix somewhere so I don't have to keep this issue bookmarked :)

**Comment by Ferroin** [comment]
@netdata/agent-sre The remaining issue here is that we are, in at least some cases, not properly utilizing a saved value of `$TMPDIR` in the updater (the installation process should persist this in a way that the updater picks up properly, though it is only needed for static installs and local builds).

**Comment by Dim-P** [comment]
@Ferroin Is this still the case or is the updater aware of changes to `$TMPDIR` now?

**Comment by godismyjudge95** [comment]
> @Ferroin Is this still the case or is the updater aware of changes to `$TMPDIR` now?

Based on our server installs it is still an issue that has to be manually fixed.

**Comment by Dim-P** [comment]
> > @Ferroin Is this still the case or is the updater aware of changes to `$TMPDIR` now?
> 
> Based on our server installs it is still an issue that has to be manually fixed.

Thanks for the update @godismyjudge95 .

**Comment by ilyam8** [comment]
If the problem is not resolved, please open a new issue.
