### ISSUE TITLE
metric for monitor service running or not

### ISSUE THREAD

**Issue by hamzash9500** [netdata/netdata#9899]
##### Question summary
please can you provide me with the metric that can monitor the service is running or not?
##### OS / Environment
ubuntu 18
netdata version : v1.23.0

**Comment by thiagoftsm** [comment]
Hi @hamzash9500 ,

Netdata has [apps.plugim](https://learn.netdata.cloud/docs/agent/collectors/apps.plugin) to monitor specific group of software. This plugin has a chart called `apps.uptime` that shows how long an application is running since Netdata restart. I think this is what you are looking for, but if I am wrong, please, let us know.

Best regards!

**Comment by thiagoftsm** [comment]
> Is there a solution to the problem??

In reality this is a feature that we have inside `apps.plugin`. The dimensions are updated and have data only when we are collecting data for it. If you do a request for `http://localhost:19999/api/v1/data?chart=apps.uptime`, you will see that dimensions are not created if the software was never running, or if the software stopped after Netdata to start collect it, it will be shown until the database rotates. Good part of the description I gave to you is processed for the next function

https://github.com/netdata/netdata/blob/3e0661a2afebbe3b40e51740abe468de23e11e41/collectors/apps.plugin/apps_plugin.c#L3632

To start storing `zero` for everything instead do not store data can be considered a new feature for Netdata, because we will have to change our internal design.

A possible simple solution for your case, would be to create [an alarm](https://learn.netdata.cloud/docs/agent/health/reference) inside `/etc/netdata/health.d/`, and this alarm would be triggered every time that you do no have more data for a dimension. For example, let us suppose you are monitoring `Email` server, so you could write something like:

```
alarm : service_not_running
  on  : apps.uptime
  os  : linux
warn  : (($email_last_collected_t - $apps.plugin_last_collected_t) > 0 )
crit  : ($email_last_collected_t = nan) || (($email_last_collected_t - $apps.plugin_last_collected_t) > 10 )
every : 1s
info  : Check if the email services are running
```

You can get the variables available for a char running the query `http://localhost:19999/api/v1/alarm_variables?chart=apps.uptime`. 

Finally the alarm that I gave to you is a simple example and probably it would need to be refined to give a better notification.

Best regards!
