### ISSUE TITLE
How to do if i wanna use collector only?

### ISSUE THREAD

**Issue by oleotiger** [netdata/netdata#9907]
I wanna use collectors in netdata only.

The way is to package collectors up with grpc with python.

My purpose is to collect a certain set of metrics at request with certain frequency.

What should I do?

Where is the entrance?

Any suggestion?

**Comment by thiagoftsm** [comment]
Hi @oleotiger ,

I am not sure if I understood your doubt, but I understood that you wanna get the data that was collected, if this is the case, you will need to use our [api](https://editor.swagger.io/?url=https://raw.githubusercontent.com/netdata/netdata/master/web/api/netdata-swagger.yaml) to request the data you want.

Best regards!

**Comment by oleotiger** [comment]
> Hi @oleotiger ,
> 
> I am not sure if I understood your doubt, but I understood that you wanna get the data that was collected, if this is the case, you will need to use our [api](https://editor.swagger.io/?url=https://raw.githubusercontent.com/netdata/netdata/master/web/api/netdata-swagger.yaml) to request the data you want.
> 
> Best regards!

There still is some difference.

I have read the api. Getting collected data through api is to get data from the database.

Here I wanna get data from the server straightly through calling the collecting method?

Is there any api or may way i can try?

**Comment by thiagoftsm** [comment]
> Here I wanna get data from the server straightly through calling the collecting method?

This is not possible, because the collectors are clients, they cannot be consider as a server.

> Is there any api or may way i can try?

The collectors send data to Netdata using the [collector language](https://learn.netdata.cloud/docs/agent/collectors/plugins.d#external-plugins-api), if you want to run an external collector and send data from it to an external service, this service will need to have a parser for the language. 

You will have more work, if you want to use an internal collector, this means that you will need to change it to send for another server and not only for Netdata. Without any doubt to use the WEB API is the simplest way to get the data.

Let me know if you have any other doubt, and keep in mind the suggestion I gave, the simplest road is to request for Netdata using the WEB API. You can also disable collectors as I already answered you in a previous issue.

Best regards!
