### ISSUE TITLE
What is the Netdata Cloud availability?

### ISSUE THREAD

**Issue by aureliomarcoag** [netdata/netdata#9953]
##### Question summary
Hi! I've looked for this on the documentation, but haven't had any luck.
We loved Netdata Cloud and what it offers, but before using it in production we'd like to know more about it's availability.

In other words, what percentage of our Agents data does Netdata guarantee will reach Netdata Cloud (could we lose part of the data if netdata cloud goes down)?

What about the app.netdata.cloud application, what's the expected availability for this application (the frontend dashboard, rooms, etc.)?

Thanks in advance!

##### OS / Environment
N/A
##### Component Name
Netdata Cloud
##### Expected results
N/A

**Comment by thiagoftsm** [comment]
Hi @aureliomarcoag ,

> In other words, what percentage of our Agents data does Netdata guarantee will reach Netdata Cloud (could we lose part of the data if netdata cloud goes down)?

Any computer running Netdata [1.22 or higher](https://learn.netdata.cloud/docs/cloud/get-started#before-you-start) can work with the cloud.

If you are running Netdata with `memory mode = dbengine`, you will never lose data, because they are stored direct on your machine. When Netdata is connected with the cloud, you continue storing data locally, unless memory mode is set to `ram`.

> What about the app.netdata.cloud application, what's the expected availability for this application (the frontend dashboard, rooms, etc.)?

This is service that runs 24 x 7 and it will always receives update in different areas. 

Best regards!

**Comment by Ferroin** [comment]
WRT Netdata Cloud, we currently do not have any SLAs for the application itself (either the frontend web app or the backend that handles routing of the data from the agents).

Currently though we have had a relatively good track record in terms of downtime (we've only had a few major service disruptions since launch, and the only big one recently was a mostly planned instance earlier this week when we were upgrading the underlying infrastructure to patch a security issue), and I personally (as someone on the SRE/infra team) only expect this to get better as time goes on.

---

As far as data retention goes, @thiagoftsm is correct. All the data is stored locally on the individual nodes and only retrieved by the cloud when the user tells it to. This has three side effects that may or may not matter for your usage:

* Netdata Cloud can only show you data from systems that are online (we are working on alerting functionality from the cloud to send notifications when an agent goes offline though).
* Because the data is retrieved in real time, actual bandwidth usage is very low when you're not actively accessing Netdata Cloud.
* You functionally cannot directly use nodes with Netdata configured to not store anything locally (`memory mode = none`) with Netdata Cloud, and nodes that are configured to only store data until Netdata restarts (`memory mode = ram`) will also only be able to show data since the last restart even in Netdata Cloud.

**Comment by aureliomarcoag** [comment]
Thank you for the clarifications, much appreciated! @Ferroin @thiagoftsm

**Comment by OdysLam** [comment]
Hey @aureliomarcoag, 

Welcome to our community. If you want to discuss further about Netdata Cloud, you should definitely join our forums at https://community.netdata.cloud
