### ISSUE TITLE
apps_groups plugin takes a while to show the rigth number of processes

### ISSUE THREAD

**Issue by mbarper** [netdata/netdata#9979]
##### Question summary
When running a systemd service which calls a bash scritp to run a JAVA process I should get a number of processes equal to 2, the java process and its parent, the bash script process. apps.processes metric shows only 1 process and after some time (even hours) it updates to 2 processes.

What could be the problem or the behabior of the plugin that makes the number of processes doesn't update inmediatly?

##### OS / Environment
ubuntu 18

##### Component Name
apps_groups plugin

##### Expected results
Show the total number of processes involved in the apps_groups.conf definition.

**Comment by thiagoftsm** [comment]
Hi @mbarper ,

Reading your description, I think the `apps_groups.conf` has a different name for the process, or it is trying to match an exact pattern that it cannot find inside `/proc`, how did you define the group you want to monitor inside `apps_groups.conf`?

Best regards!

**Comment by mbarper** [comment]
Hi,

I have configured the process like this:

`myprocess: '*java blablabla*'
`

this JAVA process is launched by its father, a bash script inside a systemctl service, and it is launched almost inmediatly, so both processes are running.

At start of the systemctl service Netdata shows 1 process and after some time, couple of hours it shows 2 processes. It is weird and I don't find anything in the C code that makes this behavior, but I'm not a C guy so maybe I'm missing something.

**Comment by thiagoftsm** [comment]
Hi @mbarper ,

Firstly I apologize the delay, but I had a busy week.

I tested a scenario like yours and I think I discover a possible problem. 

## Scenario with problems

1 - I created the following entry inside my `apps_groups.conf`:

```
testing: *java blablabla*
```

2 - After this I created two shell scripts, the first I named `myprocess.java` and it initially had the following content:

```
#!/bin/bash

sh ~/blablabla.sh

for i in `seq 1 1000000` ; do
    echo $i > /dev/null
    sleep 1
done
```

3 - I created another shell script called `blablabla.sh` with the following content:

```
#!/bin/bash

for i in `seq 1 1000000` ; do
    echo "Testing" > /dev/null
    sleep 1
done
```

4 - I started Netdata
5 - On other terminal I called the first script running `sh myprocess.java`

On this scenario I replicated the exact same problem that you report. 

## Scenario that works

What I observed, Netdata was not able to match correctly the process name, because the strings that it was searching inside `cat /proc/PID/cmdline` or `/proc/1111/status` could not be matched. This is happening, because we are using simple patterns to define position that we compare strings:

https://github.com/netdata/netdata/blob/537a8135cfaf03efb6c9c800185d9bfbba076cc1/collectors/apps.plugin/apps_plugin.c#L1102

I got a solution for the problem doing small changes on my configuration:

1 - I changed my `apps_groups.conf` to :

```
testing: *.java blablabla*
```

As you can see I added a dot for the extension. This was enough to detect the java without problems.

2 - I changed my `myprocess.java` to : 

```
#!/bin/bash

export PATH=$PATH:/home/thiago
blablabla.sh

for i in `seq 1 1000000` ; do
    echo $i > /dev/null
    sleep 1
done
```

Thanks the fact that I can call directly `blablabla.sh` instead to use `sh ~/blablabla.sh`, it began to be detected.

3 - Finally I executed Netdata and I called again my shell script.

Best regards!
